### PR TITLE
Don't split an exported class when renaming an inner binding

### LINKED ISSUE #7843: Class property transform fails with "We don't know what to do with this node type"
This is a bug report

### Input Code

The following code produces an error:
```js
export class Test {
  static staticProp = {};
  constructor(props) {
    console.log(props);
  }
  log = (props) => {
    console.log(props.msg);
  };
}
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    ["@babel/stage-1", { "decoratorsLegacy": true }]
  ]
}

```

### Expected Behavior

Babel should successfully compile the code. Works with babel 6 in the REPL: https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=usage&code_lz=KYDwDg9gTgLgBAYwDYEMDOa4BVhvgbwCg448UYBLBUmcqgBSgjDgF458BfAbmMQgB2eKAFcEMaAAowTMGgCUHPiQSC0EJMAB0SCAHNpshbxKc-uvWziHmCtgD4lJFWo3aLNuVoC2aPfJM4HkJOIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=false&presets=stage-1&prettier=false&targets=&version=6.26.0&envVersion=1.6.2

### Current Behavior

Babel fails to compile with the following error:
```
Error: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?
    at NodePath.insertAfter (/path/to/project/node_modules/@babel/traverse/lib/path/modification.js:154:11)
    at PluginPass.Class (/path/to/project/node_modules/@babel/plugin-proposal-class-properties/lib/index.js:267:14)
    at newFn (/path/to/project/node_modules/@babel/traverse/lib/visitors.js:243:21)
    at NodePath._call (/path/to/project/node_modules/@babel/traverse/lib/path/context.js:65:18)
    at NodePath.call (/path/to/project/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/path/to/project/node_modules/@babel/traverse/lib/path/context.js:100:12)
    at TraversalContext.visitQueue (/path/to/project/node_modules/@babel/traverse/lib/context.js:144:16)
    at TraversalContext.visitSingle (/path/to/project/node_modules/@babel/traverse/lib/context.js:104:19)
    at TraversalContext.visit (/path/to/project/node_modules/@babel/traverse/lib/context.js:185:19)
    at Function.traverse.node (/path/to/project/node_modules/@babel/traverse/lib/index.js:106:17)
```

### Possible Solution

Not sure, but it's interesting that either of the following adjustments can be used to work around the issue:
```diff
// Use different identifiers for constructor arg and `log` arg
export class Test {
  static staticProp = {};
  constructor(props) {
    console.log(props);
  }
- log = (props) => {
+ log = (p) => {
-   console.log(props.msg);
+   console.log(p.msg);
  };
}
```

```diff
// Export the class separate from its declaration
-export class Test {
+class Test {
  static staticProp = {};
  constructor(props) {
    console.log(props);
  }
  log = (props) => {
    console.log(props.msg);
  };
}
+
+export { Test };
```

### Context

Trying to use what I _think_ is compliant with the current proposals, but have to follow one of the provided workarounds instead.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            | 7.0.0-beta.46 
| Babylon          | 
| node             | 8.6.0
| npm              | yarn 1.5.1
| Operating System | mac OS

### LINKED ISSUE #7951: "We don't know what to do with this node type" error using @babel/plugin-proposal-class-properties
## Bug Report

**Current Behavior**
Error using `@babel/plugin-proposal-class-properties`:

```
Error: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?
    at NodePath.insertBefore (/node_modules/@babel/traverse/lib/path/modification.js:55:11)
    at PluginPass.Class (/node_modules/@babel/plugin-proposal-class-properties/lib/index.js:257:14)
    at newFn (/node_modules/@babel/traverse/lib/visitors.js:237:21)
    at NodePath._call (/node_modules/@babel/traverse/lib/path/context.js:65:20)
    at NodePath.call (/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/node_modules/@babel/traverse/lib/path/context.js:100:12)
    at TraversalContext.visitQueue (/node_modules/@babel/traverse/lib/context.js:142:16)
    at TraversalContext.visitSingle (/node_modules/@babel/traverse/lib/context.js:102:19)
    at TraversalContext.visit (/node_modules/@babel/traverse/lib/context.js:182:19)
    at Function.traverse.node (/node_modules/@babel/traverse/lib/index.js:106:17)
```

**Input Code**

Repo: https://github.com/xcrzx/babel-class-properties

```js
export default class Foo extends Bar {
    static foo = {};

    test = (...args) => {
        console.log(...args);
    };
}
```
The error appears only if I have `static foo = {};`, `export default`, `extends Bar` and `(...args)` all together.

**Babel Configuration (.babelrc, package.json, cli command)**

babel.config.js:
```js
module.exports = {
  plugins: ['@babel/plugin-proposal-class-properties'],
};
```

**Environment**
- Babel version(s): [v7.0.0-beta.47]
- Node/npm version: [Node 9.11.1/npm 6.0.0]
- OS: [OSX 10.13.4]
- Monorepo [no]
- How you are using Babel: [`cli`, `loader`]

**Additional context/Screenshots**
The error appeared when I upgraded babel packages from v7.0.0-beta.44 to v7.0.0-beta.47.

### LINKED ISSUE #8033: Error: We don't know what to do with this node type...
## Bug Report

**Current Behavior**
Error while compile:
```
$ babel index.js
Error: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?
    at NodePath.insertBefore (C:\workspace\babel-bug-report\node_modules\@babel\traverse\lib\path\modification.js:55:11)
    at PluginPass.Class (C:\workspace\babel-bug-report\node_modules\@babel\plugin-proposal-class-properties\lib\index.js:257:14)
    at newFn (C:\workspace\babel-bug-report\node_modules\@babel\traverse\lib\visitors.js:237:21)
    at NodePath._call (C:\workspace\babel-bug-report\node_modules\@babel\traverse\lib\path\context.js:65:20)
    at NodePath.call (C:\workspace\babel-bug-report\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (C:\workspace\babel-bug-report\node_modules\@babel\traverse\lib\path\context.js:100:12)
    at TraversalContext.visitQueue (C:\workspace\babel-bug-report\node_modules\@babel\traverse\lib\context.js:142:16)
    at TraversalContext.visitSingle (C:\workspace\babel-bug-report\node_modules\@babel\traverse\lib\context.js:102:19)
    at TraversalContext.visit (C:\workspace\babel-bug-report\node_modules\@babel\traverse\lib\context.js:182:19)
    at Function.traverse.node (C:\workspace\babel-bug-report\node_modules\@babel\traverse\lib\index.js:106:17)
```

**Input Code**
Repo: https://github.com/tihonove/babel-bug-report

```js
export class Foo {
    static bar = {};
    constructor(b) {}
    foo = b => b;
}
```

**Babel Configuration (.babelrc, package.json, cli command)**

.babelrc:
```js
{
    "presets": [
        "@babel/es2015"
    ],
    "plugins": [
        "@babel/proposal-class-properties"
    ]
}
```

command:
```
yarn babel index.js
```

**Environment**
- Babel version(s): v7.0.0-beta.47
- Node/npm version: v8.6.0/5.3.0
- OS: Windows 10
- Monorepo: yes
- How you are using Babel: cli or loader

### LINKED ISSUE #8062: babel 7 b45+ errors out on class properties
## Bug Report

**Current Behavior**
```
    throw new Error("We don't know what to do with this node type. " + "We were previously a Statement but we can't fit in here?");
    ^

Error: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?
    at NodePath.insertBefore (node_modules/@babel/traverse/lib/path/modification.js:57:11)
    at PluginPass.Class (node_modules/@babel/plugin-proposal-class-properties/lib/index.js:475:14)
    at newFn (node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (node_modules/@babel/traverse/lib/index.js:94:17)
```

**Input Code**

```js
import React from "react";

export class App extends React.Component {
  constructor(props) { super(props); }
  f = () => { const { props } = this; }
  static g = () => null;

  render() { return null; }
}
```

**Expected behavior/code**
Errors out in babel 7 b45+, works in babel 77 b44.
Also, babel is very preculiar when repoing this error.  if you try to change the code a little bit more, eg removing f or g, removing export call, remove constructor or contents of f etc etc the error probably  goes away.

**Babel Configuration (.babelrc, package.json, cli command)**
./node_modules/.bin/babel-node src/index.js 

```js
"@babel/core": "7.0.0-beta.49",
    "@babel/preset-env": "7.0.0-beta.49",
    "@babel/preset-react": "7.0.0-beta.49",
    "@babel/node": "7.0.0-beta.49",
    "@babel/runtime": "7.0.0-beta.49",
```
```
{
  "presets": [
    "@babel/env",
    "@babel/preset-react",
  ],
  "plugins": ["@babel/plugin-proposal-class-properties"]
}
```
**Environment**
- Babel version(s): v7.0.0-beta.49
- Node/npm version:  Node 8.9.3/npm 6
- OS:  OSX 10.13.4
- Monorepo no
- How you are using Babel: cli

**Possible Solution**

**Additional context/Screenshots**
works in babel 7 b44

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #8062, Fixes #8033, Fixes #7951, Fixes #7843
| Patch: Bug Fix?          | :+1: 
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR         | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

File: packages/babel-plugin-proposal-class-properties/test/fixtures/regression/7951/output.mjs [hunk 1]
```diff
@@ -0,0 +1,9 @@
+export class Foo extends Bar {
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-proposal-class-properties/test/fixtures/regression/7951/output.mjs]: The problem was that when `...args` was renamed to `...args2`, this export declaration was split.
For some reason `classPath.parentPath` was set to `classPath` instead of `programPath`. I'll investigate it, but this PR "workarounds" the problem by only splitting the export declaration when necessary.

**Comment by loganfsmyth** [comment]
@nicolo-ribaudo I added a bunch more issues to your "Fixed issues" list. Could you look them over and make sure they are the same problem, and see if there are any other tests cases we should add?

**Comment by nicolo-ribaudo** [comment]
#7281 and #7177 (which use decorators) still don't work.
Do you have any suggestion for additional tests? All those issues use almost the same code.

**Comment by hzoo** [comment]
Should we land this in the meantime?
