### PR TITLE
Inline `@babel/highlight` in `@babel/code-frame`

### LINKED ISSUE #11605: standalone is missing polyfills in ES5 environment
## Bug Report
I'm trying to run https://unpkg.com/@babel/standalone@7.9.6/babel.js in ES5 browser (Opera 12.18), but it's missing some polyfills. Looks like reoccurring #7607. Here are some of the problematic places:

Symbol
https://github.com/babel/babel/blob/df819a060c05a53d0e62f12985892e63d0e22f9a/packages/babel-types/src/constants/index.js#L67

Set
https://github.com/babel/babel/blob/e39b508030a9f696584d21b0eb9677498e3ca231/packages/babel-helper-validator-identifier/src/keyword.js#L54

Object.assign
https://github.com/babel/babel/blob/698fe8ef503fc2f317b814e5e20e5fe492f7e07b/packages/babel-types/src/definitions/core.js#L156
Looks like `fields: Object.assign({` in the babel.js.

WeakMap
https://github.com/babel/babel/blob/f6c7bf36cec81baaba8c37e572985bb59ca334b1/packages/babel-traverse/src/cache.js#L1

WeakSet
https://github.com/babel/babel/blob/f6c7bf36cec81baaba8c37e572985bb59ca334b1/packages/babel-traverse/src/path/introspection.js#L368

Map
Relevant code gets imported from ansi-styles from chalk. #9162

Object.setPrototypeOf
Chalk again.

### LINKED ISSUE #12442: @babel/highlight should evaluate if color should be forced each time highlight is called
## Bug Report

`@babel/highlight` should evaluate if color should be forced each time the `highlight` function is called, instead of only once when the module is loaded.

**Current behavior**

`@babel/highlight` evaluates if color should be forced once; when the module is loaded. Changing the value of `process.env.FORCE_COLOR` at runtime has no effect on `@babel/code-frame` output.

**Expected behavior**

`@babel/highlight` should evaluate if color should be forced each time the `highlight` function is called. Changing the value of `process.env.FORCE_COLOR` at runtime should have an effect on `@babel/code-frame` output.

**Environment**

- `@babel/highlight`: 7.10.4
- `@babel/code-frame`: 7.10.4
- Node: 15.3.0 
- npm: 7.0.14
- OS: macOS 11.0.1

**Possible Solution**

The problem is that a static `supportsColor` value that `chalk` defines once when the module loads is used here:

https://github.com/babel/babel/blob/c6aea4e85d2b8f3e82575642d30b01c8cbe112a9/packages/babel-highlight/src/index.js#L98-L103

`chalk` uses `supports-color` to determine this value, here:

https://github.com/chalk/chalk/blob/02abeebac3fa41b346ad1f0b4674d371953da932/source/index.js#L3

`supports-color` exports a [`supportsColor`](https://github.com/chalk/supports-color#requiresupports-colorsupportscolorstream-options) function so this value could be determined on demand, using:

```js
require('supports-color').supportsColor(process.stdout);
```

**Additional context**

In a published package I author, I’m trying to do snapshot testing of the error messages a function throws that contains fancy colorized syntax highlighting, etc. using `@babel/code-frame`, which in turn uses `@babel/highlight` under the hood. The problem is, when I run `npm test` locally in a terminal the snapshot contains colors, but in GitHub actions CI the snapshots fail because there are no colors.

Typically in a situation like this before each snapshot test runs you could store the current `process.env.FORCE_COLOR` value, set it to `1`, run the snapshot test with color forced, then afterwards restore the `process.env.FORCE_COLOR` value back to what it was.

Unfortunately due to this issue, changing `process.env.FORCE_COLOR` at runtime makes no difference when the 
`@babel/code-frame` function `codeFrameColumns` is called, in turn calling the `@babel/highlight` function `highlight`.

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #12442, fixes #11605 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | https://github.com/babel/website/pull/2995
| Any Dependency Changes?  |
| License                  | MIT

`@babel/highlight` is only used in one of our packages: `@babel/code-frame`. I thus checked on npm, and noticed that it also has very few dependents in the wider ecosystem: just 40 :) https://www.npmjs.com/browse/depended/@babel/highlight

I manually checked how it is used in packages that have been updated in the last year, and there are only two packages with usage of `@babel/highlight` that makes sense: one is https://github.com/facebook/flow/blob/2dc7cec37d7aa97f84640248d272ca38d982158e/packages/flow-upgrade/testUtils/codemodTestUtils.js#L15 (for which `@babel/code-frame` would also be ok, given that it's just to make test output more readable) and one is https://github.com/suchipi/at-js.
It's not enough usage for us to justify maintaining it as a standalone package. ~If anybody asks for it, we can export a `highlight` function from `@babel/code-frame`.~ We now export a `highlight` function from `@babel/code-frame`.

Merging `@babel/highlight` into `@babel/code-frame` means that we can fully remove the `chalk` dependency, which is unused (but exposed as-is in the `@babel/highlight` API through `getChalk()`) and alone makes 60% of `@babel/code-frame`'s size. :tada:

I will add `@babel/highlight` to the archive once this PR is merged.

### CODE REVIEW

File: packages/babel-code-frame/src/index.ts [hunk 1]
```diff
@@ -1,26 +1,5 @@
...
-let pcWithForcedColor: Colors = undefined;
-function getColors(forceColor: boolean) {
-  if (forceColor) {
-    pcWithForcedColor ??= createColors(true);
-    return pcWithForcedColor;
-  }
-  return colors;
-}
+import { getDefs, isColorSupported } from "./defs.ts";
+import { highlight } from "./highlight.ts";
```
Comment (JLHwung) [inline packages/babel-code-frame/src/index.ts:2]: Can we also export the `highlight` function? So that for `@babel/highlight` users, the can migrate to the `highlight` imported from `@babel/code-frame` when upgrading to Babel 8.

**Review by liuxingbaoyu — APPROVED** [review]

File: Gulpfile.mjs [hunk 2]
```diff
@@ -521,7 +521,7 @@ function buildRollup(packages, buildStandalone) {
             // We have manually applied commonjs-esm interop to the source
             // for library not in this monorepo
             // https://github.com/babel/babel/pull/12795
-            if (!id.startsWith("@babel/")) return "compat";
+            if (!id.startsWith("@babel/")) return "default";
```
Comment (JLHwung) [inline Gulpfile.mjs:524]: Could you briefly explain why archived syntax plugins are using `compat` while other dependencies are using `default`? Intuitively we should apply the same interop for everything not in the monorepo.

**Review by JLHwung — APPROVED** [review]

File: Gulpfile.mjs (hunk 2 above)
Comment (nicolo-ribaudo) [reply Gulpfile.mjs:524]: Docs: https://rollupjs.org/configuration-options/#output-interop

`default` matches what Node.js does, so it's what we should use for external packages. For syntax plugins it doesn't really matter, because they all have `.default` and `.__esModule` so the `compat` and `default` work the same. But yeah, lets use `default` everywhere.
