### PR TITLE
fix: `declare class` in namespace should be removed

### LINKED ISSUE #14773: [Bug]: Babel should not add assignment operations when using namespace + declare class
### 💻

- [x] Would you like to work on a fix?

### How are you using Babel?

@babel/register or @babel/node

### Input code
```
export namespace MyNamespace{
  export declare class MyClass {
  }
}

const AffiliateSelectionService = MyNamespace.MyClass;
```

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

babel: https://babeljs.io/repl/#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=usage&corejs=3.6&spec=true&loose=true&code_lz=KYDwDg9gTgLgBAOwIYFtgGcxIMbDgWQE8A5VDLXAbwCg45RJY4ATYbAGySjw6XXQKEAwp35wadAL7Vp1bBATp4REXwEBeQaTSYcwAHQrR6ANxA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ctypescript&prettier=true&targets=&version=7.18.9&externalPlugins=&assumptions=%7B%7D
```
// Babel output
(function (_MyNamespace) {
  _MyNamespace.MyClass = MyClass;
})(MyNamespace || (exports.MyNamespace = MyNamespace = {}));
```

typescript: https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAOwIYFtgGcxIMbDgWQE8A5VDLXAbwCg45RJY4ATYbAGySjw6XXQKEAwp35wadAL7Vp1atggJ08IiL4CAvINJpMOYADpVo9AG4gA
```
// Typescript output
(function (MyNamespace) {
})(MyNamespace || (MyNamespace = {}));
```

### Environment

  - System:
    OS: macOS 10.15.7
  - Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yimingjfe**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #14773 
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

For a concrete example, please see [Issue](https://github.com/babel/babel/issues/14773), Declare class in namespace should not be assigned as a value after compilation. 

Currently, babel-plugin-transform-typescript does not consider ClassDeclaration as a pure type.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14774"></a>

### CODE REVIEW

File: packages/babel-plugin-transform-typescript/src/namespace.ts [hunk 1]
```diff
@@ -185,6 +185,13 @@ function handleNested(
...
       case "FunctionDeclaration":
       case "ClassDeclaration": {
+        if (
+          subNode.declaration.type === "ClassDeclaration" &&
+          subNode.declaration.declare
+        ) {
+          continue;
+        }
+
         const itemName = subNode.declaration.id.name;
```
Comment (liuxingbaoyu) [inline packages/babel-plugin-transform-typescript/src/namespace.ts:195]: `subNode.declaration.type === "ClassDeclaration"` seems to be a duplicate.

File: packages/babel-plugin-transform-typescript/src/namespace.ts [hunk 2]
```diff
@@ -185,6 +185,13 @@ function handleNested(
       case "TSEnumDeclaration":
       case "FunctionDeclaration":
       case "ClassDeclaration": {
+        if (
+          subNode.declaration.type === "ClassDeclaration" &&
+          subNode.declaration.declare
+        ) {
+          continue;
+        }
+
```
Comment (liuxingbaoyu) [inline packages/babel-plugin-transform-typescript/src/namespace.ts:194]: `subNode.declaration.type === "ClassDeclaration"` seems to be a duplicate.

Comment (yimingjfe) [reply packages/babel-plugin-transform-typescript/src/namespace.ts]: This is not necessary, you are right.

**Review by liuxingbaoyu — APPROVED** [review]

**Review by nicolo-ribaudo — COMMENTED** [review]
Thank you! Can you update the test to also cover enums, functions, and variables?

**Comment by yimingjfe** [comment]
> Thank you! Can you update the test to also cover enums, functions, and variables?

Ok,I’d like to do it.

**Review by nicolo-ribaudo — APPROVED** [review]
Thanks!
