### PR TITLE
fix: Edge cases for async functions and `noNewArrow` assumption

### LINKED ISSUE #15170: [Bug]: (Crash) Async arrow function with same parameter name under noNewArrow assumption
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
x = async x => 0 ;
```

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

`input.js` is terminated normally:
```console
$ node input.js # no error
```
but under `noNewArrow` assumption, Babel fails to transpile `input.js`:

By the way, when I used variable declaration instead of assignment expression, (`var x = async x => 0`)  the transpilation terminates normally.

### Environment

- Babel version: 7.19.1
- Node: v18.11.0
- npm version: 8.19.2
- OS: macos 12.4

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #15170 
| Patch: Bug Fix?          | √
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | √
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15181"></a>

### CODE REVIEW

**Comment by JLHwung** [comment]
The PR is marked as a regression fix. Can you pinpoint which version it was introduced in?

**Comment by liuxingbaoyu** [comment]
https://github.com/babel/babel/pull/14752
This one, though I think it could be a very extreme example.
`let x = async x => 0 ;` There is no exception.

**Comment by liuxingbaoyu** [comment]
Also current repl cannot set assumption to `false`, fixed in https://github.com/babel/website/pull/2701.

**Review by JLHwung — APPROVED** [review]

File: packages/babel-helper-wrap-function/src/index.ts [hunk 1]
```diff
@@ -89,37 +90,50 @@ function classOrObjectMethod(
...
+    | t.FunctionExpression
+    | t.CallExpression
+    | t.ArrowFunctionExpression
+  > = inPath;
   let node;
-  if (path.isArrowFunctionExpression()) {
+  let functionId = null;
+  const nodeParams = inPath.node.params;
+
+  if (inPath.isArrowFunctionExpression()) {
```
Comment (nicolo-ribaudo) [inline packages/babel-helper-wrap-function/src/index.ts:108]: Can we always use `path` instead of `inPath` (i.e. only use `inPath` for the original `let path = inPath` declaration)? I was initially confused about what's the difference between the two variables, before realizing that it's just because `path` can later become a `CallExpression` but we only want to allow functions as parameters.

**Review by nicolo-ribaudo — APPROVED** [review]
