### PR TITLE
Evaluate object and initializer when setting a private method

### LINKED ISSUE #12705: Right-hand side expression is not evaluated on assignment to private method
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

- [REPL](https://babeljs.io/en/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEDC0G8BQ1XQMQCMwCcAUAlIgL4poBmA9pYYmWmgC4AWAlhAHRa7QC80wSgDsIlEAFMOISgHM8AIgjNKAVxAATaNJnQW7Xc3FCDOSgHd5BANz1opUkiHizcQhyo1rQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.12.12&externalPlugins=%40babel%2Fplugin-proposal-private-methods%407.12.1%2C%40babel%2Fplugin-proposal-class-properties%407.12.1)

Transpiled code doesn't evaluate right-hand side expression before throwing a `TypeError` when assigning to private methods.

**Input Code**

```js
class C {
    #bar() {}
    foo() {
        this.#bar = console.log("should log this then throw");
    }
}

new C().foo();
```

**Expected behavior**

`new C().foo();` should log `"should log this then throw"` and then throw.

- Example from Google Chrome Version 90.0.4399.0 Canary:
    ```
    VM112:4 should log this then throw
    VM112:4 Uncaught TypeError: Private method '#bar' is not writable
        at C.foo (<anonymous>:4:19)
        at <anonymous>:8:9
    ```

**Babel Configuration:** See the REPL link

**Environment**

- Babel version(s): v7.12.12
- Node/npm version: 10.13
- OS: Using REPL
- Monorepo: Using REPL
- How you are using Babel: Using REPL

**Possible Solution**

We can transform the right-hand side expression and pass it as an argument to `_classPrivateMethodSet` so that it's evaluated before the function call.

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #12705 
| Patch: Bug Fix?          | Y
| Tests Added + Pass?      | Yes
| License                  | MIT

Pass down `value` to the argument of `classPrivateMethodSet` so it will always be evaluated before a runtime error is thrown.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/12707"></a>

### CODE REVIEW

File: packages/babel-helper-create-class-features-plugin/src/fields.js [hunk 1]
```diff
@@ -294,7 +294,9 @@ const privateNameHandlerSpec = {
           value,
         ]);
       }
-      return t.callExpression(file.addHelper("classPrivateMethodSet"), []);
+      // Although classPrivateMethodSet accepts no arguments and throws runtime
+      // error, `value` should always be evaluated
+      return t.callExpression(file.addHelper("classPrivateMethodSet"), [value]);
```
Comment (JLHwung) [inline packages/babel-helper-create-class-features-plugin/src/fields.js:299]: Although we could further optimize the output, e.g. only plug in `value` if it is _not_ static. But I don't think it worths the efforts since a runtime error will be always thrown later.

File: packages/babel-plugin-proposal-private-methods/test/fixtures/private-method/reassignment/output.js [hunk 2]
```diff
@@ -0,0 +1,16 @@
+var counter = 0;
+
+var _privateMethod = new WeakSet();
+
+class Foo {
+  constructor() {
+    _privateMethod.add(this);
+
+    babelHelpers.classPrivateMethodSet(++counter);
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-proposal-private-methods/test/fixtures/private-method/reassignment/output.js:9]: Since `classPrivateMethodSet` doesn't take any parameter, I'd prefer to transform this to `++counter, babelHelpers.classPrivateMethodSet()`.

Comment (JLHwung) [reply packages/babel-plugin-proposal-private-methods/test/fixtures/private-method/reassignment/output.js:9]: Actually I thought about that for a while, but the sequence expression comes at 1 byte more.

File: packages/babel-plugin-proposal-private-methods/test/fixtures/private-method-loose/reassignment/output.js [hunk 3]
```diff
@@ -0,0 +1,17 @@
+var counter = 0;
+
+var _privateMethod = babelHelpers.classPrivateFieldLooseKey("privateMethod");
+
+class Foo {
+  constructor() {
+    Object.defineProperty(this, _privateMethod, {
+      value: _privateMethod2
+    });
+    babelHelpers.classPrivateFieldLooseBase(this, _privateMethod)[_privateMethod] = ++counter;
```
Comment (jridgewell) [inline packages/babel-plugin-proposal-private-methods/test/fixtures/private-method-loose/reassignment/output.js:10]: Per https://github.com/tc39/ecma262/issues/1224, which got consensus at this meeting, I believe this is still incorrect. Even if `this` isn't an instance of `Foo`, we need to evaluate `++counter`:

1. Evaluate object
2. Evaluate key (which is a noop here, only computed props can have a evaluated key)
3. Evaluate RHS
4. Perform set

**Review by jridgewell — APPROVED** [review]

File: packages/babel-plugin-proposal-private-methods/test/fixtures/private-method-loose/reassignment/output.js (hunk 3 above)
Comment (nicolo-ribaudo) [reply packages/babel-plugin-proposal-private-methods/test/fixtures/private-method-loose/reassignment/output.js:10]: Well, this is loose mode :shrug:

Comment (jridgewell) [reply packages/babel-plugin-proposal-private-methods/test/fixtures/private-method-loose/reassignment/output.js:10]: Ha, I didn't see the `loose`. 👍

**Review by jridgewell — COMMENTED** [review]
Can we add a test case for an accessor without a `set`?

File: packages/babel-plugin-proposal-private-methods/test/fixtures/private-method-loose/reassignment/output.js (hunk 3 above)
Comment (JLHwung) [reply packages/babel-plugin-proposal-private-methods/test/fixtures/private-method-loose/reassignment/output.js:10]: Has it been covered in assumptions?

File: packages/babel-plugin-proposal-private-methods/test/fixtures/private-method/reassignment/output.js (hunk 2 above)
Comment (ExE-Boss) [reply packages/babel-plugin-proposal-private-methods/test/fixtures/private-method/reassignment/output.js:9]: It’s 2 bytes if you include the space.

**Comment by nicolo-ribaudo** [comment]
@JLHwung Could you rebase this? :pray:

File: packages/babel-plugin-proposal-private-methods/test/fixtures/accessors/set-only-getter/output.js [hunk 4]
```diff
@@ -14,7 +14,7 @@ class Cl {
       value: 0
     });
 
-    babelHelpers.readOnlyError("#privateFieldValue");
+    this, 1, babelHelpers.readOnlyError("#privateFieldValue");
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-proposal-private-methods/test/fixtures/accessors/set-only-getter/output.js:17]: This is a few more unnecessary bytes, but this path will always result in an error so it's highly improbable that it will happen in production code.

**Review by nicolo-ribaudo — APPROVED** [review]

**Review by nicolo-ribaudo — APPROVED** [review]

**Comment by nicolo-ribaudo** [comment]
Rewrite the title to keep it short enough while still adding info about the last two commits.
