### PR TITLE
fix(register): skip hook for ignored files

### LINKED ISSUE #17903: @babel/register interefers with Node built-in type stripping for ignored files
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/register or @babel/node

### Input code

**`a.js`**

```js
require("@babel/register")({
  extensions: [".ts"],
  ignore: ["./b.ts"],
  presets: ["@babel/preset-typescript"],
});
require("./b.ts");
```

**`b.ts`**

```ts
let n: number;
```

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

I want to use `@babel/register` for only some of my TypeScript files and use Node’s [built-in type stripping](https://nodejs.org/api/typescript.html#type-stripping) for others, as configured by [`ignore`](https://babeljs.io/docs/options#ignore) or [`only`](https://babeljs.io/docs/options#only). But it doesn’t work: Babel disables Node’s built-in type stripping for ignored files.

```console
$ node a.js
/tmp/test/b.ts:1
let n: number;
     ^

SyntaxError: Unexpected token ':'
    at wrapSafe (node:internal/modules/cjs/loader:1743:18)
    at Module._compile (node:internal/modules/cjs/loader:1786:20)
    at Module._compile (/tmp/test/node_modules/pirates/lib/index.js:129:24)
    at node:internal/modules/cjs/loader:1943:10
    at Object.newLoader [as .ts] (/tmp/test/node_modules/pirates/lib/index.js:134:7)
    at Module.load (node:internal/modules/cjs/loader:1533:32)
    at Module._load (node:internal/modules/cjs/loader:1335:12)
    at wrapModuleLoad (node:internal/modules/cjs/loader:255:19)
    at Module.require (node:internal/modules/cjs/loader:1556:12)
    at require (node:internal/modules/helpers:152:16)
    at Object.<anonymous> (/tmp/test/a.js:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1812:14)
    at Object..js (node:internal/modules/cjs/loader:1943:10)
    at Module.load (node:internal/modules/cjs/loader:1533:32)
    at Module._load (node:internal/modules/cjs/loader:1335:12)
    at wrapModuleLoad (node:internal/modules/cjs/loader:255:19)
    at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
    at node:internal/main/run_main_module:33:47

Node.js v24.14.0
```

### Environment

```
  System:
    OS: Linux 6.19 cpe:/o:nixos:nixos:26.05 26.05 (Yarara)
  Binaries:
    Node: 24.14.0 - /home/anders/.nix-profile/bin/node
    Yarn: 1.22.22 - /home/anders/.nix-profile/bin/yarn
    npm: 11.9.0 - /home/anders/.nix-profile/bin/npm
    pnpm: 10.30.2 - /home/anders/.nix-profile/bin/pnpm
    bun: 1.3.10 - /home/anders/.nix-profile/bin/bun
  npmPackages:
    @babel/preset-typescript: ^7.28.5 => 7.28.5 
    @babel/register: ^7.28.6 => 7.28.6 
```

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #17903 
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

In this PR we skip the babel-register hook for ignored files in programmatic options. Previously the hook was still registered for ignored files and therefore an ignored `.ts` file may throw syntax error because the original JS loader, where the builtin TS type stripping happens, was skipped as `pirates` has no knowledge that Babel does not handle this ignored file.

### CODE REVIEW

File: packages/babel-register/src/worker/transform.ts [hunk 1]
```diff
@@ -109,8 +119,22 @@ async function transform(input: string, filename: string) {
   return await store({ code, map });
 }
 
+async function isFileIgnored(filename: string) {
```
Comment (JLHwung) [inline packages/babel-register/src/worker/transform.ts:122]: This helper can potentially be reused by the babel-cli: See #17878

Do you think we should make it an API of `@babel/core`?

**Comment by liuxingbaoyu** [comment]
https://babeljs.io/docs/babel-register#specifying-options
`@babel/register` supports `ignore` and `only` options, and supporting them may be sufficient.

**Comment by JLHwung** [comment]
> https://babeljs.io/docs/babel-register#specifying-options `@babel/register` supports `ignore` and `only` options, and supporting them may be sufficient.

Thanks, as is said in the docs, `@babel/register` does not support `ignore` and `only` in config files, I will simplify the implementation.

**Comment by JLHwung** [comment]
> https://babeljs.io/docs/babel-register#specifying-options `@babel/register` supports `ignore` and `only` options, and supporting them may be sufficient.

I looked into this issue a bit, if we want to completely remove the `loadPartialConfig` call, we will have to somehow duplicate the pattern matching logic of `@babel/core` to `@babel/register`, such as `packages/babel-core/src/config/pattern-to-regex.ts` and the `matchesPatterns` in `packages/babel-core/src/config/config-chain.ts`.

If performance is your concern, I think what we can do is to disable `configFile` and `babelrc` in the first `loadPartialConfig` call so the core only checks if the file is deemed `ignored` via programmatic options. This will reduce the overhead of looking for `.babelrc` or `babel.config`.

**Comment by liuxingbaoyu** [comment]
It appears that we don't support patterns in the documentation, but only regular expressions and functions.

**Comment by JLHwung** [comment]
> It appears that we don't support patterns in the documentation, but only regular expressions and functions.

I believe this is a doc issue. In somewhere we mentioned that it supports regex / glob, elsewhere regex / function. I have updated the register docs to reflect on the current implementation: https://github.com/babel/website/pull/3190

File: packages/babel-register/src/worker/transform.ts (hunk 1 above)
Comment (nicolo-ribaudo) [reply packages/babel-register/src/worker/transform.ts:122]: It seems small enough that it's fine to just copy&paste it.

File: packages/babel-register/test/index.js [hunk 2]
```diff
@@ -341,6 +349,35 @@ describe("@babel/register", function () {
...
+      test("via programmatic options ignored", async () => {
+        const entryFile =
+          require.resolve("./fixtures/ignore-programmatic/index.ts");
+        const output = await spawnNodeAsync(
+          [entryFile],
+          path.dirname(entryFile),
+        );
+        expect(output).toContain(path.join("ignored", "ignored-throw.ts"));
+        expect(output).toContain(
+          "SyntaxError: TypeScript enum is not supported in strip-only mode",
```
Comment (nicolo-ribaudo) [inline packages/babel-register/test/index.js]: This could be thrown also by the non-ignored file if we accidentally ignore it. Could we instead `try/catch` the `require` that we expect to throw, and log something that then we check here?

**Review by liuxingbaoyu — APPROVED** [review]

File: packages/babel-register/src/worker/transform.ts [hunk 3]
```diff
@@ -109,8 +119,27 @@ async function transform(input: string, filename: string) {
...
+    filename,
+    showIgnoredFiles: true,
+    // @babel/register does not support ignore/only in config files,
+    // so we can skip checking those files
+    babelrc: false,
+    configFile: false,
+    browserslistConfigFile: false,
+    plugins: [],
+    presets: [],
+    targets: { browsers: undefined },
```
Comment (JLHwung) [inline packages/babel-register/src/worker/transform.ts:134]: Currently, babel-core still has to resolve the browser targets, even though it does not determine whether an input file is ignored or not. In the future we should optimize it and resolve targets after the file ignoring logic.

**Review by nicolo-ribaudo — COMMENTED** [review]
Sorry, I had this review in my draft and forgot to send it

File: packages/babel-register/src/worker/transform.ts (hunk 1 above)
Comment (JLHwung) [reply packages/babel-register/src/worker/transform.ts:122]: OK, let's leave it as-is.

**Review by nicolo-ribaudo — APPROVED** [review]
