### PR TITLE
Don't add params of anonymous exported function decls to the outer scope

### LINKED ISSUE #9611: Duplicate declaration
## 🐛 Bug Report

When running babel with preset-env on this code

```javascript
import x from './x';

export default function(x) {}
```

It errors with 'Duplicate declaration "x"'

I think this is valid code however, as node has no problem executing the file (with esm)

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #9611
| Patch: Bug Fix?          | y
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

File: packages/babel-plugin-transform-modules-commonjs/test/fixtures/regression/issue-9611/input.mjs [hunk 1]
```diff
@@ -0,0 +1,3 @@
+import x from './x';
+
+export default function(x) {}
```
Comment (danez) [inline packages/babel-plugin-transform-modules-commonjs/test/fixtures/regression/issue-9611/input.mjs]: Looking at the code I would guess it throws, because on line 465 it tries to get the id of the declaration but this one does not have one. but maybe path.get() does never return null?

Comment (nicolo-ribaudo) [reply packages/babel-plugin-transform-modules-commonjs/test/fixtures/regression/issue-9611/input.mjs]: It is set at https://github.com/babel/babel/blob/47bee79acf39e4fba0e21c4e2c52ea6cd11fce67/packages/babel-helper-split-export-declaration/src/index.js#L34

Comment (danez) [reply packages/babel-plugin-transform-modules-commonjs/test/fixtures/regression/issue-9611/input.mjs]: 👍
