### PR TITLE
fix: Template `export { x }` stuck in infinite loop

### LINKED ISSUE #15525: [Bug]:  template.ast goes endless loop
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
const template = require("@babel/template").default;

const name = 'a'
const ast = template.ast`
export  { ${name} }   
`
console.log(ast);
```

### Configuration file name

_No response_

### Configuration

No

### Current and expected behavior

Should get ast as expected

### Environment

  System:
    OS: macOS 11.7.4
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - ~/Library/pnpm/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  npmPackages:
    @babel/core: ^7.21.3 => 7.21.3 
    @babel/generator: ^7.21.3 => 7.21.3 
    @babel/parser: ^7.21.3 => 7.21.3 
    @babel/template: ^7.20.7 => 7.20.7 

### Possible solution

No

### Additional context

It seems that no matter how many times it is executed, there will be a case where `placeholder.isDuplicated`  be true, so it  just keep looping [here](https://github.com/babel/babel/blob/main/packages/babel-template/src/literal.ts#L79):

image

I am not sure if there is something wrong with my usage, if so, please tell me, thanks a lot!

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #15525 
| Patch: Bug Fix?          | √
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | √
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

Thanks @await-ovo!

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15534"></a>

### CODE REVIEW

File: packages/babel-template/src/literal.ts [hunk 1]
```diff
@@ -45,41 +45,33 @@ function buildLiteralData<T>(
   tpl: Array<string>,
   opts: TemplateOpts,
 ) {
-  let names;
-  let nameSet: Set<string>;
-  let metadata;
-  let prefix = "";
+  let prefix = "BABEL_TPL$";
```
Comment (nicolo-ribaudo) [inline packages/babel-template/src/literal.ts:48]: If we are always adding enough `$`s anyway, why do we need a more complex prefix?

File: packages/babel-template/src/literal.ts [hunk 2]
```diff
@@ -45,41 +45,33 @@ function buildLiteralData<T>(
...
-      // Explicitly include our generated names in the whitelist so users never
-      // have to think about whether their placeholder pattern will match.
-      placeholderWhitelist: new Set(
-        result.names.concat(
-          opts.placeholderWhitelist
-            ? Array.from(opts.placeholderWhitelist)
-            : [],
-        ),
+    prefix = "$$" + prefix;
+  } while (raw.includes(prefix));
```
Comment (nicolo-ribaudo) [inline packages/babel-template/src/literal.ts:57]: Instead of trying until we add enough `$`s, can we instead do this and only compute it once?

```js
let $count = 0;
const re = /\$+(?=\d)/g;
let m;
while (m = re.exec(tpl)) $count = Math.max($count, m[0].length);

const prefix = "$".repeat($count + 1);
```

File: packages/babel-template/src/literal.ts (hunk 1 above)
Comment (liuxingbaoyu) [reply packages/babel-template/src/literal.ts:48]: Just to reduce the possibility of duplication.

File: packages/babel-template/src/literal.ts (hunk 2 above)
Comment (liuxingbaoyu) [reply packages/babel-template/src/literal.ts:57]: I guess `includes()` would be a bit faster? Of course it doesn't matter.

Comment (nicolo-ribaudo) [reply packages/babel-template/src/literal.ts:57]: The difference is that with includes we iterate over the string n times (where "n" is the final number of times we have to expand the prefix), while with the regexp loop only once (because the regexp alwags start after the previous match, and matches prefixes of any length).

Comment (liuxingbaoyu) [reply packages/babel-template/src/literal.ts:57]: It seems that only in the last case (very long code and `$$$$$$0`) the regex is slightly faster, while in other cases `includes()` is faster.
It should be faster to use `BABEL_TPL$` as per the current code.
[perf](https://perf.link/#eyJpZCI6InRiZGlidGdvczZ3IiwidGl0bGUiOiJGaW5kaW5nIG51bWJlcnMgaW4gYW4gYXJyYXkgb2YgMTAwMCIsImJlZm9yZSI6ImNvbnN0IHRwbCA9IFtcbihgYWAucmVwZWF0KDEwMjQpK1wiJDBcIikucmVwZWF0KDE2KSxcbihgYWAucmVwZWF0KDEwMjQpK1wiJCQkJCQkMFwiKS5yZXBlYXQoMTYpLFxuKGBhYC5yZXBlYXQoMTAyNCkrXCIkMFwiKS5yZXBlYXQoNjQpLFxuKGBhYC5yZXBlYXQoMTAyNCkrXCIkJCQkJCQwXCIpLnJlcGVhdCg2NCksXG4oYGFgLnJlcGVhdCgxMDI0KjEyOCkrXCIkMFwiKS5yZXBlYXQoNjQpLFxuKGBhYC5yZXBlYXQoMTAyNCoxMjgpK1wiJCQkJCQkMFwiKS5yZXBlYXQoNjQpLFxuXVswXSIsInRlc3RzIjpbeyJuYW1lIjoiYSIsImNvZGUiOiIgIGxldCBwcmVmaXggPSBcIlwiO1xuXG4gIGRvIHtcbiAgICBwcmVmaXggPSBcIiRcIiArIHByZWZpeDtcbiAgfSB3aGlsZSAodHBsLmluY2x1ZGVzKHByZWZpeCkpOyIsInJ1bnMiOlsxOTAwMCwyMTAwMCwzMDAwLDExMDAwLDE4MDAwLDEzMDAwLDEwMDAsMjIwMDAsMTgwMDAsNTAwMCwyNjAwMCwxMTAwMCw2MDAwLDI0MDAwLDI0MDAwLDE0MDAwLDI3MDAwLDE2MDAwLDE2MDAwLDgwMDAsMjEwMDAsMjAwMDAsNzAwMCw0MDAwLDE1MDAwLDkwMDAsNzAwMCwyOTAwMCwxMDAwMCwyMTAwMCwzMDAwLDMyMDAwLDI0MDAwLDI2MDAwLDI0MDAwLDEwMDAsMjUwMDAsMjcwMDAsNTAwMCwyNDAwMCw5MDAwLDUwMDAsODAwMCw3MDAwLDE5MDAwLDE5MDAwLDI0MDAwLDE0MDAwLDI2MDAwLDYwMDAsNDAwMCwxODAwMCwzMDAwMCw5MDAwLDEyMDAwLDUwMDAsMTAwMCwxNjAwMCwxODAwMCwyNjAwMCw0MDAwLDE0MDAwLDE4MDAwLDEzMDAwLDEzMDAwLDE5MDAwLDcwMDAsMjQwMDAsMTMwMDAsMTMwMDAsMjAwMCwxNTAwMCw4MDAwLDUwMDAsMTEwMDAsMTUwMDAsMzAwMDAsMzAwMCwxMzAwMCw5MDAwLDE3MDAwLDgwMDAsMTkwMDAsNjAwMCwzMDAwLDcwMDAsMjIwMDAsMTIwMDAsNzAwMCwxMjAwMCwxODAwMCwyMzAwMCwxNzAwMCwyMDAwMCwxMTAwMCwzMDAwMCwyMDAwMCwxMjAwMCwyMjAwMCw4MDAwXSwib3BzIjoxNDU2MH0seyJuYW1lIjoiYiIsImNvZGUiOiJsZXQgJGNvdW50ID0gMDtcbmNvbnN0IHJlID0gL1xcJCsoPz1cXGQpL2c7XG5sZXQgbTtcbndoaWxlIChtID0gcmUuZXhlYyh0cGwpKSAkY291bnQgPSBNYXRoLm1heCgkY291bnQsIG1bMF0ubGVuZ3RoKTtcbmNvbnN0IHByZWZpeCA9IFwiJFwiLnJlcGVhdCgkY291bnQgKyAxKTsiLCJydW5zIjpbMTYwMDAsMTEwMDAsMjEwMDAsOTAwMCwxMzAwMCw4MDAwLDEwMDAsMTQwMDAsMTUwMDAsMjkwMDAsMTcwMDAsMTAwMCwxMDAwLDIxMDAwLDIxMDAwLDcwMDAsMjIwMDAsOTAwMCwxMDAwMCwyNDAwMCwxNzAwMCwxNDAwMCwxNzAwMCwxMDAwLDgwMDAsNjAwMCw2MDAwLDI2MDAwLDEwMDAsNjAwMCwyOTAwMCwxMDAwLDkwMDAsMjMwMDAsMjEwMDAsMjQwMDAsMjAwMDAsMjQwMDAsMjAwMCwxNDAwMCw3MDAwLDEwMDAsNTAwMCwxMDAwLDE1MDAwLDEyMDAwLDcwMDAsMTIwMDAsMTAwMCwyNDAwMCwxMDAwLDE2MDAwLDQwMDAsNjAwMCw5MDAwLDkwMDAsMTAwMCwxMzAwMCwxNDAwMCwyMzAwMCw4MDAwLDExMDAwLDMwMDAsNTAwMCw3MDAwLDE2MDAwLDMwMDAsMTYwMDAsMTEwMDAsNzAwMCwxMDAwLDIwMDAsNTAwMCwyMDAwLDI4MDAwLDEzMDAwLDI3MDAwLDI5MDAwLDEwMDAwLDYwMDAsMTMwMDAsMzAwMCwxMjAwMCwyMDAwLDEwMDAsMjIwMDAsMTIwMDAsOTAwMCw0MDAwLDYwMDAsMTYwMDAsMjEwMDAsMTMwMDAsMTgwMDAsMjkwMDAsMTAwMCwxODAwMCw4MDAwLDE3MDAwLDI1MDAwXSwib3BzIjoxMTgwMH1dLCJ1cGRhdGVkIjoiMjAyMy0wNC0wMVQxNDowNjozMi41ODhaIn0%3D)

**Review by nicolo-ribaudo — APPROVED** [review]

**Review by hebertcisco — APPROVED** [review]

**Review by JLHwung — APPROVED** [review]
I am not very familiar with babel template, rubberstamp lgtm.
