### PR TITLE
fix: support compiling monorepo on single-core CPU machines

### LINKED ISSUE #14715: [Bug]: Build failure "RangeError: Invalid array length"
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

Re-building of node-babel7 7.18.7+~cs214.249.185-1 in Debian and Ubuntu is failing with the error listed below.

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

[17:01:19] 'build-babel' errored after 1.15 s
[17:01:19] RangeError: Invalid array length
    at new BaseWorkerPool (/usr/share/nodejs/jest-worker/build/base/BaseWorkerPool.js:44:21)
    at new WorkerPool (/usr/share/nodejs/jest-worker/build/WorkerPool.js:18:1)
    at new Worker (/usr/share/nodejs/jest-worker/build/index.js:135:26)
    at createWorker (file:///build/1st/node-babel7-7.18.6+~cs214.249.185/Gulpfile.mjs:229:18)
    at buildBabel (file:///build/1st/node-babel7-7.18.6+~cs214.249.185/Gulpfile.mjs:239:18)
    at file:///build/1st/node-babel7-7.18.6+~cs214.249.185/Gulpfile.mjs:544:32
    at taskWrapper (/usr/share/nodejs/undertaker/lib/set-task.js:13:15)
    at bound (node:domain:421:15)
    at runBound (node:domain:432:12)
    at asyncRunner (/usr/share/nodejs/async-done/index.js:55:18)
[17:01:19] 'build' errored after 11 s

### Environment

This is against babel 7.18.7+~cs214.249.185-1.
Prior (successful) version in Ubuntu was 7.12.12+~cs150.141.84-8.  Debian appears to have had success with 7.18.5+~cs214.249.185-1, so this may be a recent regression?

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #14715 
| Patch: Bug Fix?          | Y
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

Fixed building errors on single-core CPU machines, here we use the default value (CPU length - 1) for `numWorkers`. I mark the PR as internal because this issue does not affect end users.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14720"></a>

### CODE REVIEW

File: Gulpfile.mjs [hunk 1]
```diff
@@ -222,7 +223,8 @@ function getFiles(glob, { include, exclude }) {
 }
 
 function createWorker(useWorker) {
-  const numWorkers = require("os").cpus().length / 2 - 1;
+  // jest-worker defaults
+  const numWorkers = cpus().length - 1;
```
Comment (nicolo-ribaudo) [inline Gulpfile.mjs:227]: If we want to keep the `/ 2` (using all my cores except for one might slow things down, if I'm doing other tasks in parallel), we can use `Math.ceil(require("os").cpus().length / 2 - 1)`. Also, if `cpus().length` is 1 we probably want 1 worker and not 0 :thinking:

Comment (JLHwung) [reply Gulpfile.mjs]: If CPU length is 1 or 2 (for Intel CPU with hyper-threading), the `numWorkers` is 0 so we don't spawn extra workers and run in the main process instead.

File: Gulpfile.mjs [hunk 2]
```diff
@@ -222,7 +223,7 @@ function getFiles(glob, { include, exclude }) {
 }
 
 function createWorker(useWorker) {
-  const numWorkers = require("os").cpus().length / 2 - 1;
+  const numWorkers = Math.ceil(cpus().length / 2) - 1;
```
Comment (merceyz) [inline Gulpfile.mjs:226]: `cpus().length` can be `0` so this will give you a negative number.
Ref https://github.com/yarnpkg/berry/pull/3090
