### PR TITLE
fix: correctly resolve references to non-constant enum members

### LINKED ISSUE #17049: [Bug]: weird behaviour on resolving enum member references
### 💻

- [x] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

[REPL](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=FAChEoAIF4D5IN7EpAbgQwE6QII0gOQAWApgDZkD2BA3MpCQHYCuAtpAGKWWL0p7RIARgA0fSACF8OEZAD0c3JACWAZ0iYSqymVQkAJpAAuPI6QYt2rEqwBGJbMoBmKowXUBjSo1VH0jI3oAX2Ag8Ag6UAgYeCQUDGwBQlIKajoUJjZJLF4UfnwAWXQzADpMf31KVggxPMlpWQVIAHkzBwB3NRJZPBMNLR09Qz62yEpmIwdIVS8ABxJ3SFtlRn0VgHNg0PDwSOBM9gl0AC9cpUEi0vLVqpr6KUEZeUUASRc2zUXGHnHJ7BnKPNFstVhtZMo3Op0Ot0Ct-tpdAZjKZzAdINY7A5QsAgA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=true&targets=&version=7.26.4&externalPlugins=%40babel%2Fplugin-transform-typescript%407.26.3&assumptions=%7B%7D)

```js
(() => {
  var A = 'hello';
  enum Foo {
    A = 1,
    B = A, // A is resolved to the enum member if it's constant
  }
})();

(() => {
  var A = 'hello';
  enum Bar {
    A = Math.random(),
    B = A, // Otherwise, A is resolved to the outer scope's binding
  }
})();


enum Baz {
  A = Math.random(),
  B = A, // If there's no outer scope's binding, it's again resolved to the enum member
}
```

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

The current behavior is commented in the input code.

I would expect the enum transformation to follow what tsc does (which is more consistent and simpler): https://www.typescriptlang.org/play/?#code/PTAEEFQSwZ1BDANgd3gTzgJwKYwPaIBu2AJqAC54UAW2o2AdgK4C2oL2LARtpgHQAoIQAphASlABeAHygA3gNChC8TBCmgA5AHNEeLkk0BuRfWZsAYnioKlSyJNABGADSmlAIQ3gXoUwF8BfzFxEwFRCRl5UxU1By1dfUMTJUZWUA9VaLt1RwBZeHJqPkx4BhI8FnE3HK9HHwCgkLEwgTS2TIAvbNzQAqKSsoqqsRqM7zdAoA

### Environment

Babel v7.26.4
@babel/plugin-transform-typescript v7.26.3

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by branchseer**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #17049 
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | Yes
| Minor: New Feature?      | No
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
CI is also failing on main

**Review by nicolo-ribaudo — APPROVED** [review]
Thank you!

**Comment by branchseer** [comment]
Hi @nicolo-ribaudo, is this PR good to merge, or is there anything more to do?

**Comment by nicolo-ribaudo** [comment]
Usually we wait for a second approval from another maintainer, let's just wait a little bit longer :)

@JLHwung @liuxingbaoyu

File: packages/babel-plugin-transform-typescript/src/enum.ts [hunk 1]
```diff
@@ -162,7 +162,26 @@ function ReferencedIdentifier(
...
+      if (curScope.hasOwnBinding(name)) {
+        /* The name is declared inside enum:
+        enum Foo {
+          A,
+          B = (() => {
+            const A = 1;
+            return A;
+          })())
+        } */
+        return;
```
Comment (JLHwung) [inline packages/babel-plugin-transform-typescript/src/enum.ts:181]: This part seems like something we should provide in the scope prototype for Babel 8. The `Scope.prototype.hasBinding` could accept an `upToScope` parameter where the scope search will end.

**Review by JLHwung — APPROVED** [review]
Thank you.
