### PR TITLE
Fix tdz checks in transform-block-scoping plugin

### LINKED ISSUE #3707: TDZ transformer can't handle conditionally called code (T6640)
> Issue originally made by @spicyj
### Bug information
- **Babel version:** 90327aee47da0587c9c2e45816924b82361bf790
- **Node version:** 4
- **npm version:** 2
### Options

```
function transform(src) { console.log(require('./packages/babel-core').transform(src, {plugins: [[require('./packages/babel-plugin-transform-es2015-block-scoping'), {tdz: true}]]}).code); }
```
### Input code

```
> transform('function f() {x;} Math.random() > 0.5 && f(); let x = 5; f();')
function f() {
  (function () {
    throw new ReferenceError("x is not defined - temporal dead zone");
  })();
}Math.random() > 0.5 && f();var x = 5;f();
```
### Description

`f` should throw only if it's called before the `let` executes.

### LINKED ISSUE #3708: TDZ transformer interprets any reference to a function as calling it (?) (T6641)
> Issue originally made by @spicyj
### Options

```
function transform(src) { console.log(require('./packages/babel-core').transform(src, {plugins: [[require('./packages/babel-plugin-transform-es2015-block-scoping'), {tdz: true}]]}).code); }
```
### Input code

```
> transform('function f() {x;} maybeCall(f); let x = 5;')
function f() {
  (function () {
    throw new ReferenceError("x is not defined - temporal dead zone");
  })();
}maybeCall(f);var x = 5;
```
### Description

`f` should only throw if `maybeCall` calls `f` before the `let` executes.

### LINKED ISSUE #6848: transform-block-scoping's tdz crashes
### Demo

https://runkit.com/embed/wx1vpm3rag2x

### Input Code

```js
a = 2;
let a = 4;
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  plugins: [
    [require("@babel/plugin-transform-block-scoping"), { tdz: true }]
  ]
}
```

### Current behavior

```
TypeError: _this.addHelper is not a function
  at Object.addHelper in @babel/plugin-transform-block-scoping/lib/index.js — line 564
  at buildTDZAssert in @babel/plugin-transform-block-scoping/lib/tdz.js — line 21
  at Object.exit in @babel/plugin-transform-block-scoping/lib/tdz.js — line 71
  ...
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.32
| Babylon          | 
| node             | 
| npm              | 
| Operating System |

### LINKED ISSUE #9394: Crash when both use "@babel/plugin-proposal-object-rest-spread" & "@babel/plugin-transform-block-scoping" with TDZ is true
## Bug Report

**Current Behavior**
Compiler throw error: Property id of VariableDeclarator expected node to be of a type ["LVal"] but instead got "CallExpression

**Input Code**
```js
let { bar, foo } = { foo: "aaa", bar: "bbb" };
```

**Expected behavior/code**
Working

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    ["@babel/preset-env", {
      "ignoreBrowserslistConfig": true
    }]
  ],
  "plugins": [
    ["@babel/plugin-proposal-object-rest-spread"],
    ["@babel/plugin-transform-block-scoping", {
      "tdz": true
    }]
  ]
}
```

**Environment**
- Babel version(s): @babel/core v7.2.2
- Node/npm version: Node 10.14.2/npm 6.4.1
- OS: OSX 10.14.2
- Monorepo: no
- How you are using Babel: cli 7.2.3

**Possible Solution**

**Additional context/Screenshots**
It's working If remove `tdz` config. 

Thank you.

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #6848, fixes #3707, fixes #3708, fixes #9394
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

The first two commits in this PR are at #9492; I suggest reviewing that PR first.

### CODE REVIEW

File: packages/babel-plugin-transform-block-scoping/src/tdz.js [hunk 1]
```diff
@@ -4,9 +4,9 @@ function getTDZStatus(refPath, bindingPath) {
   const executionStatus = bindingPath._guessExecutionStatusRelativeTo(refPath);
 
   if (executionStatus === "before") {
-    return "inside";
-  } else if (executionStatus === "after") {
     return "outside";
+  } else if (executionStatus === "after") {
+    return "inside";
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-block-scoping/src/tdz.js]: I think that "inside" and "outside" were swapped? To me "inside" means "inside the temporal dead zone", so "the usage is after the lexical declaration".

Comment (danez) [reply packages/babel-plugin-transform-block-scoping/src/tdz.js]: Yeah looking at the code it seems that "inside" was meant as "inside valid Zone". It is easier to understand for me now after swapping.

File: packages/babel-traverse/src/path/introspection.js [hunk 2]
```diff
@@ -206,115 +206,208 @@ export function willIMaybeExecuteBefore(target) {
...
+// TODO (Babel 8)
+// This can be { before: boolean, after: boolean, unknown: boolean }.
+// This allows transforms like the tdz one to treat cases when the status
+// is both before and unknown/after like if it were before.
+type RelativeExecutionStatus = "before" | "after" | "unknown";
+
 /**
  * Given a `target` check the execution status of it relative to the current path.
  *
  * "Execution status" simply refers to where or not we **think** this will execuete
```
Comment (danez) [inline packages/babel-traverse/src/path/introspection.js]:
```suggestion
  * "Execution status" simply refers to whether or not we **think** this will execute
```

File: packages/babel-traverse/src/path/introspection.js [hunk 3]
```diff
@@ -206,115 +206,208 @@ export function willIMaybeExecuteBefore(target) {
...
-      return;
-    }
-  }
-
   let allStatus;
 
   // verify that all the calls have the same execution status
   for (const path of referencePaths) {
     // if a reference is a child of the function we're checking against then we can
     // safelty ignore it
```
Comment (danez) [inline packages/babel-traverse/src/path/introspection.js]:
```suggestion
     // safely ignore it
```

**Comment by danez** [comment]
Is this relevant to #7933

**Comment by nicolo-ribaudo** [comment]
It is still buggy.

File: packages/babel-traverse/src/path/introspection.js [hunk 4]
```diff
@@ -206,115 +206,208 @@ export function willIMaybeExecuteBefore(target) {
...
+// This can be { before: boolean, after: boolean, unknown: boolean }.
+// This allows transforms like the tdz one to treat cases when the status
+// is both before and unknown/after like if it were before.
+type RelativeExecutionStatus = "before" | "after" | "unknown";
+
 /**
  * Given a `target` check the execution status of it relative to the current path.
  *
- * "Execution status" simply refers to where or not we **think** this will execuete
+  * "Execution status" simply refers to whether or not we **think** this will execute
```
Comment (nicolo-ribaudo) [inline packages/babel-traverse/src/path/introspection.js]:
```suggestion
 * "Execution status" simply refers to whether or not we **think** this will execute
```

File: packages/babel-traverse/src/path/introspection.js [hunk 5]
```diff
@@ -206,115 +206,208 @@ export function willIMaybeExecuteBefore(target) {
...
   let allStatus;
 
   // verify that all the calls have the same execution status
   for (const path of referencePaths) {
     // if a reference is a child of the function we're checking against then we can
-    // safelty ignore it
-    const childOfFunction = !!path.find(
-      path => path.node === targetFuncPath.node,
-    );
+     // safely ignore it
```
Comment (nicolo-ribaudo) [inline packages/babel-traverse/src/path/introspection.js]:
```suggestion
    // safely ignore it
```

File: packages/babel-helpers/src/helpers.js [hunk 6]
```diff
@@ -842,7 +830,24 @@ helpers.classNameTDZError = helper("7.0.0-beta.0")`
 `;
 
 helpers.temporalUndefined = helper("7.0.0-beta.0")`
-  export default {};
+  // This function isn't mean to be called, but to be used as a reference.
+  // We can't use a normal object because it isn't hoisted.
+  export default function _temporalUndefined() {}
+`;
+
+helpers.tdz = helper("7.3.3")`
```
Comment (nicolo-ribaudo) [inline packages/babel-helpers/src/helpers.js]:
```suggestion
helpers.tdz = helper("7.5.5")`
```

File: packages/babel-traverse/src/path/introspection.js [hunk 7]
```diff
@@ -206,115 +206,208 @@ export function willIMaybeExecuteBefore(target) {
...
   let allStatus;
 
   // verify that all the calls have the same execution status
   for (const path of referencePaths) {
     // if a reference is a child of the function we're checking against then we can
-    // safely ignore it
-    const childOfFunction = !!path.find(
-      path => path.node === targetFuncPath.node,
-    );
+    // safelty ignore it
```
Comment (nicolo-ribaudo) [inline packages/babel-traverse/src/path/introspection.js]:
```suggestion
    // safely ignore it
```
