### PR TITLE
Fix issue replacement nodes not requeued for transforming after destructuring

### LINKED ISSUE #5628: babel keep arrow function with decomposition assignment after translate
This issue reproduce on https://babeljs.io/repl with es2015

```js
let q;
let w;
let e;
// Incorrect translation
if (true) [q, w, e] = [1, 2, 3].map(()=>123);
// Correct translation
if (true) {[q, w, e] = [1, 2, 3].map(()=>123);}

```

### Output Code

```js
"use strict";

var _slicedToArray = function () { function sliceIterator(arr, i) { var _arr = []; var _n = true; var _d = false; var _e = undefined; try { for (var _i = arr[Symbol.iterator](), _s; !(_n = (_s = _i.next()).done); _n = true) { _arr.push(_s.value); if (i && _arr.length === i) break; } } catch (err) { _d = true; _e = err; } finally { try { if (!_n && _i["return"]) _i["return"](); } finally { if (_d) throw _e; } } return _arr; } return function (arr, i) { if (Array.isArray(arr)) { return arr; } else if (Symbol.iterator in Object(arr)) { return sliceIterator(arr, i); } else { throw new TypeError("Invalid attempt to destructure non-iterable instance"); } }; }();

var q = void 0;
var w = void 0;
var e = void 0;
// Incorrect translateion
if (true) {
  ;

  var _map = [1, 2, 3].map(() => 123);

  var _map2 = _slicedToArray(_map, 3);

  q = _map2[0];
  w = _map2[1];
  e = _map2[2];
} // Correct translateion
if (true) {
  var _map3 = [1, 2, 3].map(function () {
    return 123;
  });

  var _map4 = _slicedToArray(_map3, 3);

  q = _map4[0];
  w = _map4[1];
  e = _map4[2];
  _map3;
}
```

### PR DESCRIPTION
**Pull request by buunguyen**
| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          | yes 
| Major: Breaking Change?  | no 
| Minor: New Feature?      | no 
| Deprecations?            | no 
| Spec Compliancy?         | yes 
| Tests Added/Pass?        | yes
| Fixed Tickets            | Fixes #5628
| License                  | MIT
| Doc PR                   | no
| Dependency Changes       | no

As seen in https://github.com/babel/babel/issues/5628.

```js
if (true) [q, w, e] = [1, 2, 3].map(()=>123);
```
After destructuring plugin runs, the replacement nodes aren't transformed at all, thus leaving the arrow function unprocessed. This change invokes `requeue()` so that the nodes can be processed. 

I'm new to Babel codebase and this is my first PR. I appreciate any feedback/pointer to improve the PR. Thanks!

### CODE REVIEW

**Comment by buunguyen** [comment]
Update PR with more test and better fix.

More explanation: transformation doesn't happen because [`replaceWithMultiple` only requeues `this.node`](https://github.com/babel/babel/blob/7.0/packages/babel-traverse/src/path/replacement.js#L53). However, it's possible that a [replacement is done at an ancestor node](https://github.com/babel/babel/blob/7.0/packages/babel-traverse/src/path/modification.js#L113) causing it not to be transformed at all. This PR handles that specific case by queuing the ancestor replacement node.

Any feedback is appreciated.

**Comment by jridgewell** [comment]
Can you rebase and fix the failing test?

File: packages/babel-traverse/src/path/modification.js [hunk 1]
```diff
@@ -112,7 +116,10 @@ export function insertAfter(nodes) {
     this.parentPath.isExpressionStatement() ||
     this.parentPath.isLabeledStatement()
   ) {
-    return this.parentPath.insertAfter(nodes);
+    // `replaceWithMultiple` requeues if there's a replacement for this.node,
+    // but not for an ancestor's. Set `shouldRequeue` to true so that any replacement
+    // for an ancestor node can be enqueued. Fix #5628 and #5023.
+    return this.parentPath._insertAfter(nodes, true);
```
Comment (jridgewell) [inline packages/babel-traverse/src/path/modification.js]: We can also apply this logic to `#insertBefore`

Comment (buunguyen) [inline packages/babel-traverse/src/path/modification.js]: `replaceWithMultiple` only invokes `insertAfter`. I look for usages of `insertBefore` and none has the same before with `replaceWithMultiple` (i.e. invoke `requere` if `this.node != null`), so adding this logic there won't make any difference.

**Comment by buunguyen** [comment]
@jridgewell I've cleaned up the commit. Also, remove the link to fix 5023 because https://github.com/babel/babel/issues/5023#issuecomment-288611373 was no longer a problem in the current code (it was when I submitted this fix).

**Comment by buunguyen** [comment]
@jridgewell oops, CI fails. Let me take a look.

**Comment by existentialism** [comment]
@buunguyen the CI failure is unrelated to your PR (Fixed in https://github.com/babel/babel/pull/6090)

File: packages/babel-traverse/src/path/modification.js (hunk 1 above)
Comment (jridgewell) [inline packages/babel-traverse/src/path/modification.js]: But I can invoke `#insertBefore` [myself and get the same error](http://astexplorer.net/#/gist/47c24345d741602dc04928b353fdd254/515de002dc703383abd0ca91ca18faa812b076e2). [Here](https://github.com/babel/babel/pull/5743/files#diff-04e63519c0e77a22a1a20ef218acc048R32), right?

Comment (buunguyen) [inline packages/babel-traverse/src/path/modification.js]: Good point. I may miss the mark, that's probably a separate bug. If we introduce that same logic in `insertBefore`, I think the example you posted will still fail because it wouldn't go into the branch `parentPath.insertBefore`. The current fix works based on the fact that `replaceWithMultiple` will requeue when replacement happens at current path, but not ancestor path, so only need to add requeuing when replacement happens at ancestor path. If we expect requeuing to happen when directly invoking `insertBefore` or `insertAfter`, maybe the solution is always invoke `this.requeue()` right after `this._replaceWith()`? My concern is this means a double requeuing when invoking `replaceWithMultiple()` and replacement happens at the current path. What do you think?

Comment (jridgewell) [inline packages/babel-traverse/src/path/modification.js]: These two cases should be exactly equivalent. In `#insertAfter`, we hit [`parentPath.isExpressionStatement`](https://github.com/babel/babel/pull/5743/files#diff-04e63519c0e77a22a1a20ef218acc048R122), then [`this.isStatementOrBlock()`](https://github.com/babel/babel/pull/5743/files#diff-04e63519c0e77a22a1a20ef218acc048R145). In `#insertBefore`, we'd hit [`parentPath.isExpressionStatement`](https://github.com/babel/babel/pull/5743/files#diff-04e63519c0e77a22a1a20ef218acc048R21), then [`this.isStatementOrBlock()`](https://github.com/babel/babel/pull/5743/files#diff-04e63519c0e77a22a1a20ef218acc048R32).

Comment (buunguyen) [inline packages/babel-traverse/src/path/modification.js]: That example will run to [branch 3](http://astexplorer.net/#/gist/47c24345d741602dc04928b353fdd254/081331b15feba9ea524d25707173b478ff5636f2) (i.e. `_containerInsertBefore()`). Still, if we replicate the logic, it will fix the case code goes to branch 1 and then 4, but how cases that go that branch 4 directly?

Comment (buunguyen) [inline packages/babel-traverse/src/path/modification.js]: @jridgewell I propose limiting the scope of this PR to fix #5628, i.e. not transformed in destructuring. For other potential bugs/use cases, maybe we should look at in a different PR. What do you think?

**Comment by jridgewell** [comment]
Any problems with merging this? It's now needed to fix a bug in https://github.com/babel/babel/pull/6120.
