### PR TITLE
Fix flow babel-generator function parantheses

### LINKED ISSUE #9514: @babel/plugin-syntax-flow returns incompatible Flow code
## Bug Report

**Current Behavior**
When I use `@babel/plugin-syntax-flow` to parse Flow code it generates wrong output (completely incompatible).

**Input Code**
[REPL](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=C4TwDgpgBAJAYgJwIYHMC2EB2wBKEBmAPACoB8UAvFEpiAFB2iSx4A2SIACggPZgDOhbn34AaKGw7CwZSrADyAIwBWAWSRhCdKLAAiAS3xFpYqAG8oCCOxAAuCdam8ZUAD5QAbj30ATKAF9SUW0oAAoSewsAahgrfGJwCHsaEADSUKhiAEpKclhEVAxsPCIyHIAyEPDiSKgYuITIZNo00IB-bNyoNvhkdCxcAhJSLJCAejGoADoZulIgA&debug=true&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=&prettier=false&targets=Node-6&version=7.2.2) (do not forget `@babel/plugin-syntax-flow`)

```js
type $FragmentRef<T> = any

type $RelayProps<Props, RelayPropT> = $ObjMap<
  $Diff<Props, { relay: RelayPropT | void }>,
  (<T: { +$refType: any }>( T) =>  $FragmentRef<T>) &
  (<T: { +$refType: any }>(?T) => ?$FragmentRef<T>)
  // ...
>
```

**Output Code**

```js
type $FragmentRef<T> = any;
type $RelayProps<Props, RelayPropT> = $ObjMap<$Diff<Props, {
  relay: RelayPropT | void
}>, <T: {
  +$refType: any
}>(T) => $FragmentRef<T> & <T: {
  +$refType: any
}>(?T) => ?$FragmentRef<T> // ...
>;
```

Notice the missing brackets. Prettified (😅) code:

```js
type $FragmentRef<T> = any;
type $RelayProps<Props, RelayPropT> = $ObjMap<
  $Diff<
    Props,
    {
      relay: RelayPropT | void
    }
  >,
  <
    T: {
      +$refType: any
    }
  >(
    T
  ) => $FragmentRef<T> &
    (<
      T: {
        +$refType: any
      }
    >(
      ?T
    ) => ?$FragmentRef<T>) // ...
>;
```

Meaning of this code is different from the original.

**Expected behavior/code**
It doesn't change the code in any incompatible way. It should return basically the same since there is no additional transpilation.

Currently, I can workaround it like this which is not nice at all:

```js
/*::

type $FragmentRef<T> = any

type $RelayProps<Props, RelayPropT> = $ObjMap<
  $Diff<Props, { relay: RelayPropT | void }>,
  (<T: { +$refType: any }>( T) =>  $FragmentRef<T>) &
  (<T: { +$refType: any }>(?T) => ?$FragmentRef<T>)
  // ...
>

*/
```

### PR DESCRIPTION
**Pull request by tanhauhau**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #9514 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

File: packages/babel-generator/test/fixtures/flow/type-annotations/output.js [hunk 1]
```diff
@@ -180,7 +180,7 @@ class Array {
 
 }
 
-var x: () => number | () => string = fn;
+var x: () => number | (() => string) = fn;
```
Comment (danez) [inline packages/babel-generator/test/fixtures/flow/type-annotations/output.js]: Do you know why the first FunctionTypeAnnotation here is not in parentheses? Isn't its parent also union?

Comment (nicolo-ribaudo) [reply packages/babel-generator/test/fixtures/flow/type-annotations/output.js]: It's because it is `() => (number | (() => ... ))`
