### PR TITLE
fix: raise `SyntaxError` for `declare` before getter/setter

### LINKED ISSUE #13126: Babel parser typescript should throw when declare is applied to accessors
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

Parsed successfully.

- [REPL](https://babel.dev/repl#?browsers=chrome%2088&build=&builtIns=usage&spec=false&loose=false&code_lz=MYGwhgzhAEDCCc9oG8BQ1oBMCmowCdtoBzbAF2gCMwAvACgEoAuORdLXcQ6Ccq2ugDcGqAL5A&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ctypescript&prettier=false&targets=&version=7.13.15&externalPlugins=%40babel%2Fplugin-proposal-do-expressions%407.12.13)

**Input Code**

```ts
class C99 {
  declare get baz(): C99
  declare set baz(v)
}
```

**Expected behavior**

Babel parser should throw class accessors should not have "declare" modifier, like we did for class methods.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
REPL

**Possible Solution**

**Additional context**

Found this issue when reviewing #13089.

### PR DESCRIPTION
**Pull request by fedeci**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #13126 
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

We check if method is both a getter/setter and `declare` in `pushClassMethod` so that class properties are excluded from the test.

### CODE REVIEW

File: packages/babel-parser/test/fixtures/typescript/class/declare-accessor/input.ts [hunk 1]
```diff
@@ -0,0 +1,4 @@
+class Foo {
+  declare get foo()
+  declare set foo(v)
+}
```
Comment (JLHwung) [inline packages/babel-parser/test/fixtures/typescript/class/declare-accessor/input.ts:4]: Can you add a test case when `get/set` is a property name?

```ts
class Foo {
  declare get: string;
  declare set: string;
}
```

They shout not throw because they are not accessors.

**Comment by nicolo-ribaudo** [comment]
^ Nice, a labels race condition :smile:

File: packages/babel-parser/test/fixtures/typescript/class/declare-accessor/input.ts (hunk 1 above)
Comment (fedeci) [reply packages/babel-parser/test/fixtures/typescript/class/declare-accessor/input.ts:4]: Nice, that doesn't work because the check is done too early, I'll fix in the weekend.

**Review by JLHwung — APPROVED** [review]
Thanks!

**Review by nicolo-ribaudo — APPROVED** [review]
Thanks!
