### PR TITLE
fix: Typo in `@babel/helper-create-class-features-plugin`

### LINKED ISSUE #13236: [Bug]: Typo on `babel/plugin-proposal-private-private-property-in-object` package name
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

Bug occurs on a `npm install` with `@babel/preset-env` preset set.

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

Npm provides the correct babel plugin name to install `babel/plugin-proposal-private-property-in-object` and not `babel/plugin-proposal-private-private-property-in-object`

### Environment

 System:
    OS: macOS 11.2.3
  Binaries:
    Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
    Yarn: 1.22.10 - ~/node_modules/.bin/yarn
    npm: 7.11.2 - ~/Repositories/shared-ui-components/node_modules/.bin/npm
  npmPackages:
    @babel/core: ^7.9.0 => 7.14.0 
    @babel/plugin-proposal-private-property-in-object: ^7.14.0 => 7.14.0 
    @babel/preset-env: ^7.10.2 => 7.14.0 
    babel-jest: ^26.0.1 => 26.6.3 
    babel-loader: ^8.1.0 => 8.2.2 
    eslint: ^7.25.0 => 7.25.0 
    jest: ^26.0.1 => 26.6.3 

### Possible solution

Replace line:
https://github.com/babel/babel/blob/672a58660f0b15691c44582f1f3fdcdac0fa0d2f/packages/babel-helper-create-class-features-plugin/src/features.js#L16

with 

`"@babel/plugin-proposal-private-property-in-object",`

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by aancer-rca**
Fixes #13236

Replace line:
babel/packages/babel-helper-create-class-features-plugin/src/features.js

Line 16 in 672a586

 "@babel/plugin-proposal-private-private-property-in-object"

with

"@babel/plugin-proposal-private-property-in-object",

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/13237"></a>

### CODE REVIEW

**Review by JLHwung — APPROVED** [review]
Thanks!

File: packages/babel-helper-create-class-features-plugin/src/features.js [hunk 1]
```diff
@@ -13,7 +13,7 @@ const featuresSameLoose = new Map([
   [FEATURES.privateMethods, "@babel/plugin-proposal-private-methods"],
   [
     FEATURES.privateIn,
```
Comment (nicolo-ribaudo) [inline packages/babel-helper-create-class-features-plugin/src/features.js:15]:
```suggestion
  [FEATURES.privateIn, "@babel/plugin-proposal-private-property-in-object"],
```

There is a linting error

File: packages/babel-helper-create-class-features-plugin/src/features.js [hunk 2]
```diff
@@ -13,7 +13,7 @@ const featuresSameLoose = new Map([
...
-    "@babel/plugin-proposal-private-private-property-in-object",
+    "@babel/plugin-proposal-private-property-in-object",
   ],
```
Comment (nicolo-ribaudo) [inline packages/babel-helper-create-class-features-plugin/src/features.js:17]:
```suggestion
```

Comment (JLHwung) [reply packages/babel-helper-create-class-features-plugin/src/features.js]: Guess we should have a lint fix workflow.

Comment (nicolo-ribaudo) [reply packages/babel-helper-create-class-features-plugin/src/features.js]: Yeah that would help

Comment (aancer-rca) [reply packages/babel-helper-create-class-features-plugin/src/features.js]: An option could be to hook ESLint up to Prettier in the lint-staged hook for auto clean up with something to the effect of ( not exactly, but for reference ):

```
"*.{js,jsx,ts,tsx,css,scss,md}": [
            "prettier --ignore-path ./.eslintignore --write"
        ]
```

I guess this might increase commit time slightly so probably want to take with a grain of salt & weigh tradeoffs

Comment (nicolo-ribaudo) [reply packages/babel-helper-create-class-features-plugin/src/features.js]: We have a CI job that automatically updates some fixtures when they need to be updated (https://github.com/babel/babel/actions/runs/615369743/workflow), we can do something similar.
