### PR TITLE
Retry to fix object spread helper compatibility

### LINKED ISSUE #9322: Object spread still calls getter function after transform
## Bug Report

**Current Behavior**
I still have the same issue as #7524.

**Input Code**

```js
var x = { a: 3 };
var y = { ...x, get y() { return this.a.toString(); } };
console.log(y.y === "3")
```

**Expected behavior/code**
It should log `true`.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": "last 1 Firefox version, last 1 Chrome version, last 1 Safari version, last 1 Edge version",
        "modules": "amd"
      }
    ]
  ]
}
```

**Environment**
- Babel version(s): 7.2.0
- Node/npm version: 11.6.0
- OS: Windows 10
- Monorepo: no
- How you are using Babel: `cli`

**Possible Solution**
`Object.getOwnPropertyDescriptors` should be used instead of just copying the values. This way the symbol case should be automatically covered.

**Additional context/Screenshots**
The output does use helper function but still is broken.

```js
define([], function () {
  "use strict";

  function _objectSpread(target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i] != null ? arguments[i] : {}; var ownKeys = Object.keys(source); if (typeof Object.getOwnPropertySymbols === 'function') { ownKeys = ownKeys.concat(Object.getOwnPropertySymbols(source).filter(function (sym) { return Object.getOwnPropertyDescriptor(source, sym).enumerable; })); } ownKeys.forEach(function (key) { _defineProperty(target, key, source[key]); }); } return target; }

  function _defineProperty(obj, key, value) { if (key in obj) { Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true }); } else { obj[key] = value; } return obj; }

  var x = {
    a: 3
  };

  var y = _objectSpread({}, x, {
    get y() {
      return this.a.toString();
    }

  });

  console.log(y.y === "3");
});
//# sourceMappingURL=test.js.map
```

### PR DESCRIPTION
**Pull request by saschanaz**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #9322
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

Retries #9341.

This adds `helpers._objectSpread2()` where only the even arguments would be considered as spreads.

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
Can you add a comment that the old helper can be removed in the next major release?

**Comment by saschanaz** [comment]
No idea what's causing failure to rename.

**Comment by saschanaz** [comment]
>Can you add a comment that the old helper can be removed in the next major release?

Inside the helper or above `helpers.objectSpread` line?

**Comment by saschanaz** [comment]
It seems somehow the helper name can't include a trailing number?

**Comment by nicolo-ribaudo** [comment]
Yeah it can. It will be renamed to `_objectSpread` when inlined but it isn't a problem: `@babel/runtime/helpers/objectSpread` will still point to the old helper and  `@babel/runtime/helpers/objectSpread2` to the new one.

**Comment by saschanaz** [comment]
Can this be merged or do this have any more blockers?

**Comment by saschanaz** [comment]
Any news for this?

**Comment by saschanaz** [comment]
@nicolo-ribaudo How about we just treat `null`/`undefined` always as `{}`? That way we can keep the compatibility with the previous behavior without adding `objectSpread2`.

**Comment by nicolo-ribaudo** [comment]
It wouldn't work, because the old helper handles all the arguments the same way.

**Comment by saschanaz** [comment]
The previous issue was that the old code didn’t work with the new helper because the helper assumed that the odd arguments are all objects. Modifying that behavior to also accept null/undefined should fix the specific issue.

________________________________

File: packages/babel-helpers/src/helpers.js [hunk 1]
```diff
@@ -404,6 +405,30 @@ helpers.objectSpread = helper("7.0.0-beta.0")`
   }
 `;
 
+helpers.objectSpread2 = helper("7.0.0-beta.0")`
+  import defineProperty from "defineProperty";
+
+  export default function _objectSpread(target) {
```
Comment (danez) [inline packages/babel-helpers/src/helpers.js]: Should it be named objectSpread2? I wonder in the case someone uses babel-runtime, this might be a problem, but I don't know exactly how runtime works.

Comment (nicolo-ribaudo) [reply packages/babel-helpers/src/helpers.js]: Since this is a default export, the name doesn't matter.
Anyway, we should rename it for consistency.

Comment (danez) [reply packages/babel-helpers/src/helpers.js]: But where is the name in generated output coming from? Because right now it is called `_objectSpread` even with he new helper, which made me think it might collide in the runtime again.

Comment (nicolo-ribaudo) [reply packages/babel-helpers/src/helpers.js]: It does `generateUidIdentifier("objectSpread2")`, which removes `2` before generating the id.

Comment (saschanaz) [reply packages/babel-helpers/src/helpers.js]: Would `objectSpreadTwo` is okay or should I fix the function to not remove `2`?

Comment (nicolo-ribaudo) [reply packages/babel-helpers/src/helpers.js]: It's ok as it is now for me.

Comment (saschanaz) [reply packages/babel-helpers/src/helpers.js]: You mean this can be ignored?

>Anyway, we should rename it for consistency.

Comment (nicolo-ribaudo) [reply packages/babel-helpers/src/helpers.js]: We should rename the helper:
```js
export default function _objectSpread2
```
But is is not a problem if that `2` then gets automatically removed by `generateUid`.

**Comment by nicolo-ribaudo** [comment]
Thanks!

**Comment by mathieutu** [comment]
Hi folks. Thanks for you work. 

Just to be sure, do you confirm that this PR will fix the issue https://github.com/babel/babel/issues/8749?

Do you have any idea of its release planning?

Thanks!

**Comment by cloudkite** [comment]
This change breaks IE11 compatibility when using object spread syntax without using polyfills as getOwnPropertyDescriptors is not available in IE11.

**Comment by nicolo-ribaudo** [comment]
Could you please open a new issue? 🙏

**Comment by QingLeiLi** [comment]
I got the error 
> ModuleNotFoundError: Module not found: Error: Can't resolve '@babel/runtime/helpers/objectSpread2'

There must be something wrong in `babel-plugin-proposal-object-rest-spread`.

**Comment by pwnreza** [comment]
WhatsApp Image 2019-07-05 at 13 24 32

Same error as referenced by @edi9999
We are depending on building our RN app via pre-installed set of node_modules.
So we are pretty desperate for a fix 🙏

**Comment by kimroen** [comment]
> I got the error
> 
> > ModuleNotFoundError: Module not found: Error: Can't resolve '@babel/runtime/helpers/objectSpread2'
> 
> There must be something wrong in `babel-plugin-proposal-object-rest-spread`.
> 
> ADD：`objectSpread2 ` was add in the `@babel/runtime-corejs2` package, but the `helperGenerator` method will search the helper in the `@babel/runtime` package only, except set the corejs option to 2.

We're getting a similar error after upgrading from `7.4.3` to `7.5.0`. The error we're getting is this:

"Unknown helper objectSpread2".

**Comment by QingLeiLi** [comment]
> > I got the error
> > > ModuleNotFoundError: Module not found: Error: Can't resolve '@babel/runtime/helpers/objectSpread2'
> > 
> > 
> > There must be something wrong in `babel-plugin-proposal-object-rest-spread`.
> > ADD：`objectSpread2 ` was add in the `@babel/runtime-corejs2` package, but the `helperGenerator` method will search the helper in the `@babel/runtime` package only, except set the corejs option to 2.
> 
> We're getting a similar error after upgrading from `7.4.3` to `7.5.0`. The error we're getting is this:
> 
> "Unknown helper objectSpread2".

Yeah, add `@babel/plugin-transform-runtime` option 
`
{
      corejs: 2,
}
`
make it works again.

**Comment by Udbhav12** [comment]
@QingLeiLi Can you please share your entire package.json file ?

**Comment by QingLeiLi** [comment]
> package.json

package.json ? Did you mean babel config?

```
// babel.config.js
module.exports = {
    return {
        presets: [
            [
                '@babel/preset-env',
                {
                    modules: 'false',
                    targets: {
                        ios: '9',
                        android: '4.4'
                    },
                    useBuiltIns: 'usage'
                }
            ],
            ['@babel/preset-react'],
            ['@babel/preset-typescript']
        ],
        plugins: [
            ['@babel/plugin-transform-runtime', {
            	// point
                "corejs": 2,
            }],
            '@babel/plugin-proposal-class-properties',
            [
                "@babel/plugin-proposal-decorators",
                {
                    "decoratorsBeforeExport": false
                }
            ]
        ],
    };
};
```

**Comment by pwnreza** [comment]
> WhatsApp Image 2019-07-05 at 13 24 32
> 
> Same error as referenced by @edi9999
> We are depending on building our RN app via pre-installed set of node_modules.
> So we are pretty desperate for a fix 🙏

[See here](https://github.com/babel/babel/issues/10166)

**Comment by kimroen** [comment]
Just wanted to mention that the issue I was describing above was fixed by this PR: https://github.com/babel/babel/pull/10170
