### PR TITLE
Parse `for await (async of ...)`

### LINKED ISSUE #13235: [Bug]: Parser can't parse "for await (async of []);"
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
async function f() {
    for await (async of []);
}
```

[Babel REPL](https://babel.dev/repl#?browsers=&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=IYZwngdgxgBAZgV2gFwJYHsLwBQEoYDeAUDPOgE4zADuwqyM2oks6cMA2gLq4DcRAXyA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=script&lineWrap=false&presets=&prettier=false&targets=&version=7.14.0&externalPlugins=)

### Configuration file name

_No response_

### Configuration

```json
{}
```

### Current and expected behavior

Expected:
- The parser parses a `for await` statement with the identifier `async` as its left-hand-side.

Actual:
```
/repl.js: Unexpected token, expected "=>" (2:22)

  1 | async function f() {
> 2 |   for await (async of []);
    |                       ^
  3 | }
```

### Environment

- Babel 7.14.0
- Current Babel main (b99c4f06d433b04d3f3308838d494d9e50158ea0)

### Possible solution

After `for await (` not followed by `var`/`let`/`const`, the ECMAScript grammar requires a *LeftHandExpression* followed by `of`.

Babel instead parses an arbitrary expression, and then checks that the expression can be converted to a left-hand-side. This *mostly* works, except that when the next two tokens are `async of` the expression parser sees them as the start of an async arrow function with parameter `of` (which is not a *LeftHandExpression*).

The solution I currently have in mind is to explicitly look ahead for `async of` after the  `for await (`, and parse the left-hand-side as an identifier instead of an expression. That will fix this edge-case, and the existing approach of parsing an expression should remain viable in all other cases for now.

### Additional context

https://github.com/babel/babel/pull/13208
https://github.com/prettier/prettier/pull/10781#pullrequestreview-648146981

### PR DESCRIPTION
**Pull request by Zalathar**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #13235  
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  | No
| License                  | MIT

This allows the parser to correctly parse `for await (async of []);` by implementing the suggestion given by @JLHwung in https://github.com/babel/babel/issues/13235#issuecomment-830132666.

When the expression parser sees `async of`, it will peek ahead for a `=` character before it commits to parsing an async arrow function.

On its own this would also cause `for (async of []);` to parse, which is forbidden, so we also add explicit code to the `for` parser to detect and reject for-of statements that begin with `async of`.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/13244"></a>

### CODE REVIEW

File: packages/babel-parser/src/parser/statement.js [hunk 1]
```diff
@@ -539,13 +539,30 @@ export default class StatementParser extends ExpressionParser {
...
     const refExpressionErrors = new ExpressionErrors();
     const init = this.parseExpression(true, refExpressionErrors);
     const isForOf = this.isContextual("of");
-    if (isForOf || this.match(tt._in)) {
-      if (isForOf && startsWithLet) {
+    if (isForOf) {
+      // Check for leading tokens that are forbidden in for-of loops:
+      if (startsWithLet) {
         this.raise(init.start, Errors.ForOfLet);
+      } else if (startsWithAsyncOf && init.type !== "ArrowFunctionExpression") {
```
Comment (JLHwung) [inline packages/babel-parser/src/parser/statement.js:559]: I don't think we need lookahead before, instead we can check if `awaitAt === -1`, `init.type` is `Identifier`, `init.name` is `async` and `!containsEsc` here.

File: packages/babel-parser/test/fixtures/core/categorized/for-async-of-dot/input.js [hunk 2]
```diff
@@ -0,0 +1 @@
+for (async.x of y);
```
Comment (JLHwung) [inline packages/babel-parser/test/fixtures/core/categorized/for-async-of-dot/input.js:1]: Can you add a new test case when async contains escape?
```js
for (\u0061sync of []);
```
It should parsed successfully.

Note that currently V8 throws, I think this is a V8 bug.

File: packages/babel-parser/src/parser/statement.js (hunk 1 above)
Comment (Zalathar) [reply packages/babel-parser/src/parser/statement.js:559]: This doesn't quite work, because it rejects `for ((async) of []);` which should be legal.

File: packages/babel-parser/test/fixtures/core/categorized/for-async-of-dot/input.js (hunk 2 above)
Comment (Zalathar) [reply packages/babel-parser/test/fixtures/core/categorized/for-async-of-dot/input.js:1]: There's a test for that in the generator suite, but I can add one to the parser suite as well.

File: packages/babel-parser/src/parser/statement.js (hunk 1 above)
Comment (Zalathar) [reply packages/babel-parser/src/parser/statement.js:559]: Though if I also do an early check for `tt.name`, that should be good enough? I'll try it out.

Comment (JLHwung) [reply packages/babel-parser/src/parser/statement.js:559]: Make sense. Well in that case we can check `type = Identifier` here and avoid the `of` lookahead.

**Comment by Zalathar** [comment]
Is there any particular place I should be putting these parser tests? I wasn't sure if I should put them in `es2015/for-of/`.

**Comment by JLHwung** [comment]
@Zalathar The `for(async of` tests can be placed in `es2021`, resulted from a need-Consensus PR: https://github.com/tc39/ecma262/pull/2256

The `for await(async of` tests can be placed in `es2018/async-generators`. The syntax hasn't changed since then.

**Review by JLHwung — APPROVED** [review]
Awesome!

**Review by nicolo-ribaudo — APPROVED** [review]
Thanks!
