### PR TITLE
[generator] remove parens from break & continue

### LINKED ISSUE #5742: bad interaction between transform-es2015-block-scoping and auxiliaryCommentBefore
## Problem

This issue was originally reported to Jest, see:

https://github.com/facebook/jest/issues/3089

When the auxiliaryCommentBefore is used in conjunction with `transform-es2015-block-scoping`, invalid JavaScript code is generated, resulting in the following error:

```bash
    /Users/benjamincoe/bcoe/coverage/bugs_demo/buggy.js:18
            } else /* istanbul ignore next */{++cov_sg4xb2gde.b[1][1];}};_loop2: for (var i = 0; i < stages.length; i++) {/* istanbul ignore next */var _ret = _loop(i); /* istanbul ignore next */switch (_ret) {case "continue":continue;case "break":break (/* istanbul ignore next */_loop2);}
                                                                                                                                                                                                                                                              ^
    SyntaxError: Unexpected token (
```

## Reproduction

This error can be reproduced by running the repo:

https://github.com/mderk/bugs_demo/blob/master/buggy.js

CC: @mderk, @cpojer

### PR DESCRIPTION
**Pull request by sarupbanskota**
| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          | 
| Major: Breaking Change?  | 
| Minor: New Feature?      | 
| Deprecations?            | 
| Spec Compliancy?         | 
| Tests Added/Pass?        | 
| Fixed Tickets            | Fixes #5742 
| License                  | MIT
| Doc PR                   | 
| Dependency Changes       |

### CODE REVIEW

File: packages/babel-generator/src/generators/statements.js [hunk 1]
```diff
@@ -123,10 +123,14 @@ function buildLabelStatement(prefix, key = "label") {
     const label = node[key];
     if (label) {
       this.space();
-
-      const terminatorState = this.startTerminatorless();
-      this.print(label, node);
-      this.endTerminatorless(terminatorState);
+      if (prefix == "break" || prefix == "continue") {
+        // see https://git.io/vQ7uG
+        this.print(label, node);
```
Comment (loganfsmyth) [inline packages/babel-generator/src/generators/statements.js]: This avoids one issue, but won't 100% solve the issue. Consider if the label has a `leadingComment` of a `LineComment`. What is the right output?

```
continue foo;
```
becomes
```
continue // a comment
  foo;
```

instead of
```
continue (// a comment
  foo);
```
but it is still not right, since the spec doesn't allow newlines between `continue` and the label, so that is parsed like

```
continue;
// a comment
foo;
```

We'd almost have to move the comment output to _before_ `continue`, which will be a pain.

Comment (sarupbanskota) [inline packages/babel-generator/src/generators/statements.js]: I realise that one @loganfsmyth, you also mentioned it before. Having parens next to `break` and `continue` is wrong (?), so I wanted to get that out of the way.

Comment (sarupbanskota) [inline packages/babel-generator/src/generators/statements.js]: @loganfsmyth @jridgewell what do you think about converting single line comments after `break` or `continue` to multi line instead of trying to move them above the `break` or `continue`?

not that I know an easy way, but I could look for ideas .. 

e.g from my comment https://github.com/babel/babel/issues/5742#issuecomment-315352527

``` js
switch (_ret) {case "continue":continue;case "break":break /* istanbul ignore next */_loop2;}
```
that seems like valid code, and nothing broke too

Comment (loganfsmyth) [inline packages/babel-generator/src/generators/statements.js]: My concern is that where before you'd get a very obvious syntax error when loading the code, now `babel-generator` will output code that will parse, but have different runtime behavior. That _probably_ will trigger a syntax error too, since there probably isn't a variable with the same name as the label, but it isn't guaranteed.

I don't care if we get a 100% fix in for this, but I do wonder if there is a way we could make `babel-generator` throw a clear error when that case happens, instead of outputting broken code.

Comment (loganfsmyth) [inline packages/babel-generator/src/generators/statements.js]: > what do you think about converting single line comments

If it's something we can do, go for it. It might still not be easy. There's still the issue of multiline comments, e.g.

```
continue /* foo
bar */ label;
```

but as with my previous comment, either we throw a clear error, or maybe extending your approach, we also just replace newlines in the comments with spaces?

File: packages/babel-generator/test/fixtures/parentheses/break-statement/expected.js [hunk 2]
```diff
@@ -0,0 +1,5 @@
+label: for (const a of [1, 2, 3]) {
+  break
+  /*test*/
```
Comment (sarupbanskota) [inline packages/babel-generator/test/fixtures/parentheses/break-statement/expected.js]: I know ideally this shouldn't be in a newline, but thanks to https://github.com/babel/babel/blob/d82afb407eaa4ff03b98b85824efcd161913952d/packages/babel-generator/src/printer.js#L532, newlines are always inserted before a BlockComment.

Why though - is it necessary to print newline always?

File: packages/babel-plugin-transform-es2015-block-scoping/src/index.js [hunk 3]
```diff
@@ -261,6 +261,12 @@ const loopVisitor = {
     const { node, parent, scope } = path;
     if (node[this.LOOP_IGNORE]) return;
 
+    if (node.trailingComments) {
+      node.trailingComments.forEach(comment => {
+        comment.value = comment.value.replace(/\n/g, "");
+      });
+    }
+
```
Comment (sarupbanskota) [inline packages/babel-plugin-transform-es2015-block-scoping/src/index.js]: For this to function properly, you need to locally replace the `babel-generator` lib's `index.js` with the lib built with the code in this branch

**Comment by sarupbanskota** [comment]
@jridgewell I'm gonna go sleep now, so just leaving a note for you:

https://github.com/babel/babel/pull/5950#discussion_r127546940 is solved. The problem left to solve is: how do we remove newlines before/after `BlockComment`, only within `"BreakStatement|ContinueStatement|ReturnStatement"`. (assuming for other node types the mandatory newline is for a good reason)

File: packages/babel-generator/test/fixtures/parentheses/break-statement/expected.js (hunk 2 above)
Comment (jridgewell) [inline packages/babel-generator/test/fixtures/parentheses/break-statement/expected.js]: Just good formatting. I'd like to keep it if we're in between statements, but it shouldn't apply if we're in an expression.

**Comment by sarupbanskota** [comment]
http://astexplorer.net/#/gist/bc452ed08e49572e781845fb6398353c/08e03696fba7f67e52410cb463a85c69d48d1a70 if i visit the `break` in the AST, the `label` property is `null`

as opposed to, http://astexplorer.net/#/gist/3c80e5858c2d70f9a355c4dc72f96d24/eb7eb5586030dfe588d4ed917fafde3b5d1a8817 where the `break` property recognises it's label. 

looks like I'll need to fix Babylon to recognise the label for the first case too

**Comment by loganfsmyth** [comment]
That parser behavior is expected unfortunately, that's the other edge case we'll need to work around. Newlines aren't allowed between `break` and `label`, even in comments. I wasn't sure about that, but reading through the spec and testing in Chrome that appears to be the case.

**Comment by sarupbanskota** [comment]
If newlines aren't permitted between `break` and `label`, any `break` that has a `label` cannot have a `trailingComment` that is both `BlockComment`  and has a `\n` within.

So:

```js
label: for (const a of [1, 2, 3]) {
  break /*multi
  line*/label;
}
```
would be invalid. But for us to tell that this case is invalid, we'll need to look for whether this `break` has a `label`. The AST says `label` is `null` for this case. If that's expected how else could we approach? The only way I can think of is that somehow the `/n` needs to be stripped off before supplying it to the AST in cases where a `BlockComment` is trailing a `break`..

cc @loganfsmyth

**Comment by sarupbanskota** [comment]
```js
label: for (const a of [1, 2, 3]) {
  break /*multi
  line*/label;
}
```

this converts to 
```js
label: for (var a of [1, 2, 3]) {
  break; /*multi
         line*/
  label;
}
```

which as far as the spec goes, we're doing it right.

About throwing the error, https://github.com/babel/babel/pull/5950#issuecomment-315552840 is the difficulty, and if we do throw, won't we be raising a false error for those who intentionally did it that way?

**Comment by loganfsmyth** [comment]
> If newlines aren't permitted between `break` and `label`, any `break` that has a `label` cannot have a `trailingComment` that is both `BlockComment` and has a `\n` within.

There's something odd happening here. In this case it would be the `label` that has `leadingComments`. I'd expect a `trailingComments` property on `BreakStatement` to be printed at the very end of the statement, which means _after_ the label. ASTExplorer is producing what you're referring to, but if you run Babylon directly, you get what I expected. ASTExplorer wraps Babylon to use `recast` so that may be introducing confusion here.

```
require('babylon').parse(`
  label: do { break /* */ label; }while(false);
`).program.body[0].body.body.body[0];
```
has the `leadingComments` block on `Identifier`.

Perhaps the easiest way we could do this would be to introduce either a new utility method, or probably more easily, a parameter on `startTerminatorless` that toggles the behavior between "only labels allowed" and "any expression allowed". Then like we set

    this._parenPushNewlineState =

we could set

    this._noLineTerminator = true;

and inside the comment printing logic, we can check that flag and strip all newlines from the comments when needed.

File: packages/babel-generator/src/printer.js [hunk 4]
```diff
@@ -513,7 +513,7 @@ export default class Printer {
     );
   }
 
-  _printComment(comment) {
+  _printComment(comment, node) {
```
Comment (loganfsmyth) [inline packages/babel-generator/src/printer.js]: As mentioned in my last comment, I think we'd be best off not allowing the printer to know anything about the code. At the moment the `Printer` class has essentially zero node-specific logic, and I think it would be better to keep it that way.

So as mentioned, we could set a flag in `startTerminatorless` for the label case, and check that flag here instead of checking the node type.

**Comment by loganfsmyth** [comment]
Sorry, I made a mistake in part of my previous comment about `leadingComments`. Feel free to disregard what I said.

> If newlines aren't permitted between `break` and `label`, any `break` that has a `label` cannot have a `trailingComment` that is both `BlockComment` and has a `\n` within.

This statement isn't quite right. `break` statement `trailingComments` will render _after_ the semicolon, not between the `break` keyword and the label. It is the `label` has cannot have a `leadingComment` that is a LineComment or BlockComment with a newline in it.

File: packages/babel-generator/src/printer.js (hunk 4 above)
Comment (sarupbanskota) [inline packages/babel-generator/src/printer.js]: Ok agreed, I actually think of that, but I was done with this implementation by the time you commented 😅 

I'll try the approach you suggested!

Comment (loganfsmyth) [inline packages/babel-generator/src/printer.js]: Oh no worries, iterating on code is a fact of life :)

File: packages/babel-generator/src/printer.js [hunk 5]
```diff
@@ -291,18 +292,24 @@ export default class Printer {
    *  `undefined` will be returned and not `foo` due to the terminator.
    */
 
-  startTerminatorless(): Object {
-    return (this._parenPushNewlineState = {
-      printed: false,
-    });
+  startTerminatorless(key: string): Object {
+    if (key == "label") {
```
Comment (loganfsmyth) [inline packages/babel-generator/src/printer.js]: This still seems like an implementation detail to me, better to do

```
startTerminatorless(isLabel: boolean = false): Object {
```
with the `key` check staying in the calling function.

Comment (sarupbanskota) [inline packages/babel-generator/src/printer.js]: agreed, sending an update

**Comment by sarupbanskota** [comment]
@loganfsmyth @jridgewell - review once more, please!

**Comment by loganfsmyth** [comment]
Thanks!

**Comment by maxbates** [comment]
Is there any chance this could be merged into the 6.x stream? This is biting me too, but would prefer to move to babel 7 once it's out of alpha/beta.

**Comment by jridgewell** [comment]
Can you submit a PR?
