### PR TITLE
Correctly transpile when default parameter initializer references binding in rest pattern

### LINKED ISSUE #11281: `object-rest-spread` does not transpile correctly when binding is referenced in param initializer
## Bug Report

- [ ] I would like to work on a fix!

**Input Code**
- [REPL](https://babeljs.io/repl#?browsers=chrome%2080&build=&builtIns=false&spec=false&loose=false&code_lz=BQbwBAhgNGB08HkwF8YCMwF4wJgYy0gEosA-MEZIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cenv&prettier=false&targets=&version=7.8.7&externalPlugins=%40babel%2Fplugin-proposal-object-rest-spread%407.8.3%2C%40babel%2Fplugin-external-helpers%407.8.3)

```js
({ a, ...O }, b = O, c = a) => {}
```
**Current Behavior**
The code above is transformed to
```js
(_ref, b = O, c = a) => {
  let {
    a
  } = _ref,
      O = babelHelpers.objectWithoutProperties(_ref, ["a"]);
};
```
where initializers `b = O` and `c = a` no longer refers to the destructured params. 

**Expected behavior/code**
It should transformed to
```js
(function (_ref) {
  let { a } = _ref,
      O = babelHelpers.objectWithoutProperties(_ref, ["a"]);
  var b = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : O;
  var c = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : a;
});
```

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "plugins": { "@babel/proposal-object-rest-spread" }
}
```

**Environment**: REPL

**Possible Solution**
I haven't come up with a simple solution. Suggestions are welcome.

Solution 1: Fall back to `transform-parameters` when such pattern is detected

i) A function param declarator contains a RestElement.
ii) The declarator is also referenced by another params' initializers.

This solution will downgrade unnecessary codes, i.e.
```js
({ a, ...O }, b = 2, c = O) => {}
```
will be transformed to
```js
(function (_ref) {
  var a = _ref.a,
      O = babelHelpers.objectWithoutProperties(_ref, ["a"]);
  var b = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : 2;
  var c = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : O;
});
```
even when `b = 2` is supported on the target platform.

Solution 2: Extract `convertSingleParam` from `convertParams` defined in `transform-parameters`, apply `convertSingleParam` if one of params satisfies the pattern mentioned above. 

This solution should prevent downgrading the code as much as possible. i.e.
```js
({ a, ...O }, b = 2, c = O) => {}
```
should be transformed to
```js
(function (_ref, b = 2) {
 let { a } = _ref,
      O = babelHelpers.objectWithoutProperties(_ref, ["a"]);
   var c = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : O;
});
```

**Additional context/Screenshots**
This issue is discovered when I am investigating #11278.

### PR DESCRIPTION
**Pull request by vedantroy**
Note: If the title seems familiar, it is because I copied it from https://github.com/babel/babel/pull/11317, which I closed because I rewrote the code to a large degree, so the commit history was useless. Third time is the charm :upside_down_face:
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #11281 
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  | Yes
| License                  | MIT

Fixes the bug where `({ a, ...R }, b = R, c = a) => {}` was not transpiled correctly if `transform-function-parameters` was not enabled.

I fixed it by modifying `convertFunctionParams` to accept a function to transform rest elements.

### CODE REVIEW

File: packages/babel-plugin-proposal-object-rest-spread/src/index.js [hunk 1]
```diff
@@ -1,6 +1,7 @@
 import { declare } from "@babel/helper-plugin-utils";
 import syntaxObjectRestSpread from "@babel/plugin-syntax-object-rest-spread";
 import { types as t } from "@babel/core";
+import { convertFunctionParams } from "@babel/plugin-transform-parameters";
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-proposal-object-rest-spread/src/index.js]: You need to add this as a dependency in package.json

Comment (vedantroy) [reply packages/babel-plugin-proposal-object-rest-spread/src/index.js]: Fixed. For some reason I thought adding it as a dependency wouldn't work because on my previous branch when I tried `npm i -S @babel/plugin-transform-parameters` and `npm i -S @babel/helper-call-delegate` npm threw up due package-lock.json conflict.

Comment (JLHwung) [reply packages/babel-plugin-proposal-object-rest-spread/src/index.js]: The correct (by the book) recipe is
```sh
lerna add @babel/helper-call-delegate --scope=@babel/plugin-proposal-object-rest-spread
```
But I feel like it's too verbose and most of time I manually revise `package.json` and then run `yarn lerna bootstrap`.

We should state it clearly in `CONTRIBUTING.md`.

File: packages/babel-plugin-proposal-object-rest-spread/src/index.js [hunk 2]
```diff
@@ -213,8 +218,67 @@ export default declare((api, opts) => {
...
+            if (paramHasRestElement[i]) {
+              replaceRestElement(param.parentPath, param);
+            }
+          }
+        } else {
+          const shouldTransformParam = idx =>
+            idx >= i - 1 || paramHasRestElement[idx];
+          convertFunctionParams(
+            path,
+            false, // TODO: What should this value be?
```
Comment (JLHwung) [inline packages/babel-plugin-proposal-object-rest-spread/src/index.js]: I think it is okay to pass through `loose` here.

File: packages/babel-plugin-proposal-object-rest-spread/src/index.js [hunk 3]
```diff
@@ -213,8 +218,67 @@ export default declare((api, opts) => {
       // function a({ b, ...c }) {}
       Function(path) {
         const params = path.get("params");
-        for (let i = params.length - 1; i >= 0; i--) {
-          replaceRestElement(params[i].parentPath, params[i]);
+        const paramHasRestElement = [];
```
Comment (JLHwung) [inline packages/babel-plugin-proposal-object-rest-spread/src/index.js]: It suffices to model `paramHasRestElement` as `Set<number>` and to only include the index of which has rest element.

File: packages/babel-plugin-proposal-object-rest-spread/src/index.js [hunk 4]
```diff
@@ -213,8 +218,67 @@ export default declare((api, opts) => {
...
+          if (idInRest) assignPath.stop();
+        };
+
+        let i;
+        for (i = 0; i < params.length && !idInRest; ++i) {
+          const param = params[i];
+          if (!paramHasRestElement[i]) {
+            if (param.isAssignmentPattern()) AssignmentPatternHandler(param);
+            else {
+              param.traverse({ AssignmentPattern: AssignmentPatternHandler });
```
Comment (JLHwung) [inline packages/babel-plugin-proposal-object-rest-spread/src/index.js]: we need to skip scopables when doing sub-traverse:
```js
Scope(path) {
  path.skip()
}
```

i.e.
```js
({ ...R }, f = R => R) => {}
```

File: packages/babel-plugin-proposal-object-rest-spread/src/index.js (hunk 3 above)
Comment (vedantroy) [reply packages/babel-plugin-proposal-object-rest-spread/src/index.js]: Changed. I used an array of booleans instead of a set since the code was about the same length and I figured array access would be (very marginally) faster than set access.

**Comment by vedantroy** [comment]
Any more feedback?

File: packages/babel-plugin-proposal-object-rest-spread/src/index.js [hunk 5]
```diff
@@ -209,12 +214,76 @@ export default declare((api, opts) => {
...
+        }
+
+        // if true, a parameter exists that has an id in its initializer
+        // that is also an id bound in a rest parameter
+        // example: f({...R}, a = R)
+        let idInRest = false;
+
+        const IdentifierHandler = function(idPath) {
+          if (
+            (idPath.parentKey === "right" || idPath.parentKey === "value") &&
```
Comment (JLHwung) [inline packages/babel-plugin-proposal-object-rest-spread/src/index.js]: It does not suffice to check `parentKey` to determine if `idPath` is _referenced_. i.e.
```js
({ ...R }, a = f(R)) => {}
({ ...R }, { [R.key]: a }) => {}
```

We can check if an identifier is referencing the rest param binding via `scope`, like what we did in
https://github.com/babel/babel/blob/548cb3ee89552ffc08ee5625b084bd33f8107530/packages/babel-plugin-transform-parameters/src/params.js#L26
```js
{
  "ReferencedIdentifier|BindingIdentifier"(path, state) {
      // state.scope is the function scope
      // path.scope is the scope of current traversed identifier
      scope.getBinding(name) === state.scope.getBinding(name) && // referencing the binding accessible from function scope
      state.scope.hasOwnBinding(name) && // the binding is owned by the function scope
      idsInRestParams.has(name) // it a binding introduced by the rest param
    }
}
```

And similar to #11349, if we are doing on this approach, we shall skip type annotations and type parameters.

Comment (vedantroy) [reply packages/babel-plugin-proposal-object-rest-spread/src/index.js]: Fixed. I swear every time I think I need to do something manually, Babel's path/visitor api proves me wrong and gives me a shorter solution.
