### PR TITLE
fix: handle tokens for invalid template element

### LINKED ISSUE #14054: [Bug]: Unexpected error thrown when parsing broken template literal
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
require('@babel/parser').parse('`\\u{prettier}`', {tokens: true, errorRecovery:true})
```

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

```text
Uncaught TypeError: Cannot read properties of null (reading 'charCodeAt')
    at babel7CompatTokens (<CWD>\node_modules\@babel\parser\lib\index.js:13359:21)
    at Parser.parseTopLevel (<CWD>\node_modules\@babel\parser\lib\index.js:13430:44)
    at Parser.parse (<CWD>\node_modules\@babel\parser\lib\index.js:15202:10)
    at Object.parse (<CWD>\node_modules\@babel\parser\lib\index.js:15254:38)
```

### Environment

- Babel `v7.16.5`

### Possible solution

_No response_

### Additional context

This only happens, when `{tokens: true, errorRecovery:true}`

```text
 require('@babel/parser').parse('`\\u{prettier}`', {errorRecovery:true})
Node {
  type: 'File',
  start: 0,
  end: 14,
  loc: SourceLocation {
    start: Position { line: 1, column: 0 },
    end: Position { line: 1, column: 14 },
    filename: undefined,
    identifierName: undefined
  },
  errors: [
    SyntaxError: Invalid escape sequence in template. (1:2)
 ...
```

```text
 require('@babel/parser').parse('`\\u{prettier}`', {tokens: true})
Uncaught [SyntaxError: Invalid escape sequence in template. (1:2)
] {
  loc: Position { line: 1, column: 2 },
  pos: 2,
  code: 'BABEL_PARSER_SYNTAX_ERROR',
  reasonCode: 'InvalidEscapeSequenceTemplate'
}
```

I believe this caused by #13919 @JLHwung

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #14054 
| Patch: Bug Fix?          | Y
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

This PR fixes a regression introduced at #13919. We skip evaluating the template value when a template element is invalid, i.e. it may contain invalid Unicode escape or octal escape.

Since Babel parser updates have broken prettier for several times (https://github.com/babel/babel/issues?q=is%3Aissue+label%3A%22i%3A+regression%22+prettier+label%3A%22pkg%3A+parser%22), I plan to add prettier-e2e test in another PR so hopefully a babel parser patch release will not break prettier in the future.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14055"></a>

### CODE REVIEW

**Review by nicolo-ribaudo — APPROVED** [review]

File: packages/babel-parser/src/parser/statement.js [hunk 1]
```diff
@@ -135,7 +135,7 @@ function babel7CompatTokens(tokens) {
             // ends with '`'
             templateElementEnd = end - 1;
             templateElementEndLoc = createPositionWithColumnOffset(loc.end, -1);
-            templateValue = value.slice(1, -1);
+            templateValue = value === null ? null : value.slice(1, -1);
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/src/parser/statement.js:138]: Nit: we can use `value?.slice`

**Review by existentialism — APPROVED** [review]

File: packages/babel-parser/src/parser/statement.js (hunk 1 above)
Comment (JLHwung) [reply packages/babel-parser/src/parser/statement.js:138]: I don't think so. We need returning `null` when `value` is `null`.
