### PR TITLE
Fix location/range on TypeScript ExportNamedDeclarations

### LINKED ISSUE #9399: @babel/parse(ts): Declare keyword is not included to range exported node in TypeScript
## Bug Report

**Current Behavior**
Babel does not include range of `declare` keyword to range exported node

exported node contains property `declare=true`

**Input Code**
```ts
export declare const foo = ''
```
```ts
export declare enum foo {}
```
```ts
export declare class foo {}
```

**Expected behavior/code**
Range of exported node should contain `declare` keyword

**Babel Configuration (.babelrc, package.json, cli command)**

```js
  const babel = require('@babel/parser');
  const plugins: ParserPlugin[] = [
    'typescript',
    'objectRestSpread',
    'decorators-legacy',
    'classProperties',
    'asyncGenerators',
    'dynamicImport',
    'estree',
    'bigInt',
    'importMeta'
  ];
  if (jsx) {
    plugins.push('jsx');
  }

  return babel.parse(text, {
    sourceType: 'unambiguous',
    allowImportExportEverywhere: true,
    allowReturnOutsideFunction: true,
    ranges: true,
    plugins
  });
```

**Environment**
- Babel version(s):  7.3.0
- Node/npm version: 6-11
- OS: ----
- Monorepo: ---
- How you are using Babel: @babel/parser -> `parse`

**Additional context/Screenshots**
https://astexplorer.net/#/gist/a748e5502863178b7d0d6dabd74c1900/6c73fa77be54cfbc8566ce5887944a93ea20ed99
issue is present in both 7.3 and 7.2

### PR DESCRIPTION
**Pull request by existentialism**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #9399
| Patch: Bug Fix?          | Y
| Major: Breaking Change?  | N
| Minor: New Feature?      | N
| Tests Added + Pass?      | Y/Y
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

File: packages/babel-parser/src/plugins/typescript.js [hunk 1]
```diff
@@ -1853,10 +1853,21 @@ export default (superClass: Class<Parser>): Class<Parser> =>
...
+      const startLoc = this.state.startLoc;
+
       // "export declare" is equivalent to just "export".
       const isDeclare = this.eatContextual("declare");
 
+      // Reset location to include `declare` in range
+      if (isDeclare) {
+        this.state.start = startPos;
+        this.state.startLoc = startLoc;
+      }
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/src/plugins/typescript.js]: I think that it would be better not to mock `this.state` and set the correct start to the `declaration` node after that it is parsed.

Comment (existentialism) [reply packages/babel-parser/src/plugins/typescript.js]: Updated helper to support `range` option
