### PR TITLE
Fix traverse NodePath caching

### LINKED ISSUE #17563: Strange cache in Babel 8 Beta 3
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

When I traverse AST with `noScope` it somehow cached inside AST, so next traverse also works without scope.

If I use `JSON.parse(JSON.stringify(ast))` everything works good. I'm not sure is it a bug or feature, but all previous versions of Babel 8 and Babel 7 (including `v7.28.5`) has no such cache.

### Input code

```js
import * as parser from "@babel/parser";
import traverse from "@babel/traverse";
import * as t from "@babel/types";

const code = `
    export const a = 1;
    const b = a;
`;

const ast = parser.parse(code, {
    sourceType: "module",
});

traverse(ast, {
    noScope: true,
    Identifier(path) {
        console.log("Found identifier:", path.node.name);
    }
});

traverse(ast, {
  Identifier(path) {
    console.log("Found identifier:", path.node.name);
    path.scope.getOwnBinding('a');
  }
});
```

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

current:

```js
Found identifier: a
Found identifier: b
Found identifier: a
Found identifier: a
file:///Users/coderaiser/babel/node_modules/@babel/traverse/lib/index.js:1521
    return this.bindings[name];
                        ^

TypeError: Cannot read properties of undefined (reading 'a')
    at Scope.getOwnBinding (file:///Users/coderaiser/babel/node_modules/@babel/traverse/lib/index.js:1521:25)
    at Identifier (file:///Users/coderaiser/babel/1.mjs:30:32)
    at NodePath._call (file:///Users/coderaiser/babel/node_modules/@babel/traverse/lib/index.js:4896:20)
    at _visit (file:///Users/coderaiser/babel/node_modules/@babel/traverse/lib/index.js:4822:15)
    at _visitPaths (file:///Users/coderaiser/babel/node_modules/@babel/traverse/lib/index.js:4789:9)
    at _traverse (file:///Users/coderaiser/babel/node_modules/@babel/traverse/lib/index.js:4860:11)
    at _visit (file:///Users/coderaiser/babel/node_modules/@babel/traverse/lib/index.js:4824:21)
    at _visitPaths (file:///Users/coderaiser/babel/node_modules/@babel/traverse/lib/index.js:4789:9)
    at _traverse (file:///Users/coderaiser/babel/node_modules/@babel/traverse/lib/index.js:4858:11)
    at _visit (file:///Users/coderaiser/babel/node_modules/@babel/traverse/lib/index.js:4824:21)

Node.js v24.8.0
```

Expected:

```js
Found identifier: a
Found identifier: b
Found identifier: a
Found identifier: a
Found identifier: b
Found identifier: a
````

### Environment

Latest version of babel (beta 3)

### Possible solution

_No response_

### Additional context

_No response_

### LINKED ISSUE #17567: Babel 8 Beta 3: `TypeError: Cannot read properties of null (reading 'isMethod')`
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```js
import * as parser from "@babel/parser";
import traverse from "@babel/traverse";
import * as t from "@babel/types";

const code = `
    const a = {
        "files": [],
    }
`;

const ast = parser.parse(code, {
  sourceType: "module",
});

traverse(ast, {
  ObjectProperty(path) {
      traverse(path.node, {
          noScope: true,
          ArrayExpression(path) {
              console.log('x');
          }
      });
  }
});
```

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

Current:

```js
file:///Users/coderaiser/putout/node_modules/@babel/traverse/lib/index.js:4955
  if ((this.key === "key" || this.listKey === "decorators") && path.isMethod() || this.key === "discriminant" && path.isSwitchStatement()) {
                                                                    ^

TypeError: Cannot read properties of null (reading 'isMethod')
    at NodePath.setScope (file:///Users/coderaiser/putout/node_modules/@babel/traverse/lib/index.js:4955:69)
    at NodePath.setContext (file:///Users/coderaiser/putout/node_modules/@babel/traverse/lib/index.js:4976:12)
    at NodePath.pushContext (file:///Users/coderaiser/putout/node_modules/@babel/traverse/lib/index.js:5028:8)
    at _visitPaths (file:///Users/coderaiser/putout/node_modules/@babel/traverse/lib/index.js:4781:19)
    at _traverse (file:///Users/coderaiser/putout/node_modules/@babel/traverse/lib/index.js:4860:11)
    at traverseNode (file:///Users/coderaiser/putout/node_modules/@babel/traverse/lib/index.js:4875:12)
    at traverse (file:///Users/coderaiser/putout/node_modules/@babel/traverse/lib/index.js:5106:3)
    at ObjectProperty (file:///Users/coderaiser/putout/1.mjs:17:7)
    at NodePath._call (file:///Users/coderaiser/putout/node_modules/@babel/traverse/lib/index.js:4896:20)
    at _visit (file:///Users/coderaiser/putout/node_modules/@babel/traverse/lib/index.js:4822:15)
```
Expected:

```
x
```

### Environment

Babel 8 Beta 3

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by coderaiser**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #17567, Fixes #17563 
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

File: packages/babel-traverse/src/path/context.ts [hunk 1]
```diff
@@ -140,7 +140,8 @@ export function setScope(this: NodePath) {
 
   if (
     // Skip method scope if is computed method key or decorator expression
-    ((this.key === "key" || this.listKey === "decorators") &&
+    (path &&
+      (this.key === "key" || this.listKey === "decorators") &&
```
Comment (nicolo-ribaudo) [inline packages/babel-traverse/src/path/context.ts]: Could we instead do this?
```js
if (!path) {
  if (!this.isScope()) return;
} else if ( /* ... the existing if */ ) {
  path = path.parentPath;
}
```

Since if the current node is not a scope node and there is no parent, there is no way to actually define a scope.

**Comment by liuxingbaoyu** [comment]
Thanks!
The issue comes from here, https://github.com/babel/babel/blob/c776ee263c5d8c71a54ab988859b8066a6085b59/packages/babel-traverse/src/path/context.ts#L137, but I forgot why I did that.

File: packages/babel-traverse/src/path/context.ts (hunk 1 above)
Comment (coderaiser) [reply packages/babel-traverse/src/path/context.ts]: @nicolo-ribaudo Just made changes

**Comment by liuxingbaoyu** [comment]
We can just revert the change in https://github.com/babel/babel/blob/c776ee263c5d8c71a54ab988859b8066a6085b59/packages/babel-traverse/src/path/context.ts#L137 and it seems the tests still pass.

**Comment by coderaiser** [comment]
@liuxingbaoyu should I just remove this line instead of checking `path`?

**Comment by liuxingbaoyu** [comment]
Removing the `!process.env.BABEL_8_BREAKING` check should fix this regression.
This was added in https://github.com/babel/babel/pull/17043.
But please don't merge it yet; I'll try again later to see if there are any other issues.

**Comment by coderaiser** [comment]
@liuxingbaoyu as I see only removing check for `!process.env.BABEL_8_BREAKING` makes test fail, we also pass `BABEL_8_BREAKING` to run the test:

```js
make build && BABEL_8_BREAKING=true yarn jest babel-traverse
```

So with this line or without, additional check for `path` is still neaded.

**Comment by JLHwung** [comment]
Pending @liuxingbaoyu's investigation result.

**Comment by liuxingbaoyu** [comment]
Well, `forceSetScope` is back. 🤦‍♂️
This is a bit complicated. I'll try to explain it.

I added `forceSetScope` or `!process.env.BABEL_8_BREAKING &&` because `noScope` polluted the cache.
Later, we stopped using `noScope` in `traverse.hasType`, and the issue in tests no longer appeared.
The issue reappeared in https://github.com/babel/babel/issues/17563.

The fix we made in this PR conflicts with https://github.com/babel/babel/pull/17565, preventing it from fixing https://github.com/babel/babel/issues/17563.
So I merged them into this PR.
