### PR TITLE
Fix decorators interaction with abstract/declare fields

### LINKED ISSUE #17942: Decorators conflicts with `abstract` fields - trying to initialize with `_initProto` and compiler throws
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

Minimal reproduction:

```ts
function getterDecorator<T>(get: () => T, context: ClassGetterDecoratorContext) {
  return function (this: any) {
    return get.call(this);
  };
}

export abstract class Foo {
  abstract readonly test: number;

  @getterDecorator
  get test2(): number {
    return 1;
  }
}
```

This will not compile:

```
[PARSE_ERROR] Error: Property 'test' cannot have an initializer because it is marked abstract.
    ╭─[ <...>/test.ts:28:21 ]
    │
 28 │   abstract readonly test: number = void _initProto(this);
    │                     ──┬─
    │                       ╰───
────╯
```

Seems like using decorators is modyfing the class by addinig initiators, which is forbidden for abstract fields.

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

I'd expect abstract fields not being initialized, or in optimal scenario not having initializers at all, but rather having implementation of getter changed by compiler to avoid 1000s of initializers being called on each property each time I create a new instance.

### Environment

babel: 7.18.5
node 22.5
yarn 4.11
macOS, monorepo (yarn)

### Possible solution

As a workaround I can modify my code to use abstract methods instead of abstract getters

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | `Fixes #1, Fixes #2` 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

Fixes #17942

### CODE REVIEW

File: packages/babel-helper-create-class-features-plugin/src/decorators.ts [hunk 1]
```diff
@@ -1363,6 +1365,14 @@ function transformClass(
       const isPrivate = key.type === "PrivateName";
 
       const kind = getElementKind(element);
+      if (kind === FIELD_IGNORED) {
+        if (hasDecorators) {
+          throw element.buildCodeFrameError(
+            "Class elements marked with 'declare' or 'abstract' cannot be decorated.",
```
Comment (JLHwung) [inline packages/babel-helper-create-class-features-plugin/src/decorators.ts]: I think this error should be moved to the parser. TSC forbids such errors, too:

https://www.typescriptlang.org/play/?#code/MYGwhgzhAEDC0G8BQ1XQAIBMCmxpgCMIAXAJzGGPwG4U0tdodQxTtoDaBfIA

**Review by JLHwung — COMMENTED** [review]
It seems to me that this PR does not quite fix the original issue.

To recap, we injected the protoInitCall, one of the `fieldInitializerExpressions` to a non-static field:

https://github.com/babel/babel/blob/508caa2a2e4969858c6ea7ae65fd2c3efd6afb12/packages/babel-helper-create-class-features-plugin/src/decorators.ts#L1539-L1549

The original issue does not provide the config required to reproduce the error. I tried a bit on REPL and I can only reproduce the error when we keep the typescript syntax but transform the decorators ([link](https://babeljs.io/repl#?config_lz=N4IgZglgNgpgdgQwLYxALhAJxgBygOgCsBnEAGhB22JgBdS0BtRkeAN3NFoUwHM6GIACYwwCAK5R6ZAARwA9rRkQYMgIxrZCpSoD6SeQCN1a8iANDJMBmKg0AvgF1HFPON4Q4DZiAAChhEMYKAB6Nw84AFoqeRx5YgQoSJEAY3lMBFp00jJQNhhMYgh5OHQQACYABnKAZkiNECcyFn9A4LCod09I4gBPOG4AD0jaXpxrFMwIHFpOJxcQYnlxTBSYABUx1AwLKzMEYmJxJBnir3RQGloABXFDKAgUgGEoA-IAMRUoIQZaTHEYPZ7EA&code_lz=GYVwdgxgLglg9mABAcwKZSqgTgEVROLAQykIB4AVAPgAo0oAuRGgSkQF4rEKAaRAsJgAejRAGEANkQDO0gOLpMufIRKExCYVDYBvALAAoRIizoQWJKEiwEzKAAsY0pkTABPXYePHTUc0noAOggiCQkaBycWAG4vRABfWIN4w0NUIQAHQihEIgAjaShiaH4pWUQAMTg4RH0jXIKiohLTIgATBAk3RExCpjAQAFs87CS4gAF6JTwCYlIsOPoe1EKAJlZ-oZGsWrifMwtEAEYk4xTkoA&lineWrap=true&version=7.29.2)) And the posted error stacktrace does look like a third-party TS parser, which means the user might have kept the TS syntax and fed the Babel output to another TS aware tool.

Previously we disallowed untransformed TS class features in `packages/babel-helper-create-class-features-plugin/src/typescript.ts`, maybe we can guard the abstract field as well. Alternatively, we can also skip TS abstract field / declared field / finite field in the decorators transform.

**Comment by nicolo-ribaudo** [comment]
This PR fixes the case in which you only transpile decorators and not TS. I suspect that the original issue is using Babel to transpile decorators, and then feeding the output into Oxc to transpile the rest.

> Alternatively, we can also skip TS abstract field / declared field / finite field in the decorators transform.

Uhm, isn't this what this PR does? We skip abstract/declare fields in the loop so that we don't attach the `fieldInitializerExpressions` to them.

---

I'll split the parser changes into a separate PR: https://github.com/babel/babel/pull/17949

**Comment by JLHwung** [comment]
> This PR fixes the case in which you only transpile decorators and not TS. I suspect that the original issue is using Babel to transpile decorators, and then feeding the output into Oxc to transpile the rest.
> 
> > Alternatively, we can also skip TS abstract field / declared field / finite field in the decorators transform.
> 
> Uhm, isn't this what this PR does? We skip abstract/declare fields in the loop so that we don't attach the `fieldInitializerExpressions` to them.
> 
> I'll split the parser changes into a separate PR: #17949

Thank you, yeah the split changes are much easier to review.

**Review by JLHwung — APPROVED** [review]

**Review by liuxingbaoyu — APPROVED** [review]
