### PR TITLE
fix: disable caching when babel could not read/write cache

### LINKED ISSUE #6906: @babel/register crashes when node_modules/.cache folder is not writable
Bug report.

`@babel/register` crashes when the `node_modules/.cache` folder is not writable. This can happen if the node process is running as a different user than the user who owns the `node_modules` folder.

### Babel Register Configuration

The specifics of my config are not relevant to this issue, but here it is anyway.

```js
babelRegister({
  only: [/views/, /lib/],
  extensions: ['.js', '.mjs']
})
```

### Expected Behavior

I noticed that `@std/esm` also uses the `node_modules/.cache` folder, but it recovers gracefull when this folder is not writable, probably falling back to another folder or simply disabling the cache. This seems like much better behavior than crashing the process.

### Current Behavior

The process crashes when `node_modules/.cache` is not writable.

### Context

I run my production Node.js process as the `www-data` user, which does not have permission to write to the app folder, including the `node_modules` folder. Therefore, `@babel/register` is unable to write into the `node_modules/.cache` folder.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  @babel/core@7.0.0-beta.32 
| Babel-register | @babel/register@7.0.0-beta.32
| Babylon          | 
| node             | 8.9.0
| npm              | 5.5.1
| Operating System | macOS 10.13.1

### LINKED ISSUE #9649: Stack overflow exception when using Azure Run from Package feature
## Bug Report

**Current Behavior**
When using Azure DevOps to deploy to an Azure App Service or Function the default deployment method is `Run from Package`.
This will simply deploy a zip file with your whole web-app. This zip gets mounted as a read-only `wwwroot` directory.
The problem is that babel tries to write a cache file in the read-only directory. For some reason this generates a stack exception in the `mkdirp`.

**Expected behavior/code**
I expect a warning that tells me the cache file could not be created and caching will not be used.

**Current Solution**
I have succesfully used the `BABEL_CACHE_PATH` setting to point to a location outside of the default Azure `wwwroot` directory.

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #6906, fixes #9649 
| Patch: Bug Fix?          | Yes
| Tests Added + Pass?      | Added test on permission issues
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

In this PR we catch the IO error and disable caching when permission issue arises, or it the cache path resides in a readonly filesystem.

The following `existsSync` usage
```js
if (fs.existsSync(file)) {
  fs.readFileSync(file)
}
```
is also replaced as it introduces duplicate IO operations. In general [`fs.existsSync`](https://nodejs.org/api/fs.html#fs_fs_exists_path_callback) should only be used
> if the file won’t be used directly, for example when its existence is a signal from another process.

In the future I will open a separate PR to replace all similar usage in our codebase.

### CODE REVIEW

File: packages/babel-register/src/cache.js [hunk 1]
```diff
@@ -32,27 +38,66 @@ export function save() {
...
+        cacheDisabled = true;
+        return;
+      default:
+        throw e;
+    }
   }
+
+  try {
+    data = JSON.parse(cacheContent);
+  } catch (err) {}
```
Comment (nicolo-ribaudo) [inline packages/babel-register/src/cache.js]: Nit:

```suggestion
  } catch {}
```

I'm surprised that eslint doesn't warn about the unused variable.

**Comment by nicolo-ribaudo** [comment]
Is it possible to add a test somehow?

File: packages/babel-register/src/cache.js (hunk 1 above)
Comment (JLHwung) [reply packages/babel-register/src/cache.js]: > eslint doesn't warn about the unused variable

Because optional catching binding is a stage-4 proposal?

File: packages/babel-register/src/cache.js [hunk 2]
```diff
@@ -32,27 +38,66 @@ export function save() {
...
+    switch (e.code) {
+      case "EACCES":
+      case "EPERM":
+        console.warn(
+          `Babel could not write cache to file: ${FILENAME} 
+due to a permission issue. Cache is disabled.`,
+        );
+        cacheDisabled = true;
+        break;
+      case "EROFS":
```
Comment (JLHwung) [inline packages/babel-register/src/cache.js]: Disclaimer: I have not tested on a readonly filesystem, this error code is copied from `man 2 open`
> [EROFS]            The named file resides on a read-only file system, and the file is to be modified.

**Comment by JLHwung** [comment]
@nicolo-ribaudo Added test on permission issues. On the readonly file system error, I think it is hard to reproduce on unit testing.

File: packages/babel-register/test/cache.js [hunk 3]
```diff
@@ -73,5 +73,42 @@ describe("@babel/register - caching", () => {
       expect(fs.existsSync(testCacheFilename)).toBe(true);
       expect(get()).toEqual({});
     });
+
+    it("should create the cache after load", cb => {
+      load();
+
+      process.nextTick(() => {
+        process.nextTick(() => {
```
Comment (nicolo-ribaudo) [inline packages/babel-register/test/cache.js]: [Q]: Why isn't one `nextTick` enough?

**Comment by nicolo-ribaudo** [comment]
@JLHwung The failing test on windows it a test of this PR.

File: packages/babel-register/test/cache.js (hunk 3 above)
Comment (JLHwung) [reply packages/babel-register/test/cache.js]: [A]: I thought the execution order of `next tick` tasks is not defined. Apparently I am wrong after reading https://nodejs.org/docs/latest/api/process.html#process_process_nexttick_callback_args, thank you for reminding me!

**Comment by JLHwung** [comment]
@nicolo-ribaudo The failing test on Windows is due to the following [caveats](https://nodejs.org/api/fs.html#fs_file_modes)
> on Windows only the write permission can be changed [by `fs.chmod`]

I guess that the read error could only occur when the file is owned by another user and have ACL settings excluding current user to read it. There is no `isReadable` mode on Windows.

As it is difficult to construct such example on Windows CI, I disable this test on Windows.
