### PR TITLE
Ensure `import()` is not transpiled in `babel-core` published source

### LINKED ISSUE #11958: babel.config.mjs not working
**Current behavior**
On node@14.8.0, I have 2 equivalent simple files: babel.config.cjs and babel.config.mjs (except for the exporting keyword)...

```js
const presets = [
  [
    "@babel/env",
    {
      targets: {
        edge: "10",
        firefox: "50",
        chrome: "60",
        safari: "11.1",
      },
      useBuiltIns: "usage",
      corejs: 2,
    }
  ]
];

module.exports = { presets };
```

commenting the mjs, everything works perfect doing npx babel src/index.js, while commenting the cjs one (enabling esm support), I get 
"Error: /Users/kotaro/Projects/ro/test/babel.config.mjs: Error while loading config - Cannot find module 'file:///Users/kotaro/Projects/ro/test/babel.config.mjs'
Require stack:
- /Users/kotaro/Projects/ro/test/node_modules/@babel/core/lib/config/files/import.js
- /Users/kotaro/Projects/ro/test/node_modules/@babel/core/lib/config/files/module-types.js
- /Users/kotaro/Projects/ro/test/node_modules/@babel/core/lib/config/files/configuration.js
- /Users/kotaro/Projects/ro/test/node_modules/@babel/core/lib/config/files/index.js
- /Users/kotaro/Projects/ro/test/node_modules/@babel/core/lib/index.js
- /Users/kotaro/Projects/ro/test/node_modules/@babel/cli/lib/babel/options.js
- /Users/kotaro/Projects/ro/test/node_modules/@babel/cli/lib/babel/index.js
- /Users/kotaro/Projects/ro/test/node_modules/@babel/cli/bin/babel.js"

Tracking the sources, it seems you guys are transpiling import into a require at https://github.com/babel/babel/blob/main/packages/babel-core/src/config/files/import.js:

```js
function import_(filepath) {
  console.log('000000', filepath);
  return Promise.resolve(`${filepath}`).then(s => _interopRequireWildcard(require(s)));
}
```
so that filepath is an absolute URL: { href: 'file:///Users/kotaro/Projects/ro/test/babel.config.mjs', ...} which seems to fail loading (yes, file is there).

Setting type: "module" in package json provokes same error

**Expected behavior**
babel should handle equivalently cjs and mjs if node version supports it

**Environment**
node@14.8.0

```
- Babel version(s): 7.11.1
- Node/npm version: [e.g. Node 14.8.0/npm 6.14.7]
- OS: OSX 10.13.4
- Monorepo: no
- How you are using Babel: cli ATM

**Possible Solution**


**Additional context**
Add any other context about the problem here. Or a screenshot if applicable

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #11958
| Patch: Bug Fix?          | Yes
| Tests Added + Pass?      | Yes
| License                  | MIT

#11879 introduced a regression: Since `@babel/core` is compiled with `gulp-babel`, which does not declare support of dynamic import, `import()` is transpiled in the published source: https://unpkg.com/browse/@babel/core@7.11.0/lib/config/files/import.js

This PR adds the extra caller data and also a hacky prepublish test to ensure that `.mjs` loading works in the published builds.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/11974"></a>

### CODE REVIEW

File: packages/babel-core/test/config-chain.js [hunk 1]
```diff
@@ -51,6 +53,31 @@ function loadOptionsAsync(opts) {
   return babel.loadOptionsAsync({ cwd: __dirname, ...opts });
 }
 
+async function loadOptionsAsyncInSpawedProcess({ filename, cwd }) {
+  // !!!! hack is coming !!!!
+  // remove this section when https://github.com/facebook/jest/issues/9430 is resolved
```
Comment (nicolo-ribaudo) [inline packages/babel-core/test/config-chain.js:58]: Nit: add a `TODO(Babel 8)` here. Hopefully we'll be able to update jest to a working version for Babel 8, and we'll catch this comment when checking if there is anything left to do for the major release. Worst case we'll defer removing this 😬

**Review by nicolo-ribaudo — APPROVED** [review]

File: packages/babel-core/test/config-chain.js (hunk 1 above)
Comment (JLHwung) [inline packages/babel-core/test/config-chain.js:58]:
```suggestion
  // todo(Babel 8): remove this section when https://github.com/facebook/jest/issues/9430 is resolved
```

**Review by piranna — APPROVED** [review]
