### PR TITLE
fix destructuring rest with template literal

### LINKED ISSUE #9834: Object rest syntax not transpiling correctly with dynamic properties
## Bug Report

**Current Behavior**
Assigning object values to dynamic variables while using object rest syntax results in transpiling code that looks like:

```js
// dynamic properties to be omitted from initialObject are simply undefined
_objectWithoutProperties(initialObject, ["undefined"]);
```

**Input Code**
- REPL or Repo link if applicable:
[here's a link to a complete reproduction in the REPL at babeljs.io](https://babeljs.io/repl#?babili=false&browsers=%20Chrome%20%3E%3D%2067%2C%20Firefox%20%3E%3D%2063%2C%20Edge%20%3E%3D%2017%2C%20Opera%20%3E%3D%2057%2C%20Safari%20%3E%3D%2011.1%0A&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABFApgZygeQLYygBQCc4AHFQ2dAChjDxgEMAbTAIwCsVoAaZdKANIoAngEpEAb0QAoRIgBuDQpNlzEAbQAGAEgmoMQ4QF80mgLoAuRMAa4mw7qrkA6V4X6qjiALyJa9ZjZOaABuaVUIBDQ4JhRnJjgAcyp3DFEw1XcoEEIwMKNwyLAMPgwgrigfFTk0GGwSaOKrdQByAAs4bHIW3hbsJUSUHsQWphg0BmGW1iUoKf7ExJghs0c5GzthAHEQYWaWslRCKYTx-ZREqYg2wjPejBQAd2WWs2kjDP0sXAJiMgplmgqF9yjwRrV6o0WqJwgB6WF-JDXYhdRAAExQ8igcBiaCsEg2MHsOz2iAAgoRCAxhFQAKyiArwxGIABCDFYKCYiAASgBRfAAGXxEIaUSsFKpNPpvEJxN24sp1LpDKAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=react%2Cenv&prettier=false&targets=&version=7.4.3&externalPlugins=). I've also included a screenshot below.

**Expected behavior/code**
As you can see at the REPL link above, babel tries to remove `'undefined'` properties from the `initialObject`, resulting in `rest` containing all of the `initialObject`'s properties. If you were to paste that code into chrome devtools, `rest` would correctly only contain `familyGuy`.

**Babel Configuration (.babelrc, package.json, cli command)**

The config is built-in to the REPL at the link above, but the `preset-env` is using the following browsers:

`Chrome >= 67, Firefox >= 63, Edge >= 17, Opera >= 57, Safari >= 11.1`

**Environment**
- Babel version(s): 7.4
- How you are using Babel: REPL

image

### PR DESCRIPTION
**Pull request by tanhauhau**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #9834 
| Patch: Bug Fix?          | 👍
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

File: packages/babel-plugin-transform-destructuring/test/fixtures/destructuring/issue-9834/input.js [hunk 1]
```diff
@@ -0,0 +1,6 @@
+function testOmitProperties(initialObject, testKey) {
+  var {
+    [`${testKey}s`]: family,
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-destructuring/test/fixtures/destructuring/issue-9834/input.js]: What is it was `${i++}`? It shouldn't increment it twice.

Comment (nicolo-ribaudo) [reply packages/babel-plugin-transform-destructuring/test/fixtures/destructuring/issue-9834/input.js]: > found this comment (#9416 (review)), wonder what is your plan, would like to work on it if I can

I'll talk with the team to check if they are ok with it :+1:

**Comment by existentialism** [comment]
thanks @tanhauhau!
