### PR TITLE
fix: Generate parentheses correctly

### LINKED ISSUE #16763: [Bug]: Failed to compile.
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

There is no specific code I can input here, it's hard to identify. We're using CRA and today after cleaning modules and lock file `@babel/generator` got updated from `7.25.0` to `7.25.4`. This caused the following error during building process:

```
Module parse failed: Unexpected token (419:26)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
|           e[_key - 1] = arguments[_key];
|         }
>         do for (s of i = t, e) t = t.replace(s[0], s[1]); while (t !== i);
|         return t;
|       },
```

### Configuration file name

.babelrc

### Configuration

```
{
  "plugins": [
    ["babel-plugin-transform-typescript-metadata"],
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-proposal-class-properties", { "loose": true }]
  ],
  "presets": [
    ["@babel/preset-env"],
    ["@babel/preset-react"],
    ["@babel/preset-typescript"]
  ]
}
```

### Current and expected behavior

Current behavior: fails to compile.
Excepted behavior: compiles successfully as in version `7.25.0`

### Environment

- System:
  - OS: macOS 14.5
- Binaries:
  - Node: 20.17.0 - /usr/local/bin/node
  - Yarn: 1.22.22 - /usr/local/bin/yarn
  - npm: 10.8.2 - /usr/local/bin/npm
- npmPackages:
  - @babel/generator: 7.25.4 => 7.25.4 
  - @babel/plugin-proposal-class-properties: ^7.18.6 => 7.18.6 
  - @babel/plugin-proposal-decorators: ^7.24.7 => 7.24.7 
  - @babel/plugin-proposal-private-property-in-object: ^7.21.11 => 7.21.11 
  - @babel/preset-env: 7.25.4 => 7.25.4 
  - @babel/preset-react: 7.24.7 => 7.24.7 
  - @babel/preset-typescript: ^7.24.7 => 7.24.7 
  - babel-plugin-transform-typescript-metadata: ^0.3.2 => 0.3.2 

### Possible solution

`SequenceExpression` function in `packages/babel-generator/src/node/parentheses.ts` returns wrong value.

### Additional context

For now we specify exact version `7.25.0` of `@babel/generator` in our `package.json` as temporary solution.

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #16763 
| Patch: Bug Fix?          | √
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | √
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

https://github.com/babel/babel/pull/16722

### CODE REVIEW

**Review by JLHwung — APPROVED** [review]
Can you also add a new test case for export declaration?
```js
export default (c, d);
```
Currently Babel generates invalid code, it should be one of the regressions introduced in #16722. 

Essentially we should check all the productions in the ES spec that are represented by the statement alias AST, if that production has an immediate child as a AssignmentExpression or LeftHandSideExpression per spec (which prohibits  SequenceExpression per Babel), then we should add it to the SequenceExpression's parentheses rule. It seems to me that this is the only one left.

File: packages/babel-generator/src/node/parentheses.ts [hunk 1]
```diff
@@ -301,6 +301,10 @@ export function SequenceExpression(
   if (parentType === "ClassDeclaration" || parentType === "ClassExpression") {
     return parent.superClass === node;
```
Comment (JLHwung) [inline packages/babel-generator/src/node/parentheses.ts:302]: It seems to me that if a SequenceExpression is an immediate child of Class, it must be the superClass, since the other productions are wrapped within either class element or the Decorator node.

If that's the case, then the `ClassExpression` branch can also be removed as it is already covered by the last return.

**Review by nicolo-ribaudo — APPROVED** [review]
Sorry for this 😅 Thanks for the quick fix! I'll release it now.
