### PR TITLE
Only allow Identifiers, Patterns and Rest in parameters of FunctionDeclarations

### LINKED ISSUE #4059: AST seems to allow MemberExpression in function parameter list (T7068)
> Issue originally made by Francisco (tolmasky)
### Bug information
- **Babel version:** 6.4.5
- **Node version:** 0.12.9
- **npm version:** 2
### Input code

``` js
https://runkit.com/tolmasky/babel-function-declaration-params-issue/1.0.0
```
### Description

require("babel-types").NODE_FIELDS.FunctionDeclaration.params.validate.chainOf[1].each lists “LVal”, which contains “MemberExpression"

This means that function parameters can be Member Expressions. This may totally be correct, but I am not familiar with this and certainly when you try to parse:

function a(a.b) { } it fails.

However, constructing that does not break validation, and get code generated (see reduction above in input code).

### PR DESCRIPTION
**Pull request by danez**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #4059
| Patch: Bug Fix?          | y
| Major: Breaking Change?  | n
| Minor: New Feature?      | n
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

File: packages/babel-types/src/definitions/core.js [hunk 1]
```diff
@@ -288,7 +288,7 @@ export const functionCommon = {
   params: {
     validate: chain(
       assertValueType("array"),
-      assertEach(assertNodeType("LVal")),
+      assertEach(assertNodeType("Identifier", "Pattern", "RestElement")),
```
Comment (nicolo-ribaudo) [inline packages/babel-types/src/definitions/core.js]: Also `TSParameterProperty`?

Comment (danez) [reply packages/babel-types/src/definitions/core.js]: Fixed
