### PR TITLE
Initialize NodePath context when using `getSibling`

### LINKED ISSUE #12383: BABEL_TRANSFORM_ERROR - babel traverse context -  cannot read property "removeBinding" of null
## Bug Report

**EDIT by @nicolo-ribaudo**

You can workaround this bug by making sure that `@babel/core` uses an older `@babel/traverse` version.
If you are using `yarn` you can specify `"@babel/traverse": "7.12.0"` in [`resolutions`](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/), otherwise you can try downgrading it as described by https://github.com/babel/babel/issues/12383#issuecomment-732049261.

---

https://github.com/babel/babel/pull/12331 after this pr

<details>

"This is technically a breaking change (we are changing the default value of a parameter in the public API), but I couldn't find anyone online using that parameter and I'm not sure why anyway would not wont it to use the correct context."

is there anyone that do code review, here @babel ?

What do you think about semver?

</details>

image

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #12383
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

When the `path` returned by `NodePath.get()` is passed back to plugins code, we must make sure to always initialize the `context` (otherwise it re-uses a possibly wrong cached contex).

I'm marking this PR as `i: regression` even if this bug was already present, because #12331 made it more common (`noScope: true` was almost ignored before that PR, while after that PR it's respected).

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/12387"></a>

### CODE REVIEW

File: packages/babel-traverse/test/family.js [hunk 1]
```diff
@@ -81,6 +82,32 @@ describe("path/family", function () {
...
+
+          const testPath = path.get("test");
+
+          testHasScope = !!testPath.scope;
+          consequentHasScope = !!testPath.getSibling("consequent").scope;
+        },
+      });
+
+      expect(testHasScope).toBe(true);
+      expect(consequentHasScope).toBe(true);
```
Comment (nicolo-ribaudo) [inline packages/babel-traverse/test/family.js:109]: Before this PR `consequentHasScope` is `false`.

**Review by existentialism — APPROVED** [review]

**Review by JLHwung — APPROVED** [review]
