### PR TITLE
Don't insert duplicated nodes when transforming function bind

### LINKED ISSUE #6458: BindExpression changed behavior between beta.0 and beta.2
bug report

transform-decorators-legacy is somehow broken in latest version and doesn't refer imported objects properly

### Input Code

```js
import Obj from "./file";

console.log(::Obj.method)
```

### Babel Configuration (.babelrc, package.json, cli command)

```json
{
  "plugins": [
    "transform-function-bind"
  ],
  "presets": ["env"]
}
```

### Expected Behavior

```js
"use strict";

var _file = _interopRequireDefault(require("./file"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

console.log(_file.default.method.bind(_file));
```

### Current Behavior

```js
"use strict";

var _file = _interopRequireDefault(require("./file"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

console.log(_file.default.method.bind(Obj));
```

### Possible Solution

```js
import * as Obj from "./file";

console.log(::Obj.default.method)
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            | 7.0.0-beta.2
| node             | 8.4.0
| npm              | 5.4.0
| Operating System | mac sierra

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #6458 
| Patch: Bug Fix?          | 👍
| Major: Breaking Change?  | 
| Minor: New Feature?      | 
| Tests Added + Pass?      | 👍
| Documentation PR         | 
| Any Dependency Changes?  | 

Another bug coming from duplicated nodes... :disappointed:

### CODE REVIEW

File: packages/babel-plugin-transform-function-bind/src/index.js [hunk 1]
```diff
@@ -16,7 +16,7 @@ export default function({ types: t }) {
 
   function inferBindContext(bind, scope) {
     const staticContext = getStaticContext(bind, scope);
-    if (staticContext) return staticContext;
+    if (staticContext) return t.cloneDeep(staticContext);
```
Comment (existentialism) [inline packages/babel-plugin-transform-function-bind/src/index.js]: cloneDeep strikes again!

**Comment by xtuc** [comment]
Thanks @nicolo-ribaudo. Tests are green, let's merge this.
