### PR TITLE
fix: Support auto accessors with TypeScript annotations

### LINKED ISSUE #15205: [Bug]: missing support for auto accessors with TypeScript annotations
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```ts
class Foo {
    accessor prop: string = 1;
}
```

### Configuration file name

_No response_

### Configuration

https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=MYGwhgzhAEBiD29oG8BQ0PTMYBTK8ATtAA6HwkBc0EALoQJYB2A5tALzQCMA3KgL6ogA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=true&timeTravel=false&sourceType=module&lineWrap=true&presets=stage-2%2Cstage-3%2Ctypescript&prettier=true&targets=&version=7.20.4&assumptions=%7B%7D

### Current and expected behavior

Current:
```
/repl.ts: Missing semicolon. (2:17)

  1 | class Foo {
> 2 |     accessor prop: string = 1;
    |                  ^
  3 | }
  4 |
```

Expected:
parses fine as it's [valid TS syntax](https://www.typescriptlang.org/play?ts=4.9.3#code/MYGwhgzhAEBiD29oG8CwAoaXpmMAplPAE7QAOx8ZAXNBAC7ECWAdgObQC80A5GDwG4MAXwxA)

### Environment

Website

### Possible solution

Add support for type annotations on auto-accessors when parsing TS

### Additional context

It looks like there [is support for TS modifiers including `abstract`](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=MYGwhgzhAEBiD29oG8BQ1oAcCuAjEAlsNGMMAKZTwBOW18mAjNALzSMDc6dBAbmABdyJMpQg06DAEyt2XDJnpDgQgCYiKVWooYBmWZ24QBgohrESdmACwH5WPIWLHTxUpvHb6mAKx3UAL6oqGC4xtSkAtCgkDAAQmC0aBih4ZHmWpKYXAFAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=true&timeTravel=false&sourceType=module&lineWrap=true&presets=stage-2%2Cstage-3%2Ctypescript&prettier=true&targets=&version=7.20.4&assumptions=%7B%7D), but type annotations are not allowed

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #15205 
| Patch: Bug Fix?          | √
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | √
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15209"></a>

### CODE REVIEW

**Review by JLHwung — DISMISSED** [review]

File: packages/babel-parser/test/fixtures/typescript/class/accessor-with-type/input.ts [hunk 1]
```diff
@@ -0,0 +1,3 @@
+class Foo {
+  accessor prop: number = 1;
```
Comment (JLHwung) [inline packages/babel-parser/test/fixtures/typescript/class/accessor-with-type/input.ts:2]: Can you add more test cases? So we can cover cases like static, private, computed, etc.

**Comment by JLHwung** [comment]
Apart from the parser bits, we should also extend the classMemberVisitors

https://github.com/babel/babel/blob/871fd5ec0c22829495d6a11b1729feb7e9e52ad7/packages/babel-plugin-transform-typescript/src/index.ts#L120

for ClassAccessorProperty.

**Review by JLHwung — COMMENTED** [review]
Good job. Can you add the following test cases?

## For transform
```js
class C {
  accessor a;
}
```
With `{ allowDeclareFields: false }`, we should not remove the accessor field.

2.
```ts
class C {
    accessor a!;
}
```
With `{ allowDeclareFields: false }`, we should not remove the definite accessor field.

## For parser
1.
```ts
class C {
    private accessor #p: any;
}
```
Accessibility modifier should not be used with private names.

2.
```ts
class C {
    accessor a!;
}
```
We should support the definite postfix (`!`) in accessor key.

3.
```ts
abstract class C {
    abstract accessor #a;
}
```
A private accessor should not have abstract modifier.

4.
```ts
declare class C {
  accessor x = 1;
}
```
An ambient accessor cannot have initializer.

5.
```ts
abstract class C {
  abstract accessor x = 1;
}
```
An abstract accessor cannot have initializer.

6.
```ts
declare class C {
  #x = 1;
}
```
An ambient private property cannot have initializer. (This issue is not related to this PR but would be great to included here, too)

7.
```ts
class C {
  accessor #x?;
}
```
An accessor can not be optional. We are currently throwing unexpected token at `?`. We can provide a better error here.

8.
```ts
class C {
  readonly accessor x;
}
```
An accessor can not be readonly.

**Comment by liuxingbaoyu** [comment]
Is `accesor` a misspelling of `accessor`?
I've noticed a lot of misinformation currently using this.😕

**Comment by JLHwung** [comment]
> accesor

Yeah, definitely a typo of accessor.

File: packages/babel-parser/src/parse-error/standard-errors.ts [hunk 2]
```diff
@@ -35,6 +35,7 @@ export default {
   AwaitNotInAsyncContext:
     "'await' is only allowed within async functions and at the top levels of modules.",
   AwaitNotInAsyncFunction: "'await' is only allowed within async functions.",
+  // TODO: Accesor -> Accessor
   BadGetterArity: "A 'get' accesor must not have any formal parameters.",
   BadSetterArity: "A 'set' accesor must have exactly one formal parameter.",
```
Comment (liuxingbaoyu) [inline packages/babel-parser/src/parse-error/standard-errors.ts:40]: This is kind of annoying, delaying to babel8 means we have to copy and paste a lot of tests, and modify it immediately I'm not sure if it will affect compatibility.

Comment (JLHwung) [reply packages/babel-parser/src/parse-error/standard-errors.ts:40]: We can do it in a separate PR. 

We don't have to defer to Babel 8: The error message improvement can be shipped in patch releases, since it is not part of our API protocol. This approach is also similar to how Node.js treats its error message.

File: packages/babel-parser/test/fixtures/typescript/class/accessor/input.ts [hunk 3]
```diff
@@ -0,0 +1,21 @@
...
+  accessor #prop3: number = 1;
+  accessor [prop4]: number = 1;
+  private accessor prop5: number = 1;
+  abstract accessor prop6: number;
+  declare accessor prop7: number;
+  private accessor #p: any;
+
+  accessor a!;
+  abstract accessor #s;
+  accessor #d?;
```
Comment (JLHwung) [inline packages/babel-parser/test/fixtures/typescript/class/accessor/input.ts:13]: This is not allowed in an abstract context. Can you update the test case?

Comment (liuxingbaoyu) [reply packages/babel-parser/test/fixtures/typescript/class/accessor/input.ts:13]: Are you saying `abstract accessor #s;`?

Comment (JLHwung) [reply packages/babel-parser/test/fixtures/typescript/class/accessor/input.ts:13]: Oh actually `accessor #d?` is not allowed in either abstract class or non-abstract class. It seems to me the test case `class/accessor` covers only valid cases, can we make it a separate invalid test case?

File: packages/babel-parser/test/fixtures/typescript/class/accessor-invalid/input.ts [hunk 4]
```diff
@@ -0,0 +1,15 @@
+abstract class Foo {
+  declare accessor prop7: number;
+  private accessor #p: any;
+
+  accessor a!;
```
Comment (JLHwung) [inline packages/babel-parser/test/fixtures/typescript/class/accessor-invalid/input.ts:5]: TS will throw `Declarations with definite assignment assertions must also have type annotations.`, we can address that in a separate PR.

File: packages/babel-parser/test/fixtures/typescript/class/accessor-invalid/input.ts [hunk 5]
```diff
@@ -0,0 +1,15 @@
+abstract class Foo {
+  declare accessor prop7: number;
```
Comment (JLHwung) [inline packages/babel-parser/test/fixtures/typescript/class/accessor-invalid/input.ts:2]: TS will throw "'accessor' modifier cannot be used with 'declare' modifier."

File: packages/babel-parser/test/fixtures/typescript/class/accessor-invalid/output.json [hunk 6]
```diff
@@ -0,0 +1,220 @@
+{
+  "type": "File",
+  "start":0,"end":239,"loc":{"start":{"line":1,"column":0,"index":0},"end":{"line":15,"column":1,"index":239}},
+  "errors": [
+    "SyntaxError: An 'accessor' property cannot be declared optional. (7:2)"
```
Comment (JLHwung) [inline packages/babel-parser/test/fixtures/typescript/class/accessor-invalid/output.json:5]: It seems that other errors are not reported.

Comment (liuxingbaoyu) [reply packages/babel-parser/test/fixtures/typescript/class/accessor-invalid/output.json:5]: Yes, I only reported that unrecoverable error.
Actually initially I also implemented another one, but then I thought they didn't matter.

Comment (JLHwung) [reply packages/babel-parser/test/fixtures/typescript/class/accessor-invalid/output.json:5]: Doesn't the `output.json` in parser tests only report recoverable errors unless one set `errorRecovery: false`? The unrecoverable error will be reported at `options.throw`.

Comment (liuxingbaoyu) [reply packages/babel-parser/test/fixtures/typescript/class/accessor-invalid/output.json:5]: I mean currently the only errors reported are from unrecoverable errors. And the rest are illegal but normal parsing, I don't think it matters, so they haven't been implemented.

Comment (liuxingbaoyu) [reply packages/babel-parser/test/fixtures/typescript/class/accessor-invalid/output.json:5]: > An accessor can not be optional. We are currently throwing unexpected token at ?. We can provide a better error here.

https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=MYGwhgzhAEDC0G8BQ1pmMAplA9gJ2gGIAPAfgG4kBfIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=stage-2&prettier=false&targets=Node-0&version=7.20.4&externalPlugins=&assumptions=%7B%7D

Comment (JLHwung) [reply packages/babel-parser/test/fixtures/typescript/class/accessor-invalid/output.json:5]: > And the rest are illegal but normal parsing

Although `tsc` parser is a loose parser, it does not necessarily mean it should not report errors. The `errorRecovery` option enables Babel the same tsc functionality: report errors without crashing the parser.

Generally the Babel parser does not report typing errors, such as "the call signature does not match the function interface": they are considered as "runtime errors" because these errors can only be reported from a typing system.

But for those errors that can be detected solely from AST, they are most static errors and thus they should be reported by the parser. We have reported similar errors, e.g. Babel throws "Private elements cannot have an accessibility modifier" for
```ts
class C {
  private #Q;
}
```
Therefore I am not convinced the idea that "the rest are illegal but normal parsing". If TS would ever have a spec, they should be early errors and a parser should report them.

Comment (liuxingbaoyu) [reply packages/babel-parser/test/fixtures/typescript/class/accessor-invalid/output.json:5]: I personally prefer to make unrecoverable errors recoverable, and normally parsed ts errors are not actively reported. (at least when no user requests these)
Because I believe all users will use tsc at the same time, and ts makes too many errors recoverable.

> My bad, by a better error message, I do mean that we can recover from this error and throw a recoverable error.

I've done this and the only error is from what you said.

**Comment by liuxingbaoyu** [comment]
Let's release this in the next patch release?

File: packages/babel-parser/src/plugins/typescript/index.ts [hunk 7]
```diff
@@ -90,12 +90,14 @@ const TSErrors = ParseErrorEnum`typescript`({
     propertyName: string;
   }) =>
     `Property '${propertyName}' cannot have an initializer because it is marked abstract.`,
-  AccesorCannotDeclareThisParameter:
+  AccessorCannotBeOptional:
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/src/plugins/typescript/index.ts:93]: We can (and should) fix the error messages now (i.e. `BadSetterArity`/`BetGetterArity`), but we should wait until Babel 8 to fix typos in error _codes_.

**Review by nicolo-ribaudo — APPROVED** [review]
As @JLHwung mentioned, we generally report errors for TypeScript errors which are more close to syntax errors than to type errors.

However, this PR is good enough to be merged, except that you need to update the error codes/messages.

File: packages/babel-parser/src/plugins/typescript/index.ts (hunk 7 above)
Comment (liuxingbaoyu) [reply packages/babel-parser/src/plugins/typescript/index.ts:93]: Do error codes refer to the property names? These seem to be only visible from the inside.

Comment (nicolo-ribaudo) [reply packages/babel-parser/src/plugins/typescript/index.ts:93]: Yes they are the property names; and they are public. For example, prettier relies on them: https://github.com/prettier/prettier/blob/b50dfd1974d33abb980e9b4df949913932eeb478/src/language-js/parse/babel.js#L183

**Comment by nicolo-ribaudo** [comment]
This should be included in the next patch if possible, since other tools are waiting on us.

**Review by JLHwung — APPROVED** [review]
