### PR TITLE
Fix parsing ts type casts and nested patterns in destructuring

### LINKED ISSUE #14504: [Bug]: `createParenthesizedExpressions` and parens around object rest
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
({ ...(z) } = {});
```

### Configuration file name

_No response_

### Configuration

```js
const { parse } = require("@babel/parser");

const input = `({ ...(z) } = {});`;

const result = parse(input, { createParenthesizedExpressions: true });

console.dir(result, { depth: null });
```

I didn't find a way to set `createParenthesizedExpressions` in Babel's REPL, however this issue manifests itself in Prettier ([playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAKYACAdD1AvASgwF8MBeDYYggbhABoQIAHGAS2gGdlQBDAJ34QA7gAUBCbil4AbYbwCe3RgCN+vMAGs4MAMq8AtnAAybKHGQAzWZzir1WnbuYazAc2Qx+AVzsg4BipwACbBIca8UG7evG5wAGIQ-Aa8MOxRyCC83jAQDCAAFjAGMgDqBWzwnC5gcLqSlWwAbpUKmWCcyiBmtvwwoupuKVY2fgBWnAAeuu4ycACK3hDwIzK2jC78vZkqvEEy+cz8ZjClbMEwBcgAHAAMG0K2perMmUdwvU0WjACOS-ADFhSLKcAC05hCIXy-DgfzYMIGsWGSGsaz8tgMbE8PnRswW-wsKNGjBgezOFyuSAATCT1GwZO4AMIQAzI-ycACs+W8tgAKnspKj1iAmr4AJJQMKwXRgY6sACCkt0MAUc1WtmIxCAA)).

### Current and expected behavior

Current: `SyntaxError: Invalid rest operator's argument.`
Expected: no error

### Environment

this doesn't depend on the environment

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes https://github.com/babel/babel/issues/14498, fixes #14504
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14500"></a>

### CODE REVIEW

File: packages/babel-parser/src/parser/lval.js [hunk 1]
```diff
@@ -625,7 +631,8 @@ export default class LValParser extends NodeUtils {
 
     const validity = this.isValidLVal(
       expression.type,
-      hasParenthesizedAncestor || expression.extra?.parenthesized,
+      !(hasParenthesizedAncestor || expression.extra?.parenthesized) &&
+        ancestor.type === "AssignmentExpression",
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/src/parser/lval.js:635]: This code was needed to disallow `a as b = c`, however we must now make sure to _not_ disallow `[a as b] = c`.

File: packages/babel-parser/test/fixtures/typescript/cast/unparenthesized-assert-and-assign/output.json [hunk 2]
```diff
@@ -3,8 +3,7 @@
   "start":0,"end":46,"loc":{"start":{"line":1,"column":0,"index":0},"end":{"line":2,"column":29,"index":46}},
   "errors": [
     "SyntaxError: Invalid left-hand side in assignment expression. (1:0)",
-    "SyntaxError: Invalid left-hand side in assignment expression. (2:6)",
-    "SyntaxError: Invalid left-hand side in object destructuring pattern. (2:6)"
+    "SyntaxError: Invalid left-hand side in assignment expression. (2:6)"
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/test/fixtures/typescript/cast/unparenthesized-assert-and-assign/output.json:6]: These two errors were at the same location.

It would be better to only keep the "object destructuring pattern" rather than "assignment expression", but it's quite complex because it requires delaying errors until we know what the outer object is (destructuring or object). I might improve it in a follow-up PR.

File: packages/babel-parser/src/parser/lval.js (hunk 1 above)
Comment (JLHwung) [reply packages/babel-parser/src/parser/lval.js:635]: Can you add a new test case?
```ts
for (a as b of []);
```
It is disallowed in 7.16.2 but tsc allows it, and it seems this PR also fixes this one, too.

**Review by JLHwung — APPROVED** [review]

**Review by existentialism — APPROVED** [review]

**Comment by nicolo-ribaudo** [comment]
cc @thorn0 I would appreciate if you could check if there is any missing new test!

**Comment by thorn0** [comment]
`({ ...[] }=x);` and `({ ...{} }=x);` should be errors, but they're parsed successfully if the `typescript` plugin is enabled. [REPL](https://babeljs.io/repl/build/51788/#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=BQbwBAdFDaC6YF8C8APAlAbgFCklECiqmQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ctypescript&prettier=false&targets=&version=7.17.9%2Bpr.14500&externalPlugins=&assumptions=%7B%7D)

**Comment by thorn0** [comment]
`(q as T)! = b`: [TS](https://www.typescriptlang.org/play?#code/DYUwLgBAjgUAFFCBDAzsgdgTwJQEIIC8EArugCYgBmAluiGUA), [Babel (this PR)](https://babeljs.io/repl/build/51788/#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=DYUwLgBAjgUAFFCBDAzsgdgTwJQEIIC8EArugCYgBmAluiGUA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ctypescript&prettier=false&targets=&version=7.17.9%2Bpr.14500&externalPlugins=&assumptions=%7B%7D)

**Comment by nicolo-ribaudo** [comment]
Thanks, fixed!

**Review by JLHwung — APPROVED** [review]

File: packages/babel-parser/test/fixtures/es2018/object-rest-spread/expression-rest-not-last-invalid/output.json [hunk 3]
```diff
@@ -23,7 +22,7 @@
             "start":1,"end":13,"loc":{"start":{"line":1,"column":1,"index":1},"end":{"line":1,"column":13,"index":13}},
             "properties": [
               {
-                "type": "SpreadElement",
+                "type": "RestElement",
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/test/fixtures/es2018/object-rest-spread/expression-rest-not-last-invalid/output.json:25]: This is a slight improvement, since it gives a better shape to the recovered AST (the input code is `({ ...rest, x } = {})`.

File: packages/babel-parser/src/parser/lval.js [hunk 4]
```diff
@@ -162,11 +171,10 @@ export default class LValParser extends NodeUtils {
       }
 
       case "SpreadElement": {
```
[the remark this answers is not in the document]
Comment (nicolo-ribaudo) [reply packages/babel-parser/src/parser/lval.js:166]: Done! 69719e4

**Review by JLHwung — APPROVED** [review]

**Review by existentialism — APPROVED** [review]

File: packages/babel-types/src/definitions/core.ts [hunk 5]
```diff
@@ -1191,6 +1206,9 @@ defineType("AssignmentPattern", {
         "ObjectPattern",
         "ArrayPattern",
         "MemberExpression",
+        "TSAsExpression",
+        "TSTypeAssertion",
```
Comment (JLHwung) [inline packages/babel-types/src/definitions/core.ts:1210]: Can AssignmengPattern.left be a TSTypeAssertion?

```ts
[<number>a = 1] = [42];
{<number>a = 1} = [42];
```
is invalid in TS nightly: https://www.typescriptlang.org/play?jsx=0&ts=4.7.0-dev.20220502#code/NoHgdgrgtgRgpgJwHwEMAEBeNBGAuptYAFgCZcBuAKAG9xp5l0tsBfA4s8oA
