### PR TITLE
[runtime-corejs3] Only polyfill instance methods when it might be needed

### LINKED ISSUE #9753: Critical dependency: the request of a dependency is an expression
## Bug Report

**Current Behavior**
No problem with `@babel/runtime-corejs2`,
but `@babel/runtime-corejs3`  will notice:
Critical dependency: the request of a dependency is an expression

**Input Code**
- REPL or Repo link if applicable:

```js
//@babel/runtime-corejs2
console.log(require("./locale/"+lan)) //no problem
console.log(require(`./locale/${lan}`))// no problem
//@babel/runtime-corejs3
console.log(require("./locale/"+lan)) //no problem
console.log(require(`./locale/${lan}`))// Critical dependency: the request of a dependency is an expression
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (.babelrc, package.json, cli command)**

```js
const utils = require("./build/utils");
const {
    polyfills,
    demandList
} = { polyfills: [
    'es.array.iterator',
    'es.promise',
    'es.promise.finally'
  ],
  demandList: [
    ["component", {
      libraryName: "antd",
      style: 'style/index.css'
    }, "ant"],
    ["component", {
      libraryName: 'vant',
      libDir: 'es',
      style: 'index.css',
    }, 'vant'],
    ["component", {
      libraryName: "mint-ui",
    }, 'mint-ui'],
    ["component", {
      libraryName: "element-ui",
      styleLibraryName: "theme-chalk"
    }, 'element-ui'],
    ["component", {
      style: false,
      camel2Dash: false,
      libraryName: 'lodash',
      libDir: '',
    }, 'lodash']
  ],};
let envOptions = {
    useBuiltIns: utils.isModernBuild() ? false : "usage",
    modules: false,
    debug: false,
    corejs: utils.isModernBuild() ? null : {
        version: 3,
        proposals: true
    },
    exclude: utils.isModernBuild() ? [] : polyfills,
}
if(utils.isModernBuild()){
    envOptions.targets = {
        esmodules: true
    }
}

const presets = [
    "@babel/preset-react",
    [
        "@babel/preset-env",
        envOptions
    ]
]
const plugins = [
    ...demandList,
    "@babel/plugin-syntax-dynamic-import",
    ["@babel/plugin-transform-runtime", {
        regenerator: envOptions.useBuiltIns !== 'usage',
        corejs: (envOptions.useBuiltIns === 'usage' && !utils.isModernBuild()) ? 3 : false,
        helpers: envOptions.useBuiltIns === 'usage',
    }]

]

!utils.isModernBuild() && plugins.push([require("./build/plugin/babel/polyfillsPlugin"), {
    polyfills
}])

module.exports = {
    presets,
    plugins
}
```

**Environment**
```
{
  "name": "webpack4-modern",
  "version": "0.0.1",
  "description": "learn webpack4 config change",
  "main": "index.js",
  "scripts": {
    "start": "cross-env NODE_ENV='development' webpack-dev-server --config build/webpack.dev.config.js --mode development --dll",
    "dev": "cross-env NODE_ENV='development' webpack-dev-server --config build/webpack.dev.config.js --mode development",
    "build": "cross-env NODE_ENV='production' webpack --config build/webpack.prod.config.js --mode production",
    "build:modern": "cross-env NODE_ENV='production' webpack --config build/webpack.prod.config.js --mode production --modern legacy && cross-env NODE_ENV='production' webpack --config build/webpack.prod.config.js --mode production --modern",
    "server": "http-server ./dist -g -o"
  },
  "keywords": [
    "webpack4",
    "cli",
    "modern"
  ],
  "author": "zr",
  "license": "ISC",
  "devDependencies": {
    "@babel/core": "^7.4.0",
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "@babel/plugin-transform-runtime": "^7.4.0",
    "@babel/preset-env": "^7.4.2",
...
  },
  "dependencies": {
    "@babel/runtime-corejs3": "^7.4.2",
    "core-js": "^3.0.0",
    "regenerator-runtime": "^0.13.2",
...
  }
}

```

**Possible Solution**

**Additional context/Screenshots**
微信图片_20190323184407

//@babel/runtime-corejs3
微信截图_20190323193330

//@babel/runtime-corejs2
微信截图_20190323193546

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #9753
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      | Yes?
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

This PR allows instance methods polyfills to specify on which base type they need to be applied. If Babel is 100% that it is called on another instance type, it will avoid polyfilling it.

For example, `"".concat` doesn't need to be polyfilled but `foo.concat` does because `foo` might be an array.
#9753 shows that polyfilling `.concat` breaks webpack logic to handle `require` calls with template literals.

Other instance methods could be optimized, but if this PR lands I'll leave it as a `[good first issue]` PR.

### CODE REVIEW

File: packages/babel-plugin-transform-runtime/test/fixtures/runtime-corejs3/instance-inference-optimization/input.js [hunk 1]
```diff
@@ -0,0 +1,3 @@
+"".concat(b);
+[].concat(b);
+a.concat(b);
```
Comment (danez) [inline packages/babel-plugin-transform-runtime/test/fixtures/runtime-corejs3/instance-inference-optimization/input.js]: Where are the type annotations coming from in this test?

The code seems to only work based on type annotations, but I don't see a single annotation here and it still works?

Comment (nicolo-ribaudo) [reply packages/babel-plugin-transform-runtime/test/fixtures/runtime-corejs3/instance-inference-optimization/input.js]: `getTypeAnnotation` isn't just an ast property accessor: it runs our rudimental type inference (https://github.com/babel/babel/tree/master/packages/babel-traverse/src/path/inference)

Comment (danez) [reply packages/babel-plugin-transform-runtime/test/fixtures/runtime-corejs3/instance-inference-optimization/input.js]: Ah interesting. 👍
