### PR TITLE
fix: do not eat get/set after async is parsed

### LINKED ISSUE #11914: @babel/parser throw an error when parsing object shorthand property async get () after updating to version 7.11.1
`index.js`
```js
export default {
  async get () {}
};
```
`package.json`
```json
{
  "name": "babel-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {},
  "devDependencies": {
    "@babel/cli": "^7.10.5",
    "@babel/core": "^7.10.3"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "babel": "babel index.js"
  },
  "author": "",
  "license": "ISC"
}
```

when running `npm run babel`, I got an error below
```bash
{ SyntaxError: /Users/icefox/Desktop/babel-test/index.js: Unexpected token (2:11)

  1 | export default {
> 2 |   async get () {}
    |             ^
  3 | };
    at Parser._raise (/Users/icefox/Desktop/babel-test/node_modules/_@babel_parser@7.11.1@@babel/parser/lib/index.js:763:17)
    at Parser.raiseWithData (/Users/icefox/Desktop/babel-test/node_modules/_@babel_parser@7.11.1@@babel/parser/lib/index.js:756:17)
    at Parser.raise (/Users/icefox/Desktop/babel-test/node_modules/_@babel_parser@7.11.1@@babel/parser/lib/index.js:750:17)
    at Parser.unexpected (/Users/icefox/Desktop/babel-test/node_modules/_@babel_parser@7.11.1@@babel/parser/lib/index.js:8930:16)
    at Parser.parseIdentifierName (/Users/icefox/Desktop/babel-test/node_modules/_@babel_parser@7.11.1@@babel/parser/lib/index.js:11017:18)
    at Parser.parseIdentifier (/Users/icefox/Desktop/babel-test/node_modules/_@babel_parser@7.11.1@@babel/parser/lib/index.js:10994:23)
    at Parser.parseMaybePrivateName (/Users/icefox/Desktop/babel-test/node_modules/_@babel_parser@7.11.1@@babel/parser/lib/index.js:10311:19)
    at Parser.parsePropertyName (/Users/icefox/Desktop/babel-test/node_modules/_@babel_parser@7.11.1@@babel/parser/lib/index.js:10795:155)
    at Parser.parsePropertyDefinition (/Users/icefox/Desktop/babel-test/node_modules/_@babel_parser@7.11.1@@babel/parser/lib/index.js:10708:14)
    at Parser.parseObjectLike (/Users/icefox/Desktop/babel-test/node_modules/_@babel_parser@7.11.1@@babel/parser/lib/index.js:10612:25)
  loc: Position { line: 2, column: 11 },
  pos: 28,
  code: 'BABEL_PARSE_ERROR' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! babel-test@1.0.0 babel: `babel index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the babel-test@1.0.0 babel script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/icefox/.tnpm/_logs/2020-08-05T05_53_09_257Z-debug.log
[tnpm] subprocess:/Users/icefox/.nvm/versions/node/v10.21.0/lib/node_modules/tnpm/lib/npm_child_process.js exit code: 1, signal: null
[tnpm] mainprocess exit code: 1
```

It works fine with `async` with property name except `get`, and older version of `@babel/parser`, and in latest chrome and node v8, it turns out a valid syntax

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #11914 
| Patch: Bug Fix?          | Yes
| Tests Added + Pass?      | Yes
| License                  | MIT

Fixed a regression introduced in #11871. When `async` is consumed, we should not unintentionally eat `set`/`get` because async accessor is not a thing in the spec.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/11916"></a>

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
We should release this PR later today

**Comment by RoXuS** [comment]
> We should release this PR later today

Save us :D

File: packages/babel-parser/src/parser/expression.js [hunk 1]
```diff
@@ -1754,7 +1754,7 @@ export default class ExpressionParser extends LValParser {
       }
       // get PropertyName[?Yield, ?Await] () { FunctionBody[~Yield, ~Await] }
       // set PropertyName[?Yield, ?Await] ( PropertySetParameterList ) { FunctionBody[~Yield, ~Await] }
-      if (prop.key.name === "get" || prop.key.name === "set") {
+      else if (prop.key.name === "get" || prop.key.name === "set") {
         isAccessor = true;
```
Comment (KFlash) [inline packages/babel-parser/src/parser/expression.js:1758]: There are 4 unnecessary member access. 2 unnecessary function call here that slow down on performance. Also 2x string comparison. No plans to optimize it?

Comment (JLHwung) [reply packages/babel-parser/src/parser/expression.js:1758]: Thanks! Will address in another PR.
