### PR TITLE
Correctly access shadowed class binding in `super.*`

### LINKED ISSUE #11994: Invalid class transform
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

When parameter name is same as class name, and `super` used, it transform into invalid code.

- [REPL](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=AQ4YwGwQwZx4BiB7JwDeAoUoC2BTAFwAskATACmSQEp0ttQAnQgV0YDtgYWAHPRgHT5iZSimoBuetgC-04DKA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ces2015%2Cenv&prettier=false&targets=&version=7.11.4&externalPlugins=)

**Input Code**

```js
    class Foo {
      method(Foo) {
        return super.method(Foo);
      }
    }
```

**Expected behavior**

```js
  // ...

  _createClass(Foo, [{
    key: "method",
    value: function method(Foo) {
      return _get(_getPrototypeOf(Foo.prototype), "method", this).call(this, Foo);
                                  ^^^^^^^^^^^^^ This is not right
    }
  }]);

  // ...
```

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

See Babel REPL

**Environment**

See Babel REPL

**Possible Solution**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Zzzen**
…#11994

| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #11994 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/12544"></a>

### CODE REVIEW

File: packages/babel-plugin-transform-classes/src/transformClass.js [hunk 1]
```diff
@@ -201,6 +206,24 @@ export default function transformClass(
...
+      Scopable(path) {
+        if (
+          path.type === "ClassDeclaration" ||
+          path.type === "ClassExpression"
+        ) {
+          path.skip();
+          return;
+        }
+
+        if (path.scope.hasOwnBinding(classState.classRef.name)) {
```
Comment (Zzzen) [inline packages/babel-plugin-transform-classes/src/transformClass.js:220]: Copied from https://github.com/babel/babel/blob/17d62c3743ca7c529bc14ddcb890a6a31ed956b1/packages/babel-plugin-transform-classes/src/transformClass.js#L499,L502


```ts
  /**
   * Replace the constructor body of our class.
   */
  function pushConstructor(
    superReturns,
    method: { type: "ClassMethod" },
    path: NodePath,
  ) {
    // https://github.com/babel/babel/issues/1077
    if (path.scope.hasOwnBinding(classState.classRef.name)) {
      path.scope.rename(classState.classRef.name);
    }
    // ...
  }
```

Comment (Zzzen) [reply packages/babel-plugin-transform-classes/src/transformClass.js:220]: We need to traverse here because `super` may appear anywhere in methods.

**Comment by nicolo-ribaudo** [comment]
I think that we need to move this logic in `ReplaceSupers`, so that it works for example with
```js
class A extends B {
  method() {
    let A;
    super.#foo();
  }
}
```

**Comment by Zzzen** [comment]
I agree with moving logic in ReplaceSupers but can't see why the example should work: derived classes should have no access to private methods of Base classes, right?  Only public and protected methods are accessible.

File: packages/babel-helper-create-class-features-plugin/test/fixtures/replace-supers/static/output.js [hunk 2]
```diff
@@ -0,0 +1,13 @@
+class B {
+  method() {}
+
+}
+
+class D extends B {
+  static method() {
+    let B;
+    let D;
+    return super.method();
```
Comment (Zzzen) [inline packages/babel-helper-create-class-features-plugin/test/fixtures/replace-supers/static/output.js:10]: ReplaceSuper doesn't seem to work. I can't figure out a better test.

**Comment by nicolo-ribaudo** [comment]
It can work in cases like
```js
class B {
  #foo = 3;

  static getA() {
    return class A extends B {
      method() {
        let A;
        super.#foo();
      }
    }
  }
}
```

**Comment by Zzzen** [comment]
Really? Tried it on chrome 87, got: `Uncaught SyntaxError: Unexpected private field`

**Comment by nicolo-ribaudo** [comment]
Sorry, I was completely wrong :upside_down_face: 

`ReplaceSupers` in the `helper-create-class-features-plugin` package is used for cases like this:
```js
class A extends B {
  #foo() {
    let A;
    super.x;
  }
}
```

Which on `main` is (wrongly) transformed to
```js
class A extends B {
  constructor(...args) {
    super(...args);

    _foo.add(this);
  }

}

var _foo2 = function _foo2() {
  let A;

  _get(_getPrototypeOf(A.prototype), "x", this);
};
```

**Comment by Zzzen** [comment]
👌👌 updated

File: packages/babel-helper-replace-supers/src/index.js [hunk 3]
```diff
@@ -26,6 +26,24 @@ function getPrototypeOfExpression(objectRef, isStatic, file, isPrivateMethod) {
...
+        path.skip();
+        return;
+      }
+
+      if (path.scope.hasOwnBinding(objectRefName)) {
+        path.scope.rename(objectRefName);
+      }
+    },
+  });
+}
```
Comment (nicolo-ribaudo) [inline packages/babel-helper-replace-supers/src/index.js:45]: We should use `environmentVisitor` here, so that it properly handles every place where `super` refers to the current super class.

We can also avoid creating a new traversal visitor every time this function is called, to slightly improve perf:
```js
const unshadowSuperBindingVisitor = traverse.visitors.merge([
  environmentVisitor,
  {
    Scopable(path, { refName }) {
      if (path.scope.hasOwnBinding(refName)) {
        path.scope.rename(refName);
      }
    },
  },
]);
```

And then use it in `replace()` as
```js
path.traverse(unshadowSuperBindingVisitor, { refName: this.opts.refToPreserve }); 
```

File: packages/babel-plugin-transform-classes/src/transformClass.js [hunk 4]
```diff
@@ -496,10 +497,16 @@ export default function transformClass(
...
+    const replaceSupers = new ReplaceSupers({
+      methodPath: path,
+      objectRef: classState.classRef,
+      superRef: classState.superName,
+      isLoose: classState.isLoose,
+      file: classState.file,
+      refToPreserve: classState.classRef,
+    });
+
+    replaceSupers.replace();
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-classes/src/transformClass.js:509]: Isn't the `ReplaceSupers` in `pushBody` enough?

Comment (Zzzen) [reply packages/babel-plugin-transform-classes/src/transformClass.js:509]: Nope. `classState.classRef` may be shadowed in child scopes of constructor.  You can view the output of `name-collisions-with-class-ref-in-constructor/input.js` applied by the latest babel.
https://babeljs.io/repl#?browsers=%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEBiD29oFMAeAXZA7AJjAQpMtAN4BQ00w8WE6ATgK7Drz0AUAlKRZdAJYAzaOwaNk3cnz4hk6OIgDcvaREYAHZPQB0AWzkALeDi7LpAX16Xz0MkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.12.12&externalPlugins=

```js
  function Foo() {
    var _thisSuper, _this;
    _classCallCheck(this, Foo);

    if (true) {
      var _Foo;
      // `_Foo.prototype` should be `Foo.prototype`
      _get((_thisSuper = _assertThisInitialized(_this), _getPrototypeOf(_Foo.prototype)), "method", _thisSuper).call(_thisSuper);
    }

    return _possibleConstructorReturn(_this);
  }
```

Comment (nicolo-ribaudo) [reply packages/babel-plugin-transform-classes/src/transformClass.js:509]: Could you add a test that fails without those lines then? I tried commenting them out but `yarn jest classes` still passes.

File: packages/babel-helper-replace-supers/src/index.js (hunk 3 above)
Comment (Zzzen) [reply packages/babel-helper-replace-supers/src/index.js:45]: It's strange that bindings are not updated correctly in `unshadowSuperBindingVisitor`.

https://github.com/Zzzen/babel/pull/1/files#r554520633

File: packages/babel-plugin-transform-classes/src/transformClass.js (hunk 4 above)
Comment (Zzzen) [reply packages/babel-plugin-transform-classes/src/transformClass.js]: 🤔 You are right, the constructor is already transformed in `pushBody`.

**Review by nicolo-ribaudo — APPROVED** [review]
Thanks!

**Review by JLHwung — APPROVED** [review]
