### PR TITLE
[systemjs] Fix nested `let`/`const` shadowing imported bindings

### LINKED ISSUE #13888: [Bug]: plugin-transform-modules-systemjs transformation is unsafe
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

[REPL](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAbzgDzgXzgMyhEcDkAdAPTKEBWAzvgNwBQdwmcAFDFAK4CmAlInQEgAxhAB2leKgC8cAIz1hYyhAA2XQiogBzFsh700DUVwDurISoCGlSnC7IYXUQBNbqBGh4t9dIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.15.8&externalPlugins=%40babel%2Fplugin-transform-modules-systemjs%407.15.4&assumptions=%7B%7D).

```js
import { x } from './x.js';

if (true) {
	const x = 1;
	console.log(x);
}

new (class extends x {})();
```

### Configuration file name

_No response_

### Configuration

Using `@babel/plugin-transform-modules-systemjs`, nothing else

### Current and expected behavior

I would expect the `x = 1` to declare a local constant, as it does in the original code. Instead, it assigns to a new module-level variable (which in this case has the same name as an import, causing an error). 

### Environment

```
  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 16.5.0 - ~/.nvm/versions/node/v16.5.0/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 7.19.1 - ~/.nvm/versions/node/v16.5.0/bin/npm
  npmPackages:
    @babel/core: ^7.15.8 => 7.15.8 
    @babel/plugin-proposal-dynamic-import: ^7.14.5 => 7.14.5 
    @babel/plugin-transform-modules-systemjs: ^7.15.4 => 7.15.4 
```

### Possible solution

_No response_

### Additional context

cc @guybedford :)

### PR DESCRIPTION
**Pull request by The-x-Theorist**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #13888  
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

Variables will be renamed in the hoisting operation, and variables declared inside blockStatment will be different, hence they won't collide with any other identifier.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14057"></a>

### CODE REVIEW

File: packages/babel-helper-hoist-variables/src/index.ts [hunk 1]
```diff
@@ -40,6 +40,12 @@ const visitor = {
 
     for (const declar of declarations) {
       firstId = declar.node.id;
+      if (
+        declar.parentPath.parentPath.isBlockStatement() &&
+        declar.parent.kind !== "var"
```
Comment (nicolo-ribaudo) [inline packages/babel-helper-hoist-variables/src/index.ts:45]: Nit: we can hoist this check outside of the `for` loop:
```js
const needsRename = path.node.kind !== "var" && path.parentPath.isBlockStatement()
```

File: packages/babel-plugin-proposal-do-expressions/test/fixtures/do-expressions/variable-declaration-start-to-iife/exec.js [hunk 2]
```diff
@@ -7,4 +7,4 @@ expect(
     bar;
   }
 ).toBe("foo");
-expect(bar).toBe("foo");
+// expect(bar).toBe("foo");
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-proposal-do-expressions/test/fixtures/do-expressions/variable-declaration-start-to-iife/exec.js:10]: This behavior should not change.

File: packages/babel-helper-hoist-variables/src/index.ts (hunk 1 above)
Comment (nicolo-ribaudo) [reply packages/babel-helper-hoist-variables/src/index.ts:45]: Actually, I think we can just edit the `Scope` visitor above to check `kind === "let" || kind === "const"`.

Comment (The-x-Theorist) [reply packages/babel-helper-hoist-variables/src/index.ts]: Okay, I will change that.

File: packages/babel-helper-hoist-variables/src/index.ts [hunk 3]
```diff
@@ -38,8 +38,14 @@ const visitor = {
     > = path.get("declarations");
     let firstId;
 
+    const needsRename =
+      path.node.kind !== "var" && path.parentPath.isBlockStatement();
+
     for (const declar of declarations) {
       firstId = declar.node.id;
+      if (needsRename) {
+        declar.scope.rename(declar.node.id.name);
```
Comment (nicolo-ribaudo) [inline packages/babel-helper-hoist-variables/src/index.ts:47]: The TS warning here is correct; I think this breaks, for example, with `const { x } = {}`. You probably need to do
```js
if (needsRename) {
  for (const name of Object.keys(declar.getBindingIdentifiers()) {
    declar.scope.rename(name);
  }
}
```

Comment (The-x-Theorist) [reply packages/babel-helper-hoist-variables/src/index.ts:47]: Okay, I will do that.

Comment (nicolo-ribaudo) [reply packages/babel-helper-hoist-variables/src/index.ts]: Also add a test for this!

Comment (The-x-Theorist) [reply packages/babel-helper-hoist-variables/src/index.ts]: Okay, I will add the test

Comment (The-x-Theorist) [reply packages/babel-helper-hoist-variables/src/index.ts]: I think that it's working now.

**Review by nicolo-ribaudo — DISMISSED** [review]
Thanks!

File: packages/babel-plugin-transform-modules-systemjs/test/fixtures/systemjs/module-level-variable-destructuring/output.mjs [hunk 4]
```diff
@@ -0,0 +1,23 @@
...
+  var x, _x;
+
+  return {
+    setters: [function (_xJs) {
+      x = _xJs.x;
+    }],
+    execute: function () {
+      if (true) {
+        ({
+          x: _x
```
Comment (JLHwung) [inline packages/babel-plugin-transform-modules-systemjs/test/fixtures/systemjs/module-level-variable-destructuring/output.mjs:13]: Why `const { x } = { x: 1 }` is also transformed? I would expect `_x` is registered in the same scope of the local `x` declaration:

```js
if (true) {
  const { x: _x } = { x: 1 };
  console.log(_x);
}
```

Comment (The-x-Theorist) [reply packages/babel-plugin-transform-modules-systemjs/test/fixtures/systemjs/module-level-variable-destructuring/output.mjs:13]: Hoisted vars are renamed, So I think that's the reason for this.

Comment (The-x-Theorist) [reply packages/babel-plugin-transform-modules-systemjs/test/fixtures/systemjs/module-level-variable-destructuring/output.mjs:13]: What should we change in this?

Comment (nicolo-ribaudo) [reply packages/babel-plugin-transform-modules-systemjs/test/fixtures/systemjs/module-level-variable-destructuring/output.mjs:13]: Oh right, the problem is that we should only hoist `var` declarations. Then we can pass `"var"` instead of `null` to `hoistVariables` in the `systemjs` plugin (or we can just delete that parameter, since `"var"` is the default value).

Comment (nicolo-ribaudo) [reply packages/babel-plugin-transform-modules-systemjs/test/fixtures/systemjs/module-level-variable-destructuring/output.mjs:13]: I have been thinking about this, and the proper fix probably is in the `systemjs` plugin itself.

We should not hoist all variables (`var` and `let`/`const`), but only `var` and top-level `let`/`const`. We can do this by:
1. In the big loop over the program body (in the `Program.exit` visitor), we convert all the exported `let`/`const` bindings to `var`. This is safe, because exported `let`/`const` bindings are necessarily defined in the top-level scope and not in nested blocks.
2. When calling `hoistVariables`, we should remove the third parameter (`null`) so that it only hoists `var` and not also `let`/`const`.

Comment (nicolo-ribaudo) [reply packages/babel-plugin-transform-modules-systemjs/test/fixtures/systemjs/module-level-variable-destructuring/output.mjs:13]: For (1), be careful because `export let x = 1;` and `export { x }; let x = 1;` are handled in two different code paths and both should still work.

Comment (nicolo-ribaudo) [reply packages/babel-plugin-transform-modules-systemjs/test/fixtures/systemjs/module-level-variable-destructuring/output.mjs:13]: Also, it looks like after this change `hositVariables` will only be used to hoist `var` declarations, so in Babel 8 we can remove `let` support :smile:

Comment (JLHwung) [reply packages/babel-plugin-transform-modules-systemjs/test/fixtures/systemjs/module-level-variable-destructuring/output.mjs:13]: I think the systemjs transform hoists more variables than it should've. Specifically, it is hoisting block scoped variable, which should never affect the exported specifiers because export statement is always on the top level. For example, the expected output of
```js
import { x } from './x.js';

if (true) {
	const { x } = { x: 1 };
	console.log(x);
}

new (class extends x {})();
```
should be
```js
System.register(["./x.js"], function (_export, _context) {
  "use strict";

  var x;
  return {
    setters: [function (_xJs) {
      x = _xJs.x;
    }],
    execute: function () {
      if (true) {
        const {
          x
        } = {
          x: 1
        };
        console.log(x);
      }

      new class extends x {}();
    }
  };
});
```

So I suggest we fix this in the systemjs transform. We can inline the `hoistVariable` visitor, but skip those variable declarations, if they are 1) of kind "let" or "const" and 2) defined in a new scope (other than the top level scope). For more context about why `let` or `const` should be hoisted, see https://github.com/babel/babel/pull/8104.

I don't think we need to rename the bindings if the path is a block-scoped declaration under block statement, because 1) at the hoist-variable-helper level, we don't know where the bindings will be hoisted to, neither do we know they will conflict with bindings in the target scope 2) even if there are conflict bindings, it should be up to the `emitFunction`'s responsibility to ensure the hoisted variables can be legally registered, either by renaming the hoisted variable, or renaming its own bindings. 3) a block-scoped variable can be defined under any BlockParent, including BlockStatement.

Comment (JLHwung) [reply packages/babel-plugin-transform-modules-systemjs/test/fixtures/systemjs/module-level-variable-destructuring/output.mjs:13]: I think the systemjs transform hoists more variables than it should've. Specifically, it is hoisting block scoped variable, which should never affect the exported specifiers because export statement is always on the top level. For example, the expected output of
```js
import { x } from './x.js';

if (true) {
	const { x } = { x: 1 };
	console.log(x);
}

new (class extends x {})();
```
should be
```js
System.register(["./x.js"], function (_export, _context) {
  "use strict";

  var x;
  return {
    setters: [function (_xJs) {
      x = _xJs.x;
    }],
    execute: function () {
      if (true) {
        const {
          x
        } = {
          x: 1
        };
        console.log(x);
      }

      new class extends x {}();
    }
  };
});
```

So I suggest we fix this in the systemjs transform. We can inline the `hoistVariable` visitor, but skip those variable declarations, if they are 1) of kind "let" or "const" and 2) defined in a new scope (other than the top level scope). For more context about why `let` or `const` should be hoisted, see https://github.com/babel/babel/pull/8104.

I don't think we need to rename the bindings if the path is a block-scoped declaration under block statement, because 1) at the hoist-variable-helper level, we don't know where the bindings will be hoisted to, neither do we know they will conflict with bindings in the target scope 2) even if there are conflict bindings, it should be up to the `emitFunction`'s responsibility to ensure the hoisted variables can be legally registered, either by renaming the hoisted variable, or renaming its own bindings. 3) a block-scoped variable can be defined under any BlockParent, including BlockStatement.

Comment (The-x-Theorist) [reply packages/babel-plugin-transform-modules-systemjs/test/fixtures/systemjs/module-level-variable-destructuring/output.mjs:13]: Okay I understand, I will wait for @nicolo-ribaudo re-review before working on.

Comment (nicolo-ribaudo) [reply packages/babel-plugin-transform-modules-systemjs/test/fixtures/systemjs/module-level-variable-destructuring/output.mjs:13]: I dropped my review to re-review _after_ the updates 😛

Comment (The-x-Theorist) [reply packages/babel-plugin-transform-modules-systemjs/test/fixtures/systemjs/module-level-variable-destructuring/output.mjs:13]: Oh sorry, I will start working on. 😂

Comment (The-x-Theorist) [reply packages/babel-plugin-transform-modules-systemjs/test/fixtures/systemjs/module-level-variable-destructuring/output.mjs:13]: If third parameter is removed from the `hoistVariable` it removes all the `_export` calls from the outputs, and doesn't transform the input?

Comment (JLHwung) [reply packages/babel-plugin-transform-modules-systemjs/test/fixtures/systemjs/module-level-variable-destructuring/output.mjs:13]: Yeah we will still need to hoist these export bindings _and_ set up the metadata from which the `_export` calls are built. I suggest we copy the code from the `hoistVariable` to the systemjs transform, and implement the custom hoisting logic mentioned in https://github.com/babel/babel/pull/14057#discussion_r821846879. Or we can add a new option in the helper, though I lean to the first option since the hoisting logic here is not reused by other plugins.

Comment (nicolo-ribaudo) [reply packages/babel-plugin-transform-modules-systemjs/test/fixtures/systemjs/module-level-variable-destructuring/output.mjs:13]: I'm surprised that the current helper doesn't work, because we only need `_export` for things that become `var` in step 1 :thinking: 
Do you mind pushing the current (non working) code you have?

Comment (JLHwung) [reply packages/babel-plugin-transform-modules-systemjs/test/fixtures/systemjs/module-level-variable-destructuring/output.mjs:13]: I don't have a working branch. We can infer the behaviour of `hoistVariable` helper from the implementation:

https://github.com/babel/babel/blob/dacaab1071a509f334c9c7355c38dd829cda9935/packages/babel-helper-hoist-variables/src/index.ts#L23-L32

The third variable `kind` controls two behaviours: 1) Whether we should check a BlockParent to see if it contains to-be-hoisted variables, and 2) whether we should hoist the `let`-kind variable declarations.

In systemjs transform, what we want to achieve is to hoist `var` variables within block parent (so `kind` has to be `"let"`), but leave `let`-kind declarations within block parent untouched.

Comment (nicolo-ribaudo) [reply packages/babel-plugin-transform-modules-systemjs/test/fixtures/systemjs/module-level-variable-destructuring/output.mjs]: @The-x-Theorist I hope you don't mind, I pushed two commits to your branch.

[`14e9cfd` (#14057)](https://github.com/babel/babel/pull/14057/commits/14e9cfd1e2183e882e266ed8206680607bf1b080) is how I was thinking to fix the problem, as described in https://github.com/babel/babel/pull/14057#discussion_r821846879:
1. It changes all the top-level `let`/`const` to `var`
2. It only hoists `var`s

The updated tests look good, but it probably needs a few new tests to make sure that both `const x = 1; export { x }` and `export const x  = 1;` work (unless we already have these tests).

File: packages/babel-plugin-transform-modules-systemjs/src/index.ts [hunk 5]
```diff
@@ -427,6 +433,11 @@ export default declare((api, options) => {
                   );
                   addExportName(name, name);
                 } else {
+                  if (declar.isVariableDeclaration()) {
+                    // Convert top-level variable declarations to "var",
+                    // because they must be hoisted
+                    declar.node.kind = "var";
+                  }
```
Comment (JLHwung) [inline packages/babel-plugin-transform-modules-systemjs/src/index.ts:440]: A top level var declaration can be nested within for statement:
```js
for (var x = 1;false;);
export { x }
```
or it could be within a do expression.

File: packages/babel-helper-hoist-variables/src/index.ts [hunk 6]
```diff
@@ -38,8 +38,16 @@ const visitor = {
     > = path.get("declarations");
```
Comment (JLHwung) [inline packages/babel-helper-hoist-variables/src/index.ts:38]: The hoistVariable visitor should be merged with `environmentVisitor`, too.

**Review by JLHwung — APPROVED** [review]

File: packages/babel-plugin-transform-modules-systemjs/src/index.ts (hunk 5 above)
Comment (nicolo-ribaudo) [reply packages/babel-plugin-transform-modules-systemjs/src/index.ts:440]: They already have `var`, there is no need to manually change them.

File: packages/babel-helper-hoist-variables/src/index.ts (hunk 6 above)
Comment (nicolo-ribaudo) [reply packages/babel-helper-hoist-variables/src/index.ts:38]: Lets do it in another PR since it's separate from this bug :+1:

**Comment by nicolo-ribaudo** [comment]
@The-x-Theorist I reverted your hoistVariable changes but I still kept your tests since they ensure that we fixed the bug. Thank you!

**Review by nicolo-ribaudo — APPROVED** [review]
