### PR TITLE
Fix bug incorrect dereferencing rest argument

### LINKED ISSUE #5787: Rest param indexing incorrectly allows accessing params before the rest param
### Input Code
```js
let f = function(a, ...rest) {
  let b = rest[rest.length - 3];
  let c = rest[rest.length - 2];
  let d = rest[rest.length - 1];
  return [a, b, c, d];
};
console.log(f(1, 2));
```

[Repl link](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&targets=&browsers=&builtIns=false&debug=false&code=let%20f%20%3D%20function(a%2C%20...rest)%20%7B%0A%20%20let%20b%20%3D%20rest%5Brest.length%20-%203%5D%3B%0A%20%20let%20c%20%3D%20rest%5Brest.length%20-%202%5D%3B%0A%20%20let%20d%20%3D%20rest%5Brest.length%20-%201%5D%3B%0A%20%20return%20%5Ba%2C%20b%2C%20c%2C%20d%5D%3B%0A%7D%3B%0Aconsole.log(f(1%2C%202))%3B)

### Babel Configuration (.babelrc, package.json, cli command)
Just the es2015 preset in the repl.

### Expected Behavior
It should print this:
```
Array [
  1,
  undefined,
  undefined,
  2
]
```

### Current Behavior
It prints this:
```
Array [
  1,
  undefined,
  1,
  2
]
```

### Possible Solution
It looks like this is an incorrect special case for when you're only accessing the rest parameter using array indexing. If I ever explicitly use the `rest` variable, then it produces different code and the function behaves correctly. So one easy solution is to get rid of that special case.

Another solution is to make the compiled output a little smarter and always evaluate to `undefined` if the argument index is before the rest index.

### Context

I'm working on [this bug](https://github.com/decaffeinate/decaffeinate/issues/1043) in the decaffeinate project, and noticed this issue when testing. That bug is from working through issues in the CoffeeScript test suite, so it doesn't necessarily correspond to real-world code. My current impression is that I'll be able to fix my bug in a way that works in both babel and V8, but it certainly would be nice if they were consistent.

### PR DESCRIPTION
**Pull request by buunguyen**
| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          | yes
| Major: Breaking Change?  | no
| Minor: New Feature?      | no
| Deprecations?            | no
| Spec Compliancy?         | yes
| Tests Added/Pass?        | yes
| Fixed Tickets            | Fixes #5787 
| License                  | MIT
| Doc PR                   | no
| Dependency Changes       | 

See bug description in #5787. The fix changes the generated expression so that it returns `undefined` if the `index` to be used to dereference `arguments` is before the rest argument `offset`.

### CODE REVIEW

File: packages/babel-plugin-transform-es2015-parameters/test/fixtures/parameters/regression-5787/expected.js [hunk 1]
```diff
@@ -0,0 +1,8 @@
+function f(a) {
+  var _ref, _ref2, _ref3;
+
+  var b = (_ref = (arguments.length <= 1 ? 0 : arguments.length - 1) - 3 + 1, arguments.length <= _ref || _ref < 1 ? undefined : arguments[_ref]);
```
Comment (jridgewell) [inline packages/babel-plugin-transform-es2015-parameters/test/fixtures/parameters/regression-5787/expected.js]: This first ternary (`ref = (arguments.length <= 1 ? 0 : argument.length - 1)`) shouldn't be necessary now.

File: packages/babel-plugin-transform-es2015-parameters/src/rest.js [hunk 2]
```diff
@@ -177,6 +177,7 @@ function optimiseIndexGetter(path, argsId, offset) {
     scope.push({ id: temp, kind: "var" });
     path.parentPath.replaceWith(restIndexImpure({
       ARGUMENTS: argsId,
+      OFFSET: t.numericLiteral(offset),
```
Comment (jridgewell) [inline packages/babel-plugin-transform-es2015-parameters/src/rest.js]: Won't we need this in the pure path, too?

```js
function test(a, ...rest) {
  return rest[-1];
}

Comment (buunguyen) [inline packages/babel-plugin-transform-es2015-parameters/src/rest.js]: Good catch, thank you. I've added a commit to address this. Also I tried to optimize the AST to avoid test like `1 < 2`... in the pure path. However, I don't know how to evaluate the node without putting it in a path first because `evaluate()` is an instance method of a path. So I had to put the node into the tree first, then evaluate the path before replacing node. A bit hacky I suppose. If you have any suggestion to improve this, please let me know.

File: packages/babel-plugin-transform-es2015-parameters/test/fixtures/parameters/regression-5787/expected.js (hunk 1 above)
Comment (buunguyen) [inline packages/babel-plugin-transform-es2015-parameters/test/fixtures/parameters/regression-5787/expected.js]: Good point. However, that check is generated by length-getter optimizer and necessary when `rest.length` is used in other places that is not as part of the index-getter optimizer. If we want to fix this, we have to keep track of whether we run the length-getter inside the context of an index-getter or not to generate the right code. I'm concerned about the added complexity to remove that test, not sure if it's worth it. But I can certainly give it a try.

Comment (buunguyen) [inline packages/babel-plugin-transform-es2015-parameters/test/fixtures/parameters/regression-5787/expected.js]: It's actually hairier than I thought. The code we see is a result of 2 generators working independently: index-getter and length-getter. The length-getter includes that check so that `someRestParam.length` always returns the correct non-negative value and it is only a coincidence that the check is irrelevant in the specific case we saw when the expressions generated by index-getter and length-getter are combined. The code will fail in cases that depending on the invariant of `arr.length` being non-negative. For example:

```js
let x
let b = rest[x = rest.length - 3];
// => x might have incorrect value because rest.length could be negative
```
I propose to keep that check there to avoid introducing complexity just to have a minor optimization to a specific code path. Please let me what you think.

Comment (jridgewell) [inline packages/babel-plugin-transform-es2015-parameters/test/fixtures/parameters/regression-5787/expected.js]: Never mind then, this works.

**Comment by buunguyen** [comment]
It would be great to know if this is good to merge or any further feedback... Thanks!

File: packages/babel-plugin-transform-es2015-parameters/src/rest.js [hunk 3]
```diff
@@ -177,14 +178,30 @@ function optimiseIndexGetter(path, argsId, offset) {
...
+
+    // See if we can statically evaluate the first test (i.e. index < offset)
+    // and optimize the AST accordingly.
+    const offsetTestPath = parentPath.get("test").get("left");
+    const valRes = offsetTestPath.evaluate();
+    if (valRes.confident) {
+      if (valRes.value === true) {
+        parentPath.replaceWith(parentPath.scope.buildUndefinedNode());
+      }
+      else {
```
Comment (jridgewell) [inline packages/babel-plugin-transform-es2015-parameters/src/rest.js]: Nit: Join with the `}`

File: packages/babel-plugin-transform-es2015-parameters/src/rest.js [hunk 4]
```diff
@@ -177,14 +178,30 @@ function optimiseIndexGetter(path, argsId, offset) {
...
+        parentPath.get("test").replaceWith(parentPath.get("test").get("right"));
```
Comment (jridgewell) [inline packages/babel-plugin-transform-es2015-parameters/src/rest.js]: Do we have a test case for this one? I don't think you can `#replaceWith` another path.

File: packages/babel-plugin-transform-es2015-parameters/src/rest.js (hunk 3 above)
Comment (buunguyen) [inline packages/babel-plugin-transform-es2015-parameters/src/rest.js]: Done

File: packages/babel-plugin-transform-es2015-parameters/src/rest.js (hunk 4 above)
Comment (buunguyen) [inline packages/babel-plugin-transform-es2015-parameters/src/rest.js]: See this https://github.com/babel/babel/pull/5810/files#diff-171b2ff6e4556995af8a3b21cf2209dcR5.

If you comment out `parentPath.get("test").replaceWith(parentPath.get("test").get("right"));`, the generated code would be: `1 < 1 || arguments.length <= 1 ? undefined : arguments[1];`.

Comment (buunguyen) [inline packages/babel-plugin-transform-es2015-parameters/src/rest.js]: Also, replaceWith accepts path: https://github.com/babel/babel/blob/1e55653ac173c3a59f403a7b5269cf6d143d32d9/packages/babel-traverse/src/path/replacement.js#L106.

But I can change the line to `parentPath.get("test").replaceWith(parentPath.get("test").get("right").node)` if you think it's better.

**Comment by jridgewell** [comment]
LGTM.
