### PR TITLE
fix @babel/traverse can't use path.remove() with noScope

### LINKED ISSUE #11128: @babel/traverse noScope can't path.remove()
When I upgraded from v7.7.7 to v7.8.4, I found that there was a problem with the noScope option of @babel/traverse.

Error message:
```
e:\mypath\babel\node_modules\@babel\traverse\lib\path\removal.js:39
  Object.keys(bindings).forEach(name => this.scope.removeBinding(name));
                                                   ^

TypeError: Cannot read property 'removeBinding' of null
    at e:\mypath\babel\node_modules\@babel\traverse\lib\path\removal.js:39:52
    at Array.forEach (<anonymous>)
    at NodePath._removeFromScope (e:\mypath\babel\node_modules\@babel\traverse\lib\path\removal.js:39:25)
    at NodePath.remove (e:\mypath\babel\node_modules\@babel\traverse\lib\path\removal.js:22:8)
    at AssignmentExpression (e:\mypath\babel\test.js:6:14)
    at NodePath._call (e:\mypath\babel\node_modules\@babel\traverse\lib\path\context.js:55:20)
    at NodePath.call (e:\mypath\babel\node_modules\@babel\traverse\lib\path\context.js:42:17)
    at NodePath.visit (e:\mypath\babel\node_modules\@babel\traverse\lib\path\context.js:90:31)
    at TraversalContext.visitQueue (e:\mypath\babel\node_modules\@babel\traverse\lib\context.js:112:16)
    at TraversalContext.visitSingle (e:\mypath\babel\node_modules\@babel\traverse\lib\context.js:84:19)
```

Code to reproduce the problem:
```js
var traverse = require("@babel/traverse").default;
var parser = require("@babel/parser");

traverse(parser.parse("a=1"), {
    AssignmentExpression(path) {
        path.remove();
    },
    noScope: true,
});
```

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #11128  
| Patch: Bug Fix?          |Yes
| Major: Breaking Change?  |No
| Minor: New Feature?      |No
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |No
| License                  | MIT

### CODE REVIEW

File: packages/babel-traverse/src/path/removal.js [hunk 1]
```diff
@@ -7,7 +7,9 @@ export function remove() {
   this._assertUnremoved();
 
   this.resync();
-  this._removeFromScope();
+  if (this.opts && !this.opts.noScope) {
```
Comment (nicolo-ribaudo) [inline packages/babel-traverse/src/path/removal.js]: When is `this.opts` undefined?

Comment (liuxingbaoyu) [reply packages/babel-traverse/src/path/removal.js]: I don't know ... CI reports an error. I didn't find out exactly what caused it. I also feel very confused, but in order not to affect compatibility, I added this judgment.
[CI Link](https://travis-ci.com/babel/babel/jobs/286667571)

File: packages/babel-traverse/test/removal.js [hunk 2]
```diff
@@ -33,4 +33,15 @@ describe("removal", function() {
       expect(generateCode(rootPath)).toBe("x = () => {};");
     });
   });
+
+  it("remove with noScope", function() {
+    const ast = parse("a=1");
+    traverse(ast, {
+      AssignmentExpression: function(path) {
+        path.remove();
+      },
```
Comment (JLHwung) [inline packages/babel-traverse/test/removal.js]: I guess we should add `noScope: true` here?

File: packages/babel-traverse/src/path/removal.js (hunk 1 above)
Comment (nicolo-ribaudo) [reply packages/babel-traverse/src/path/removal.js]: The check should be `!this.opts || !this.opts.noScope`. If `opts` is not defined, `noScope` is not true so the scope is created.

Comment (liuxingbaoyu) [reply packages/babel-traverse/src/path/removal.js]: oh no! You're right.

File: packages/babel-traverse/test/removal.js (hunk 2 above)
Comment (liuxingbaoyu) [reply packages/babel-traverse/test/removal.js]: Yes, I'm a fool...

File: packages/babel-traverse/src/path/removal.js (hunk 1 above)
Comment (liuxingbaoyu) [reply packages/babel-traverse/src/path/removal.js]: I stumbled upon [this](https://github.com/babel/babel/blob/f544753bb8c9c7a470d98e897b089fd31b83d1f6/packages/babel-traverse/src/path/context.js#L114-L119) just now...
