### PR TITLE
jsx: fix sequence expression at JSXAttributeValue

### LINKED ISSUE #8604: Comma expression (Sequence expression) incorrectly allowed as JSXAttributeValue
## Bug Report

**Current Behavior**

Code like `<div>{3, 1}</div>` is not treated as a parse error, but it should be.

[REPL link](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=DwEwlgbgfA3gzAGgAQEYC-wD05oG4BQokSAZgPZkC8MKyATGkplAUA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=es2015%2Ces2016%2Ces2017%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3%2Ces2015-loose&prettier=false&targets=&version=6.26.0&envVersion=1.6.2)

**Input Code**
```js
// No error
<div>{3, 1}</div>;
// No error
<div foo={1, 2} />;
```

**Expected behavior/code**

Expected a parse error.

The [JSX Spec](https://facebook.github.io/jsx/) specifies `JSXChildExpression` and `JSXAttributeValue` as being `{` *AssignmentExpression* `}`, but the comma expression is [above `AssignmentExpression` in the grammar](https://www.ecma-international.org/ecma-262/5.1/#sec-11.14)

**Environment**
- Babel version(s): 6.26.0
- Node/npm version: N/A (repl)
- OS: N/A (repl)
- Monorepo N/A (repl)
- How you are using Babel: N/A (repl)

**Possible Solution**

**Additional context/Screenshots**

https://stackoverflow.com/questions/52139174/comma-operator-in-typescript-jsx-expressions

### PR DESCRIPTION
**Pull request by macabeus**
Following https://github.com/babel/babel/issues/8604, we should not allow codes like these
```js
<div key={console.log('foo'), JSON.stringify(props)} />
<div>{console.log('foo'), JSON.stringify(props)}</div>
```

But we should allow codes like
```js
<div key={(console.log('foo'), JSON.stringify(props))} />
<div>{(console.log('foo'), JSON.stringify(props))}</div>
```

This PR fixes it, raising an exception with this message: `Sequence of values at JSX must be parenthesized.`
But, since we currently allow the wrong code, this fix is a breaking change.

| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #8604
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | Yes
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
Instead of parsing an Expression and then throw if it is a SequenceExpression, we can parse an AssignmentExpression since the beginning.

**Comment by macabeus** [comment]
@nicolo-ribaudo Where is the `AssignmentExpression` at JSX plugin? I tried to find it, but I can't.

**Comment by nicolo-ribaudo** [comment]
You can use `this.parseMaybeAssign` (defined it `src/parser/expression.js`) instead of `this.parseExpression` at line 329.

**Comment by macabeus** [comment]
@nicolo-ribaudo I updated the code 😄

File: packages/babel-parser/src/plugins/jsx/index.js [hunk 1]
```diff
@@ -327,8 +327,22 @@ export default (superClass: Class<Parser>): Class<Parser> =>
         node.expression = this.jsxParseEmptyExpression();
       } else {
         node.expression = this.parseExpression();
+
+        if (
+          node.expression.type === "SequenceExpression" &&
+          ((node.expression.extra &&
+            node.expression.extra.parenthesized === false) ||
+            node.expression.extra === undefined)
```
Comment (danez) [inline packages/babel-parser/src/plugins/jsx/index.js]: You could do this here, which is a little bit simpler:

```
node.expression.type === "SequenceExpression" &&
          (!node.expression.extra ||
            node.expression.extra.parenthesized !== true)
```
I also used `!== true`, as extra might be an object but parenthesized could be undefined.

File: packages/babel-parser/src/plugins/jsx/index.js [hunk 2]
```diff
@@ -327,8 +327,21 @@ export default (superClass: Class<Parser>): Class<Parser> =>
         node.expression = this.jsxParseEmptyExpression();
       } else {
         node.expression = this.parseExpression();
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/src/plugins/jsx/index.js]: Is there a reason to check if the expression is parenthesized instead of using `parseMaybeAssign` (which already disallow comma expressions) here?

Comment (danez) [reply packages/babel-parser/src/plugins/jsx/index.js]: 👍

**Comment by nicolo-ribaudo** [comment]
Since in a past meating we had concerns that this PR could break someone's code, here is a summary of what other parsers do when parsing `<div>{console.log('foo'), JSON.stringify(props)}</div>`:

  | Parser | Parsed? | Error
  |--------|---------|-------
  | Acorn | :heavy_check_mark: 
  | TypeScript | :x: | `'}' expected.`
  | Flow | :heavy_check_mark: |
  | Espree (Uses acorn) | :heavy_check_mark: |
  | Esprima | :x: | `Unexpected token ,`

Bonus: Pretter prints it as `<div>{(console.log('foo'), JSON.stringify(props))}</div>`

**Comment by macabeus** [comment]
Sorry for not being at the meeting. I'm very busy at last days 😞

@xtuc What were the outputs of the meeting?

**Comment by nicolo-ribaudo** [comment]
For now we are not merging this PR since, as shown in https://github.com/babel/babel/pull/8787#issuecomment-439726230, many tools allow sequence expression and thus some people may rely on it.
We will merge this in Babel 8, and in the meantime we will investigate about an opt-in flag to enable warnings about "things that will break in the next major release".

**Comment by nicolo-ribaudo** [comment]
I'm merging this to the `next-8-dev` branch. It will take some time before it's released!
