### PR TITLE
fix: non breaking align options naming

### LINKED ISSUE #13170: [Bug]: `sourceFileName` vs. `sourceFilename` scattered differently over project, sometimes typed wrong
### 

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

n/a

### Configuration file name

_No response_

### Configuration

n/a

### Current and expected behavior

```js
  function myFancyBabelPlugin() {
    return {
      parserOverride(contents, options) {
        if (
          options.sourceFileName &&
```

^-- type error “Did you mean 'sourceFilename'”, but `sourceFilename` is undefined and `sourceFileName` is set.
A bit of searching shows differently cased values: https://github.com/babel/babel/search?q=sourceFilename+path%3Apackages.

### Environment

```sh
$ npx envinfo --preset
Need to install the following packages:
  envinfo
Ok to proceed? (y) y

No "true" preset found.
```

### Possible solution

picking either

### Additional context

Actual code is here: https://github.com/wooorm/xdm/blob/main/test/babel.js#L37-L41.

### PR DESCRIPTION
**Pull request by fedeci**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #13170  
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/13532"></a>

### CODE REVIEW

**Comment by fedeci** [comment]
Let's see if it breaks e2e🤞

**Comment by fedeci** [comment]
May we consider it a new feature because previously this was "shadowed" and not accessible?

**Comment by nicolo-ribaudo** [comment]
Yeah I'd consider this a new feature.

**Review by nicolo-ribaudo — COMMENTED** [review]
Can you also add a test that directly passes the `sourceFileName` option?
And also a test for the `unknown` special case (why do we need that special case?)

File: packages/babel-core/test/parse.js [hunk 1]
```diff
@@ -17,19 +17,40 @@ function fixture(...args) {
...
+      sourceFileName: "input.js",
       cwd: fixture(),
     });
     expect(JSON.parse(JSON.stringify(result))).toEqual(output);
   });
 
   it("should parse using passed in configuration", function () {
-    const input = fs.readFileSync(fixture("input.js"), "utf8");
-    const output = require(fixture("output.json"));
+    const input = fs.readFileSync(
```
Comment (fedeci) [inline packages/babel-core/test/parse.js:49]: @nicolo-ribaudo this tests the no-"unknown" handling because no `filename`, `filenameRelative` or `sourceFileName` is passed.

**Review by nicolo-ribaudo — APPROVED** [review]

**Review by hzoo — APPROVED** [review]

**Comment by LarsDenBakker** [comment]
This change breaks one of my babel plugins that relies on the `parserOverride` hook. The value of `sourceFileName` has now changed to be the file basename instead of the relative path to the file.

**Comment by fedeci** [comment]
That should be the right behaviour but yeah, since it breaks let's leave it entirely for babel-8.

**Comment by LarsDenBakker** [comment]
@fedeci thanks! Shouldn't we add filename as well to parserOpts then? Otherwise in the `parserOverride` hook there is no way to know where the actual file is located.

I have a babel plugin that transforms HTML Imports to es modules, and it transforms the HTML to valid JS in this hook. I need to know the folder of the location for resolving some references inside the HTML.

**Comment by fedeci** [comment]
Probably yes, I'll update the other PR in these days!

**Comment by dlockhart** [comment]
Noticed this change is breaking [this plugin here](https://github.com/cfware/babel-plugin-bundled-import-meta/blob/master/index.js#L67), which is probably the same/similar thing @LarsDenBakker is referring to.

**Comment by DylanPiercey** [comment]
If we're already considering this a breaking change, would it not make more sense to standardize all uses of `sourcefilename` to be the same casing? Currently the parserOpts is the only one that expects the lowercase `n`.

**Comment by fedeci** [comment]
@DylanPiercey this was not to be considered as a breaking change initially because of my fault. It will be reverted in the next patch version. The "big breaking change" is already scheduled for babel 8.

**Comment by nicolo-ribaudo** [comment]
I'm releasing v7.15.5 to revert this.
