### PR TITLE
Fix issue semi-colon gets inserted unnecessarily

### LINKED ISSUE #5744: Destructuring is not working
Hello! When I type `if(true) [a, b] = [b, a];` babel insert ; into body.
Just see this: https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&targets=&browsers=&builtIns=false&debug=false&code=function%20x()%20%7B%0A%20%20let%20a%20%3D%201%3B%0A%20%20let%20b%20%3D%202%3B%0A%20%20%0A%20%20%2F%2F%20broken%0A%20%20if(true)%20%5Ba%2C%20b%5D%20%3D%20%5Bb%2C%20a%5D%3B%0A%20%20%0A%20%20%2F%2F%20ok%0A%20%20if(true)%20%7B%0A%20%20%20%20%5Ba%2C%20b%5D%20%3D%20%5Bb%2C%20a%5D%3B%0A%20%20%7D%0A%7D

This breaks my code

### PR DESCRIPTION
**Pull request by buunguyen**
| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          | yes
| Major: Breaking Change?  | no
| Minor: New Feature?      | no 
| Deprecations?            | no 
| Spec Compliancy?         | yes 
| Tests Added/Pass?        | yes 
| Fixed Tickets            | Fixes #5744
| License                  | MIT
| Doc PR                   | no
| Dependency Changes       | no 

Original:
```js
if (true) [a, b] = [b, a];
```

Transpiled version:
```js
if (true) {
  ;
  var _ref = [b, a];
  a = _ref[0];
  b = _ref[1];
  _ref;
}
```

The problem is `insertAfter` could push an empty expression statement, resulting in the semi-colon. This change checks to make sure the expression statement is not empty before pushing.

### CODE REVIEW

File: packages/babel-traverse/src/path/modification.js [hunk 1]
```diff
@@ -126,7 +126,10 @@ export function insertAfter(nodes) {
     if (Array.isArray(this.container)) {
       return this._containerInsertAfter(nodes);
     } else if (this.isStatementOrBlock()) {
-      if (this.node) nodes.unshift(this.node);
+      // Unshift current node if it's not an empty expression
+      if (this.node && (!this.isExpressionStatement() || this.node.expression != null)) {
```
Comment (hzoo) [inline packages/babel-traverse/src/path/modification.js]: Is it better to do ^ or just check if it's an not an `EmptyExpression`?

Comment (buunguyen) [inline packages/babel-traverse/src/path/modification.js]: I can't find `EmptyExpression` or `isEmptyExpression` in the codebase. Or did you mean we should create a new method `isEmptyExpression` to wrap the above? Like:

```js
if (this.node && !this.isEmptyExpression()) {...}
...
isEmptyExpression() => this.isExpressionStatement() && this.node.expression == null
```

Comment (buunguyen) [inline packages/babel-traverse/src/path/modification.js]: Or you probably meant `EmptyStatement` :). Let me try that.

Comment (hzoo) [inline packages/babel-traverse/src/path/modification.js]: oh sorry I thought it was "EmptyStatement"

Comment (buunguyen) [inline packages/babel-traverse/src/path/modification.js]: I just tried, it doesn't work. 

In this particular case, `this.node` is of type `ExpressionStatement`. `this.isEmptyStatement()` returns `false` because `ExpressionStatement` isn't `EmptyStatement` and they aren't aliases of one another.

I wondered why `this.node` wasn't `EmptyStatement` in the first place and dug in a bit more. Turns out this line https://github.com/babel/babel/blob/7.0/packages/babel-traverse/src/path/replacement.js#L50 sets `this.container['expression'] = null` and `this.container` is `this.node` in the piece of code in question.

Comment (hzoo) [inline packages/babel-traverse/src/path/modification.js]: And do we want to make the same change in insertBefore?

Comment (buunguyen) [inline packages/babel-traverse/src/path/modification.js]: I thought so too, but couldn't come up with a test for that case. Basically we need something that results in:

```js
{
  code 
  code 
  ;  <--  empty statement here
}
```
Without a test/bug that exposes the above behavior, there's no guarantee such situation is possible. Currently, the behavior is caused by that line to `this.container['expression'] = null`, which is only invoked before `insertAfter`. I haven't seen anything line that before `insertBefore`. That said, I could definitely make that change to `insertBefore` for the extra caution. Let me know.

Comment (hzoo) [inline packages/babel-traverse/src/path/modification.js]: Ah ok I see. I guess `this.container['expression'] = null` is rather a weird way to do things but we can do this

**Comment by hzoo** [comment]
Thanks for looking into this and doing a through investigation!
