### PR TITLE
Fix optional chain optimization in sequence expression

### LINKED ISSUE #15887: [Bug]: Optional chaining expressions resolving as `true` instead of undefined
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code
https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=PTAEDMEsCcGcBdQBtIDsCmoAWBDWoADACgH1p1xQBeUVAVySQEpqqb7GDQ9QAHHaIgD2leFkzoAHr3KxYkIalAB3LJADGWUOgBuOJHXjp88IYXjQ66LumjRF6IXVhIAnt1QATULIbx8aKBimKpCSBLSsvKKoABG6GgA5uaW1gBQHEgA_AB0RghpaSBBavgoGKCw6OgAtiZmsmE6mOpCdujq8G5pdF4UaOieufnwQA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.22.11&externalPlugins=&assumptions=%7B%7D

### Configuration file name

reproduced in babel try it out - see for configuration

### Configuration

reproduced in babel try it out - see for configuration

### Current and expected behavior

In my application expressions like `null?.a` are evaluating as true. This behavior started today with version 7.22.11

### Environment

Babel version 7.22.11

### Possible solution

Changes like these in a recent change might be the issue? It looks like if a value is undefined, babel gives an expression that evalutes to true.

image

https://github.com/babel/babel/pull/15871/commits/170c83478fbb3115aca98bef532bd8e8cc3bf7ae

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #15887
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

The problem is that `isCompletionRecord` in the test code is returning false, because the sequence expression was not in a completion record position.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15888"></a>

### CODE REVIEW

File: packages/babel-plugin-transform-optional-chaining/src/transform.ts [hunk 1]
```diff
@@ -209,9 +212,10 @@ export function transformOptionalChain(
     !ifNullishBoolean && t.isUnaryExpression(ifNullish, { operator: "void" });
 
   const isEvaluationValueIgnored =
-    (t.isExpressionStatement(replacementPath.parent) ||
-      t.isSequenceExpression(replacementPath.parent)) &&
-    !replacementPath.isCompletionRecord();
+    (t.isExpressionStatement(replacementPath.parent) &&
+      !replacementPath.isCompletionRecord()) ||
+    (t.isSequenceExpression(replacementPath.parent) &&
+      last(replacementPath.parent.expressions) !== replacementPath.node);
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-optional-chaining/src/transform.ts:218]: It might make sense to have a `path.isValueObservable()` helper.

Comment (JLHwung) [reply packages/babel-plugin-transform-optional-chaining/src/transform.ts:218]: It certainly reminds me of the messy [`path._getCompletionRecords`](https://github.com/babel/babel/blob/c71a2177639b0782b594a44afd685d4631884e6d/packages/babel-traverse/src/path/family.ts#L226). Thankfully the switch statement is not an expression.

Comment (JLHwung) [reply packages/babel-plugin-transform-optional-chaining/src/transform.ts:218]: Similar usage:
https://github.com/babel/babel/blob/c71a2177639b0782b594a44afd685d4631884e6d/packages/babel-plugin-proposal-destructuring-private/src/index.ts#L162-L164

**Review by liuxingbaoyu — APPROVED** [review]

**Comment by nicolo-ribaudo** [comment]
Releasing a patch to fix the regression.
