### PR TITLE
Fix: propagate argument evaluation errors through async promise chain

### LINKED ISSUE #17250: Async method destructuring error not caught by Promise.catch after Babel transform
### 💻

- [x] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```JavaScript
(new class {
  async foo(a, { b }) { }
})
  .foo()
  .catch(e => {
    console.log("caught");
  });
```

### Configuration file name

_No response_

### Configuration

```json
{
  "plugins": ["transform-async-to-generator"]
}
```

### Current and expected behavior

Expected behavior:

`caught` should be printed.

Current behavior:

throw error:
```
Uncaught TypeError: Cannot destructure property 'b' of 'undefined' as it is undefined.
```

### Environment

N/A

### Possible solution

_No response_

### Additional context

[Babel Playground](https://babeljs.io/repl#?browsers=chrome%2050&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=BQOwpg7gBAxgNgQwM5KgbwFBSsgniGKAMwHsTgEAadKAIygF8BKGhjZrKAOlPKc64wEAFxgALYGCgBeAHzpO2GCRBIScMFzgkA5sABEQgK46xw_UwDcnZtaA&forceAllTransforms=false&modules=false&shippedProposals=false&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=true&targets=&version=7.27.0&externalPlugins=&assumptions=%7B%7D)

### PR DESCRIPTION
**Pull request by magic-akari**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #17250
| Patch: Bug Fix?          | 👍
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

File: packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/async-complex-params/output.js [hunk 1]
```diff
@@ -0,0 +1,9 @@
+new class {
+  foo(_x, _x2) {
+    return babelHelpers.asyncToGenerator(function* (a, {
+      b
+    }) {})();
```
Comment (liuxingbaoyu) [inline packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/async-complex-params/output.js:5]: It looks like the parameters are not being passed?

Comment (magic-akari) [reply packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/async-complex-params/output.js]: Thank you, it has been fixed.

File: packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/async-complex-params/output.js [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+  foo(_x5, _x6) {
+    var _arguments = arguments,
+      _this = this;
+    return babelHelpers.asyncToGenerator(function* (a, {
+      b
+    }) {
+      console.log(_this, _arguments);
+    }).apply(this, arguments);
+  }
+}().foo(1, {
```
Comment (liuxingbaoyu) [inline packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/async-complex-params/output.js:31]: Will this work?
```
  foo(_x5, _x6) {
    var _arguments = arguments,
      _this = this;
    return babelHelpers.asyncToGenerator(function* (a, {
      b
    }) {
      console.log(_this, _arguments);
    })(_x5, _x6);
  }
```

Comment (magic-akari) [reply packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/async-complex-params/output.js:31]: This approach seems feasible, but I encountered this scenario during testing:

```JavaScript
"use strict";
class Foo {
    async foo(a, b = 2, c) {
        return a + b + c;
    }
}
```

Our parameter copying logic stops at `b = 2` because the `length` property of the `foo` method in Foo instances reports 1. This causes parameters to be lost during the passing process.

Comment (magic-akari) [reply packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/async-complex-params/output.js:31]: Alternatively, here's a more straightforward example:

```JavaScript
class Foo {
    async foo(a, b = 2) {
        return a + b;
    }
}
```

Comment (magic-akari) [reply packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/async-complex-params/output.js:31]: @liuxingbaoyu It might be worth considering avoiding the hoisting of this and arguments in this scenario, as they have already been properly passed. 
That said, this adjustment could likely be deferred to a follow-up PR to keep the current changeset focused. What do you think?

Comment (liuxingbaoyu) [reply packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/async-complex-params/output.js:31]: Yes, I have a PR planned to remove the hoisting in functions, we can also consider whether to do the same for methods.
https://github.com/babel/babel/pull/15992

**Review by liuxingbaoyu — APPROVED** [review]
Thanks!

File: packages/babel-helper-wrap-function/src/index.ts [hunk 3]
```diff
@@ -63,29 +66,69 @@ const buildDeclarationWrapper = template.statements(`
...
   callId: t.Expression,
+  ignoreFunctionLength: boolean,
 ) {
   const node = path.node;
   const body = node.body;
 
+  let params: Array<t.Identifier | t.Pattern | t.RestElement> = [];
+
+  // Errors thrown during argument evaluation must reject the resulting promise
+  const shoudlForwardParams = node.params.some(p => p.type.includes("Pattern"));
```
Comment (JLHwung) [inline packages/babel-helper-wrap-function/src/index.ts:77]:
```suggestion
  const shoudlForwardParams = node.params.some(p => isPattern(p));
```
where `isPattern` can be imported from `@babel/types`.

File: packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/async-complex-params/input.js [hunk 4]
```diff
@@ -0,0 +1,29 @@
...
+})
+  .foo(1, { b: 2 });
+
+
+(new class extends class { get c() { return "c"; } } {
+  async foo(a, { b }) {
+    console.log(super.c);
+  }
+})
+  .foo(1, { b: 2 });
```
Comment (JLHwung) [inline packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/async-complex-params/input.js:29]: Could you add an `exec.js` test for this case?

File: packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/async-complex-params/options.json [hunk 5]
```diff
@@ -0,0 +1,3 @@
+{
+  "plugins": ["transform-async-to-generator"]
+}
```
Comment (JLHwung) [inline packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/async-complex-params/options.json:3]: Could you add a new test with different scenario? For example, is the transpiled behaviour correct when we enable both the `async-to-generator` transform and the `destructuring` transform? Or with the `object-rest-spread-transform`.

**Review by JLHwung — COMMENTED** [review]
Thank you! Let some comments on more integration tests.

File: packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/async-complex-params/options.json (hunk 5 above)
Comment (magic-akari) [reply packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/async-complex-params/options.json:6]: Done. I suppose you mean `transform-parameters`.

**Review by JLHwung — APPROVED** [review]

File: packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/async-complex-params/options.json (hunk 5 above)
Comment (JLHwung) [reply packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/async-complex-params/options.json:6]: Thanks. Could you add the test for the `ignoreFunctionLength` assumption if we don't have one?

Comment (magic-akari) [reply packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/async-complex-params/options.json:6]: Done. But an e2e test failed—it looks like a flaky test.

Comment (JLHwung) [reply packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/async-complex-params/options.json:6]: Thanks. It is, I have restarted the test.
