### PR TITLE
Disallow reinitializing private elements

### LINKED ISSUE #13299: [Bug]: Class Private Fields/Accessors/Methods must not be re-initialized on instance
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

(See "Prevent private class members from being added more than once" section in https://github.com/evanw/esbuild/releases/tag/v0.11.20#:~:text=Prevent%20private%20class%20members%20from%20being%20added%20more%20than%20once)

```js
class Base {
  constructor(obj) {
    return obj;
  }
}

let counter = 0;
class Derived extends Base {
  #foo = ++counter;
  static get(obj) {
    return obj.#foo;
  }
}

const foo = {};
new Derived(foo);
assert.equals(Derived.get(foo), 1);

// This should throw an error, private fields must not be re-initialized
// on an object that already contains the field.
assert.throws(() => {
  new Derived(foo);
});
// ^ That should have thrown, but it doesn't.

// Must not re-initialize the field
assert.equals(Derived.get(foo), 1);
// But the counter is incremented (the initializer runs, but the field
// should not re-add)
assert.equals(counter, 2);
```

[REPL](https://babeljs.io/repl/#?browsers=Chrome%2075&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=MYGwhgzhAEBCkFNoG8BQ1rAPYDsIBcAnAV2Hy0IAosAjAKwEoV0NpCF9jCdpa6BuFgF9UI1CA6YsxHPgSFoAXmgAGQaEgwAIvICWANwQATaAgAecnEZjwISNBgDEAMyxYl0ANSfsMuYUEMAjB8XWBoAHMOanomB1Z2Tm5eegA6FzdA6BExbDx8aFd3ZWQhQRwEAHdoHUIDY0oihkFNeXxUhABHYjAQCEpa-qNUqPxGtwYAGmgARmbUVAB6RegAFQALXRgIdekQE3x1wixqsB55Y8JpgAc6_RCkZ10EfZgAW2ICaBwsApokdgAWl0OF0oV6ugAXsYlitcNAzik6AgyNBDiEESB2GAjABPKSyMAgmCHR7PfapVCtQjtQ7HSr9ShMRQAPmYGAq1UGhiM4yw8yE82W0AAemt1hidnsTBLDGijiccNMaMQCmDoEYsAgIDgAOTtBbCgCynwKPwKQJBYN0EOh8rJLyMVKgbQ63V6_W5xhG0Sa0zmgmFsFV9qkfnk0C2kZwwHYbwQsmM0EopOj1ttEZIeGVIdTT0dsOgUuI-2-vzYCEBOKMDGddhpbp6fUovkTV2gACZmkA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=true&targets=&version=7.14.1&externalPlugins=)

### Configuration file name

babel.config.json

### Configuration

```json
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "shippedProposals": true,
        "targets": {
          "chrome": "75"
        }
      }
    ]
  ]
}
```

### Current and expected behavior

Currently, this will re-initialize the field `#foo`, but this is incorrect. It should throw an error when trying to initialize the field a second time.

### Environment

- Babel version: v7.14.1

### Possible solution

We should create new `initializePrivateFieldSpec`, `initializePrivateAccessorSpec`, and `initializePrivateMethodSpec` ~~(and `static` versions)~~ [helpers](https://github.com/babel/babel/blob/main/packages/babel-helpers/src/helpers.js) to initialize the field to a descriptor. Inside the helpers, we should check if the `WeakMap`/`WeakSet` that represents the transformed field already contains the `instance` key. If so, throw. Else, initialize.

Or, we could just have a simple `checkPrivateFieldInitSpec` which does the check, but doesn't initialize. We'd then call the `check` before initializing a field.

After creating the helpers, we should call them in the appropriate place in https://github.com/babel/babel/blob/main/packages/babel-helper-create-class-features-plugin/src/fields.js (look for any function that ends in "InitSpec").

### Additional context

This is a medium difficulty issue, so could be tackled by someone with a little experience making changes to Babel.

### PR DESCRIPTION
**Pull request by komyg**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            |  Fixes #13299
| Patch: Bug Fix          |
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | No
| Documentation PR Link    | 
| Any Dependency Changes?  | No
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/13601"></a>

### CODE REVIEW

File: packages/babel-helper-create-class-features-plugin/src/fields.ts [hunk 1]
```diff
@@ -449,16 +449,31 @@ function buildPrivateFieldInitLoose(ref, prop, privateNamesMap) {
...
-  })`;
+  const helper = state.addHelper("classPrivateFieldInitSpec");
+  const expr = t.callExpression(helper, [
+    t.thisExpression(),
+    t.cloneNode(id),
+    template.expression.ast`{
+        writable: true,
+        value: ${value}
+      }`,
+  ]);
```
Comment (nicolo-ribaudo) [inline packages/babel-helper-create-class-features-plugin/src/fields.ts:464]: This plugin could be used with older `@babel/core` versions, that don't support the new `classPrivateFieldInitSpec` helper. We should do something like this:
```js
if (state.availableHelper("classPrivateFieldInitSpec")) {
  // use the helper
} else {
  // return the old output, even if partially incorrect
}
```

Comment (komyg) [reply packages/babel-helper-create-class-features-plugin/src/fields.ts:473]: Done!

File: packages/babel-helper-create-class-features-plugin/src/fields.ts [hunk 2]
```diff
@@ -449,16 +449,30 @@ function buildPrivateFieldInitLoose(ref, prop, privateNamesMap) {
...
-    value: ${value},
-  })`;
+  if (!state.availableHelper("classPrivateFieldInitSpec")) {
+    return template.statement.ast`${t.cloneNode(id)}.set(${ref}, {
+      // configurable is always false for private elements
+      // enumerable is always false for private elements
+      writable: true,
+      value: ${value},
+    })`;
+  }
```
Comment (nicolo-ribaudo) [inline packages/babel-helper-create-class-features-plugin/src/fields.ts:463]: Since this is self-contained and it won't be needed in Babel 8, we could wrap it with a `process.env.BABEL_8_BREAKING` guard so that we can automatically remove it when bumping our major version:

```suggestion
  if (!process.env.BABEL_8_BREAKING) {
    if (!state.availableHelper("classPrivateFieldInitSpec")) {
      return template.statement.ast`${t.cloneNode(id)}.set(${ref}, {
        // configurable is always false for private elements
        // enumerable is always false for private elements
        writable: true,
        value: ${value},
      })`;
    }
  }
```

File: packages/babel-helpers/src/helpers.js [hunk 3]
```diff
@@ -2015,6 +2015,24 @@ helpers.classPrivateMethodGet = helper("7.1.6")`
   }
 `;
 
+helpers.classPrivateFieldInitSpec = helper("7.14.1")`
+  export default function _classPrivateFieldInitSpec(obj, privateMap, value) {
+    if (privateMap.has(obj)) {
+      throw new TypeError("redeclared private field identifier");
```
Comment (nicolo-ribaudo) [inline packages/babel-helpers/src/helpers.js:2021]: We could copy the Firefox error message:
```suggestion
      throw new TypeError("Initializing an object twice is an error with private fields");
```

The problem here is technically not that the field is _declared_ twice (that would be a parsing error), but that it runs through the class initialization process twice.

File: packages/babel-helpers/src/helpers.js [hunk 4]
```diff
@@ -2015,6 +2015,24 @@ helpers.classPrivateMethodGet = helper("7.1.6")`
...
+    }
+    privateMap.set(obj, value);
+  }
+`;
+
+helpers.classPrivateMethodInitSpec = helper("7.14.1")`
+  export default function _classPrivateMethodInitSpec(obj, privateSet) {
+    if (privateSet.has(obj)) {
+      throw new TypeError("redeclared private method identifier");
+    }
```
Comment (nicolo-ribaudo) [inline packages/babel-helpers/src/helpers.js:2031]: We can extract this code in a third helper and share it between the two helpers:

```js
import checkPrivateRedeclaration from "checkPrivateRedeclaration";

export default function _classPrivateMethodInitSpec(obj, privateSet) {
  checkPrivateRedeclaration(privateSet, obj);
  privateSet.add(obj);
}
```

**Comment by colinaaa** [comment]
Since https://github.com/babel/babel/pull/13570 has been merged, you probably need to rebase to main and write code with typings

File: packages/babel-helper-create-class-features-plugin/src/fields.ts (hunk 2 above)
Comment (komyg) [reply packages/babel-helper-create-class-features-plugin/src/fields.ts]: Done!

**Comment by komyg** [comment]
> Since #13570 has been merged, you probably need to rebase to main and write code with typings

Done!

Thank you for the typings by the way. They will be very hepful.

File: packages/babel-helper-create-class-features-plugin/src/fields.ts [hunk 5]
```diff
@@ -510,16 +510,34 @@ function buildPrivateInstanceFieldInitSpec(
...
+    !process.env.BABEL_8_BREAKING &&
+    !state.availableHelper("classPrivateFieldInitSpec")
+  ) {
+    return template.statement.ast`${t.cloneNode(id)}.set(${ref}, {
+      // configurable is always false for private elements
+      // enumerable is always false for private elements
+      writable: true,
+      value: ${value},
+    })`;
+  }
```
Comment (nicolo-ribaudo) [inline packages/babel-helper-create-class-features-plugin/src/fields.ts:528]: This needs to be two separate `if`s. Our logic to conditionally remove Babel 7 code or Babel 8 code at release time isn't smart enough :grimacing: 

```js
if (!process.env.BABEL_8_BREAKING) {
  if (!state.availableHelper("classPrivateFieldInitSpec")) {
    ...
  }
}
```

File: packages/babel-helper-create-class-features-plugin/src/fields.ts [hunk 6]
```diff
@@ -839,8 +865,8 @@ export function buildFieldsInitNodes(
 ) {
   let needsClassRef = false;
   let injectSuperRef: t.Identifier;
-  const staticNodes: t.Statement[] = [];
-  const instanceNodes: t.Statement[] = [];
+  const staticNodes: Array<t.Expression | t.Statement> = [];
+  const instanceNodes: Array<t.Expression | t.Statement> = [];
```
Comment (nicolo-ribaudo) [inline packages/babel-helper-create-class-features-plugin/src/fields.ts:869]: This is a bug! Those nodes are inserted in statement positions, so they should always be statements. `buildPrivateInstanceMethodInitSpec` should return `t.expressionStatement(expr)` instead of just `expr`.

File: packages/babel-helper-create-class-features-plugin/src/fields.ts [hunk 7]
```diff
@@ -622,7 +641,14 @@ function buildPrivateInstanceMethodInitSpec(
       });
     `;
   }
-  return template.statement.ast`${id}.add(${ref})`;
+
+  if (!state.availableHelper("classPrivateMethodInitSpec")) {
+    template.statement.ast`${id}.add(${ref})`;
```
Comment (nicolo-ribaudo) [inline packages/babel-helper-create-class-features-plugin/src/fields.ts:646]:
```suggestion
    return template.statement.ast`${id}.add(${ref})`;
```

File: packages/babel-helper-create-class-features-plugin/src/fields.ts (hunk 6 above)
Comment (colinaaa) [reply packages/babel-helper-create-class-features-plugin/src/fields.ts:869]: Seems that typings are not only convenient for writing codes, but also for reviewing codes :)

**Comment by nicolo-ribaudo** [comment]
Can you run `OVERWRITE=true yarn jest` or `OVERWRITE=true make test`?

**Comment by komyg** [comment]
> Can you run `OVERWRITE=true yarn jest` or `OVERWRITE=true make test`?

Done.

I've pushed all the snapshot changes.

**Comment by nicolo-ribaudo** [comment]
The CI failure would be fixed by rebasing; don't worry about it.

File: packages/babel-helper-create-class-features-plugin/src/fields.ts [hunk 8]
```diff
@@ -510,16 +510,33 @@ function buildPrivateInstanceFieldInitSpec(
...
-    value: ${value},
-  })`;
+  if (!process.env.BABEL_8_BREAKING) {
+    if (!state.availableHelper("classPrivateFieldInitSpec")) {
+      return template.statement.ast`${t.cloneNode(id)}.set(${ref}, {
+      // configurable is always false for private elements
+      // enumerable is always false for private elements
+      writable: true,
+      value: ${value},
+    })`;
```
Comment (nicolo-ribaudo) [inline packages/babel-helper-create-class-features-plugin/src/fields.ts:525]:
```suggestion
        // configurable is always false for private elements
        // enumerable is always false for private elements
        writable: true,
        value: ${value},
      })`;
```

File: packages/babel-helper-create-class-features-plugin/src/fields.ts [hunk 9]
```diff
@@ -510,16 +510,33 @@ function buildPrivateInstanceFieldInitSpec(
...
+  }
+
+  const helper = state.addHelper("classPrivateFieldInitSpec");
+  const expr = t.callExpression(helper, [
+    t.thisExpression(),
+    t.cloneNode(id),
+    template.expression.ast`{
+        writable: true,
+        value: ${value}
+      }`,
```
Comment (nicolo-ribaudo) [inline packages/babel-helper-create-class-features-plugin/src/fields.ts:536]:
```suggestion
      writable: true,
      value: ${value}
    }`,
```

**Review by nicolo-ribaudo — APPROVED** [review]
Thanks!

File: packages/babel-helper-create-class-features-plugin/src/fields.ts [hunk 10]
```diff
@@ -602,27 +619,87 @@ function buildPrivateInstanceMethodInitSpec(
...
+  const expr = t.callExpression(helper, [
+    t.thisExpression(),
+    t.cloneNode(id),
+    template.expression.ast`{
+        get: ${getId ? getId.name : prop.scope.buildUndefinedNode()},
+        set: ${setId ? setId.name : prop.scope.buildUndefinedNode()}
+      }`,
+  ]);
+
+  return t.expressionStatement(expr);
```
Comment (jridgewell) [inline packages/babel-helper-create-class-features-plugin/src/fields.ts:682]: Nit: ditto

```suggestion
  return template.statement.ast`${helper}(
    ${t.thisExpression()},
    ${id},
    {
      get: ${getId ? getId.name : prop.scope.buildUndefinedNode()},
      set: ${setId ? setId.name : prop.scope.buildUndefinedNode()}
    },
  )`;
```

File: packages/babel-helper-create-class-features-plugin/src/fields.ts [hunk 11]
```diff
@@ -602,27 +619,87 @@ function buildPrivateInstanceMethodInitSpec(
...
+
+  if (!process.env.BABEL_8_BREAKING) {
+    if (!state.availableHelper("classPrivateMethodInitSpec")) {
+      return template.statement.ast`${id}.add(${ref})`;
+    }
+  }
+
+  const helper = state.addHelper("classPrivateMethodInitSpec");
+  const expr = t.callExpression(helper, [t.thisExpression(), t.cloneNode(id)]);
+  return t.expressionStatement(expr);
```
Comment (jridgewell) [inline packages/babel-helper-create-class-features-plugin/src/fields.ts:702]: Nit: ditto

```suggestion
  return template.statement.ast`${helper}(${t.thisExpression()}, ${id})`;
```

File: packages/babel-helper-create-class-features-plugin/src/fields.ts [hunk 12]
```diff
@@ -510,16 +510,33 @@ function buildPrivateInstanceFieldInitSpec(
...
+  const expr = t.callExpression(helper, [
+    t.thisExpression(),
+    t.cloneNode(id),
+    template.expression.ast`{
+      writable: true,
+      value: ${value}
+    }`,
+  ]);
+
+  return t.expressionStatement(expr);
```
Comment (jridgewell) [inline packages/babel-helper-create-class-features-plugin/src/fields.ts:539]: Nit: I think you can use template to generate the full call here:

```suggestion
  return template.statement.ast`${helper}(
    ${t.thisExpression()},
    ${id},
    {
      writable: true,
      value: ${value}
    },
  )`;
```

**Review by jridgewell — APPROVED** [review]

File: packages/babel-helper-create-class-features-plugin/src/fields.ts (hunk 12 above)
Comment (JLHwung) [reply packages/babel-helper-create-class-features-plugin/src/fields.ts:539]: The `id` above should still be cloned though.

**Review by JLHwung — APPROVED** [review]

**Comment by komyg** [comment]
Hi, I've incorporated all of your suggestions and added the latest changes from the main branch.

Would you like to re-review it?

**Review by jridgewell — APPROVED** [review]
LGTM, thanks for working on this!

**Review by nicolo-ribaudo — APPROVED** [review]
Thank you!
