### PR TITLE
Fix optional method chaining in derived classes

### LINKED ISSUE #10673: Optional chaining on super.method() breaks
## Bug Report

**Current Behavior**
Optional call of a super method (`super.method?.()`) attempts to use `super` as an identifier, which is invalid. This might only happen in strict mode?

**Input Code**
[REPL](https://babeljs.io/repl/#?babili=false&browsers=last%201%20and_chr%20version%0A&build=&builtIns=usage&spec=false&loose=false&code_lz=MYGwhgzhAEBCkFNoG8BQ0PQLYIC4AsB7AEwAoBKFaAX1VtVEhgBEEAnASwDcFjoEAHrgQA7YjHgQkaTNjxEylGbMxs8AVzYjoEdQAd2AOhwESAfkMV0mWtSA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=stage-3&prettier=false&targets=&version=7.7.2&externalPlugins=)

```js
class Base {
    method() { }
}

class Sub extends Base {
    method() {
        return super.method?.()
    }
}
```

**Expected behavior/code**
Super method must always be invoked as `super.method()`, not `method.call(super)`

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "plugins": [ "@babel/plugin-proposal-optional-chaining" ]
}
```

**Environment**
- Babel version(s): 7.7.2
- Node/npm version: any
- OS: any
- Monorepo: any
- How you are using Babel: REPL

**Possible Solution**

Two different possible solutions:

1. ~Access `super.method` twice~ (Don't do this, see https://github.com/babel/babel/issues/10673#issuecomment-550959334)
2. Call the cached method with `this` instead of super

<details>

<summary>Solution 1 (ignore this)</summary>

```js
// Solution 1
// Input
super.method?.();

// Output
((_super$method = super.method) === null || _super$method === undefined)
  ? undefined
  : super.method();
```

</details>

```js
// Solution 2
// Input
super.method?.();

// Output
((_super$method = super.method) === null || _super$method === undefined)
  ? undefined
  : _super$method.call(this)
```

**Additional context/Screenshots**

This should be a beginner level fix.

### PR DESCRIPTION
**Pull request by Shriram-Balaji**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #10673  
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | Yes
| Documentation PR Link    |  NA 
| Any Dependency Changes?  | No
| License                  | MIT

### CODE REVIEW

File: packages/babel-plugin-proposal-optional-chaining/src/index.js [hunk 1]
```diff
@@ -86,6 +86,10 @@ export default declare((api, options) => {
                 context = object;
               }
 
+              if (t.isSuper(context)) {
```
Comment (jridgewell) [inline packages/babel-plugin-proposal-optional-chaining/src/index.js]: Nit: We can put this with the `if else` above.

File: packages/babel-plugin-proposal-optional-chaining/test/fixtures/general/super-method-call/input.js [hunk 2]
```diff
@@ -0,0 +1,12 @@
+"use strict";
```
Comment (jridgewell) [inline packages/babel-plugin-proposal-optional-chaining/test/fixtures/general/super-method-call/input.js]: Could you also add a `loose` test?  We can reuse this same `input.js` file, just copy it to a new folder and also copy https://github.com/babel/babel/blob/76cb2010e350a1ef69966d92c0d706e6115efca3/packages/babel-plugin-proposal-optional-chaining/test/fixtures/general/function-call-loose/options.json into the same fodler.

File: packages/babel-plugin-proposal-optional-chaining/src/index.js (hunk 1 above)
Comment (Shriram-Balaji) [reply packages/babel-plugin-proposal-optional-chaining/src/index.js]: @jridgewell Would you like for `t.isSuper` to be called twice in the `if else`? because context would be null if it wasnt memoized before, right?

File: packages/babel-plugin-proposal-optional-chaining/test/fixtures/general/super-method-call/input.js (hunk 2 above)
Comment (Shriram-Balaji) [reply packages/babel-plugin-proposal-optional-chaining/test/fixtures/general/super-method-call/input.js]: Sure, added this.

File: packages/babel-plugin-proposal-optional-chaining/src/index.js [hunk 3]
```diff
@@ -86,6 +86,10 @@ export default declare((api, options) => {
...
+                context = t.thisExpression();
+              }
+
               node.arguments.unshift(t.cloneNode(context));
```
[the remark this answers is not in the document]
Comment (nicolo-ribaudo) [reply packages/babel-plugin-proposal-optional-chaining/src/index.js]: But it's already used inside the `t.assignmentExpression` of the `if` branch.

File: packages/babel-plugin-proposal-optional-chaining/src/index.js (hunk 1 above)
Comment (jridgewell) [reply packages/babel-plugin-proposal-optional-chaining/src/index.js]: There should only be one check needed. The only way `context` would be a `Super` here is if it went into the `else` case (because if it when through the `if` case it would be an `AssignmentExpression`). So we need to do an `else if` (before the current `else`) to check if `t.isSuper(object)`.

Comment (Shriram-Balaji) [reply packages/babel-plugin-proposal-optional-chaining/src/index.js]: @jridgewell Alright, that makes sense. The changes are done now 😄

File: packages/babel-plugin-proposal-optional-chaining/src/index.js [hunk 4]
```diff
@@ -82,6 +82,8 @@ export default declare((api, options) => {
               let context = scope.maybeGenerateMemoised(object);
               if (context) {
                 chain.object = t.assignmentExpression("=", context, object);
+              } else if (t.isSuper(context)) {
```
Comment (JLHwung) [inline packages/babel-plugin-proposal-optional-chaining/src/index.js]:
```suggestion
              } else if (t.isSuper(object)) {
```
`context` is `null` in the `else` branch.

Comment (Shriram-Balaji) [reply packages/babel-plugin-proposal-optional-chaining/src/index.js]: @JLHwung Oh right, that's what I meant to do. Fixed now.

**Comment by existentialism** [comment]
@Shriram-Balaji thanks! great work!
