### PR TITLE
Fix parsing of imports with module string name in flow plugin

### LINKED ISSUE #12209: babel-parser throws syntax error for import string names with `flow` plugin
## Bug Report

- [x] I would like to work on a fix!

**Current behavior**

babel-parser throws syntax error `Unexpected token (1:9)` with `moduleStringNames` plugin and `flow` plugin. ([REPL](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAbzgIgGYQsuBDAzndCOAXwKghBRAgBMBXAGwFMBabZAbgCgg&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env%2Cflow%2Cenv&prettier=false&targets=&version=7.12.3&externalPlugins=%40babel%2Fplugin-syntax-module-string-names%407.12.1))
This happens on `import` only, `export` works fine. ([REPL](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAbzgIgGYQsuBDAzndCOAXwKggFsUKIATAVwBtgBabZAbgCgg&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env%2Cflow%2Cenv&prettier=false&targets=&version=7.12.3&externalPlugins=%40babel%2Fplugin-syntax-module-string-names%407.12.1))

**Input Code**

```js
import { "foo" as foo } from "module-a";
```

**Expected behavior**

No syntax error is thrown.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
Call `parse` directly.
```js
const code = `import { "foo" as foo } from "module-a";`;
require("@babel/parser").parse(code, {
  sourceType: "module",
  plugins: ["moduleStringNames", "flow"],
});
```

**Environment**

**Possible Solution**

**Additional context**

Found from working on https://github.com/prettier/prettier/pull/9408

### PR DESCRIPTION
**Pull request by sosukesuzuki**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #12209
| Patch: Bug Fix?          | Y
| Major: Breaking Change?  | N
| Minor: New Feature?      | N
| Tests Added + Pass?      | Y
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/12224"></a>

### CODE REVIEW

**Review by existentialism — APPROVED** [review]

File: packages/babel-parser/src/plugins/flow.js [hunk 1]
```diff
@@ -2525,10 +2527,12 @@ export default (superClass: Class<Parser>): Class<Parser> =>
...
       } else if (
         specifierTypeKind !== null &&
-        (this.match(tt.name) || this.state.type.keyword)
+        (this.match(tt.name) ||
+          this.match(tt.string) ||
+          this.state.type.keyword)
       ) {
         // `import {type foo`
-        specifier.imported = this.parseIdentifier(true);
+        specifier.imported = this.parseModuleExportName();
```
Comment (JLHwung) [inline packages/babel-parser/src/plugins/flow.js:2535]: I don't think `import { type "foo" } from "bar"` is supported in flow, neither implied from `moduleStringNames`. 
Since `moduleStringNames` are meant to offer compatibility for WASM modules, I don't think Flow will practically support it in type imports.

**Review by JLHwung — APPROVED** [review]

**Review by nicolo-ribaudo — APPROVED** [review]

**Comment by nicolo-ribaudo** [comment]
Thanks!
