### PR TITLE
fix: improve module block program location tracking

### LINKED ISSUE #15051: [Bug]: regression for module block parse
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```console
> require('@babel/parser').parse('module {/* comment */}', {plugins: ['moduleBlocks']}).program.body[0].expression.body
Node {
  type: 'Program',
  start: 21,   // <---------------------
  end: 8,  // <---------------------
  loc: SourceLocation {
    start: Position { line: 1, column: 21, index: 21 },
    end: Position { line: 1, column: 8, index: 8 },
    filename: undefined,
    identifierName: undefined
  },
  sourceType: 'module',
  interpreter: null,
  body: [],
  directives: [],
  trailingComments: [
    {
      type: 'CommentBlock',
      value: ' comment ',
      start: 8,
      end: 21,
      loc: [SourceLocation]
    }
  ]
}
```

### Configuration file name

_No response_

### Configuration

N/A

### Current and expected behavior

Range should be `8 ~ 21`

### Environment

N/A

### Possible solution

_No response_

### Additional context

Possible introduced in #14980 @JLHwung

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #15051 
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

This PR ensures that a module block's program starts immediately after `{` and ends immediately before the matching `}`. By doing so we aligns the comment attaching behaviour of a program within a module block to a top level program.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15052"></a>

### CODE REVIEW

File: packages/babel-parser/src/parser/statement.ts [hunk 1]
```diff
@@ -1208,6 +1216,8 @@ export default abstract class StatementParser extends ExpressionParser {
     if (!oldStrict) {
       this.setStrict(false);
     }
+
+    this.next();
```
Comment (JLHwung) [inline packages/babel-parser/src/parser/statement.ts:1220]: This is essentially reverting changes in https://github.com/babel/babel/pull/14980/commits/101cad5322f47907244575df1713e09d355ec31b.

File: packages/babel-parser/test/fixtures/experimental/module-blocks/valid-trailing-comment-module-blocks/input.js [hunk 2]
```diff
@@ -0,0 +1,3 @@
+module {
+  /* leading */ x /* trailing */
```
Comment (JLHwung) [inline packages/babel-parser/test/fixtures/experimental/module-blocks/valid-trailing-comment-module-blocks/input.js:2]: Currently Babel attaches `trailing` as the trailing comment of the Program node because the parser finishes the Program node before `/* trailing */`.

Now the behaviour is aligned to how we parse plain `/* leading */ x /* trailing */`.

**Review by liuxingbaoyu — APPROVED** [review]

File: packages/babel-parser/src/parser/expression.ts [hunk 3]
```diff
@@ -3236,18 +3236,24 @@ export default abstract class ExpressionParser extends LValParser {
...
-    this.expect(tt.braceL);
+    if (!this.match(tt.braceL)) {
+      this.unexpected(null, tt.braceL);
+    }
+    // start program node immediately after `{`
+    const program = this.startNodeAt<N.Program>(
+      this.state.end,
+      this.state.endLoc,
+    );
+    this.next(); // eat `{`
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/src/parser/expression.ts:3247]: Nit, but we could use `this.state.lastTokEnd`/`this.state.lastTokEnd.index` to keep using expect instead of this math-createNode-next dance.

**Review by nicolo-ribaudo — APPROVED** [review]

File: packages/babel-parser/src/parser/expression.ts (hunk 3 above)
Comment (JLHwung) [reply packages/babel-parser/src/parser/expression.ts:3150]: They are not equivalent. For example
```js
module { /* 1 */ }
```
When we see a left brace `{`, `this.state.endLoc` points to the whitespace after `{`, while `this.state.lastTokEnd` after `{` is eaten will point to the whitespace immediately after the comment `/* 1 */`.

Comment (nicolo-ribaudo) [reply packages/babel-parser/src/parser/expression.ts:3150]: 👍

**Review by nicolo-ribaudo — APPROVED** [review]
