### PR TITLE
Map commonjs named imports back to the correct location - fixes #1987

### LINKED ISSUE #1987: Unhelpful source map for module imports
Create an empty directory and run:

	npm install babel source-map-support
	mkdir src
	touch src/index.js src/module.js

index.js:

	import { assert } from './module'
	import { install } from 'source-map-support'
	install()

	const testMath = () => {
		assert(1 + 1 === 2)
		assert(2 + 2 === 5)
		assert(3 + 3 === 6)
	}

	testMath()

module.js:

	export const assert = cond => {
		if (!cond)
			throw new Error("Assertion failed.")
	}

Then:

	node_modules/babel/bin/babel/index.js src --out-dir js --source-maps
	node js

You'll see:

	Error: Assertion failed.
		at assert (/home/andy/programming/mason3/eslint-bugs/src/module.js:3:9)
		at testMath (/home/andy/programming/mason3/eslint-bugs/src/index.js:1:16)
		at Object.<anonymous> (/home/andy/programming/mason3/eslint-bugs/src/index.js:11:1)

It doesn't identify the line that failed.
It instead shows the line where the function was imported, which isn't helpful.

### PR DESCRIPTION
**Pull request by loganfsmyth**
The import identifier is being used as the property in the new member expression, but still had its original location information.

### CODE REVIEW

File: packages/babel/src/transformation/modules/common.js [hunk 1]
```diff
@@ -91,8 +92,11 @@ export default class CommonJSFormatter extends DefaultFormatter {
           t.variableDeclarator(variableName, ref)
         ]));
       } else {
+        var importedIdentifier = t.cloneDeep(specifier.imported);
```
Comment (sebmck) [inline packages/babel/src/transformation/modules/common.js]: Add a comment above pointing back to the original issue please.

File: packages/babel/src/transformation/modules/common.js [hunk 2]
```diff
@@ -1,6 +1,7 @@
 import DefaultFormatter from "./_default";
 import * as util from  "../../util";
 import * as t from "../../types";
+import traversal from "../../traversal";
```
Comment (sebmck) [inline packages/babel/src/transformation/modules/common.js]: `traversal` -> `traverse` for consistency.

File: packages/babel/src/transformation/modules/common.js [hunk 3]
```diff
@@ -91,8 +92,11 @@ export default class CommonJSFormatter extends DefaultFormatter {
           t.variableDeclarator(variableName, ref)
         ]));
       } else {
+        var importedIdentifier = t.cloneDeep(specifier.imported);
+        traversal.clearNode(importedIdentifier);
```
Comment (sebmck) [inline packages/babel/src/transformation/modules/common.js]: Isn't this equivalent to just `t.identifier(specifier.imported.name)`?

Comment (loganfsmyth) [inline packages/babel/src/transformation/modules/common.js]: Oh yeah, I guess I can do that too. I like that better. Do you think I should still add the comment with the issue number in that case?

Comment (sebmck) [inline packages/babel/src/transformation/modules/common.js]: Nah the comment wont be necessary in that case then.

**Comment by loganfsmyth** [comment]
@sebmck Updated.

**Comment by sebmck** [comment]
Thanks @loganfsmyth!
