### PR TITLE
fix(ts): raise error for `export default interface {}`

### LINKED ISSUE #13520: [Bug]:  Parse error when using named import "as" with `babel-plugin-transform-flow-strip-types`
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

A file containing a named import using `as` or `As` results in a parse error when using the `babel-plugin-transform-flow-strip-types`. This plugin is used by `babelJest` when transpiling some tests including ES6 modules.

For example, this excerpt belongs to a file defining a named import with name `as`, which is absolutely valid.

```js
import { historyIcon as as } from "../shapes/history.js";
```

_How to get this file:_ 
```
wget `npm v @cds/core dist.tarball` && tar -xOzf core-5.4.1.tgz package/icon/collections/essential.js 
```

### Configuration file name

_No response_

### Configuration

Using the default config in CRA (create-react-application):
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/jest/babelTransform.js#L26-L37

### Current and expected behavior

Current behavior when running `yarn test` in my app:

```console
SyntaxError: /home/agamez/Desktop/kubeapps/dashboard/node_modules/@cds/core/icon/collections/essential.js: Unexpected token, expected "," (1:3239)

    > 58 | import{historyIcon as as}from"../shapes/history.js";
         |                    ^

      at Object._raise (node_modules/@babel/parser/src/parser/error.js:97:45)
      at Object.raiseWithData (node_modules/@babel/parser/src/parser/error.js:92:17)
      at Object.raise (node_modules/@babel/parser/src/parser/error.js:41:17)
      at Object.unexpected (node_modules/@babel/parser/src/parser/util.js:161:16)
      at Object.expect (node_modules/@babel/parser/src/parser/util.js:138:28)
      at Object.parseNamedImportSpecifiers (node_modules/@babel/parser/src/parser/statement.js:2364:14)
      at Object.parseImport (node_modules/@babel/parser/src/parser/statement.js:2145:39)
      at Object.parseStatementContent (node_modules/@babel/parser/src/parser/statement.js:265:25)
      at Object.parseStatement (node_modules/@babel/parser/src/parser/statement.js:176:17)
      at Object.parseStatement (node_modules/@babel/parser/src/plugins/flow/index.js:1815:26)
```

Expected behavior: no parse errors whatsoever.

### Environment

```
  System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 7.15.1 - ~/.nvm/versions/node/v14.15.0/bin/npm
```

### Possible solution

When enabling (using the default true value) `flow` in CRA [it loads the `@babel/plugin-transform-flow-strip-types'` plugin](https://github.com/facebook/create-react-app/blob/master/packages/babel-preset-react-app/create.js#L111) which is  [loading getting the AST given a file](https://github.com/babel/babel/blob/main/packages/babel-plugin-transform-flow-strip-types/src/index.js#L28). Here is where the parse error is returned.

My guess is that the parser used by this plugin is performing a wrong tokenization in the particular case of a named import with the same value as the predecessor token `as`.

### Additional context

I wasn't able to reproduce the parse error using the `babelParser.parse` method manually, so I guess it has something to do with the `babel-plugin-transform-flow-strip-types` plugin.

More context: https://github.com/kubeapps/kubeapps/pull/3042#issuecomment-870053634

### LINKED ISSUE #13604: [Bug]: `export default interface {}` should throw
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
export default interface {}
```

[REPL](https://babel.dev/repl#?browsers=ie%2011&build=&builtIns=false&corejs=false&spec=false&loose=true&code_lz=KYDwDg9gTgLgBAE2AYwDYEMrDgSwHYzBQBm6y2A3gL4DcQA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=typescript&prettier=false&targets=&version=7.14.8&externalPlugins=)

### Configuration file name

_No response_

### Configuration

```json
{
  "presets": ["@babel/preset-typescript"]
}
```

### Current and expected behavior

Current: Parsed incorrectly as an ExportDeclaration with ObjectExpression.

Expected: Babel should throw an identifier is expected after `interface`, aligning to TSC behaviour: [TS Playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAE2AMwIYFcA28CWA7GYKNAY2DgG8BfIA)

### Environment

REPL

### Possible solution

Babel parser handles `export default interface {}` in 

https://github.com/babel/babel/blob/e0dc925bbe148022df6b43dd6965ebca661915fc/packages/babel-parser/src/plugins/typescript/index.js#L1801-L1803

The `tsCheckLineTerminator` eats `interface` but then since parser doesn't see a `tt.name` (identifier token) following, it exits without rewinding the parser states so the source is parsed as if it were `export default {}`.

We can perform lookahead after `interface` and see if it is a `tt.name` in https://github.com/babel/babel/blob/e0dc925bbe148022df6b43dd6965ebca661915fc/packages/babel-parser/src/plugins/typescript/index.js#L2307-L2315

like how we handle `export default abstract class`: 

https://github.com/babel/babel/blob/e0dc925bbe148022df6b43dd6965ebca661915fc/packages/babel-parser/src/plugins/typescript/index.js#L2290-L2294

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by a-tarasyuk**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #13604 | Patch: Bug Fix?          |
| Tests Added + Pass?      | Yes
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/13622"></a>

### CODE REVIEW

File: packages/babel-parser/src/plugins/typescript/index.js [hunk 1]
```diff
@@ -2305,13 +2306,17 @@ export default (superClass: Class<Parser>): Class<Parser> =>
       // export default interface allowed in:
       // https://github.com/Microsoft/TypeScript/pull/16040
       if (this.state.value === "interface") {
```
Comment (fedeci) [inline packages/babel-parser/src/plugins/typescript/index.js:2308]: We should avoid using `lookahead()` as it is expensive. We may have to save the start location of the `interface` token, call `this.next()` and then check if the current token is a `tt.name`.

File: packages/babel-parser/src/plugins/typescript/index.js [hunk 2]
```diff
@@ -2305,13 +2306,17 @@ export default (superClass: Class<Parser>): Class<Parser> =>
...
+        if (this.lookahead().type === tt.name) {
+          const result = this.tsParseDeclaration(
+            this.startNode(),
+            this.state.value,
+            true,
+          );
+          if (result) return result;
+        } else {
+          this.next();
+          this.raise(this.state.pos, TSErrors.IdentifierExpected);
```
Comment (fedeci) [inline packages/babel-parser/src/plugins/typescript/index.js:2318]: If we do what I wrote above we have already skipped interface, so we can 
```suggestion
          this.raise(this.state.start, TSErrors.IdentifierExpected);
```

File: packages/babel-parser/src/plugins/typescript/index.js [hunk 3]
```diff
@@ -90,6 +90,7 @@ const TSErrors = makeErrorTemplates(
     EmptyTypeParameters: "Type parameter list cannot be empty.",
     ExpectedAmbientAfterExportDeclare:
       "'export declare' must be followed by an ambient declaration.",
+    IdentifierExpected: "Identifier expected.",
```
Comment (fedeci) [inline packages/babel-parser/src/plugins/typescript/index.js:93]: Can we provide a more specific error message?

Comment (a-tarasyuk) [reply packages/babel-parser/src/plugins/typescript/index.js:93]: > Expected: Babel should throw an identifier is expected after interface, aligning to TSC behaviour: TS Playground

File: packages/babel-parser/src/plugins/typescript/index.js (hunk 1 above)
Comment (a-tarasyuk) [reply packages/babel-parser/src/plugins/typescript/index.js:2308]: > We can perform lookahead after interface and see if it is a tt.name in like how we handle export default abstract class: https://github.com/babel/babel/issues/13604

File: packages/babel-parser/src/plugins/typescript/index.js (hunk 3 above)
Comment (a-tarasyuk) [reply packages/babel-parser/src/plugins/typescript/index.js:93]: Do we need to follow the description from `Expected` section?

Comment (fedeci) [reply packages/babel-parser/src/plugins/typescript/index.js:93]: Aligning to `tsc` doesn't always mean to throw the same errors😄
Probably `'export default interface' must be followed by an identifier.` would be better.

Comment (a-tarasyuk) [reply packages/babel-parser/src/plugins/typescript/index.js:93]: > Babel should throw an identifier is expected after interface
It seems the issue description should be changed to avoid confusion.

Comment (fedeci) [reply packages/babel-parser/src/plugins/typescript/index.js:93]: We are not handling interfaces here but interfaces exported as default. We can provide a specific error message that would be more useful to users.

File: packages/babel-parser/src/plugins/typescript/index.js (hunk 1 above)
Comment (fedeci) [reply packages/babel-parser/src/plugins/typescript/index.js:2308]: Probably it was suggested because `lookahead` has recently got perf improvements. I would still avoid it if we can.

Comment (JLHwung) [reply packages/babel-parser/src/plugins/typescript/index.js:2308]: I mentioned `lookahead` before because it could solve the original problem. In TS the `interface` is a reserved keyword so we can avoid the lookahead and just throw if there is no `tt.name` after `interface`, since

```js
export default interface[0];
export default interface(0);
```

are invalid in TS, though they are valid in JS.

Comment (nicolo-ribaudo) [reply packages/babel-parser/src/plugins/typescript/index.js:2309]: Well, `interface` is a reserved word in JS strict mode and thus in modules (https://tc39.es/ecma262/#sec-identifiers-static-semantics-early-errors, last production).

File: packages/babel-parser/src/plugins/typescript/index.js [hunk 4]
```diff
@@ -102,6 +102,8 @@ const TSErrors = makeErrorTemplates(
       "'override' modifier cannot appear on an index signature.",
     IndexSignatureHasStatic:
       "Index signatures cannot have the 'static' modifier.",
+    InvalidInterfaceDeclarationInExportDefault:
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/src/plugins/typescript/index.js:105]: I would _slightly_ prefer to name this `MissingExportDefaultInterfaceName` (or even just `MissingInterfaceName` so that we can potentially reuse it for `interface {}` outside of an export default declaration).

The error message is ok.

File: packages/babel-parser/src/plugins/typescript/index.js [hunk 5]
```diff
@@ -2305,13 +2307,23 @@ export default (superClass: Class<Parser>): Class<Parser> =>
...
-        );
+        const interfaceNode = this.startNode();
+        const prevValue = this.state.value;
+        this.next();
 
-        if (result) return result;
+        if (this.state.type === tt.name) {
+          const result = this.tsParseDeclaration(
+            interfaceNode,
+            prevValue,
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/src/plugins/typescript/index.js:2317]:
```suggestion
            "interface",
```

`prevValue` is always `"interface"` here (it's guarded in the `if` at line 2309), so we don't need to store it in a variable.

File: packages/babel-parser/test/fixtures/typescript/interface/export-default/output.json [hunk 6]
```diff
@@ -0,0 +1,26 @@
...
+      {
+        "type": "ExportDefaultDeclaration",
+        "start":0,"end":27,"loc":{"start":{"line":1,"column":0},"end":{"line":1,"column":27}},
+        "exportKind": "value",
+        "declaration": {
+          "type": "ObjectExpression",
+          "start":25,"end":27,"loc":{"start":{"line":1,"column":25},"end":{"line":1,"column":27}},
+          "properties": []
+        }
+      }
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/test/fixtures/typescript/interface/export-default/output.json:22]: I don't like this output. It was already the old output we generated before this PR, but since we are modifying the code that generates it we can use this chance to improve it.

If the interface name is missing, we should still parse it as an interface and set `id` to `null`.

We can modify the `tsParseInterfaceDeclaration` function and move the error checking there, instead of in `parseExportDefaultExpression`:
```js
    tsParseInterfaceDeclaration(
      node: N.TsInterfaceDeclaration,
    ): N.TsInterfaceDeclaration {
      if (this.match(tt.name)) {
        node.id = this.parseIdentifier();
        this.checkLVal(
          node.id,
          "typescript interface declaration",
          BIND_TS_INTERFACE,
        );
      } else {
        node.id = null;
        this.raise(
          this.state.start,
          TSErrors.InvalidInterfaceDeclarationInExportDefault,
        );
      }
```

We can then directly call `tsParseInterfaceDeclaration` instead of `tsParseDeclaration` in the code you modified.

**Review by nicolo-ribaudo — COMMENTED** [review]
Thanks! Except for two minor comments, I think we can modify this PR's implementation to further improve the current generated AST.

File: packages/babel-parser/src/plugins/typescript/index.js (hunk 1 above)
Comment (JLHwung) [reply packages/babel-parser/src/plugins/typescript/index.js:2309]: Since export default is only allowed in module, we can safely assume interface is a reserved word here.

File: packages/babel-parser/src/plugins/typescript/index.js [hunk 7]
```diff
@@ -107,6 +107,8 @@ const TSErrors = makeErrorTemplates(
     InvalidModifiersOrder: "'%0' modifier must precede '%1' modifier.",
     InvalidTupleMemberLabel:
       "Tuple members must be labeled with a simple identifier.",
+    MissingInterfaceName:
+      "'export default interface' must be followed by an identifier.",
```
Comment (fedeci) [inline packages/babel-parser/src/plugins/typescript/index.js:111]: Now that we changed the generic behaviour for interface parsing we want to have a generic error too. `'interface' declarations must be followed by an identifier.` should be good.

File: packages/babel-parser/src/plugins/typescript/index.js [hunk 8]
```diff
@@ -2305,12 +2313,9 @@ export default (superClass: Class<Parser>): Class<Parser> =>
...
-        const result = this.tsParseDeclaration(
-          this.startNode(),
-          this.state.value,
-          true,
-        );
-
+        const interfaceNode = this.startNode();
+        this.next();
+        const result = this.tsParseInterfaceDeclaration(interfaceNode);
         if (result) return result;
```
Comment (fedeci) [inline packages/babel-parser/src/plugins/typescript/index.js:2319]: Is this check still required?

Comment (a-tarasyuk) [reply packages/babel-parser/src/plugins/typescript/index.js:2319]: It seems - yes

File: packages/babel-parser/src/plugins/typescript/index.js (hunk 7 above)
Comment (a-tarasyuk) [reply packages/babel-parser/src/plugins/typescript/index.js]: I've changed the message.

**Review by JLHwung — APPROVED** [review]
Thanks!

**Review by fedeci — APPROVED** [review]
