### PR TITLE
fix: do expressions should allow early exit

### LINKED ISSUE #5233: do expressions should allow return statements
https://twitter.com/sebmarkbage/status/825197254252257280

```js
function method() {
  let a = do {
    if (true) return 1;
    2;
  };
  return a;
}

let result = method();

assert(result === 1);
```

### PR DESCRIPTION
**Pull request by kermanx**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | fixes #5233
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | Yes
| Documentation PR Link    | -
| Any Dependency Changes?  | No external dependencies added
| License                  | MIT

Fixes #5233. Unwraps do expressions to allow early exits.

Previously, the do expressions are transformed into an immediately invoked function expression, which will make `break`/`continue`/`return` to the outer scopes not working (which should, according to the [proposal](https://github.com/tc39/proposal-do-expressions#breakcontinuereturn)).

In this PR, the do expressions are flattened to multiple statements, to address this problem. This is done by:

1. Searching for the closest wrapping statement, which is about to be flattened.
2. For this statement, each children expressions with side-effects before the do-expressions (because those after all the do-expressions can be preserved with a correct side-effect order) will be extracted to the same level as the original statement, recursively. And the results will be stored in temporary variables like `_do1`.

### Example Input

```js
async function p(x) {
  const y = effect(0) + do {
    if (effect(1)) {
      return x;
    }
    if (effect(2)) {
      const zz = effect(10) + do {
        if (effect(11)) {
          return x;
        }
        if (effect(12)) {
          11
        }
      } + effect(13);
      zz
    } else {
      2
    }
  } + effect(3);
  return y;
}
```

### Example Output

```js
async function p(x) {
  var _do3;
  _do3 = effect(0);
  {
    var _do4;
    if (effect(1)) {
      return x;
    }
    if (effect(2)) {
      var _do;
      _do = effect(10);
      {
        var _do2;
        if (effect(11)) {
          return x;
        }
        if (effect(12)) {
          _do2 = 11;
        }
      }
      const zz = _do + _do2 + effect(13);
      _do4 = zz;
    } else {
      _do4 = 2;
    }
  }
  const y = _do3 + _do4 + effect(3);
  return y;
}
```

### Todos

Since these are rather edge cases, I am not going to implement them if not required.

- `const { [do { return; }]: do { return; } } = x` will use the old IIFE approach, because I can't think of a way to do it correctly except to downgrade the whole object restructuring pattern.
- Complex assignment like `a ||= do { ... }` is not supported yet. Instead, an explicit error is thrown.

### CODE REVIEW

**Review by Fyyto — APPROVED** [review]

File: packages/babel-plugin-proposal-do-expressions/src/index.ts [hunk 1]
```diff
@@ -1,4 +1,6 @@
 import { declare } from "@babel/helper-plugin-utils";
+import traverse, { type NodePath } from "@babel/traverse";
+import * as t from "@babel/types";
```
Comment (JLHwung) [inline packages/babel-plugin-proposal-do-expressions/src/index.ts:3]: To reduce dependencies duplication, we generally access traverse and types from the `api` object injected by `@babel/core`: `const { types: t, traverse } = api`.

File: packages/babel-plugin-proposal-do-expressions/src/index.ts [hunk 2]
```diff
@@ -10,19 +12,239 @@ export default declare(api => {
...
+        expressions.pop();
+      } else {
+        break;
+      }
+    }
+    expressions.forEach(path => pushEffect(path));
+  }
+}
+
+function captureDoExpressionResult(
```
Comment (JLHwung) [inline packages/babel-plugin-proposal-do-expressions/src/index.ts:146]: It seems to me this utility shares a similar purpose with the `NodePath#getCompletionRecords`, can we apply the capture transform to the return result of `NodePath#getCompletionRecords`?

File: packages/babel-plugin-proposal-do-expressions/test/fixtures/do-expression-switch-case/condition-before-expression/output.js [hunk 3]
```diff
@@ -1,8 +1,13 @@
...
-      if (true) {
-        return 'out';
-      }
+const x = n => {
+  {
+    var _do;
+    switch (n) {
+      case 0:
+        if (true) {
+          'out';
```
Comment (JLHwung) [inline packages/babel-plugin-proposal-do-expressions/test/fixtures/do-expression-switch-case/condition-before-expression/output.js:7]: The completion record `'out'` should have been captured.

File: packages/babel-plugin-proposal-do-expressions/src/index.ts [hunk 4]
```diff
@@ -10,19 +12,239 @@ export default declare(api => {
...
+    t.isBinaryExpression(node) ||
+    t.isLogicalExpression(node) ||
+    t.isConditionalExpression(node) ||
+    t.isObjectExpression(node) ||
+    t.isArrayExpression(node) ||
+    t.isClassExpression(node) ||
+    t.isFunctionExpression(node) ||
+    t.isArrowFunctionExpression(node) ||
+    t.isParenthesizedExpression(node) ||
+    t.isRecordExpression(node) ||
```
Comment (JLHwung) [inline packages/babel-plugin-proposal-do-expressions/src/index.ts:245]: `TupleExpression` should be included as well.

File: packages/babel-plugin-proposal-do-expressions/test/fixtures/do-expression-with-early-exit/call-expression/input.js [hunk 5]
```diff
@@ -0,0 +1,9 @@
+function main() {
```
Comment (JLHwung) [inline packages/babel-plugin-proposal-do-expressions/test/fixtures/do-expression-with-early-exit/call-expression/input.js:1]: Can you add some execution tests for the `do-expression-with-early-exit` suite? For an example, you can search `exec.js` within the plugin test suites.

**Review by JLHwung — COMMENTED** [review]
Thank you for PR. This is a complete rewrite of the do transform. It would be great if you can provide an abstract in the PR description so that it would be easier for reviewers to jump in.

File: packages/babel-plugin-proposal-do-expressions/src/index.ts [hunk 6]
```diff
@@ -10,19 +12,194 @@ export default declare(api => {
...
+        throw new Error("DoExpression must be in a statement");
+      }
+      if (Array.isArray(path.container) && path.isStatement()) {
+        // Flatten the closest parent statement
+        flattenStatement(path);
+        break;
+      }
+      if (path.isArrowFunctionExpression()) {
+        const body = path.get("body");
+        body.assertExpression();
```
Comment (JLHwung) [inline packages/babel-plugin-proposal-do-expressions/src/index.ts:37]: A do expression could be a parameter initializer or a computed key, 
```js
({ [do {'key'}]: x } = do { value }) => {}
```
in either case this assertion may fail.

File: packages/babel-plugin-proposal-do-expressions/src/index.ts [hunk 7]
```diff
@@ -10,19 +12,194 @@ export default declare(api => {
...
+    ) {
+      const { node } = path;
+      if (node.type === "DoExpression") {
+        effects.push(node.body);
+        if (needResult) {
+          const completions = path
+            .get("body")
+            .getCompletionRecords(/* shouldPreserveBreak */ true)
+            .filter(completion => completion.isExpressionStatement());
+          if (completions.length === 0) {
```
Comment (JLHwung) [inline packages/babel-plugin-proposal-do-expressions/src/index.ts:107]: This check should be applied before the previous expression statement filter, otherwise `do { return 42 }` will be replaced by an `undefined` node.

Comment (kermanx) [reply packages/babel-plugin-proposal-do-expressions/src/index.ts:125]: I add a test

```js
function main() {
  return do { return 42 }
}

expect(main()).toBe(42);
```

And it is passing.

**Review by JLHwung — APPROVED** [review]
This PR now looks good to me, thank you for working on this topic. If you would like to contribute more, it would be great to port the do expressions overwrite to the async-do-expressions plugin.

**Comment by nicolo-ribaudo** [comment]
> Since these are rather edge cases, I am not going to implement them if not required.

I have not read the code yet so it's possible you are already doing this, but if we are not going to implement these we should make sure to throw an explicit error saying "This is not supported by Babel"

**Comment by kermanx** [comment]
I updated the code to support do-expression within all kinds of loops and parameters. And it now uses `Reflect.apply` to call functions when necessary to preserve both the side-effect order and `this` value. AFAIK the only problem left is object destructure pattern, as said in the updated PR description.

**Review by nicolo-ribaudo — COMMENTED** [review]
Thanks for the PR! This is incredible. And sorry it took so long to review it.

I haven't reviewed the tests yet, but I have some comments about the implementation.

File: packages/babel-plugin-proposal-do-expressions/test/fixtures/do-expression-switch-case/condition-before-break/output.js [hunk 8]
```diff
@@ -1,8 +1,11 @@
-const x = n => function () {
-  switch (n) {
-    case 0:
-      if (true) {
-        return void 0;
-      }
+const x = n => {
+  {
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-proposal-do-expressions/test/fixtures/do-expression-switch-case/condition-before-break/output.js:2]: Do you think it would be difficult to avoid this extra unnecessary block? Maybe by just using a list of statements rather than a block containing a list of statements.

File: packages/babel-plugin-proposal-do-expressions/src/index.ts [hunk 9]
```diff
@@ -10,19 +12,621 @@ export default declare(api => {
...
+          [
+            path.node.callee as t.Expression,
+            thisArgument.isSuper()
+              ? t.thisExpression()
+              : t.cloneNode(thisArgument.node),
+            t.arrayExpression(
+              path.node.arguments as Array<t.Expression | t.SpreadElement>,
+            ),
+          ],
+        ),
```
[the remark this answers is not in the document]
Comment (kermanx) [reply packages/babel-plugin-proposal-do-expressions/src/index.ts:438]: One problem is that `.call` can be overwrite:

https://www.typescriptlang.org/play/?#code/PTAEAEBcGcFoDsD2BjAFgU2QawLACh8AzAV3mUgEtF5RCAKAQwEpQBvfUT0Za6RAG3QA6fogDmdAIxN8AX3xEhyBv36gAvKDot1APjYcuPeH0EjxdAEwy88gnnosuzl664hQk-ACV0hQeRCDAAOwfwAnnSEADRssrEA2gC6LB5eDkoq-NpuuZwelvhAA

File: packages/babel-plugin-proposal-do-expressions/src/index.ts [hunk 10]
```diff
@@ -10,19 +12,621 @@ export default declare(api => {
...
+
+function isTopLevelSimple(path: NodePath<t.Node>): boolean {
+  return (
+    path.isPureish() ||
+    path.isBinaryExpression() ||
+    path.isParenthesizedExpression() ||
+    path.isSequenceExpression() ||
+    (path.isUnaryExpression() &&
+      path.node.operator !== "throw" &&
+      path.node.operator !== "delete")
```
[the remark this answers is not in the document]
Comment (kermanx) [reply packages/babel-plugin-proposal-do-expressions/src/index.ts:620]: In fact in this function I want to filter out nodes that it's top level is **copiable and pure**, in order to save a temp variable. I should rename the function.

File: packages/babel-plugin-proposal-do-expressions/src/index.ts [hunk 11]
```diff
@@ -10,19 +12,621 @@ export default declare(api => {
...
+          const [newPath] = path.replaceWith(
+            t.blockStatement([initNode, path.node]),
+          );
+          flattenStatement(newPath.get("body")[0]);
+        }
+        break;
+      }
+      case "ForInStatement":
+      case "ForOfStatement": {
+        // Example:       for (const i in do { f1(); }) { ... }
```
[the remark this answers is not in the document]
Comment (kermanx) [reply packages/babel-plugin-proposal-do-expressions/src/index.ts:160]: It seems that `for-of`

```js
for (var x = 1 of [undefined]) console.log(x)
```

is syntax error, and `for-in`

```js
for (var x = 1 in x) console.log(x)
```

is ok but `= 1` can never be executed, thus the current behavior should be right afaik.

[the remark this answers is not in the document]
Comment (nicolo-ribaudo) [reply packages/babel-plugin-proposal-do-expressions/src/index.ts:160]:
```js
for (var x = 1 in {});
console.log(x);
```
logs `1` :)

File: packages/babel-plugin-proposal-do-expressions/src/index.ts (hunk 9 above)
[the remark this answers is not in the document]
Comment (nicolo-ribaudo) [reply packages/babel-plugin-proposal-do-expressions/src/index.ts:438]: `Reflect.apply` can be overwritten too. Most other Babel transform assume that `.call` is the original `.call`, and a lot of other things would break when users overwrite it.

File: packages/babel-plugin-proposal-do-expressions/test/fixtures/do-expression-switch-case/condition-before-break/output.js (hunk 8 above)
Comment (kermanx) [reply packages/babel-plugin-proposal-do-expressions/test/fixtures/do-expression-switch-case/condition-before-break/output.js:2]: But the problem is that I can't find a simple way to detect if some new variables are declared in the scope of do-expression 🥹

Comment (nicolo-ribaudo) [reply packages/babel-plugin-proposal-do-expressions/test/fixtures/do-expression-switch-case/condition-before-break/output.js:2]: Let's keep this as is then :)

It can be improved in the future.
