### PR TITLE
register import equals specifier

### LINKED ISSUE #10042: Export is not defined error for TSImportEqualsDeclaration
## Bug Report

**Current Behavior**
syntax error 

**Input Code**
```js
import foo = require('f');
export { foo } // Export 'foo' is not defined
```

**Expected behavior/code**
no error

**Babel Configuration (.babelrc, package.json, cli command)**
typescript plugin

**Environment**
- Babel version(s): 7.4.5
- Node/npm version: Node 11.13 / npm 6.7

**Possible Solution**
In tsParseImportEqualsDeclaration()
call checkLVal() or scope.declareName()

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #10042 
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

In this PR we register the import equals specifier so that it would not throw if it appears in an export named declaration later.

Note that we does not support transforming ImportEqualsDeclaration yet, but we should be able to parse it.

Credits to @jj-choi

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
> Credits to @jj-choi

Note that you can mark them as "co-author" of the commit

**Comment by JLHwung** [comment]
Rebased `upstream/master` onto e1839e5ec9c10ffadac51aa58fbc1e6753c6b27f so that the CI build would not be affected by eslint packages. 😂

File: packages/babel-parser/src/plugins/typescript/index.js [hunk 1]
```diff
@@ -1292,6 +1293,12 @@ export default (superClass: Class<Parser>): Class<Parser> =>
     ): N.TsImportEqualsDeclaration {
       node.isExport = isExport || false;
       node.id = this.parseIdentifier();
+      this.checkLVal(
+        node.id,
+        BIND_LEXICAL,
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/src/plugins/typescript/index.js]: I'm not sure about which kind of binding this should be: https://www.typescriptlang.org/play/?esModuleInterop=false&target=99&module=1&ssl=3&ssc=17&pln=4&pc=17#code/JYWwDg9gTgLgBAQzgXjlApgRwK7AwCgCIFCBKAbgChKYBPMdRFOAO2xACN0oqAbdeAgBcrdlyjMATFUroAHpFhwA3kwC+5IA

Comment (JLHwung) [reply packages/babel-parser/src/plugins/typescript/index.js]: The binding type should be as same as import default specifier: https://www.typescriptlang.org/play/?esModuleInterop=false&target=99&module=1&ssl=1&ssc=1&pln=3&pc=1#code/JYWwDg9gTgLgBAQzgXjlApgRwK7AwCgCIYBPMdAZwGMpgwZCBKAbgChXTzEU4A7bEACN0UNgBt08BAC4+A4VB4AmNq3QAPSLDgBvbgF9mQA

The declaration conflict error is shadowed by the module-not-found.
