### PR TITLE
Type-safe ParseErrors

### LINKED ISSUE #14317: [Bug]: Sufficiently complex LValues allow `let` to incorrectly be used as an identifier name.
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```javascript
require("@babel/parser").parse("let [let = 5] = []")
```

RunKit link: https://runkit.com/tolmasky/let-allowed-in-lvalue

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

Current behavior: No error
Expected behavior: Should get "'let' is not allowed to be used as a name in 'let' or 'const' declarations."

If you remove the initializer you'll see you correctly get this error.

### Environment

- Babel version: 7.17.3

### Possible solution

This is fixed in https://github.com/babel/babel/pull/14320

### Additional context

_No response_

### LINKED ISSUE #14318: [Bug]: keywords allowed for identifiers in Typescript
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```javascript
require("@babel/parser").parse("function if({ const, while, with, let }){}",
{
    sourceType: "module",
    plugins: ["typescript"]
})
```

RunKit link: https://runkit.com/tolmasky/keywords-as-identifiers-in-typescript

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

Current behavior: no error
Expected behavior: Should throw an error.

### Environment

- Babel 7.17.3

### Possible solution

This is fixed in https://github.com/babel/babel/pull/14320

### Additional context

_No response_

### LINKED ISSUE #14319: [Bug]: Import specifiers allow keywords in Typescript
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```javascript
require("@babel/parser").parse(`import { const as const } from "blah"`,
{
    sourceType: "module",
    plugins:["typescript"]
})
```

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

Current behavior: No error.
Expected behavior: Should throw an error.

https://runkit.com/tolmasky/keywords-in-import-specifiers-in-typescript

### Environment

- Babel 7.17.3

### Possible solution

This is fixed in https://github.com/babel/babel/pull/14320

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tolmasky**
The main point of this PR is to deliver on the original promise made in [PR #14130](https://github.com/babel/babel/pull/14130) where the re-arrangement of the `raise` parameters would allow us to eventually provide a more descriptive and type-safe way of raising errors. However, during the execution of this change, a number of other bugs popped up (most notably https://github.com/babel/babel/issues/14317, https://github.com/babel/babel/issues/14318, and https://github.com/babel/babel/issues/14319), which were also tackled here. The summaries below describe each of these "conceptually separate" (but code-connected) changes.

| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #14317, Fixes #14318, Fixes #14319
| Patch: Bug Fix?          | I think so
| Major: Breaking Change?  | No
| Minor: New Feature?      | Probably not
| Tests Added + Pass?      | Yes
| Any Dependency Changes?  | NO
| License                  | MIT

## Type-safe `Parser.raise`

As mentioned above, `raise` is now "Error class" aware and type-checks any additional parameters passed to it for forming the resulting error message. So, for example, instead of doing this: 

```javascript
this.raise(
  Errors.ModuleExportNameHasLoneSurrogate,
  { node: result },
  surrogate[0].charCodeAt(0).toString(16),
);
```

You now do this:

```javascript
this.raise(Errors.ModuleExportNameHasLoneSurrogate, {
  at: result,
  surrogateCharCode: surrogate[0].charCodeAt(0),
});
```

I think this makes these errors more understandtable at the point of `raise`-ing them, since they can get somewhat confusing when they start to have multiple parameters. Additionally, without type-checking and good names, they can quickly become out of sync with their definitions. For example, prior to this change we passed an unused argument when raising `Errors.ModuleAttributeDifferentFromType`:

```javascript
this.raise(
  Errors.ModuleAttributeDifferentFromType,
  { node: node.key },
  node.key.name,
);
```

This is now a type error. Additionally, passing the wrong type for each parameter is also a type error. For example, if you accidentally pass a `Node` to something expecting a `string`, you'll see something like this:

Screen Shot 2022-03-01 at 12 32 54 PM

### Defining ParseErrors

The way you define these type-safe errors is fairly straight-forward too (although even more straight-forward in Typescript, where I originally prototyped this...). Similar to before, you create an object where the key represents the `ReasonCode`, only you pass in a `toMessage` function if the message is dynamic instead of the hand-rolled templates we were using before:

```javascript
const Errors = toParseErrorClasses(_ => {
    StaticError: _("An error message."),
    DynamicError: _<{| name: string |}>(({ name }) => `A dynamic error message that takes a ${name}`),
});
```

The `_` wrapper is an unfortunate workaround for a [Flow bug](https://github.com/facebook/flow/issues/8838) that will be fixed after their big year-long rewrite. Hopefully though by then we will have just ported the parser to Typescript and then it will just look like this (the Typescript implementation exists on a separate branch so it will be easy to swap in):

```javascript
const Errors = ParseErrorEnum({
    StaticError: "An error message.",
    DynamicError: ({ name } : { name: string }) => `A dynamic error message that takes a ${name}`,
});
```

The API allows you to do a couple of other things, like easily pass in a SyntaxPlugin:

```javascript
const TSErrors = ParseErrorEnum`typescript` ({
    SomeError: "Blah.",
    // ...
});
```

As well as conditionally override the `ReasonCode` and `ErrorCode` on a per Error basis:

```javascript
const Errors = toParseErrorClasses({
  // ... 

  // This uses `SourceTypeModuleError` instead of `SyntaxError`
  ImportOutsideModule: _(
    `'import' and 'export' may appear only with 'sourceType: "module"'`,
    { code: ParseErrorCodes.SourceTypeModuleError },
  ),

  // ...
  
  // This uses a different reasonCode in Babel 8.
  PatternIsOptional: _(
    "A binding pattern parameter cannot be optional in an implementation signature.",
    // For consistency in TypeScript and Flow error codes
    !process.env.BABEL_8_BREAKING
      ? { reasonCode: "OptionalBindingPattern" }
      : {},
  ),
});
```
 
### Live errors

A natural consequence of the implementation is that these errors are also *live*. That is to say, if you now mutate the error after the fact:

```javascript
theParseError.loc.line += 1;
theParseError.surrogateCharCode = 22;
```

The error message will now also reflect the new information. This is important for us at RunKit (it allows us to update error messages when previous cells change without having to re-parse or do string manipulation), but also gives me the necessary tools to significantly expand our fuzz testing. Since errors now contain semantically meaningful information, that can be both interpreted and modified, it is possible to combine this with placeholders to create a ton of variety from existing tests. For example, something like `let %%name%% = 10; let %%name%% = 20`, can both be trivially mutated, but also have the resulting error trivially mutated as well (`duplicateIdentifierError.name = random_name`), allowing us to quickly generate the expected errors without needing a ton of fixture, the same way we do with line number fuzzing currently. Another simple place to start could be to make most identifiers in our error fixtures be placeholders, and then insert reserved words into all our existing tests expecting them to be UnexpectedReservedWord/Keyword errors.

`ParseErrors` now also have a `clone` method to copy errors with changes so that you don't have to necessarily mutate the original error:

```javascript
newError = oldError.clone({ loc: new Position(1, 3), details: { name: "test" } });
```

Any property left out of `clone`'s argument will just be taken from the original (this is recursively true for the `details` property).

### No more need for dry-error-messages eslint rule, and no more ignoring the dry-error-messages eslint rule

A natural result of this is that we no longer need the custom dry-error-messages linter rule, this is now enforced by the type system, and furthermore there are no remaining instances where this rule is ignored. All errors are now properly declared through the `toParseErrorClasses` and all instances of "inline" calls of on-the-fly `ErrorTemplate`s have been removed.

### `report-error-message-format`

As mentioned above, we now get the `dry-error-message` behavior for free through the type system, and it is fully enforced on all errors now. As such, this linter rule was removed. This however leaves `report-error-message-format` rule, which after this PR won't do anything since it still only operates on calls to `makeErrorTemplates`, which no longer exists. I have purposefully not updated this for a two of reasons:

1. Our error messages now make use of template strings, so it would be non-trivial to execute this rule statically.

2. Even prior to this change, many error messages evaded this plugin (most notably, "Unexpected token") since they were being passed inline. As such, had I updated this rule to work with the new error system,  it would have lead to either needing to disable it for a number of error messages, or caused a lot of test churn as I updated a bunch of tests to include periods at the end. I wanted to keep the test updates in this PR focused on the meaningful behavior changes and not drown them all out in a sea of updated tests.

I think the best course of action is to change this in a subsequent commit to be a rule that is checked at *test time*, that way we are not relying on being able to discern what the final message would be after the template string is fully resolved. In the test runner I can easily loop through all the messages in the error array and throw an error if they don't match our desired format.

### Further ParseError Notes

1. Despite generating their messages dynamically based on their properties, `ParseError`s still respect setting their `message` property directly. (e.g. doing `error.message = "custom message";`).
2. `ParseError`s still show up as `SyntaxError`s in stack traces, logs, etc. (AKA, the `constructor`'s name is `SyntaxError`, despite each error type now being a custom subclass). This makes the errors behave externally like they used to in most meaningful ways (for example, we didn't have to regenerate any tests because of the changed Error class hierarchy).
3. I removed the `ErrorParser` intermediate class and just put `raise` and `raiseOverwrite` directly in `Tokenizer`, since `Tokenizer` directly makes use of these functions and has all the necessary data to implement them. It for example already implements `recordStrictModeErrors` itself, so not sure why a more fundamental method like `raise` is punted to a later subclass. Additionally, since these are the only two remaining methods from `ErrorParser` (everything else from that file was either no longer necessary, like `raiseWithData`, or has a home is the actual `ParseError` class), it doesn't really add much to the class.
4. I moved `unexpected`, `expectPlugin`, and `expectOnePlugin` from `UtilParser` to `Tokenizer` for the same reason: `Tokenizer` has all the necessary data to implement these functions (it's not "waiting" for something introduced in a later subclass to be able to implement it), and *uses* `unexpected()` and `expectPlugin` directly already.
5. In the typescript implementation, the `reasonCode` is also part of the parameterized type `ParseError<ReasonCode, Properties>`. This can be really nice and useful for compiler error messages, but not trivially possible with flow.
6. It's not clear why we have both `InvalidOrUnexpectedToken` and `UnexpectedToken`, although the former produces a slightly different message "unexpected character". Seems like we should consider renaming `InvalidOrUnexpectedToken` to `UnexpectedCharacter`, or removing it and just using `UnexpectedToken` instead.
7. I've added `pipelineOperator` to the `SyntaxPlugin` enum, and thus as a plugin that can show up in a `ParseError`'s `syntaxPlugin` field. This was mainly since it was nice to be able to separate these errors out into their own file, but this doesn't mean that they *have to* also have the syntaxPlugin field set. If we prefer, I can keep easily keep the organizational aspect of this while still not exposing this property.

## checkLVal bug

As mentioned above, in the process of updating the various calls to `raise`, I ran into a few bugs. One of them came up when trying to make `InvalidLHS` and `InvalidLhsBinding` use our new type-safe system, since it was being passed a seemingly arbitrary raw "context description" string. Such context strings happens in other places of the code as well, namely `parseImportSpecifierLocal` and `parseHackPipeBody`. I've done my best to coalesce these various "node description" strings to instead be a "UI concern" *of errors* in `parse-error/to-node-description.js`, instead of a *code concern* for various functions that internally end up calling `checkLVal` and thus need to provide context strings. What this means is that instead of having to have various methods (like `checkLVal`, `parseImportSpecifierLocal`, `parseHackPipeBody`, etc.) keep track of, and pass around, description strings, the error instead receives the relevant node type (a piece of information we already have in most cases), and then the "human friendly" description is generated by the error when creating the message itself. This makes it easier to keep a consistent terminology throughout all errors that want to do this sort of thing, and simplifies the code by removing an extra "noisy" parameter (that was often not even used -- for example, while `checkLVal` only ever produces an error message that references assignments, parentheses, or destructuring, it still forced every caller to come up with an english name for the parent node in question).

This reorganization surfaced a real bug: the fact that we currently don't always identify invalid uses of `let` variable names. Versions of this bug affected not just the base implementation but actually further plugins as well (you'd fix it for just JavaScript and have other related bugs still in Typescript for example), and it all came down to the fact that `checkLVal` both has *a lot* of parameters, as well as complicated recursive behavior. Just considering the JavaScript parser momentarily, fixing the bug there was somewhat straight forward in that it was the result of recursive calls accidentally not forwarding all the arguments they were passed, and thus those parameters would get reset to their default values (in other words `disallowLetBindings` would eventually be dropped if the recursion path took the right turns and was deep enough).

However, this was then further complicated in the Typescript implementation, since it inadvertantly *changed the meaning* of the `checkLVal`'s parameters. The original source of this bug is that the Typescript parser didn't properly copy over all the default initializations for the various parameters in its `checkLVal` overridden definition. This means that binding would by defualt be `undefined` instead of `BIND_NONE`. To compensate, Typescript.checkLVal would thus treat `binding = falsey` as "none", and thus *not* treat `BIND_NONE` as "none". Interestingly, this *sometimes* lead to a "two wrongs make a right" situation because *existing* calls to *just* `checkLVal(blah)` would all of a sudden act as if they were passing `undefined` for binding, which Typescript would respect, and so things would occasionally "seem" fine. However, things would break down during cross-inheritance recursive calls where the two "belief systems" would come in conflict as to whether "none" should be represented by `undefined` or `BIND_NONE`. This has its own interesting behavior, that I won't go into much more detail about, except to say that the resulting behavior was that `binding` actually ended up becoming almost an inadvertent "state variable" that was gating recursive calls.

Anyways, to try to make this all significantly simpler, I made the following change. `checkLVal` now *only* exists in the LVal parser (lval.js). Instead of overriding *this* method, subclassers override a separate `isValidLVal` method, which is way simpler, and decouples the question of whether *this particular node is an LVal or needs to be traversed* from the actual traversal and other various book-keeping state that makes up the 5 arguments that get passed around in `checkLVal`. The goal was to remove *subclassing recursion and re-entrancy* which in my experience leads to incredibly difficult situations to reason about like this. Instead, `isValidLVal` is only "linearly recursive". That is to say, subclass implementations only every "call up" and never wind up back inside of themselves. You handle the special nodes you define, and otherwise hand off the task to the superclass, and are never in charge of any *traversals* yourself. For example, in `placeholders.js`:

```javascript
isValidLVal(type: string, ...rest) {
  return type === "Placeholder" || super.isValidLVal(type, ...rest);
}
```

Anyways, this fixes https://github.com/babel/babel/issues/14317.

## TypeScript Changes

In the process of investigating the original let bug, and in updating the errors in Typescript generally, I encountered further keyword and reserved word bugs. Additionally, I discovered that our external tests weren't as robust as they could be, and thus made it hard to match the new results. Below is a brief explanation of each change at the high level:

### Typescript tests

The tests we pull from Typescript proper aren't in a format that we were consuming properly from what I could tell. To list a few issues:

1. We were parsing all the tests with `sourceType: "module"`, despite many tests explicitly testing non-strict mode situations. I now use "unambiguous" and look for the "@alwaysStrict" to hopefully parse each test in the proper mode.
2. There were several tests that weren't utf-8 but were being read from the filesystem in utf-8. I now check the encoding of the file so as to read it correctly (I believe I leave out one of the two utf16's that node doesn't support out of the box, but I think this only leads to excluding one test?)
3. Many of the typescript tests, despite being just one file, actually represent a set of files (using the "twoslasher" format, or some variation thereof). I've copied and modified the `twoslasher` stuff to try to get as close as possible to something we can make sense of in our tests, splitting out the individual files and throwing out any file formats that don't make sense for our tests, like JSOn and markdown for example. This does a better job of consuming most tests, at the expense of a small number of tests (3 or so I think?) that were relying on everything being inlined together to (accidentally I think?) simulate the behavior of having imported those files (or at least sharing common namespace).
4. This works together with our new ".d.ts" detection (described below) to allow us appropriately test `.d.ts` files vs. `.ts` files
5. The bug fixes described below now agree with more of the errors Typescript itself throws, so we were able to add more error codes to the `scripts/parser-tests/typescript/error-codes.js `.

The end result is that the `scripts/parser-tests/typescript/allowlist.txt` is now dramatically shorter (301 fewer "exceptions"). However, I do feel it's important to state that the external typescript testing process is fairly tenuous, as success has always been measured simply by whether both the original test and our test both agree on whether `an` error is generated, any error, even different errors. I certainly ran into this myself, where for example previously completely unrelated errors were thrown (including the file being the wrong encoding I think) and thus our behavior was deemed "correct" simply because we "expected" an error in this file. I know that this is tricky no matter what, since we're only really capable of syntax errors, and the typescript error suite covers semantic errors *and* tests *sets of files* instead of just *single files*, but I think there might be more we could do here. For example, I think a potential avenue of exploration is trying to include the TSErrorCodes in our own errors, so as to try to do a better job at identifying whether our errors match with theirs. In that setting, we could have "partial successes", where we throw a *subset* of the errors what are expected from a given test, and we can better track how we stack up against typescript proper.

### .d.ts handling

Just to get one of the easier changes out of the way first, I've made it so that if the `DTS` plugin option is not explicitly set to `false`, and the `sourceFilename` option provided ends with a `.d.ts` file extension, we automatically assume the entire file is in an ambient context (in other words, that `DTS` had been set to `true`). I think this is a very safe change (since as we'll see below we were kind of always inadvertently getting DTS behavior previously), and also I think this realistically matches the expected behavior. As mentioned above, this was instrumental in getting a lot of tests to pass since we were now trivially using the current ambient context mode when parsing.

### Reserved words are once again meaningful in Typescript

OK, now we'll get into the meat of the Typescript changes, which are ultimately related to the `checkLVal` changes above. As I was figuring out why the `let` stuff continued to be broken in Typescript after implementing the fix in the main JavaScript parser, I discovered that it was arising for a variety of *other* reasons in the Typescript parser as well. I'm not sure if it was always this way, or simply changed at some later point, but all reserved word collision-checking is disabled in typescript prior to this PR, by giving `checkReservedWord` an empty implementation. The reason I don't think that this was always the intention (or perhaps remains not currently the intention), is because there is plenty of code in the rest of the Typescript parser that *does* try deal with keywords and reserved words. However, for the most part, this code has no effect due to the `checkReservedWord` situation. For example, the import specifier code explicitly goes out of its way to keep track of whether keyword identifiers are allowed or not. For example, `parseTypeOnlyImportExportSpecifier`'s has fairly complicated code to track whether to allow keywords in import specifiers during the "as as as" parsing. However, this code actually *doesn't* work in 2 out of 3 cases (you're supposed to call `parseModuleExportName` instead of `parseIdentifier`), but this is never noticed since keywords are just turned off everywhere.

The source of the decision to disable `checkReservedWord` seems to be that reserved words *are* allowed in surprising places when parsing typescript *declarations* (in other words, in ambient contexts). This is called out in the `checkReservedWord` empty implementation. However, this means that currently `function if({ const, while, with, let }){}` is totally valid typescript.  The fix is to simply disable `checkReservedWord` only when in ambient contexts. However, we also aren't always currently setting the ambient context correctly...

### Appropriately determine when to establish an ambient context

So the next part of this fix was to also catch all the remaining edge cases where we should be in an ambient context. Previously, we weren't setting the ambient context state when in a `declare` declaration. For example, in `declare class ...` will now have `inAmbientContext` set to `true`. As mentioned earlier, we now set ambient contexts depending on the filename as well, so this catches those cases.

### const declarations in ambient contexts

One final important change with ambient contexts is that you are now only allowed to leave off the initializer on const declarations in ambient contexts. So `const x: number;` is normal code (just like with typescript proper). Similarly, `const x:number = 10` is *not* allowed in ambient contexts. However, just like with typescript proper, type-less literal consts initializers *are* allowed in ambient contexts (e.g. `const x = 1` or `const x = "hi"`). This fixed a bunch of third party tests, and made it so I had to add `declare` in front of a few consts in our tests. I had the beginnings of the same fix for functions, but those are harder since implementation-less functions are "kind of" allowed if they are overloads. This can be somewhat trivially implemented in the same way it's done in the Typescript parser, but is complicated by the fact that we have to keep track of ESTree style methods as well as normal Babel methods, etc. For this reason, you can still just outright leave out implementations from functions anywhere in the code, matching Babel's current behavior.

### Interfaces and enums are parsed as statements

The other reason (I think) for the lack of reserved word checking in Typescript is to allow `interface` and `enum` to escape error detection and then be hijacked during expression parsing to implement these features. These two are now simply handled in `parseStatementContent`, the same way `class` is in normal JavaScript, and thus avoids this problem entirely. It is just the context-sensitive Typescript keywords (like `module` and `abstract`) that need to be handled in the expression code, much like `let` in normal JavaScript.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14320"></a>

### CODE REVIEW

File: packages/babel-parser/src/parse-error.js [hunk 1]
```diff
@@ -0,0 +1,211 @@
...
+  get pos() {
+    return this.loc.index;
+  }
+}
+
+function toParseErrorClass<ErrorDetails>(
+  toMessage: ToMessage<ErrorDetails>,
+  credentials: ParseErrorCredentials,
+): Class<ParseError<ErrorDetails>> {
+  return class extends ParseError<ErrorDetails> {
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/src/parse-error.js:98]: If I'm reading this file correctly, the new approach creates a new class for every possible error. Would it be possible to use a single class instead (`ParseError`), and pass the error code or the `toMessage` function as a constructor argument?

File: packages/babel-parser/src/parse-error.js [hunk 2]
```diff
@@ -0,0 +1,211 @@
...
+    #message: typeof StandardMessage | string = StandardMessage;
+
+    constructor(...args): ParseError<ErrorDetails> {
+      super(...args);
+      // $FlowIgnore - Only necessary because we can't make syntaxPlugin optional.
+      ObjectAssign(this, credentials);
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/src/parse-error.js:104]: I don't understand what's happening here. Regardless of what the flow type say, `toParseErrorCredentials` returns a two-elements array. Are we assigning `this[0]` and `this[1]`? Why do we use indexes rather than property names? Are then these properties read somewhere?

File: packages/babel-parser/src/parse-error.js [hunk 3]
```diff
@@ -0,0 +1,211 @@
...
+  type ParseErrorCredentials,
+} from "./parse-error/credentials";
+
+const ArrayIsArray = Array.isArray;
+const {
+  assign: ObjectAssign,
+  defineProperty: ObjectDefineProperty,
+  getPrototypeOf: ObjectGetPrototypeOf,
+  keys: ObjectKeys,
+} = Object;
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/src/parse-error.js:17]: Nit: we usually don't protect our code against built-ins modifications (I think runkit even relied on it to implement parser plugins, right?).

File: packages/babel-parser/src/parse-error.js [hunk 4]
```diff
@@ -0,0 +1,211 @@
...
+// eslint-disable-next-line no-redeclare
+export function toParseErrorClasses(argument, syntaxPlugin) {
+  if (ArrayIsArray(argument)) {
+    return toClasses => toParseErrorClasses(toClasses, argument[0]);
+  }
+
+  const classes = argument(toParseErrorCredentials);
+
+  for (const reasonCode of ObjectKeys(classes)) {
+    const [toMessage, credentials = {}] = classes[reasonCode];
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/src/parse-error.js:172]: If we need both the key and the value, we can directly iterate over `Object.entries(classes)`.

File: packages/babel-parser/src/parse-error.js [hunk 5]
```diff
@@ -0,0 +1,211 @@
...
+      reasonCode: credentials.reasonCode || reasonCode,
+      ...(syntaxPlugin ? { syntaxPlugin } : {}),
+    });
+
+    classes[reasonCode] = ParseErrorClass;
+
+    // We do this for backwards compatibility so that all errors just have the
+    // "SyntaxError" name in their messages instead of leaking the private
+    // subclass name.
+    ObjectDefineProperty(ParseErrorClass.prototype.constructor, "name", {
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/src/parse-error.js:184]: Nit: This should go in `toParseErrorClass`, since it's about every specific class and not about the collection of classes.

File: packages/babel-parser/src/parse-error/module-errors.js [hunk 6]
```diff
@@ -0,0 +1,14 @@
+// @flow
+
+import { ParseErrorCodes, toParseErrorCredentials } from "../parse-error";
+
+export default (_: typeof toParseErrorCredentials) => ({
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/src/parse-error/module-errors.js:5]: Nit: to reduce the boilerplate, we could export `type _ = typeof toParseErrorCredentials` from `parse-error.js`, and just to
```js
export default (_: _) => ({
```

File: packages/babel-parser/src/parse-error/to-node-description.js [hunk 7]
```diff
@@ -0,0 +1,34 @@
...
+  RestElement: "rest element",
+  UpdateExpression: {
+    true: "prefix operation",
+    false: "postfix operation",
+  },
+  VariableDeclarator: "variable declaration",
+  YieldExpression: "yield expression",
+};
+
+type NodeTypesWithDescriptions = $Keys<typeof NodeDescriptions>;
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/src/parse-error/to-node-description.js:23]:
```suggestion
type NodeTypesWithDescriptions = $Keys<$Diff<typeof NodeDescriptions, { UpdateExpression: any }>>;
```

so that it does not include `UpdateExpression` and thus `{ type: "UpdateExpression" }` is not assignable to `NodeWithDescription` (because it must now have `prefix: boolean`).

File: packages/babel-parser/src/parser/expression.js [hunk 8]
```diff
@@ -653,8 +651,10 @@ export default class ExpressionParser extends LValParser {
     refExpressionErrors: ?ExpressionErrors,
   ): N.Expression {
     if (update) {
-      this.checkLVal(node.argument, "prefix operation");
-      return this.finishNode(node, "UpdateExpression");
+      this.checkLVal(node.argument, {
+        in: (node = this.finishNode(node, "UpdateExpression")),
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/src/parser/expression.js:655]:
```suggestion
        in: this.finishNode(node, "UpdateExpression"),
```
it already mutates `node`.

**Review by nicolo-ribaudo — COMMENTED** [review]
Wow this is a long PR description!

I only reviewed the first files so far.

File: packages/babel-parser/src/parse-error.js [hunk 9]
```diff
@@ -0,0 +1,211 @@
...
+    if (details.missingPlugin) {
+      ObjectDefineProperty(this, "missingPlugin", {
+        get() {
+          return this.details.missingPlugin;
+        },
+        enumerable: true,
+      });
+    }
+
+    return this;
```
[the remark this answers is not in the document]
Comment (tolmasky) [reply packages/babel-parser/src/parse-error.js:73]: I agree, but Flow gives me an error without it! There's a weird bug in Flow where if you give the constructor a return type, it reveals that it doesn't have "special constructor" knowledge and says the return type conflicts with "implicitly returned undefined" from the constructor. I believe if I *remove* the ParseError<ErrorDetails> return type from the constructor, then it stops complaining about lacking a `return this`, but some other part of the code starts complaining. I'll try poking around at it some more, but this is why these lines are currently there :(

File: packages/babel-parser/src/parse-error.js (hunk 2 above)
Comment (tolmasky) [reply packages/babel-parser/src/parse-error.js:104]: Credentials isn't an array, its a `ParseErrorCredentials` (in the type declaration above):

```javascript
function toParseErrorClass<ErrorDetails>(
  toMessage: ToMessage<ErrorDetails>,
  credentials: ParseErrorCredentials,
)
``` 

And `ParseErrorCredentials` is defined as:

```javascript
export type ParseErrorCredentials = {
  code: ParseErrorCode,
  reasonCode: string,
  syntaxPlugin?: SyntaxPlugin,
};
```

Thus, if we could *also* make `syntaxPlugin` an optional field of `ParseError`, then Flow wouldn't complain. But since `syntaxPlugin` is *not present* in `ParseError` at all (because that would force errors with no `syntaxPlugin` to have a `syntaxPlugin` field with `undefined`), we can't call `Object.assign` without Flow saying "wait a minute, this MAY have a syntaxPlugin, which ParseError *doesn't* have!" So, this is equivalent to the following code:

```javascript
      // Items everyone agrees we have:
      const { syntaxPlugin = NoPresent, ...undisputed } = credentials;
      ObjectAssign(this, undisputed);
      // No-op but makes Flow happy
      if (syntaxPlugin != NotPresent) {
          this.syntaxPlugin = syntaxPlugin;      
      }
```

File: packages/babel-parser/test/fixtures/typescript/cast/unparenthesized-assert-and-assign/output.json [hunk 10]
```diff
@@ -3,7 +3,8 @@
   "start":0,"end":46,"loc":{"start":{"line":1,"column":0,"index":0},"end":{"line":2,"column":29,"index":46}},
   "errors": [
     "SyntaxError: Invalid left-hand side in assignment expression. (1:0)",
-    "SyntaxError: Invalid left-hand side in assignment expression. (2:6)"
+    "SyntaxError: Invalid left-hand side in assignment expression. (2:6)",
+    "SyntaxError: Invalid left-hand side in object destructuring pattern. (2:6)"
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/test/fixtures/typescript/cast/unparenthesized-assert-and-assign/output.json:7]: We are reporting two errors at the same position, for the same invalid syntax. We should use `raiseOverwrite` and only report the second one.

File: packages/babel-parser/test/fixtures/typescript/const/no-initializer/output.json [hunk 11]
```diff
@@ -1,6 +1,9 @@
 {
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/test/fixtures/typescript/const/no-initializer/output.json:1]: Can you create a test with the same input as this one in the `dts` folder?

File: scripts/parser-tests/typescript/index.js [hunk 12]
```diff
@@ -1,37 +1,58 @@
...
-import ts from "../../../build/typescript/lib/typescript.js";
 import TestRunner from "../utils/parser-test-runner.js";
-import parsingErrorCodes from "./error-codes.js";
+import ErrorCodes from "./error-codes.js";
+
+import { spawnSync } from "child_process";
+const getEncoding = path =>
+  spawnSync("file", ["--brief", "--mime-encoding", path])
+    .stdout.toString()
+    .slice(0, -1);
```
Comment (nicolo-ribaudo) [inline scripts/parser-tests/typescript/index.js:11]: If this is for a trailing newline, `.trim()` is more explicit.

File: packages/babel-parser/src/parse-error.js (hunk 1 above)
Comment (tolmasky) [reply packages/babel-parser/src/parse-error.js:98]: Short answer is not trivially, but there are kind of two categories of reasons for this, "design reasons" (legitimate), and "Flow reasons" (unfortunate):

1. To approach this from the "design" side first, this is in many senses fundamentally asking whether Errors should be nominal types or not. If we were to try to collapse all errors employ "one re-usable class", then you can't robustly express something like:

```javascript
export type DeferredStrictErrorClass =
  | typeof Errors.StrictNumericEscape
  | typeof Errors.StrictOctalLiteral;
```

This is because, despite these errors having different names, they all fundamentally have the same "shape", which is just `ParseError<{||}>`. That is to say, they're just type aliases, which can cross-satisfy. So ParseErrorA *can* satisfy ParseErrorB, as long as they have identical `ErrorDetails`, which is at it turns out is very common because the vast majority of ParseError types are implicitly parameterized with empty details (`{||}`). This is made even worse by the fact that, from the user's perspective (the user being us in this case), it seems arbitrary which types are nominal and which aren't. Because, if the ParseError *does* have a unique shape, all of a sudden it behaves effectively like a nominal type. For example, no other error is ever going to have a `surrogateCharCode` member, so for all practical purposes, `Errors.ModuleExportNameHasLoneSurrogate` *is* a nominal type, and you can safely write a function like this:

```function doSomethingWithALoneSurrogateError(error: Errors.ModuleExportNameHasLoneSurrogate) {
// Can't pass just any old error here!
}
```

So by collapsing everything to one class, you get this weird world that can lull you into thinking you can use the type system to very specifically type certain functions, only to be surprised that that's not the case... but only sometimes.

Now, in Typescript (and other type systems), there is a tricky solution to this. You can force nominality with phantom fields that are only present at type-check time. In my original Typescript implementation, I actually wrote it the way you proposed, and employed this trick, something like this:

```
type ParseErrorClasses<T extends AllErrorDetails> = {
  [ReasonCode in keyof AllErrorDetails]:
    ParseErrorClass<AllErrorDetails[ReasonCode]> & { NominalType: ReasonCode };
};
```

As you can see here, we're actually using the `ReasonCode` to further narrow the acceptable type (without making it a static field, which has it's own issues). In this scenario, even if ErrorDetailsA === ErrorDetailsB, Error.A !== Error.B, because `{ NominalType: "A" }` does *not* satisfy `{ NominalType: "B" }`. Now, this is unfortunately not doable in Flow, although even if we did go this route in Typescript it has it's own downsides. But, to summarize the "design decision", making each error a separate class allows us to be more expressive with our types, which I do make use of throughout the code.

2. To just address a further Flow-specific thing, Flow is very finicky about shuttling parameter arguments around. Having a specific class-per-error allows Flow to keep the different parameterized types separate. This is due to a know bug (previously "expected behavior") where Flow "pushes" function unions down to their parameters. Here is a reproduction: https://github.com/facebook/flow/issues/8838. I actually got really close to doing something like you're describing, but then Flow says "oh wait a minute, shouldn't I just merge *all* the constructor calls to be unions of each-other then?" So basically instead of constructor<T>(T) | constructor<U>(U), it transforms it into constructor<T | U>({ ...T, ...U }), meaning every error will accept the arguments for every error defined anywhere (ahhhhhhh!) What makes this bug even more insidious is that it only happens on *calling*. That is to say, everything *seems* fine until you actually raise the error. This was super frustrating because I was getting this all working in the try flow playground, and I would try raising individual errors, and everything would be fine, but then I'd try `make flow` and it would be broken. Finally, I tried calling two *separate* raises and it broke in the playground.  Anyways, if and when Flow fixes this (they *do* want it to work like Typescript, but its part of a year-long rewrite), then *that* part of the problem would be solved. So, when we move to Typescript, something like this *would* be easier.

3. Just to add one more consideration, I tried to do my best to not make any internal functionality public, such that any "abuses" of the API would be fine. So for example:

```javascript
// We don't want this:
const ParseErrorClass = result.errors[0].constructor;
const trickyError = new ParseErrorClass(myOwnToMessage);
// But we're fine with this:
const sureDoThis = new ParseErrorClass({ loc: new Position() });
```

File: packages/babel-parser/src/parse-error.js (hunk 9 above)
[the remark this answers is not in the document]
Comment (nicolo-ribaudo) [reply packages/babel-parser/src/parse-error.js:73]: Oh well, just leave `return this` here then :shrug:

File: packages/babel-parser/src/parse-error.js (hunk 1 above)
Comment (nicolo-ribaudo) [reply packages/babel-parser/src/parse-error.js:98]: Since all the errors have a distinct `reasonCode` property, doesn't it make them nominal?

File: packages/babel-parser/src/parse-error/module-errors.js (hunk 6 above)
Comment (tolmasky) [reply packages/babel-parser/src/parse-error/module-errors.js:5]: Yeah, this one is really unfortunate. If you look at the flow/typescript/placeholder/etc. errors, they don't need this at all, because they just call `toParseErrorClasses(_ => ...)`, and so get the function's type inferred for free. The standard errors can't do this because I want to export them *from* parse-error, and do to the infuriating way that import works (this wouldn't be a problem using `require`), I can't use `toParseErrorClasses` in these files (see me complaining about this here: https://twitter.com/tolmasky/status/1492204196019453952?s=21 ). I chose not to export `toParseErrorCredentials` for this reason, since its an ugly artifact of the Flow/ESM combination (it wouldn't be necessary with Typescript/ESM *or* with Flow/require), we don't need it for any of the plugin error definitions, and we can hopefully completely get rid of it when we switch to Typescript. But, happy to do this one if you want, just wanted to explain the reasoning (or rather, just vent about ESM and Flow ;) )

File: packages/babel-parser/src/parser/expression.js [hunk 13]
```diff
@@ -946,18 +947,18 @@ export default class ExpressionParser extends LValParser {
         }
       }
       if (node.arguments.length === 0 || node.arguments.length > 2) {
-        this.raise(
-          Errors.ImportCallArity,
-          { node },
-          this.hasPlugin("importAssertions") ||
+        this.raise(Errors.ImportCallArity, {
+          at: node,
+          required:
```
[the remark this answers is not in the document]
Comment (tolmasky) [reply packages/babel-parser/src/parser/expression.js:952]: Sounds good, will change. I didn't like this one and am happy to have someone tell me what to use!

File: packages/babel-parser/src/parser/statement.js [hunk 14]
```diff
@@ -722,14 +719,14 @@ export default class StatementParser extends ExpressionParser {
...
+        this.raise(Errors.ForOfAsync, { at: init });
       }
     }
     if (isForOf || this.match(tt._in)) {
       this.checkDestructuringPrivate(refExpressionErrors);
       this.toAssignable(init, /* isLHS */ true);
-      const description = isForOf ? "for-of statement" : "for-in statement";
-      this.checkLVal(init, description);
+      const type = isForOf ? "ForOfStatement" : "ForInStatement";
+      this.checkLVal(init, { in: { type } });
```
[the remark this answers is not in the document]
Comment (tolmasky) [reply packages/babel-parser/src/parser/statement.js:729]: Sigh (cries in anguish remembering how I first wrote the whole thing to work exactly like that, only to then discover...) that then we can't differentiate between "postfix operation" and "prefix operation". I *wish* we just had `PrefixUpdateExpression` and `PostfixUpdateExpression`. The current official answer is "this represents the "human-type-identifying aspects of a node, which in almost all circumstances is just "type", but due to the decision of merging postfix and prefix operations into one kind of node, is not *always* the case".

File: scripts/parser-tests/typescript/index.js (hunk 12 above)
Comment (tolmasky) [reply scripts/parser-tests/typescript/index.js]: Done: https://github.com/babel/babel/pull/14320/commits/8e16a07f4b2698b85a5e2ee9f3edf2c22cb7631a

File: packages/babel-parser/src/parse-error.js [hunk 15]
```diff
@@ -0,0 +1,211 @@
...
+// eslint-disable-next-line no-redeclare
+declare function toParseErrorClasses<T: Object>(
+  toClasses: (typeof toParseErrorCredentials) => T,
+  syntaxPlugin?: string,
+): T;
+
+// See comment about eslint and Flow overloading above.
+// eslint-disable-next-line no-redeclare
+export function toParseErrorClasses(argument, syntaxPlugin) {
+  if (ArrayIsArray(argument)) {
```
[the remark this answers is not in the document]
Comment (tolmasky) [reply packages/babel-parser/src/parse-error.js:173]: Done: https://github.com/babel/babel/pull/14320/commits/3a914eca4e135349686507ebf3750431d84f9d4f

File: packages/babel-parser/src/parse-error.js (hunk 1 above)
Comment (tolmasky) [reply packages/babel-parser/src/parse-error.js:98]: Right, but I have been incapable of getting this to work in Flow, specifically, when first routed through `toParseErrorClasses` *and* in `raise`. It's "easy" to make `toParseErrorClass` (not-plural) work, it totally breaks down for `toParseErrorClasses` (do to parameter-type extraction not working, and $ObjiMap not working, and type-parameter type extraction not working, any of which would provide an escape hatch, all of which will "in theory" work when that bug I linked to is fixed).

To briefly summarize, unlike in Typescript, I don't have access to `ReasonCode` at the right time, since it's "trapped" in the keys of the definition object. In Typescript, this is irrelevant, since `keyof` *actually works*, and this is trivial:
```javascript
toParseErrorClasses<T>(errors: T):
  { [ReasonCode keyof T]: ParseError<ReasonCode, Parameters<T[ReasonCode]>>[0] }
```
Flow however has no way of extracting the parameters of types from a function (well, it almost does, but it's broken, you can find several issues on it). Hence the need to bounce everything through that annoying `_` function, which means we don't know the `ReasonCode` at the point of creating our `ParseError` class. So, not a problem you might say, we'll just create an intermediate "shuttle" type to "carry" the `ErrorDetails` to the next step (which we kind of also do in the current implementation), but then you run into Flow's inability to properly extract (infer) the parameterized types. I will try to find my saved tryFlow examples, but even if we dramatically loosen the constraints around the "usability" of the API and start forcing the user to type more and more boilerplate, you then run into the bug I linked to above, where without the "class separation" to artificially prevent Flow from getting confused and thinking these are all overloads of the same constructor/raise function and thus union-ing the parameter types. 

Anyways, I definitely would prefer something *like* this (I still think there are some issues with a method like this, in particular I find it weird to have to pass in a reasonCode that it already knows ahead of time what it should be exactly, and I also dislike that if a user gets ahold of these classes, there's no type system to enforce that -- but that's a different matter to discuss if we can first get this working at all). In fact, if you recall this is what originally made me angry enough to try to *first* port the entire parser to typescript just to avoid having to find workarounds to well-known bugs in Flow. That being said, I can't tell from this whether you tried it already, but if you have and you've gotten it working with `toParseErrorClasses` and `raise`, I'd actually be super open to looking into it further, since I do agree that the current internals aren't ideal, but as far as I can tell provide the closest thing to the ideal API we're going to get before switching to Typescript.

File: packages/babel-parser/src/parse-error.js [hunk 16]
```diff
@@ -0,0 +1,211 @@
...
+  }
+
+  clone({
+    loc,
+    details,
+  }: {
+    loc?: Position,
+    details?: ErrorDetails,
+  } = {}) {
+    return new (ObjectGetPrototypeOf(this).constructor)({
```
[the remark this answers is not in the document]
Comment (tolmasky) [reply packages/babel-parser/src/parse-error.js:83]: It might be, can't remember why I did that, I will check and change it to that if so.

File: packages/babel-parser/src/parser/expression.js (hunk 13 above)
[the remark this answers is not in the document]
Comment (tolmasky) [reply packages/babel-parser/src/parser/expression.js]: Done: https://github.com/babel/babel/pull/14320/commits/cc47820d2f1abf11d9f5ededc5a75078d64e2db4

File: packages/babel-parser/src/parse-error.js (hunk 4 above)
Comment (tolmasky) [reply packages/babel-parser/src/parse-error.js:180]: I use `Object.keys` here because when I use `Object.entries` was added in Node 8. I wasn't sure whether our compilation process did any fancy polyfilling, but I'm pretty sure the Node 6 tests failed when I used `Object.entries`.

File: packages/babel-parser/src/parse-error.js (hunk 16 above)
[the remark this answers is not in the document]
Comment (tolmasky) [reply packages/babel-parser/src/parse-error.js:83]: Ah, I remember now! I did that because `instance.constructor` *can* be mutated, but `Object.getPrototypeOf(instances).constructor` *can't* be mutated, so this guarantees we're getting the right class. If this is too defensive of a nit-pick, I can change it though.

File: packages/babel-parser/src/parse-error/to-node-description.js (hunk 7 above)
Comment (tolmasky) [reply packages/babel-parser/src/parse-error/to-node-description.js]: Done, I did it on a separate commit because I had to do the code formatting with Prettier: https://github.com/tolmasky/babel/commit/650917d5a1dca21369440d223e59730af02cff7f

File: packages/babel-parser/test/fixtures/typescript/const/no-initializer/output.json (hunk 11 above)
Comment (tolmasky) [reply packages/babel-parser/test/fixtures/typescript/const/no-initializer/output.json:1]: Done: https://github.com/tolmasky/babel/commit/d8c403a9c29b53549c73d7360c05bf934b6038dc

File: packages/babel-parser/test/fixtures/typescript/declare/const-new-line/output.json [hunk 17]
```diff
@@ -1,6 +1,10 @@
 {
   "type": "File",
   "start":0,"end":35,"loc":{"start":{"line":1,"column":0,"index":0},"end":{"line":2,"column":27,"index":35}},
+  "errors": [
+    "SyntaxError: Missing initializer in const declaration. (2:15)",
+    "SyntaxError: Missing initializer in const declaration. (2:26)"
```
[the remark this answers is not in the document]
Comment (tolmasky) [reply packages/babel-parser/test/fixtures/typescript/declare/const-new-line/output.json]: Done: https://github.com/babel/babel/pull/14320/commits/94ae6def47b04890366404b279bb4e74e370b0f9

I want to point out that this test seems to be incorrect though, as typescript proper seems to be angry by the newline in-between them, but we are happy about it. However, this matches previous behavior so is outside the scope of this PR.

https://www.typescriptlang.org/play?#code/CYUwxgNghgTiBQYD2A7AzgFwAQA8BcWKArgLYBGIMWAvFgIwAMANFgJ4GYwCWKA5jVgBEAJgaCA3PHihIsBMnTYcwgsXKUWrFVk49ek+EA

File: scripts/parser-tests/typescript/index.js [hunk 18]
```diff
@@ -1,37 +1,58 @@
...
+import fs from "fs";
 import { fileURLToPath } from "url";
-import ts from "../../../build/typescript/lib/typescript.js";
 import TestRunner from "../utils/parser-test-runner.js";
-import parsingErrorCodes from "./error-codes.js";
+import ErrorCodes from "./error-codes.js";
+
+import { spawnSync } from "child_process";
+const getEncoding = path =>
+  spawnSync("file", ["--brief", "--mime-encoding", path])
```
Comment (JLHwung) [inline scripts/parser-tests/typescript/index.js:9]: The typescript parser test is 5x slower (3s vs 16s) due to the process spawning overhead. Since there are only 7 tests failing if we assume they are `utf-8`:
```
     bom-utf16be.ts false true
     bom-utf16le.ts false true
     collisionCodeGenModuleWithUnicodeNames.ts false true
     instanceofOperator.ts false true
     promiseTest.ts false true
     targetTypeBaseCalls.ts false true
     unicodeIdentifierNames.ts false true
```
Can we read the test file as buffer and check the BOM instead? Or we can just hardcode those utf16 files.

**Review by JLHwung — COMMENTED** [review]
> Seems like we should consider renaming InvalidOrUnexpectedToken to UnexpectedCharacter, or removing it and just using UnexpectedToken instead.

I agree, however since the reasonCode is part of API, we have to defer such changes to Babel 8.

File: scripts/parser-tests/typescript/index.js (hunk 18 above)
Comment (tolmasky) [reply scripts/parser-tests/typescript/index.js:9]: Let me see if I can read them all in one go (and thus only spawn once), would prefer to not have to mess around with BOMs.

File: packages/babel-parser/src/parse-error.js (hunk 1 above)
Comment (nicolo-ribaudo) [reply packages/babel-parser/src/parse-error.js:98]: I tried this: https://github.com/tolmasky/babel/pull/1

Comment (tolmasky) [reply packages/babel-parser/src/parse-error.js:98]: Right, but the only purpose for `toParseErrorClasses` is to avoid this boilerplate and duplication ;) If you pass in all the info to `_` yourself, not only does it work (since we already know we can make `x = toParseErrorClass<"blah">()` work), it now actually makes `toParseErrorClasses` redundant, since you can remove it and get the same behavior as just manually calling `toParseErrorClass` on each set of infos yourself manually:

```javascript
const Errors = toParseErrorClasses(_ => ({
 Error1 = _<"Error1>("message"),
 Error2 = _<"Error2", {| x: string |}>(({ x: string }) => `...`)
});
```

Doesn't provide any "type inference magic" over the following:

```javascript
const Errors = {
 Error1 = toParseErrorClass("Error1",  "message"),
 Error2 = toParseErrorClass<{| x: string |}>("Error2",  ({ x: string }) => `...`)
};
```
It only saves you from typing the long function name `toParseErrorClass`, which is equivalently resolved by just renaming it to that manually:

```javascript
import { toParseErrorClass as _ } from "./parse-error";

const Errors = {
 Error1 = _<"Error1">( "message"),
 Error2 = _<"Error2">({ x: string }) => `...`)
};
```

But in all cases, we now have to specifically, repeatedly, provide all the information at the call-site, which skirts around the original goal of avoiding the change for errors through boilerplate, and the noisiness of having the error definitions dominated by the same error codes and type info over and over. Unfortunately, the need for the `_` in Flow makes this a little less clear, since in Typescript the following is so much cleaner:

```javascript
Errors = toParseErrorClasses({
 Error1: "message",
 Error2: ({ x: string }) => `...`) // no need even for <{ x: string }>!
});
```

File: packages/babel-parser/src/parse-error/pipeline-operator-errors.js [hunk 19]
```diff
@@ -0,0 +1,60 @@
...
+  "ArrowFunctionExpression",
+  "AssignmentExpression",
+  "ConditionalExpression",
+  "YieldExpression",
+]);
+
+export default (_: typeof toParseErrorCredentials) => ({
+  // This error is only used by the smart-mix proposal
+  PipeBodyIsTighter: _(
+    `Unexpected yield after pipeline body; any yield expression acting as Hack-style pipe body must be parenthesized due to its loose operator precedence.`,
```
[the remark this answers is not in the document]
Comment (tolmasky) [reply packages/babel-parser/src/parse-error/pipeline-operator-errors.js]: Done: https://github.com/babel/babel/pull/14320/commits/39564c4a86aa7ecf47dbbbc3c430b2bb4e66908f

File: packages/babel-parser/src/parse-error/to-node-description.js [hunk 20]
```diff
@@ -0,0 +1,34 @@
...
+type NodeWithDescription =
+  | { type: "UpdateExpression", prefix: boolean }
+  | { type: NodeTypesWithDescriptions };
+
+// eslint-disable-next-line no-confusing-arrow
+const toNodeDescription = ({ type, prefix = false }: NodeWithDescription) =>
```
[the remark this answers is not in the document]
Comment (tolmasky) [reply packages/babel-parser/src/parse-error/to-node-description.js]: Done: https://github.com/babel/babel/pull/14320/commits/39564c4a86aa7ecf47dbbbc3c430b2bb4e66908f

File: packages/babel-parser/src/parse-error.js (hunk 1 above)
Comment (tolmasky) [reply packages/babel-parser/src/parse-error.js]: Alright, I just pushed an update that seems to work. I'll describe it here tomorrow, but the most important point is that this version doesn't have any sort of `ParseError` class at all, so we're I think just about as close as possible to introducing no new outside-observable changes. Still want to clean it up a bit more and then explain the change here, but will get to it tomorrow.

File: packages/babel-parser/src/parse-error.js [hunk 21]
```diff
@@ -0,0 +1,176 @@
...
+  ParseErrorCodes,
+  type ParseErrorCredentials,
+} from "./parse-error/credentials";
+
+// Babel uses "normal" SyntaxErrors for it's errors, but adds some extra
+// functionality. This functionality is defined in the
+// `ParseErrorSpecification` interface below. We may choose to change to someday
+// give our errors their own full-blown class, but until then this allow us to
+// keep all the desirable properties of SyntaxErrors (like their name in stack
+// traces, etc.), and also allows us to punt on any publically facing
```
Comment (JLHwung) [inline packages/babel-parser/src/parse-error.js:17]:
```suggestion
// traces, etc.), and also allows us to punt on any publicly facing
```

Comment (tolmasky) [reply packages/babel-parser/src/parse-error.js:17]: Good catch!

File: packages/babel-parser/src/parser/statement.js (hunk 14 above)
[the remark this answers is not in the document]
Comment (tolmasky) [reply packages/babel-parser/src/parser/statement.js:729]: OK, I still want to clean up a few things, and add more comments, etc., but here is an explanation of the current code. First, the starting with the goals:

1. First off, we want to have the named and type-checked parameters of course.
2. We'd like to have an easy way of defining these errors.
3. We'd like for these changes to minimally affect the publicly exposed API.

As mentioned previously, all of these are trivially achievable in Typescript, thanks to much better inference and way better functioning object-mapping support. That being said, the original implementation of this PR didn't satisfy (3), due to creating a class per error (which I think might have some potentially benefits as an *API choice* in the future, but I agree that we should avoid it now if possible, since it is a *separate* concern from the goals above, and may tie us to a decision we need to support in the future). 

I did manage to find a workaround to the bug that was preventing us from having the nominal types without a subclass, using an indirection trick (if you do `[V][0]`, Flow stops "merging" all the types together). Unfortunately, this only works in later versions of Flow, and upgrading even a few versions up puts us in the new [type-first](https://flow.org/en/docs/lang/types-first/) mode in Flow, which throws thousands of errors. So, didn't seem worth it to try to block everything on that big update.

However, as I was trying to remove the subclasses-per-error-type stuff, I realized that this is still technically a problem even if we do get it down to *one* combined `ParseError` class, as that still deviates from the current behavior of just using `SyntaxError`'s. Given that the current code already did some fancy stuff to hide that fact (like overriding the constructor name), it seems that whether we add 1 class to the hierarchy or 2 doesn't make that much of a difference (unless you're doing really weird stuff like `error1 instanceof error2.constructor` or something), and by that I mean they're both "bad", not that they're both "good" so we shouldn't worry about it. Additionally, I noticed that in some of the most critical places where we used our nominal types, the original PR wasn't taking advantage of the nominality (such as with `raise`).

So, the new approach works much harder on fixing (2) completely (by going back to a "just SyntaxErrors with extra properties" approach), and keeping it "as nominal" as the original PR (which is to say, unfortunately not nominal enough, but it's really only affecting the quality of the error messages currently), and putting us in a place that definitely has identical "value structure" to what we'd get in a future move to Typescript, with *almost* most of the type conveniences.

File: packages/babel-parser/src/parse-error/credentials.js [hunk 22]
```diff
@@ -0,0 +1,66 @@
...
+};
+
+const thisify = <T>(f: (self: any, ...args: any[]) => T): ((...any[]) => T) =>
+  function (...args: any[]): T {
+    return ((f(this, ...args): any): T);
+  };
+
+const reflect = (keys: string[], last = keys.length - 1) => ({
+  get: self => keys.reduce((object, key) => object[key], self),
+  set: (self, value) =>
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/src/parse-error/credentials.js:34]: I'd prefer to just define descriptors using a real `this`, and avoid both `thisify` and the `...(descriptor.get && { get: thisify<any>(descriptor.get) })`s below.

File: packages/babel-parser/src/parse-error/credentials.js [hunk 23]
```diff
@@ -0,0 +1,66 @@
+// @flow
+
+export const ParseErrorCodes = Object.freeze({
+  SyntaxError: "BABEL_PARSER_SYNTAX_ERROR",
+  SourceTypeModuleError: "BABEL_PARSER_SOURCETYPE_MODULE_REQUIRED",
+});
+
+export type ParseErrorCode = $Values<typeof ParseErrorCodes>;
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/src/parse-error/credentials.js:8]: I'm surprised that Flow reports this as `$Values<{| SourceTypeModuleError: string, SyntaxError: string |}>`, but then it does the correct thing and doesn't allow me to assign any string to it.

**Review by nicolo-ribaudo — APPROVED** [review]

File: packages/babel-parser/src/parse-error/credentials.js (hunk 22 above)
Comment (tolmasky) [reply packages/babel-parser/src/parse-error/credentials.js:34]: Yup, sorry got stubborn working on this at night, will do.

Comment (tolmasky) [reply packages/babel-parser/src/parse-error/credentials.js]: Done: https://github.com/babel/babel/pull/14320/commits/97ab2abdbc4974328fd49cecf6bd7085f9dfff11

File: scripts/parser-tests/typescript/index.js (hunk 18 above)
Comment (tolmasky) [reply scripts/parser-tests/typescript/index.js]: OK just ended up doing the BOM thing like you suggested. I tried looking at other PRs, and I see them mostly taking in the 9s range, while these now take 6s -- so it seems faster than without this PR (certainly faster than when I was shelling out to `file` of course), but just wanting to point out the actual times since you mentioned 3s, but perhaps that was just on your machine?

Comment (tolmasky) [reply scripts/parser-tests/typescript/index.js]: Here is the commit, do un-resolve the conversation if you think it is still an issue: https://github.com/babel/babel/pull/14320/commits/f38dc5d93278c7fab9dbb7cf846bc40c4ff12652

File: packages/babel-parser/src/parse-error.js (hunk 1 above)
Comment (tolmasky) [reply packages/babel-parser/src/parse-error.js]: Meant to put this here originally, just copying it here in case someone else is reading:

OK, I still want to clean up a few things, and add more comments, etc., but here is an explanation of the current code. First, the starting with the goals:

1. First off, we want to have the named and type-checked parameters of course.
2. We'd like to have an easy way of defining these errors.
3. We'd like for these changes to minimally affect the publicly exposed API.

As mentioned previously, all of these are trivially achievable in Typescript, thanks to much better inference and way better functioning object-mapping support. That being said, the original implementation of this PR didn't satisfy (3), due to creating a class per error (which I think might have some potentially benefits as an *API choice* in the future, but I agree that we should avoid it now if possible, since it is a *separate* concern from the goals above, and may tie us to a decision we need to support in the future). 

I did manage to find a workaround to the bug that was preventing us from having the nominal types without a subclass, using an indirection trick (if you do `[V][0]`, Flow stops "merging" all the types together). Unfortunately, this only works in later versions of Flow, and upgrading even a few versions up puts us in the new [type-first](https://flow.org/en/docs/lang/types-first/) mode in Flow, which throws thousands of errors. So, didn't seem worth it to try to block everything on that big update.

However, as I was trying to remove the subclasses-per-error-type stuff, I realized that this is still technically a problem even if we do get it down to *one* combined `ParseError` class, as that still deviates from the current behavior of just using `SyntaxError`'s. Given that the current code already did some fancy stuff to hide that fact (like overriding the constructor name), it seems that whether we add 1 class to the hierarchy or 2 doesn't make that much of a difference (unless you're doing really weird stuff like `error1 instanceof error2.constructor` or something), and by that I mean they're both "bad", not that they're both "good" so we shouldn't worry about it. Additionally, I noticed that in some of the most critical places where we used our nominal types, the original PR wasn't taking advantage of the nominality (such as with `raise`).

So, the new approach works much harder on fixing (2) completely (by going back to a "just SyntaxErrors with extra properties" approach), and keeping it "as nominal" as the original PR (which is to say, unfortunately not nominal enough, but it's really only affecting the quality of the error messages currently), and putting us in a place that definitely has identical "value structure" to what we'd get in a future move to Typescript, with *almost* most of the type conveniences.

File: packages/babel-parser/src/parse-error.js (hunk 5 above)
Comment (tolmasky) [reply packages/babel-parser/src/parse-error.js]: We ended up not needing this anymore with the "use SyntaxErrors" system.

File: packages/babel-parser/src/parse-error.js (hunk 3 above)
Comment (tolmasky) [reply packages/babel-parser/src/parse-error.js]: Got rid of these.

File: packages/babel-parser/src/parse-error.js (hunk 16 above)
[the remark this answers is not in the document]
Comment (tolmasky) [reply packages/babel-parser/src/parse-error.js]: With the new system we don't do this at all anymore.

File: packages/babel-parser/src/parse-error.js (hunk 9 above)
[the remark this answers is not in the document]
Comment (tolmasky) [reply packages/babel-parser/src/parse-error.js]: With the new system we don't need to do this at all anymore.

File: packages/babel-parser/src/parser/statement.js [hunk 24]
```diff
@@ -2536,19 +2536,17 @@ export default class StatementParser extends ExpressionParser {
...
 
       if (node.key.name !== "type") {
-        this.raise(
-          Errors.ModuleAttributeDifferentFromType,
-          { node: node.key },
-          node.key.name,
-        );
+        this.raise(Errors.ModuleAttributeDifferentFromType, {
+          at: node.key,
+          // key: node.key.name,
```
[the remark this answers is not in the document]
Comment (tolmasky) [reply packages/babel-parser/src/parser/statement.js]: I had originally commented it because I was confused why it was there, it later turned out that it was just not used (this is the one I mention in the summary). I have now gotten rid of it though, good catch!

File: packages/babel-parser/src/plugins/typescript/index.js [hunk 25]
```diff
@@ -2434,25 +2553,74 @@ export default (superClass: Class<Parser>): Class<Parser> =>
...
+      if (!isAmbientContext) return declaration;
+
+      for (const { id, init } of declaration.declarations) {
+        // Empty initializer is the easy case that we want.
+        if (!init) continue;
+
+        // var and let aren't ever allowed initializers.
+        //
+        // If a const declaration has no type annotation and is initiailized to a
+        // string literal, numeric literal, or (FIXME) enum reference, then it is
```
[the remark this answers is not in the document]
Comment (tolmasky) [reply packages/babel-parser/src/plugins/typescript/index.js:2584]: Yeah, this was written before that. Although `isPossiblyLiteralEnum` is still technically more liberal than something that actually has a sense of the enums and types, but this follows the rest of the parser's approach of sticking to syntax. I'll update the comment to reflect that.

[the remark this answers is not in the document]
Comment (tolmasky) [reply packages/babel-parser/src/plugins/typescript/index.js]: Done: https://github.com/babel/babel/pull/14320/commits/14674c17869116ffa927a358c3888deee0d9b250

File: packages/babel-parser/src/util/scope.js [hunk 26]
```diff
@@ -38,13 +39,13 @@ export class Scope {
...
-  declare raise: raiseFunction;
-  declare inModule: boolean;
+  inModule: boolean;
   undefinedExports: Map<string, Position> = new Map();
 
-  constructor(raise: raiseFunction, inModule: boolean) {
-    this.raise = raise;
+  constructor(parser: Tokenizer, inModule: boolean) {
+    this.parser = parser;
     this.inModule = inModule;
```
[the remark this answers is not in the document]
Comment (tolmasky) [reply packages/babel-parser/src/util/scope.js:49]: I wasn't sure, and got scared by how `initializeScopes` in `UtilParse` seems to mutate `inModule` (it might end up behaving identically to just always referring to the parent parser's inModule, but wasn't as familiar with that part of the code). I spent a little time trying to understand all this when I briefly went down a rabbit hole of trying to get typescript module/namespace scopes [working better](https://github.com/tolmasky/babel/tree/parse-error-better-scopes), which I later abandoned because it would have made this PR much harder to understand I think, and because namespace scopes aren't super well documented (https://github.com/microsoft/TypeScript/issues/48047), but I do think there were some good ideas in there I'd like to return to. Anyways, that branch had better support for nesting scopes generally, to the point where I think we were close to being able to dump the "store everything in a temp variable, switch the parser, then restore everything in a finally block" strategy, and instead "push a module scope". In that sort of scenario, I think `inModule` makes more sense as *solely* belonging to the scope, vs. belonging to the parser.

File: packages/babel-parser/src/parser/lval.js [hunk 27]
```diff
@@ -494,145 +495,211 @@ export default class LValParser extends NodeUtils {
...
+  isValidLVal(type: string, isParenthesized: boolean, binding: BindingTypes) {
+    return (
+      {
+        AssignmentPattern: "left",
+        RestElement: "argument",
+        ObjectProperty: "value",
+        ParenthesizedExpression: "expression",
+        ArrayPattern: "elements",
+        ObjectPattern: "properties",
+      }[type] || false
```
[the remark this answers is not in the document]
Comment (tolmasky) [reply packages/babel-parser/src/parser/lval.js]: Turns out that this really makes Flow angry. Working on a solution to this, but no matter what we're going to need a FlowIgnore to do this I think.

File: packages/babel-parser/src/plugins/flow/index.js [hunk 28]
```diff
@@ -2345,21 +2433,10 @@ export default (superClass: Class<Parser>): Class<Parser> =>
...
-            boolean | void,
-            boolean | void,
-          ]
-    ): void {
-      if (expr.type !== "TypeCastExpression") {
-        return super.checkLVal(expr, ...args);
-      }
+    isValidLVal(type: string, ...rest) {
+      return (
+        { TypeCastExpression: true }[type] || super.isValidLVal(type, ...rest)
```
[the remark this answers is not in the document]
Comment (tolmasky) [reply packages/babel-parser/src/plugins/flow/index.js]: Done: https://github.com/babel/babel/pull/14320/commits/001e0967e61d8035cd6f64ea5b7edd681d57923e

File: packages/babel-parser/src/plugins/typescript/index.js [hunk 29]
```diff
@@ -3442,7 +3589,17 @@ export default (superClass: Class<Parser>): Class<Parser> =>
...
+      // If the user took the time to provide a filename and it has the ".d.ts"
+      // file extension, then assume they want ambient context parsing unless
+      // they explicitly specify otherwise.
+      const DTS = this.getPluginOption("typescript", "dts");
+      const DTSTruthy = !!DTS;
+      const DTSFalse = DTS === false;
+
+      return (
+        DTSTruthy ||
+        (!DTSFalse && !!this.filename && /\.d\.ts$/.test(this.filename))
```
[the remark this answers is not in the document]
Comment (tolmasky) [reply packages/babel-parser/src/plugins/typescript/index.js]: Done: https://github.com/babel/babel/pull/14320/commits/06f46ab44324b7923425bffa8000e3ed39566ad1

File: packages/babel-parser/test/fixtures/typescript/cast/unparenthesized-assert-and-assign/output.json (hunk 10 above)
Comment (tolmasky) [reply packages/babel-parser/test/fixtures/typescript/cast/unparenthesized-assert-and-assign/output.json:7]: So, this isn't actually anything new and is just following the "current behavior" or recursively giving you every left-hand-side error in an expression. You can test this by using the current babel with something like this:

```javascript
require("@babel/parser").parse("({ a: ++5 } = 10)", { errorRecovery: true }).errors
```

Which will give you an almost identical result:

```
SyntaxError: Invalid left-hand side in prefix operation. (1:8)
SyntaxError: Invalid left-hand side in object destructuring pattern. (1:6)
```

In fact, you can create a pathological case by just doing:

```javascript
require("@babel/parser").parse("5++++++", { errorRecovery: true }).errors
```

And that will look even worse, since they'll "seem" like duplicated bugs, just because they all start at the same position (but in reality would look different if we tracked error *ranges*):

```
SyntaxError: Invalid left-hand side in postfix operation. (1:0)
SyntaxError: Invalid left-hand side in postfix operation. (1:0)
SyntaxError: Invalid left-hand side in postfix operation. (1:0)
SyntaxError: Invalid left-hand side in postfix operation. (1:0)
```

Anyways, all this to say, I think if we want different behavior for nested LHS errors, we should file a separate bug for exploring the raiseOverwrite thing, but this current test is simply surfacing that we now correctly don't ignore this LHS bug and just happens to surface this existing behavior, which to fix would require exploring and unrelated thing and potentially changing other test results and behaviors.

**Review by JLHwung — APPROVED** [review]
