### PR TITLE
fix: do not add `.value: undefined` to regexp literals

### LINKED ISSUE #16419: [Bug]: @babel/parser adds `.value: undefined` to regexp literals
https://astexplorer.net/#/gist/c57f3172d6d43582ea154a859089d21e/latest

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #16419 
| Patch: Bug Fix?          | √
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | √
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

I tried representing `undefined` as `null` in `output.json`, but that would cause changes for 5000+ tests.

### CODE REVIEW

File: packages/babel-parser/src/parser/expression.ts [hunk 1]
```diff
@@ -1730,13 +1730,12 @@ export default abstract class ExpressionParser extends LValParser {
     pattern: string;
     flags: N.RegExpLiteral["flags"];
   }) {
-    const node = this.parseLiteral<N.RegExpLiteral>(
-      value.value,
-      "RegExpLiteral",
-    );
+    const node = this.startNode<N.RegExpLiteral>();
+    this.addExtra(node, "raw", this.input.slice(node.start, this.state.end));
```
Comment (liuxingbaoyu) [inline packages/babel-parser/src/parser/expression.ts:1734]: This may also be removed (probably Babel 8)

Comment (nicolo-ribaudo) [reply packages/babel-parser/src/parser/expression.ts:1734]: I would keep it just for consistency with other literals

**Review by nicolo-ribaudo — APPROVED** [review]

**Review by JLHwung — APPROVED** [review]
