### PR TITLE
skip id-destructuring bugfix when binding info is not found

### LINKED ISSUE #13907: [Bug]: Cannot read properties of undefined (reading 'constantViolations')
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```js
//root.jsx

import { observer, inject } from 'mobx-react'
import { AccountRootStore } from 'stores/account/account_root_store'

const AccountsEdit = inject(({ accountRootStore }) => ({
  accountRootStore,
  accountStore: accountRootStore.accountStore,
  currentUser: accountRootStore.currentUser,
  onSubmit: accountRootStore.accountSettingsFormStore.onSubmit,
}))(
  observer(
    class AccountsEdit extends React.PureComponent {
      render() {
        return (
          <div>
          </div>
        )
      }
    },
  ),
)
```

### Configuration file name

babel.config.js

### Configuration

```js
module.exports = function (api) {
  let validEnv = ['development', 'test', 'production']
  let currentEnv = api.env()
  let isDevelopmentEnv = api.env('development')
  let isProductionEnv = api.env('production')
  let isTestEnv = api.env('test')

  if (!validEnv.includes(currentEnv)) {
    throw new Error(
      'Please specify a valid `NODE_ENV` or ' +
        '`BABEL_ENV` environment variables. Valid values are "development", ' +
        '"test", and "production". Instead, received: ' +
        JSON.stringify(currentEnv) +
        '.',
    )
  }

  return {
    presets: [
      isTestEnv && [
        '@babel/preset-env',
        {
          loose: true,
          targets: {
            node: 'current',
          },
        },
      ],
      (isProductionEnv || isDevelopmentEnv) && [
        '@babel/preset-env',
        {
          useBuiltIns: 'entry',
          modules: 'auto',
          bugfixes: true,
          loose: true,
          corejs: '3.19',
          configPath: __dirname + '/package.json',
        },
      ],
      [
        '@babel/preset-react',
        {
          development: isDevelopmentEnv || isTestEnv,
          useBuiltIns: true,
        },
      ],
      ['@babel/preset-typescript', { allExtensions: true, isTSX: true }],
    ].filter(Boolean),
    plugins: [
      process.env.WEBPACK_DEV_SERVER && 'react-refresh/babel',
      '@loadable/babel-plugin',
      'babel-plugin-macros',
      [
        '@babel/plugin-proposal-class-properties',
        {
          loose: true,
        },
      ],
      [
        '@babel/plugin-transform-classes',
        {
          loose: true,
        },
      ],
      isTestEnv && [
        '@babel/plugin-transform-spread',
        {
          loose: true,
        },
      ],
      [
        '@babel/plugin-transform-runtime',
        {
          helpers: false,
        },
      ],
      [
        'babel-plugin-styled-components',
        {
          displayName: !isTestEnv,
          ssr: false,
        },
      ],
      isProductionEnv && [
        'babel-plugin-transform-react-remove-prop-types',
        {
          removeImport: true,
        },
      ],
    ].filter(Boolean),
  }
}

```

### Current and expected behavior

Before update:
```
  System:
    OS: macOS 11.6
  Binaries:
    Node: 17.0.1 - /usr/local/opt/node/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
  npmPackages:
    @babel/core: ^7.15.8 => 7.15.8
    @babel/eslint-parser: ^7.15.8 => 7.15.8
    @babel/plugin-proposal-class-properties: ^7.14.5 => 7.14.5
    @babel/plugin-transform-classes: ^7.15.4 => 7.15.4
    @babel/plugin-transform-runtime: ^7.15.8 => 7.15.8
    @babel/plugin-transform-spread: ^7.15.8 => 7.15.8
    @babel/preset-env: ^7.15.8 => 7.15.8
    @babel/preset-react: ^7.14.5 => 7.14.5
    @babel/preset-typescript: ^7.15.0 => 7.15.0
    @babel/runtime: ^7.15.4 => 7.15.4
    babel-jest: ^27.3.1 => 27.3.1
    babel-plugin-styled-components: ^1.13.3 => 1.13.3
    babel-plugin-transform-react-remove-prop-types: ^0.4.24 => 0.4.24
    eslint: ^7.32.0 => 7.32.0
    jest: ^27.3.1 => 27.3.1
    webpack: ^4.44.2 => 4.46.0
```

All works fine

Behavior after update:
```
ERROR in ./app/javascript/components/accounts/edit/root.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: /Users/pavel/t/main/app/javascript/components/accounts/edit/root.jsx: Cannot read properties of undefined (reading 'constantViolations')
    at shouldTransform (/Users/pavel/t/main/node_modules/@babel/plugin-bugfix-safari-id-destructuring-collision-in-function-expression/lib/index.js:15:47)
    at PluginPass.FunctionExpression (/Users/pavel/t/main/node_modules/@babel/plugin-bugfix-safari-id-destructuring-collision-in-function-expression/lib/index.js:40:22)
    at newFn (/Users/pavel/t/main/node_modules/@babel/traverse/lib/visitors.js:177:21)
    at NodePath._call (/Users/pavel/t/main/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/pavel/t/main/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/pavel/t/main/node_modules/@babel/traverse/lib/path/context.js:100:31)
    at TraversalContext.visitQueue (/Users/pavel/t/main/node_modules/@babel/traverse/lib/context.js:103:16)
    at TraversalContext.visitSingle (/Users/pavel/t/main/node_modules/@babel/traverse/lib/context.js:77:19)
    at TraversalContext.visit (/Users/pavel/t/main/node_modules/@babel/traverse/lib/context.js:131:19)
    at Function.traverse.node (/Users/pavel/t/main/node_modules/@babel/traverse/lib/index.js:82:17)
```

### Environment
```
  System:
    OS: macOS 11.6
  Binaries:
    Node: 17.0.1 - /usr/local/opt/node/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
  npmPackages:
    @babel/core: ^7.16.0 => 7.16.0
    @babel/eslint-parser: ^7.16.0 => 7.16.0
    @babel/plugin-proposal-class-properties: ^7.16.0 => 7.16.0
    @babel/plugin-transform-classes: ^7.16.0 => 7.16.0
    @babel/plugin-transform-runtime: ^7.16.0 => 7.16.0
    @babel/plugin-transform-spread: ^7.16.0 => 7.16.0
    @babel/preset-env: ^7.16.0 => 7.16.0
    @babel/preset-react: ^7.16.0 => 7.16.0
    @babel/preset-typescript: ^7.16.0 => 7.16.0
    @babel/runtime: ^7.16.0 => 7.16.0
    babel-jest: ^27.3.1 => 27.3.1
    babel-plugin-styled-components: ^1.13.3 => 1.13.3
    babel-plugin-transform-react-remove-prop-types: ^0.4.24 => 0.4.24
    eslint: ^7.32.0 => 7.32.0
    jest: ^27.3.1 => 27.3.1
    webpack: ^4.44.2 => 4.46.0
```

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #13907 
| Patch: Bug Fix?          | Y
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

In #13842 we detect the pattern `function a([a]) {}` from the scope info. This PR handles situations when 
1) babel-helper-function-name injects the function id and mark them as `NOT_LOCAL_BINDING`, in this case the id will not be registered as constant violation
2) a plugin injects an id but does not update scope info accordingly

For the plugin to work, the assumption now is that the scope info of function parameters can be trusted: so we can avoid scanning parameters.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/13910"></a>

### CODE REVIEW

**Review by jridgewell — APPROVED** [review]

File: packages/babel-plugin-bugfix-safari-id-destructuring-collision-in-function-expression/src/util.ts [hunk 1]
```diff
@@ -18,16 +18,16 @@ export function shouldTransform(
...
   const paramNameBinding = path.scope.getOwnBinding(name);
-  const constantViolations = paramNameBinding.constantViolations;
-  if (constantViolations.length === 0) {
-    // the function scope has no such collided bindings
+  if (paramNameBinding === undefined) {
+    // Case 1: the function id is injected by babel-helper-name-function, which
+    // assigns `NOT_LOCAL_BINDING` to the `functionId` and thus not registering id
+    // in scope tracking
+    // Case 2: the function id is injected by a third party plugin which does not update the
+    // scope info
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-bugfix-safari-id-destructuring-collision-in-function-expression/src/util.ts:26]: If we are in Case 2, it means that the function didn't originally have a paramter with the same name of the new injected id?

e.g. does this work?
```js
let x = function ([a]) {};
```
```js
// plugin
Function(path) {
  path.node.id = t.identifier("a");
}
```

(if it doesn't it's ok - the plugin needs to be fixed)

Comment (JLHwung) [reply packages/babel-plugin-bugfix-safari-id-destructuring-collision-in-function-expression/src/util.ts:26]: Yeah it works if the `path` is then requeued (as is shown in the https://github.com/babel/babel/pull/13910/files#diff-9c3e0b47cab12356380982d8d3c8b5c3bbf3e160e18448619c2b54e9106bcb03) so that the bugfix can have a chance to be executed again.

**Review by nicolo-ribaudo — APPROVED** [review]
