### PR TITLE
Register binding when transforming TSParameterProperty

### LINKED ISSUE #11061: wrong js code when using ts constructor assignment
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**
If a module imported from TypeScript has the same name as a constructor parameter, a bug occurs.

**Input Code**
- REPL or Repo link if applicable: 
  - [babeljs repl](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAbziApgZzQQwObAHbZwC-cAZlBCHAOSnBQoBGmaKAtJgCYj7UBQfFAA9IsOAGMANizRwAypRQwAFvkII-cCRDxoYUAK7iY0ABSa4ASDAHGk4OOTosuAgC4nGHGoB0AWWdvAgsASkQLIj5IoA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=typescript%2Cenv&prettier=false&targets=Node-8.9&version=7.8.3&externalPlugins=)
  - [typescript repl](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=3&pc=1#code/JYWwDg9gTgLgBAbziApgZzQQwObAHbZwC+cAZlBCHAOSnBQoBGmaKAtJgCYj7UBQfFAA9IsOAGMANizRwAypRQwAFvkII+cCRDxoYUAK7iY0ABSa4ASDAHGk4OOTosuAgC4nGHGoB0AWWdvAgsASkQLIj5IoA)

```ts
import { messaging } from 'firebase-admin'

export class Something {
  constructor(
  	public messaging: messaging.Messaging
  ) {
  }
}
```

**Expected behavior/code**

Expected,

```js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.Something = void 0;

class Something {
  constructor(messaging) {
    this.messaging = messaging;
  }

}

exports.Something = Something;
```

But actual,

```js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.Something = void 0;

var _firebaseAdmin = require("firebase-admin");

class Something {
  constructor(_firebaseAdmin.messaging) { // Whoops!
    this.messaging = messaging;
  }

}

exports.Something = Something;
```

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `.babelrc`

```json
{
  "presets": [
    ["@babel/env", {
      "targets": "maintained node versions",
      "useBuiltIns": "usage",
      "corejs": 3
    }],
    "@babel/typescript"
  ]
}
```

**Environment**

```
  System:
    OS: macOS 10.15.2
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
  npmPackages:
    @babel/cli: ^7.8.3 => 7.8.3
    @babel/core: ^7.8.3 => 7.8.3
    @babel/plugin-proposal-class-properties: ^7.8.3 => 7.8.3
    @babel/plugin-proposal-decorators: ^7.8.3 => 7.8.3
    @babel/plugin-proposal-object-rest-spread: ^7.8.3 => 7.8.3
    @babel/plugin-proposal-optional-chaining: ^7.8.3 => 7.8.3
    @babel/preset-env: ^7.8.3 => 7.8.3
    @babel/preset-typescript: ^7.8.3 => 7.8.3
    eslint: ^6.2.2 => 6.2.2
    jest: ^24.9.0 => 24.9.0
```

- Babel version(s): 7.8.3
- Node/npm version: node 10.16.3 / npm 6.9.0
- OS: macOS 10.15.2
- Monorepo: no
- How you are using Babel: cli

**Possible Solution**

**Additional context/Screenshots**
.

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #11061 
| Patch: Bug Fix?          | Y
| Tests Added + Pass?      | Yes
| License                  | MIT

Although the issue #11061 is triggered from https://github.com/babel/babel/blob/c22e72eb24b9dd83d43e693067d9c856acf9977d/packages/babel-helper-module-transforms/src/rewrite-live-references.js#L180-L187

where both the local binding and root binding of `message` is `undefined` and therefore replaced by `firebaseAdmin.messging`, it should be fixed in `transform-typescript` when we transform `TSParameterProperty` to general function parameters.

I don't think the root binding of `message` should be `undefined`, too. But I prefer to fix that in another PR.

### CODE REVIEW

File: packages/babel-helper-module-transforms/src/rewrite-live-references.js [hunk 1]
```diff
@@ -177,14 +177,14 @@ const rewriteReferencesVisitor = {
...
-    // redeclared in this scope
-    if (rootBinding !== localBinding) return;
-
     const importData = imported.get(localName);
     if (importData) {
+      const localBinding = path.scope.getBinding(localName);
+      const rootBinding = scope.getBinding(localName);
+
+      // redeclared in this scope
+      if (rootBinding !== localBinding) return;
```
Comment (nicolo-ribaudo) [inline packages/babel-helper-module-transforms/src/rewrite-live-references.js:186]: Why did you need to move this?

**Review by nicolo-ribaudo — APPROVED** [review]

**Review by hzoo — APPROVED** [review]
