### PR TITLE
fix: Throw error when compiling `super()` in arrow functions with default / rest parameters

### LINKED ISSUE #15148: [Bug]: Super call in arrow function causing infinite recursion
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
class Bar extends Foo {
    constructor() {
        let f = (...args) => super(...args);
        f();
    }
}
```

[Example on Babel REPL](https://babeljs.io/repl/#?browsers=since%202017&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=MYGwhgzhAEBCYCdoFMAeAXZA7AJjAYgPaHQDeAUNFdMIVhOggK7DqEIAUAlGZdfyGTpoAM2gBeaBwB0sxAHMIPcQD5oEJgAdknWdIVKA3H35UR3Y_wC-5G0A&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.20.2&externalPlugins=&assumptions=%7B%7D)

### Configuration file name

.babelrc

### Configuration

```json
{
    "presets": [["@babel/preset-env", { "bugfixes": true }]],
    "targets": ["since 2017"]
}
```

##### Current behavior (silently success and causing infinite recursion)
```js
"use strict";

class Bar extends Foo {
  constructor() {
    var _supercall = function _supercall() {
      return _supercall(...arguments);
    };
    let f = function f() {
      return _supercall(...arguments);
    };
    f();
  }
}
```

##### Expected behavior
- Give ~~warning or~~ error in this situation;
- ~~Or just keep the arrow function;~~
- ~~Or transpile the whole class into pre-ES6 style (just like the result of using [`since 2016`](https://babeljs.io/repl/#?browsers=since%202016&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=MYGwhgzhAEBCYCdoFMAeAXZA7AJjAYgPaHQDeAUNFdMIVhOggK7DqEIAUAlGZdfyGTpoAM2gBeaBwB0sxAHMIPcQD5oEJgAdknWdIVKA3H35UR3Y_wC-5G0A&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.20.2&externalPlugins=&assumptions=%7B%7D)).~~

### Environment

- Babel version: v7.20.2
- Node: v16.17.0
- pnpm version: pnpm 7.14.2
- OS: Windows 10
- Monorepo: no

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by SuperSodaSea**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #15148
| Patch: Bug Fix?          | :+1:
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

In `@babel/plugin-transform-parameters`, compiling `super()` in arrow functions with default or rest parameters without compiling classes will generate code with infinite recursion. Check and throw error in this situation.

#### Tests

- babel-plugin-transform-arrow-functions/test/fixtures/arrow-functions/super-call
- babel-plugin-transform-arrow-functions/test/fixtures/arrow-functions/super-prop
- babel-plugin-transform-parameters/test/fixtures/parameters/arrow-default-super-no-classes-plugin
- babel-plugin-transform-parameters/test/fixtures/parameters/arrow-rest-super-no-classes-plugin

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15163"></a>

### CODE REVIEW

File: packages/babel-plugin-transform-parameters/test/fixtures/parameters/arrow-rest-super-no-classes-plugin/input.js [hunk 1]
```diff
@@ -0,0 +1,6 @@
+class Bar extends Foo {
+    constructor() {
+        let f = (...args) => super(...args);
```
Comment (JLHwung) [inline packages/babel-plugin-transform-parameters/test/fixtures/parameters/arrow-rest-super-no-classes-plugin/input.js:3]: Note that the input here is very similar to how we would transform `super()`:

https://github.com/babel/babel/blob/9862d4273d12383b14934a1b1ec8424f1d3a00f9/packages/babel-traverse/test/arrow-transform.js#L53-L71

My gut is that it should have been fixed in how we generate the super call:

https://github.com/babel/babel/blob/9862d4273d12383b14934a1b1ec8424f1d3a00f9/packages/babel-traverse/src/path/conversion.ts#L652

We already have an arrow function check when constructing `supercall`, 

https://github.com/babel/babel/blob/9862d4273d12383b14934a1b1ec8424f1d3a00f9/packages/babel-traverse/src/path/conversion.ts#L287-L291

somehow it does not throw, probably because `allowInsertArrow` is not properly passed.

File: packages/babel-plugin-transform-parameters/test/fixtures/parameters/arrow-rest-super-no-classes-plugin/options.json [hunk 2]
```diff
@@ -0,0 +1,4 @@
+{
+    "plugins": ["transform-parameters"],
+    "throws": "It's not possible to compile `super()` in an arrow function with default or rest parameters without compiling classes.\nPlease add '@babel/plugin-transform-classes' to your Babel configuration."
```
Comment (JLHwung) [inline packages/babel-plugin-transform-parameters/test/fixtures/parameters/arrow-rest-super-no-classes-plugin/options.json:3]: This error message is way better than `Unable to handle nested super() usage in arrow`, we can improve that message if we figure out how to make that work.

**Review by JLHwung — COMMENTED** [review]
I think we can avoid the extra traversal if we fix this issue in the arrow conversion.

File: packages/babel-plugin-transform-parameters/test/fixtures/parameters/arrow-rest-super-no-classes-plugin/input.js (hunk 1 above)
Comment (SuperSodaSea) [reply packages/babel-plugin-transform-parameters/test/fixtures/parameters/arrow-rest-super-no-classes-plugin/input.js:3]: Perhaps we can add `allowInsertArrow: true` here?

https://github.com/babel/babel/blob/073b3b0536812bac7bb9d5d6363adef1dd174d07/packages/babel-plugin-transform-parameters/src/index.ts#L48-L49

Comment (SuperSodaSea) [reply packages/babel-plugin-transform-parameters/test/fixtures/parameters/arrow-rest-super-no-classes-plugin/input.js:3]: I tried to add `allowInsertArrow: false` and it fails on #13939 related tests...:thinking:
Maybe we need something like `allowInsertArrowWithRest`?

```
    × 13939
    × 13939 complex
    × 13939 private
    × 13939 private complex

SyntaxError: babel/packages/babel-plugin-transform-parameters/test/fixtures/regression/13939/input.js: Unable to transform arrow inside class property
      1 | class A {
    > 2 |   handle = (x = 0) => {
        |            ^
      3 |     console.log(x);
      4 |   };
      5 | }

...
```

File: packages/babel-traverse/src/path/conversion.ts [hunk 3]
```diff
@@ -286,7 +290,17 @@ function hoistFunctionEnvironment(
...
     if (!allowInsertArrow) {
       throw superCalls[0].buildCodeFrameError(
-        "Unable to handle nested super() usage in arrow",
+        "When using '@babel/plugin-transform-arrow-functions', " +
+          "it's not possible to compile `super()` in an arrow function without compiling classes.\n" +
+          "Please add '@babel/plugin-transform-classes' to your Babel configuration.",
+      );
+    }
+    if (!allowInsertArrowWithRest) {
+      // NOTE: This may happen in `@babel/preset-env` with target `since 2017`, or in the default setting of `create-react-app`.
```
Comment (JLHwung) [inline packages/babel-traverse/src/path/conversion.ts:299]:
```suggestion
      // preset-env with target `since 2017` enables `transform-parameters` without `transform-classes`.
```
The `create-react-app`'s default will evolve, while the target `since 2017` is almost fixed.

**Review by JLHwung — APPROVED** [review]
Thanks!

**Review by liuxingbaoyu — APPROVED** [review]

**Comment by AntiMoron** [comment]
666
