### PR TITLE
fix(ts): allow trailing comma after rest parameter in `TSDeclareFunction`

### LINKED ISSUE #13100: TypeScript: trailing commas after rest parameters in ambient contexts
## Bug Report

**Current behavior**

Currently, Babel throws an unrecoverable syntax error whenever it finds a trailing comma after a rest parameter, however TypeScript allows such commas in ambient contexts (in declarations marked with `declare` or in `.d.ts` files).

- [Babel REPL](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=CYUwxgNghgTiAEAzArgOzAFwJYHtVJxwAoA6M2AcwGcAueKVATwG0BdAGgEo6HGBuAFADQkWAlFUq8AEKx4AbwHxlBYmRKVa9Jmy48mAgL5CR0OPCyoMIGIihgEsgF4KlKxIVLkY1fSw7c2oxGJuBmCBiMAA4IAIrwALzwXho-Wry6nIkAfEFAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=typescript&prettier=false&targets=&version=7.13.14&externalPlugins=), [TS Playground](https://www.typescriptlang.org/play?ts=4.2.3#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVJxwAoA6M2AcwGcAueKVATwG0BdAGgEo6HGBuALAAoYaEiwE4qlXgAhWPADew+KoLEyJSrXpM2XHk2EBfYaPDQ48LKgwgYiKGATyAXkpVrEhUuRjVDFg5uXUYTMyExSwQMRgAHBABFeABeeF8tfx1efU5UgD5QoA)

**Input Code**

```ts
// in a .ts file
declare function foo(...args: any[],): any;

declare class Bar {
    foo(...args: any[],): any
}

declare interface Baz {
    foo(...args: any[],): any
}

declare type Q = (...args: any[],) => any

// in a .d.ts file
function foo(...args: any[],): any;

class Bar {
    foo(...args: any[],): any
}

interface Baz {
    foo(...args: any[],): any
}

type Q = (...args: any[],) => any
```

**Expected behavior**

No error

**Environment**

- Babel version(s): v7.13.14

### PR DESCRIPTION
**Pull request by fedeci**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #13100  
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

If in declare context we can allow a comma after a function rest parameter.

### CODE REVIEW

File: packages/babel-parser/src/plugins/typescript/index.js [hunk 1]
```diff
@@ -2779,6 +2779,20 @@ export default (superClass: Class<Parser>): Class<Parser> =>
       return super.parseMaybeDecoratorArguments(expr);
     }
 
+    checkCommaAfterRest(close) {
+      if (this.match(tt.comma)) {
+        if (this.lookaheadCharCode() === close) {
+          if (!this.state.isDeclareContext) {
```
Comment (thorn0) [inline packages/babel-parser/src/plugins/typescript/index.js:2785]: Is this condition true in `d.ts` files?

Comment (fedeci) [reply packages/babel-parser/src/plugins/typescript/index.js:2785]: It is true if there is the `declare` keyword before the function declaration.

Comment (thorn0) [reply packages/babel-parser/src/plugins/typescript/index.js:2785]: In that case this PR doesn't fully fix #13100

Comment (nicolo-ribaudo) [reply packages/babel-parser/src/plugins/typescript/index.js:2785]: We don't have a separate parsing goal for `.d.ts` files I think, since any code that is valid in `.d.ts` files was valid in normal `.ts` files.

Comment (nicolo-ribaudo) [reply packages/babel-parser/src/plugins/typescript/index.js:2785]: (Q: Do you know if I can use the `.d.ts` parse goal on the TS playground?)

Comment (fedeci) [reply packages/babel-parser/src/plugins/typescript/index.js:2785]: The problem is that
`function foo(...args: any[], )` (without the body) is invalid in `.ts` files even if it is only a type definition.

Comment (thorn0) [reply packages/babel-parser/src/plugins/typescript/index.js:2785]: > any code that is valid in .d.ts files was valid in normal .ts

```ts
class Foo {
    foo(): any;
}
```
is invalid in `.ts` unless it's nested in `declare namespace`.

As for `function foo(...args: any[], )` without the body, it can be used for two different things:

1) for [overloads](https://www.typescriptlang.org/docs/handbook/2/functions.html#function-overloads)
2) for type-only declarations (inside `declare namespace`, `declare global`, `declare module "name" { ... }`, and probably something else)

In the first case, the rest parameter trailing comma isn't allowed. In the latter, it's allowed as it's an "ambient context".

Comment (thorn0) [reply packages/babel-parser/src/plugins/typescript/index.js:2785]: > Do you know if I can use the .d.ts parse goal on the TS playground

I believe if you wrap you code e.g. in `declare module 'foo' { ... }`, it'll be the same.

Comment (nicolo-ribaudo) [reply packages/babel-parser/src/plugins/typescript/index.js:2785]: I think we can start by fixing the "easy" case (which is what this PR does), but we'll eventually need to add a `{ dts: boolean }` option to the typescript parser plugin.

Comment (thorn0) [reply packages/babel-parser/src/plugins/typescript/index.js:2785]: From Prettier's perspective, making the error recoverable would suffice.

Comment (sosukesuzuki) [reply packages/babel-parser/src/plugins/typescript/index.js:2785]: I've created a new issue so we don't forget #13108

File: packages/babel-parser/src/plugins/typescript/index.js [hunk 2]
```diff
@@ -2779,6 +2779,20 @@ export default (superClass: Class<Parser>): Class<Parser> =>
...
+            this.raiseTrailingCommaAfterRest(this.state.start);
+            return;
```
Comment (sosukesuzuki) [inline packages/babel-parser/src/plugins/typescript/index.js:2787]:
```suggestion
```
this `return` should be removed to parse codes like below:
```ts
function foo(...args: any[], ): any;
```

File: packages/babel-parser/src/plugins/typescript/index.js [hunk 3]
```diff
@@ -2779,6 +2779,20 @@ export default (superClass: Class<Parser>): Class<Parser> =>
...
+          }
+          this.eat(tt.comma);
+        } else {
+          this.raiseRestNotLast(this.state.start);
```
Comment (sosukesuzuki) [inline packages/babel-parser/src/plugins/typescript/index.js:2791]: It is need to add tests to check raising this error.

Comment (fedeci) [reply packages/babel-parser/src/plugins/typescript/index.js:2791]: This method is inherited from here adding some adjustments:
https://github.com/babel/babel/blob/7bc72bb451e71d7d8964efdf4438d5a907aae655/packages/babel-parser/src/parser/lval.js#L526-L535
That branch is already tested in "ES" parser, I don't know if it is necessary to repeat those.

Comment (nicolo-ribaudo) [reply packages/babel-parser/src/plugins/typescript/index.js:2790]: Then I'd prefer to do something like this rather than copy-pasting the code:

```js
checkCommaAfterRest(close) {
  if (
    this.state.isDeclareContext &&
    this.match(tt.comma) &&
    this.lookaheadCharCode() === close
  ) {
    this.next(); // tt.comma
  } else {
    super.checkCommaAfterRest(close);
  }
}
```

by doing so, if we'll make any change to `checkCommaAfterRest` we don't risk forgetting to also update this second implementation.

Comment (fedeci) [reply packages/babel-parser/src/plugins/typescript/index.js:2790]: Don't we risk to call twice `lookaheadCharCode` doing so?

**Review by nicolo-ribaudo — APPROVED** [review]

**Review by hzoo — APPROVED** [review]

File: packages/babel-parser/src/plugins/typescript/index.js (hunk 3 above)
Comment (hzoo) [reply packages/babel-parser/src/plugins/typescript/index.js]: Just thinking, maybe we can add some parser contributing.md section (or somewhere) mentioning that for plugins (TS/Flow) we would prefer overwritten methods to use super? Not sure if that's worth making a lint thing either though

**Review by sosukesuzuki — APPROVED** [review]

File: packages/babel-parser/src/plugins/typescript/index.js (hunk 3 above)
Comment (nicolo-ribaudo) [reply packages/babel-parser/src/plugins/typescript/index.js]: > Not sure if that's worth making a lint thing either though

It's hard to do so, because we need to know which methods shadow methods on the superclass. Maybe it's doable with tslint, but not with eslint.

Comment (thorn0) [reply packages/babel-parser/src/plugins/typescript/index.js]: It's doable with this https://devblogs.microsoft.com/typescript/announcing-typescript-4-3-beta/#override-and-the-noimplicitoverride-flag

Comment (hzoo) [reply packages/babel-parser/src/plugins/typescript/index.js]: Ah yeah I was thinking of a simple heuristic of methods that don't start with `ts` since it seems we do that? Not a big deal
