### PR TITLE
[estree] attach comments after directives at the end of file

### LINKED ISSUE #14919: [Bug]: ESTree plugin can stop comments from being attached to directives
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
"use strict";

/** @external foo */
```

### Configuration file name

_No response_

### Configuration

```json
{
  "plugins": ["estree"]
}
```

### Current and expected behavior

**Current behavior**

If a source file contains 1) a directive, followed by 2) a comment, and nothing else, and the ESTree plugin is enabled, then `@babel/parser` does not attach the comment to any AST node.

<details>
<summary>Current AST</summary>

```json
{
  "type": "File",
  "start": 0,
  "end": 36,
  "loc": {
    "start": {
      "line": 1,
      "column": 0
    },
    "end": {
      "line": 4,
      "column": 0
    }
  },
  "range": [
    0,
    36
  ],
  "errors": [],
  "program": {
    "type": "Program",
    "start": 0,
    "end": 36,
    "loc": {
      "start": {
        "line": 1,
        "column": 0
      },
      "end": {
        "line": 4,
        "column": 0
      }
    },
    "range": [
      0,
      36
    ],
    "sourceType": "script",
    "interpreter": null,
    "body": [
      {
        "type": "ExpressionStatement",
        "start": 0,
        "end": 13,
        "loc": {
          "start": {
            "line": 1,
            "column": 0
          },
          "end": {
            "line": 1,
            "column": 13
          }
        },
        "range": [
          0,
          13
        ],
        "expression": {
          "type": "Literal",
          "start": 0,
          "end": 12,
          "loc": {
            "start": {
              "line": 1,
              "column": 0
            },
            "end": {
              "line": 1,
              "column": 12
            }
          },
          "range": [
            0,
            12
          ],
          "value": "use strict",
          "raw": "'use strict'"
        },
        "directive": "use strict"
      }
    ]
  },
  "comments": [
    {
      "type": "CommentBlock",
      "value": "* @external foo ",
      "start": 15,
      "end": 35,
      "loc": {
        "start": {
          "line": 3,
          "column": 0,
          "index": 15
        },
        "end": {
          "line": 3,
          "column": 20,
          "index": 35
        }
      }
    }
  ]
}
```
</details>

**Expected behavior**

`@babel/parser` attaches the comment to the `ExpressionStatement` node for the directive as a trailing comment.

<details>
<summary>Expected AST</summary>

```json
{
  "type": "File",
  "start": 0,
  "end": 36,
  "loc": {
    "start": {
      "line": 1,
      "column": 0
    },
    "end": {
      "line": 4,
      "column": 0
    }
  },
  "range": [
    0,
    36
  ],
  "errors": [],
  "program": {
    "type": "Program",
    "start": 0,
    "end": 36,
    "loc": {
      "start": {
        "line": 1,
        "column": 0
      },
      "end": {
        "line": 4,
        "column": 0
      }
    },
    "range": [
      0,
      36
    ],
    "sourceType": "script",
    "interpreter": null,
    "body": [
      {
        "type": "ExpressionStatement",
        "start": 0,
        "end": 13,
        "loc": {
          "start": {
            "line": 1,
            "column": 0
          },
          "end": {
            "line": 1,
            "column": 13
          }
        },
        "range": [
          0,
          13
        ],
        "trailingComments": [
          {
            "type": "CommentBlock",
            "value": "* @external foo ",
            "start": 15,
            "end": 35,
            "loc": {
              "start": {
                "line": 3,
                "column": 0,
                "index": 15
              },
              "end": {
                "line": 3,
                "column": 20,
                "index": 35
              }
            }
          }
        ],
        "expression": {
          "type": "Literal",
          "start": 0,
          "end": 12,
          "loc": {
            "start": {
              "line": 1,
              "column": 0
            },
            "end": {
              "line": 1,
              "column": 12
            }
          },
          "range": [
            0,
            12
          ],
          "value": "use strict",
          "raw": "'use strict'"
        },
        "directive": "use strict"
      }
    ]
  },
  "comments": [
    {
      "type": "CommentBlock",
      "value": "* @external foo ",
      "start": 15,
      "end": 35,
      "loc": {
        "start": {
          "line": 3,
          "column": 0,
          "index": 15
        },
        "end": {
          "line": 3,
          "column": 20,
          "index": 35
        }
      }
    }
  ]
}
```
</details>

### Environment

- Babel version: 7.19.0
- Node version: 18.8.0
- npm version: 8.18.0
- OS: macOS 12.0.1
- Monorepo: yes

### Possible solution

Pull request coming shortly.

### Additional context

This issue is a regression introduced by babel/babel#13521, which rewrote the comment-attachment code.

### PR DESCRIPTION
**Pull request by hegemonic**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #14919 
| Patch: Bug Fix?          | yes
| Major: Breaking Change?  | no
| Minor: New Feature?      | no
| Tests Added + Pass?      | Yes
| Documentation PR Link    | n/a
| Any Dependency Changes?  | no
| License                  | MIT

If a source file contains 1) a directive, followed by 2) a comment, and nothing else, then `@babel/parser` attaches the comment to the `Directive` node as a trailing comment.

The ESTree plugin handles `Directive` nodes by creating an `ExpressionStatement` node, then transferring information from the `Directive` node to the `ExpressionStatement` node. Previously, at the time it transfers information, comments hadn't yet been attached to the `Directive` node. And even if they had been, the ESTree plugin didn't do anything with comments attached to the `Directive` node. As a result, the source file's comment wasn't attached to any node in the resulting AST.

With this change, the ESTree plugin generates an AST in which the comment is attached to the `ExpressionStatement` node as a trailing comment.

Fixes #14919.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14920"></a>

### CODE REVIEW

**Review by JLHwung — COMMENTED** [review]
Can you add a new test case with `estree` plugin enabled?

```js
// 1;
"use strict";
// 2;
"use strict";
```

The comment `1` should be the leading comment of the first ExpressionStatement, and `2` should be the trailing comment of the first ExpressionStatement and the leading comment of the second ExpressionStatement.

File: packages/babel-parser/src/plugins/estree.ts [hunk 1]
```diff
@@ -175,6 +178,9 @@ export default (superClass: typeof Parser) =>
         end,
         afterBlockParse,
       );
+      if (node.directives.length) {
+        this.processComment(node);
```
Comment (JLHwung) [inline packages/babel-parser/src/plugins/estree.ts:182]: Currently `processComment` is only called in `finishNodeAt`. Here we call it before the `node` is finished so that `directiveToStmt` can manipulate the attached comments, _as if_ the `node` had been finished. And we are creating new AST nodes within `directiveToStmt`, I am worried that it will break the invariance assumed by the comment attaching algorithm elsewhere.

The reason of #14919 is that we are discarding the created AST nodes `Directive` and `DirectiveLiteral` and then creating new AST nodes to replace them. But the link from comment whitespaces to their leading nodes / trailing nodes are not updated, because at that point the tokenizer has moved _after_ the directives, and the comment processor is awaiting Program/Block to be finished so that the comment can be attached, assuming we are not manipulating the AST nodes ended before current position. So eventually the comment are attached to an unused AST node `Directive`, which is not in the final AST.

We can solve this issue by reusing the created AST node, specifically in
https://github.com/babel/babel/blob/4b7047dddcb09a93bc540cd48f461a8d503ce260/packages/babel-parser/src/plugins/estree.ts#L98

we can cast Directive to ExpressionStatement and DirectiveLiteral to Literal, update the AST shapes accordingly, essentially reverting what we did in the base parser:

https://github.com/babel/babel/blob/4b7047dddcb09a93bc540cd48f461a8d503ce260/packages/babel-parser/src/parser/statement.ts#L237

In this way the comment attaching should work for the ESTree directive representation.

Comment (hegemonic) [reply packages/babel-parser/src/plugins/estree.ts:164]: Many thanks for the detailed explanation, and for the pointer to `stmtToDirective()`! That saved me a ton of time.

Hopefully the revised code is in better shape.

**Comment by hegemonic** [comment]
The `babel-old-version` check is failing, but I don't think this pull request caused it to fail. If you disagree, please let me know.

**Comment by liuxingbaoyu** [comment]
Yes, the CI failure has nothing to do with this PR.

**Review by liuxingbaoyu — APPROVED** [review]

**Review by liuxingbaoyu — APPROVED** [review]

**Review by nicolo-ribaudo — APPROVED** [review]

**Review by JLHwung — APPROVED** [review]
