### PR TITLE
Fix: inputSourceMap should work when it is an external file

### LINKED ISSUE #10534: Input source maps are ignored in v7.6.0 and up
## Bug Report

**Current Behavior**
Babel ignores input source maps.

**Input Code**
https://github.com/dkamyshov/babel-input-source-map-reproduction

- run `yarn`, you should see `{"version":3,"sources":["../lib-tmp/index.js"],...` in the console - **this is incorrect**

- run `yarn add -D @babel/core@7.5.5`. you should see `{"version":3,"sources":["../src/index.tsx"],...` - this is correct

**Expected behavior/code**
Babel should consume input source maps and reference original source files in the resulting source maps.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "sourceMaps": true,
  "inputSourceMap": true,
  "presets": ["@babel/preset-env"]
}
```

```
babel lib-tmp --out-dir lib --extensions .js --source-maps
```

**Environment**
- Babel version(s): 7.6.3 (@babel/core 7.6.3)
- Node/npm version: v10.16.0, 6.9.0
- OS: OSX 10.14.6
- Monorepo: no
- How you are using Babel: cli

**Possible Solution**
Downgrade to v7.5.5 or earlier.

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #10534 
| Patch: Bug Fix?          | Yes
| Tests Added + Pass?      | Yes
| License                  | MIT

This PR fixes invalid `fromMapFileComment` call signature via prepending parsed comment text by `//`, which is [required in `convert-source-map`](https://github.com/thlorenz/convert-source-map/blob/ad25a3e4373c641a2241cf1470b81ae123e4c23d/index.js#L15).

This PR is a follow up to #9960.

### CODE REVIEW

File: packages/babel-core/test/fixtures/transformation/source-maps/input-source-map-external/input.js [hunk 1]
```diff
@@ -0,0 +1,5 @@
+var foo = function () {
+  return 4;
+};
+
+//# sourceMappingURL=input.js.map
```
Comment (JLHwung) [inline packages/babel-core/test/fixtures/transformation/source-maps/input-source-map-external/input.js]: The test case is copied and later transformed from `packages/babel-core/test/fixtures/transformation/source-maps/input-source-map`.
