### PR TITLE
Memoize call expressions in optional chains in loose mode

### LINKED ISSUE #11084: [plugin-proposal-optional-chaining] Loose mode produces unoptimized code for class methods
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**
The `loose` mode of `optional-chaining` plugin compiles class methods in non-optimized way repeating the call to the method instead of remembering its result.

It does not happen for function call though.

**Input Code**
- REPL or Repo link if applicable: [Runkit](https://runkit.com/lodin/optional-chaining-repeating-call-to-object-method).

```js
a.get(b)?.();
```
compiles to:
```js
a.get(b) == null ? void 0 : a.get(b)();
```

**Expected behavior/code**
The result of method call should be memoized as it happens in the strict mode.

```js
var a$get;

(a$get = a.get(b)) == null ? void 0 : a$get();
```

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
    plugins: [[require('@babel/plugin-proposal-optional-chaining'), {loose: true}]]
}
```

**Environment**

- Babel version(s): 7.8.4
- Node/npm version: v13.5.0/6.13.4
- OS: Windows 10
- Monorepo: Lerna
- How you are using Babel: cli/programmatically

### PR DESCRIPTION
**Pull request by oliverdunk**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #11084  
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  | No
| License                  | MIT

Previously, in loose mode, we weren't memoizing optional call expressions. This resulted in code like `a.get(b)?.();` being compiled to `a.get(b) == null ? void 0 : a.get(b)();`, which repeats a function call.

This MR changes the behaviour so that memoization is only skipped when no work is done by the call's callee.

### CODE REVIEW

File: packages/babel-plugin-proposal-optional-chaining/src/index.js [hunk 1]
```diff
@@ -50,9 +59,10 @@ export default declare((api, options) => {
 
           let ref;
           let check;
-          if (loose && isCall) {
+          if (loose && isCall && isSimpleMemberExpression(node.callee)) {
```
Comment (jridgewell) [inline packages/babel-plugin-proposal-optional-chaining/src/index.js]: I think this can be as simple as `!t.isCallExpression(chain)` and still get the same behavior.

Note, `chain` is just a local variable for `node.callee`.

Comment (jridgewell) [inline packages/babel-plugin-proposal-optional-chaining/src/index.js]: Nit:
```suggestion
          if (loose && isCall && isSimpleMemberExpression(chain)) {
```

Comment (oliverdunk) [reply packages/babel-plugin-proposal-optional-chaining/src/index.js]: Easy change, done!

**Comment by oliverdunk** [comment]
@jridgewell Please ignore that request for review. I need to make sure we're probably setting the call context.

**Comment by oliverdunk** [comment]
@jridgewell Found and fixed my bug! It would be great if you could take a look :)

File: packages/babel-plugin-proposal-optional-chaining/src/index.js [hunk 2]
```diff
@@ -72,12 +83,12 @@ export default declare((api, options) => {
 
           // Ensure call expressions have the proper `this`
           // `foo.bar()` has context `foo`.
-          if (isCall && t.isMemberExpression(chain)) {
```
Comment (jridgewell) [inline packages/babel-plugin-proposal-optional-chaining/src/index.js]: We'll still need this.

File: packages/babel-plugin-proposal-optional-chaining/src/index.js [hunk 3]
```diff
@@ -72,12 +83,12 @@ export default declare((api, options) => {
...
-            if (loose) {
+          if (isCall) {
+            if (loose && isSimpleMemberExpression(chain)) {
               // To avoid a Function#call, we can instead re-grab the property from the context object.
               // `a.?b.?()` translates roughly to `_a.b != null && _a.b()`
               node.callee = chain;
-            } else {
+            } else if (chain.object) {
```
Comment (jridgewell) [inline packages/babel-plugin-proposal-optional-chaining/src/index.js]: With the above change, we'll be able to revert this.

File: packages/babel-plugin-proposal-optional-chaining/src/index.js (hunk 2 above)
Comment (oliverdunk) [reply packages/babel-plugin-proposal-optional-chaining/src/index.js]: Ah, I was wondering why the chain.object wasn't needed before. Do you think isMemberExpression is a bit too specific? Shouldn't we allow optional member expressions too?

Comment (jridgewell) [reply packages/babel-plugin-proposal-optional-chaining/src/index.js]: Any optional members will have been converted to regular members by https://github.com/babel/babel/blob/d4d6ec8f2b8ebfb32381a1e8dcadbadec3ae5736/packages/babel-plugin-proposal-optional-chaining/src/index.js#L41

**Comment by oliverdunk** [comment]
@jridgewell I've addressed your feedback again. Really appreciate all of the help! It's early days when it comes to my understanding of Babel - but you and Nico have been incredibly welcoming.

**Comment by nicolo-ribaudo** [comment]
Thanks Oliver!
