### PR TITLE
fix: Avoid internally generating negative source maps columns

### LINKED ISSUE #15712: [Bug]: not working after upgrade to 7.22.5
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

After upgrading Angular from 16.0.4 to 16.1.1 (which increased version of babel from 7.21.4 to 7.22.5) application will not compile anymore.

Minimal reproduction for non working version
`git clone https://github.com/kukjevov/ng-universal-demo`
`cd ng-universal-demo`
`git checkout 2.0`
`npm install --legacy-peer-deps`
`npm run build`

Minimal reproduction for working version
`git clone https://github.com/kukjevov/ng-universal-demo`
`cd ng-universal-demo`
`git checkout 1.0`
`npm install --legacy-peer-deps`
`npm run build`

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

Error received
ERROR in ./node_modules/@anglr/notifications/es2020/src/components/notificationMessage/notificationMessage.component.js
Error: D:\git\universal-demo\node_modules\@anglr\notifications\es2020\src\components\notificationMessage\notificationMessage.component.js: `column` must be greater than or equal to 0 (columns start at column 0)
    at exports.originalPositionFor (D:\git\universal-demo\node_modules\@jridgewell\trace-mapping\dist\trace-mapping.umd.js:402:23)
    at SourceMap.mark (D:\git\universal-demo\node_modules\@babel\generator\lib\source-map.js:57:65)
    at Buffer._mark (D:\git\universal-demo\node_modules\@babel\generator\lib\buffer.js:191:60)
    at Buffer._appendChar (D:\git\universal-demo\node_modules\@babel\generator\lib\buffer.js:135:12)
    at Buffer.appendChar (D:\git\universal-demo\node_modules\@babel\generator\lib\buffer.js:104:10)
    at Generator._appendChar (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:205:15)
    at Generator.tokenChar (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:126:10)
    at Generator.rightParens (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:81:10)
    at Generator.CallExpression (D:\git\universal-demo\node_modules\@babel\generator\lib\generators\expressions.js:196:8)
    at Buffer.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\buffer.js:249:5)
    at Generator.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:163:15)
    at Generator.print (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.ExpressionStatement (D:\git\universal-demo\node_modules\@babel\generator\lib\generators\expressions.js:227:8)
    at Generator.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:159:7)
    at Generator.print (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.printJoin (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:404:12)
    at Generator.printSequence (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:476:10)
    at Generator.BlockStatement (D:\git\universal-demo\node_modules\@babel\generator\lib\generators\base.js:51:8)
    at Generator.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:159:7)
    at Generator.print (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.printAndIndentOnComments (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:423:10)
    at Generator.IfStatement (D:\git\universal-demo\node_modules\@babel\generator\lib\generators\statements.js:52:8)
    at Generator.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:159:7)
    at Generator.print (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.printJoin (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:404:12)
    at Generator.printSequence (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:476:10)
    at Generator.BlockStatement (D:\git\universal-demo\node_modules\@babel\generator\lib\generators\base.js:51:8)
    at Generator.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:159:7)
    at Generator.print (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.FunctionExpression (D:\git\universal-demo\node_modules\@babel\generator\lib\generators\methods.js:109:8)
    at Generator.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:159:7)
    at Generator.print (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.ObjectProperty (D:\git\universal-demo\node_modules\@babel\generator\lib\generators\types.js:82:8)
    at Generator.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:159:7)
    at Generator.print (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.printJoin (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:404:12)
    at Generator.printList (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:482:10)
    at Generator.ObjectExpression (D:\git\universal-demo\node_modules\@babel\generator\lib\generators\types.js:49:10)
    at Generator.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:159:7)
    at Generator.print (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.printJoin (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:404:12)
    at Generator.printList (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:482:10)
    at Generator.CallExpression (D:\git\universal-demo\node_modules\@babel\generator\lib\generators\expressions.js:195:8)
    at Generator.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:159:7)
    at Generator.print (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.AssignmentExpression (D:\git\universal-demo\node_modules\@babel\generator\lib\generators\expressions.js:252:8)
    at Buffer.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\buffer.js:249:5)
    at Generator.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:163:15)
    at Generator.print (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.ExpressionStatement (D:\git\universal-demo\node_modules\@babel\generator\lib\generators\expressions.js:227:8)
 @ ./node_modules/@anglr/notifications/es2020/src/index.js 4:0-79 4:0-79
 @ ./app/boot/app.component.ts 27:0-43 179:90-121
 @ ./app/boot/browser-app.module.ts 6:0-47 16:14-26
 @ ./app/main.browser.bootstrap.ts 11:0-61 16:45-61
 @ ./app/main.browser.ts 11:10-44

### Environment

- Babel: 7.22.5
- Node: v16.15.0
- npm: 8.19.4
- Windows: 10.0.19045

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #15712  
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | √
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15719"></a>

### CODE REVIEW

File: packages/babel-generator/test/index.js [hunk 1]
```diff
@@ -914,6 +917,61 @@ describe("generation", function () {
       }
     `);
   });
+
+  it("should not throw when loc.column === 0 with inputSourceMap", () => {
+    const ast = parseExpression("a(\n)");
+
+    ast.loc.end.column = 0;
```
Comment (JLHwung) [inline packages/babel-generator/test/index.js:924]: Can we construct a test without AST location mutations? If not it may point to an upstream issue and we can provide a better error message.

The current `_normalizePosition` implementation will also fail if any external tool sets `ast.loc.end.line` to `-1`. If we decide to mute such errors, we should also handle the `.line` info.

Comment (liuxingbaoyu) [reply packages/babel-generator/test/index.js:924]: This happened in a complex Angular project, and I thought it was a downstream bug, but since it's a regression, I took this approach.

> The current _normalizePosition implementation will also throw if any external tool sets ast.loc.end.line to -1. If we decide to mute such errors, we should also handle the .line info.

You are right, but the reason for this regression is that we internally added `columnOffset` resulting in a possible -1, and `lineOffset` is not currently actually used, I'm not sure about doing the same.
Maybe we can remove `lineOffset`?

Comment (kukjevov) [reply packages/babel-generator/test/index.js:924]: Anything new here ? It would be awesome to have this fix :)

File: packages/babel-generator/src/buffer.ts [hunk 2]
```diff
@@ -469,18 +468,13 @@ export default class Buffer {
...
-  ) {
+  _normalizePosition(prop: "start" | "end", loc: Loc, columnOffset: number) {
     const pos = loc[prop];
     const target = this._sourcePosition;
 
     if (pos) {
-      target.line = pos.line + lineOffset;
-      target.column = pos.column + columnOffset;
+      target.line = pos.line;
+      target.column = Math.max(pos.column + columnOffset, 0);
```
Comment (JLHwung) [inline packages/babel-generator/src/buffer.ts:477]: Can you add a note here to https://github.com/babel/babel/issues/15712? So that we can investigate this issue in the future.

**Review by JLHwung — APPROVED** [review]

**Review by nicolo-ribaudo — APPROVED** [review]
The changes look good, but I would like to learn more about the underlying cause of this problem (not a blocker for this PR)
