### PR TITLE
Return rejected promise when stringify import specifier throws

### LINKED ISSUE #15261: [Bug]: Error in `toString` during dynamic import should result in rejected promise
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
var filename = {
  toString: () => { throw "toString failure"; }
}

import(filename)
.then(obj => {
  console.log("import success");
})
.catch(err => {
  console.log("import failed");
});
```

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

[REPL](https://babeljs.io/repl/#?browsers=&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=G4QwTgBAZglgNgUwHYgLYIgXggbwFAQQAuA9gMpFgxIDmAXBABQCUWAfLsQBZgkDuEAESkKVWtBDwArmASCA3BAC-eFXhioADiTBFGsRCnTM8AOiJdkjEgCMAVu1wEIAYxJIAziUSm4JGoyCGtq6EB5SLi4IHh6CzPKqJqYuIEQuXIwIYJCYHPiEbp7eCL7-gcE6RBLwCAAmcQlK8UA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env&prettier=true&targets=&version=7.20.6&externalPlugins=&assumptions=%7B%7D)

The code above is transpiled into
```js
...
Promise.resolve("".concat(filename))
...
```
which results in throwing "toString failure".

However, since the exception is thrown during `toString`, the original import expression should result in [rejected promise](https://262.ecma-international.org/13.0/#sec-import-call-runtime-semantics-evaluation), and "import failed" should be printed.

### Environment

Tried at REPL (7.20.6)

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by SuperSodaSea**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #15261
| Patch: Bug Fix?          | :+1:
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    |
| Any Dependency Changes?  |
| License                  | MIT

When using dynamic import (`import(specifier)`), the `toString` of the specifier should be evaluated immediately, not in promise. And if the `toString` throws, `import()` should return a rejected promise instead of throwing it immediately.

See https://github.com/babel/babel/issues/15261#issuecomment-1343994886 for more context.

##### :heavy_plus_sign: Added
- babel-plugin-proposal-dynamic-import
  - amd/to-string
  - commonjs/exec-throw
  - commonjs/exec-to-primitive
  - commonjs/exec-to-string-order
  - commonjs/exec-to-string-throw
  - commonjs/template-literal
  - systemjs/to-string

##### :wavy_dash: Output Changed
- babel-plugin-proposal-dynamic-import
  - commonjs/to-string

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15290"></a>

### CODE REVIEW

File: packages/babel-helper-module-transforms/src/dynamic-import.ts [hunk 1]
```diff
@@ -1,9 +1,67 @@
...
+    }
+    helper = t.cloneNode(helper);
+  }
+
+  return { pure: false, specifier: t.callExpression(helper, [specifier]) };
+}
+
 export function getDynamicImportSource(
   node: t.CallExpression,
 ): t.StringLiteral | t.TemplateLiteral {
```
Comment (SuperSodaSea) [inline packages/babel-helper-module-transforms/src/dynamic-import.ts:67]: Could the old function `getDynamicImportSource` be deleted safely (won't cause compatibility issue)?

File: packages/babel-helpers/src/helpers/dynamicImportSpecifier.js [hunk 2]
```diff
@@ -0,0 +1,9 @@
+/* @minVersion 7.20.6 */
+
+export default function _dynamicImportSpecifier(s) {
+  try {
+    return Promise.resolve("" + s);
+  } catch (e) {
+    return Promise.reject(e);
+  }
```
Comment (JLHwung) [inline packages/babel-helpers/src/helpers/dynamicImportSpecifier.js:8]:
```js
  return new Promise(function (resolve, reject) {
    try { resolve("" + s) } catch (e) { reject(e) }
  })
```
will be 4 bytes shorter after terser since the it can mangle names like `resolve` and `reject`.

File: packages/babel-helper-module-transforms/src/dynamic-import.ts (hunk 1 above)
Comment (JLHwung) [reply packages/babel-helper-module-transforms/src/dynamic-import.ts:67]: It is a public export, so better keep it until Babel 8.

File: packages/babel-helper-module-transforms/src/dynamic-import.ts [hunk 3]
```diff
@@ -1,9 +1,67 @@
 // Heavily inspired by
 // https://github.com/airbnb/babel-plugin-dynamic-import-node/blob/master/src/utils.js
 
+import type { File } from "@babel/core";
 import * as t from "@babel/types";
 import template from "@babel/template";
 
+// TODO(Babel 8): Remove this
```
Comment (JLHwung) [inline packages/babel-helper-module-transforms/src/dynamic-import.ts:8]: We can wrap the fallback logic within `if (process.env.BABEL_8_BREAKING)` and get rid of yet another Babel 8 todo item. 😄

**Review by JLHwung — APPROVED** [review]

File: packages/babel-helpers/src/helpers/dynamicImportSpecifier.js (hunk 2 above)
Comment (nicolo-ribaudo) [reply packages/babel-helpers/src/helpers/dynamicImportSpecifier.js:8]:
```js
return new Promise(resolve => resolve(""+s));
```

also works. It's simple enough that we probably don't need an helper for that.

Comment (SuperSodaSea) [reply packages/babel-helpers/src/helpers/dynamicImportSpecifier.js:8]: Oh, wait, maybe we don't even need a helper. Since the `f` in `new Promise(f)` is executed synchronously, we just need to do this:

```js
import(s)
```
=>
```js
new Promise((resolve) => resolve(require("" + s)))
```

And throwing in `toString` can automatically make a rejected promise.

Comment (nicolo-ribaudo) [reply packages/babel-helpers/src/helpers/dynamicImportSpecifier.js:8]: I still want to keep `require` in `.then`, so that the imported code is executed on the next tick.

File: packages/babel-plugin-transform-modules-commonjs/src/dynamic-import.ts [hunk 4]
```diff
@@ -29,8 +28,10 @@ export function transformDynamicImport(
         Promise.resolve().then(() => ${buildRequire(source, file)})
       `
       : template.expression.ast`
-        new Promise(r => r(${source}))
-          .then(s => ${buildRequire(t.identifier("s"), file)})
+        (source =>
+          new Promise(r => r("" + source))
```
Comment (JLHwung) [inline packages/babel-plugin-transform-modules-commonjs/src/dynamic-import.ts:32]:
```suggestion
          new Promise(r => r(${
            t.isTemplateLiteral(source) ? source : t.templateLiteral([], [source])
          }))
```

The transform from `${x}` to `"" + x` relies on the `ignoreToPrimitiveHint` assumption.

Consider an exotic object:

```js
var source = {
  [Symbol.toPrimitive](hint) {
    if (hint === 'string') {
      return "foo"
    }
    return null
  }
}
```

`"" + source` will be `null` while `${source}` will be `"foo"`. The [ToString](https://tc39.es/ecma262/#sec-tostring) operation should respect the `toPrimitive` symbol.

**Review by JLHwung — APPROVED** [review]
LGTM except for the `toPrimitive` cases.

File: packages/babel-plugin-proposal-dynamic-import/test/fixtures/amd/no-interop/output.js [hunk 5]
```diff
@@ -1,3 +1,3 @@
 define(["require"], function (_require) {
-  var modP = new Promise((_resolve, _reject) => _require(["mod"], imported => _resolve(imported), _reject));
+  var modP = Promise.resolve().then(() => new Promise((_resolve, _reject) => _require(["mod"], imported => _resolve(imported), _reject)));
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-proposal-dynamic-import/test/fixtures/amd/no-interop/output.js:2]: Since the AMD `require` function is already asynchronous, we don't need to defer it to `.then` — the original code was fine.

File: packages/babel-plugin-transform-modules-commonjs/src/dynamic-import.ts (hunk 4 above)
Comment (SuperSodaSea) [reply packages/babel-plugin-transform-modules-commonjs/src/dynamic-import.ts]: Fixed, and I go further to move the common logic to function `buildDynamicImport`:

https://github.com/babel/babel/blob/75996fe68e4d00aed78e465f330fcb37a406d71f/packages/babel-helper-module-transforms/src/dynamic-import.ts#L18-L22

And in `transform-modules-amd/commonjs/system` we only need to write code once:

https://github.com/babel/babel/blob/75996fe68e4d00aed78e465f330fcb37a406d71f/packages/babel-plugin-transform-modules-amd/src/index.ts#L102-L114

https://github.com/babel/babel/blob/75996fe68e4d00aed78e465f330fcb37a406d71f/packages/babel-plugin-transform-modules-commonjs/src/dynamic-import.ts#L24-L26

https://github.com/babel/babel/blob/75996fe68e4d00aed78e465f330fcb37a406d71f/packages/babel-plugin-transform-modules-systemjs/src/index.ts#L277-L285

File: packages/babel-plugin-proposal-dynamic-import/test/fixtures/amd/no-interop/output.js (hunk 5 above)
Comment (SuperSodaSea) [reply packages/babel-plugin-proposal-dynamic-import/test/fixtures/amd/no-interop/output.js:2]: Ok, I just need to set the `buildDynamicImport`'s `runInThen` to `false` for it.

https://github.com/babel/babel/blob/75996fe68e4d00aed78e465f330fcb37a406d71f/packages/babel-plugin-transform-modules-amd/src/index.ts#L102-L114

Comment (SuperSodaSea) [reply packages/babel-plugin-proposal-dynamic-import/test/fixtures/amd/no-interop/output.js]: Now the logic looks like this:

CommonJS (Deferred to then):
https://github.com/babel/babel/blob/9b2100566283b50c9ed895d03ee1f1c0a7bb93c0/packages/babel-helper-module-transforms/src/dynamic-import.ts#L44-L50

SystemJS (Needs to return a rejected promise so wrap it in a promise):
https://github.com/babel/babel/blob/9b2100566283b50c9ed895d03ee1f1c0a7bb93c0/packages/babel-helper-module-transforms/src/dynamic-import.ts#L51-L56

AMD (Builder already returns a `new Promise` so do nothing):
https://github.com/babel/babel/blob/9b2100566283b50c9ed895d03ee1f1c0a7bb93c0/packages/babel-helper-module-transforms/src/dynamic-import.ts#L57-L60

**Review by JLHwung — APPROVED** [review]

**Review by nicolo-ribaudo — APPROVED** [review]
Thank you!
