### PR TITLE
Fix missing parens when function expressions is tag

### LINKED ISSUE #5192: Missing Parens. Syntax Error after transforming ArrowFn as Callee
When transforming CallExpression with ArrowFn as the callee to TaggedTemplate, a pair of parens doesn't get outputted. 

http://astexplorer.net/#/K2CkvW8FLH

Edit: Also for FunctionExpression

### Input Code

```js
(() => {})("foo")
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  plugins: [
    ({types: t}) => ({
      visitor: {
        CallExpression(path) {
          path.replaceWith(
            t.taggedTemplateExpression(
              path.get("callee").node,
              t.templateLiteral(
                [ t.templateElement({ raw: path.get("arguments")[0].node.value }, true) ], []
              )
            )
          );
        }
      }
    })
  ]
}
```

### Expected Behavior

```js
(() => {})`foo`;
```

### Current Behavior

```js
() => {}`foo`
```

which is a SyntaxError.

### Context

Minify `foo("bar")` to 

```js
foo`bar`
```

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.21
| node             | 7
| npm              | 4

### PR DESCRIPTION
**Pull request by existentialism**
| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          |  yes
| Major: Breaking Change?  | no
| Minor: New Feature?      | no
| Deprecations?            | no
| Spec Compliancy?         | no
| Tests Added/Pass?        | yes
| Fixed Tickets            | Fixes #5192 
| License                  | MIT
| Doc PR                   | 
| Dependency Changes       |

### CODE REVIEW

File: packages/babel-generator/src/node/parentheses.js [hunk 1]
```diff
@@ -166,20 +166,22 @@ export function UnaryLike(node: Object, parent: Object): boolean {
 }
 
 export function FunctionExpression(node: Object, parent: Object, printStack: Array<Object>): boolean {
-  return isFirstInStatement(printStack, { considerDefaultExports: true });
-}
-
-export function ArrowFunctionExpression(node: Object, parent: Object): boolean {
-  // export default (function () {});
-  if (t.isExportDeclaration(parent)) {
+  if (t.isTaggedTemplateExpression(parent)) {
```
Comment (loganfsmyth) [inline packages/babel-generator/src/node/parentheses.js]: I think the function expression case is fine, it's only the arrow function that needs fixing.

Comment (loganfsmyth) [inline packages/babel-generator/src/node/parentheses.js]: Oh wait, I see why you added this.

    function(){}`foo`

is fine as long as it is in an expression context, so I'd be in favor of expanding `isFirstInStatement` to handle functions in tagged templates, are you up for that? So your test output would be

    (() => {})``;
    (function(){}``);
