### PR TITLE
fix: skip merging large input sourcemaps

### LINKED ISSUE #10875: Very high memory usage compiling mozilla/PDF.js
## Bug Report

**Current Behavior**
When running npm start or npm run build, while pdf.js is used in create-react-app project, memory usage seems to skyrocket to unreasonable amounts and fail with "JavaScript heap out of memory" error.
unreasonable memory usage
NPM Error
I've reported it to PDF.js guys, and they found that ejecting and downgrading babel from 7.7.0+ to 7.6.4 seems to fix the issue so they think it must be regression issue with Babel. The issue can be reproduced in any fresh create-react-app (version 3.3.0) project with pdfjs-dist installed. ([link to original issue](https://github.com/mozilla/pdf.js/issues/11410))

***Steps to reproduce the problem***
1. Create new react app with create-react-app
2. npm install pdfjs-dist
3. Copy [example](https://github.com/mozilla/pdf.js/tree/master/examples/create-react-app) 
4. npm start or npm run build

**Input Code**
[Example repo](https://github.com/astrada/pdf.js-cra-test)

**Expected behavior/code**
npm start or npm run build succesfully without unreasonable memory usage

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
No additional configuration except of what CRA gives us

**Environment**

```
System:
    OS: Windows 10 10.0.18362
  Binaries:
    Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
```
- Babel version(s): v7.7.4
- Node/npm version: Node 12/npm 6
- OS: Windows 10 Enterprise 1903

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #10875 
| Patch: Bug Fix?          | Yes
| Tests Added + Pass?      | Yes
| License                  | MIT

This PR addresses #10875 where a large input source map is consumed and causing OOM error. It is not an ideal fix but still preserve basic support for practical size input source map.

Note that #10885 misidentified the memory bottleneck. But I preserve the change here since we need to detect the source map file size.

Ideally the mergeSourceMap in babel generator should operate in a streaming mode. But this does not fit in a patch release.

I don't consider it as a regression since in 7.6.4 the `inputSourceMap` is not working properly on external sourcemaps.

@artisb45 @midgethoen Though the URL does not change, [here](https://gist.github.com/JLHwung/a4e735de002261d84764b8c3ed136c24) is a new fix. You can download it and overwrite `node_modules/@babel/core/lib/transformation/normalize-file.js`.

### CODE REVIEW

File: packages/babel-core/src/transformation/normalize-file.js [hunk 1]
```diff
@@ -65,14 +66,18 @@ export default function normalizeFile(
...
-          if (!match) throw new Error("Invalid source map comment format.");
-          inputMap = convertSourceMap.fromJSON(
-            fs.readFileSync(
-              path.resolve(path.dirname(options.filename), match[1]),
-              "utf8",
-            ),
+          // when `lastComment` is non-null, EXTERNAL_SOURCEMAP_REGEX must have matches
+          const match: [string, string] = (EXTERNAL_SOURCEMAP_REGEX.exec(
+            lastComment,
+          ): any);
```
Comment (nicolo-ribaudo) [inline packages/babel-core/src/transformation/normalize-file.js]: Is this guaranteed to never return `null`?

Comment (JLHwung) [reply packages/babel-core/src/transformation/normalize-file.js]: Yes because the capturing group `([^\s'"`]+)` has a `+` quantifier, if the whole regex passed, the capturing group must not be `null`.

**Comment by JLHwung** [comment]
@nicolo-ribaudo Correct. I have tested on `pdfjs-dist/build/pdf.js.map` (1.21 MB) and it does not bail. To be conservative I shrink the threshold to 1M. We can easily change it to an option if people really need to configure.
