### PR TITLE
Fix printing BigIntLiterals/DecimalLiterals with compact option

### LINKED ISSUE #12423: `compact: true` causes space between `return` and bigint literal to be omitted
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**
`return 0n` becomes `return0n` when `compact: true` is set.

**Input Code**

```js
'use strict';
const {transformSync} = require('@babel/core');

const {code} = transformSync('function a() { return 0n; }', {
  babelrc: false,
  configFile: false,
  compact: true
});

console.log(code);
```

**Environment**
- Babel version(s): 7.12.9
- Node/npm version: node 14.15.1, npm 6.14.8
- OS: Fedora 32
- Monorepo: no
- How you are using Babel: API

**Possible Solution**

**Additional context**
Identified by nyc user, https://github.com/istanbuljs/nyc/issues/1369

### PR DESCRIPTION
**Pull request by existentialism**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #12423 
| Patch: Bug Fix?          | Y
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/12424"></a>

### CODE REVIEW

File: packages/babel-generator/src/generators/types.js [hunk 1]
```diff
@@ -216,19 +216,19 @@ export function StringLiteral(node: Object) {
 export function BigIntLiteral(node: Object) {
   const raw = this.getPossibleRaw(node);
   if (!this.format.minified && raw != null) {
-    this.token(raw);
+    this.word(raw);
```
Comment (existentialism) [inline packages/babel-generator/src/generators/types.js:219]: @nicolo-ribaudo @JLHwung we could also use `this.number` here if clearer (though there's logic in there for handling integer tokens), thoughts?

**Review by jridgewell — APPROVED** [review]

File: packages/babel-generator/src/generators/types.js (hunk 1 above)
Comment (nicolo-ribaudo) [reply packages/babel-generator/src/generators/types.js:219]: Maybe let's add a comment explaining that we use `word` instead of `number` to avoid that additional logic?

**Review by JLHwung — APPROVED** [review]
I think we could add a `compact: true` test runner for `@babel/generator`, like we did for `estree` in `@babel/parser`. Essentially we shall enforce the following idempotent invariance:

```js
generate(ast, { compact: true }) === generate(parse(generate(ast, { compact: true })), { compact: true })
```

**Comment by existentialism** [comment]
@JLHwung yeah been thinking of doing this for a while, will take a look
