### PR TITLE
fix: Works correctly with `--frozen-intrinsics`

### LINKED ISSUE #15625: [Bug]: Cannot assign to read only property 'stackTraceLimit'
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
import { parse } from "@babel/core";
console.log(parse("").type);
```

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

```sh
$ node reproduce.mjs
File
```

```
$  node --frozen-intrinsics reproduce.mjs 
(node:602173) ExperimentalWarning: The --frozen-intrinsics flag is experimental
(Use `node --trace-warnings ...` to show where the warning was created)
/path/to/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js:65
  Error.stackTraceLimit && (Error.stackTraceLimit = Math.max(Error.stackTraceLimit, MIN_STACK_TRACE_LIMIT));
                                                  ^

TypeError <Object <Object <[Object: null prototype] {}>>>: Cannot assign to read only property 'stackTraceLimit' of function 'function Error() { [native code] }'
    at setupPrepareStackTrace (/path/to/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js:65:51)
    at stopHiding - secret - don't use this - v1 (/path/to/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js:45:5)
    at parse (/path/to/node_modules/@babel/core/lib/parse.js:34:76)
    at file:///path/to/reproduce.mjs:2:13
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.15.0
```

### Environment

"@babel/core": "^7.21.8"

node v18.15.0

### Possible solution

```patch
diff --git a/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js b/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js
index 9b6ce01..0757ad6 100644
--- a/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js
+++ b/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js
@@ -62,6 +62,7 @@ function setupPrepareStackTrace() {
     prepareStackTrace = defaultPrepareStackTrace
   } = Error;
   const MIN_STACK_TRACE_LIMIT = 50;
+  try {
   Error.stackTraceLimit && (Error.stackTraceLimit = Math.max(Error.stackTraceLimit, MIN_STACK_TRACE_LIMIT));
   Error.prepareStackTrace = function stackTraceRewriter(err, trace) {
     let newTrace = [];
@@ -87,6 +88,7 @@ function setupPrepareStackTrace() {
     }
     return prepareStackTrace(err, newTrace);
   };
+  } catch {}
 }
 function defaultPrepareStackTrace(err, trace) {
   if (trace.length === 0) return ErrorToString(err);
```

```sh
$ node --frozen-intrinsics reproduce.mjs
(node:604212) ExperimentalWarning: The --frozen-intrinsics flag is experimental
(Use `node --trace-warnings ...` to show where the warning was created)
File
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #15625 
| Patch: Bug Fix?          | √
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | √
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15626"></a>

### CODE REVIEW

File: packages/babel-core/src/errors/rewrite-stack-trace.ts [hunk 1]
```diff
@@ -70,6 +70,18 @@ function CallSite(filename: string): CallSite {
   } as CallSite);
 }
 
+// https://github.com/nodejs/node/pull/38215/files#diff-670bf55805b781d9a3579f8bca9104c04d94af87cc33220149fd7d37b095ca1cR210
+function isErrorStackTraceLimitWritable() {
+  const desc = Object.getOwnPropertyDescriptor(Error, "stackTraceLimit");
+  if (desc === undefined) {
```
Comment (nicolo-ribaudo) [inline packages/babel-core/src/errors/rewrite-stack-trace.ts:76]: We first check if the property exists, so the descriptor will never be undefined when we call this function.

Comment (liuxingbaoyu) [reply packages/babel-core/src/errors/rewrite-stack-trace.ts:76]: You mean `Error.stackTraceLimit &&= Math.max(
     Error.stackTraceLimit,
     MIN_STACK_TRACE_LIMIT,
   );`?
If we can't increase `Error.stackTraceLimit`, maybe there is no need to enable this feature? (Just a guess, I'm not sure if it would be better to enable it with only the default 10 stack frames)

Comment (nicolo-ribaudo) [reply packages/babel-core/src/errors/rewrite-stack-trace.ts:76]: I got confused by the `!!Error.captureStackTrace` check above, I thought it was `!!Error.stackTraceLimit`

File: packages/babel-core/test/errors-stacks.js [hunk 2]
```diff
@@ -283,4 +297,29 @@ describe("@babel/core errors", function () {
...
+        babel.parseSync("foo;", {
+          root: String.raw\`${fixture("valid")}\`,
+        });
+        console.log("%done%");
+        `,
+          ],
+          {
+            cwd: __dirname,
+          },
+        ).output + "",
```
Comment (nicolo-ribaudo) [inline packages/babel-core/test/errors-stacks.js:321]:
```suggestion
        spawnSync(
          process.execPath,
          [
            "--frozen-intrinsics",
            "--input-type=module",
            "-e",
            `
        import * as babel from "@babel/core";
        await babel.parseAsync("foo;", {
          root: String.raw\`${fixture("valid")}\`,
        });
        console.log("%done%");
        `,
          ],
          { cwd: __dirname },
        ).output + "",
```

Does this work with ESM?

File: packages/babel-core/src/errors/rewrite-stack-trace.ts [hunk 3]
```diff
@@ -70,6 +70,18 @@ function CallSite(filename: string): CallSite {
...
+    return Object.isExtensible(Error);
+  }
+
+  return Object.prototype.hasOwnProperty.call(desc, "writable")
+    ? desc.writable
+    : desc.set !== undefined;
```
Comment (nicolo-ribaudo) [inline packages/babel-core/src/errors/rewrite-stack-trace.ts:82]:
```suggestion
  return desc && Object.prototype.hasOwnProperty.call(desc, "writable") && desc.writable;
```

Do you think this would be enough? Since `stackTraceLimit` is only supported by V8, and:
- if the property doesn't exist, there is no reason to set it because we are in a different engine
- in V8 it's a data property, not a setter

File: packages/babel-core/test/errors-stacks.js [hunk 4]
```diff
@@ -2,6 +2,20 @@ import * as babel from "../lib/index.js";
...
+const __dirname = path.dirname(fileURLToPath(import.meta.url));
+
+let USE_ESM = false;
+try {
+  const type = readFileSync(
+    new URL("../../../.module-type", import.meta.url),
+    "utf-8",
+  ).trim();
+  USE_ESM = type === "module";
+} catch {}
```
Comment (nicolo-ribaudo) [inline packages/babel-core/test/errors-stacks.js:18]: Can you import this from `$repo-utils` now?

**Comment by liuxingbaoyu** [comment]
@nicolo-ribaudo Thanks! Yes I'm doing both locally. :)

File: packages/babel-core/src/errors/rewrite-stack-trace.ts (hunk 3 above)
Comment (liuxingbaoyu) [reply packages/babel-core/src/errors/rewrite-stack-trace.ts:82]: > in V8 it's a data property, not a setter

Is it possible for the user to set it to have no `setter`?

Comment (nicolo-ribaudo) [reply packages/babel-core/src/errors/rewrite-stack-trace.ts:82]: Yes, but it disables `.stack` generation:
```
➜ node
Welcome to Node.js v20.0.0.
Type ".help" for more information.
> Error.stackTraceLimit = 2
2
> new Error().stack
'Error\n    at REPL8:1:1\n    at Script.runInThisContext (node:vm:122:12)'
> let limit = 3;
undefined
> Object.defineProperty(Error, "stackTraceLimit", { get: () => limit, set: v => limit = v })
[Function: Error] { stackTraceLimit: [Getter/Setter] }
> Error.stackTraceLimit
3
> new Error().stack
undefined
> 
```

File: packages/babel-core/test/errors-stacks.js [hunk 5]
```diff
@@ -283,4 +281,28 @@ describe("@babel/core errors", function () {
           at ... internal jest frames ..."
     `);
   });
+
+  itGte("12.0.0")(
```
Comment (nicolo-ribaudo) [inline packages/babel-core/test/errors-stacks.js:285]: I would love to see a PR using `itGte` in more places :)

**Review by nicolo-ribaudo — APPROVED** [review]
