### PR TITLE
fix: `new.target` with shadowed class name

### LINKED ISSUE #14406: [Bug]: Right-Hand Side of 'instanceof' is not an Object
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
function v1() {
    let v1 = new.target;    
}
var v3 = new v1();
```
Here is the [REPL](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=false&spec=false&loose=true&code_lz=GYVwdgxgLglg9mABANwIwAoCUiDeAoRQxAGwFMoVVEBeRMUgdwDooBDAJwHNyBuIxPAF88yDigDMNOo0pYeQA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=unambiguous&lineWrap=true&presets=env&prettier=false&targets=&version=7.17.8&externalPlugins=&assumptions=%7B%7D)

### Configuration file name

babel.config.json

### Configuration

```json
{
  "sourceType": "unambiguous",
  "presets": ["@babel/preset-env"],
  "plugins": [
    "@babel/plugin-transform-runtime"
  ]
}
```

### Current and expected behavior

Inside the function, this bug will be triggered when the variable name and function name happen to be the same and the variable is a new target. The transpiled code run by node will report the following error:
```shell
 var v1 = this instanceof v1 ? this.constructor : void 0;
                ^

TypeError: Right-hand side of 'instanceof' is not an object
```

### Environment

- babel
- ├── @babel/cli@7.17.0=6
- ├── @babel/generator@7.17.3
- ├── @babel/plugin-transform-runtime@7.17.0
- ├── @babel/preset-env@7.16.11
- Node: [v17.3.0]
- npm version [8.5.2]
- os [ubuntu 20.04]

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #14406 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14611"></a>

### CODE REVIEW

File: packages/babel-plugin-transform-new-target/src/index.ts [hunk 1]
```diff
@@ -49,6 +49,19 @@ export default declare(api => {
...
+            const name = node.id.name;
+            while (scope !== func.parentPath.scope) {
+              if (
+                scope.hasOwnBinding(name) &&
+                !scope.bindingIdentifierEquals(name, node.id)
+              ) {
+                scope.rename(name);
+              }
+              scope = scope.parent;
+            }
```
Comment (JLHwung) [inline packages/babel-plugin-transform-new-target/src/index.ts:64]: Nit: they can be moved after the `if (func.isClass())` branch.

**Review by JLHwung — APPROVED** [review]

**Review by JLHwung — APPROVED** [review]

File: packages/babel-plugin-transform-new-target/src/index.ts [hunk 2]
```diff
@@ -61,6 +58,23 @@ export default declare(api => {
             return;
           }
 
+          if (!node.id) {
+            node.id = scope.generateUidIdentifier("target");
+          } else {
+            // packages/babel-helper-create-class-features-plugin/src/fields.ts#L192 unshadow
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-new-target/src/index.ts:64]: We could actually move this to a `Scope#unshadow(name, targetAncestorScope)` method, and use it here like
```js
path.scope.unshadow?.(name, func.parentPath.scope);
```

It will only work when people update their `@babel/traverse` (usually by updating their `@babel/core`), but it's not a breaking change because when using older versions `new.target` will just continue to be broken.

Then, we can use `scope.unshadow()` in `babel-helper-create-class-features-plugin` starting from Babel 8 (or better, now with a fallback to the inline `unshadow()` function when `!process.env.BABEL_8_BREAKING`).

Comment (liuxingbaoyu) [reply packages/babel-plugin-transform-new-target/src/index.ts:64]: I feel a little unnecessary.
Because `unshadow` is only a few lines of code and may be different in different scenarios.
Another major reason is that our current Scope is a bit messy, eg binding is not always reliable.
Maybe we can do it in the future.

Comment (nicolo-ribaudo) [reply packages/babel-plugin-transform-new-target/src/index.ts:64]: Oh ok fair enough, we can refactor if needed.

**Review by nicolo-ribaudo — APPROVED** [review]
