### PR TITLE
eslint-parser: ES2020 features

### LINKED ISSUE #11711: @babel/parser: update ESTree plugin to support optional chaining
## Bug Report

- [x] I would like to work on a fix!

Now that https://github.com/estree/estree/pull/204 has landed, we need to update `@babel/parser`'s ESTree plugin to output a spec-compliant AST for optional chaining nodes.

Initial work to get tests passing (due to Acorn being released with the new syntax) can be seen [here](https://github.com/babel/babel/pull/11709).

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #11711 
| Minor: New Feature?      | Yes
| Tests Added + Pass?      | Yes
| Any Dependency Changes?  | `eslint-visitor-keys` is bumped to `^1.3.0` which includes the `ChainExpression` visitor keys.
| License                  | MIT

This PR adds estree parsing support on the following features:

- optional chaining expression.
- nullish coalescing
- `export * ns` (credits to @existentialism)

The nullish coalescing is out of the box since ESTree and Babel shares the AST shape. Thus I have enabled test.

The `@babel/parser` `estree` plugin now supports parsing optional chaining and `export * ns`.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/11815"></a>

### CODE REVIEW

File: eslint/babel-eslint-parser/src/convert/convertAST.js [hunk 1]
```diff
@@ -82,20 +83,16 @@ function convertNodes(ast, code) {
...
+  t.VISITOR_KEYS.Property = VISITOR_KEYS.Property;
+  t.VISITOR_KEYS.MethodDefinition = VISITOR_KEYS.MethodDefinition;
 
   traverse(ast, astTransformVisitor, null, state);
 
   // These can be safely deleted because they are not defined in the original visitor keys.
-  delete t.VISITOR_KEYS.Property;
+  delete t.VISITOR_KEYS.ChainExpression;
   delete t.VISITOR_KEYS.MethodDefinition;
+  delete t.VISITOR_KEYS.Property;
```
Comment (nicolo-ribaudo) [inline eslint/babel-eslint-parser/src/convert/convertAST.js:95]: Unrelated, but the monkey-patching should be done in a `try/finally` in case `traverse()` throws.

**Comment by kaicataldo** [comment]
I don’t think this needs to block this PR, but we should make sure we bump the ESLint peer dep version once optional chaining lands in ESLint core (hopefully the next release).

I also have a [PR](https://github.com/babel/babel/pull/11778) open to upgrade to ESLint v7, so if we can land that it should be an easy bump :)

**Comment by kaicataldo** [comment]
ESLint optional chaining PR [here](https://github.com/eslint/eslint/pull/13416).
