### PR TITLE
[parser] Invalid NonOctal Decimal

### LINKED ISSUE #10465: The BigInt suffix should be disallowed in NonOctal Decimal Integer Literal
## Bug Report

**Current Behavior**
The following code should throw a syntax error if the parser plugin bigInt is enabled.

**Input Code**
- REPL or Repo link if applicable: https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=AwDgnAdkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env&prettier=false&targets=&version=7.6.0&externalPlugins=%40babel%2Fplugin-syntax-bigint%407.4.4

```js
089n
```

**Expected behavior/code**
It should throw `Invalid BigIntLiteral` error.

**Background**

We use tokenizer to process the source code into a stream of tokens and `08n` will be processed in `readNumber`
https://github.com/babel/babel/blob/9c1ad0a9f7f8c57e02a20e9f151fce8076d80725/packages/babel-parser/src/tokenizer/index.js#L981

The NonOctal Decimal Integer Literal is defined as

```
NonOctalDecimalInteger:
0 DecimalDigits

DecimalDigits:
DecimalDigit DecimalDigits_opt

DecimalDigit:
0 1 2 3 4 5 6 7 8 9
```
The above grammar requires a NonOctal Decimal Integer Literal to be a sequence of decimal digits starting with zero and the length is at least 2.

**Possible Solution**
1. Detect NonOctal Decimal Integer Literal in `readNumber`. Throw an error here when it is detected.

https://github.com/babel/babel/blob/9c1ad0a9f7f8c57e02a20e9f151fce8076d80725/packages/babel-parser/src/tokenizer/index.js#L1027-L1028

2. Add a test on https://github.com/babel/babel/tree/master/packages/babel-parser/test/fixtures/experimental/bigint

3. Run `make test-test262-update-whitelist` to update the whitelist, the following lines are expected to be removed.
https://github.com/babel/babel/blob/9c1ad0a9f7f8c57e02a20e9f151fce8076d80725/scripts/tests/test262/test262_whitelist.txt#L113-L116

If you don't know how to clone Babel, follow these steps: (you need to have `make` and `yarn` available on your machine).
1. Write a comment there to let other possible contributors know that you are working on this bug.
1. Fork the repo
1. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
1. Run `yarn && make bootstrap`
1. Wait :hourglass_flowing_sand: 
1. Run `make watch` (or `make build` whenever you change a file)
1. Add a test (only `input.js`; `output.js` will be automatically generated)
1. Update the code!
1. `yarn jest parser` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
1. If it is working, run `make test` to run all the tests
1. Run `git push` and open a PR!

### PR DESCRIPTION
**Pull request by gonzarodriguezt**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #10465 
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | Yes
| Any Dependency Changes?  | No
| License                  | MIT

I added a regex verification for a NonOctal Decimal Integer, defined as a sequence of decimal digits starting with 0 and with at least two characters, i did it within the scope of the `if (octal)` because `octal` ensure two of the requirements, and there was a similar octal verification.

**Todo:**
- [x] Update the whitelist

### CODE REVIEW

File: packages/babel-parser/src/tokenizer/index.js [hunk 1]
```diff
@@ -1024,8 +1025,11 @@ export default class Tokenizer extends LocationParser {
 
     if (this.hasPlugin("bigInt")) {
       if (next === charCodes.lowercaseN) {
-        // disallow floats and legacy octal syntax, new style octal ("0o") is handled in this.readRadixNumber
-        if (isFloat || octal) this.raise(start, "Invalid BigIntLiteral");
+        // disallow floats, legacy octal syntax and non octal decimals
+        // new style octal ("0o") is handled in this.readRadixNumber
+        if (isFloat || octal || isNonOctalDecimal) {
```
Comment (JLHwung) [inline packages/babel-parser/src/tokenizer/index.js]: Does `isNonOctalDecimal == true` _imply_ `(octal || isNonOctalDecimal) == true` ? If so we could consider removing `octal` check here.

File: packages/babel-parser/src/tokenizer/index.js [hunk 2]
```diff
@@ -990,15 +991,15 @@ export default class Tokenizer extends LocationParser {
...
         this.raise(
           start,
           "Legacy octal literals are not allowed in strict mode",
         );
       }
-      if (/[89]/.test(this.input.slice(start, this.state.pos))) {
-        octal = false;
-      }
+      if (/[89]/.test(number)) octal = false;
+      if (/^[0-9]*$/.test(number)) isNonOctalDecimal = true;
```
Comment (JLHwung) [inline packages/babel-parser/src/tokenizer/index.js]: `octal == true` implies that `startsWithDot == false` (because it starts with zero), which in turn means that `this.readInt(10) != null`, or otherwise we would throw `Invalid number` error here.
```js
if (!startsWithDot && this.readInt(10) === null) {
      this.raise(start, "Invalid number");
}
```
IIRC `this.readInt(10)` would ensure the input from `start` to `this.state.pos` to always be `[0-9]`, if so we don't have to check `[0-9]` again, which means `isNonOctalDecimal` equals to the previous definition of `octal`:
```js
this.state.pos - start >= 2 && this.input.charCodeAt(start) === charCodes.digit0;
```

Comment (nicolo-ribaudo) [reply packages/babel-parser/src/tokenizer/index.js]: Yeah, so it would be enought to do
```js
if (/[89]/.test(number)) {
  octal = false;
  isNonOctalDecimal = true;
}
```

So that `isNonOctalDecimal` literally means "we tought that it was an octal number, but it turns out that it isn't"

Comment (gonzarodriguezt) [reply packages/babel-parser/src/tokenizer/index.js]: You're right, i didn't see it in that way, it took me a while to realize why the test i added was passing, but it's because when `octal` is set to false here:

```javascript 
if (/[89]/.test(number)) octal = false;
```
`isNonOctalDecimal` remains true, so it can throw the error here:

```javascript
 if (isFloat || octal || isNonOctalDecimal) {...}
```
It's confusing, thanks for the review, i'll come back with some changes!

Comment (gonzarodriguezt) [reply packages/babel-parser/src/tokenizer/index.js]: @nicolo-ribaudo Nice! Also, the `decimal` part isn't confusing? Sounds like fractional numbers, maybe it can only be `isNonOctal`?

Comment (nicolo-ribaudo) [reply packages/babel-parser/src/tokenizer/index.js]: The spec calls it [`NonOctalDecimalIntegerLiteral`](https://tc39.es/ecma262/#prod-annexB-NonOctalDecimalIntegerLiteral), so maybe `nonOctalDecimalInt`?

But if you prefer `isNonOctal`, it's ok :+1:

File: packages/babel-parser/src/tokenizer/index.js [hunk 3]
```diff
@@ -1024,8 +1026,23 @@ export default class Tokenizer extends LocationParser {
 
     if (this.hasPlugin("bigInt")) {
       if (next === charCodes.lowercaseN) {
-        // disallow floats and legacy octal syntax, new style octal ("0o") is handled in this.readRadixNumber
-        if (isFloat || octal) this.raise(start, "Invalid BigIntLiteral");
+        // disallow numeric separators in non octal decimals
+        if (this.hasPlugin("numericSeparator") && isNonOctalDecimalInt) {
+          const underscorePos = this.input
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/src/tokenizer/index.js]: Could you move this whole `if` out of the `if (this.hasPlugin("bigInt"))`? It also applies to normal numbers:
```js
0_1;
```

Comment (gonzarodriguezt) [reply packages/babel-parser/src/tokenizer/index.js]: Sure! I thought it was only for bigInts, can i ask if that's because bigInt is no more going to be experimental?

Comment (gonzarodriguezt) [reply packages/babel-parser/src/tokenizer/index.js]: Done!

**Comment by gonzarodriguezt** [comment]
Now all green again 🎉

File: packages/babel-parser/src/tokenizer/index.js [hunk 4]
```diff
@@ -1022,10 +1024,26 @@ export default class Tokenizer extends LocationParser {
...
     }
 
+    // disallow numeric separators in non octal decimals
+    if (this.hasPlugin("numericSeparator") && isNonOctalDecimalInt) {
+      const underscorePos = this.input
+        .slice(start, this.state.pos)
+        .indexOf("_");
+      if (underscorePos > 0) {
+        this.raise(
+          underscorePos,
```
Comment (JLHwung) [inline packages/babel-parser/src/tokenizer/index.js]: Shouldn't it be `start + underscorePos`? 
```js
void 0_n;
```

File: scripts/tests/test262/test262_whitelist.txt [hunk 5]
```diff
@@ -104,26 +104,12 @@ language/expressions/object/method-definition/private-name-early-error-gen-insid
...
-language/literals/bigint/numeric-separators/numeric-separator-literal-nonoctal-09-err.js(default)
-language/literals/bigint/numeric-separators/numeric-separator-literal-nonoctal-0_8-err.js(default)
-language/literals/bigint/numeric-separators/numeric-separator-literal-nonoctal-0_9-err.js(default)
-language/literals/bigint/numeric-separators/numeric-separator-literal-nzd-nsl-dds-leading-zero-err.js(default)
 language/literals/numeric/numeric-separators/numeric-separator-literal-lol-00-err.js(default)
 language/literals/numeric/numeric-separators/numeric-separator-literal-lol-01-err.js(default)
 language/literals/numeric/numeric-separators/numeric-separator-literal-lol-07-err.js(default)
 language/literals/numeric/numeric-separators/numeric-separator-literal-lol-0_0-err.js(default)
 language/literals/numeric/numeric-separators/numeric-separator-literal-lol-0_1-err.js(default)
 language/literals/numeric/numeric-separators/numeric-separator-literal-lol-0_7-err.js(default)
```
Comment (nicolo-ribaudo) [inline scripts/tests/test262/test262_whitelist.txt]: If you want to open another PR to fix these tests, you are welcome to do so!

**Comment by gonzarodriguezt** [comment]
Thanks guys! Appreciate the review, I learned a lot 🙏

File: scripts/tests/test262/test262_whitelist.txt (hunk 5 above)
Comment (gonzarodriguezt) [reply scripts/tests/test262/test262_whitelist.txt]: Great, i would like to do so! Should i make an issue or just as a follow up of this PR?

Comment (nicolo-ribaudo) [reply scripts/tests/test262/test262_whitelist.txt]: Naa, just a PR

Comment (gonzarodriguezt) [reply scripts/tests/test262/test262_whitelist.txt]: Goodd 👌
