### PR TITLE
Fix plugin-transform-block-scoping const violations

### LINKED ISSUE #13245: [Bug]: plugin-transform-block-scoping constant checks produce different behaviour
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
let isCalled = false;
const fn = () => isCalled = true;

const i = 0;
try {
  i = fn();
} catch (e) {
  console.log(isCalled);
}
```

[Babel REPL](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.6&spec=false&loose=true&code_lz=DYUwLgBAlgzgwgQ2KAJhAvBAZkmIDcAUAMYD2AdjJFuRhABQCUGAfNPEqnWAE4CuBQiQpVodAIxFeATwgBvQhDGYaTIgF8IxBGGIALBiGYKlZSqVAA6YKQDm9WImQgUjDYSA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=Node-10&version=7.14.0&externalPlugins=%40babel%2Fplugin-transform-block-scoping%407.13.16)

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

Original code logs "true".

But [plugin-transform-block-scoping](https://babeljs.io/docs/en/babel-plugin-transform-block-scoping)'s constant checks produces code with a slightly different behaviour:

```js
function _readOnlyError(name) { throw new TypeError("\"" + name + "\" is read-only"); }
var isCalled = false;
var fn = () => isCalled = true;

var i = 0;
try {
  i = (_readOnlyError("i"), fn());
} catch (e) {
  console.log(isCalled);
}
```

This logs "false" because `_readOnlyError()` throws before `fn()` is evaluated.

### Environment

Babel REPL

### Possible solution

Order of `fn()` and `_readOnlyError("i")` should be reversed:

```js
i = (fn(), _readOnlyError("i"))
```

This order would produce wrong result if `_readOnlyError()` returned a value, but since we know for sure it'll throw, that's not relevant.

### Additional context

There are two other more obscure cases where the above solution is not sufficient to solve the problem:

(I may have time to make a PR for the simple case above, but unlikely I will for these two)

#### Destructuring

```js
const c = 0;
let x = 1, y = 2;
try {
  [x, c, y] = [11, 0, 22];
} catch (e) {
  console.log( {x, y} );
}
```

[REPL](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.6&spec=false&loose=true&code_lz=MYewdgzgLgBMMF4YAYDcAoANgU1gD0RgEYAaGAT0ICYMoAnSgb3RhgG08zgzyBdQtkVIoyVKrwwBfOAEMowABYwAFNgCUMZq1CQQOAHSYQAc2WNOFSWqnogA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=Node-10&version=7.14.0&externalPlugins=%40babel%2Fplugin-transform-block-scoping%407.13.16)

`[x, c, y] = []` is transformed to `[x, c, y] = (_readOnlyError("c"), [11, 0, 22])`.

Original logs `{x: 11, y: 2}` whereas transpiled code logs `{x: 1, y: 2}`. It should throw only after `x` has been assigned, but before `y` is.

This is tricky to get right. Best solution I can see is:

```js
// NB Assignment to `y` has been omitted
[x] = [11, 0, 22], _readOnlyError("c");
```

#### Assignment operators

```js
const calls = [];
const fn = () => calls.push('fn');

const i = {
  valueOf() {
    calls.push('valueOf');
    return 1;
   }
};

try {
  i += fn();
} catch (e) {
  console.log(calls);
}
```

[Babel REPL](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.6&spec=false&loose=true&code_lz=MYewdgzgLgBMCGAbREYF4YG0C6BuAUKJLAGZjowAUAlOgHxxIoB0ADgK4QAWlA5Gb2oFC4aDACWFAN74YMAG5J2AUwDyJGjBly5CZBDacevRYhXrBBHTABOyqOxvkAjFbkBffO-FQbATy1ZCRgAagwyGgJ3RihgLiplWm04URBEZWZEEABzSj0UIS8gA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=Node-10&version=7.14.0&externalPlugins=%40babel%2Fplugin-transform-block-scoping%407.13.16)

Original logs `[ 'fn', 'valueOf' ]`.

Babel transforms `i += fn()` to `i += (_readOnlyError("i"), fn())`. So transpiled code logs `[]`.

After reversing `fn()` and `_readOnlyError("i")`, it logs `[ 'fn' ]` (still incorrect).

The correct transpiled output would be:

```js
i + fn(), _readOnlyError("i")
```

NB `&&=`, `||=` and `??=` aren't affected by this additional complication, but I think all other assignment operators are.

`i++` / `++i` should be treated as same as `i += 1`:

```js
i + 1, _readOnlyError("i")
```

### PR DESCRIPTION
**Pull request by overlookmotel**
Fixes #13245.

| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #13245
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | Yes
| Documentation PR Link    | n/a
| Any Dependency Changes?  | No
| License                  | MIT

Fix for #13245.

This PR fixes:

1. The simple case `const c = 1; c = y++;`
2. Assignment expressions `const c = 1; c += y++`
3. Update expressions `const c = 1; c++`
4. An unrelated bug with `for in` - see addition to `no-for-in/exec.js` test for what was previously failing

The tests are maybe written a bit weirdly. My intent was to keep `const` declarations in same function scope as they were previously, in case that's part of the purpose of the tests. It's a pain testing side effects of code that throws. 

I'm leaving the bugs with destructuring for someone else! When/if this PR is merged, I'll open a separate issue for that specifically.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/13248"></a>

### CODE REVIEW

File: packages/babel-plugin-transform-block-scoping/src/index.js [hunk 1]
```diff
@@ -433,17 +433,47 @@ class BlockScoping {
...
+          }
         } else if (violation.isUpdateExpression()) {
           violation.replaceWith(
-            t.sequenceExpression([throwNode, violation.node]),
+            t.sequenceExpression([
+              t.binaryExpression(
+                violation.node.operator[0],
+                violation.get("argument").node,
+                t.numericLiteral(1),
+              ),
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-block-scoping/src/index.js:462]: I think we can simplify this to `t.unaryExpression("+", violation.get("argument").node)` (even if it saves literally a single byte).

**Review by nicolo-ribaudo — APPROVED** [review]
Thanks!

File: packages/babel-plugin-transform-block-scoping/src/index.js (hunk 1 above)
Comment (overlookmotel) [reply packages/babel-plugin-transform-block-scoping/src/index.js]: Yes, `+c` has same effect of triggering `.valueOf()` as `c + 1`. Have added a commit to make this change.

I hadn't really bothered with optimization since in most cases code like this is a bug in any case.

Have also added another commit for the other most obvious optimization - shorten `c = f()` to just `f()` since the assignment will never be executed anyway. There are other optimizations which could be made (`a += 'long_string'` to `a + ''` for example), but in my view going further would add complexity for little gain.

Comment (overlookmotel) [reply packages/babel-plugin-transform-block-scoping/src/index.js]: Added one more commit to shorten `c &&= x++` -> `c && x++`.

**Comment by overlookmotel** [comment]
Thanks for merging.
