### PR TITLE
fix(babel-traverse): automatically provide a hub when traversing a File or Program and no parentPath is given #11350

### LINKED ISSUE #11350: this.hub is undefined in estree mode
## Bug Report

This related to #8617

- [x] I would like to work on a fix!

**Current Behavior**
`@babel/parser` has a different behavior when `estree` enabled, and when not.

**Input Code**
When `estree` disabled code with `Duplicated variable declaration` throws while parsing:

```js
const {parse} = require('@babel/parser');
const traverse = require('@babel/traverse').default;

const code = `function square(n) {
  const n = 1;
}`;

// crash with an error: Identifier 'n' has already been declared (1:16)
const ast = parse(code);
```

When `estree` mode enabled code is parsed, but can't be traversed because of `this.hub` is undefined:

```js
const {parse} = require('@babel/parser');
const traverse = require('@babel/traverse').default;

const code = `function square(n) {
  const n = 1;
}`;

const ast2 = parse(code, {
    plugins: [
        'estree',
    ]
});

traverse(ast, {
  enter(path) {
      console.log('n');
  }
});

/*
    throw this.hub.buildError(id, `Duplicate declaration "${name}"`, TypeError);
                     ^

TypeError: Cannot read property 'buildError' of undefined
    at Scope.checkBlockScopedCollisions (/home/coderaiser/node_modules/@babel/traverse/lib/scope/index.js:402:22)
*/
```

**Expected behavior/code**
Would be great if in `estree` mode `babel` throws while parsing and/or can throw while traversing
about `Duplicate declaration`. 

**Environment**

- Babel version(s): `v7.9.4`
- Node/npm version: Node 12(13)/npm 6
- OS: `Ubuntu`
- Monorepo: no
- How you are using Babel: `parse`, `traverse`

**Possible Solution**

I suggest to use `TypeError`, because this is what [hub actually does](
https://github.com/babel/babel/blob/f6c7bf36cec81baaba8c37e572985bb59ca334b1/packages/babel-traverse/src/hub.js), this way:

```js
throw TypeError(`Duplicate declaration "${name}"`);
```

If of course `buildError` doesn't used in development purpose to set breakpoint on error building, anyways `Chrome Developer Tools` debugger already suggest similar feature `pause on exceptions` (caught and uncaught).

### PR DESCRIPTION
**Pull request by simbahax**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #11350 
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | Yes
| Documentation PR Link    | N/A 
| Any Dependency Changes?  | N/A
| License                  | MIT

This PR implements the changes proposed by @JLHwung in #11350 .
I am happy to incorporate any additional feedback :)

### CODE REVIEW

File: packages/babel-traverse/test/regression-11350-hub-undefined.js [hunk 1]
```diff
@@ -0,0 +1,20 @@
+import { parse } from "@babel/parser";
+
+import _traverse from "../lib/index.js";
+const traverse = _traverse.default || _traverse;
+
+describe("this.hub should not be undefined while traversing a program or file", function () {
```
Comment (JLHwung) [inline packages/babel-traverse/test/regression-11350-hub-undefined.js]: Could you move the test to `test/traverse.js`?

File: packages/babel-traverse/test/regression-11350-hub-undefined.js [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+  it("traverse", function () {
+    const p = parse("try { throw new Error() } catch (e) { const v = 0 }");
+    traverse(p, {
+      CatchClause(path) {
+        path.node.param.name = "v";
+        expect(function () {
+          path.scope.crawl();
+        }).toThrow(TypeError('Duplicate declaration "v"'));
```
Comment (JLHwung) [inline packages/babel-traverse/test/regression-11350-hub-undefined.js]: Here the test relies on the scope check and the specific message thrown during the scope check. Could you construct a minimal unit test instead? For example you can just call `path.hub.buildError` with a custom error message, which is also the argument of the unit test assertion.

File: packages/babel-traverse/src/path/ancestry.ts [hunk 3]
```diff
@@ -64,8 +64,7 @@ export function getStatementParent(this: NodePath): NodePath<t.Statement> {
       path = path.parentPath;
     }
   } while (path);
-
-  if (path && (path.isProgram() || path.isFile())) {
+  if (path && (!path.node || path.isProgram() || path.isFile())) {
```
Comment (JLHwung) [inline packages/babel-traverse/src/path/ancestry.ts]: Q: Is this check required?

**Review by scutuatua-crypto — APPROVED** [review]

File: packages/babel-traverse/test/regression-11350-hub-undefined.js (hunk 1 above)
Comment (simbahax) [reply packages/babel-traverse/test/regression-11350-hub-undefined.js]: done!

File: packages/babel-traverse/test/regression-11350-hub-undefined.js (hunk 2 above)
Comment (simbahax) [reply packages/babel-traverse/test/regression-11350-hub-undefined.js]: done!

File: packages/babel-traverse/src/path/ancestry.ts (hunk 3 above)
Comment (simbahax) [reply packages/babel-traverse/src/path/ancestry.ts]: Without any changes, `path.getStatementParent` does not work correctly with this PR: 
[This](https://github.com/babel/babel/blob/main/packages/babel-traverse/test/ancestry.js#L67) test fails with the following error message:

```
path/ancestry > getStatementParent > should throw
    Error: expect(received).toThrow(expected)
    
    Expected pattern: /File\/Program node/
    
    Received function did not throw
        at file:///home/david/babel/packages/babel-traverse/test/ancestry.js?1766349415427:76:10
        at async file:///home/david/babel/node_modules/tinypool/dist/esm/entry/worker.js:72:20
```

This is caused by the (except for the hub) empty parentPath we pass to traverseNode. The if-condition will then always be false because path.isProgram and path.isFile return false as path.type and path.node are null for the path that has been found.

**Comment by simbahax** [comment]
Not sure why [CI / Test on Node.js 24 (pull_request)](https://github.com/babel/babel/actions/runs/20415549242/job/58658688373?pr=17672) is failing, this appears not to be related to this PR.

File: packages/babel-traverse/src/path/ancestry.ts (hunk 3 above)
Comment (JLHwung) [reply packages/babel-traverse/src/path/ancestry.ts]: Thanks, could you add a brief comment here? Maybe one day we should revisit the hub providing approach such that the `getStatementParent` doesn't have to check `path.node`, which is generally not nullish unless the node has been removed.

Comment (simbahax) [reply packages/babel-traverse/src/path/ancestry.ts]: Done - the comment should have been there in the first place :)

**Review by JLHwung — APPROVED** [review]
Thanks.

**Review by liuxingbaoyu — COMMENTED** [review]
Thanks!
I've moved the fix to prevent an empty `NodePath` from appearing at the top.
And added a `path.getPathLocation()` test, which previously returned `.program`.

**Review by liuxingbaoyu — APPROVED** [review]

**Comment by liuxingbaoyu** [comment]
CI is unrelated to this PR and will be fixed at https://github.com/babel/babel/pull/17692.

**Comment by nicolo-ribaudo** [comment]
Does this PR need to be included in Babel 7? If so, @simbahax would you mind opening a PR cherry-picking the commit (30af57a25649635268e0a9ecdfae99bdd5dda5b4) to the 7.x branch? Thank you!
