### PR TITLE
Keep user options intact in transformFile

### LINKED ISSUE #6885: transformFile generates incorrect AMD ids
I am not sure the following behavior is intended or not, hence this issue is more a question than a bug report. 

When using babel-core `transformFile` to perform async code conversion from es modules to AMD modules (with the `babel-plugin-transform-es2015-modules-amd` plugin), the generated AMD module ID is incorrect.
Let's take the following exemple:

### Input Code

```js
const { promisify } = require('util');
const babel = require('babel-core');
const transformFile = promisify(babel.transformFile);

const config = {
    presets: 'env',
    plugins: ['transform-es2015-modules-amd'],
    moduleRoot: 'ROOT',
    moduleIds: true,
    getModuleId (moduleName) {
        return moduleName;
    }
};

async function transpile () {
    const files = [
        './src/a.js',
        './src/b.js',
        './src/c.js'
    ]
    return Promise.all(files.map(async file => {
        let { code } = await transformFile(file, config);
        console.log(code);
        return Promise.resolve(code);
    }));
}
transpile();
```

### Current Behavior

The previous code outputs : 

```js
define("ROOT/./src/c", [], function () {
  "use strict";
});
define("ROOT/./src/c", [], function () {
  "use strict";
});
define("ROOT/./src/c", [], function () {
  "use strict";
});
```

### Expected Behavior

where you would expect it to be:

```js
define("ROOT/./src/a", [], function () {
  "use strict";
});
define("ROOT/./src/b", [], function () {
  "use strict";
});
define("ROOT/./src/c", [], function () {
  "use strict";
});
```

### Possible Solution

I've found that `transformFile` stores the file name inside the configuration object by modifying the reference of the user provided object.
Since this bit is done synchronously the configuration object will have the last file name (in our case './src/c.js'.

I would like to know if the "cloning" of the config is to be done by the user or by `transformFile`: that is to say turn my code from what is was to something like:

```js
async function transpile () {
    const files = [
        './src/a.js',
        './src/b.js',
        './src/c.js'
    ]
    return Promise.all(files.map(async file => {
        let { code } = await transformFile(file, {...config});
        console.log(code);
        return Promise.resolve(code);
    }));
}
```

or turn [this line](https://github.com/babel/babel/blob/master/packages/babel-core/src/transform-file.js#L21) into something like `let options = Object.assign({}, opts, { filename })`. `options` being used to keep the user provided object intact.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0
| Babylon          | 
| node             | 8.9.1
| npm              | 5.5.1
| Operating System | MacOS 10.12.6

Thank you 😸

### PR DESCRIPTION
**Pull request by nico29**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #6885 
| Patch: Bug Fix?          | y
| Major: Breaking Change?  | n
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR         | 
| Any Dependency Changes?  |
| License                  | MIT

As stated in #6885 I changed the user options handling in `transformFile` and `transformFileSync` to prevent the `filename` key from altering the user provided object.

(For the tests,  es2015/regression/6864 is failing, but was failing before any modifications)

### CODE REVIEW

File: packages/babel-core/test/api.js [hunk 1]
```diff
@@ -118,26 +118,31 @@ describe("api", function() {
...
-      },
-      function(err, res) {
-        if (err) return done(err);
-        assert.equal(res.code, "foo();");
-        done();
-      },
-    );
+    const options = {
+      babelrc: false,
+    };
```
Comment (nicolo-ribaudo) [inline packages/babel-core/test/api.js]: Can we `Object.freeze` this object? So it will throw when it is modified.

File: packages/babel-core/test/api.js [hunk 2]
```diff
@@ -118,26 +118,31 @@ describe("api", function() {
...
+      // keep user options untouched
+      assert.equal(Object.keys(options).length, 1);
+      done();
+    });
   });
 
   it("transformFileSync", function() {
+    const options = {
+      babelrc: false,
+    };
```
Comment (nicolo-ribaudo) [inline packages/babel-core/test/api.js]: Also this one.

File: packages/babel-core/test/api.js [hunk 3]
```diff
@@ -118,26 +118,31 @@ describe("api", function() {
...
+    babel.transformFile(__dirname + "/fixtures/api/file.js", options, function(
+      err,
+      res,
+    ) {
+      if (err) return done(err);
+      assert.equal(res.code, "foo();");
+      // keep user options untouched
+      assert.equal(Object.keys(options).length, 1);
```
Comment (nicolo-ribaudo) [inline packages/babel-core/test/api.js]: This isn't enough, since if a property value is modified it won't be caught.
```js
assert.deepEqual(options, { babelrc: false });
```

Comment (nico29) [reply packages/babel-core/test/api.js]: Yes you are right, I missed that.

**Comment by nico29** [comment]
@nicolo-ribaudo I've adapted the code as you suggested.

**Comment by Arfey** [comment]
fetch master and try again

**Comment by nico29** [comment]
@Arfey done, thanks

**Comment by loganfsmyth** [comment]
Perfect, thanks!

**Comment by nico29** [comment]
Awesome thank you all 🙌
