### PR TITLE
fix: report missing plugins on type exports

### LINKED ISSUE #7954: Incorrect parse error thrown for unexpected Flow code
## Bug Report

**Current Behavior**
An incorrect parse error is thrown when unexpected Flow code is present.

For the below, I see:

```
SyntaxError: node_modules/some-package/test.js: Support for the experimental syntax 'exportDefaultFrom' isn't currently enabled (3:8):

  1 | /* @flow */
  2 |
> 3 | export type Foo = number;
    |        ^
  4 |

Add @babel/plugin-proposal-export-default-from (https://git.io/vb4yH) to the 'plugins' section of your Babel config to enable transformation.
```

**Input Code**
```js
/* @flow */

export type Foo = number;
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (.babelrc, package.json, cli command)**

N/A (I think?)

**Environment**
- Babel version(s): `7.0.0-beta.46 (@babel/core 7.0.0-beta.46)`
- Node/npm version: v10.0.0
- OS: OSX 10.12.6
- Monorepo: N/A
- How you are using Babel: `cli`

### LINKED ISSUE #11331: The problem is export without default is not working react-native-gesture-handler
I have a react-native application.i use react-native-web for transform the application mobile to application web  The problem is export without default is not working in node_modules\react-native-gesture-handler\DrawerLayout.js

.babel.config.js:
```js
module.exports = {
  presets: [
    'module:metro-react-native-babel-preset',
    '@babel/preset-typescript',
  ],
  plugins: [
    ['react-native-web', {commonjs: true}],
    '@babel/plugin-proposal-export-default-from',
    '@babel/plugin-proposal-export-namespace-from',
    '@babel/plugin-proposal-object-rest-spread',
    ['@babel/plugin-proposal-class-properties', {loose: true}],
    [
      'module-resolver',
      {
        alias: {
          '^react-native$': 'react-native-web',
        },
      },
    ],
  ],
};

```

package.json
```json
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/plugin-proposal-export-default-from": "^7.8.3",
    "@babel/preset-flow": "^7.9.0",
    "@babel/runtime": "^7.5.5",
    "@react-native-community/eslint-config": "^0.0.5",
    "@testing-library/react-native": "^4.0.9",
    "@babel/plugin-proposal-class-properties": "^7.8.3",
    "@babel/plugin-proposal-export-namespace-from": "^7.8.3",
    "@babel/plugin-syntax-export-default-from": "^7.8.3",
    "babel-jest": "^24.9.0",
    "babel-loader": "^8.1.0",
    "babel-plugin-react-native-web": "^0.12.2",
    "eslint": "6.6.0",
    "jest": "^24.9.0",
    "jetifier": "^1.6.5",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.8.6",
    "url-loader": "^2.1.0",
  },
```

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #7954, closes #8080, fixes #11331
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

This PR throws more helpful errors on type exports supported by both Flow and TypeScript
```js
export type Foo = number;
```

It is also considered as a bug fix as type exports should never be considered as exportDefault from clause.

To simplify the parser logic, the current approach does not warn missing flow helpers for the following pedantic case:
```js
export type from = number;
```
which means it will still throw missing `exportDefaultFrom` plugins though it is a valid type exports. I think this situation still acceptable and practically only those flow codes with such statements as the first one will trigger this issue.

### CODE REVIEW

File: packages/babel-parser/src/parser/statement.js [hunk 1]
```diff
@@ -1834,10 +1834,28 @@ export default class StatementParser extends ExpressionParser {
...
+        return false;
+      }
+      if (
+        (value === "type" || value === "interface") &&
+        !this.state.containsEsc
+      ) {
+        const l = this.lookahead();
+        // If we see any variable name other than `from` after `type` keyword,
+        // we consider it as flow/typescript type exports
+        // note that this approach may fail on some pedentic cases
```
Comment (existentialism) [inline packages/babel-parser/src/parser/statement.js:1848]:
```suggestion
        // note that this approach may fail on some pedantic cases
```
