### PR TITLE
Fix class inheritance in IE10

### LINKED ISSUE #7892: Class inherit prototype uncorrect in IE10 using @babel/runtime@7.0.0-beta.46
## Bug Report

**Current Behavior**

The output is `undefined` in IE10.

**Input Code**

```js
function A() {}
A.prototype.a = 'aaa';

class B extends A {}
console.log(B.prototype.a);
```

**Expected behavior/code**

Expect output `aaa`, but got `undefined` in IE10. I also tested this in `@vue/cli@3.0.0-beta.9`, it have the same problem.

**Babel Configuration (.babelrc, package.json, cli command)**

**Environment**
- Babel version(s): v7.0.0-beta.36
- Node/npm version: Node 8/npm 5
- OS: OSX 10.13.4
- Monorepo [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

**Possible Solution**

**Additional context/Screenshots**

### LINKED ISSUE #7965: Verify and fix broken subclassing in IE10 due to change in getPrototypeOf usage
I'm 99% sure this is an issue, but I haven't tested myself.

Looks like the point was raised in https://github.com/babel/babel/pull/7020/files#r156839425, but at the time it was brushed off as not a blocker because the code was specifically for subclassing builtins, which won't work on older browsers anyway.

Since then however, in @jridgewell's https://github.com/babel/babel/pull/7674, this code has moved into more general use, meaning that it will affect any code performing subclassing.

We currently have the helper
```
helpers.getPrototypeOf = () => template.program.ast`
  export default function _getPrototypeOf(o) {
    _getPrototypeOf = Object.getPrototypeOf || function _getPrototypeOf(o) {
      return o.__proto__;
    };
    return _getPrototypeOf(o);
  }
`;
```
but on IE10, it already has a `getPrototypeOf`, but since it doesn't have a `setPrototypeOf`, IE10 will simply assign `.__proto__`, which means that the `getPrototypeOf` helper will not return the prototype assigned by the `setPrototypeOf` helper.

To clarify, this is all about our helpers. We use `helpers.getPrototypeOf(Foo).apply()` for `super()` for instance, so even in cases where `Object.setPrototypeOf` is unsupported, we still need `helpers.setPrototypeOf()` to do _something_ so that asking for the prototype back with `helpers.getPrototypeOf()` return the correct value, even if the prototype chain itself isn't actually manipulated. In Babel 6 this is accomplished by _always_ reading `.__proto__` first, so if we do `foo.__proto__` in `helpers.setPrototypeOf`, `helpers.getPrototypeOf` should read `.__proto__` even though `Object.getPrototypeOf` returns something different.

### PR DESCRIPTION
**Pull request by jridgewell**
This reverts commit f8ab9466d331871a90f458af40b14e8d831e0c29, and unfixes #7771, because of IE 10. 😩

Also updates the `getPrototypeOf` helper according to https://github.com/babel/babel/issues/7965#issuecomment-390046440.

Fixes #7892.
Fixes #7965.

### CODE REVIEW

File: packages/babel-helpers/src/helpers.js [hunk 1]
```diff
@@ -399,23 +399,31 @@ helpers.inherits = () => template.program.ast`
     if (typeof superClass !== "function" && superClass !== null) {
       throw new TypeError("Super expression must either be null or a function");
     }
-    setPrototypeOf(subClass.prototype, superClass && superClass.prototype);
+    subClass.prototype = Object.create(superClass && superClass.prototype, {
+      constructor: {
+        value: subClass,
+        enumerable: false,
```
Comment (Kovensky) [inline packages/babel-helpers/src/helpers.js]: It could be better to omit `enumerable: false` just to not force sham implementations to throw, but this would only happen on IE<9 anyway.

File: packages/babel-plugin-transform-classes/test/fixtures/get-set-loose/call-semantics-getter-defined-on-parent/exec.js [hunk 2]
```diff
@@ -20,11 +20,14 @@ class Obj extends Base {
     super.test(...[1, 2, 3]);
     return super.test(...arguments);
   }
-
-  test() {
+}
+Object.defineProperty(Obj.prototype, 'test', {
```
Comment (loganfsmyth) [inline packages/babel-plugin-transform-classes/test/fixtures/get-set-loose/call-semantics-getter-defined-on-parent/exec.js]: I don't understand what caused this change. Any idea? It doesn't seem like this should be split off like this.

File: packages/babel-helpers/src/helpers.js [hunk 3]
```diff
@@ -399,23 +399,31 @@ helpers.inherits = () => template.program.ast`
...
 `;
 
 helpers.getPrototypeOf = () => template.program.ast`
   export default function _getPrototypeOf(o) {
-    _getPrototypeOf = Object.getPrototypeOf || function _getPrototypeOf(o) {
-      return o.__proto__;
-    };
+    _getPrototypeOf = Object.setPrototypeOf
+      ? Object.getPrototypeOf
+      : function _getPrototypeOf(o) { return o.__proto__; };
```
Comment (loganfsmyth) [inline packages/babel-helpers/src/helpers.js]: I think I'd still want to fall back to `Object.getPrototypeOf` if `__proto__` falsy, since that was the old behavior.

File: packages/babel-helpers/src/helpers.js (hunk 1 above)
Comment (jridgewell) [reply packages/babel-helpers/src/helpers.js]: This is the spec inherits. I think changing it to be enumerable would break more people who use a for-in.

You can always use loose mode to support these IE9?

File: packages/babel-helpers/src/helpers.js (hunk 3 above)
Comment (jridgewell) [reply packages/babel-helpers/src/helpers.js]: Done.

File: packages/babel-helpers/src/helpers.js (hunk 1 above)
Comment (loganfsmyth) [reply packages/babel-helpers/src/helpers.js]: I think they just mean that the default is already `false` anyway, so leaving it out doesn't make anything fail, but allows polyfills to be less agressive in requiring enumerability on older platforms.

File: packages/babel-plugin-transform-classes/test/fixtures/get-set-loose/call-semantics-getter-defined-on-parent/exec.js (hunk 2 above)
Comment (jridgewell) [reply packages/babel-plugin-transform-classes/test/fixtures/get-set-loose/call-semantics-getter-defined-on-parent/exec.js]: This is the reason I filled #7771. https://github.com/jridgewell/babel/commit/ab403f3d6d768a98130ef3588feed71b941beaac#diff-0cd85dd4813df0687b8938547953d585L24

`test` here will be set on the subclass, but the super defines a `get test`, so it'll throw.

File: packages/babel-helpers/src/helpers.js (hunk 1 above)
Comment (jridgewell) [reply packages/babel-helpers/src/helpers.js]: Ahh, ok.

File: packages/babel-plugin-transform-classes/test/fixtures/get-set-loose/call-semantics-getter-defined-on-parent/exec.js (hunk 2 above)
Comment (loganfsmyth) [reply packages/babel-plugin-transform-classes/test/fixtures/get-set-loose/call-semantics-getter-defined-on-parent/exec.js]: Ahh got it.

File: packages/babel-helpers/src/helpers.js [hunk 4]
```diff
@@ -399,23 +399,34 @@ helpers.inherits = () => template.program.ast`
...
 helpers.getPrototypeOf = () => template.program.ast`
   export default function _getPrototypeOf(o) {
-    _getPrototypeOf = Object.getPrototypeOf || function _getPrototypeOf(o) {
-      return o.__proto__;
-    };
+    if (Object.setPrototypeOf && Object.getPrototypeOf) {
+      _getPrototypeOf = Object.getPrototypeOf;
+    } else {
+      _getPrototypeOf = function _getPrototypeOf(o) {
+        return o.__proto__;
```
Comment (loganfsmyth) [inline packages/babel-helpers/src/helpers.js]: I think my comment here was misinterpreted. My concern was that this does not preserve the behavior changed in https://github.com/babel/babel/pull/7675/files#diff-a6fddd06921a2b0da9eb1fb68cd794b9L14

Old super calls used to be `(Foo.__proto__ || Object.getPrototypeOf(Foo)).call`, but here we assume that `__proto__` is the source of truth and will always have a value, instead of falling back to `Object.getPrototypeOf` of `__proto__` is falsy.

Comment (jridgewell) [reply packages/babel-helpers/src/helpers.js]: Wow, that was dyslexic of me. Fixed.

**Comment by benjamn** [comment]
How soon can this be released? Meteor implemented [a pretty nasty workaround](https://github.com/meteor/meteor/blob/e3bac92c82c56acb65c42f8e4bfa7b244666f107/packages/babel-runtime/legacy.js#L17-L38) for this, which I would love to revert before shipping Meteor 1.7.

**Comment by loganfsmyth** [comment]
@benjamn Likely tomorrow. What's your timetable for 1.7?

**Comment by benjamn** [comment]
Tomorrow is great. We're on RC #11 right now, but I think this is a good reason to wait. I'm giving a talk at [Meteor Night](https://blog.meteor.com/come-to-meteor-night-on-may-30-in-san-francisco-a7472b81d147) next Wednesday, but we can just ship the workaround if the next Babel beta somehow doesn't get released by then.
