### PR TITLE
[ts] Allow keywords in tuple labels

### LINKED ISSUE #13702: [Bug]: Typescript plugin fails on named tuple positions where the name is a reserved word in JS
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```
type FuncWithDescription = [
  function: (...args: any[]) => any,
  string: string
]
```

https://babeljs.io/repl#?browsers=defaults&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=C4TwDgpgBAYgrgOwMYHUCWwAWARCBnJAJzTGDQHsEoBeKAbQCgooAzRJMygLigAoA6QQENCAczw8hCEHQC6AShoA-KFJAAaJlDzBiCUTx17RDWQwZJKO1gnRZcBYqQoIJsdnZz4iJTgjk09FrMdLwAHlwIcAC2AEYQhIrUKmHqUABEhBDAcIRUWNBRcQnpsprMIeGRMfGEaSDVxYnKUGEAVBoZ0XAANmRgPSBQBVBFtXilpkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2%2Ctypescript&prettier=false&targets=&version=7.15.3&externalPlugins=&assumptions=%7B%7D

### Configuration file name

_No response_

### Configuration

See REPL link

#### Current
It throws at line 2: `/repl.tsx: Unexpected token (2:2)`
If you rename `function` to `fn`, then
it throws at line 3: `Tuple members must be labeled with a simple identifier. (3:2)`

#### Expected
It does not throw an error on either line. Why would I expect this? Because TS is totally fine with this same code: https://www.typescriptlang.org/play?ts=4.0.2#code/C4TwDgpgBAYgrgOwMYHUCWwAWARCBnJAJzTGDQHsEoBeKAbQFgAoKVqAM0STMoC4oAFADoRAQ0IBzPP1EIQdALoBKagD4oskABpmbKHmDEEE-gaMTmC5sySUDHBOiy4CxUhQTTYXJznxESHgRFGnpdNjoBAA9eBDgAWwAjCEIlGnUorSgAIkIIYDhCKixoOKSU7IUdFgjo2ITkwiyQevLU9KgogCptHPi4ABsyMAGQKBKoMsa8SssgA

### Environment

See REPL link for env details

### Possible solution

There are two ways to fix this problem, in my opinion

#### Option 1: Updated docs, and better error messages

Indicate in the docs (just like with [other caveats](https://babeljs.io/docs/en/babel-plugin-transform-typescript#caveats)) that there are certain tokens that are not acceptable for named tuple positions.

Then, ensure that the errors thrown in my example above clearly state this problem and/or reference the newly updated docs. I think the second error (`Tuple members must be labeled with a simple identifier.`) is possibly acknowledging this discrepancy, but it is not clear to me that the error is a known caveat vs an actual TS syntax issue. (The first error thrown against the word `function`, though, is quite vague.)

#### Option 2: Update the TypeScript plugin to handle these names

I do not know how many words fail in the Babel plugin, and yet succeed in TS. I do know that the following are in the list:

- `function`
- `string`
- `number`

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Harpica**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #13702, Closes #13743
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | Yes
| Documentation PR Link    | No
| Any Dependency Changes?  | No
| License                  | MIT

Fixes Typescript compiler failure while the name (label) in tuple is a keyword:
- add keyword check before parsing first token
- if it is keyworkd - treat it as Identifier
- else - keep the logic

Can't fix another problem mentioned in the issue: 
``` typescript 
type FuncWithDescription = [
  function: (...args: any[]) => any, // fixed
  string: string // not fixed, throws error 
]

```
It seems to be called by this line of code (1116 line)
``` typescript 
 this.raise(TSErrors.InvalidTupleMemberLabel, { at: type });
```

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15423"></a>

### CODE REVIEW

**Comment by JLHwung** [comment]
Thanks for the PR!

- For third-party parser test failure, please update the allowlist:
```
make bootstrap-typescript && make test-typescript-update-allowlist
```

- For Babel 8 breaking changes test:

Please duplicate the test to `tuple-keyword-labeled-babel-7`, set `"BABEL_8_BREAKING": "false"` in `options.json` of the duplicated Babel 7 test.
Update the current test options with `"BABEL_8_BREAKING": true`.
Re-run `OVERWRITE=1 yarn jest` and `BABEL_8_BREAKING=1 OVERWRITE=1 yarn jest`.

**Comment by liuxingbaoyu** [comment]
Does the failure of third-party parser tests seem unexpected?

**Comment by Harpica** [comment]
@JLHwung, thank you for your advice!

I fixed the second issue (on Babel 8), but I can't perform these 2 commands for 3d parties issue:
image
image

(My OS is Windows)

**Comment by liuxingbaoyu** [comment]
This command does not support windows yet, do you have wsl?
If not, try
`git clone --single-branch --shallow-since=2022-04-01 https://github.com/microsoft/TypeScript.git ./build/typescript`

**Comment by Harpica** [comment]
@liuxingbaoyu Thank you! WSL helped c: 
Waiting for review

**Review by nicolo-ribaudo — DISMISSED** [review]
Thank you!

**Review by nicolo-ribaudo — COMMENTED** [review]
There is a possible alternative solution that would also fix the `string:` case.

Instead of checking if `tokenIsKeyword`, we can check if we have a "word" followed by a colon:
```js
const isLabeled = tokenIsKeywordOrIdentifier(this.state.type) && this.lookaheadCharCode() === charCodes.colon;
```

and then if `isLabeled` is true we parse the label:
```js
let label;
if (isLabeled) {
  label = this.parseIdentifier(true);
  this.expect(tt.colon);
}

const type = this.tsParseType();
```

**Comment by Harpica** [comment]
@nicolo-ribaudo Hello!
Thank you for suggestion, currenty I'm trying to implement it and it seems that it doesn't help with the case with question mark (labeled optional tuple): `[identifier?: type]`
Is there a way to look for more than one token ahead? Also, why does `string: string` fail check for 
```typescript
 if (
      type.type === "TSTypeReference" &&
      !type.typeParameters &&
      type.typeName.type === "Identifier"
    ) 
```
If this is the way to find types that could be converted to identifiers

**Comment by nicolo-ribaudo** [comment]
The reason is that it's parsed as a `TSStringKeyword`, by the `keywordTypeFromName` function.

Maybe this would work, trying to parse the identifier both as a type and as a label at the same time if it's followed by `?`:

```js
let label;
let optional;
let type;

const isWord = tokenIsKeywordOrIdentifier(this.state.type);
if (isWord && this.lookaheadCharCode() === charCodes.colon) {
  label = this.parseIdentifier(true);
  this.expect(tt.colon);
  type = this.tsParseType();
} else if (isWord && this.lookaheadCharCode() === charCodes.questionMark) {
  const startLoc = this.state.loc;
  const wordName = this.state.value;

  optional = true;

  const typeOrLabel = this.tsParseNonArrayType();

  if (this.lookaheadCharCode() === charCodes.colon) {
    label = this.createIdentifier(this.startNodeAt(startLoc), wordName);
    this.expect(tt.questionMark);
    this.expect(tt.colon);
    type = this.tsParseType();
  } else {
    type = typeOrLabel;
    this.expect(tt.questionMark);
  }
} else {
  type = this.tsParseType();
}
```

Or if you prefer, you could update the current `type.type === "TSTypeReference"` check to compare it with all the possible types introduced by the `keywordTypeFromName` function.

File: packages/babel-parser/src/plugins/typescript/index.ts [hunk 1]
```diff
@@ -1092,47 +1091,87 @@ export default (superClass: ClassWithMixin<typeof Parser, IJSXParserMixin>) =>
...
+          type = this.tsParseType();
+        } else {
+          labeled = false;
+          type = typeOrLabel;
+          this.expect(tt.question);
+        }
+      } else {
+        type = this.tsParseType();
+        optional = this.eat(tt.question);
+        labeled = this.eat(tt.colon);
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/src/plugins/typescript/index.ts:1133]: When can this be followed by a colon?

Comment (Harpica) [reply packages/babel-parser/src/plugins/typescript/index.ts:1133]: In case we have invalid label in tuple followed by colon, which fails `tokenIsKeywordOrIdentifier` check?

I'm sorry to bother you, this issue seemed easier than it really is for me

Comment (Harpica) [reply packages/babel-parser/src/plugins/typescript/index.ts:1133]: I was thinking about the case described in "tuple-invalid-label-1" test: `type T = [x.y: A];` which should throw error `TSErrors.InvalidTupleMemberLabel` to be passed

Comment (nicolo-ribaudo) [reply packages/babel-parser/src/plugins/typescript/index.ts:1133]: Ok :+1: Maybe add a comment in the code with that example, explaining that it can only happen in that case.
Also, probably we can move the `TSErrors.InvalidTupleMemberLabel` inside this block so that it's throw in the same place as where we parse the invalid code.

**Comment by liuxingbaoyu** [comment]
Friendly ping. :)

**Comment by Harpica** [comment]
@liuxingbaoyu 
I've fetched fresh commits and seems like tests are passed :)
I'm sorry, but what do you mean by modifying branch? I can change base branch in PR (babel:main), but I cannot change my branch (without closing PR and opening new, which doesn't seem to be good)

**Comment by liuxingbaoyu** [comment]
Ah, sorry! I have not tried this. For `forked/main` I can't make edits to help finish if you don't have time anymore. Please ignore it if you are continuing. :)

File: packages/babel-parser/test/fixtures/typescript/types/tuple-keyword-labeled-babel-7/input.ts [hunk 2]
```diff
@@ -0,0 +1,4 @@
+type FuncWithDescriptionBabel7 = [
+  function: (...args: any[]) => any,
+  string: string
```
Comment (JLHwung) [inline packages/babel-parser/test/fixtures/typescript/types/tuple-keyword-labeled-babel-7/input.ts:3]: Can you augment the test case to include optional keyword labeled tuple? such as `void?: string`

**Review by JLHwung — APPROVED** [review]
For future PRs: we should recover from this case:

```ts
type t = [label: string?]
```
which may happen when users are migrating labelless tuple to a labeled one.

Currently TS throws "A labeled tuple element is declared as optional with a question mark after the name and before the colon, rather than after the type." and Babel throws unrecoverable errors.
