### PR TITLE
fix(typescript): erase type exports

### LINKED ISSUE #6065: Exporting of TypeScript types separate from their declarations doesn't get erased
Hi, I just tried out the new `babel-preset-typescript` in version 7.0.0-alpha.19 with much anticipation. Unfortunately I discovered that it doesn't erase types that are exported separate from their declaration:

```ts
type Foo = number
export { Foo }
```

gets transformed to

```ts
export { Foo }
```

which of course generates an error if you try to run it: `ReferenceError: Foo is not defined`. It correctly deletes the export if you write

```ts
export type Foo = number
```

### LINKED ISSUE #7640: [plugin-transform-typescript] Default or named exported interface result in runtime error
### Input Code
```ts
interface IEvent {
  type: string;
}

export default IEvent;
```
### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    ["@babel/env", {
      "targets": {
        "browsers": ["last 2 versions"],
        "node": "6"
      },
      "loose": true,
      "useBuiltIns": false
    }],
    "@babel/preset-stage-3",
    "@babel/typescript"
  ],
  "plugins": [
    ["@babel/plugin-transform-runtime", {
      "helpers": true,
      "polyfill": false,
      "regenerator": false,
      "moduleName": "@babel/runtime"
    }]
  ]
}
```

### Expected Behavior

Either:
* Not referencing (thus exporting) IEvent at all
* Or, setting IEvent to undefined/null/anything so parsing the file doesn't result in a runtime error

### Current Behavior

TS compilation results in:

```js
"use strict";

exports.__esModule = true;
exports.default = void 0;
var _default = IEvent; // <<< IEvent doesn't exist!
exports.default = _default;
```

Which results in the runtime error:
```js
Uncaught ReferenceError: IEvent is not defined
```

### Possible Solution
When stripping interfaces (or probably any non-value types), either:
* leave a placeholder value for exports
* or, detect references in exports and remove those exports

### Context
I'm using and re-exporting interfaces in my node modules' 'index.ts' file, so you can use them in other TypeScript projects, e.g.:

```ts
// index.ts
import { default as IEvent } from "./lib/IEvent";

// app.ts
import { IEvent } from "seng-event";
```

When publishing the package, the `tsc` also runs to generate `d.ts` files, which makes the code above work in a TS project (babel strips types and generates JS code, tsc generates the definitions).

**Workaround**
A workaround is to use named exports, since the faulty generated code only happens when using default exports.

```ts
export interface IEvent {
  type: string;
}
```

When using a named export, the export itself will be removed along with the interface, since it's a single statement. The (now empty) file will be imported somewhere, but will just result in an undefined value. This shouldn't matter, since Interfaces themselves are not used at runtime.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  7.0.0-beta.42
| node             | 8.9.1
| npm              | 5.5.1
| Operating System | macOS 10.13.3

### Related

Different but related to https://github.com/babel/babel/issues/7118 (where that's a syntax/parsing error, while this current issue is a runtime error)

---

Edit by @nicolo-ribaudo

This also doesn't work with `export { interface }` (https://github.com/babel/babel/issues/7641) - [repl](http://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=FASwdgLgpgTgZgQwMZQAQEkCyBPAwgGwQGcjUBvYVVADwC5UwBXAWwCNYBuS1beptzsAC-wYEkIlUOAsVJRq0MABNSWPBNJkRweQAcA9jAjkp62QBoM0jaiFcgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=false&presets=typescript%2Cenv&prettier=false&targets=Node-8&version=7.0.0-beta.34&envVersion=7.0.0-beta.33)

### LINKED ISSUE #9480: error: bundling failed: SyntaxError: { path }\PinCode\index.ts: Exporting local ”IPinCodeParams“, which is not declared
## Bug Report

**Current Behavior**
I created a new project. I have special folders for interfaces, types and etc. I will have a lot of them, so I import them into one file and export them from there. When I want to export multiple interfaces I get an error:
```js
error: bundling failed: SyntaxError: C:\Users\QWERTY\Desktop\TestProjects\2019\TestProject\node_modules\react-native\scripts\src\types\PinCode\index.ts: Exporting local "IPinCodeParams", which is not declared.
  13 | }
  14 |
> 15 | export { PinStatus, IPinCodeParams }
     |                     ^
    at File.buildCodeFrameError (C:\Users\QWERTY\Desktop\TestProjects\2019\TestProject\node_modules\@babel\core\lib\transformation\file\file.js:261:12)
    at NodePath.buildCodeFrameError (C:\Users\QWERTY\Desktop\TestProjects\2019\TestProject\node_modules\@babel\traverse\lib\path\index.js:157:21)
    at getLocalMetadata (C:\Users\QWERTY\Desktop\TestProjects\2019\TestProject\node_modules\@babel\helper-module-transforms\lib\normalize-and-load-metadata.js:281:22)
    at child.get.forEach.spec (C:\Users\QWERTY\Desktop\TestProjects\2019\TestProject\node_modules\@babel\helper-module-transforms\lib\normalize-and-load-metadata.js:315:11)
    at Array.forEach (<anonymous>)
    at programPath.get.forEach.child (C:\Users\QWERTY\Desktop\TestProjects\2019\TestProject\node_modules\@babel\helper-module-transforms\lib\normalize-and-load-metadata.js:307:33)
    at Array.forEach (<anonymous>)
    at getLocalExportMetadata (C:\Users\QWERTY\Desktop\TestProjects\2019\TestProject\node_modules\@babel\helper-module-transforms\lib\normalize-and-load-metadata.js:294:27)
    at getModuleMetadata (C:\Users\QWERTY\Desktop\TestProjects\2019\TestProject\node_modules\@babel\helper-module-transforms\lib\normalize-and-load-metadata.js:86:21)
```

**Input Code / Babel Configuration (.babelrc, package.json, cli command)**
**package.json**
```js
{
  "name": "TestProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "node node_modules/react-native/local-cli/cli.js run-android",
    "ios": "node node_modules/react-native/local-cli/cli.js run-ios",
    "lint": "yarn tslint && yarn typecheck",
    "tslint": "tslint --project tsconfig.json --config tslint.json src/**/*.ts{,x} --format stylish",
    "typecheck": "tsc --project tsconfig.json --noEmit",
    "postinstall": "typesync",
    "type-sync": "typesync"
  },
  "husky": {
    "hooks": {
      "pre-commit": "yarn lint",
      "pre-push": "yarn lint"
    }
  },
  "dependencies": {
    "mobx": "^4.9.2",
    "mobx-persist": "^0.4.1",
    "mobx-react": "^5.4.3",
    "react": "16.8.0",
    "react-native": "0.58.4",
    "react-native-vector-icons": "^6.2.0",
    "react-navigation": "^2.18.1"
  },
  "devDependencies": {
    "@babel/plugin-proposal-class-properties": "^7.3.0",
    "@babel/plugin-proposal-decorators": "^7.3.0",
    "@types/babel-core": "6.25.5",
    "@types/jest": "24.0.0",
    "@types/prettier": "^1.16.0",
    "@types/react": "16.8.2",
    "@types/react-native": "0.57.34",
    "@types/react-native-vector-icons": "^4.6.4",
    "@types/react-navigation": "^3.0.1",
    "@types/react-test-renderer": "16.8.0",
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "24.1.0",
    "babel-plugin-module-resolver": "^3.1.3",
    "husky": "^1.3.1",
    "jest": "24.1.0",
    "jsc-android": "236355.1.1",
    "metro-react-native-babel-preset": "0.51.1",
    "mobx-logger": "^0.7.1",
    "prettier": "^1.16.4",
    "react-native-typescript-transformer": "^1.2.11",
    "react-test-renderer": "16.6.3",
    "tslint": "^5.12.1",
    "tslint-config-prettier": "^1.18.0",
    "tslint-eslint-rules": "^5.4.0",
    "tslint-react": "^3.6.0",
    "typescript": "^3.2.4",
    "typesync": "^0.4.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**.babelrc**
```js
{
  "presets": [
    "module:metro-react-native-babel-preset",
  ],
  "plugins": [
    [
      "@babel/plugin-proposal-decorators",
      {
        "legacy": true
      }
    ],
    "@babel/transform-react-jsx-source",
    [
      "module-resolver",
      {
        "root": [
          "/src"
        ],
        "alias": {
          "@api": "./src/api",
          "@actions": "./src/actions",
          "@components": "./src/components",
          "@constants": "./src/constants",
          "@hocs": "./src/hocs",
          "@managers": "./src/managers",
          "@locales": "./src/locales",
          "@reducers": "./src/reducers",
          "@screens": "./src/screens",
          "@static": "./src/static",
          "@stores": "./src/stores",
          "@styles": "./src/styles",
          "@types": "./src/types",
          "@utils": "./src/utils"
        }
      }
    ],
  ]
}
```

**tsconfing.json**
```js
{
  "compilerOptions": {
    "target": "es2015",
    "module": "commonjs",
    "moduleResolution": "node",
    "jsx": "react-native",
    "baseUrl": "./src",
    "outDir": "./dist",
    "allowSyntheticDefaultImports": true,
    "declaration": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noEmit": true,
    "noImplicitAny": false,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "pretty": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "strict": true,
    "paths": {
      "@api": [
        "api"
      ],
      "@actions": [
        "actions"
      ],
      "@components": [
        "components"
      ],
      "@constants": [
        "constants"
      ],
      "@hocs": [
        "hocs"
      ],
      "@managers": [
        "managers"
      ],
      "@locales": [
        "locales"
      ],
      "@reducers": [
        "reducers"
      ],
      "@screens": [
        "screens"
      ],
      "@static": [
        "static"
      ],
      "@stores": [
        "stores"
      ],
      "@styles": [
        "styles"
      ],
      "@types": [
        "types"
      ],
      "@utils": [
        "utils"
      ]
    }
  },
}
```

**tslist.json**
```js
{
  "defaultSeverity": "error",
  "extends": [
    "tslint-config-prettier",
    "tslint-eslint-rules",
    "tslint-react",
    "tslint:latest"
  ],
  "jsRules": {},
  "rules": {
    "await-promise": false,
    "interface-over-type-literal": false,
    "jsx-alignment": true,
    "jsx-boolean-value": false,
    "jsx-no-bind": true,
    "jsx-no-lambda": false,
    "max-classes-per-file": false,
    "member-access": false,
    "member-ordering": false,
    "no-constant-condition": false,
    "no-duplicate-imports": false,
    "no-empty": false,
    "no-implicit-dependencies": false,
    "no-submodule-imports": false,
    "object-literal-sort-keys": false,
    "ordered-imports": false,
    "quotemark": [
      true,
      "single",
      "jsx-single",
      "avoid-escape"
    ],
    "semicolon": [
      true,
      "always"
    ],
    "trailing-comma": [
      true,
      {
        "singleline": "never",
        "multiline": "always"
      }
    ],
    "triple-equals": [
      true,
      "allow-undefined-check"
    ]
  },
  "linterOptions": {
    "exclude": [
      "./src/typings/**/*.d.ts"
    ]
  },
  "rulesDirectory": []
}
```

[Reference to the source project (Github)][1]

  [1]: https://github.com/SergeyMyssak/TestProject

**Expected behavior/code**
I have this folder structure:
```
android\
ios\
node_modules\
src\
--->constants\
       |--->colors.ts
       |--->fonts.ts
       |--->index.ts
--->router\
       |--->index.ts
--->screen\
       |--->Splash\
               |--->containers\
                      |--->index.ts
                      |--->SplashContainer.tsx
               |--->views\
                      |--->index.ts
                      |--->SplashView.tsx
               |--->index.tsx
       |--->index.ts
--->types\
       |--->PinCode\
               |--->index.tsx
       |--->index.tsx
--->App.tsx
.babelrc
*
*
*
package.json
rn-cli.config.js
tsconfig.json
tslint.json
```

In the file **"PinCode"** I have an enum and an interface. 

When I write so (all right):
```js
export enum PinStatus {
  New = 'new',
  Confirm = 'confirm',
  Unlock = 'unlock',
  Edit = 'edit',
}

export interface IPinCodeParams {
  status: PinStatus;
  onComplete: () => void;
  onClose?: () => void;
  originalCode?: string;
}
```

But when I write so (I get the error):
```js
enum PinStatus {
  New = 'new',
  Confirm = 'confirm',
  Unlock = 'unlock',
  Edit = 'edit',
}

interface IPinCodeParams {
  status: PinStatus;
  onComplete: () => void;
  onClose?: () => void;
  originalCode?: string;
}

export { PinStatus, IPinCodeParams };
```

I have created some completely new projects, tried to rewrite this project several times, but nothing came out. I finally got this error anyway. Why do I get this error? How to fix it?

**Environment**
- Babel version(s): I don't know, but I use "babel-core": "7.0.0-bridge.0"
- Node/npm/yarn version: v10.4.1 / v6.5.0 / v1.9.4
- OS: Windows 10
- How you are using Babel: cli

### LINKED ISSUE #9763: New @babel/parser early errors break by-name typescript exports
## Bug Report

**Current Behavior**
`@babel/parser` doesn't consider identifiers declared with typescript syntax as identifiers in scope.

**Input Code**

```ts
enum Test {}

export { Test as default }
```

**Expected behavior/code**
`export`s of typescript types should not be a build error.

This case is particularly strange as `Test` is _actually_ a concrete value; it's just declared with a typescript declaration.

This is the expected output, for reference:

```js
var Test;

(function (Test) {})(Test || (Test = {}));

export { Test as default }
```

Direct `export enum Test {}` is unaffected.

**Babel Configuration (.babelrc, package.json, cli command)**

Way too big, but just adding `@babel/plugin-syntax-typescript` to the REPL is sufficient to reproduce it. `@babel/plugin-transform-typescript` doesn't help as the error happens before any transforms can run.

**Environment**
- Babel version(s): 7.4.2
- Node/npm version: 11.10.0
- OS: macOS 18.2.0
- Monorepo: yes
- How you are using Babel: `babel-jest` / `babel-loader`

**Possible Solution**
Identifiers declared with `type`, `enum`, `interface` (and `namespace`) need to be considered as valid for `export`ing when the `typescript` plugin is enabled.

This same problem affects `flow` but the other way around. The following code is "valid syntax" in both flow and typescript; but babel can only parse the flow version, which is incorrect at runtime as flow requires explicitly annotating the export as a type export:

```ts
type Foo = {}
export { Foo }
```

### PR DESCRIPTION
**Pull request by airato**
some context https://github.com/babel/babel/pull/9766#issuecomment-479239380
cc @nicolo-ribaudo 

| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #9763, Fixes #9480, Fixes #6065, Fixes #7640
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

File: packages/babel-plugin-transform-typescript/src/index.js [hunk 1]
```diff
@@ -94,6 +135,26 @@ export default declare((api, { jsxPragma = "React" }) => {
         }
       },
 
+      ExportNamedDeclaration(path, { exportableTSNames }) {
+        // remove export declaration if it's exporting only types
+        if (
+          path.node.specifiers.length > 0 &&
+          !path.node.specifiers.find(
+            exportSpecifier =>
+              exportableTSNames.indexOf(exportSpecifier.local.name) === -1,
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-typescript/src/index.js]: 1) `exportableTSNames` should probably be a `new Set()`?
2) I don't remember if `@babel/traverse`'s scope tracking supports TypeScript. If it does, we could check `path.sope.getBinding(exportSpecifier.local.name)` instead of using `exportableTSNames`.

Comment (airato) [reply packages/babel-plugin-transform-typescript/src/index.js]: `scope.getBinding` doesn't seem to work for TS type declarations

**Comment by nicolo-ribaudo** [comment]
Could you also add a test for an interface exported before its declaration? It seems to be working on the repl ([repl with ts support](https://deploy-preview-2019--babel.netlify.com/repl?#?babili=false&browsers=&build=10764&builtIns=false&spec=false&loose=false&code_lz=JYOwLgpgTgZghgYwgAgILIN4F8BQOIAeADgPZRiZoA0yAQjQMLK46iSyIq2YsBucUZAwDcQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&filename=repl.ts&lineWrap=true&presets=typescript&prettier=false&targets=&version=7.4.4%2Bpr.9944&externalPlugins=)), but it's better to test it.

**Comment by nicolo-ribaudo** [comment]
Thanks!

**Comment by sebinsua** [comment]
@Sergiioo Not sure when the next version of Babel with this inside it will be released but this will be worth an upgrade.
