### PR TITLE
Fix for #4943 "Calling an async function with default parameter as function for arguments checking handled synchonous"

### LINKED ISSUE #4943: Calling an async function with default parameter as function for arguments checking handled synchonous
Babel throws a synchronous exception during calltime evaluation of default params
### Input Code  

```js
function mandatory(paramName) {
    throw new Error(`Missing parameter: ${paramName}`)
}

async function foo({ a, b = mandatory('b') }) {
    return Promise.resolve(b)
}

// uses chai.assert and chai-as-promised
describe('foo', () => {
    it('should return a rejected promise', async () => {
        const promise = foo({ a: 'hi' })
        assert.isRejected(promise, /Error: Missing parameter: b/)
    })
})
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": ["es2015"],
  "plugins": [
    "transform-object-rest-spread",
    "transform-async-to-generator"
  ]
}
```

### Expected Behavior

This test fails with an error:

```  
Error: Missing parameter: b
```  
because this exception is thrown outside the async flow. 
 
In the latest Chrome (which supports async functions with a flag) and in Firefox 52, this code works as expected (i.e. the promise is rejected):

### Possible Solution
currently this code will be compiled to:  

```js
var foo = function () {
    var _ref = _asyncToGenerator(regeneratorRuntime.mark(function _callee(_ref2) {
        var _ref2$a = _ref2.a,
            a = _ref2$a === undefined ? 'a' : _ref2$a,
            _ref2$b = _ref2.b,
            b = _ref2$b === undefined ? mandatory('b') : _ref2$b;
        return regeneratorRuntime.wrap(function _callee$(_context) {
            while (1) {
                switch (_context.prev = _context.next) {
                    case 0:
                        return _context.abrupt('return', Promise.resolve(b));

                    case 1:
                    case 'end':
                        return _context.stop();
                }
           }
       }, _callee, this);
    }));

    return function foo(_x) {
        return _ref.apply(this, arguments);
    };
}();

function _asyncToGenerator(fn) { 
    return function () { 
         var gen = fn.apply(this, arguments); 
         return new Promise(function (resolve, reject) { 
             function step(key, arg) { 
                 try { 
                     var info = gen[key](arg); 
                     var value = info.value; 
                 } catch (error) { 
                     reject(error); return; 
                 } 
                 if (info.done) { 
                     resolve(value); 
                 } else { 
                     return Promise.resolve(value).then(function (value) { 
                         step("next", value); 
                     }, 
                     function (err) { 
                         step("throw", err); 
                     }); 
                 } 
             } 
             return step("next"); 
         }); 
     }; 
 }
```
this code shows that the resolution is put in the wrong place of the code. it may be pushed to the
`regeneratorRuntime.wrap` callback function?

### Context
I am using async functions and default parameters with evaluation at call time.

With the default parameters I use a function to check if a value is provided or not.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.5.5
|babel-cli | 6.6.5 
|babel-eslint | 6.0.4 
|babel-plugin-transform-async-to-generator | 6.8.0 
|babel-plugin-transform-object-rest-spread | 6.8.0 
|babel-polyfill | 6.9.1 
|babel-preset-es2015 |  6.6.0 
|babel-register | 6.7.2 
| node             | 6.5.0
| npm              | 3.10.3
| Operating System | macosx 10.12.1

### PR DESCRIPTION
**Pull request by hulkish**
| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          | yes
| Major: Breaking Change?  | no
| Minor: New Feature?      | no
| Deprecations?            | no
| Spec Compliancy?         | yes
| Tests Added/Pass?        | yes
| Fixed Tickets            | Fixes #4943 
| License                  | MIT
| Doc PR                   | no
| Dependency Changes       | no

This change reflects this suggestion: https://github.com/babel/babel/issues/4943#issuecomment-298263313

### CODE REVIEW

**Comment by spicyj** [comment]
This seems simple enough to me. Can you write a test for this?

**Comment by hulkish** [comment]
@spicyj sure, is there an area i should focus on for this test? Like... should I look for if the arguments are being applied outside of the promise block?

**Comment by spicyj** [comment]
I think testing for the original issue – something that throws immediately upon execution – and verifying the correct behavior at runtime would be the best test here.

**Comment by hulkish** [comment]
@spicyj gotcha, ill work on that now

**Comment by hulkish** [comment]
@spicyj hows that?

**Comment by spicyj** [comment]
Sorry, I should have been clearer. Can you add an exec.js test as described in https://github.com/babel/babel/blob/7.0/CONTRIBUTING.md#writing-tests that verifies the code actually works at runtime? That is, not just checking the compiled output. That way, if someone changes this in the future, it will be obvious why the function call needs to be inside the `new Promise()`.

Also, not sure it makes sense to have this test in packages/babel-core – any reason you didn't put both in the async-to-generator folder?

**Comment by hulkish** [comment]
@spicyj no reason, ill move it

**Comment by hulkish** [comment]
@spicyj better?

**Comment by hulkish** [comment]
I agree the test can be simpler, but i think its good to check for doesNotThrow & also a check to see that the asynchronously thrown error is caught

File: packages/babel-helpers/src/helpers.js [hunk 1]
```diff
@@ -216,8 +216,10 @@ helpers.asyncGeneratorDelegate = template(`
 helpers.asyncToGenerator = template(`
   (function (fn) {
     return function () {
-      var gen = fn.apply(this, arguments);
+      var _args = arguments;
+      var _promiseWrapper = this;
       return new Promise(function (resolve, reject) {
```
Comment (loganfsmyth) [inline packages/babel-helpers/src/helpers.js]: If you want to change this to an arrow function, that's fine with me. Seems like it would be worth it.

File: packages/babel-plugin-transform-async-to-generator/test/fixtures/regression/4943/exec.js [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+  if (err instanceof AssertionError) {
+    throw err;
+  }
+});
+
+barUsage().catch((err) => {
+  if (err instanceof AssertionError) {
+    throw err;
+  }
+});
```
Comment (loganfsmyth) [inline packages/babel-plugin-transform-async-to-generator/test/fixtures/regression/4943/exec.js]: I believe the runner expects a promise to be returned if it is going to have async operations that need to be waited for. As it is, this will queue up a bunch of async operations, but not wait for them to complete before moving on to a new test. 

I guess the easiest solution might be to wrap this whole test in `return (async function(){ ... })();`?

**Comment by hulkish** [comment]
@spicyj @loganfsmyth ok:
- simplified the tests
- made the exec ran test return an async function
- improved original change to asyncToGenerator helper template by using an arrow function on returned promise block. (This gets transformed to the same behavior: 
```js
function _asyncToGenerator(fn) { return function () { var _this = this, _arguments = arguments; return new Promise(function (resolve, reject) { var gen = fn.apply(_this, _arguments); [...]
```

**Comment by hulkish** [comment]
hmm.. im guessing this fails in ci builds (and not locally) because of node version differences.... should i revert my arrow function change?

**Comment by hulkish** [comment]
Went ahead and removed the arrow function and just put the expected output in the helper template.. that ok?

**Comment by xtuc** [comment]
Thanks for your PR :+1: 

The PR is against master (Babel 6) which still support Node < 0.12 and doesn't support arrow functions syntax. I would like to port this to Babel 7 using an arrowFunction, ok for you @loganfsmyth ?

**Comment by existentialism** [comment]
Yes, let's target to 7.0

**Comment by xtuc** [comment]
Ok, as said by @loganfsmyth, would be great to change it to an arrowFunction then.

**Comment by hulkish** [comment]
@xtuc do i need to do this? If so, some advice on where to apply the support for this per the issue [explained here](https://github.com/babel/babel/pull/5688#issuecomment-298507360).

**Comment by hzoo** [comment]
screen shot 2017-05-02 at 2 07 36 pm

Can you change the base of the PR to target 7.0? Then you can use arrow functions fine. Then there won't be a need to apply the es2015 preset either in the exec test.

**Comment by hulkish** [comment]
@hzoo so I made these changes, resolved the conflicts and pushed... but it's not being reflected here for some reason...what do?

**Comment by hulkish** [comment]
Do I need to move my changes to the corresponding 7.0 branch in my fork?

**Comment by hulkish** [comment]
ok now im a little confused.... ???

**Comment by hulkish** [comment]
nvm, got it.

**Comment by xtuc** [comment]
@hulkish are you fine with the arrowFunction change? The issue was from Node < 0.12. You need to correct the old tests fixtures which still use the function.

**Comment by hulkish** [comment]
@xtuc yea im good with it.. I just fixed the test for it.

**Comment by hulkish** [comment]
Ok, so back to this, lol: 
```bash
make[1]: Leaving directory `/home/ubuntu/babel'
make test-only
make[1]: Entering directory `/home/ubuntu/babel'
./scripts/test.sh

undefined:233
    return new Promise((resolve, reject) => {
                                          ^
SyntaxError: Unexpected token >
    at Object.<anonymous> (/home/ubuntu/babel/packages/babel-helper-transform-fixture-test-runner/lib/index.js:186:61)
    at Module._compile (module.js:456:26)
    at Module._extensions..js (module.js:474:10)
```

**Comment by hulkish** [comment]
should i merge 7.0 into this branch?

**Comment by hulkish** [comment]
Ok, new but suspiciously similar issue:

```bash
core-js@2.4.1 node_modules/core-js

/home/ubuntu/babel/packages/babel-core/node_modules/babel-types/lib/constants.js:29
var BLOCK_SCOPED_SYMBOL = exports.BLOCK_SCOPED_SYMBOL = Symbol.for("var used t
                                                        ^
ReferenceError: Symbol is not defined
    at Object.<anonymous> (/home/ubuntu/babel/packages/babel-core/node_modules/babel-types/lib/constants.js:29:57)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ubuntu/babel/packages/babel-core/node_modules/babel-types/lib/index.js:6:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
make[1]: *** [bootstrap] Error 8
make[1]: Leaving directory `/home/ubuntu/babel'
make: *** [test-ci] Error 2

make test-ci returned exit code 2
```

Seems like Symbol isnt transformed? Unrelated to my issue?

**Comment by hulkish** [comment]
prq6mcrjq4vno

**Comment by hulkish** [comment]
@loganfsmyth anything else i need to do here?

File: packages/babel-plugin-transform-async-to-generator/test/fixtures/regression/4943/options.json [hunk 3]
```diff
@@ -0,0 +1,7 @@
+{
+  "presets": ["es2015"],
```
Comment (existentialism) [inline packages/babel-plugin-transform-async-to-generator/test/fixtures/regression/4943/options.json]: Still needed post move to 7.0?

Comment (hulkish) [inline packages/babel-plugin-transform-async-to-generator/test/fixtures/regression/4943/options.json]: I didn't realize this should be moved out for 7.0 branch, ill go ahead and do that.

Comment (hulkish) [inline packages/babel-plugin-transform-async-to-generator/test/fixtures/regression/4943/options.json]: how's that?

**Comment by loganfsmyth** [comment]
The easiest fix for those failures would be to add `use strict` to those tests, I think.

**Comment by loganfsmyth** [comment]
By the way, thanks so much for this, I know it's been a lot of back and forth, hope it's not too bad of an experience.

**Comment by hulkish** [comment]
@loganfsmyth no no, its cool... its far more important that the outcome is desired than to rush this anyway

**Comment by hulkish** [comment]
@loganfsmyth im kinda stuck now though...travis build fails but circlici build works haha

**Comment by jridgewell** [comment]
Node 4 doesn't support destructuring, you'll have to enable the transform to run the exec test.

**Comment by hulkish** [comment]
@loganfsmyth ok i think this is the one!!

**Comment by loganfsmyth** [comment]
Thanks so much!
