### PR TITLE
check descriptor before private field access

### LINKED ISSUE #12904: Confusing error when static private field is accessed before declaration.
## Bug Report

**Current behavior**
At runtime, when reading or setting a private static field before its declaration we get the following error: `TypeError Cannot read property 'get' of undefined` and respectively `TypeError Cannot read property 'set' of undefined`

[REPL](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAECCvQN4ChrQgFzBglsaAxAB7QC80AdgKYDucsAFAJQDcq6Wu-BAnmdABYATGzTAA9hUwAnAK7AM46cyTsxkiOJBUAdCHEBzBvB29-AZiGt2AX2Q2gA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.13.7&externalPlugins=)
**Input Code**

```js
class AA {
  static #x = new AA();
  static #y = 0;
  constructor() {
    // Either line will trigger the confusing error
    // One for get the other for set 
    console.log(AA.#y);
    //AA.#y = 10
  }
}
```

**Expected behavior**
The private static field access should continue to be an error, but the error message should be more explicit about what the cause of the error is. Node, for example,  issues this error `Cannot read private member #y from an object whose class did not declare it`. 

**Possible Solution**
Change `_classStaticPrivateFieldSpecGet` and `_classStaticPrivateFieldSpecGet` helpers to check if `descriptor` is `undefined` and issue an appropriate error:

```js

function _classStaticPrivateFieldSpecGet(receiver, classConstructor, descriptor) {
    if (receiver !== classConstructor) {
        throw new TypeError("Private static access of wrong provenance");
    }
    if (descriptor === undefined) {
        throw new TypeError("Private static field was accessed before its declaration.");
    }
    if (descriptor.get) {
        return descriptor.get.call(receiver);
    }
    return descriptor.value;
}

function _classStaticPrivateFieldSpecSet(receiver, classConstructor, descriptor, value) {
    if (receiver !== classConstructor) {
        throw new TypeError("Private static access of wrong provenance");
    }
    if (descriptor === undefined) {
        throw new TypeError("Private static field was accessed before its declaration.");
    }
    if (descriptor.set) {
        descriptor.set.call(receiver, value);
    } else {
        if (!descriptor.writable) {
            throw new TypeError("attempted to set read only private field");
        }
        descriptor.value = value;
    }
    return value;
}
```

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #12904
| Patch: Bug Fix?          | Y
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

As suggested in #12904, check if `descriptor` is `undefined` before pass it as a descriptor. Note that the `privateFieldAsProperty` a.k.a. loose handler is not affected because the loosePrivateKey is always hoisted before class declaration. So in this case they will throw the same error as if we are accessing a private properties that is not defined in current class.

I mark this PR as polish because we still throw on the new cases, but the error message is confusing. <s>This PR is now based on #12911, please review that PR first.</s>

### CODE REVIEW

File: packages/babel-plugin-proposal-private-methods/test/fixtures/static-accessors-loose/access-before-declaration/exec.js [hunk 1]
```diff
@@ -0,0 +1,29 @@
+expect(() => {
+  class C {
+    static #_ = new C;
+    static get #p() { return C };
+    constructor() {
+      C.#p;
+    }
+  }
+}).toThrow(/attempted to use private field on non-instance/);
```
Comment (JLHwung) [inline packages/babel-plugin-proposal-private-methods/test/fixtures/static-accessors-loose/access-before-declaration/exec.js:9]: This is exactly #12905, the Babel behaviour on static accessors are not aligned with V8. I will try to tackle in a separate PR. Before that it is just a test case parallel to properties.

**Review by nicolo-ribaudo — APPROVED** [review]

**Review by jridgewell — APPROVED** [review]
