### PR TITLE
Simplify the special-case printing of single-param arrow functions

### LINKED ISSUE #13198: [Bug]: Edge-case exception while printing single-parameter arrow function
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
const { parse } = require("@babel/parser");
const t = require("@babel/types");
const { default: generate } = require("@babel/generator");

// Create an identifier with a location and a leading comment.
const param = parse("(/*x*/ a)").program.body[0].expression;

// Create an async arrow function without a location.
const ast = t.arrowFunctionExpression(
    [param],
    t.identifier("a"),
    /* async */ true,
);

// TypeError: Cannot read property 'start' of undefined
generate(ast);
```

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

Expected: Babel generates valid output source for the AST.

Actual:
```
$ yarn node repro.js 
/Users/user/babel/packages/babel-generator/lib/generators/methods.js:137
      if (firstParam.loc && firstParam.loc.start.line > node.loc.start.line) {
                                                                 ^

TypeError: Cannot read property 'start' of undefined
    at Generator.ArrowFunctionExpression (/Users/user/babel/packages/babel-generator/lib/generators/methods.js:137:66)
    at /Users/user/babel/packages/babel-generator/lib/printer.js:287:19
    at Buffer.withSource (/Users/user/babel/packages/babel-generator/lib/buffer.js:188:28)
    at Generator.withSource (/Users/user/babel/packages/babel-generator/lib/printer.js:153:15)
    at Generator.print (/Users/user/babel/packages/babel-generator/lib/printer.js:286:10)
    at Generator.generate (/Users/user/babel/packages/babel-generator/lib/printer.js:45:10)
    at Generator.generate (/Users/user/babel/packages/babel-generator/lib/index.js:26:18)
    at generate (/Users/user/babel/packages/babel-generator/lib/index.js:100:14)
    at Object.<anonymous> (/Users/user/babel/repro.js:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
```

### Environment

- Current Babel main (fb908fd87e1bf8a5ebe2c881c0baab1488c917e7)

### Possible solution

Originally I was planning to PR an additional null check, but on closer inspection (and in light of #13136) I think it makes more sense to get rid of all this special-case code and just delegate to the regular param-printing code.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Zalathar**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #13198 
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  | No
| License                  | MIT

This is an alternate version of #13202 that retains the special-case handling for single-parameter arrow functions, and instead tries to make it simpler and more robust.

We still remove the complex special-case code for printing single-parameter arrow functions *with* parentheses, and just delegate to the regular parameter-printing code in that case.

### CODE REVIEW

File: packages/babel-plugin-proposal-object-rest-spread/test/fixtures/object-rest/nested-computed-key/output.js [hunk 1]
```diff
@@ -1,7 +1,7 @@
 var _ref2;
 
 const {
-  [(_ref) => {
+  [_ref => {
```
Comment (Zalathar) [inline packages/babel-plugin-proposal-object-rest-spread/test/fixtures/object-rest/nested-computed-key/output.js:4]: I looked into why some of these arrow functions are *losing* their parens.

It turns out that the previous implementation of `hasTypes` was checking `param.trailingComments`, which is truthy when `trailingComments` is an empty array.

Switching to `param.trailingComments?.length` makes the generator conclude that this arrow function doesn't need parentheses after all.

File: packages/babel-generator/src/generators/methods.ts [hunk 2]
```diff
@@ -151,12 +137,18 @@ export function ArrowFunctionExpression(
...
-  return (
+function hasTypesOrComments(
+  node: t.ArrowFunctionExpression,
+  param: t.Identifier,
+): boolean {
+  return !!(
     node.typeParameters ||
     node.returnType ||
+    // @ts-expect-error
+    node.predicate ||
```
Comment (Zalathar) [inline packages/babel-generator/src/generators/methods.ts:148]: This doesn't type-check because `predicate` isn't declared on `ArrowFunctionExpression`.

**Review by nicolo-ribaudo — APPROVED** [review]
Thanks!

**Review by JLHwung — APPROVED** [review]
