### PR TITLE
Respect preserveComments option in tempate.ast()

### LINKED ISSUE #9684: template.ast() doesn't respect preserveComments option.
## Bug Report

**Current Behavior**
```
const testAst = api.template.ast(`test(/* test */ 'test')`, {
  preserveComments: true
});
```

Will have no comment node in the resulting AST.

**Expected behavior/code**
The resulting AST should have comment node

**Environment**
- Babel version(s): 7.3.4
- Node/npm version: 10.15.2
- OS: Windows 10
- Monorepo: no
- How you are using Babel: API.

### PR DESCRIPTION
**Pull request by dentrado**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #9684 
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | Yes
| Documentation PR Link    | - 
| Any Dependency Changes?  | No
| License                  | MIT

`validate(opts)` added `preserveComments: false` when `preserveComments` was not present in the validated options. This caused the `NO_PLACEHOLDER` options in `builder.js` to contain `preserveComments: false`. So since `NO_PLACEHOLDER` later is merged in to the rest of the options given to template.ast() the preserveComments option was always set to false.

This PR changes `validate(opts)` so it keeps `preserveComments` undefined if it was null/undefined.

### CODE REVIEW

File: packages/babel-template/test/index.js [hunk 1]
```diff
@@ -219,7 +231,7 @@ describe("@babel/template", function() {
     });
   });
 
-  describe.only(".syntacticPlaceholders", () => {
+  describe(".syntacticPlaceholders", () => {
```
Comment (nicolo-ribaudo) [inline packages/babel-template/test/index.js]: 😬

Comment (kaicataldo) [reply packages/babel-template/test/index.js]: We should probably lint for this 😬

Comment (kaicataldo) [reply packages/babel-template/test/index.js]: Actually, it looks like we should be linting for this already: https://github.com/jest-community/eslint-plugin-jest/blob/master/docs/rules/no-focused-tests.md is a recommended rule.

Comment (nicolo-ribaudo) [reply packages/babel-template/test/index.js]: We added it yesterday :stuck_out_tongue: 
https://github.com/babel/babel/pull/11119

**Comment by nicolo-ribaudo** [comment]
Thanks!
