### PR TITLE
fix: Class reference in type throws error

### LINKED ISSUE #16671: [Bug]: Type in property decorator causes error
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@rollup/plugin-babel

### Input code

repo to reproduce.

https://github.com/dog-s-life/babel-test

### Configuration file name

babel.config.cjs

### Configuration

```js
module.exports = {
    presets: [
        '@babel/preset-typescript',
        [
            '@babel/env',
            {
                modules: false,
                useBuiltIns: false
            }
        ]
    ],
    plugins: [
        [
            '@babel/transform-runtime',
            {
                corejs: false,
                regenerator: false
            }
        ],
        [
            '@babel/plugin-proposal-decorators',
            {
                version: '2023-11'
            }
        ],
    ]
};
```

### Current and expected behavior

If a function with a class instance as its type is specified as an argument for the property decorator, an error occurs when bundling the inherited class.
typescript eslint seems to handle properly. (no red line)

### Environment

  System:
    OS: Linux 5.19 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
  Binaries:
    Node: 20.15.1 - /usr/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.7.0 - /usr/bin/npm
    pnpm: 9.5.0 - /usr/bin/pnpm
  npmPackages:
    @babel/cli: ^7.24.8 => 7.24.8 
    @babel/core: ^7.24.9 => 7.24.9 
    @babel/plugin-proposal-decorators: ^7.24.7 => 7.24.7 
    @babel/plugin-transform-runtime: ^7.24.7 => 7.24.7 
    @babel/preset-typescript: ^7.24.7 => 7.24.7 

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #16671 
| Patch: Bug Fix?          | √
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | √
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

File: packages/babel-helper-create-class-features-plugin/src/misc.ts [hunk 1]
```diff
@@ -53,6 +53,11 @@ function handleClassTDZ(
 
 const classFieldDefinitionEvaluationTDZVisitor: Visitor<HandleClassTDZState> = {
   ReferencedIdentifier: handleClassTDZ,
+  "TSTypeReference|TSExpressionWithTypeArguments|TSTypeQuery|TSQualifiedName"(
```
Comment (nicolo-ribaudo) [inline packages/babel-helper-create-class-features-plugin/src/misc.ts:56]: Can we skip on `"TSType"` so we are sure we never forget to update this list?

Comment (liuxingbaoyu) [reply packages/babel-helper-create-class-features-plugin/src/misc.ts]: I realized we just need to use `TSTypeAnnotation`. :)

**Review by JLHwung — APPROVED** [review]

**Review by nicolo-ribaudo — APPROVED** [review]
