### PR TITLE
fix: don't deduplicate comments with same start index

### LINKED ISSUE #12769: @babel/generator comment deduplication removes too many comments
## Bug Report

- [ ] I would like to work on a fix!

**Input Code**

```js
import { parse } from "@babel/parser";
import generator from "@babel/generator";
import t from "@babel/types";

const code1 = `
// hello!
a();
`;

const code2 = `
// hello
b();
`;

let ast1 = parse(code1).program;
let ast2 = parse(code2).program;

let ast = t.program([...ast1.body, ...ast2.body]);

console.log(generator.default(ast).code);
```

**Expected behavior**

```js
// hello!
a();
// hello
b();
```

**Current behavior**

```js
// hello!
a();
b();
```

**Environment**

```json
    "@babel/generator": "7.12.15",
    "@babel/parser": "7.12.15",
```

**Possible Solution**

**Additional context**

I was surprised that there are cases where comment exists twice (as leading and trailing), e.g. 
```js
if (1) {
  a();
}
// /* */
else {
  b();
}
```
. Looks like babel-generators "workaround" for this isn't quite right.

Distantly related to https://github.com/parcel-bundler/parcel/issues/5787

### PR DESCRIPTION
**Pull request by gzzhanghao**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #12769  
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | Yes
| Documentation PR Link    | No 
| Any Dependency Changes?  | No
| License                  | MIT

__Input code__

```js
const template = require('@babel/template');
const generator = require('@babel/generator');
const t = require("@babel/types");

const createStatement = template.statement("/*#__PURE__*/ foo()", {
  preserveComments: true,
});

const result = t.program([createStatement(), createStatement()]);

console.log(generator.default(result).code);
```

__Expected behavior__

```js
/*#__PURE__*/
foo();
/*#__PURE__*/
foo();
```

__Current behavior__

```js
/*#__PURE__*/
foo();
foo();
```

This PR includes following changes:

- Generate comments with same start index (Fixes #12769)
- Clone comments in cloneNode (Moved to #13178)

### CODE REVIEW

File: packages/babel-generator/test/index.js [hunk 1]
```diff
@@ -348,6 +348,20 @@ describe("generation", function () {
     const output = generate(type).code;
     expect(output).toBe("(infer T)[]");
   });
+
+  it("comments with same start index", () => {
+    const code1 = "/* leading a */ a();";
```
Comment (kaicataldo) [inline packages/babel-generator/test/index.js:353]: Is there a particular reason we can't construct and parse the full program in the test instead of cobbling it together after?

File: packages/babel-generator/test/index.js [hunk 2]
```diff
@@ -348,6 +348,20 @@ describe("generation", function () {
     const output = generate(type).code;
     expect(output).toBe("(infer T)[]");
   });
+
+  it("comments with same start index", () => {
```
Comment (kaicataldo) [inline packages/babel-generator/test/index.js:352]: Can we describe what we're actually testing here? i.e. "should not deduplicate comments with same start index from two different ASTs" or something similar.

File: packages/babel-generator/test/index.js (hunk 1 above)
Comment (kaicataldo) [inline packages/babel-generator/test/index.js:353]: The example of generating multiple statements for the program body in the PR author comment seems like a more likely scenario than what we're testing here. Can we change this to match that?

File: packages/babel-types/src/clone/cloneNode.ts [hunk 3]
```diff
@@ -102,25 +102,18 @@ export default function cloneNode<T extends t.Node>(
...
-    ? cloneCommentsWithoutLoc(comments)
-    : comments;
+  if (!comments || !deep) {
+    return comments;
+  }
+  return comments.map(({ type, value, loc }) => {
+    if (withoutLoc) {
+      return { type, value, loc: null } as T;
+    }
+    return { type, value, loc } as T;
```
Comment (kaicataldo) [inline packages/babel-types/src/clone/cloneNode.ts:117]: I've actually personally been bitten by this (a cloned AST's comments still reference the original comments and so mutating the cloned AST's comments mutates the original AST as well unless you clone without location information), so I'm excited to see a fix for this!

File: packages/babel-generator/src/printer.ts [hunk 4]
```diff
@@ -598,11 +598,6 @@ class Printer {
     if (this._printedComments.has(comment)) return;
     this._printedComments.add(comment);
 
-    if (comment.start != null) {
-      if (this._printedCommentStarts[comment.start]) return;
```
Comment (kaicataldo) [inline packages/babel-generator/src/printer.ts:602]: It doesn't look  like `this._printedCommentStarts` is referenced anywhere else in this class, so we should be able to remove that class property.

**Comment by kaicataldo** [comment]
Since modifying anything with comments ends up affecting a rather large surface area, I wonder if it would be prudent to split this up into two PRs (the cloning fix in one and the deduplication fix in the other) in case we find regressions and need to revert something.

**Comment by gzzhanghao** [comment]
@kaicataldo Good point, the cloning fix was moved to #13178.

**Comment by mischnic** [comment]
I think the check that is removed here was added so that the comment in this example (which exists twice in the AST, both as leading and trailing)
```js
if (1) {
  a();
}
// /* */
else {
  b();
}
```
isn't printed twice.

Have you checked that this case still behaves correctly?

**Comment by gzzhanghao** [comment]
@mischnic We already have a similar test case: [babel-generator/test/fixtures/comments/try-block-line-comment/input.js](https://github.com/babel/babel/blob/main/packages/babel-generator/test/fixtures/comments/try-block-line-comment/input.js)

**Comment by nicolo-ribaudo** [comment]
Yeah, @mischnic's code works in the REPL for this PR! https://babeljs.io/repl/build/45409/#?browsers=chrome%2060&build=&builtIns=false&spec=false&loose=false&code_lz=JYMwBAFAjAlGDeAoMYCGEYG5EF9EHp8x8AqME_RAUwBsBnKhZMAIw2xyA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.13.15%2Bpr.13169&externalPlugins=

**Review by nicolo-ribaudo — APPROVED** [review]
:+1:

I think that the original use case for this object is now better handled by the `_printedComments` `WeakSet`.

**Review by JLHwung — APPROVED** [review]
