### PR TITLE
Use `for..of Object.keys` instead of `for..in`

### LINKED ISSUE #9511: Configuring babel.config.js for for testing modules with mocha
After reading all the information I still can't configure babel 7 to compile files from modules when using mocha. This is my project structure:
```
script4j
|
|-modules
|   |-script4j.base
|   |      |-node_modules
|   |      |-package.json
|   |-script4jfx.base
|   |      |-node_modules
|   |      |-package.json
|   |-script4jfx.graphics
|   |      |-node_modules
|   |      |-package.json
|   |      |-register.js
|-babel.config.js
```
As you see I have three modules. No one module has `.babelrc` file. Module `script4jfx.graphics` depends on `script4j.base` and `script4jfx.base`. This is a piece of package.json of `script4jfx.graphics`:

```
    "devDependencies": {
        "gulp": "4.0.0",
        "chai": "4.2.0",
        "mocha": "5.2.0",
        "@babel/core": "7.2.2",
        "@babel/register": "7.0.0",
        "@babel/preset-env": "7.3.1",
        "@babel/cli": "7.2.3",
        "babel-plugin-module-resolver": "3.2.0",
        "typescript": "3.3.3",
        "script4j.base": "file:./../script4j.base",
        "script4jfx.base": "file:./../script4jfx.base"
    },
    "dependencies": {
        "script4j.base": "file:./../script4j.base",
        "script4jfx.base": "file:./../script4jfx.base"
    }
```
This is `register.js`:

```
require("@babel/register")({
    rootMode: "upward",
});
```
This is my babel.config.js:

```
module.exports = function (api) {
    api.cache(true);
    console.log("Point XXX");//       <-- NOTE THIS LINE
    return {
        babelrcRoots: [
            '.',
            './modules/script4j.base',
            './modules/script4jfx.base',
            './modules/script4jfx.graphics'
        ],
	ignore: [/node_modules/],
        presets: ["@babel/preset-env"]
    };
}
```

This is the way I run mocha:
```
$ pwd
home/Pavel/script4j/modules/script4jfx.graphics

$./node_modules/mocha/bin/mocha ./tmp/script4jfx.graphics.spec.js --require register.js --compilers js:@babel/register
```
And this is what I get:
```
Point XXX
/home/Pavel/script4j/modules/script4j.base/dist/script4j.base.js:1191
export { Class, Integer, ... };
^^^^^^
SyntaxError: Unexpected token export
```
So, as you see `script4j.base` wasn't compiled by babel. How to fix it?

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #9511
| Patch: Bug Fix?          | Yes
| Tests Added + Pass?      | Yes
| License                  | MIT

In https://github.com/babel/babel/issues/9511 (and #9495 is another symptom), @PavelKastornyy reported a node crash becaue the JavaScript heap run out of memory. The problem was that their code was adding enumerable properties to `Object.prototype`: it is something that shouldn't be done, but Babel shouldn't make node crash if someone adds them.
I reduced down the problem to `for...in` loops in `@babel/traverse` that grew the memory consumption exponentially because of that unexpected properties.

### CODE REVIEW

File: packages/babel-helper-define-map/src/index.js [hunk 1]
```diff
@@ -98,7 +99,7 @@ export function push(
 }
 
 export function hasComputed(mutatorMap: Object): boolean {
-  for (const key in mutatorMap) {
+  for (const key in own(mutatorMap)) {
```
Comment (loganfsmyth) [inline packages/babel-helper-define-map/src/index.js]: Do we need the macro? It's pretty easy to do `for (const key of Object.keys(mutatorMap)) {`.

Comment (nicolo-ribaudo) [reply packages/babel-helper-define-map/src/index.js]: I already had the macro in another project so I published it and added there, but I can remove it if you prefer.
My fear is that `for ... of + Object.keys` is slower than `for ... in + Object.hasOwnProperty`, and it is used in some perf-sensitive places in `@babel/traverse`.

Comment (nicolo-ribaudo) [reply packages/babel-helper-define-map/src/index.js]: Nvm, I was wrong https://jsperf.com/for-in-vs-for-ok/1

File: packages/babel-traverse/src/visitors.js [hunk 2]
```diff
@@ -23,7 +23,7 @@ export function explode(visitor) {
   visitor._exploded = true;
 
   // normalise pipes
-  for (const nodeType in visitor) {
+  for (const nodeType of Object.keys(visitor)) {
```
Comment (nicolo-ribaudo) [inline packages/babel-traverse/src/visitors.js]: @loganfsmyth Since this is a pulic api, should I handle the case where `visitor` is null/undefined (that `for..in` handled by default)?

Comment (loganfsmyth) [reply packages/babel-traverse/src/visitors.js]: Since we're doing `visitor._exploded` above we shouldn't need to worry about that case here.
