### PR TITLE
fix: build standalone on windows

### LINKED ISSUE #14331: [Bug]: clone repo and error while `make bootstrap`
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```sh
make bootstrap
```

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

image

### Environment

- Babel version: 7.17.6
- Node: 14.15.3
- npm 6.14.9/yarn 3.1.1
- OS: Windows 10

### Possible solution

I found that you guys use 'patch:@rollup/plugin-commonjs@^18.1.0#./.yarn/patches/@rollup__plugin-commonjs.patch' to manually fix '@rollup/plugin-commonjs', but it seems not work for me.
I can only temporarily skip the error, but I am not sure if it will affect the functions.
image

By the way, I am trying to figure out referencePaths and bindings in @babel/traverse through source code for tracing var in js/ts.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #14331 
| Patch: Bug Fix?          |√
| Major: Breaking Change?  |×
| Minor: New Feature?      |×
| Tests Added + Pass?      | ×
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14462"></a>

### CODE REVIEW

**Comment by liuxingbaoyu** [comment]
This is a crude solution. 

If you need to be robust enough, you may need to add new npm packages.

**Review by JLHwung — APPROVED** [review]
Thanks!

File: Gulpfile.mjs [hunk 1]
```diff
@@ -297,6 +297,15 @@ function buildRollup(packages, targetBrowsers) {
...
           external,
           onwarn(warning, warn) {
+            function normalizePath(str) {
+              return typeof str == "string"
+                ? str.split(path.sep).join(path.posix.sep)
+                : str;
+            }
+
+            warning.importer = normalizePath(warning.importer);
+            warning.exporter = normalizePath(warning.exporter);
```
Comment (nicolo-ribaudo) [inline Gulpfile.mjs:307]: Since `warning` is a Rollup object that we pass back to rollup, I'd prefer if we could avoid modifying it.
Instead, we can create an `osifyPath = str => str.split("/").join(path.sep)` function and do `warning.exporter === osifyPath("packages/babel-core/src/index.ts")` below ("osify" = "make it like the os").

Comment (liuxingbaoyu) [reply Gulpfile.mjs]: That's right! We should not modify this object.

The requested change has been completed.

But it looks a bit odd that `"@babel/helper-define-polyfill-provider" -> "@babel\helper-define-polyfill-provider"`

And it's a little inconvenient to expand in this way.When adding new conditions we need to copy and paste osifyPath.

Maybe we can deep clone the warning object, which is a small object.

**Review by nicolo-ribaudo — APPROVED** [review]
This looks fine!
