### PR TITLE
fix(partial-app): support super method call

### LINKED ISSUE #17654: Partial application transform does not support super method call
### 💻

- [x] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
class C extends class {
  static x = "base"
  static concat(y, z) { return [this.x, y, z].join(" "); }
} {
  static x = "derived"
  static concat(y, z) { return [this.x, y, z].join("_"); }
  static {
    console.log(super.concat(?, "invoked")("is"))
  }
}
```

[REPL](https://babel.dev/repl#?config_lz=N4IgZglgNgpgdgQwLYxALhAJxgBygOgCsBnEAGhDwFcBzCOUtAbSZAAEAjBDmKAemp04AWhyYA9jnHEEUUQkwAXCLOEIceCAGMEy8XDYB2fACZjARnLAAvgF1bFYuKqYtMACoBPHKgxJxACZUsCDWQA&code_lz=MYGwhgzhAEDC0FMAeAXBA7AJjUkYG8AoaaCFMFAS2GiWgF5oAiAI0gSeNPKpuAHt0wCgAoAngBpoALwCU0fNABOCFAFcl6aAG0UAC0oQAdEimSZAXSMArfpXQimzWQG5oAX0LuFXMhWq0DMyYCEqUAG4ImJwkfrzQAkKi5nIKyqoaWroGxqbQKVa29o4APkyuHr48AUQkJIkQ_CAIRiD8AOYiEGoADqFGicIoIgD8Ukz24fwA1lHljoblslye7kA&evaluate=true&lineWrap=true&version=7.28.5)

### Configuration file name

_No response_

### Configuration

```json
{
  "filename": "repl.js",
  "plugins": [
    [
      "@babel/plugin-proposal-partial-application@7.27.1",
      {}
    ]
  ],
  "sourceType": "module"
}
```

### Current and expected behavior

Current: The transpiled output throws syntax error "invalid use of keyword 'super'"

Expected: The input is valid and it should log "derived is invoked" to the console.

### Environment

REPL

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #17654 
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

This PR improves the member expression handling such that it supports the super method. Previously we generated invalid lone `super` node. <s>The handling logic here is copied from the decorators transform. As a bonus the new logic will reuse the `this` expression when possible. Hence there are a few output changes.</s>

Also left a todo comment in the plugin since partial applications nested within `NewExpression` and `OptionalCallExpression` are not yet supported.

### CODE REVIEW

File: packages/babel-plugin-proposal-partial-application/test/fixtures/general/bound-method/output.js [hunk 1]
```diff
@@ -1,8 +1,8 @@
 class Partial {
   constructor() {
-    var _this$compare, _this;
-    this.compare = (_this = this, _this$compare = _this.compare, function compare(_argPlaceholder, _argPlaceholder2) {
-      return _this$compare.call(_this, _argPlaceholder, _argPlaceholder2);
+    var _this$compare;
+    this.compare = (_this$compare = this.compare, function compare(_argPlaceholder, _argPlaceholder2) {
+      return _this$compare.call(this, _argPlaceholder, _argPlaceholder2);
```
Comment (JLHwung) [inline packages/babel-plugin-proposal-partial-application/test/fixtures/general/bound-method/output.js]: This change is not correct, although `this` is static in `_this$compare = this.compare`, the result is no longer a bound method because the function wrapper `compare` has its own this binding. We should still memoise `this` to ensure that the method is bound.

The test suite does not actually test the `this` binding, so the test still passes.
