### PR TITLE
Do not hoist jsx referencing a mutable binding

### LINKED ISSUE #10522: transform-react-constant-elements: using mutable variable doesn't lead to deoptimization
## Bug Report

**Current Behavior**
When a React component uses a `let` variable, hoisting of the returned React Element leads to incorrect behavior

**Input Code**
- REPL or Repo link if applicable:
https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=DYUwLgBAZg9jEF4IHIAWJjBsg3AKDxAA8AHGAJ0gGMYA7AZ0jHIEsBzNkc-gQSrBZ16ANRYBDAEIBXMGDqIIACgCUiAHwQA3ngjQ4C5GzgATAEYBPELh0Ry4KeVoQAPPRJjaazbBgBfZwD0bh5q-L74QA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=react&prettier=false&targets=&version=7.6.2&externalPlugins=%40babel%2Fplugin-transform-react-constant-elements%407.6.0

```js
let foo = 'hello';

export const Component = () => {
  foo = 'goodbye';
  return <span>{foo}</span>;
};
```

**Expected output**

```js
let foo = 'hello';

export const Component = () => {
  foo = 'goodbye';
  return React.createElement("span", null, foo);
};
```

**Actual output**

```js
let foo = 'hello';

var _ref =
/*#__PURE__*/
React.createElement("span", null, foo);

export const Component = () => {
  foo = 'goodbye';
  // renders "hello" instead of "goodbye"
  return _ref;
};
```

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #10522
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

Related tests:
- https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/dont-hoist-before-hoc/
- https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/reassignment

### CODE REVIEW

File: packages/babel-traverse/src/path/lib/hoister.js [hunk 1]
```diff
@@ -32,6 +32,15 @@ const referenceVisitor = {
     const binding = path.scope.getBinding(path.node.name);
     if (!binding) return;
 
+    // we can handle reassignments only if they happen in the same scope as the declaration
+    for (const violation of binding.constantViolations) {
+      if (violation.scope !== binding.path.scope) {
```
Comment (jridgewell) [inline packages/babel-traverse/src/path/lib/hoister.js]: Can't we still hoist to the level of the violation?

```js
let foo = 'hello';
export const Component = () => {
  foo = 'goodbye';
  return <span>{array.map(() => <inner>{foo}</inner>}</span>;
};

Comment (nicolo-ribaudo) [reply packages/babel-traverse/src/path/lib/hoister.js]: No, we can't. Consider this example:

```js
let foo = 0;
export const Component = () => {
  foo++;
  return Promise.resolve().then(() => <span>{foo}</span>);
};

Component();
Component();
```

Here both the components should use `2`, but if we hoist it the first one will use `1`.
