### PR TITLE
fix(optional chaining): Optional delete returns true with nullish base

### LINKED ISSUE #10805: Optional delete must return true when base is nullish
## Bug Report

**Current Behavior**

When using optional delete to delete a property of a nullish base, the delete operation returns `undefined`. It should return `true`

**Input Code**
[repl](https://babeljs.io/repl/#?browsers=Chrome%2078&build=&builtIns=usage&spec=false&loose=false&code_lz=DYUwLgBAZg9jDcAoAxjAdgZ0gJ3BAvBACYihgjRwD8AdAEYCG2SK6GMoNDGGI2YAClyR8oiGGwBXEAEp4QA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015&prettier=false&targets=&version=7.7.4&externalPlugins=%40babel%2Fplugin-proposal-optional-chaining%407.6.0)

```js
let foo;
const ret = delete foo?.bar;

console.assert(ret === true);
```

**Expected behavior/code**
The `ret` value should be `true`, not `undefined`.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "plugins": ["@babel/plugin-proposal-optional-chaining"]
}
```

**Possible Solution**
When replacing optional deletes, we must use `t.booleanLiteral(true)` in the consequent (truthy branch of a ternary expression) instead of `scope.buildUndefinedNode()`.

Specifically, we must fix https://github.com/babel/babel/blob/d18afbd7c3e977208194acbea4c0de0313a6e1eb/packages/babel-plugin-proposal-optional-chaining/src/index.js#L116

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

### PR DESCRIPTION
**Pull request by mpaarating**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #10805
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

Per issue #10805, the return value when using delete on a nullish base is
currently undefined. The correct return type should be true.

### CODE REVIEW

File: packages/babel-plugin-proposal-optional-chaining/test/fixtures/general/delete/output.js [hunk 1]
```diff
@@ -7,7 +7,7 @@ const obj = {
     b: 0
   }
 };
-let test = obj === null || obj === void 0 ? void 0 : (_obj$a = obj.a) === null || _obj$a === void 0 ? void 0 : delete _obj$a.b;
-test = obj === null || obj === void 0 ? void 0 : delete obj.a.b;
-test = obj === null || obj === void 0 ? void 0 : (_obj$b = obj.b) === null || _obj$b === void 0 ? void 0 : delete _obj$b.b;
-obj === null || obj === void 0 ? void 0 : delete obj.a;
+let test = obj === null || obj === void 0 ? true : (_obj$a = obj.a) === null || _obj$a === void 0 ? true : delete _obj$a.b;
```
Comment (jridgewell) [inline packages/babel-plugin-proposal-optional-chaining/test/fixtures/general/delete/output.js]: Excellent!
