### PR TITLE
fix: avoid `popContext` on unvisited node paths

### LINKED ISSUE #16293: [Bug]: do-expressions plugin throws "Couldn't find a Program" in Babel 8
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
async () => do {
  await 0
  while (0) {}
  0
}
```

### Configuration file name

babel.config.json

### Configuration

```json
{
  "plugins": [
    [
      "@babel/plugin-proposal-do-expressions"
    ]
  ]
}
```

### Current and expected behavior

`transformAsync` when called with the code above throws a "Couldn't find a Program" error.

<details><summary>Stack trace</summary>

```text
.../node_modules/@babel/traverse/lib/index.js:1362
    throw new Error("Couldn't find a Program");
          ^

Error: unknown file: Couldn't find a Program
    at Scope.getProgramParent (.../node_modules/@babel/traverse/lib/index.js:1362:11)
    at Scope.crawl (.../node_modules/@babel/traverse/lib/index.js:1274:32)
    at Scope.init (.../node_modules/@babel/traverse/lib/index.js:1264:12)
    at NodePath.setScope (.../node_modules/@babel/traverse/lib/index.js:3652:15)
    at NodePath.setContext (.../node_modules/@babel/traverse/lib/index.js:3664:8)
    at NodePath.popContext (.../node_modules/@babel/traverse/lib/index.js:3716:10)
    at TraversalContext.visitQueue (.../node_modules/@babel/traverse/lib/index.js:4876:12)
    at TraversalContext.visitMultiple (.../node_modules/@babel/traverse/lib/index.js:4839:17)
    at TraversalContext.visit (.../node_modules/@babel/traverse/lib/index.js:4885:19)
    at traverseNode (.../node_modules/@babel/traverse/lib/index.js:4905:17)
    at traverse (.../node_modules/@babel/traverse/lib/index.js:4942:3)
    at traverse.hasType (.../node_modules/@babel/traverse/lib/index.js:4974:3)
    at NodePath.replaceExpressionWithStatements (.../node_modules/@babel/traverse/lib/index.js:2297:57)
    at PluginPass.exit (.../node_modules/@babel/plugin-proposal-do-expressions/lib/index.js:20:18)
    at newFn (.../node_modules/@babel/traverse/lib/index.js:354:14)
    at NodePath._call (.../node_modules/@babel/traverse/lib/index.js:3582:20)
    at NodePath.call (.../node_modules/@babel/traverse/lib/index.js:3572:17)
    at NodePath.visit (.../node_modules/@babel/traverse/lib/index.js:3624:8)
    at TraversalContext.visitQueue (.../node_modules/@babel/traverse/lib/index.js:4864:16)
    at TraversalContext.visitSingle (.../node_modules/@babel/traverse/lib/index.js:4843:19)
    at TraversalContext.visit (.../node_modules/@babel/traverse/lib/index.js:4887:19)
    at traverseNode (.../node_modules/@babel/traverse/lib/index.js:4905:17)
    at NodePath.visit (.../node_modules/@babel/traverse/lib/index.js:3622:21)
    at TraversalContext.visitQueue (.../node_modules/@babel/traverse/lib/index.js:4864:16)
    at TraversalContext.visitSingle (.../node_modules/@babel/traverse/lib/index.js:4843:19)
    at TraversalContext.visit (.../node_modules/@babel/traverse/lib/index.js:4887:19)
    at traverseNode (.../node_modules/@babel/traverse/lib/index.js:4905:17)
    at NodePath.visit (.../node_modules/@babel/traverse/lib/index.js:3622:21)
    at TraversalContext.visitQueue (.../node_modules/@babel/traverse/lib/index.js:4864:16)
    at TraversalContext.visitMultiple (.../node_modules/@babel/traverse/lib/index.js:4839:17)
    at TraversalContext.visit (.../node_modules/@babel/traverse/lib/index.js:4885:19)
    at traverseNode (.../node_modules/@babel/traverse/lib/index.js:4905:17)
    at NodePath.visit (.../node_modules/@babel/traverse/lib/index.js:3622:21)
    at TraversalContext.visitQueue (.../node_modules/@babel/traverse/lib/index.js:4864:16)
    at traverseNode (.../node_modules/@babel/traverse/lib/index.js:4901:20)
    at traverse (.../node_modules/@babel/traverse/lib/index.js:4942:3)
    at transformFile (.../node_modules/@babel/core/lib/transformation/index.js:68:7)
    at transformFile.next (<anonymous>)
    at run (.../node_modules/@babel/core/lib/transformation/index.js:12:12)
    at run.next (<anonymous>)
    at transform (.../node_modules/@babel/core/lib/transform.js:8:17)
    at transform.next (<anonymous>)
    at step (.../node_modules/gensync/index.js:261:32)
    at .../node_modules/gensync/index.js:273:13
    at async.call.result.err.err (.../node_modules/gensync/index.js:223:11)
    at .../node_modules/gensync/index.js:189:28
    at .../node_modules/@babel/core/lib/gensync-utils/async.js:42:7
    at .../node_modules/gensync/index.js:113:33
    at step (.../node_modules/gensync/index.js:287:14)
    at .../node_modules/gensync/index.js:273:13
    at async.call.result.err.err (.../node_modules/gensync/index.js:223:11) {
  code: 'BABEL_TRANSFORM_ERROR'
}

Node.js v21.6.2
```

</details>

The error does not occur in Babel 7.

### Environment

```text
System:
  OS: macOS 14.1.1
Binaries:
  Node: 21.6.2 - /opt/homebrew/bin/node
  npm: 10.4.0 - /opt/homebrew/bin/npm
npmPackages:
  @babel/core: 8.0.0-alpha.6 => 8.0.0-alpha.6 
  @babel/plugin-proposal-do-expressions: 8.0.0-alpha.6 => 8.0.0-alpha.6 
```

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #16293 
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

When Babel invokes `traverse.hasType` to check whether there is an await expression in the do expression body:

https://github.com/babel/babel/blob/8c3f035a572cdbff5c52e2cb5611940996831301/packages/babel-traverse/src/path/replacement.ts#L309-L316

it throws when it is trying to initialize a `Scope` during `path.popContext()` when the `path` is supposed to work only within the `{ noScope: true }` traversal context.

This issue is likely directly caused by the breaking change https://github.com/babel/babel/pull/15759, as reverting these change will also fix this issue.

However it reveals a bug in the traverser: currently Babel is popping the context even if the visit queue exits early, rendering some unvisited node paths trying to initialize the `Scope` without the top traversal context.

### CODE REVIEW

**Review by liuxingbaoyu — APPROVED** [review]

**Comment by JLHwung** [comment]
The original regression only affects Babel 8, possibly due to different path caching strategy. Since the error is thrown when Babel is creating scope in a `noScope` traversal, this PR fixes the traverser and ensures that Babel does not pop more contexts than they were pushed.

I will construct a context test to show that both Babel 7 and Babel 8 is affected by the traverser bug.

File: packages/babel-traverse/test/traverse.js [hunk 1]
```diff
@@ -314,6 +314,44 @@ describe("traverse", function () {
...
+                          enter(path) {
+                            if (path.isVariableDeclaration()) path.stop();
+                          },
+                        },
+                        { level: 3 },
+                      );
+                      // the function declaration path should have state.level as 2
+                      // as it is defined within level 2 traversal and the node is
+                      // not visited in the next sub-traversal
+                      contextLevel = path.state.level;
```
Comment (JLHwung) [inline packages/babel-traverse/test/traverse.js:341]: In the main branch the `contextLevel` is `1`, which is incorrect since Babel leaks the outer context to the inner sub-traversal.

**Review by nicolo-ribaudo — APPROVED** [review]

File: packages/babel-traverse/test/traverse.js (hunk 1 above)
Comment (nicolo-ribaudo) [reply packages/babel-traverse/test/traverse.js:341]: Thanks!
