### PR TITLE
Fix(estree): Reset export's start after decorator

### LINKED ISSUE #15085: [Bug]: Some issue in @babel/parser version 7.20.0
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

After we moved from version 7.19.6 to 7.20.0 we got those new errors:

SyntaxError: A decorated export must export a class declaration.
at instantiate /node_modules/@babel/parser/src/parse-error/credentials.ts:62:21

TypeError: Cannot read property 'before' of undefined
at checkSpacingBefore

Can you check and fix it, please?

### Configuration file name

package.json

### Configuration

.....
"devDependencies": {
    "@babel/cli": "7.12.10",
    "@babel/core": "7.12.10",
    "@babel/plugin-proposal-class-properties": "7.12.1",
    "@babel/plugin-proposal-decorators": "7.12.12",
    "@babel/plugin-proposal-export-default-from": "7.12.1",
    "@babel/plugin-proposal-export-namespace-from": "7.12.1",
    "@babel/plugin-proposal-function-bind": "7.12.1",
    "@babel/plugin-proposal-nullish-coalescing-operator": "7.12.1",
    "@babel/plugin-proposal-optional-chaining": "7.12.7",
    "@babel/plugin-syntax-dynamic-import": "7.8.3",
    "@babel/plugin-transform-runtime": "7.12.10",
    "@babel/preset-env": "7.12.11",
    "@babel/preset-react": "7.12.10",
    "@babel/register": "7.18.9",
    "babel-eslint": "10.0.3",
    "babel-plugin-istanbul": "5.2.0",
    "babel-plugin-module-resolver": "3.2.0",
    "@babel/runtime": "7.12.5",
    .....
  },
  ......

### Current and expected behavior

Current: @babel/parser version 7.20.0 not working.
Expected: @babel/parser version 7.20.0 should work as version 7.19.6 worked properly.

### Environment

- Babel version: 7.12.10
- Node: v14.18.3
- npm version: 6.14.15
- OS: Red Hat Enterprise Linux Server 7.6 (Maipo)
- Monorepo: no

### Possible solution

To revert some latest changes.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #15085 
| Patch: Bug Fix?          | Y
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

In this PR we partially reverts https://github.com/babel/babel/pull/15032 when `estree` plugin is enabled, so that the legacy syntax `@dec export default class {}` still work with the `keyword-spacing` rule.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15107"></a>

### CODE REVIEW

File: eslint/babel-eslint-tests/test/integration/eslint/verify.js [hunk 1]
```diff
@@ -1073,32 +1099,6 @@ describe("verify", () => {
   });
 
   describe("decorators #72 (legacy)", () => {
-    function verifyDecoratorsLegacyAndAssertMessages(
```
Comment (JLHwung) [inline eslint/babel-eslint-tests/test/integration/eslint/verify.js:1076]: This helper is moved to the top level.

File: packages/babel-parser/test/fixtures/estree/export/decorator-before-export/output.json [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+  "start":0,"end":51,"loc":{"start":{"line":1,"column":0},"end":{"line":2,"column":28}},
+  "program": {
+    "type": "Program",
+    "start":0,"end":51,"loc":{"start":{"line":1,"column":0},"end":{"line":2,"column":28}},
+    "sourceType": "module",
+    "interpreter": null,
+    "body": [
+      {
+        "type": "ExportNamedDeclaration",
+        "start":5,"end":22,"loc":{"start":{"line":1,"column":5},"end":{"line":1,"column":22}},
```
Comment (JLHwung) [inline packages/babel-parser/test/fixtures/estree/export/decorator-before-export/output.json:12]: When `estree` is enabled, we restore the pre-7.20 behaviour: the `ExportNamedDeclaration` now starts at the `export` token.

**Review by liuxingbaoyu — APPROVED** [review]

**Review by nicolo-ribaudo — APPROVED** [review]
