### PR TITLE
[ts] Check if param is assignable when parsing arrow return type

### LINKED ISSUE #11038: `typescript` preset: incompatible with `+=` operator inside arrow functions, nested in ternary
## Bug Report

- [x] I would like to work on a fix!
  I have close to zero experience with Babel's internals though. I would not be offended, if you think you can fix it yourself quicklier.

**Current Behavior**
The `typescript` preset is incompatible with [`d3-array/cumsum.js`](https://github.com/d3/d3-array/blob/master/src/cumsum.js). The issue seems to only occur for arrow functions using the `+=` operator, nested inside a ternary. When `typescript` is disabled, the code compiled without any issues.

**Input Code**
- Original broken `d3-array/cumsum.js`: [REPL](https://babeljs.io/en/repl#?browsers=&build=&builtIns=false&spec=false&loose=true&code_lz=KYDwDg9gTgLgBAE2AMwIYFcA29noHYDGMAlhHnAegLYDO1AFAG6qbrA0A0czrwEyASjgBvAFBxuqKHDpU4AXjgAGLsTxIQC5QG5xcKMBjoo5AGKYIqGADYALAEEoUVAE8AdMigQqTFm06SvPwK8or4SMhqwAh6EgD83AoAfHD0snAA1IoZjHAAPnnKArFwAFyJ8ilp1JnZPGz8TKrqoBkZXPXsQgVFAroAvkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Ctypescript&prettier=true&targets=&version=7.8.3&externalPlugins=)
- Minimal reproduction: [REPL](https://babeljs.io/en/repl#?browsers=&build=&builtIns=false&spec=false&loose=true&code_lz=AwAg_CBuILwHwgBQGcCuBbEBqGUCUIAXFLAsANxA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Ctypescript&prettier=true&targets=&version=7.8.3&externalPlugins=)

```js
0 ? v => (sum += v) : v => 0;
```

> /repl.ts: Only '=' operator can be used for specifying default value. (1:13)
> 
> > 1 | 0 ? v => (sum += v) : v => 0;

**Expected behavior/code**
Babel should compile the above code with `typescript` enabled.

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #11038
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

This is the third attempt at fixing #11038:
- https://github.com/babel/babel/pull/11992, reverted by https://github.com/babel/babel/pull/12173 because the tests were failing
- https://github.com/babel/babel/pull/12183, reverted by https://github.com/babel/babel/pull/12198 because of https://github.com/babel/babel/issues/12195 (test for the regression added by https://github.com/babel/babel/pull/12203)

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/13581"></a>

### CODE REVIEW

File: packages/babel-parser/src/parser/lval.js [hunk 1]
```diff
@@ -229,6 +229,49 @@ export default class LValParser extends NodeUtils {
...
+      case "ArrayPattern":
+      case "AssignmentPattern":
+        return true;
+
+      case "ObjectExpression": {
+        const last = node.properties.length - 1;
+        return node.properties.every((prop, i) => {
+          return (
+            prop.type !== "ObjectMethod" &&
+            (i === last || prop.type !== "SpreadElement") &&
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/src/parser/lval.js:245]: The bug that caused the regression was that this was using `=== "SpreadElement"` instead of `!==`.

Comment (JLHwung) [reply packages/babel-parser/src/parser/lval.js:245]: Should we also sync the changes to `flow` plugin?

**Comment by nicolo-ribaudo** [comment]
The failure is a regression.

File: packages/babel-parser/src/parser/expression.js [hunk 2]
```diff
@@ -1544,7 +1544,8 @@ export default class ExpressionParser extends LValParser {
     return parenExpression;
   }
 
-  shouldParseArrow(): boolean {
+  // eslint-disable-next-line no-unused-vars
```
Comment (sosukesuzuki) [inline packages/babel-parser/src/parser/expression.js:1547]: It is better to add the comment like below:
```suggestion
  // eslint-disable-next-line no-unused-vars -- `params` is used in typescript plugin
```

File: packages/babel-parser/src/parser/lval.js [hunk 3]
```diff
@@ -60,7 +60,7 @@ export default class LValParser extends NodeUtils {
    - RestElement is not the last element
    - Missing `=` in assignment pattern
 
-   NOTE: There is a corresponding "isAssignable" method in flow.js.
+   NOTE: There is a corresponding "isAssignable" method.
    When this one is updated, please check if also that one needs to be updated.
```
[the remark this answers is not in the document]
Comment (nicolo-ribaudo) [reply packages/babel-parser/src/parser/lval.js:64]: I actually like this comment: even if they are in the same file, it's still easy to miss `isAssignable` when updating `toAssignable`.

File: packages/babel-parser/src/parser/lval.js (hunk 1 above)
Comment (KFlash) [reply packages/babel-parser/src/parser/lval.js:247]: Why use 'every' ? It's slow vs a native for-loop

File: packages/babel-parser/src/parser/lval.js [hunk 4]
```diff
@@ -235,6 +236,7 @@ export default class LValParser extends NodeUtils {
       case "ObjectPattern":
       case "ArrayPattern":
       case "AssignmentPattern":
+      case "RestElement":
```
Comment (KFlash) [inline packages/babel-parser/src/parser/lval.js:239]: @nicolo-ribaudo What about a lookup table? This switch is slow because of 1) string comparison 2) many cases 3) hard to optimize in v8

Comment (nicolo-ribaudo) [reply packages/babel-parser/src/parser/lval.js:239]: I don't think this switch relies on string comparisons: these strings are always constants in our code so V8 will atomize them and just compare them as pointers (but @JLHwung knows more than me about this)

Comment (KFlash) [reply packages/babel-parser/src/parser/lval.js:239]: v8 will convert this switch to a lookup, so it's faster if you do it.

**Review by JLHwung — APPROVED** [review]

**Review by sosukesuzuki — APPROVED** [review]

**Comment by KFlash** [comment]
Merged, but performance not improved. What's the reason?

**Comment by nicolo-ribaudo** [comment]
That change doesn't have an observable impact on the normal `@babel/parser` usage.

**Comment by cederom** [comment]
Thank you guys :-) Then this release will land into `npm`? `7.15.0` is still the latest one over there :-)

**Comment by JLHwung** [comment]
It is fixed in `@babel/parser` `7.15.3`, `@babel/parser` is a dependency of `@babel/core`.
