### PR TITLE
Kill the "shadow-functions.js" internal plugin in favor of an explicit helper

### LINKED ISSUE #3930: super is not working inside methods marked async (T6895)
> Issue originally made by Dmitriy Krasnikov (dmitriy.krasnikov)
### Bug information
- **Babel version:** 6.3.26
- **Node version:** 5.3
- **npm version:** 3.3.12
### Options

```
{
  plugins:[
    "transform-async-to-generator",
  ]
}
```
### Input code

``` js
export class BaseClass {
  async test(id){
    console.log(id);
  }
}
export class ChildClass extends BaseClass{
  async test(id){
    id=1;
    super.test(id);
  }
}

let cls = new ChildClass();
cls.test(5);
```
### Description

Outputs:

```js
export class BaseClass {
  test(id) {
    return _asyncToGenerator(function* () {
      console.log(id);
    })();
  }
}
export class ChildClass extends BaseClass {
  test(id) {
    return _asyncToGenerator(function* () {
      id = 1;
      super.test(id);
    })();
  }
}

let cls = new ChildClass();
cls.test(5);
```

### LINKED ISSUE #5597: [7.0] Investigate what would be needed to remove the shadow-function.js internal plugin
This plugin is ugly and requires us to tack private undocumented properties onto AST nodes so that `this` and `arguments` are handled properly when processing scopes.

Ideally the rewriting and hoisting of these values would be handled by some helper that was used by all of the places we need to normalize these values. We should investigate what if anything might be blocking us from doing that.

The primary thing that comes to mind is that when we transform these things, we need to take into account _anything_ that might care about `this` in those contexts. e.g.

```
async fn(){
  super.fn();
}
```
when rewriting, we have to move the function content inside of a wrapper, which breaks `super`.

```
var fn = function(){
  return (...args) => arguments;
}
```
When converting this arrow to a function, we need to rewrite `arguments`.

I think this is doable, but we'll need to keep plugin ordering in mind. The `super` case above for instance is a bug we currently have that I think is fixable easily if we do this.

### PR DESCRIPTION
**Pull request by loganfsmyth**
| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          | Y
| Major: Breaking Change?  | Y, if something was relying on this stuff not being unwrapped immediately, or was using the `_forceShadow`, `.shadow` or `._shadowedFunctionLiteral` properties. Hopefully minimal though.
| Minor: New Feature?      | Maybe?
| Deprecations?            | 
| Spec Compliancy?         | 
| Tests Added/Pass?        | 
| Fixed Tickets            | Fixes #5597, Fixes #3930 
| License                  | MIT
| Doc PR                   | 
| Dependency Changes       | 

This removes the private "shadow"-related properties from the AST and relies on explicit traversal to handle the conversion of arrow functions into non-arrow functions.

I've also added support for handling `super` and `new.target` into the generic utility to handle cases that we could not handle properly with the old implementation.

This also has the added benefit of not performing unexpected transformations on the AST when no plugins were enabled by the user, since we've had users reporting this as an annoyance on several occasions. This is also a bit of a blocker for any work trying to make Babel a more general codemod-like tool.

### CODE REVIEW

File: packages/babel-plugin-transform-async-generator-functions/test/fixtures/nested/arrows-in-declaration/expected.js [hunk 1]
```diff
@@ -2,9 +2,7 @@ let g = (() => {
   var _ref = babelHelpers.asyncGenerator.wrap(function* () {
     var _this = this;
 
-    (function () {
-      return _this;
-    });
+    () => this;
```
Comment (loganfsmyth) [inline packages/babel-plugin-transform-async-generator-functions/test/fixtures/nested/arrows-in-declaration/expected.js]: These changes are from the removed call on https://github.com/babel/babel/pull/5677/files#diff-3953cdd7a44c58e0431a2e202efb64d4L31 that wasn't needed.

File: packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/object-method-with-super/expected.js [hunk 2]
```diff
@@ -0,0 +1,11 @@
+class Foo extends class {} {
+  method() {
+    var _superprop_callMethod = (..._args) => super.method(..._args);
```
Comment (loganfsmyth) [inline packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/object-method-with-super/expected.js]: It's not pretty, but it's the only way we can deal with this.

File: packages/babel-plugin-transform-es2015-block-scoping/src/index.js [hunk 3]
```diff
@@ -416,56 +416,79 @@ class BlockScoping {
     // build the closure that we're going to wrap the block with, possible wrapping switch(){}
     const fn = t.functionExpression(null, params,
       t.blockStatement(isSwitch ? [block] : block.body));
-    fn.shadow = true;
```
Comment (loganfsmyth) [inline packages/babel-plugin-transform-es2015-block-scoping/src/index.js]: This whole set of changes is gross and probably the most likely to be missing edge cases, but it works as far as I can tell.

These changes were all needed so that we can get access to the final NodePath for the function, since it wasn't available anywhere before.

File: packages/babel-plugin-transform-es2015-block-scoping/test/fixtures/general/for-break-continue-return/expected.js [hunk 4]
```diff
@@ -1,5 +1,5 @@
 (function () {
-  var _loop = function (i) {
+  var _loop2 = function (i) {
```
Comment (loganfsmyth) [inline packages/babel-plugin-transform-es2015-block-scoping/test/fixtures/general/for-break-continue-return/expected.js]: A change in ordering in block scoping means these variable names are generated in opposite order now, thus breaking the test.

File: packages/babel-plugin-transform-es2015-classes/src/index.js [hunk 5]
```diff
@@ -46,6 +46,10 @@ export default function ({ types: t }) {
         if (state.opts.loose) Constructor = LooseTransformer;
 
         path.replaceWith(new Constructor(path, state.file).run());
+
+        if (path.isCallExpression() && path.get("callee").isArrowFunctionExpression()) {
+          path.get("callee").arrowFunctionToExpression();
```
Comment (loganfsmyth) [inline packages/babel-plugin-transform-es2015-classes/src/index.js]: We don't really have a firm policy for when it's cool to insert actual arrows, so I added a few new arrows in place of `.shadow` but explicitly converted them to keep the tests passing.

File: packages/babel-plugin-transform-es2015-object-super/src/index.js [hunk 6]
```diff
@@ -1,46 +1,39 @@
...
-      Super(path) {
-        const parentObj = path.findParent((path) => path.isObjectExpression());
-        if (parentObj) parentObj.node[CONTAINS_SUPER] = true;
-      },
+      ObjectExpression(path, state) {
+        let objectRef;
+        const getObjectRef = () => objectRef = objectRef || path.scope.generateUidIdentifier("obj");
 
-      ObjectExpression: {
-        exit(path, file) {
```
Comment (loganfsmyth) [inline packages/babel-plugin-transform-es2015-object-super/src/index.js]: This implementation had to change because the usage of the `exit` handler meant that the arrow transform would fail for
```
var obj = {
  method(){
    var fn = () => super.method();
  }
};
```
since it can't handle `super`, meaning that for object-super to work, it needs to run before the arrow transform.

File: packages/babel-traverse/src/path/replacement.js [hunk 7]
```diff
@@ -239,6 +238,8 @@ export function replaceExpressionWithStatements(nodes: Array<Object>) {
       }
     }
 
+    this.get("callee").arrowFunctionToExpression();
```
Comment (loganfsmyth) [inline packages/babel-traverse/src/path/replacement.js]: Again just to make the tests pass, we could also leave this out and insert real arrows if we want to.

File: packages/babel-types/src/definitions/es2015.js [hunk 8]
```diff
@@ -245,10 +245,10 @@ defineType("MetaProperty", {
   fields: {
     // todo: limit to new.target
     meta: {
-      validate: assertValueType("string"),
+      validate: assertNodeType("Identifier"),
```
Comment (loganfsmyth) [inline packages/babel-types/src/definitions/es2015.js]: These were just wrong :P

File: packages/babel-plugin-transform-es2015-object-super/src/index.js (hunk 6 above)
Comment (hzoo) [inline packages/babel-plugin-transform-es2015-object-super/src/index.js]: So there's no need for the `CONTAINS_SUPER` check anymore?

File: packages/babel-plugin-transform-es2015-arrow-functions/test/fixtures/arrow-functions/spec/expected.js [hunk 9]
```diff
@@ -14,7 +14,7 @@ function foo() {
 
     return function () {
       babelHelpers.newArrowCheck(this, _this2);
-      return this;
```
Comment (hzoo) [inline packages/babel-plugin-transform-es2015-arrow-functions/test/fixtures/arrow-functions/spec/expected.js]: looks like this used to be a bug too?

File: packages/babel-plugin-transform-es2015-classes/src/index.js (hunk 5 above)
Comment (hzoo) [inline packages/babel-plugin-transform-es2015-classes/src/index.js]: Would hope that the dependency system would allow us to add/remove, preferring to instead arrows/newer syntax

File: packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/object-method-with-super/expected.js (hunk 2 above)
Comment (xtuc) [inline packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/object-method-with-super/expected.js]: This looks okay to me. Nice job, you use the same reference to the `super.method` call (instead of two separate) :+1:

File: packages/babel-traverse/src/path/ancestry.js [hunk 10]
```diff
@@ -200,59 +200,3 @@ export function inType() {
...
- * - _forceShadow - If truthy, this specific identifier will be bound in the closest
- *    Function that is not flagged "shadow", or the Program.
- * - _shadowedFunctionLiteral - When set to a NodePath, this specific identifier will be bound
- *    to this NodePath/Node or the Program. If this path is not found relative to the
- *    starting location path, the closest function will be used.
- *
- * Please Note, these flags are for private internal use only and should be avoided.
- * Only "shadow" is a public property that other transforms may manipulate.
- */
-
```
Comment (xtuc) [inline packages/babel-traverse/src/path/ancestry.js]: Could we keep this comment. It helped me understand what `shadow`'ing meant.

File: packages/babel-plugin-transform-es2015-classes/src/index.js (hunk 5 above)
Comment (loganfsmyth) [inline packages/babel-plugin-transform-es2015-classes/src/index.js]: Yeah, we can always drop this now if we want, since the plugins are already in a fine order for it AFAIK, I just figured it would be better to leave that for a separate PR.

File: packages/babel-plugin-transform-es2015-object-super/src/index.js (hunk 6 above)
Comment (loganfsmyth) [inline packages/babel-plugin-transform-es2015-object-super/src/index.js]: I don't think there's a good reason to have it if we've not using the `exit` handler, since the main benefit of it was avoiding traversing the methods more than once. and there's no way to avoid that without the `exit`, but the `exit` would run it all in the wrong order.

File: packages/babel-plugin-transform-es2015-arrow-functions/test/fixtures/arrow-functions/spec/expected.js (hunk 9 above)
Comment (loganfsmyth) [inline packages/babel-plugin-transform-es2015-arrow-functions/test/fixtures/arrow-functions/spec/expected.js]: Since it is `.bind` both work, this way is just a little more consistent with the non-spec arrow transform, since they share more code now.

File: packages/babel-traverse/src/path/ancestry.js (hunk 10 above)
Comment (loganfsmyth) [inline packages/babel-traverse/src/path/ancestry.js]: Happy to chat if you have suggestions. This PR mostly removes the whole concept of "shadowing" that we had before, in favor of fixing everything up right away, so it's not obvious where we'd put this, or if it would be useful to people at this point.

Comment (xtuc) [inline packages/babel-traverse/src/path/ancestry.js]: Yes, I you did great by removing unnecessary complexity. The term variable shadowing as explained in the [wiki there](https://en.wikipedia.org/wiki/Variable_shadowing) is confusing to me. It seems that shadowing wasn't the correct concept for passing `this` since it's just a transpilation technique. We could maybe chat about that on Slack if you have time?

File: packages/babel-traverse/src/path/conversion.js [hunk 11]
```diff
@@ -25,14 +25,415 @@ export function ensureBlock() {
...
+
+  if (specCompliant) {
+    // TODO: This approach is broken inside class constructor functions, but is fixable.
+    this.get("body").unshiftContainer(
+      "body",
+      t.expressionStatement(t.callExpression(this.hub.file.addHelper("newArrowCheck"), [
+        t.thisExpression(),
+        t.identifier(thisBinding),
+      ]))
+    );
```
Comment (Kovensky) [inline packages/babel-traverse/src/path/conversion.js]: Looks like I got you a merge conflict by merging #5620

File: packages/babel-plugin-transform-es2015-arrow-functions/test/fixtures/arrow-functions/spec/expected.js (hunk 9 above)
Comment (Kovensky) [inline packages/babel-plugin-transform-es2015-arrow-functions/test/fixtures/arrow-functions/spec/expected.js]: I'd prefer if we could keep `this` as `this`, but it's not like it's incorrect code here. Minifies better too!

File: packages/babel-traverse/src/path/conversion.js [hunk 12]
```diff
@@ -25,14 +25,415 @@ export function ensureBlock() {
...
+
+  fnPath.traverse({
+    Function(child) {
+      if (child.isArrowFunctionExpression() || child.isClassProperty()) return;
+      child.skip();
+    },
+    ThisExpression(child) {
+      thisPaths.push(child);
+    },
+    JSXIdentifier(child) {
```
Comment (Kovensky) [inline packages/babel-traverse/src/path/conversion.js]: Is this for `<this.Foo/>`?

File: packages/babel-traverse/test/arrow-transform.js [hunk 13]
```diff
@@ -0,0 +1,439 @@
...
+      () => {
+        super(345);
+        this;
+      };
+      super();
+      this;
+      () => super();
+      () => this;
+    `, `
+      var _supercall = (..._args) => _this = super(..._args),
```
Comment (Kovensky) [inline packages/babel-traverse/test/arrow-transform.js]: Was wondering if something would catch multiple `super()` invocations, but I guess that's the job of the JS engine / class transform.

File: packages/babel-helper-remap-async-to-generator/src/index.js [hunk 14]
```diff
@@ -95,6 +90,9 @@ function classOrObjectMethod(path: NodePath, callId: Object) {
   // Regardless of whether or not the wrapped function is a an async method
   // or generator the outer function should not be
   node.generator = false;
+
+  // Unwrap the wrapper IIFE's environment so super and this and such still work.
+  path.get("body.body.0.argument.callee.arguments.0").unwrapFunctionEnvironment();
```
Comment (loganfsmyth) [inline packages/babel-helper-remap-async-to-generator/src/index.js]: It's gross garbage :P It's reaching in to the path where we put the IIFE, since we only get access to the path _after_ it is inserted, so we have to insert it then do this gross stuff to get the reference.

File: packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/deeply-nested-asyncs/expected.js [hunk 15]
```diff
@@ -11,11 +11,12 @@ let s = (() => {
       var _ref2 = babelHelpers.asyncToGenerator(function* (y, a) {
         let r = (() => {
           var _ref3 = babelHelpers.asyncToGenerator(function* (z, b) {
+            yield z;
+
             for (var _len2 = arguments.length, innerArgs = Array(_len2 > 2 ? _len2 - 2 : 0), _key2 = 2; _key2 < _len2; _key2++) {
               innerArgs[_key2 - 2] = arguments[_key2];
             }
 
-            yield z;
```
Comment (loganfsmyth) [inline packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/deeply-nested-asyncs/expected.js]: I forget, but this change seems _more_ like what it's supposed to do, so I didn't worry about it. It's possible I looked into the reason, but I don't remember anymore.

File: packages/babel-plugin-transform-es2015-arrow-functions/src/index.js [hunk 16]
```diff
@@ -1,34 +1,17 @@
...
-          path.replaceWith(t.callExpression(
-            t.memberExpression(node, t.identifier("bind")),
-            [t.thisExpression()]
-          ));
-        } else {
-          path.arrowFunctionToShadowed();
-        }
+        path.arrowFunctionToExpression({
+          // While other utils may be fine inserting other arrows to make more transforms possible,
+          // the arrow transform itself absolutely cannot insert new arrow functions.
```
Comment (loganfsmyth) [inline packages/babel-plugin-transform-es2015-arrow-functions/src/index.js]: Why not both? :P

File: packages/babel-plugin-transform-es2015-block-scoping/src/index.js [hunk 17]
```diff
@@ -416,56 +416,79 @@ class BlockScoping {
...
 
-    let ref = fn;
-
-    if (this.loop) {
-      ref = this.scope.generateUidIdentifier("loop");
-      this.loopPath.insertBefore(t.variableDeclaration("var", [
-        t.variableDeclarator(ref, fn),
-      ]));
-    }
+    const has = this.has;
```
Comment (loganfsmyth) [inline packages/babel-plugin-transform-es2015-block-scoping/src/index.js]: I think this was leftover from copy-pasting from https://github.com/babel/babel/pull/5677/files/c8ff06f90661f5e67a93b7e2f2d387a029edd98a#diff-775ae6452de339480d54604c7d217b5dL463

Looks like `this.has` is used one other place, but otherwise isn't updated, so you're right I could move this up farther.

File: packages/babel-plugin-transform-es2015-block-scoping/src/index.js [hunk 18]
```diff
@@ -416,56 +416,79 @@ class BlockScoping {
...
+      basePath = ".argument" + basePath;
     }
 
     // handlers async functions
     const hasAsync = traverse.hasType(fn.body, this.scope, "AwaitExpression", t.FUNCTION_TYPES);
     if (hasAsync) {
       fn.async = true;
       call = t.awaitExpression(call);
+      basePath = ".argument" + basePath;
     }
```
Comment (loganfsmyth) [inline packages/babel-plugin-transform-es2015-block-scoping/src/index.js]: No idea, I didn't realize this logic even did this until inspecting this code.

File: packages/babel-traverse/src/path/conversion.js (hunk 11 above)
Comment (loganfsmyth) [inline packages/babel-traverse/src/path/conversion.js]: No worries.

File: packages/babel-traverse/src/path/conversion.js (hunk 12 above)
Comment (loganfsmyth) [inline packages/babel-traverse/src/path/conversion.js]: It is, I guess I should make this `JSXMemberExpression` now that you mention it though.

File: packages/babel-traverse/test/arrow-transform.js (hunk 13 above)
Comment (loganfsmyth) [inline packages/babel-traverse/test/arrow-transform.js]: That I think we should leave up to the class transform, it could certainly add logic for that.

File: packages/babel-traverse/src/path/ancestry.js (hunk 10 above)
Comment (loganfsmyth) [inline packages/babel-traverse/src/path/ancestry.js]: Yeaaah talk about confusing naming.

File: packages/babel-plugin-transform-es2015-arrow-functions/test/fixtures/arrow-functions/spec/expected.js (hunk 9 above)
Comment (loganfsmyth) [inline packages/babel-plugin-transform-es2015-arrow-functions/test/fixtures/arrow-functions/spec/expected.js]: Up for expanding on your reasoning? My motivation was mostly that it's less separation between spec and non-spec mode, but it could be made to work either way I guess.

File: packages/babel-traverse/src/path/conversion.js (hunk 12 above)
Comment (loganfsmyth) [inline packages/babel-traverse/src/path/conversion.js]: Added some checks to explicitly verify the location of the identifier.

**Comment by loganfsmyth** [comment]
Okay, I rebased to fix the merge conflict with spec function naming, and addressed the few issues people have raised except the one question of `this` vs `_this` in arrow spec mode. Happy to chat on that on Slack tomorrow.

File: packages/babel-traverse/src/path/ancestry.js (hunk 10 above)
Comment (xtuc) [inline packages/babel-traverse/src/path/ancestry.js]: I talked with @loganfsmyth and now I'm fine with that.

File: packages/babel-plugin-transform-es2015-arrow-functions/test/fixtures/arrow-functions/spec/expected.js (hunk 9 above)
Comment (loganfsmyth) [inline packages/babel-plugin-transform-es2015-arrow-functions/test/fixtures/arrow-functions/spec/expected.js]: Alright, I added support for spec arrow in subclass constructors, and made `this` stay `this` in spec arrows except for the subclass constructor case.

**Comment by mikemorancodes** [comment]
What if I just need to fix the #3930 issue?
