### PR TITLE
Fix handling of comments with decorators before `export`

### LINKED ISSUE #12276: @babel/generator  CommentBlock positon changed after generator  when using decorators-legacy and decoratorsBeforeExport
## Bug Report

**Current behavior**

```js
//ORIGINAL  CODE:
var code_str =`
    /*__qa-anchor:uuid@routes__*/          ==================>HERE
    @NgModule({})
    export class Tst { }
`
var t = parse(code_str)              //babel/parser
var ncd = gen(t)                   //babel/generator

//NEW CODE:
/*
    > console.log(ncd)
    @NgModule({})
    export                                                   ===================> WHY?
    /*__qa-anchor:uuid@routes__*/           ===================> the comment position is changed 
    class Tst {}

*/

```

**Input Code**

```js
const typ = require("@babel/types")
const _parse = require('@babel/parser').parse
const _gen = require('@babel/generator').default

function parse(code_str) {
    //decorators-legacy for angular style
    let ast= _parse(code_str,{sourceType:'module',ranges:false,plugins:['typecript','decorators-legacy',"jsx","classProperties"]})
    return(ast)
}

function gen(ast) {
    //decoratorsBeforeExport for angular style
    return(_gen(ast,{comments:true,decoratorsBeforeExport:true}).code)
}


var code_str =`
    /*__qa-anchor:uuid@routes__*/
    @NgModule({})
    export class Tst { }
`

var t = parse(code_str)
/*    -------------------------------------------------------everything looks fine
> t.program.body[0].declaration.type
'ClassDeclaration'
> t.program.body[0].declaration.leadingComments       ------>leadingComments of declaration
[
  {
    type: 'CommentBlock',
    value: '__qa-anchor:uuid@routes__',
    start: 5,
    end: 34,
    loc: SourceLocation { start: [Position], end: [Position] }
  }
]
>

*/

var ncd = gen(t)                             ================>after using generator

/*
    > console.log(gen(t))
    @NgModule({})
    export                                  ===================>
    /*__qa-anchor:uuid@routes__*/           ===================> the comment position is changed 
    class Tst {}

*/

var nt = parse(ncd)

/*
> nt.program.body[0].declaration.id.leadingComments        ==============> the leadingComments changed to id
[
  {
    type: 'CommentBlock',
    value: '__qa-anchor:uuid@routes__',
    start: 21,
    end: 50,
    loc: SourceLocation { start: [Position], end: [Position] }
  }
]
>

> nt.program.body[0].declaration.leadingComments                 ======> undefined
undefined
>

*/

```

**Environment**

- Babel version(s): [6.26.0 (babel-core 6.26.3)]
- Node/npm version: [v12.16.3/6.14.4]
- OS: [Linux server_name 4.15.0-118-generic #119-Ubuntu SMP Tue Sep 8 12:30:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux]
- Monorepo: [maybe yes, i use @babel/generator ]
- How you are using Babel: [`code`]

**Possible Solution**

- in my usage, i need to insert a typ.EmptyStatement() after each CommentBlock :

```js
var code_str =`
    /*__qa-anchor:uuid@routes__*/
    ;                              =========================> insert a EmptyStatement after Each CommentBlock
    @NgModule({})
    export class Tst { }
`

var t = parse(code_str)
var ncd = gen(t)

> console.log(ncd)
/*__qa-anchor:uuid@routes__*/
;                               =========================> insert a EmptyStatement after Each CommentBlock
@NgModule({})
export class Tst {}
undefined
>
```

**Additional context**

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #12276
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15032"></a>

### CODE REVIEW

**Review by liuxingbaoyu — DISMISSED** [review]

File: packages/babel-parser/src/parser/statement.ts [hunk 1]
```diff
@@ -522,13 +522,49 @@ export default abstract class StatementParser extends ExpressionParser {
...
     if (decorators.length) {
       node.decorators = decorators;
       this.resetStartLocationFromNode(node, decorators[0]);
       this.state.decoratorStack[this.state.decoratorStack.length - 1] = [];
+
+      // In case of decorators followed by `export`, we manually mark the
+      // comments between `export` and `class` as leading comments of the
+      // class declaration node.
+      // This is needed because the class location range overlaps with
+      // `export`, and thus they would me marked as inner comments of
```
Comment (JLHwung) [inline packages/babel-parser/src/parser/statement.ts:545]:
```suggestion
      // `export`, and thus they would be marked as inner comments of
```

File: packages/babel-parser/src/parser/statement.ts [hunk 2]
```diff
@@ -522,13 +522,49 @@ export default abstract class StatementParser extends ExpressionParser {
...
+      // the class declaration.
+      //   @dec export /* comment */ class Foo {}
+      // See [parseDecorators] for the hanling of comments before decorators
```
Comment (JLHwung) [inline packages/babel-parser/src/parser/statement.ts:548]:
```suggestion
      // See [parseDecorators] for the handling of comments before decorators
```

File: packages/babel-parser/src/parser/statement.ts [hunk 3]
```diff
@@ -522,13 +522,49 @@ export default abstract class StatementParser extends ExpressionParser {
...
+      if (this.decoratorsEnabledBeforeExport()) {
+        const {
+          start,
+          lastTokStart,
+          lastTokEndLoc: { index: lastTokEnd },
+        } = this.state;
+
+        if (this.input.slice(lastTokStart, lastTokEnd) === "export") {
```
Comment (JLHwung) [inline packages/babel-parser/src/parser/statement.ts:556]: Can we move the comments manipulation to https://github.com/babel/babel/blob/ddaee9025c3af7d7eebdda62c89784074c8c034a/packages/babel-parser/src/parser/comments.ts#L164 ?

So that comments manipulation are placed within a single file and we probably don't have to do an `export` lookback.

Comment (nicolo-ribaudo) [reply packages/babel-parser/src/parser/statement.ts:556]: I moved the logic to comments.ts, but I'm not sure about how to do it in finalizeComment. Specifically, I don't think we can distinguish `/* 1 */` and `/* 2 */` when finalizing the comments of the class node:
```js
@dec export default /* 1 */ class /* 2 */ extends X {}
```

(I just realized that this PR doesn't support the `default` case, I'll add it)

**Comment by nicolo-ribaudo** [comment]
I completely rewrote how decorators are attached to classes:
- first we finalize the `ClassDeclaration`/`ExportNamedDeclaration` nodes, attaching their comments
- then we attach the decorators

while doing so I also removed the `decoratorStack` state, which was not needed anymore.

**Comment by nicolo-ribaudo** [comment]
There are still some generator bugs

**Comment by nicolo-ribaudo** [comment]
Before this PR:
```js
@dec export class A {}
           ^^^^^^^^^^^
           ExportDeclaration

^^^^^^^^^^^^^^^^^^^^^^
   ClassDeclaration

^^^^
Decorator
```
After this PR:
```js
@dec export class A {}
^^^^^^^^^^^^^^^^^^^^^^
   ExportDeclaration

^^^^^^^^^^^^^^^^^^^^^^
   ClassDeclaration

^^^^
Decorator
```

(in both cased the nodes hierarchy if `ExportDeclaration > ClassDeclaration > Decorator`)

File: packages/babel-parser/src/parser/statement.ts [hunk 4]
```diff
@@ -1102,6 +1112,8 @@ export default abstract class StatementParser extends ExpressionParser {
   parseExpressionStatement(
     node: Undone<N.ExpressionStatement>,
     expr: N.Expression,
+    /* eslint-disable @typescript-eslint/no-unused-vars -- used in TypeScript parser */
```
Comment (liuxingbaoyu) [inline packages/babel-parser/src/parser/statement.ts:1124]:
```suggestion
    /* eslint-disable-next-line @typescript-eslint/no-unused-vars -- used in TypeScript parser */
```

File: packages/babel-parser/src/parser/statement.ts [hunk 5]
```diff
@@ -1102,6 +1121,8 @@ export default abstract class StatementParser extends ExpressionParser {
...
```
Comment (liuxingbaoyu) [inline packages/babel-parser/src/parser/statement.ts:1124]:
```suggestion
    /* eslint-disable-next-line @typescript-eslint/no-unused-vars -- used in TypeScript parser */
```

**Review by liuxingbaoyu — APPROVED** [review]
Great job!
Also the E2E test failure is related, I'm not sure if that is expected.

**Comment by nicolo-ribaudo** [comment]
@fisker / @sosukesuzuki How does prettier decide when to print decorators before `export` and when to print them after?

**Comment by JLHwung** [comment]
I believe e2e test breaking because prettier uses location of first decorator versus the attached class node to detect decorators before export:

https://github.com/prettier/prettier/blob/ca246afacee8e6d5db508dae01730c9523bbff1d/src/language-js/print/decorators.js#L76

**Comment by nicolo-ribaudo** [comment]
Uhm ok. I can restore the original location of the export declaration, but I believe it's wrong and in Babel 8 we should make it include decorators again (because the a node should always start before is children and end after).

**Comment by liuxingbaoyu** [comment]
https://github.com/prettier/prettier/issues/12806#issuecomment-1120253747
They should not use tokens.

**Review by JLHwung — APPROVED** [review]
I agree that the new location setting makes sense to me. Since prettier has pinned `@babel/parser` so it should be fine even if we ship as-is. Can prettier support the new location setting here? If so we don't have to defer to Babel 8.

**Comment by nicolo-ribaudo** [comment]
Another option that prettier has is to check if `inputSource[exportDeclarationNode.start] === "@"`. Prettier maintainers, how does that sound?

**Comment by fisker** [comment]
End up with `locStart(node) === locStart(decorators[0])` solution, https://github.com/prettier/prettier/pull/13733/files
