### PR TITLE
Add test for fixed block scoping issue

### LINKED ISSUE #8128: Incorrect code generated when running for-of after block-scoping
## Bug Report

The following examples can be found in this gist: https://gist.github.com/rubennorte/f121ed807a1e0bff803ee62cb8783662

**Current Behavior**

Babel generates assignments to undeclared variables when specifying the for-of plugin after block-scoping:

```javascript
var _loop = function (_result) {
  _result = otherValue;
  fn(() => {
    _result;
  });
  //<<<<<<<<<<<< ASSIGNMENT TO UNDECLARED VARIABLE result
  result = _result;
};

for (var _iterator = results, _isArray = Array.isArray(_iterator), _i = 0, _iterator = _isArray ? _iterator : _iterator[Symbol.iterator]();;) {
  var _ref;

  if (_isArray) {
    if (_i >= _iterator.length) break;
    _ref = _iterator[_i++];
  } else {
    _i = _iterator.next();
    if (_i.done) break;
    _ref = _i.value;
  }

  var _result2 = _ref;

  _loop(_result2);
}
```

**Input Code**

```javascript
for (let result of results) {
  result = otherValue;
  fn(() => {
    result;
  });
}
```

**Expected behavior/code**

Something like:

```javascript
var _loop = function (result) {
  result = otherValue;
  fn(() => {
    result;
  });
};

for (var _iterator = results, _isArray = Array.isArray(_iterator), _i = 0, _iterator = _isArray ? _iterator : _iterator[Symbol.iterator]();;) {
  var _ref;

  if (_isArray) {
    if (_i >= _iterator.length) break;
    _ref = _iterator[_i++];
  } else {
    _i = _iterator.next();
    if (_i.done) break;
    _ref = _i.value;
  }

  _loop(_ref);
}
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "plugins": [
    ["@babel/plugin-transform-block-scoping", {"loose": true}],
    ["@babel/plugin-transform-for-of", {"loose": true}]
  ]
}
```

**Environment**
- Babel version(s): v7.0.0-beta.48
- Node/npm version: Node 4.3.2 and Node v9.3.0
- OS: Linux
- How you are using Babel: `cli` and `core`

**Possible Solution**

Inverting the order of the plugins solves the issue, but it shouldn't matter (should it?).

**Additional context/Screenshots**

This seems to happen when there are re-assignments of the variable used to iterate over the values and a function that used it inside the loop. If the value is declared with `var` OR it isn't reassigned OR there isn't a function inside the loop, the issue doesn't happen.

**Edit**: when running Babel with the block-scoping plugin and then **again** with the for-of plugin, the generated code is correct, so it must be an issue traversing the AST with both transforms at the same time.

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Closes #8128
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

#8128 was accidentally fixed in 7.9.0, probably by https://github.com/babel/babel/pull/11262. This PR adds a test to make sure that we don't regress.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/13304"></a>

### CODE REVIEW

File: packages/babel-plugin-transform-block-scoping/test/fixtures/general/issue-8128-for-of-after/output.js [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+  });
+  result = _result;
+};
+
+var _iterator = babelHelpers.createForOfIteratorHelper(results),
+    _step;
+
+try {
+  for (_iterator.s(); !(_step = _iterator.n()).done;) {
+    var result = _step.value;
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-block-scoping/test/fixtures/general/issue-8128-for-of-after/output.js:14]: Plugin ordering changed the output, but that's unavoidable since both apply different transformations to the same thing.

**Review by JLHwung — APPROVED** [review]
