### PR TITLE
Fix some incorrect typeof parsing in flow

### LINKED ISSUE #10571: Babel chokes on valid Flow syntax (`typeof blah.default`)
## Bug Report

package.json
```json
{
    "devDependencies": {
        "@babel/cli": "7.6.4",
        "@babel/core": "7.6.4",
        "@babel/preset-flow": "7.0.0",
        "flow-bin": "0.109.0"
    }
}
```

.flowconfig
```
[include]
src
```

.babelrc
```json
{
    "presets": ["@babel/preset-flow"]
}
```

src/test.js
```js
// @flow
type Stuff = {
  x: number,
  default: string,
};

function f(stuff: Stuff) {
  const x: typeof stuff.x = 1;
  const y: typeof stuff.default = "hi";
}
```

Flow runs fine:
```
$ ./node_modules/.bin/flow 
No errors!
```

Babel does not:
```
$ ./node_modules/.bin/babel src
{ SyntaxError: /Users/kannan/h/babel-flow-default-token/src/test.js: Unexpected keyword 'default' (9:24)

   7 | function f(stuff: Stuff) {
   8 |   const x: typeof stuff.x = 1;
>  9 |   const y: typeof stuff.default = "hi";
     |                         ^
  10 | }
  11 | 
    at Object.raise (/Users/kannan/h/babel-flow-default-token/node_modules/@babel/parser/lib/index.js:6420:17)
    at Object.checkReservedWord (/Users/kannan/h/babel-flow-default-token/node_modules/@babel/parser/lib/index.js:9722:12)
    at Object.parseIdentifierName (/Users/kannan/h/babel-flow-default-token/node_modules/@babel/parser/lib/index.js:9697:12)
    at Object.parseIdentifier (/Users/kannan/h/babel-flow-default-token/node_modules/@babel/parser/lib/index.js:9667:23)
    at Object.flowParseQualifiedTypeIdentifier (/Users/kannan/h/babel-flow-default-token/node_modules/@babel/parser/lib/index.js:1595:23)
    at Object.flowParseGenericType (/Users/kannan/h/babel-flow-default-token/node_modules/@babel/parser/lib/index.js:1605:20)
    at Object.flowIdentToTypeAnnotation (/Users/kannan/h/babel-flow-default-token/node_modules/@babel/parser/lib/index.js:1713:21)
    at Object.flowParsePrimaryType (/Users/kannan/h/babel-flow-default-token/node_modules/@babel/parser/lib/index.js:1732:21)
    at Object.flowParseTypeofType (/Users/kannan/h/babel-flow-default-token/node_modules/@babel/parser/lib/index.js:1617:26)
    at Object.flowParsePrimaryType (/Users/kannan/h/babel-flow-default-token/node_modules/@babel/parser/lib/index.js:1862:23)
  pos: 142,
  loc: Position { line: 9, column: 24 },
  code: 'BABEL_PARSE_ERROR' }
```

My Node version:
```
$ node --version
v8.15.0
```

BTW, I know Flow is processing the file because I added a type error to "test.js" and Flow caught it.

### PR DESCRIPTION
**Pull request by existentialism**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #10571
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

Went and matched parsing behavior in flow parser v0.111.1, and the error message in cases where user wasn't technically overwriting.

### CODE REVIEW

File: packages/babel-parser/src/plugins/flow.js [hunk 1]
```diff
@@ -1134,12 +1151,12 @@ export default (superClass: Class<Parser>): Class<Parser> =>
     ): N.FlowQualifiedTypeIdentifier {
       startPos = startPos || this.state.start;
       startLoc = startLoc || this.state.startLoc;
-      let node = id || this.parseIdentifier();
+      let node = id || this.parseIdentifier(true);
```
Comment (JLHwung) [inline packages/babel-parser/src/plugins/flow.js]: I think we should also replace by `flowParseRestrictedIdentifier` here because
```
interface I extends bool.member {}
```
will [throw](https://flow.org/try/#0JYOwLgpgTgZghgYwgAgJLIgD0iAJgZ2QCMB7EgGwDoBbCao6ZAbwF8g) `unexpected reserved type`, though the error message is not optimal.

Comment (existentialism) [reply packages/babel-parser/src/plugins/flow.js]: Updated with tests!

File: packages/babel-parser/src/plugins/flow.js [hunk 2]
```diff
@@ -22,12 +22,15 @@ import {
   SCOPE_OTHER,
 } from "../util/scopeflags";
 
-const reservedTypes = [
+const reservedTypes = new Set([
+  "_",
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/src/plugins/flow.js]: I wish there was something like https://eslint.org/docs/rules/sort-keys for arrays

File: packages/babel-parser/test/fixtures/flow/type-annotations/typeof-reserved-invalid-2/input.js [hunk 3]
```diff
@@ -0,0 +1,2 @@
+// @flow
+const x: typeof type.interface = "hi";
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/test/fixtures/flow/type-annotations/typeof-reserved-invalid-2/input.js]: I would report this as bug to the flow team, given that `type.interface` is valid in JS :thinking:

File: packages/babel-parser/test/fixtures/flow/type-annotations/typeof-reserved-valid/input.js [hunk 4]
```diff
@@ -0,0 +1,15 @@
+// @flow
+const a: typeof default = "hi";
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/test/fixtures/flow/type-annotations/typeof-reserved-valid/input.js]: This also seem like a flow bug, since `default` is not a valid variable name.
