### PR TITLE
[babel 8] Remove `selfClosing` from `jsxElement` builder

### LINKED ISSUE #14460: [Bug]: 'selfClosing' doesn't work in 't.jsxElement'
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
import g from '@babel/generator';
import * as t from '@babel/types';

const jsxElement = t.jsxElement(t.jsxOpeningElement(t.jsxIdentifier('div'), []), null, [], true);
console.log(g(jsxElement).code); // <div>
const jsxElement2 = t.jsxElement(t.jsxOpeningElement(t.jsxIdentifier('div'), [], true), null, [], true);
console.log(g(jsxElement2).code); // <div />
```

### Configuration file name

_No response_

### Configuration

no config

### Current and expected behavior

Current:
Can not generate self-closing jsx code if pass true to the fourth parameter of `t.jsxElement`;

Expected:
Generate self-closing jsx code if pass true to the fourth parameter of `t.jsxElement`;

### Environment

- Babel versions: 
  - @babel/types 7.17.0
  - @babel/generator 7.17.9
- Node: 14.19.1
- pnpm: 7.0.0-rc.3
- OS: macOS 11.6
- Monorepo: no

### Possible solution

At the type level, remove `t.jsxElement`'s  fourth parameter and remove the `selfClosing` prop in interface `JSXElement`.
Or fix the generator to make sense of `JSXElement`'s `selfClosing` parameter.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by wjw99830**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #14460  
| Patch: Bug Fix?          | ❌
| Major: Breaking Change?  | ✅
| Minor: New Feature?      | ❌
| Tests Added + Pass?      | ✅
| Documentation PR Link    | 
| Any Dependency Changes?  | ❌
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14464"></a>

### CODE REVIEW

File: packages/babel-types/src/definitions/jsx.ts [hunk 1]
```diff
@@ -42,7 +42,7 @@ defineType("JSXClosingElement", {
 });
 
 defineType("JSXElement", {
-  builder: ["openingElement", "closingElement", "children", "selfClosing"],
```
Comment (JLHwung) [inline packages/babel-types/src/definitions/jsx.ts:45]: I think this change should be behind the `BABEL_8_BREAKING` flag, because a different shape is returned from `t.JSXElement`.

For example, see
https://github.com/babel/babel/blob/2c7e9f79bb8c28c73ecc52c53fa1bc3a25c21b63/packages/babel-types/src/definitions/core.ts#L457-L462

Comment (wjw99830) [reply packages/babel-types/src/definitions/jsx.ts:45]: That's right. I'll fix it later.

**Comment by JLHwung** [comment]
Can you rebase on the latest main? The caniuse-lite CI error has been fixed.

**Review by nicolo-ribaudo — APPROVED** [review]
Thank you!
