### PR TITLE
Fix handling newline with TypeScript declare and abstract classes

### LINKED ISSUE #9325: @babel/parser(ts): class with preceding keywords on different line
## Bug Report

**Current Behavior**
Babel ignores new lines between class and keyword, typescript does not

https://github.com/Microsoft/TypeScript/blob/master/tests/cases/conformance/classes/classDeclarations/classAbstractKeyword/classAbstractSingleLineDecl.ts

**Input Code**
```ts
abstract
class B {}
```
```ts
declare
class B {}
```

**Expected behavior/code**
in body there should be 2 statements
- ExpressionStatement `abstract` and `declare` and 
- ClassDeclaration

**Babel Configuration (.babelrc, package.json, cli command)**

```js
  const babel = require('@babel/parser');
  const plugins: ParserPlugin[] = [
    'typescript',
    'objectRestSpread',
    'decorators-legacy',
    'classProperties',
    'asyncGenerators',
    'dynamicImport',
    'estree',
    'bigInt',
    'importMeta'
  ];
  if (jsx) {
    plugins.push('jsx');
  }

  return babel.parse(text, {
    sourceType: 'unambiguous',
    allowImportExportEverywhere: true,
    allowReturnOutsideFunction: true,
    ranges: true,
    plugins
  });
```

**Environment**
- Babel version(s):  7.2.3
- Node/npm version: 6-11
- OS: ----
- Monorepo: ---
- How you are using Babel: @babel/parser -> `parse`

### PR DESCRIPTION
**Pull request by existentialism**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #9325 
| Patch: Bug Fix?          | :+1:
| Major: Breaking Change?  | 
| Minor: New Feature?      | 
| Tests Added + Pass?      | Y/Y
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
Can you also add the check for type aliases? These should be two statements:

```js
type
Foo = string;
```

**Comment by existentialism** [comment]
@nicolo-ribaudo updated (was going to originally save it for a follow up pr)

File: packages/babel-parser/test/fixtures/typescript/module-namespace/module-new-line/input.js [hunk 1]
```diff
@@ -0,0 +1,2 @@
+module
+Foo = {}
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/test/fixtures/typescript/module-namespace/module-new-line/input.js]: Since `module Foo = {}` woldn't be valid anyway, maybe the test should be like this?

```js
module
Foo
{}
```

Also for interfaces and namespaces

Comment (existentialism) [reply packages/babel-parser/test/fixtures/typescript/module-namespace/module-new-line/input.js]: K
