### PR TITLE
Bug fix #6666

### LINKED ISSUE #6666: Existential return type annot in arrow function confused with `*=` operator
> Issue originally reported by @mroch in babel/babylon#772

### Input Code
```js
const x = ():*=>{}
```

### Babylon/Babel Configuration
flow plugin enabled

### Expected Behavior
Should be an arrow function with a `*` type annotation

### Current Behavior
"Unexpected token" pointing at the `*=`

### Your Environment
babylon7-7.0.0-beta.12 and babylon6-6.17.1: http://astexplorer.net/#/gist/a4d0ae75b6e1db95a394fd591f31a8c9/8cb4469554642dd1ce1bae05742af3146406d8af

Flow parses it correctly

### PR DESCRIPTION
**Pull request by rajzshkr**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            |  #6666 
| Patch: Bug Fix?          |
| Major: Breaking Change?  | No
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR         | 
| Any Dependency Changes?  |
| License                  | MIT

---
*Edit by @nicolo-ribaudo:*
Old PR: https://github.com/babel/babylon/pull/778

### CODE REVIEW

File: packages/babylon/src/tokenizer/index.js [hunk 1]
```diff
@@ -445,7 +446,7 @@ export default class Tokenizer extends LocationParser {
       type = tt.exponent;
     }
 
-    if (next === 61) {
+    if (next === 61 && !exprAllowed) {
```
Comment (xtuc) [inline packages/babylon/src/tokenizer/index.js]: (This has nothing to do with your PR)

The char codes are very difficult to read to me since I need to lookup in the table. It's sometimes inconsistent between int or hex representation.

I would like to PR to add a constant file where the char codes are stored and replace every occurrence in Babylon. What do you think?

Comment (rajzshkr) [reply packages/babylon/src/tokenizer/index.js]: This seems to be a good idea which will make the code readable. I'll make a separate PR.This seems to be a good idea which will make the code readable. I'll make a separate PR.

Comment (xtuc) [reply packages/babylon/src/tokenizer/index.js]: I would wait for more thoughts about since, especially @danez which is the main contrib of the parse.

Actually I already started locally. I can push a PR today, we can also both work on it.

**Comment by existentialism** [comment]
@rajzshkr thanks!

File: packages/babylon/src/tokenizer/index.js (hunk 1 above)
Comment (danez) [reply packages/babylon/src/tokenizer/index.js]: good idea
