### PR TITLE
fix: fix static private field shadowed by local variable

### LINKED ISSUE #12960: Symbol required for Private Static Field in check can be shadowed
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**
When accessing or checking for a private static field, the generated code references the class constructor, which could be shadowed.

https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=FAYwNghgzlAEAqBTKAXWBvYtZdqiKAliLAMQAesAvLAIy64C2iKAFgPYAmAFAJQa5sIdgDtUCZGhq0A3ILKVCI2ADcZsAPQaJ4wnCisIndgHdEnWEtgBzRCMQAnAudjDOiefJUA6Cuq06aHp4hsZmFla29k4oLm4e2AC-wIlAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.13.7&externalPlugins=

**Input Code**

```js

class Test {
  
  static #x = 1
  
  method() {
    const Test = 1;
    #x in v; // Test is shadowed in generated code
    
    v.#x; // Test is shadowed in generated code
  }
}
```

**Expected behavior**
Either a warning, or generated code avoids the issue.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

presets: 'stage-2'

**Environment**
babel playground

**Possible Solution**

Perhaps the generated code could capture a separate reference in a temp variable before it's shadowed.

### PR DESCRIPTION
**Pull request by colinaaa**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #12960 
| Patch: Bug Fix?          | 👍
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | 👍
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

use `innerBinding` created by #13429, and check whether the `classRef` for private fields equals the `innerBinding`.

currently throw an error, maybe we could generate correct code

Q: any idea how could we generate correct code? 
Should we rename the local variable?
Or rename the class?
Or capture a separate reference in a temp variable before it's shadowed?

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/13656"></a>

### CODE REVIEW

File: packages/babel-helper-create-class-features-plugin/src/fields.ts [hunk 1]
```diff
@@ -273,6 +274,13 @@ const privateNameHandlerSpec: Handler<PrivateNameState & Receiver> & Receiver =
             ? "classStaticPrivateMethodGet"
             : "classStaticPrivateFieldSpecGet";
 
+        const binding = member.scope.getBinding(classRef.name);
+        if (innerBinding && binding && !(binding.identifier === innerBinding)) {
```
Comment (nicolo-ribaudo) [inline packages/babel-helper-create-class-features-plugin/src/fields.ts:278]: Nit:
```suggestion
        if (innerBinding && binding && binding.identifier !== innerBinding) {
```

Also, `binding` should always be defined (because if there isn't a conflicting variable, it's `innerBinding`). It would be better to assert it, rather than checking it:
```js
if (innerBinding) {
  if (!binding) throw new Error("Internal Babel error: binding should be defined");
  if (binding.identifier !== innerBinding) {
    // ...
  }
}
```

File: packages/babel-helper-create-class-features-plugin/src/fields.ts [hunk 2]
```diff
@@ -273,6 +274,13 @@ const privateNameHandlerSpec: Handler<PrivateNameState & Receiver> & Receiver =
...
+          // the classRef has been shadowed
+          throw binding.path.buildCodeFrameError(
+            `Shadowing class ${classRef.name} with private property`,
+          );
```
Comment (nicolo-ribaudo) [inline packages/babel-helper-create-class-features-plugin/src/fields.ts:282]: > Q: any idea how could we generate correct code?
> Should we rename the local variable?

Yeah, I'd rename the local variable:
```js
path.scope.rename(classRef.name);
```

File: packages/babel-helper-create-class-features-plugin/src/fields.ts (hunk 1 above)
Comment (colinaaa) [reply packages/babel-helper-create-class-features-plugin/src/fields.ts:278]: Infect, `binding` could be undefined.

e.g: for a `ClassExpression`, `classRef` is generated by `path.scope.generateUidIdentifier("class");` and would be inserted **after** our transformation.

```js
const cls = class Test {
  static #x = 1
  method() {
    const Test = 1;
    return this.#x;
  }
}
```

Comment (nicolo-ribaudo) [reply packages/babel-helper-create-class-features-plugin/src/fields.ts:278]: Oh thanks, I didn't realize it

File: packages/babel-helper-create-class-features-plugin/src/fields.ts (hunk 2 above)
Comment (colinaaa) [reply packages/babel-helper-create-class-features-plugin/src/fields.ts]: Sure!

I renamed all the local variables that shadowing the `classRef` including those in parent scopes.

File: packages/babel-plugin-proposal-class-properties/test/fixtures/private-loose/static-shadow/exec.js [hunk 3]
```diff
@@ -0,0 +1,15 @@
...
+
+  static #x = 1
+
+  static method() {
+    const Test = 2;
+    const func = () => {
+      const Test = 3;
+      return this.#x;
+    }
+    return func();
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-proposal-class-properties/test/fixtures/private-loose/static-shadow/exec.js:11]: Can you also add some references to `Test`?
```suggestion
    const Test = 2;
    const func = () => {
      const Test = 3;
      return this.#x + Test;
    }
    return func() + Test;
```

**Review by nicolo-ribaudo — APPROVED** [review]
Thanks!

File: packages/babel-helper-create-class-features-plugin/src/fields.ts [hunk 4]
```diff
@@ -188,9 +189,26 @@ const privateNameVisitor = privateNameVisitorFactory<
...
 });
 
+// rename all bindings that shadows innerBinding
+function unshadow(
+  name: string,
+  scope: Scope,
+  innerBinding: t.Identifier | undefined,
+) {
+  const binding = scope.getBinding(name);
+  if (innerBinding && binding && innerBinding !== binding.identifier) {
```
Comment (JLHwung) [inline packages/babel-helper-create-class-features-plugin/src/fields.ts:199]: The `if` branch is an inlined version of `Scope#bindingIdentifierEquals`, guess we can just put
```js
while (!scope.bindingIdentifierEquals(name, innerBinding)) {
      scope.rename(name);
      scope = scope.parent;
    }
```
here?

Comment (colinaaa) [reply packages/babel-helper-create-class-features-plugin/src/fields.ts:199]: Sounds great! And all tests passed.

But I got a question: there are some cases that `scope.bindingIdentifier(name) === undefined` and `innerBinding !== undefined` which means `scope.bindingIdentifierEquals(name, innerBinding)` will always returns `false`. This will cause the while loop runs all the way alone to the top level scope and renaming all the variables.

The renaming and looping here are useless, and maybe cause performance problem.

So maybe we change it to:

```ts
  while (
    scope?.hasBinding(name) &&
    !scope.bindingIdentifierEquals(name, innerBinding)
  ) {
    scope.rename(name);
    scope = scope.parent;
  }
```

Comment (JLHwung) [reply packages/babel-helper-create-class-features-plugin/src/fields.ts]: > there are some cases that scope.bindingIdentifier(name) === undefined and innerBinding !== undefined

If the `scope` is the parent scope of the class where `innerBinding` is defined, then `scope.bindingIdentifier(classRef.name)` is surely `undefined`, unless defined otherwise. We could exit the loop after scope becomes the class scope.

**Review by JLHwung — APPROVED** [review]

File: packages/babel-helper-create-class-features-plugin/src/fields.ts [hunk 5]
```diff
@@ -188,9 +189,28 @@ const privateNameVisitor = privateNameVisitorFactory<
...
+  innerBinding: t.Identifier | undefined,
+) {
+  // in some cases, scope.getBinding(name) === undefined
+  // so we check hasBinding to avoid keeping looping
+  // see: https://github.com/babel/babel/pull/13656#discussion_r686030715
+  while (
+    scope?.hasBinding(name) &&
+    !scope.bindingIdentifierEquals(name, innerBinding)
+  ) {
+    scope.rename(name);
```
Comment (jridgewell) [inline packages/babel-helper-create-class-features-plugin/src/fields.ts:205]: Can renaming ever fail? I can't think of a case myself.

**Review by jridgewell — APPROVED** [review]

File: packages/babel-helper-create-class-features-plugin/src/fields.ts (hunk 5 above)
Comment (nicolo-ribaudo) [reply packages/babel-helper-create-class-features-plugin/src/fields.ts:205]: No, it always succeeds (but it might be observable since it sometimes changes the `.name` property of functions).
