### PR TITLE
fix destructuring of empty string

### LINKED ISSUE #13421: [Bug]: Destructuring empty string to array causes runtime error
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```js
let [a] = '';
console.log(a);
```

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

[repl](https://babeljs.io/repl/#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=DYUwLgBA2ghguhAvBA5CgUAYwPYDsDO2oAdMNgOYAUMAlEA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3&prettier=true&targets=Electron-1.8%252CNode-10.13&version=7.14.4&externalPlugins=)

#### current
VM104:58 Uncaught TypeError: _i.call is not a function
    at _iterableToArrayLimit (<anonymous>:47:18)
    at _slicedToArray (<anonymous>:6:5)
    at <anonymous>:69:11

#### expected
Console outputs undefined.

### Environment

  System:
    OS: macOS 11.3.1
  Binaries:
    Node: 14.16.0 - ~/.nvm/current/bin/node
    Yarn: 1.22.10 - ~/.nvm/current/bin/yarn
    npm: 6.14.11 - ~/.nvm/current/bin/npm
  Monorepos:
    Yarn Workspaces: 1.22.10
  npmPackages:
    @babel/core: ^7.13.8 => 7.14.3
    babel-loader: ^8.2.2 => 8.2.2
    eslint: ^7.10.0 => 7.27.0

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lala7573**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #13421 
| Patch: Bug Fix?          |  👍
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      |  👍
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/13444"></a>

### CODE REVIEW

File: packages/babel-plugin-transform-destructuring/test/fixtures/destructuring/empty-string/exec.js [hunk 1]
```diff
@@ -0,0 +1,3 @@
+let [a] = '';
+
+expect(undefined).toBe(a)
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-destructuring/test/fixtures/destructuring/empty-string/exec.js:3]: Nit:
```suggestion
expect(a).toBe(undefined)
```

Usually the "known" value should be put in the `toBe` clause, while the "value to be tested" in `expect()`.

File: packages/babel-helpers/src/helpers.js [hunk 2]
```diff
@@ -903,7 +903,7 @@ helpers.iterableToArrayLimit = helper("7.0.0-beta.0")`
     // _i = _iterator
     // _s = _step
 
-    var _i = arr && (typeof Symbol !== "undefined" && arr[Symbol.iterator] || arr["@@iterator"]);
+    var _i = arr == null? null: (typeof Symbol !== "undefined" && arr[Symbol.iterator] || arr["@@iterator"]);
```
Comment (jridgewell) [inline packages/babel-helpers/src/helpers.js:906]:
```suggestion
    var _i = arr == null ? null : (typeof Symbol !== "undefined" && arr[Symbol.iterator] || arr["@@iterator"]);
```

**Review by jridgewell — APPROVED** [review]

File: packages/babel-plugin-transform-destructuring/test/fixtures/destructuring/empty-string/exec.js (hunk 1 above)
Comment (lala7573) [reply packages/babel-plugin-transform-destructuring/test/fixtures/destructuring/empty-string/exec.js:3]: Ooops. I'll fix it.

**Comment by nicolo-ribaudo** [comment]
Can you run `OVERWRITE=true yarn jest` to update the failing test?

**Comment by nicolo-ribaudo** [comment]
It seems like there are some unrelated changes caused by outdated dependencies 🤔

If CI fails, try running `yarn` and then re-generate the fixtures again.

**Comment by lala7573** [comment]
@nicolo-ribaudo 
I removed node_modules and reinstalled using `yarn` and then re-generate the fixtures. And the ci tests seem almost done. 
Is there anything that I should have to do with this pr? Please tell me!!
Thank you for your kind guides and feedbacks.

**Review by fedeci — APPROVED** [review]

**Comment by nicolo-ribaudo** [comment]
Thanks!
