### PR TITLE
Don't resolve shadowed `arguments` variables from functions

### LINKED ISSUE #13990: [Bug]: Function's Implicit Arguments Binding Fail
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
var arguments = [1, 2, 3];
var arr = () => arguments[0];
function foo(n) {
    var f = () => arguments[0] + n; // foo's implicit arguments binding. arguments[0] is n
    return f();
}
console.log(foo(3)); // 6
```
Here is the [REPL](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=false&spec=false&loose=false&code_lz=AQNwhgTskOYK4FsCmA7ALgZ2AXmAbQEYAaYAJhIGYBdAbgChRJoIpcAKAShwD5n5l0GPAAZaDBpAicawAPSzgBccABmcFAGM0ASwD2KVbt1sUXAN4NgjKCpzBOPPolSYRVYAGpgKGfMO6AcixtBAAHABttDW00JwFMYAAjbRQAExSYADo4lyFRYG0sFEtgCCQ0OAgDFWkGAF9lDX0MXXCkTPDdGDYVIzYKDg5fBQA2IA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=unambiguous&lineWrap=true&presets=env%2Cflow&prettier=false&targets=&version=7.16.4&externalPlugins=&assumptions=%7B%7D)

### Configuration file name

babel.config.js

### Configuration

```js
module.exports = function (api) {
  api.cache(true);
  const sourceType= "unambiguous";
  const presets = [
      ["@babel/preset-env", { "modules": false}]
  ];
  const plugins = [  ];

  return {
    sourceType,
    presets,
    plugins
  };
}
```

### Current behavior and Expected behavior
The output run by node transformed by babel is 4, but it should be 6.
The foo's implicit arguments binding. arguments[0] should be n.

### Environment

- babel 
- - ├── @babel/cli@7.16.0
- - ├── @babel/preset-env@7.16.0
- Node: [v16.11.1]
- npm version [8.0.0]
- os [ubuntu 20.04]

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by The-x-Theorist**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #13990 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

Function's implicit argument binding now won't fail because the `arguments` identifier in function will be renamed differently than the `arguments` identifier in any another scope.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14036"></a>

### CODE REVIEW

File: packages/babel-traverse/test/fixtures/conversion/implicit-var-arguments/output.js [hunk 1]
```diff
@@ -0,0 +1,20 @@
+var _arguments = typeof arguments === "undefined" ? void 0 : arguments;
+
+var arguments = [1, 2, 3];
+
+var arr = function arr() {
+  return _arguments[0];
```
Comment (nicolo-ribaudo) [inline packages/babel-traverse/test/fixtures/conversion/implicit-var-arguments/output.js:6]: This looks wrong, it should still be `arguments[0]`.

File: packages/babel-traverse/src/path/conversion.ts [hunk 2]
```diff
@@ -635,7 +635,7 @@ const getScopeInformationVisitor = mergeVisitors<{
 
       let curr = child.scope;
       do {
-        if (curr.hasOwnBinding("arguments")) {
+        if (curr.hasOwnBinding("arguments") && !curr.hasBinding("arguments")) {
```
Comment (nicolo-ribaudo) [inline packages/babel-traverse/src/path/conversion.ts:638]: I think that rather than this, the proper fix would be to skip non-arrow functions in `scope.rename` if we are renaming `"arguments"`.

File: packages/babel-traverse/test/fixtures/conversion/implicit-var-arguments/output.js (hunk 1 above)
Comment (The-x-Theorist) [reply packages/babel-traverse/test/fixtures/conversion/implicit-var-arguments/output.js:6]: Yeah, It's I will fix it.

File: packages/babel-traverse/src/path/conversion.ts (hunk 2 above)
Comment (The-x-Theorist) [reply packages/babel-traverse/src/path/conversion.ts:638]: Okay, I will do the same.

**Comment by nicolo-ribaudo** [comment]
The fix should be _inside_ the renamer. You can edit this code:
https://github.com/babel/babel/blob/39080492f46909153217939ff08d9bf4b03ce2a5/packages/babel-traverse/src/scope/lib/renamer.ts#L21-L26

to also skip if `state.oldName === "arguments" && path.isFunction() && !path.isArrowFunctionExpression()`.

**Comment by nicolo-ribaudo** [comment]
Or even better, if it works, in `getBinding` (so that `bindingIdentifierEquals` then returns false):
https://github.com/babel/babel/blob/39080492f46909153217939ff08d9bf4b03ce2a5/packages/babel-traverse/src/scope/index.ts#L1116-L1144

If `!binding && name === "arguments" && scope.path.isFunction() && !scope.path.isArrowFunctionExpression()`, we can break the loop and return `undefined`. This is because in this code:
```js
var arguments = [];
function f() {
  return arguments;
}
```
the `return arguments` does _not_ refer to `var arguments`.

**Comment by The-x-Theorist** [comment]
@nicolo-ribaudo Okay, I got I will make the changes just as you described in the next commit.

File: packages/babel-traverse/test/fixtures/conversion/implicit-var-arguments/exec.js [hunk 3]
```diff
@@ -0,0 +1,11 @@
+var arguments = [1, 2, 3];
+var arr = () => arguments[0];
+
+arr(); // 1
```
Comment (nicolo-ribaudo) [inline packages/babel-traverse/test/fixtures/conversion/implicit-var-arguments/exec.js:4]: Can you add an explicit `expect` here rather than just a comment?

**Review by nicolo-ribaudo — APPROVED** [review]
Thanks!

File: packages/babel-traverse/test/fixtures/conversion/implicit-var-arguments/exec.js (hunk 3 above)
Comment (The-x-Theorist) [reply packages/babel-traverse/test/fixtures/conversion/implicit-var-arguments/exec.js:4]: Yeah, I can do that.

File: packages/babel-traverse/test/fixtures/conversion/implicit-var-arguments/options.json [hunk 4]
```diff
@@ -0,0 +1,4 @@
+{
+  "sourceType": "unambiguous",
+  "presets": ["env"]
```
Comment (nicolo-ribaudo) [inline packages/babel-traverse/test/fixtures/conversion/implicit-var-arguments/options.json:3]: The Babel 8 tests are failing because you didn't specify any target here. Could you move this test in the arrow functions plugin, and enable the plugin instead of the preset?
Also, please specify `"sourceType": "script"` since this is specific to loose mode.

Comment (The-x-Theorist) [reply packages/babel-traverse/test/fixtures/conversion/implicit-var-arguments/options.json:3]: Okay, I can do that.

Comment (The-x-Theorist) [reply packages/babel-traverse/test/fixtures/conversion/implicit-var-arguments/options.json]: I changed the same as you said.

File: packages/babel-plugin-transform-arrow-functions/test/fixtures/arrow-functions/arguments-global-var/output.js [hunk 5]
```diff
@@ -1,7 +1,7 @@
 var _arguments2 = 1;
 
 function fn() {
-  var _arguments = _arguments2;
+  var _arguments = arguments;
```
Comment (lightmare) [inline packages/babel-plugin-transform-arrow-functions/test/fixtures/arrow-functions/arguments-global-var/output.js:4]: Note for self and others: this is correct, the test was previously broken — `fn` should not see the outer `arguments`, because it was not an arrow function in input.js

**Review by nicolo-ribaudo — APPROVED** [review]

**Review by existentialism — APPROVED** [review]
