### PR TITLE
Duplicate `__proto__` key should be allowed in object patterns

### LINKED ISSUE #6705: should allow duplicate __proto__ keys in patterns
> Issue originally reported by @babel-bot in babel/babylon#306

Original issue submitted by @gsathya in https://github.com/babel/babel/issues/5145

### Input Code

```js
result = { __proto__: x, __proto__: y } = value;
```

### Babel Configuration (.babelrc, package.json, cli command)

presets - latest

### Expected Behavior
No error

### Current Behavior
Error: `Redefinition of __proto__ property`

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  
| node             | 
| npm              | 
| Operating System |

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #6705 
| Patch: Bug Fix?          | Yes
| Tests Added + Pass?      | Yes
| License                  | MIT

This PR can be reviewed commit by commit.

The first commit is to replace `refShorthandDefaultPos` argument by a new general struct: `refExpressionErrors`. By doing so we rebrand the `refShorthandDefaultPos` into a context variable within the expression scope.

This paves the way to fix the duplicate `__proto__` tracking issue: In the second commit we add a new property `doubleProto` to the `refExpressionErrors` and reset if we are sure the parsed ambiguous object patterns is indeed a LHS.

I have definitely borrowed a lot from acorn's design but carefully crafted `parseMaybeAssign` to avoid regressions we have solved before.

### CODE REVIEW

File: packages/babel-parser/src/parser/util.js [hunk 1]
```diff
@@ -268,4 +268,26 @@ export default class UtilParser extends Tokenizer {
...
+
+  checkExpressionErrors(
+    refExpressionErrors: ?ExpressionErrors,
+    andThrow: boolean,
+  ) {
+    if (!refExpressionErrors) return false;
+    const { shorthandAssign } = refExpressionErrors;
+    if (!andThrow) return shorthandAssign >= 0;
+    if (shorthandAssign >= 0) {
+      this.unexpected(shorthandAssign);
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/src/parser/util.js]: (In a separate PR)
Probably this error would be easily recoverable.

Comment (JLHwung) [reply packages/babel-parser/src/parser/util.js]: Yeah, I try to preserve the error output of shorthand assign error so it's indeed a refactor.
