### PR TITLE
Fix generator missing parens around an arrow returning function type

### LINKED ISSUE #10517: Parsing and generating flow type moves parentheses
## Bug Report

**Input Code**

`packages/babel-generator/test/fixtures/types/ArrowFunctionExpression2/input.js`:
```js
const pair = <T>(a: T): (T => T[]) => b => [a, b]
```
`packages/babel-generator/test/fixtures/types/ArrowFunctionExpression2/options.json`:
```json
{ "plugins": ["flow"] }
```

**Expected behavior/code**
The output should be the same as the input, with the parentheses around `(T => T[])`.

**Current Behavior**
Output code is:
```js
const pair = <T>(a: T): (T) => T[] => b => [a, b];
```
The parentheses have moved from `(T => T[])` to `(T) => T[]`.
Flow now gives a parse error on the output, where it worked for the original.

**Environment**
- Babel version(s):  master
- Node/npm version: Node 10/npm 6
- OS: Linux Mint 18.1
- Monorepo: yes
- How you are using Babel: ` env TEST_ONLY=babel-generator make test`

### PR DESCRIPTION
**Pull request by existentialism**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #10517
| Patch: Bug Fix?          | Y
| Major: Breaking Change?  | N
| Minor: New Feature?      | N
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

File: packages/babel-generator/src/node/parentheses.js [hunk 1]
```diff
@@ -35,14 +35,21 @@ export function NullableTypeAnnotation(node: Object, parent: Object): boolean {
...
     // (() => A) | (() => B)
     t.isUnionTypeAnnotation(parent) ||
     // (() => A) & (() => B)
     t.isIntersectionTypeAnnotation(parent) ||
     // (() => A)[]
-    t.isArrayTypeAnnotation(parent)
+    t.isArrayTypeAnnotation(parent) ||
+    // <T>(A: T): (T => T[]) => B => [A, B]
+    (t.isTypeAnnotation(parent) &&
+      t.isArrowFunctionExpression(printStack[printStack.length - 3]))
```
Comment (Jessidhia) [inline packages/babel-generator/src/node/parentheses.js]: What does `printStack[printStack.length - 3]`...... mean?

I assume this is related to Flow emit; the example syntax looks like invalid TypeScript.

Also, would the structure be the same if `<T>(A: T): // ...` (declaration signature) was written as `<T>(A: T) => /...` (expression signature)?

File: packages/babel-generator/test/fixtures/flow/arrow-functions/output.js [hunk 2]
```diff
@@ -10,4 +10,6 @@ const bar5 = (x): string => {};
 
 const bar6 = (x: number) => {};
 
-const bar7 = <T>(x) => {};
\ No newline at end of file
+const bar7 = <T>(x) => {};
+
+const bar8 = <T>(x: T): ((T) => T[]) => y => [x, y];
```
Comment (Jessidhia) [inline packages/babel-generator/test/fixtures/flow/arrow-functions/output.js]: hmm, I see. Maybe the correct output should be the one in the code comment.

File: packages/babel-generator/src/node/parentheses.js (hunk 1 above)
Comment (existentialism) [reply packages/babel-generator/src/node/parentheses.js]: Yeah, it's Flow emit related. I can add a comment, the printStack bit is just checking the grandparent (since these are only passed node, its parent, and the whole stack).

File: packages/babel-generator/test/fixtures/flow/arrow-functions/output.js (hunk 2 above)
Comment (existentialism) [reply packages/babel-generator/test/fixtures/flow/arrow-functions/output.js]: I was look into dropping the parens around `(T)` later, initial experiment looked like it touched a bunch of other fixtures.
