### PR TITLE
fix: Preserve computed key evaluation order in nested object rest (#17274)

### LINKED ISSUE #17274: Incorrect computed key evaluation order when transpiling nested object rest
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

[REPL](https://babel.dev/repl#?browsers=chrome%2080&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAGzgcwBRgJSIN4BQiiECAznMgKYB0qmOA3EYgE5VQitIBEAHjwIBfAgVJgyUfIgDa9DAAZsAXQBc0uegwBGFer4AaWfIBMexAE8jNG-0mIhRzZgDM5gF4PEAXml91eIj--EIOQoxAA&forceAllTransforms=false&modules=umd&shippedProposals=false&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.27.0&externalPlugins=%40babel%2Fplugin-transform-object-rest-spread%407.25.9&assumptions=%7B%7D)

```js
function log(n) {
  console.log(n);
  return "x"
}

const { [log(0)]: { [log(1)]: x, [log(2)]: y, ...rest }, [log(3)]: z } = { x: { x: {} }};
```

### Configuration file name

_No response_

### Configuration

```json
{
  "plugins": ["@babel/plugin-transform-object-rest-spread"]
}
```

### Current and expected behavior

Current: It logs `1, 2, 0, 3`

Expected: It should log `0, 1, 2, 3`, the computed keys are evaluated from left to right.

### Environment

REPL

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kadhirash**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #17274
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  | No
| License                  | MIT

## Summary
When destructuring with nested object rest and computed keys, the computed key expressions must be evaluated in source order (left-to-right), but they were being evaluated in the wrong order.

## Example
```javascript
function log(n) {
  console.log(n);
  return "x"
}

const { [log(0)]: { [log(1)]: x, [log(2)]: y, ...rest }, [log(3)]: z } = { x: { x: {} }};
```

**Before this fix:** Logs `1, 2, 0, 3` -> incorrect 
**After this fix:** Logs `0, 1, 2, 3`  -> correct

## Changes
- Added a global hoisting pass in the `VariableDeclarator` visitor that extracts all impure computed keys in source order
- Hoisting occurs after RHS (Right Hand Side) evaluation but before destructuring begins
- Prevents duplicate hoisting with flag system (`computedKeysAlreadyHoisted` and `_keyAlreadyHoisted`)
- Added detailed comments in the code explaining the fix
- Added regression test: `test/fixtures/regression/gh-17274/`
- Updated one existing test output to reflect correct evaluation order

### CODE REVIEW

**Comment by kadhirash** [comment]
Hey @JLHwung, are you or someone else able to take a look at this PR or give feedback? Thank you!

File: packages/babel-plugin-transform-object-rest-spread/src/index.ts [hunk 1]
```diff
@@ -426,6 +506,79 @@ export default declare((api, opts: Options) => {
...
+           * This happens after the right-hand side (obj) is stored, but before destructuring starts.
+           *
+           * Transform:
+           *   const { [log(0)]: { [log(1)]: x, ...rest }, [log(2)]: y } = obj
+           * Into:
+           *   const _obj = obj,           // Store right-hand side first
+           *         _key1 = log(0),       // Then evaluate keys in order
+           *         _key2 = log(1),
+           *         _key3 = log(2),
+           *         { [_key1]: { [_key2]: x, ...rest }, [_key3]: y } = _obj  // Then destructure
```
Comment (JLHwung) [inline packages/babel-plugin-transform-object-rest-spread/src/index.ts]: Thank you for detailed comments. They really help the review process.

This approach memoises computed keys, such as `_key1 = log(0)`. However, it can not handle the situation where the binding initializers could have side effects. For example:

```js
const { [log(0)]: x = log(1), [log(2)]: y, ...rest } = obj;
```

If we only hoist the computed keys `log(0)` and `log(2)`, then `log(1)` will be evaluated _after_ `log(2)`:

```js
const _key1 = log(0),
_key2 = log(2),
{ [_key1]: x = log(1), [_key2]: y } = obj;
```
 Of course we may also hoist initializers, but then it will unnecessarily bloat the output. A common trick is to perform the memoisation inline:

```js
var _key1, _key2;
const { [_key1 = log(0)]: x = log(1), [_key2 = log(2)]: y } = obj;
```

With the inline memoisation, one can check whether a computed key has been memoised by checking if `key` is an assignment expression and `scope.hasUid(key.left.name)` is `true`. We have already done something similar before:

https://github.com/babel/babel/blob/10833e08a35ee57cbaf9ba80389934c026fe7213/packages/babel-helper-create-class-features-plugin/src/decorators.ts#L335

File: packages/babel-plugin-transform-object-rest-spread/test/fixtures/object-rest/object-ref-computed/output.js [hunk 2]
```diff
@@ -36,15 +36,15 @@ var _$ = {
...
     },
-    [_key2]: {
+    [_key3]: {
       z
     }
   } = _$,
-  rest_y = babelHelpers.objectWithoutProperties(_$[_key3], ["y"]),
-  rest_z = babelHelpers.objectWithoutProperties(_$[_key2], ["z"]);
+  rest_y = babelHelpers.objectWithoutProperties(_$[_key2], ["y"]),
+  rest_z = babelHelpers.objectWithoutProperties(_$[_key3], ["z"]);
```
Comment (JLHwung) [inline packages/babel-plugin-transform-object-rest-spread/test/fixtures/object-rest/object-ref-computed/output.js:45]: This change looks good to me. Could you update the `packages/babel-plugin-transform-object-rest-spread/test/fixtures/object-rest/object-ref-computed-exec/exec.js` such that the previous test failed on main but passed in this PR?

This test can be also merged with the `object-ref-computed` test: Just move `exec.js` within the `object-ref-computed` folder.

In general we will also sync the content of `input.js` and `exec.js`.

File: packages/babel-plugin-transform-object-rest-spread/src/index.ts (hunk 1 above)
Comment (kadhirash) [reply packages/babel-plugin-transform-object-rest-spread/src/index.ts]: Thank you for the detailed feedback! I've updated the implementation to use inline memoization as you suggested:
Changes made:

- Variables declared upfront: `var _key, _key2;`
- Inline assignments in computed keys: `[_key = log(0)]`
- Identifier extraction in exclusion arrays:` [_key].map(toPropertyKey) (not [_key = log(0)])`
- Identifier extraction in member expressions: `_[_key] (not _[_key = key++])`

This correctly preserves evaluation order even with default values, as the assignment expressions are evaluated inline left-to-right.

All 85 tests pass. The approach follows the `memoiseComputedKey` pattern from `misc.ts` that you referenced!

File: packages/babel-plugin-transform-object-rest-spread/test/fixtures/object-rest/object-ref-computed/output.js (hunk 2 above)
Comment (kadhirash) [reply packages/babel-plugin-transform-object-rest-spread/test/fixtures/object-rest/object-ref-computed/output.js:45]: I've merged the `object-ref-computed-exec` test into the `object-ref-computed` folder. The `input.js` and `exec.js` already have the same content, and all 84 tests are passing!

File: packages/babel-plugin-transform-object-rest-spread/test/fixtures/object-rest/object-ref-computed/output.js [hunk 3]
```diff
@@ -33,18 +33,16 @@ var _$ = {
       z: 3
     }
   },
-  _key2 = ++key,
-  _key3 = ++key,
   {
-    [_key3]: {
+    [_key2 = ++key]: {
```
Comment (JLHwung) [inline packages/babel-plugin-transform-object-rest-spread/test/fixtures/object-rest/object-ref-computed/output.js:37]: This is a bugfix. Previously in the output, the `{ y, ...rest_y }` was actually destructured from the value of `3: { y: 2, z: 3 }` while it should have been destrctured from the value of `2: { y: 2, z: 3 }`. The `exec.js` test is merely passing because those two values happens to share the same shape and values. Could you update the `exec.js` (and `input.js` as well) such that they have different values? For example one can use `3: { y: 4, z: 6 }` so the assertions will pass only if they are destructured from the correct property.

Comment (kadhirash) [reply packages/babel-plugin-transform-object-rest-spread/test/fixtures/object-rest/object-ref-computed/output.js:37]: Updated! Changed key 3 to { y: 4, z: 6 } with matching assertions. The test should now properly pass with the fix

File: packages/babel-plugin-transform-object-rest-spread/src/index.ts [hunk 4]
```diff
@@ -157,24 +176,68 @@ export default declare((api, opts: Options) => {
     return { keys, allPrimitives, hasTemplateLiteral };
   }
 
-  // replaces impure computed keys with new identifiers
-  // and returns variable declarators of these new identifiers
+  /**
+   * Replaces computed keys that have side effects with temporary variables.
+   *
+   * Example: { [foo()]: x } becomes { [_temp]: x } with declaration: const _temp = foo()
```
Comment (JLHwung) [inline packages/babel-plugin-transform-object-rest-spread/src/index.ts]: Nit: this comment should be updated as well now that we use inline memoisation.

File: packages/babel-plugin-transform-object-rest-spread/src/index.ts [hunk 5]
```diff
@@ -157,24 +176,68 @@ export default declare((api, opts: Options) => {
...
-      if (propPath.node.computed && !key.isPure()) {
-        const name = scope.generateUidBasedOnNode(key.node);
-        const declarator = t.variableDeclarator(t.identifier(name), key.node);
-        impureComputedPropertyDeclarators.push(declarator);
-        key.replaceWith(t.identifier(name));
+      const keyExpression = property.get("key") as NodePath<t.Expression>;
+
+      // Skip if already processed by global computed key hoisting pass
+      // (This prevents creating duplicate temp variables like _a2 = _a)
+      if ((property.node as any)._keyAlreadyHoisted) {
```
Comment (JLHwung) [inline packages/babel-plugin-transform-object-rest-spread/src/index.ts]: Is this check required now that we check uid identifiers? In general we should avoid mutating the AST shape with internal flags.

File: packages/babel-plugin-transform-object-rest-spread/src/index.ts [hunk 6]
```diff
@@ -426,6 +546,91 @@ export default declare((api, opts: Options) => {
...
+           * Transform:
+           *   const { [log(0)]: { [log(1)]: x, ...rest }, [log(2)]: y } = obj
+           * Into:
+           *   var _log, _log2, _log3;
+           *   const { [_log = log(0)]: { [_log2 = log(1)]: x, ...rest }, [_log3 = log(2)]: y } = obj
+           *
+           * This preserves correct evaluation order even with default values.
+           */
+
+          // Only do this once per variable declaration (even if multiple rest elements exist)
```
Comment (JLHwung) [inline packages/babel-plugin-transform-object-rest-spread/src/index.ts]: Can we avoid this state if we move the following computed key memoisation out of the `visitObjectRestElements` callback?

File: packages/babel-plugin-transform-object-rest-spread/src/index.ts (hunk 4 above)
Comment (kadhirash) [reply packages/babel-plugin-transform-object-rest-spread/src/index.ts]: Updated comment

File: packages/babel-plugin-transform-object-rest-spread/src/index.ts (hunk 5 above)
Comment (kadhirash) [reply packages/babel-plugin-transform-object-rest-spread/src/index.ts]: Good catch, yeah the flag is redundant since we already check for UID identifiers. I've removed the `_keyAlreadyHoisted` flag and now it relies on the UID check. Much cleaner without the AST mutation

File: packages/babel-plugin-transform-object-rest-spread/src/index.ts (hunk 6 above)
Comment (kadhirash) [reply packages/babel-plugin-transform-object-rest-spread/src/index.ts]: Good idea. I've moved the computed key memoization outside the `visitObjectRestElements` callback. Now it runs once upfront before the callback, eliminating the need for the `alreadyMemoisedComputedKeys `state flag

**Comment by JLHwung** [comment]
Oh the CI error seems related, it seems that we are memoising computed properties even though it is not followed by a rest element.

**Comment by kadhirash** [comment]
@JLHwung yep, I noticed that in the CI error log and should have a fix for it. It didn't show up when running locally

**Comment by kadhirash** [comment]
@JLHwung should be good to merge now!

**Comment by JLHwung** [comment]
> @JLHwung should be good to merge now!

Thank you. For larger change we have a two-approval policy. Let's wait for feedback from other reviewers.

**Comment by kadhirash** [comment]
Hey @nicolo-ribaudo, @liuxingbaoyu! Are you able to take a look by chance?

File: packages/babel-plugin-transform-object-rest-spread/src/index.ts [hunk 7]
```diff
@@ -157,24 +176,62 @@ export default declare((api, opts: Options) => {
...
+        while (currentScope) {
+          if (currentScope.hasUid(identName)) {
+            isUid = true;
+            break;
+          }
+          currentScope = currentScope.parent;
+        }
+        if (isUid) {
+          continue;
+        }
```
Comment (liuxingbaoyu) [inline packages/babel-plugin-transform-object-rest-spread/src/index.ts]: `hasUid` has already found the parent scopes, so let's call it only once.

File: packages/babel-plugin-transform-object-rest-spread/src/index.ts [hunk 8]
```diff
@@ -113,15 +113,24 @@ export default declare((api, opts: Options) => {
...
+  ) {
     // RestElement has been removed in createObjectRest
-    const props = node.properties as t.ObjectProperty[];
+    // If we have a NodePath, get the current nodes (which reflect any transformations)
+    const isPath = "get" in pattern;
+    const propsList: t.ObjectProperty[] = isPath
+      ? pattern
+          .get("properties")
+          .map((p: NodePath) => p.node as t.ObjectProperty)
+      : (pattern.properties as t.ObjectProperty[]);
```
Comment (liuxingbaoyu) [inline packages/babel-plugin-transform-object-rest-spread/src/index.ts]: This function seems to be referenced only once and passed in `NodePath`?

File: packages/babel-plugin-transform-object-rest-spread/src/index.ts (hunk 7 above)
Comment (kadhirash) [reply packages/babel-plugin-transform-object-rest-spread/src/index.ts]: Good catch! You're right, I've simplified it to just call `scope.hasUid(identName)` directly

File: packages/babel-plugin-transform-object-rest-spread/src/index.ts (hunk 8 above)
Comment (kadhirash) [reply packages/babel-plugin-transform-object-rest-spread/src/index.ts]: Yeah this function is only called once at line 332 and always with a NodePath. 

I've updated the function signature to only accept `NodePath<t.ObjectPattern>` and removed the extra type check and branching logic

File: packages/babel-plugin-transform-object-rest-spread/src/index.ts [hunk 9]
```diff
@@ -113,15 +113,18 @@ export default declare((api, opts: Options) => {
   // from ast of {a: "foo", b, 3: "bar", [++x]: "baz"}
   // `allPrimitives: false` doesn't necessarily mean that there is a non-primitive, but just
   // that we are not sure.
-  function extractNormalizedKeys(node: t.ObjectPattern) {
+  function extractNormalizedKeys(pattern: NodePath<t.ObjectPattern>) {
     // RestElement has been removed in createObjectRest
-    const props = node.properties as t.ObjectProperty[];
+    const propsList: t.ObjectProperty[] = pattern
+      .get("properties")
+      .map((p: NodePath) => p.node as t.ObjectProperty);
```
Comment (liuxingbaoyu) [inline packages/babel-plugin-transform-object-rest-spread/src/index.ts:120]:
```suggestion
    const propsList = pattern.node.properties as t.ObjectProperty[];
```

**Comment by kadhirash** [comment]
@liyuxingbao I see hmm what do you suggest I do? It happened when updating the branch it included the other commits that came before this 

Edit: I ended up rebasing and fixing the commits!

**Comment by JLHwung** [comment]
The rebased commits look good to me, merging.
