### PR TITLE
Fix Flow.

### LINKED ISSUE #3064: Flow issues
A bunch of Babel files have a `@flow` annotation, but they don't actually successfully typecheck. Installing `gulp-babel` then running `flow` 0.18.1 shows 371 errors (see https://gist.github.com/Daniel15/d2fdd07df075f5e5353b for a full list).

Can we just remove the `@flow` annotations for now until these are resolved?

### PR DESCRIPTION
**Pull request by Daniel15**
Removed `@flow` annotation from files that don't actually pass Flow check at the moment. These will be added back file by file once the files are properly converted to use Flow.

Closes #3064

### CODE REVIEW

File: lib/types.js [hunk 1]
```diff
@@ -51,7 +51,7 @@ declare class BabelNodeAssignmentExpression extends BabelNode {
 
 declare class BabelNodeBinaryExpression extends BabelNode {
   type: "BinaryExpression";
-  operator: string;
+  operator: "+" | "-" | "/" | "%" | "*" | "**" | "&" | "|" | ">>" | ">>>" | "<<" | "^" | "==" | "===" | "!=" | "!==" | "in" | "instanceof" | ">" | "<" | ">=" | "<=";
```
Comment (Daniel15) [inline lib/types.js]: I ran `scripts/generate-interfaces.js` and it changed all this stuff, I guess that script was updated but not ran recently. :stuck_out_tongue:
