### PR TITLE
Fix moving comments of removed nodes

### LINKED ISSUE #9916: @babel/plugin-transform-typescript strips vital JSDoc @typedef comments
## Bug Report

<br>

**EDIT:** See my comment https://github.com/babel/babel/issues/9916#issuecomment-489404010 below, there is a strange inconsistency depending on the location of `import` statements.

<br>

Running Babel with nothing but @babel/plugin-transform-typescript removes all but the very first of many JSDoc `@typedef` comments.

Those comments are for (and just above) Typescript type definitions (export type, export interface). When the Typescript types are stripped, so are the JSDoc comments. When I run `jsdoc3` to generate the HTML API docs this tool too runs Babel and this plugin in order to be able to parse the file. Obviously, the removal of the JSDoc is counterproductive especially in this use case.

**Environment**
- Babel version(s): 7.4.4
- Node/npm version: 11.14
- jsdoc 3.5.5
- OS: Linux

- How you are using Babel: jsdoc3, config (jsdoc.json, babel section):

```
"babel": {
        "extensions": ["js","ts","jsx","tsx"],
        "presets": ["@babel/preset-typescript"],
        "plugins": [],
        "babelrc": false
    },
```

## Example

Here is an excerpt of the beginning of a file with many TS type definitions and there accompanying JSDoc comments.

```js
/**
 * This defines the creation status string constants for files
 * @global
 * @typedef {("new"|"exists")} FileCreationStatus
 */
export type FileCreationStatus = typeof CREATION_STATUS[keyof typeof CREATION_STATUS];

/**
 * @global
 * @typedef {Object} FileCreation
 * @property {SHA256Hash} hash - The SHA-256 hash of the contents of a versioned ONE object
 * @property {FileCreationStatus} status - A string constant showing whether the file
 * already existed or if it had to be created.
 */
export interface FileCreation {
    hash: SHA256Hash;
    status: FileCreationStatus;
}

/**
 * This defines the creation status string constants for objects.
 * @global
 * @typedef {FileCreationStatus} ObjectCreationStatus
 */
export type ObjectCreationStatus = FileCreationStatus;
```
After the transformation only this is left of these comments:

```js
/**
 * This defines the creation status string constants for files
 * @global
 * @typedef {("new"|"exists")} FileCreationStatus
 */
export type FileCreationStatus = typeof CREATION_STATUS[keyof typeof CREATION_STATUS];
```

Lots and lots of comments erased while there were nothing but Typescript type definitions encountered by the parser. Only when there was actual JS code again did the comment removal stop.

## Proposed solution

Don't delete any JSDoc (or any) comments. Comment removal should be left to the boolean "comment" Babel configuration property and whatever Babel code is following that instruction. If it is not set to `true` no comments should be removed, especially not JSDoc `@typedef` ones.

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #9916
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15427"></a>

### CODE REVIEW

File: packages/babel-plugin-proposal-class-properties/test/fixtures/compile-to-class/preserve-comments/output.js [hunk 1]
```diff
@@ -3,8 +3,8 @@ class C {
     /* before a */
     babelHelpers.defineProperty(this, "a", void 0);
   }
+  /* after a */
+  /* before b */
   /* after b */
 }
-/* after a */
-/* before b */
 babelHelpers.defineProperty(C, "b", void 0);
```
Comment (JLHwung) [inline packages/babel-plugin-proposal-class-properties/test/fixtures/compile-to-class/preserve-comments/output.js:10]: IMO in this case the old behaviour is more preferable, `/* before b */` is more likely to be the JSDoc comment of class property `b`.

Comment (nicolo-ribaudo) [reply packages/babel-plugin-proposal-class-properties/test/fixtures/compile-to-class/preserve-comments/output.js:10]: What do you think should be the priority? When we remove node B from ABC, we first try to attach B's trailing comments as leading comments of C, and then fallback to trailing comments of A?

Comment (nicolo-ribaudo) [reply packages/babel-plugin-proposal-class-properties/test/fixtures/compile-to-class/preserve-comments/output.js:10]: Ok actually, the priority I implemented is already like that.

What's happening here is that when we have this code:
```js
class C {
  constructor() {}
  /* before b */
  static b;
  /* after b */
}
```
we call `path.remove()` on `static b`, and thus its comments are attached to `constructor() {}` which is the only available sibling node.

I'm confused by the previous output, because `after b` was attached to the constructor but `before b` wasn't :thinking:

Comment (nicolo-ribaudo) [reply packages/babel-plugin-proposal-class-properties/test/fixtures/compile-to-class/preserve-comments/output.js]: I pushed a solution, I'm not sure I like it. The behavior I was confused about was because of the helpers for class fields to inherit comments that we recently introduced.

**Comment by ZeeshanTamboli** [comment]
I believe this fix is causing an issue for us at @MUI. We transpile our TypeScript demos to formatted Javascript using babel. In the output JS files, the comments of the source Typescript files for a type also gets added. 

**TS file**: (CustomColor.tsx)
```ts
// Update the Button's color prop options
declare module '@mui/material/Button' {
  interface ButtonPropsColorOverrides {
    neutral: true;
  }
}

export default function CustomColor() {
  return (
    <ThemeProvider theme={theme}>
      <Button color="neutral" variant="contained">
        neutral
      </Button>
    </ThemeProvider>
  );
}
```

**Output JS file**:
```diff
--- a/docs/data/material/customization/palette/CustomColor.js
+++ b/docs/data/material/customization/palette/CustomColor.js
@@ -11,6 +11,8 @@ const theme = createTheme({
   },
 });

+// Update the Button's color prop options
+
 export default function CustomColor() {
   return (
     <ThemeProvider theme={theme}>
```

This is a blocker for us to update babel to version `7.21.4`. PR - https://github.com/mui/material-ui/pull/36815

**Comment by mirabilos** [comment]
Is it possible that this is causing weird artefacts with top-level file-initial comments?

See https://github.com/danvk/dygraphs/compare/a6fa54f81ccd7558ac5cd64802fae6ad2bffe56c...c81444545809a60346a61503515938719d56568d#diff-065ff51ec7c9350ac6fae14523ffb237f5127eeeaffb2f80266c416c5df3b07eR6281 (click on the “Load diff” for the first file `dist/dygraph.js`, then scroll to the third hunk where a large amount of **very** badly indented comments is present)?

**Comment by JLHwung** [comment]
> This is a blocker for us to update babel to version `7.21.4`. PR - [mui/material-ui#36815](https://github.com/mui/material-ui/pull/36815)

@ZeeshanTamboli Can you open a new issue? So we can track the regression and see how we can fix it.
