### PR TITLE
Put back ESM helpers in a folder where we can use `.js`

### LINKED ISSUE #12902: `_index.mjs` may not be resolved for some reason in legacy projects
`_index.mjs` of @babel/runtime@7.13.x may not be resolved for some reason in legacy projects, I would like to recommend babel team to rename `_index.mjs` to `index.es.js`, Thanks!

### LINKED ISSUE #12914: Could not find module `@babel/runtime/helpers/typeof/_index.mjs` imported from `@babel/runtime/helpers/esm/typeof`
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**
I created an app with ember using npm and ember-cli ("ember-cli": "^2.18.2"). It was running very well from last 3 years. From last week facing issue while running the app.

**Input Code**
import _extends from `@babel/runtime/helpers/esm/typeof`;
results in this error:
Uncaught Error: Could not find module `@babel/runtime/helpers/typeof/_index.mjs` imported from `@babel/runtime/helpers/esm/typeof`

Calling any other modules available under /node_modules works fine.

**Expected behavior**
Need to be able to call @babel/runtime/...

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `package.json`

```json
{
  "name": "my-ember-ui",
  "version": "0.0.0",
  "private": true,
  "description": "Small description goes here",
  "license": "MIT",
  "author": "",
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "repository": "",
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "devDependencies": {
    "bootstrap": "^3.3.7",
    "broccoli-asset-rev": "^2.4.5",
    "broccoli-static-compiler": "^0.2.2",
    "ember-ajax": "^3.0.0",
    "ember-bootstrap": "^1.0.0",
    "ember-cli": "^2.18.2",
    "ember-cli-app-version": "^3.0.0",
    "ember-cli-babel": "^7.3.0-beta.1",
    "ember-cli-cors": "0.0.2",
    "ember-cli-dependency-checker": "^2.0.0",
    "ember-cli-eslint": "^4.0.0",
    "ember-cli-htmlbars": "^2.0.1",
    "ember-cli-htmlbars-inline-precompile": "^1.0.0",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-jstree": "^1.0.9",
    "ember-cli-notifications": "^4.3.3",
    "ember-cli-qunit": "^4.0.0",
    "ember-cli-shims": "^1.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-concurrency": "^0.8.14",
    "ember-crumbly": "^1.0.7",
    "ember-data": "~2.15.0",
    "ember-export-application-global": "^2.0.0",
    "ember-file-upload": "^2.5.0",
    "ember-flatpickr": "^2.7.0",
    "ember-font-awesome": "4.0.0-rc.4",
    "ember-introjs": "2.4.0",
    "ember-light-table": "^1.12.2",
    "ember-load-initializers": "^1.0.0",
    "ember-models-table": "^2.0.0-beta.3",
    "ember-one-way-select": "^4.0.0",
    "ember-paper-stepper": "0.0.10",
    "ember-power-select": "^2.0.9",
    "ember-resolver": "^4.0.0",
    "ember-responsive": "^2.0.5",
    "ember-source": "~2.15.0",
    "ember-welcome-page": "^3.0.0",
    "loader.js": "^4.2.3"
  },
  "engines": {
    "node": "^4.5 || 6.* || >= 7.*"
  },
  "dependencies": {
    "@babel/runtime": "^7.9.0",
    "ember-cli-js-cookie": "^0.1.1",
    "ember-timepicker": "^0.3.0"
  }
}

```

**Environment**
Babel version(s): @babel/runtime 7.9.0
Node/npm version: Node v10.15.3
OS: Windows 10 Enterprise, 64 bit
```

```

**Possible Solution**

**Additional context**
Note: "@babel/runtime": "^7.9.0" in dependencies added for testing if this can resolve the issue. But unable to fix.
@babel/runtime/helpers/esm/typeof.js and @babel/runtime/helpers/typeof/_index.mjs exists under node_modules

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Closes #12914, closes #12902, also would have closed other already closed issues
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

CW: rant

When preparing https://github.com/babel/babel/pull/12632, I didn't initially realize that thanks to how `package.json#exports` works we can make Node.js and bundlers automatically choose between the ESM and CJS versions of `@babel/runtime` helpers _even if they are in completely different places on the file system_.

Chosing to use the `.mjs` file extension in https://github.com/babel/babel/pull/12632 was a 100% valid choice:
1. All the packages on `npm` are published assuming that the environment uses Node.js's resolution algorithm. `npm` doesn't officially mean "Node package manager", but we all know that it does deep in our hearts. When explicitly using the extension, the target file is _always_ correctly resolved. `console.log(require.resolve("./demo.mjs"));` correctly resolves the file not only in modern Node.js versions but also in ancient ones such as 0.8.28.
2. All the main bundlers correctly load `.mjs` files as JavaScript (I think by default they load any file as JavaScript).

There were some bugs on our side (for example, `_index.mjs` and `index.js` don't have the exact same signature due to backward compat so using the `"module"` condition in `package.json` was an error), but they are all fixed now.

However, it seems like there are some other problems:
1. Many people explicitly configure Webpack to load "any extension that is not `.js`/`.ts`/`.css`" as a string, breaking `.mjs` files. **This is easily fixable on their side, but only when they know why it's broken**
2. Many pre-configured tools built around Webpack configure it to load "any extension that is not `.js`/`.ts`/`.css`" as a string, breaking `.mjs` files. **This is a bug in those tools**
3. I have heard that some less known but still widely used bundlers have problems resolving `.mjs` file. I think the one used by `ember-cli` is one of them based on some bug reports we got, but I didn't try. **`@babel/runtime` never officially cared about their custom resolution algorithms**

TBH I think we would be 100% right if we decide to keep the `.mjs` extension: we are doing a favor to the ecosystem built around Node.js, either by making those tools fix their bugs or by making people switch to tools that don't have the mentioned problems.

However, I already spent too much time helping people whose built was broken by the `@babel/runtime` update because of the broken configs or tools they are using. I'm not the only one, also other people in the team spent time on that.

I completely understand them and I am not attacking any Babel user (either direct, or because their dependencies rely on `@babel/runtime`). If updating a dependency breaks my build, I would obviously first think that it's a problem in the dependency I updated. However, we are not a "free support for everyone" agency, and the best way to avoid doing that is to prevent their builds from crashing (even if because of non-Babel tools).

I didn't test this PR locally, but the best test we have for this is the CI job introduced in https://github.com/babel/babel/pull/12883. I _think_ it will pass, but let's see.

PS (technical): if you are wondering why we can use the `.js` extension in the `esm` folder, it's because it contains a `package.json` file with `"type": "module"`.

### CODE REVIEW

File: test/runtime-integration/node.cjs [hunk 1]
```diff
@@ -4,8 +4,12 @@ const fs = require("fs");
 
 const [major, minor] = process.versions.node.split(".").map(n => +n);
 
-if (major > 12 || (major === 12 && minor >= 17)) {
-  test("ESM", "--experimental-modules ./src/main-esm.mjs", "expected-esm.txt");
+if (
+  major > 13 ||
+  (major === 12 && minor >= 17) ||
+  (major === 13 && minor >= 2)
```
Comment (nicolo-ribaudo) [inline test/runtime-integration/node.cjs:10]: ESM is not enabled by default on 13.0 and 13.1 (thanks @JLHwung for pointing it out)

**Review by Andarist — APPROVED** [review]

**Review by JLHwung — APPROVED** [review]
I think we should revert this PR in Babel 8, as a breaking change for old tools.
