### PR TITLE
Fix `export from` assignment order for loose mode.

### LINKED ISSUE #6805: Issue with loose mode export { x } from 'x';
From https://github.com/babel/babel/pull/6742, tried to upgrade Babel itself

https://github.com/babel/babel/blob/23626fc6ad0cbeb1a6141c2b0c9d6d3f15e478ab/packages/babel-plugin-transform-modules-commonjs/test/fixtures/interop-loose/export-from-2/expected.js

```
exports.foo = _foo.foo;
var _foo = require("foo");
```
since it gets required after @existentialism

### PR DESCRIPTION
**Pull request by yavorsky**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #6805
| Patch: Bug Fix?          | 👍
| Tests Added + Pass?      | Yes
| License                  | MIT

This PR fixes `exports from` behavior in loose mode.
```js
export {foo} from "foo";
```
*Before:*
```js
exports.__esModule = true;
exports.foo = _foo.foo;

var _foo = require("foo");
```
*After*
```js
exports.__esModule = true;
exports.foo = void 0;

var _foo = require("foo");

exports.foo = _foo.foo;
```

So, it will return all exported keys for `foo.js` and require module before module's property access.

I realized that @daft300punk commented that he is working on it. So, I can close in favor of @daft300punk's PR. 👍 

Also, exports-from is acting like a named exports now, so there are additional `_exports.foo = void 0`. Maybe we should use `bindingKindLookup` only for `module-commonjs` ? Anyway, it could be a separate fix.

### CODE REVIEW

**Comment by daft300punk** [comment]
Please go ahead. I haven't had the time to look at it. Thanks.

File: packages/babel-plugin-transform-modules-amd/src/index.js [hunk 1]
```diff
@@ -68,9 +69,17 @@ export default function(api, options) {
...
+            if (!loose) {
+              headers.push(...buildReexportsFromMeta(meta, metadata, loose));
+            }
+
             headers.push(
               ...buildNamespaceInitStatements(meta, metadata, loose),
             );
+
+            if (loose) {
+              headers.push(...buildReexportsFromMeta(meta, metadata, loose));
```
Comment (loganfsmyth) [inline packages/babel-plugin-transform-modules-amd/src/index.js]: I've lost a bit of context on all this, but couldn't we include this in `buildNamespaceInitStatements` when in loose mode, and leave the old logic where it was? I might also just be forgetting stuff, so either way no worries :P

File: packages/babel-helper-module-transforms/src/index.js [hunk 2]
```diff
@@ -150,6 +155,30 @@ export function buildNamespaceInitStatements(
   return statements;
 }
 
+export function buildReexportsFromMeta(meta, metadata, loose) {
+  const reexports = [];
+  for (const [exportName, importName] of metadata.reexports) {
```
Comment (Andarist) [inline packages/babel-helper-module-transforms/src/index.js]: wouldnt a `.map` be better describing the intent here?

Comment (yavorsky) [reply packages/babel-helper-module-transforms/src/index.js]: @Andarist Sure! Thanks

Comment (yavorsky) [reply packages/babel-helper-module-transforms/src/index.js]: @Andarist I've checked.. metadata.reexports is a Map. I think, it's better to use `for..of` instead of `Array.from` because of performance and consistency.

Comment (Kovensky) [reply packages/babel-helper-module-transforms/src/index.js]: Not sure... a `return Array.from(metadata.reexports, ([exportName, importName]) => (loose ? ... : ...))` looks better to me, but I just overall prefer functional style 🤔

File: packages/babel-helper-module-transforms/src/index.js [hunk 3]
```diff
@@ -150,6 +155,30 @@ export function buildNamespaceInitStatements(
...
+    reexports.push(
+      (loose
+        ? template.statement`EXPORTS.EXPORT_NAME = NAMESPACE.IMPORT_NAME;`
+        : template`
```
Comment (Kovensky) [inline packages/babel-helper-module-transforms/src/index.js]: I suspect hoisting the `template.statement` / `template` calls outside of the loop will do a lot more for performance than changing between `Array.from` or `for of`

File: packages/babel-helper-module-transforms/src/index.js [hunk 4]
```diff
@@ -155,28 +155,29 @@ export function buildNamespaceInitStatements(
...
-        EXPORTS: meta.exportName,
-        EXPORT_NAME: exportName,
-        NAMESPACE: metadata.name,
-        IMPORT_NAME: importName,
-      }),
-    );
-  }
-  return reexports;
+  const templateForCurrentMode = getTemplateForReexport(loose);
+  return Array.from(metadata.reexports).map(([exportName, importName]) =>
```
Comment (Kovensky) [inline packages/babel-helper-module-transforms/src/index.js]: The `.map` is redundant; use the second argument of `Array.from`: `Array.from(metadata.reexports, ([exportName, importName]) =>`

Comment (yavorsky) [reply packages/babel-helper-module-transforms/src/index.js]: Really, thanks :)

File: packages/babel-helper-module-transforms/src/index.js [hunk 5]
```diff
@@ -150,6 +155,31 @@ export function buildNamespaceInitStatements(
...
+        enumerable: true,
+        get: function() {
+          return NAMESPACE.IMPORT_NAME;
+        },
+      });
+    `;
+};
+
+export function buildReexportsFromMeta(meta, metadata, loose) {
+  const templateForCurrentMode = getTemplateForReexport(loose);
```
Comment (loganfsmyth) [inline packages/babel-helper-module-transforms/src/index.js]: I disagree with @Kovensky here :) I don't think moving this out of the loop matters at all, because there's caching happening here automatically.

File: packages/babel-helper-module-transforms/src/index.js [hunk 6]
```diff
@@ -150,6 +155,31 @@ export function buildNamespaceInitStatements(
...
+      Object.defineProperty(EXPORTS, "EXPORT_NAME", {
+        enumerable: true,
+        get: function() {
+          return NAMESPACE.IMPORT_NAME;
+        },
+      });
+    `;
+};
+
+export function buildReexportsFromMeta(meta, metadata, loose) {
```
Comment (loganfsmyth) [inline packages/babel-helper-module-transforms/src/index.js]: No `export` needed now, right?
