### PR TITLE
(ts) Raise syntax error for an abstract method that has body

### LINKED ISSUE #12682: No syntax error for abstract methods that have an implementation
## Bug Report

- [x] I would like to work on a fix!

**Current behavior**

- [REPL](https://babeljs.io/repl#?browsers=safari%2012&build=&builtIns=false&spec=false&loose=false&code_lz=IYIwzgLgTsDGEAJYBthjAgYge2wg3gFAIKiQzwIC2AphABbYAmAFAJQEC-A3IZ4UA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=typescript&prettier=false&targets=&version=7.12.12&externalPlugins=)

**Input Code**

```ts
abstract class Foo {
  abstract method() {};
}
```

**Expected behavior**

Syntax error should be thrown `Method 'method' cannot have an implementation because it is marked abstract.`.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "presets": ["@babel/preset-typescript"]
}
```
**Possible Solution**

**Additional context**

### PR DESCRIPTION
**Pull request by sosukesuzuki**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #12682
| Patch: Bug Fix?          | Y
| Tests Added + Pass?      | Yes
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/12687"></a>

### CODE REVIEW

**Review by existentialism — APPROVED** [review]

File: packages/babel-parser/src/plugins/typescript/index.js [hunk 1]
```diff
@@ -2824,4 +2826,39 @@ export default (superClass: Class<Parser>): Class<Parser> =>
...
     }
+
+    parseMethod<T: N.MethodLike>(
+      node: T,
+      isGenerator: boolean,
+      isAsync: boolean,
+      isConstructor: boolean,
+      allowDirectSuper: boolean,
+      type: string,
+      inClassScope: boolean = false,
```
Comment (JLHwung) [inline packages/babel-parser/src/plugins/typescript/index.js:2837]: nit: We can just use `...args` if none of them are used in the post processing logic. So we would not forget to sync signatures when we add even more arguments to `parseMethod`.

Comment (KFlash) [reply packages/babel-parser/src/plugins/typescript/index.js:2837]: Use of `...args` is one of the slowest alternatives. Just mention it in case perf is relevant here

File: packages/babel-parser/src/plugins/typescript/index.js [hunk 2]
```diff
@@ -2824,4 +2826,24 @@ export default (superClass: Class<Parser>): Class<Parser> =>
...
       }
     }
+
+    // `...args` can have a negative impact on performance.
+    parseMethod(...args: any[]) {
+      const method = super.parseMethod(...args);
+      if ((method: any).abstract) {
+        const hasBody =
+          // For estree plugin
+          method.type === "MethodDefinition"
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/src/plugins/typescript/index.js:2836]: We can do `this.hasPlugin("estree")` in this case, so that it's self-explanatory.

**Comment by KFlash** [comment]
Use of 7 properties like that consumes lots of memory. Each property takes 3 bytes each. So 21 bytes total. Plus the size of the object will give e perf regression in V8 etc. 

'...' operator is slower than simply iterate through and push to an array (search on google).

Direct string comparison is also slow.

Just mention in case perf and memory is a concern.

File: packages/babel-parser/src/plugins/typescript/index.js (hunk 1 above)
Comment (sosukesuzuki) [reply packages/babel-parser/src/plugins/typescript/index.js]: There are already some `...args` in our codebase. I don't know if this is a performance bottleneck, but at least I don't think we need to worry in this PR.

File: packages/babel-parser/src/plugins/typescript/index.js [hunk 3]
```diff
@@ -2824,4 +2826,21 @@ export default (superClass: Class<Parser>): Class<Parser> =>
         this.state.isDeclareContext = oldIsDeclareContext;
       }
     }
+
+    parseMethod(...args: any[]) {
+      const method = super.parseMethod(...args);
+      if ((method: any).abstract) {
+        const hasBody = this.hasPlugin("estree")
+          ? !!method.value.body
```
Comment (KFlash) [inline packages/babel-parser/src/plugins/typescript/index.js:2834]: 2x member access is a perf regression

File: packages/babel-parser/src/plugins/typescript/index.js (hunk 1 above)
Comment (KFlash) [reply packages/babel-parser/src/plugins/typescript/index.js]: In general. Everything that is a perf regression should be improved, but this is just a TS plugin so maybe no point because too much perf issues in this plugin.

File: packages/babel-parser/src/plugins/typescript/index.js [hunk 4]
```diff
@@ -2824,4 +2826,21 @@ export default (superClass: Class<Parser>): Class<Parser> =>
...
+          : !!method.body;
+        if (hasBody) {
+          this.raise(
+            method.start,
+            TSErrors.AbstractMethodHasImplementation,
+            (method: any).key.name,
```
Comment (JLHwung) [inline packages/babel-parser/src/plugins/typescript/index.js:2840]: The method key is not always Identifier, and that's why Flow complains here.

```ts
abstract class C {
  abstract [M]();
}
```

I think we can just throw
```
An abstract method cannot have an implementation.
```

Comment (KFlash) [reply packages/babel-parser/src/plugins/typescript/index.js:2840]: Is this correct error message to be used here? For example TS never throws on 
`abstract class C {  abstract a(): string; }`, but throws on `abstract class C {  abstract a(); }` because it's lack return type.

Regarding the example above. TS throws

`A computed property name in a method overload must refer to an expression whose type is a literal type or a 'unique symbol' type.ts(1168`

`'[M]', which lacks return-type annotation, implicitly has an 'any' return type.ts(7010)`

Comment (nicolo-ribaudo) [reply packages/babel-parser/src/plugins/typescript/index.js:2840]: If you disable the (opt-in, but enabled by default in the playground) `noImplicitAny` option, that code doesn't generate any error: https://www.typescriptlang.org/play?noImplicitAny=false#code/MYewdgzgLgBAsjAvDARAawKYE8UwIYQyiRQDcAsAFBV4BG0ATnsLMADYGEDCMA3lTHz0oTFjADacALoAKAJQVKAXypA

Comment (JLHwung) [reply packages/babel-parser/src/plugins/typescript/index.js:2840]: Sorry for the confusion here, I was meant to say that an abstract method can be computed, so that example is valid. And the TS error can be suppressed by specifying `M`. To be clear

```ts
abstract class C {
  abstract [M]() {}
}
```
will throw.

I don't think we have to extract computed key here, since it can be very verbose.

Comment (nicolo-ribaudo) [reply packages/babel-parser/src/plugins/typescript/index.js]: > I don't think we have to extract computed key here, since it can be very verbose.

I ended up doing it since I noticed it's exactly what TS does.

**Review by nicolo-ribaudo — APPROVED** [review]
