### PR TITLE
fix: reference to class expression in private method

### LINKED ISSUE #13399: [Bug]: Reference to class expression in private methods is not correctly compiled
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
fn(class WorkerClient {
  static #worker_threads() {
    return WorkerClient;
  }
});
```

[REPL](https://babeljs.io/repl#?browsers=chrome%2060&build=&builtIns=false&corejs=false&spec=false&loose=false&code_lz=GYOwFAxgNghgznABAdQPYCcDWBTdBhKAS2xABdEBvAKEUTlJlMIkQGIB3DHdAfVIAt02GABM4YAJSUatRENIBXdCBRdcBYmQDcMgL5VdErUA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env&prettier=false&targets=&version=7.14.4)

### Configuration file name

_No response_

### Configuration

```json
{
  "plugins": [
    "@babel/plugin-proposal-private-methods",
    "@babel/plugin-proposal-class-properties"
  ]
}
```

### Current and expected behavior

It is compiled to this:
```js
var _class;

fn(_class = class WorkerClient {});

function _worker_threads() {
  return WorkerClient;
}
```

As you can see, `WorkerClient` is not reachable. It should be compiled to something like this:
```js
var _class;

fn(_class = class WorkerClient {});

function _worker_threads() {
  return _class;
}
```

### Environment

- Babel 7.14.4

### Possible solution

In the `replaceThisContext` function that we use to replace `this` usage in class fields and private methods:
https://github.com/babel/babel/blob/813f2a3cce04a5366de7c1cc370652db64507305/packages/babel-helper-create-class-features-plugin/src/fields.ts#L672

we should add a new `path.traverse` call to replace references to the inner binding, with a visitor similar to this one:
```js
const innerReferencesVisitor = {
  ReferencedIdentifier(path, state) {
    const { name } = path.node;
    if (path.scope.bindingIdentifierEquals(name, state.innerBinding)) {
      state.needsClassRef = true;
      path.replaceWith(t.cloneNode(state.classRef));
    }
  },
};
```

where `state` is the one used by `thisContextVisitor` with the addition of `state.innerBinding`, which is the node representing the id of the class expression.

Note that we don't need to merge this visitor with `environmentVisitor`: `environmentVisitor` is only needed to avoid replacing nested `this`es that don't refer to the class, while for normal bindings we use `path.scope.bindingIdentifierEquals`.

We can get `innerBinding` from right before extracting the class reference at https://github.com/babel/babel/blob/813f2a3cce04a5366de7c1cc370652db64507305/packages/babel-helper-create-class-features-plugin/src/index.ts#L173-L178

We only need to get it if we have a `ClassExpression` and `path.node.id` is set, otherwise we can leave `innerBinding` as `undefined` and use it as a "signal" to skip the new `path.traverse` call.

After working on the fix itself, we'll need a bunch of tests:
- A simple `input.js`/`output.js` test, for example my original example
- An `exec.js` test, to check that the binding is the correct one. For example:
  ```js
  let x = class Test {
    static #getTest() { return Test }
    static getTest() { return this.getTest() }
  };
 
  expect(x.getTest()).toBe(x);
  ```
- An `input`/`output` test to verify that it works when the binding is used in nested scopes, for example:
  ```js
  let x = class Test {
    static #method() {
      return function inner() {
        return Test;
      };
    }
  }
  ```
- An `input`/`output` test to verify that it doesn't rewrite shadowed bindings:
  ```js
  let x = class Test {
    static #method() {
      new Test();

      return function inner() {
        let Test = 2;
        return Test;
      };
    }
  }
  ```

### Additional context

The same bug happens with static class fields (both public and private) and instance private methods:
```js
fn(class WorkerClient {
  static #x = WorkerClient;
  static y = WorkerClient;
});
```

we should duplicate the tests for those cases.

### PR DESCRIPTION
**Pull request by lala7573**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #13399 
| Patch: Bug Fix?          | 👍
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | 👍
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/13429"></a>

### CODE REVIEW

File: packages/babel-helper-create-class-features-plugin/src/index.ts [hunk 1]
```diff
@@ -168,15 +168,18 @@ export function createClassFeaturePlugin({
...
+        let ref = undefined;
         if (path.isClassExpression() || !path.node.id) {
           nameFunction(path);
           ref = path.scope.generateUidIdentifier("class");
         } else {
           ref = t.cloneNode(path.node.id);
         }
 
+        if (ref !== undefined) {
+          ref.innerBinding = path.node.id;
```
Comment (lala7573) [inline packages/babel-helper-create-class-features-plugin/src/index.ts:180]: I think this code would be better than the original 😕 
```
ref.innerBinding = ref !== undefined? path.node.id : undefined
```

File: packages/babel-helper-create-class-features-plugin/src/index.ts [hunk 2]
```diff
@@ -168,15 +168,18 @@ export function createClassFeaturePlugin({
 
         if (!props.length && !isDecorated) return;
 
-        let ref;
-
+        let ref = undefined;
```
Comment (nicolo-ribaudo) [inline packages/babel-helper-create-class-features-plugin/src/index.ts:171]: We don't need to explicitly initialize it to `undefined`, it's the default value.

File: packages/babel-helper-create-class-features-plugin/src/index.ts (hunk 1 above)
Comment (nicolo-ribaudo) [inline packages/babel-helper-create-class-features-plugin/src/index.ts:180]: Since `ref` is an AST node, we shouldn't use it to store additional information. It's better to keep `innetBinding` as a separate variable, and just do
```js
const innerBinding = path.node.id;
```

Also, we can move this to before the previous `if` (line 172): if a class doesn't have a `path.node.id` yet, it cannot be referenced anyway.

File: packages/babel-helper-create-class-features-plugin/src/fields.ts [hunk 3]
```diff
@@ -696,6 +707,11 @@ function replaceThisContext(
   if (isStaticBlock || path.isProperty()) {
     path.traverse(thisContextVisitor, state);
   }
+
+  if (state.classRef?.name !== innerBinding?.name) {
```
Comment (nicolo-ribaudo) [inline packages/babel-helper-create-class-features-plugin/src/fields.ts:711]: We should be careful here: what if both `state.classRef` and `innerBinding` are `undefined`? This check would be `true`.

**Review by nicolo-ribaudo — COMMENTED** [review]
Thanks for the PR!

File: packages/babel-plugin-proposal-class-properties/test/fixtures/private/static-self-field/input.js [hunk 4]
```diff
@@ -0,0 +1,8 @@
+function wrapper(wc) {
+  return wc
+}
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-proposal-class-properties/test/fixtures/private/static-self-field/input.js:3]: Nit: we don't need to declare the `wrapper` function for `input`/`output` tests, since it's not executed anyway.

File: packages/babel-helper-create-class-features-plugin/src/fields.ts [hunk 5]
```diff
@@ -669,6 +669,16 @@ const thisContextVisitor = traverse.visitors.merge([
   environmentVisitor,
 ]);
 
+const innerReferencesVisitor = {
+  ReferencedIdentifier(path, state) {
+    const { name } = path.node;
+    if (path.scope.bindingIdentifierEquals(name, state.innerBinding)) {
+      state.needsClassRef = true;
+      path.replaceWith(t.cloneNode(state.classRef));
```
Comment (JLHwung) [inline packages/babel-helper-create-class-features-plugin/src/fields.ts:677]: Since we only changing name, may be we can just modify `path.node.name` instead of requeueing the AST node?

**Comment by nicolo-ribaudo** [comment]
The `CI / E2E (babel-old-version)` failure has been fixed on `main` so you can safely ignore it.

File: packages/babel-helper-create-class-features-plugin/src/fields.ts (hunk 3 above)
Comment (lala7573) [reply packages/babel-helper-create-class-features-plugin/src/fields.ts:711]: If one of the values is undefined, then it would be `false` because the operator is `not equals`.

Comment (lala7573) [reply packages/babel-helper-create-class-features-plugin/src/fields.ts:711]: I think if both of the values are undefined, it would be `false` because the operator is `!==`. 
But if `state.classRef` is undefined, the traverse goes wrong. I'll fix it. Thanks for pointing out!

File: packages/babel-helper-create-class-features-plugin/src/fields.ts (hunk 5 above)
Comment (lala7573) [reply packages/babel-helper-create-class-features-plugin/src/fields.ts:677]: Aha. I didn't know that. Thank you for your advice.

File: packages/babel-helper-create-class-features-plugin/src/fields.ts (hunk 3 above)
Comment (nicolo-ribaudo) [reply packages/babel-helper-create-class-features-plugin/src/fields.ts]: Oh right! When comparing two things with `?.` _usually_ there might be a problem, but I failed at identifying it :grimacing:

**Review by nicolo-ribaudo — APPROVED** [review]
Thanks!

File: packages/babel-helper-create-class-features-plugin/src/fields.ts [hunk 6]
```diff
@@ -669,15 +669,30 @@ const thisContextVisitor = traverse.visitors.merge([
   environmentVisitor,
 ]);
 
+const innerReferencesVisitor = {
+  ReferencedIdentifier(path, state) {
+    const { name } = path.node;
+    if (path.scope.bindingIdentifierEquals(name, state.innerBinding)) {
```
Comment (hzoo) [inline packages/babel-helper-create-class-features-plugin/src/fields.ts:675]: can probably just inline the above line vs using destructing if only using it once?
```suggestion
    if (path.scope.bindingIdentifierEquals(path.node.name, state.innerBinding)) {
```

File: packages/babel-helper-create-class-features-plugin/src/index.ts [hunk 7]
```diff
@@ -168,8 +168,8 @@ export function createClassFeaturePlugin({
 
         if (!props.length && !isDecorated) return;
 
+        const innerBinding = path.node.id;
         let ref;
-
         if (path.isClassExpression() || !path.node.id) {
```
Comment (hzoo) [inline packages/babel-helper-create-class-features-plugin/src/index.ts:173]: can reuse tne innerBinding and line 177?
```suggestion
        if (path.isClassExpression() || !innerBinding) {
```

**Review by hzoo — APPROVED** [review]
tests lgtm!

File: packages/babel-helper-create-class-features-plugin/src/index.ts [hunk 8]
```diff
@@ -168,9 +168,9 @@ export function createClassFeaturePlugin({
 
         if (!props.length && !isDecorated) return;
 
+        const innerBinding = path.node.id;
         let ref;
-
-        if (path.isClassExpression() || !path.node.id) {
+        if (path.isClassExpression() || !innerBinding) {
```
Comment (fedeci) [inline packages/babel-helper-create-class-features-plugin/src/index.ts:173]: nitpick: 
```suggestion
        if (!innerBinding || path.isClassExpression()) {
```

**Review by fedeci — APPROVED** [review]
