### PR TITLE
Enable and fix babel-register tests

### LINKED ISSUE #7477: Fix and reenable babel-register tests
Instead of doing end2end tests which do not work with jests way of handling requires, we should mock `pirates` and instead only test the code that is actually in babel-register.

### PR DESCRIPTION
**Pull request by danez**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #7477 
| Patch: Bug Fix?          | n
| Major: Breaking Change?  | n
| Minor: New Feature?      | n
| Tests Added + Pass?      | Yes
| Documentation PR         | 
| Any Dependency Changes?  |
| License                  | MIT

I changed the base register test to mock `pirates and source-map support` and just test it calls these libs correctly.
The cache tests worked after fixing the cache invalidation with jest.

### CODE REVIEW

File: packages/babel-register/test/cache.js [hunk 1]
```diff
@@ -28,13 +28,13 @@ function resetCache() {
...
 
-describe.skip("@babel/register - caching", () => {
+describe("@babel/register - caching", () => {
   describe("cache", () => {
     let load, get, save;
 
     beforeEach(() => {
       // Since lib/cache is a singleton we need to fully reload it
-      delete require.cache[require.resolve("../lib/cache")];
+      jest.resetModuleRegistry();
```
Comment (nicolo-ribaudo) [inline packages/babel-register/test/cache.js]: Isn't this run automatically by jest before each test? (https://github.com/facebook/jest/issues/587#issuecomment-153263356)

Comment (danez) [reply packages/babel-register/test/cache.js]: Maybe it changed? Or it is only run once for each test file? At least the tests weren't working without.

Comment (SimenB) [reply packages/babel-register/test/cache.js]: Should be https://facebook.github.io/jest/docs/en/jest-object.html#jestresetmodules. `resetModuleRegistry` is a deprecated alias and not publicly documented.

https://github.com/facebook/jest/blob/0b076cdfd6020810fc05fb0f26cdca30d688ead1/packages/jest-runtime/src/index.js#L829-L830

It is not run automatically between tests in a single suite, but each suite (file) is run in isolation

Comment (danez) [reply packages/babel-register/test/cache.js]: Ah thanks, I somewhere found it documented, but now I can't find it anymore :) Will fix it.
