### PR TITLE
Fix PathHoister hoisting JSX member expressions on "this".

### LINKED ISSUE #4397: [transform-react-constant-elements] Can't use `this` in react element name  (T7494)
> Issue originally made by @rafaelsales
### Bug information
- **Babel version:** master
### Options

```
plugins: [
              'transform-react-constant-elements'
            ]
```
### Input code

``` js
class Component extends React.Component {

    subComponent = () => <span>Sub Component</span>

    render = () => <this.subComponent />
  }
```
### Description

The reported error is: Uncaught TypeError: Cannot read property 'subComponent' of undefined

A workaround for the issue is to put `this` in a variable:

``` js
  class Component extends React.Component {

    subComponent = () => <span>Sub Component</span>

    render = () => {
      const self = this
      return <self.subComponent />
    }
  }
```

### PR DESCRIPTION
**Pull request by STRML**
| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          |  yes
| Major: Breaking Change?  | no 
| Minor: New Feature?      | no
| Deprecations?            | no
| Spec Compliancy?         | no
| Tests Added/Pass?        | yes
| Fixed Tickets            | #4397 
| License                  | MIT

The PathHoister ignored member references on `this`, causing it to potentially hoist an expression above its function scope.

This patch tells the hoister to watch for `this`, and if seen, mark the nearest non-arrow function scope as the upper limit for hoistng.

This fixes #4397 and is an alternative to #4787.

### CODE REVIEW

File: packages/babel-traverse/src/path/lib/hoister.js [hunk 1]
```diff
@@ -2,11 +2,23 @@ import { react } from "babel-types";
...
   ReferencedIdentifier(path, state) {
-    if (path.isJSXIdentifier() && react.isCompatTag(path.node.name)) {
+    // Don't hoist regular JSX identifiers ('div', 'span', etc).
+    // We do have to consider member expressions for hoisting (e.g. `this.component`)
+    if (path.isJSXIdentifier() && react.isCompatTag(path.node.name) && !path.parentPath.isJSXMemberExpression()) {
       return;
     }
 
+    // If the identifier refers to `this`, we need to break on the closest non-arrow scope.
+    if (path.node.name === "this") {
```
Comment (loganfsmyth) [inline packages/babel-traverse/src/path/lib/hoister.js]: Oh gross, I didn't know JSX didn't use `ThisExpression`. I bet we have bugs if you transpile ES6 -> ES5 with JSX pass-through enabled. No way does everything that processes `this` also check for JSXIdentifier.

Nothing for you to change, just complaining :P
