### PR TITLE
fix: Remove type-only `import x = y.z`

### LINKED ISSUE #15942: [Bug]: TypeScript type only import namespace aliases are not removed
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
import { X } from "abc";
// assume Y is a type only namespace
import Z = X.Y.Z;

function a(t: Z.T) {
  console.log(t);
}
```

### Configuration file name

babel.config.js

### Configuration

```js
export = {
  assumptions: {
  },
  presets: [
    ["@babel/preset-env", {
      // preserve ES module syntax (imports, exports)
      modules: false,
      targets: {
        firefox: "91",
        chrome: "88",
        edge: "88"
      }
    }],
    ["@babel/preset-typescript", {
      allowNamespaces: true,
      allowDeclareFields: true
    }],
    "@babel/preset-react"
  ],
  plugins: [
    ["@babel/plugin-transform-typescript", {
      allowDeclareFields: true,
    }],
    ["@babel/plugin-proposal-decorators", {
      "legacy": true
    }],
    ["@babel/plugin-transform-class-properties", {"loose": false}],
    "@babel/plugin-proposal-private-property-in-object",
    "@babel/plugin-transform-runtime",
  ],
}
```

### Current and expected behavior

As with TypeScript, no code is now generated for type only namespaces.  However, if you import a type only namespace using an import alias, code is generated for this import, which can crash at runtime.  In the example input code, Z is a type only namespace with an interface T inside of if (or any other type).  Since it's only used as a type in the code, the code for the alias should be removed.  Instead, the generated code includes

```js
var Z = X.Y.Z;
```
Because Y doesn't exist (it's type only), X.Y.Z crashes (Y is undefined).

I would expect no code to be generated for `import Z = X.Y.Z`.

### Environment

```
    "@babel/core": "7.22.15",
    "@babel/plugin-transform-class-properties": "7.22.5",
    "@babel/plugin-proposal-decorators": "7.22.15",
    "@babel/plugin-proposal-private-property-in-object": "7.21.11",
    "@babel/plugin-transform-runtime": "7.22.15",
    "@babel/plugin-transform-typescript": "7.22.15",
    "@babel/preset-env": "7.22.15",
    "@babel/preset-react": "7.22.15",
    "@babel/preset-typescript": "7.22.15",
```
node 16.16.0

### Possible solution

_No response_

### Additional context

[Repl example demonstrating](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAbzgDTgXzgMyhEcBEAhgEYDG-A3AFCiSxwBacAvCgHQCabD1VmArgDtSMYBEFxCAChgAuRmwAqASkRU4cUuIDOEADYBTNnogBzGcupoqQA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2%2Ctypescript&prettier=false&targets=&version=7.22.16&externalPlugins=&assumptions=%7B%7D)

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #15942 
| Patch: Bug Fix?          | √
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

This seems a bit dangerous and I'm not sure if this will cause a regression.

### CODE REVIEW

File: packages/babel-traverse/src/scope/index.ts [hunk 1]
```diff
@@ -268,7 +268,17 @@ const collectorVisitor: Visitor<CollectVisitorState> = {
...
+    parent.registerDeclaration(path);
+  },
+
   ReferencedIdentifier(path, state) {
+    if (t.isTSQualifiedName(path.parent) && path.parent.right === path.node) {
+      return;
+    }
+    if (path.parentPath.isTSImportEqualsDeclaration()) return;
     state.references.push(path);
   },
```
Comment (liuxingbaoyu) [inline packages/babel-traverse/src/scope/index.ts:283]: I didn't use `childPath.skip()` to make it easier to re-land https://github.com/babel/babel/pull/16923 in the future.

File: packages/babel-plugin-transform-typescript/test/fixtures/exports/export-import=/output.mjs [hunk 2]
```diff
@@ -1,2 +1 @@
 import * as joint from '@joint/core';
-export var JGraph = joint.dia.Graph;
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-typescript/test/fixtures/exports/export-import=/output.mjs:2]: This is wrong, what if `joint.dia.Graph` is a value and not a type?

**Comment by nicolo-ribaudo** [comment]
Failure looks related :)

**Comment by nicolo-ribaudo** [comment]
How does this PR interact with the `onlyRemoveTypeImports` option? Can we have a test verifying that we only remove `import type foo =` and not `import foo =` when it's enabled?

**Comment by nicolo-ribaudo** [comment]
Oh I see. It seems like TypeScript simply does not remove it when the equivalent TS option (`verbatimModuleSyntax`) is enabled: https://www.typescriptlang.org/play/?verbatimModuleSyntax=true#code/JYWwDg9gTgLgBAbzgIwIZTgXzgMyhEOAIgA8iBuAKFEllwgjgF4V0A6NALyuvGnhgBPMAFNEcVMgDGWXPkKkKvWvAAmInMwnS2JKkNFwAFgHNgWyVN08gA Instead, people should just replace `import` with `type`.

**Review by nicolo-ribaudo — APPROVED** [review]

**Review by JLHwung — APPROVED** [review]
