### PR TITLE
[2021-12] Support class decorators in export declarations

### LINKED ISSUE #14395: [Bug]: can't using decorator before or after export
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/register or @babel/node

### Input code

```javascript
function log() {}


export @log class Todo {
  a() {}
}
```

### Configuration file name

_No response_

### Configuration

```json
{
  "presets": [["@babel/preset-env", { "targets": { "node": "16.0.0" } }]],
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "version": "2021-12" }]
  ]
}
```

### Current and expected behavior

tested `decoratorsBeforeExport` = `true` / `false`
both throw an error.
```bash
npx babel-node todo.js
Error:  ... We don't know what to do with this node type. We were previously a Statement but we can't fit in here?
```

### Environment

  System:
    OS: macOS 11.3
  Binaries:
    Node: 17.7.2 - ~/.nvm/versions/node/v17.7.2/bin/node
    npm: 8.5.2 - ~/.nvm/versions/node/v17.7.2/bin/npm
  npmPackages:
    @babel/cli: ^7.17.6 => 7.17.6 
    @babel/core: ^7.17.8 => 7.17.8 
    @babel/node: ^7.16.8 => 7.16.8 
    @babel/plugin-proposal-decorators: ^7.17.8 => 7.17.8 
    @babel/preset-env: ^7.16.11 => 7.16.11 
    babel-plugin-module-resolver: ^4.1.0 => 4.1.0 

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #14395
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14396"></a>

### CODE REVIEW

**Review by pzuraq — APPROVED** [review]

**Review by JLHwung — APPROVED** [review]

File: packages/babel-plugin-proposal-decorators/test/fixtures/2021-12-exported/default-anonymous/output.mjs [hunk 1]
```diff
@@ -0,0 +1,17 @@
+var _initClass, _dec;
+
+let _A;
+
+_dec = dec
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-proposal-decorators/test/fixtures/2021-12-exported/default-anonymous/output.mjs:5]: Here there is a missing `ExpressionStatement`, I'll open a new PR.
