### PR TITLE
fix: fixed issue16583 + test

### LINKED ISSUE #16583: [Bug]: variable declarator remove bug
### 💻

- [x] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
// WORKING_DIR_ROOT/test/custom_tests/remove.js

const traverse = require("../../packages/babel-traverse/lib").default;
const t = require("../../packages/babel-types/lib");
const generate = require("../../packages/babel-generator/lib");
const { parse } = require("../../packages/babel-parser");


const script = `
{
  let a = 33;
}
let a = 42;
`

const AST = parse(script);

let found = false;
traverse(AST, {
  /**
   * 
   * @param {NodePath<t.VariableDeclarator>} path 
   * @returns 
   */
  VariableDeclarator(path){
          
    if(!found && path.toString() === "a = 33"){
      found = true;
       path.remove();
      return;
    } else if(path.toString() === "a = 42") {
      const binding = path.scope.getBinding("a");  
      // binding is undefined
      console.log(binding);
      // can't access path of undefined
      console.log(binding.path.toString());
    }
    
    
  }
});
```

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

The test script is comprised of a BlockStatement containing one VariableDeclaration with a VariableDeclarator named `a` having any type of value. Outside of the BlockStatement we have another VariableDeclaration, just as the last one, with a VariableDeclarator having the same name.

What babel is doing is that when we remove the VariableDeclarator (NOT VariableDeclaration) from inside the BlockStatement makes it so that both Bindings of `a` (the one from the scope of the BlockStatement, and also the one from the parent scope) are deleted.

The expected behavior would be that only the Binding of `a` in the BlockStatement's scope to be deleted, but that doesn't happen

### Environment

System:
  OS: Windows 10 10.0.19045
Binaries:
  Node: 20.14.0 - C:\Program Files\nodejs\node.EXE
  Yarn: 4.2.2 - C:\Program Files\nodejs\yarn.CMD
  npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD

### Possible solution

The problem arises in the [`packages/babel-traverse/src/path/removal.ts > remove`](https://github.com/babel/babel/blob/main/packages/babel-traverse/src/path/removal.ts#L9) function, more specifically, when calling the [`this._callRemovalHooks()`](https://github.com/babel/babel/blob/main/packages/babel-traverse/src/path/removal.ts#L32) function. By the point the `_callRemovalHooks` function is called, the Binding of `a` is already removed, keep this in mind.

The first hook:

```js
function (self: NodePath, parent: NodePath) {
    const removeParent =
      // while (NODE);
      // removing the test of a while/switch, we can either just remove it entirely *or* turn the
      // `test` into `true` unlikely that the latter will ever be what's wanted so we just remove
      // the loop to avoid infinite recursion
      (self.key === "test" && (parent.isWhile() || parent.isSwitchCase())) ||
      // export NODE;
      // just remove a declaration for an export as this is no longer valid
      (self.key === "declaration" && parent.isExportDeclaration()) ||
      // label: NODE
      // stray labeled statement with no body
      (self.key === "body" && parent.isLabeledStatement()) ||
      // let NODE;
      // remove an entire declaration if there are no declarators left
      (self.listKey === "declarations" &&
        parent.isVariableDeclaration() &&
        parent.node.declarations.length === 1) ||
      // NODE;
      // remove the entire expression statement if there's no expression
      (self.key === "expression" && parent.isExpressionStatement());

    if (removeParent) {
      parent.remove();
      return true;
    }
  }
```

is the one we are going down on, which in turn calls `parent.remove()`, which is the same `remove` function that was previously mentioned.

Now, the problem lies when we call [`this._removeFromScope()`](https://github.com/babel/babel/blob/main/packages/babel-traverse/src/path/removal.ts#L14), that is because the call to [`getBindingIdentifiers`](https://github.com/babel/babel/blob/main/packages/babel-traverse/src/path/removal.ts#L28) returns the bindings that we already removed.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nerodesu017**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #16583 
| Patch: Bug Fix?          | Yes, hotfix
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

I have redone the solution for issue #16583.
The problem with it was that when removing a VariableDeclarator, the binding related to it was getting removed. If, after this, the VariableDeclaration parent was empty (check from removal hooks), the binding was removed a second time. If no binding with the same name was to be found in parent scopes, it wasn't problematic, but if a binding with the same name was in parent scopes, it was getting removed erroneously.

### CODE REVIEW

**Comment by nerodesu017** [comment]
I have successfully managed to solve the problem, but I still need an opinion over modifying the `getBinding` to `getOwnBinding` change. The former would mean traversing up the scopes, which is, from my point of view, not breaking. But please prove me otherwise, if it is.

**Comment by liuxingbaoyu** [comment]
I think this breaks the usage of `removeScope`.
Perhaps as a quick fix, we can modify `_removeFromScope`, which should be safer.
image

**Comment by nerodesu017** [comment]
> Thanks for the PR!
> 
> I think this breaks the usage of `removeBinding`. Perhaps as a quick fix, we can modify `_removeFromScope`, which should be safer. image
> 
> In addition, we can modify `parent.remove();` in `hooks` to avoid removing the scope information of the `VariableDeclaration` node.

Hi, thank you for feedback!
And you are indeed right, modifying `removeBinding` directly is not desired, will modify `_removeFromScope` as you pointed out.
Still have to tinker with the specific hook, as I don't seem to get it right at the moment (test fails), but the `_removeFromScope` change does!

Thank you, once again, will run tests one more time and push

**Comment by liuxingbaoyu** [comment]
Sorry, I realize this still seems to break the example.
```ts
{
	var x = 1;
}
```
Because `var` is hoisted to a higher scope.

image
Something like this seems to work, but note that this is just an example and it doesn't handle the case where `opts` is `null`.
Perhaps we could add a `removeNoScope` for internal use, but I'd like to hear from other members before doing so.

File: packages/babel-traverse/test/fixtures/scope/remove-nested-let-path/plugin.js [hunk 1]
```diff
@@ -0,0 +1,15 @@
+module.exports = function () {
+  return {
+    visitor: {
+      VariableDeclarator(path) {
+        switch (path + "") {
+          case "a = 33":
+            path.remove();
+
+          case "a = 42":
+            expect(path.scope.getBinding("a")).toBeDefined();
```
Comment (nicolo-ribaudo) [inline packages/babel-traverse/test/fixtures/scope/remove-nested-let-path/plugin.js:10]: If this line never runs it will not fail. We should push a comment in the output saying `"// a is defined? " + path.scope.getBinding("a")`, so that if the comment is missing the test fails.

Also, could you use an if to make this slightly easier to follow?
```js
const { value } = path.node.init;
if (value === 33) path.remove();
t.addComment(
  path.getProgramParent().path.node,
  "trailing",
  `// a is defined when visiting a=${value}? ${path.scope.hasBinding("a")}` 
);
``

File: packages/babel-traverse/test/fixtures/scope/remove-nested-let-path/plugin.js [hunk 2]
```diff
@@ -0,0 +1,18 @@
...
+        const { value } = path.node.init;
+
+        if (value === 33) path.remove();
+
+        types.addComment(
+          path.scope.getProgramParent().path.node,
+          "trailing",
+          `// a is defined when visiting a=${value}? ${path.scope.hasBinding("a")}`
+        );
+        ``;
```
Comment (nicolo-ribaudo) [inline packages/babel-traverse/test/fixtures/scope/remove-nested-let-path/plugin.js:14]:
```suggestion
```

:P

**Review by nicolo-ribaudo — APPROVED** [review]

**Review by JLHwung — CHANGES_REQUESTED** [review]
I think this bug should be fixed in `Scope#removeBinding`:

https://github.com/babel/babel/blob/de5541485a9ace552f97dca794cb7e7f8119dadd/packages/babel-traverse/src/scope/index.ts#L1369-L1373

The root cause of this bug is that currently the `scope.removeBinding()` method is not  idempotent: When we call `scope.removeBinding()` on the same scope twice, we end up removing the binding of the outer scope, because the `getBinding` returns the binding info of the outer scope after the inner binding is removed. 

To fix this, we can 

1. call `removeOwnBinding` on current scope if the current scope path is a function parent (a `var` scope). Test case: calling inner scope.removeBinding() twice from a var scope should not result to deletion of `a` in the upper scope:
```js
function outer() {
  var a;
  function inner() {
    var a;
  }
}
```
2. For let-scope, we can check the binding info. If the binding kind is `var`, we call removeOwnBinding on the scope's function parent, we should not call the removal on binding scope because it may be the outer var scope. e.g.
```js
function outer() {
  var a;
  function inner() {
    {
      let a;
    }
  }
}
```
3. For let-scope and other binding kinds, simply call `removeOwnBinding` on current scope.

The new approach will only manipulate current scope or its closest `var`-scope. With the new approach, the `path.remove()` should work as intended with current logic.

**Comment by liuxingbaoyu** [comment]
As I understand this method, it removes a binding that is accessible in the current scope.

I think this method is not expected to be idempotent because it takes a string parameter and when people call it twice, they will expect to remove two bindings named `x`.

If it were made idempotent, it would be a breaking change and break some uses. Also, it is confusing that `getBinding` can get a binding but cannot be removed using `removeBinding`.

Rather than making this method idempotent, I would rather people call this method deterministically to avoid removing unexpected variables.

**Comment by JLHwung** [comment]
> As I understand this method, it removes a binding that is accessible in the current scope.
> 
> I think this method is not expected to be idempotent because it takes a string parameter and when people call it twice, they will expect to remove two bindings named `x`.
> 
> If it were made idempotent, it would be a breaking change and break some uses. Also, it is confusing that `getBinding` can get a binding but cannot be removed using `removeBinding`.
> 
> Rather than making this method idempotent, I would rather people call this method deterministically to avoid removing unexpected variables.

Understood. The `getBinding/removeBinding` symmetry is persuasive. In that case:

https://github.com/babel/babel/blob/beb3d69fe9d650457555f0b6f9b9b579fb540f6a/packages/babel-traverse/src/path/removal.ts#L10-L26

How about moving the `!this.opts?.noScope` branch after the `if (_callRemovalHooks.call(this))` branch? Doing so will also pass all the tests in this PR. The rationale here is that if the hook delegate the removal to the node's parent, the parent `path.remove` should take care of the scope update as well. Other than deletion delegate, there are also some replacements involved in the removal hooks, such as unwrapping a single-element sequence expression, but none of these AST types introduce new bindings so `getBindingIdentifiers` will be empty anyway, which means it does not introduce any changes if `_removeFromScope` is not called for these cases.

I personally don't like a boolean flag in a hot path such as the `removeInternal` function, so I am trying my best to avoid it.

File: packages/babel-traverse/src/path/lib/removal-hooks.ts [hunk 3]
```diff
@@ -2,6 +2,7 @@
 
 import type NodePath from "../index.ts";
 import type * as t from "@babel/types";
+
```
Comment (liuxingbaoyu) [inline packages/babel-traverse/src/path/lib/removal-hooks.ts:5]:
```suggestion
```

**Review by JLHwung — APPROVED** [review]
