### PR TITLE
Fix unicode handling in generated function names

### LINKED ISSUE #13983: [Bug]: Bable can't Handle Unicode Encoding Function Name
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
var o = {
  "\uD835\uDC9C"() {}
};
```
Here is the Babel [REPL](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=false&spec=true&loose=true&code_lz=G4QwTgBA9hC8EG8BQEICIA6BXAIgDgGYBWbHAYQE4y0AKASkQF8lGBuIA&debug=false&forceAllTransforms=true&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cflow&prettier=false&targets=&version=7.16.4&externalPlugins=&assumptions=%7B%7D)

### Configuration file name

babel.config.js

### Configuration

```js
module.exports = function (api) {
  api.cache(true);
  const sourceType= "unambiguous";
  const presets = [
      ["@babel/preset-env", { "modules": false}]
  ];
  const plugins = [  ];

  return {
    sourceType,
    presets,
    plugins
  };
}
```

### Current behavior
Babel report a bug as follow
```bash
Can't reference '𝒜' as a bare identifier (This is an error on an internal node. Probably an internal error.)
```
### Expected behavior
I hope it can transform correctly and do not report errors.

### Environment

- babel 
- - ├── @babel/cli@7.16.0
- - ├── @babel/preset-env@7.16.0
- Node: [v16.11.1]
- npm version [8.0.0]
- os [ubuntu 20.04]

### Possible solution

_No response_

### Additional context

I run babel use cmd as follows
```bash
npx babel poc.js -o res/poc.js
```

### PR DESCRIPTION
**Pull request by The-x-Theorist**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #13983  
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

`transform-unicode-escapes` won't throw if a function name contain unicode encoding.
`transform-function-name` won't inject name if it's unicode encoding with `helper-function-name`. 

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14047"></a>

### CODE REVIEW

File: packages/babel-helper-function-name/src/index.ts [hunk 1]
```diff
@@ -223,6 +223,8 @@ export default function (
     name = id.name;
   }
 
+  if (isFunction(node) && /[\u{10000}-\u{10ffff}]/u.test(name)) return;
```
Comment (lightmare) [inline packages/babel-helper-function-name/src/index.ts:226]: Just curious: won't this get transpiled into an unnecessarily complex regex without unicode flag?
I mean, `/[\uD800-\uDFFF]/.test(name)` would work as well, right?

Comment (The-x-Theorist) [reply packages/babel-helper-function-name/src/index.ts:226]: @nicolo-ribaudo suggested me to use this #14047 in this issue.

Comment (nicolo-ribaudo) [reply packages/babel-helper-function-name/src/index.ts:226]: We transpile our code targeting Node.js 6, so we don't transpile the `u` flag. However yes, `/[\uD800-\uDFFF]/.test(name)` would work too.

Comment (JLHwung) [reply packages/babel-helper-function-name/src/index.ts:226]: BTW `/[\uD800-\uDFFF]/` are not equivalent to `/[\u{10000}-\u{10ffff}]/u` because lone surrogate can be a valid string literal. 🤦
```js
var o = {
  "\uD800"() {}
}
```

Comment (nicolo-ribaudo) [reply packages/babel-helper-function-name/src/index.ts:226]: Ok so `/[\uD800-\uDFFF]/` is the correct one in this case.

**Review by nicolo-ribaudo — COMMENTED** [review]
@The-x-Theorist Since many engines support unicode in identifiers, we can approach this problem as @JLHwung suggested in https://github.com/babel/babel/issues/13983#issuecomment-975683329:
1. The default function of `@babel/helper-function-name` takes an optional `supportsUnicodeId` parmeter, which defaults to `false` for better compatibility.
2. In `@babel/plugin-transform-function-name`, in the plugin factory function (the exported one) we add
   ```js
   const supportsUnicodeId = !isRequired("transform-unicode-escapes", api.targets());
   ```
   where `isRequired` is imported from `@babel/helper-compilation-targets`
3. When calling `nameFunction`, we pass the `supportsUnicodeId` flag.

You then must add one test specifying `targets: { "firefox": 50 }` and one with `targets: { "firefox": 60 }` in `options.json`.

File: packages/babel-helper-function-name/src/index.ts (hunk 1 above)
Comment (The-x-Theorist) [reply packages/babel-helper-function-name/src/index.ts:226]: Okay, I will change it to `/[\uD800-\uDFFF]/`.

File: packages/babel-plugin-transform-function-name/test/fixtures/function-name/unicode-encoding/options.json [hunk 2]
```diff
@@ -0,0 +1,4 @@
+{
+    "sourceType": "unambiguous",
```
[the remark this answers is not in the document]
Comment (The-x-Theorist) [reply packages/babel-plugin-transform-function-name/test/fixtures/function-name/unicode-encoding/options.json:2]: Okay, I will change it.

File: packages/babel-plugin-transform-function-name/test/fixtures/function-name/unicode-encoding/options.json [hunk 3]
```diff
@@ -0,0 +1,4 @@
...
+    "presets": ["env"]
```
[the remark this answers is not in the document]
Comment (The-x-Theorist) [reply packages/babel-plugin-transform-function-name/test/fixtures/function-name/unicode-encoding/options.json:3]: Okay, I will enable only the plugin.

**Comment by The-x-Theorist** [comment]
> @The-x-Theorist Since many engines support unicode in identifiers, we can approach this problem as @JLHwung suggested in [#13983 (comment)](https://github.com/babel/babel/issues/13983#issuecomment-975683329):
> 
> 1. The default function of `@babel/helper-function-name` takes an optional `supportsUnicodeId` parmeter, which defaults to `false` for better compatibility.
> 2. In `@babel/plugin-transform-function-name`, in the plugin factory function (the exported one) we add
>    ```js
>    const supportsUnicodeId = !isRequired("transform-unicode-escapes", api.targets());
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    where `isRequired` is imported from `@babel/helper-compilation-targets`
> 3. When calling `nameFunction`, we pass the `supportsUnicodeId` flag.
> 
> You then must add one test specifying `targets: { "firefox": 50 }` and one with `targets: { "firefox": 60 }` in `options.json`.
@nicolo-ribaudo I will do the same by adding `supportUnicodeId` in factory function in `transform-function-name` and adding a new test for a change.

File: packages/babel-plugin-transform-function-name/test/fixtures/function-name/unicode-encoding/options.json (hunk 3 above)
[the remark this answers is not in the document]
Comment (The-x-Theorist) [reply packages/babel-plugin-transform-function-name/test/fixtures/function-name/unicode-encoding/options.json:3]: If we don't use `preset "env"` it doesn't throw the error.

**Comment by The-x-Theorist** [comment]
> 2. In `@babel/plugin-transform-function-name`, in the plugin factory function (the exported one) we add
>    ```js
>    const supportsUnicodeId = !isRequired("transform-unicode-escapes", api.targets());
>    ```
>    where isRequired is imported from @babel/helper-compilation-targets


If we add `supportUnicodeId` const in callback of declare in `transform-function-name` its value never change when we pass it in `nameFunction` of `helper-function-name`, thus it gives same output for different targets.

**Comment by nicolo-ribaudo** [comment]
> If we add supportUnicodeId const in callback of declare in transform-function-name its value never change when we pass it in nameFunction of helper-function-name, thus it gives same output for different targets.

That's unexpected :thinking: Could you push your current code so that I can see why it's not working?

**Comment by The-x-Theorist** [comment]
> > If we add supportUnicodeId const in callback of declare in transform-function-name its value never change when we pass it in nameFunction of helper-function-name, thus it gives same output for different targets.
> 
> That's unexpected 🤔 Could you push your current code so that I can see why it's not working?

@nicolo-ribaudo  I pushed the code, If preset env is not added to the earlier test it doesn't throw the error and if targets are added in options it still doesn't throw the error even with preset env in options, I don't the problem behind this.

File: packages/babel-plugin-transform-function-name/test/fixtures/function-name/unicode-encoding/options.json (hunk 3 above)
[the remark this answers is not in the document]
Comment (JLHwung) [reply packages/babel-plugin-transform-function-name/test/fixtures/function-name/unicode-encoding/options.json:3]: I believe _the plugin_ refers to the `transform-function-name` here. There is an `options.json` already, so it suffices to remove `presets: ["env"]`.

File: packages/babel-plugin-transform-function-name/test/fixtures/function-name/unicode-id-not-supported/options.json [hunk 4]
```diff
@@ -0,0 +1,4 @@
+{
+    "plugins": ["transform-unicode-escapes"],
+    "targets": { "firefox": 60 }
```
Comment (JLHwung) [inline packages/babel-plugin-transform-function-name/test/fixtures/function-name/unicode-id-not-supported/options.json:3]: This test case is testing the behaviour of `transform-function-name` when unicode id is _not_ supported, however, `Firefox 60` does support unicode escapes. In fact it has supported since 53. So we should specify `Firefox 52` or other versions here.

File: packages/babel-plugin-transform-function-name/test/fixtures/function-name/unicode-encoding/input.js [hunk 5]
```diff
@@ -0,0 +1,3 @@
+var o = {
+  "\uD835\uDC9C"() {}
```
Comment (JLHwung) [inline packages/babel-plugin-transform-function-name/test/fixtures/function-name/unicode-encoding/input.js:2]: The new test cases use `shorthand-properties` which is not supported by `function-name`. We can either plug in `transform-shorthand-properties` or just use ObjectProperty instead.

```js
var o = {
  "\uD835\uDC9C": function () {}
}
```

When unicode escapes are supported, the output should be
```js
var o = {
  "\uD835\uDC9C": function 𝒜() {}
};
```

otherwise, the output should be

```js
var o = {
  "\uD835\uDC9C": function () {}
};
```
In this case the plugin does nothing.

File: packages/babel-helper-function-name/src/index.ts [hunk 6]
```diff
@@ -223,6 +225,10 @@ export default function (
     name = id.name;
   }
 
+  if (!supportUnicodeId && isFunction(node) && /[\uD800-\uDFFF]/.test(name)) {
+    return;
+  }
```
Comment (JLHwung) [inline packages/babel-helper-function-name/src/index.ts:230]: nit: This test is more expensive, consider place it after the `if (name === undefined)` check.

File: packages/babel-plugin-transform-function-name/package.json [hunk 7]
```diff
@@ -18,7 +18,8 @@
   ],
   "dependencies": {
     "@babel/helper-function-name": "workspace:^",
-    "@babel/helper-plugin-utils": "workspace:^"
+    "@babel/helper-plugin-utils": "workspace:^",
+    "@babel/helper-compilation-targets": "workspace:^"
```
Comment (JLHwung) [inline packages/babel-plugin-transform-function-name/package.json:22]: Please run `yarn install` when new dependencies are added and commit the changed yarn lock file.

File: packages/babel-plugin-transform-function-name/test/fixtures/function-name/unicode-id-not-supported/options.json (hunk 4 above)
Comment (The-x-Theorist) [reply packages/babel-plugin-transform-function-name/test/fixtures/function-name/unicode-id-not-supported/options.json:3]: Okay, I will use `Firefox 52` for not supported unicode escapes.

File: packages/babel-plugin-transform-function-name/test/fixtures/function-name/unicode-encoding/input.js (hunk 5 above)
Comment (The-x-Theorist) [reply packages/babel-plugin-transform-function-name/test/fixtures/function-name/unicode-encoding/input.js:2]: How can we plug-in `transform-shorthand-properties` in `transform-function-name`?

File: packages/babel-helper-function-name/src/index.ts (hunk 6 above)
Comment (The-x-Theorist) [reply packages/babel-helper-function-name/src/index.ts:230]: Okay, I will move it down.

File: packages/babel-plugin-transform-function-name/package.json (hunk 7 above)
Comment (The-x-Theorist) [reply packages/babel-plugin-transform-function-name/package.json:22]: Okay, I will run `yarn install` and commit the changes in yarn lock file.

File: packages/babel-plugin-transform-function-name/test/fixtures/function-name/unicode-id-not-supported/options.json (hunk 4 above)
Comment (The-x-Theorist) [reply packages/babel-plugin-transform-function-name/test/fixtures/function-name/unicode-id-not-supported/options.json:3]: After changing the targets it still gives the same result for different targets, I don't know what's happening?

Comment (The-x-Theorist) [reply packages/babel-plugin-transform-function-name/test/fixtures/function-name/unicode-id-not-supported/options.json:3]: `supportUnicodeId` is same for all the tests.

File: packages/babel-plugin-transform-function-name/test/fixtures/function-name/unicode-id-not-supported/options.json [hunk 8]
```diff
@@ -0,0 +1,4 @@
+{
+    "plugins": ["transform-unicode-escapes"],
```
Comment (JLHwung) [inline packages/babel-plugin-transform-function-name/test/fixtures/function-name/unicode-id-not-supported/options.json:2]:
```suggestion
    "plugins": ["transform-function-name", "transform-shorthand-properties"],
```
See also https://github.com/babel/babel/pull/14047/files/673c623ec94a8daf6bce79b87b5f1f6c8f5bca3d..af6dcf7895b497080d54557977792fe7d0d26571#r770063967 and https://github.com/babel/babel/pull/14047#discussion_r770077450

File: packages/babel-plugin-transform-function-name/test/fixtures/function-name/unicode-id-supported/options.json [hunk 9]
```diff
@@ -0,0 +1,4 @@
+{
+    "plugins": ["transform-unicode-escapes"],
+    "targets": { "firefox": 50 }
```
Comment (JLHwung) [inline packages/babel-plugin-transform-function-name/test/fixtures/function-name/unicode-id-supported/options.json:3]:
```suggestion
    "targets": { "firefox": 53 }
```

File: packages/babel-plugin-transform-function-name/test/fixtures/function-name/unicode-id-supported/options.json [hunk 10]
```diff
@@ -0,0 +1,4 @@
+{
+    "plugins": ["transform-unicode-escapes"],
```
Comment (JLHwung) [inline packages/babel-plugin-transform-function-name/test/fixtures/function-name/unicode-id-supported/options.json:2]:
```suggestion
    "plugins": ["transform-function-name", "transform-shorthand-properties"],
```

File: packages/babel-plugin-transform-function-name/test/fixtures/function-name/unicode-encoding/options.json [hunk 11]
```diff
@@ -0,0 +1,4 @@
+{
+    "plugins": ["transform-unicode-escapes"],
+    "presets": ["env"]
```
Comment (JLHwung) [inline packages/babel-plugin-transform-function-name/test/fixtures/function-name/unicode-encoding/options.json:3]:
```suggestion
    "plugins": ["transform-function-name", "transform-shorthand-properties"],
```

Comment (The-x-Theorist) [reply packages/babel-plugin-transform-function-name/test/fixtures/function-name/unicode-encoding/options.json]: Okay, I have changed the same in recent commit.

File: packages/babel-helper-function-name/src/index.ts (hunk 6 above)
Comment (JLHwung) [reply packages/babel-helper-function-name/src/index.ts:230]: Did you commit the changes?

File: packages/babel-plugin-transform-function-name/test/fixtures/function-name/unicode-encoding/options.json [hunk 12]
```diff
@@ -0,0 +1,3 @@
+{
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-function-name/test/fixtures/function-name/unicode-encoding/options.json:1]: You can delete this test, since we already test the explicit "is supported" and "is not supported" cases. This one is causing CI to fail because it is in the "is supported" category for Babel 8 and in the "is not supported" category for Babel 7.

File: packages/babel-plugin-transform-function-name/src/index.ts [hunk 13]
```diff
@@ -20,7 +25,7 @@ export default declare(api => {
       ObjectProperty(path) {
         const value = path.get("value");
         if (value.isFunction()) {
-          const newNode = nameFunction(value);
+          const newNode = nameFunction(value, null, supportUnicodeId);
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-function-name/src/index.ts:28]:
```suggestion
          const newNode = nameFunction(value, undefined, supportUnicodeId);
```
or
```suggestion
          const newNode = nameFunction(value, false, supportUnicodeId);
```

with `undefined` it will get the default value (`false`); with `null` it won't.

**Review by nicolo-ribaudo — COMMENTED** [review]
Don't forget about https://github.com/babel/babel/pull/14047/files#r770077973!

File: packages/babel-plugin-transform-function-name/test/fixtures/function-name/unicode-encoding/options.json (hunk 12 above)
Comment (The-x-Theorist) [reply packages/babel-plugin-transform-function-name/test/fixtures/function-name/unicode-encoding/options.json:1]: Okay, I will remove the following test.

File: packages/babel-plugin-transform-function-name/src/index.ts (hunk 13 above)
Comment (The-x-Theorist) [reply packages/babel-plugin-transform-function-name/src/index.ts:28]: I will the change the following in the next commit.

**Review by nicolo-ribaudo — APPROVED** [review]

**Comment by nicolo-ribaudo** [comment]
Thanks!
