### PR TITLE
 isConstantExpression should return true for immuable bindings

### LINKED ISSUE #8110: [plugin-proposal-class-properties] Unnecessary variable is injected for defined Symbol property name
## Bug Report

**Current Behavior**
I'm working with code where is a lot of private variables are defined with Symbols. Transpiling them with Babel I found the problem that `@babel/plugin-proposal-class-properties` for some reason creates another variables for every symbol I use to define my fields.

**Input Code**
- REPL or Repo link if applicable:
[Link](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=MYewdgzgLgBAZgSwKYBsAmMC8MDKBPAWwCMQUAKAckVTQoEoBuAKCeBQEMIIYBBGAbyYBIANrV0AXSwwAjAAZmAXyA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=true&fileSize=false&lineWrap=false&presets=es2015%2Ces2016%2Ces2017%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3&prettier=false&targets=&version=7.0.0-beta.49&envVersion=7.0.0-beta.49)
```js
const field = Symbol('field');

class A {
  [field] = 10;
}
```

**Expected behavior/code**
Expect output to not have additional `var _field = field` line because it is unnecessary.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "plugins": [
    ["@babel/plugin-proposal-class-properties", {"loose": true}],
  ],
  "presets": [
    ["@babel/preset-env", {
      "modules": false,
      "shippedProposals": true,
      "targets": {
        "browsers": "last 1 chrome version",
      },
    }],
  ],
}
```

**Environment**
- Babel version(s): v7.0.0-beta.49
- Node/npm version: node v10.3.0/ npm v6.0.1
- OS: Windows 10
- Monorepo: Lerna 
- How you are using Babel: `rollup-plugin-babel@0.59.1`

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

Output code:
```js
"use strict";

function _instanceof(left, right) { if (right != null && typeof Symbol !== "undefined" && right[Symbol.hasInstance]) { return right[Symbol.hasInstance](left); } else { return left instanceof right; } }

function _classCallCheck(instance, Constructor) { if (!_instanceof(instance, Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _defineProperty(obj, key, value) { if (key in obj) { Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true }); } else { obj[key] = value; } return obj; }

var field = Symbol('field');
var _field = field; // the unnecessary line 

var A = function A() {
  _classCallCheck(this, A);

  _defineProperty(this, _field, 10);
};
```

I'm not sure if this issue is connected with #6916

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #8110
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR         | 
| Any Dependency Changes?  |
| License                  | MIT

The tests in the class-properties plugin were not run because they weren't in a subfolder. They look deleted and created just because I both renamed and regenerated them.

### CODE REVIEW

File: packages/babel-traverse/src/path/introspection.js [hunk 1]
```diff
@@ -402,10 +402,7 @@ export function _resolve(dangerous?, resolved?): ?NodePath {
 export function isConstantExpression() {
   if (this.isIdentifier()) {
     const binding = this.scope.getBinding(this.node.name);
-    if (!binding) {
-      return false;
-    }
-    return binding.constant && binding.path.get("init").isConstantExpression();
+    return binding && binding.constant;
```
Comment (xtuc) [inline packages/babel-traverse/src/path/introspection.js]: I'm personally not a fan of that, I would prefer something like:

```js
if (!binding) { return false }
return binding.constant;
```

Comment (xtuc) [reply packages/babel-traverse/src/path/introspection.js]: @nicolo-ribaudo the styling is wrong here, prettier will probably fix it for you?

Comment (nicolo-ribaudo) [reply packages/babel-traverse/src/path/introspection.js]: Actually prettier accepts it. I think that it is ok to have a single statement on the sam line of the if.
