### PR TITLE
Fix identation with empty leading ObjectTypeProperty

### LINKED ISSUE #4856: [Generate] ObjectTypeAnnotation without ObjectTypeProperty output miss a line break
```js
generate(
  t.typeAlias(
    t.identifier('T'),
    null,
    t.objectTypeAnnotation([], [
      t.objectTypeIndexer(
        t.identifier('key'),
        t.anyTypeAnnotation(),
        t.identifier('Test'),
      ),
    ]),
  )
).code;
```
Now output
```js
type T = { [key: any]: Test;
};
```
Expected Output
```
type T = { 
  [key: any]: Test;
};
```

| software         | version
| ---------------- | -------
| Babel            |  6.18.x
| node             |  7.1
| npm              |  3.9.x
| Operating System | MacOS

### PR DESCRIPTION
**Pull request by existentialism**
| Q                 | A 
| ----------------- | ---
| Bug fix?          | yes
| Breaking change?  | no
| New feature?      | no
| Deprecations?     | no
| Spec compliancy?  | no
| Tests added/pass? | yes
| Fixed tickets     | Fixes #4856
| License           | MIT
| Doc PR            | 
| Dependency Changes|

### CODE REVIEW

File: packages/babel-generator/src/generators/flow.js [hunk 1]
```diff
@@ -270,6 +270,9 @@ export function ObjectTypeAnnotation(node: Object) {
     this.space();
 
     this.printJoin(props, node, {
+      addNewlines(leading) {
```
Comment (hzoo) [inline packages/babel-generator/src/generators/flow.js]: Unrelated to this particular pr, but does the `if (props.length) {` really do anything since it can be `[]`?

Comment (existentialism) [inline packages/babel-generator/src/generators/flow.js]: I guess all it really does is prevent spaces from getting generated if there is no body:

```
function foo(): {} {}
declare class A<T = string> {};
```
vs.
```
function foo(): { } {}
declare class A<T = string> { };
```

If that isn't a concern, I can remove and update tests?

Comment (hzoo) [inline packages/babel-generator/src/generators/flow.js]: Yeah it looks good nvm!

**Comment by hzoo** [comment]
Thanks again! Keep up the great work (are you in our slack?)

**Comment by existentialism** [comment]
@hzoo thanks, and yep!
