### PR TITLE
Disallow `#a in #b in c` and similar expressions

### LINKED ISSUE #13726: [Bug]: Private Brand Check incorrectly allowed as RHS of `in` operator
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

Found this while reading https://github.com/evanw/esbuild/releases/tag/v0.12.25 (esbuild continues to have wonderful changelogs):

```
class Foo {
  #a;
  #b;
  constructor(c) {
    #a in #b in c
  }
}
```

Because of the way the `in` operator works, this is parsing the same as `(#a in #b) in c`, which isn't a valid program.

### Configuration file name

_No response_

### Configuration

Only default settings are needed.

```
{}
```

### Current and expected behavior

This should throw a parse error.

### Environment

Babel 7.15.3

### Possible solution

This issue is in https://github.com/babel/babel/blob/b335dcc67fa1233ff3a76cd0e8a06922e14c8587/packages/babel-parser/src/parser/expression.js#L1219-L1226. We're not checking whether we're already in the RHS of an `in` expression.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #13726
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/13727"></a>

### CODE REVIEW

**Review by jridgewell — APPROVED** [review]

File: packages/babel-parser/src/parser/expression.js [hunk 1]
```diff
@@ -387,11 +395,34 @@ export default class ExpressionParser extends LValParser {
...
+      if (
+        minPrec >= tt._in.binop ||
+        !this.prodParam.hasIn ||
+        !this.match(tt._in)
+      ) {
+        this.raise(
+          left.start,
+          Errors.PrivateInExpectedIn,
+          this.getPrivateNameSV(left),
+        );
```
Comment (JLHwung) [inline packages/babel-parser/src/parser/expression.js:420]:
```suggestion
        this.raise(start, Errors.PrivateInExpectedIn, value);
```

File: packages/babel-parser/src/parser/expression.js [hunk 2]
```diff
@@ -387,11 +395,34 @@ export default class ExpressionParser extends LValParser {
   // operator that has a lower precedence than the set it is parsing.
 
   parseExprOp(
-    left: N.Expression,
+    left: N.Expression | N.PrivateName,
     leftStartPos: number,
     leftStartLoc: Position,
     minPrec: number,
   ): N.Expression {
+    if (this.isPrivateName(left)) {
```
Comment (JLHwung) [inline packages/babel-parser/src/parser/expression.js:403]: We should forbid parenthesized private identifiers:
```js
(#a) in v
```

**Review by sosukesuzuki — APPROVED** [review]

File: packages/babel-parser/src/parser/expression.js (hunk 2 above)
Comment (nicolo-ribaudo) [reply packages/babel-parser/src/parser/expression.js:403]: It's already forbidden; there is a test at https://github.com/babel/babel/blob/7459038db8476e6a5159af012c5da26b342e1d21/packages/babel-parser/test/fixtures/experimental/private-in/private-in-parenthesized/input.js.

It throws in the check at line 1249.

**Comment by JLHwung** [comment]
Can you add a new test case?
```js
class C {
  #x;
  async test() {
    await #x in this
  }
}
```

It was parsed successfully but should throw, probably fixed in this PR.

File: packages/babel-parser/src/parser/expression.js [hunk 3]
```diff
@@ -504,7 +531,7 @@ export default class ExpressionParser extends LValParser {
     const startLoc = this.state.startLoc;
 
     return this.parseExprOp(
-      this.parseMaybeUnary(),
+      this.parseMaybeUnaryOrPrivate(),
```
Comment (JLHwung) [inline packages/babel-parser/src/parser/expression.js:534]: This change should also be applied to `parseFSharpPipelineBody` since the pipeline body descends to LogicalORExpression which includes private in. https://valtech-nyc.github.io/proposal-fsharp-pipelines/#prod-PipelineExpression

Comment (nicolo-ribaudo) [reply packages/babel-parser/src/parser/expression.js:534]: It's done at https://github.com/babel/babel/pull/13727/files#diff-f876d1e822b0978b9c6de30b9fc6e96e2309c853a694feea274ecccf1d1d9f15R2935.

**Review by JLHwung — APPROVED** [review]
