### PR TITLE
Lazily initialize and cache constant JSX elements

### LINKED ISSUE #6751: transform-react-constant-elements may hoist vars into unreachable code
In certain circumstances involving a combination of locally scoped components and hoisted function declarations written inside unreachable code, the transform may write the hoisted jsx inside the unreachable code region.

I have placed the code in this report in astexplorer so the input/output can be played with (transform copied from `master`):

http://astexplorer.net/#/gist/a03cd893007f6c4ebb6a2bc7e56ef6f3/ce2d32e0aa49941e47fd1761971c76bedff81fc1

### Input Code

```jsx
function AComponent () {
  const CComponent = () => <div/>
  return <BComponent/>
    
  function BComponent () {
    return <CComponent/>
  }
}
```

This example is slightly contrived as the actual locally-scoped components in the RWC are function evaluation results.

### Output Code

```jsx
var _ref = <div/>;
function AComponent () {
  const CComponent = () => _ref
  return <BComponent/>

  var _ref2 = <CComponent/>;

  function BComponent () {
    return _ref2;
  }
}
```

Note how the `_ref2` is declared after the return and, thus, is unreachable code. This will cause React to throw at runtime as `BComponent` returns `undefined`.

(This would rightly be a `ReferenceError` if the transform used `let`/`const` instead of `var`)

---

This may be somewhat low priority as _actual_ components are never written with nested components inside their render functions; this case in RWC is a JSX factory function that just generates static JSX that is only rendered once.

### LINKED ISSUE #7565: transform-react-constant-elements breaks React.createElement compilation
This is a bug report

### Input Code

Simplified version of the problematic file that still crashes:

```js
// @flow

import React from 'react';
import { Switch, Route } from 'react-router-dom';

import SubscriberRoutes from './SubscriberRoutes';
import NotFoundPage from '../App/NotFoundPage';

type Props = {
  modules: string[],
};

export default function AppRoutes ({ modules }: Props) {
  return (
    <Switch>
      <Route
        render={() => <SubscriberRoutes modules={modules} />}
      />
      <Route component={NotFoundPage} />
    </Switch>
  );
}
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

I'm compiling with Webpack and I have no `.babelrc`. This is my config that I pass to `babel-loader`:

```js
{
  presets: [
    ['env', { modules: false }],
    'stage-2',
    'react',
  ],
  plugins: [
    'transform-react-constant-elements',
  ],
}
```

### Expected Behavior

I think it should compile. Have I done anything wrong or is this a bug? Removing `transform-react-constant-elements` makes it work.

### Current Behavior

```
ERROR in ./src/components/Routes/AppRoutes.js
Module parse failed: Unexpected token (9:34)
You may need an appropriate loader to handle this file type.
| var _ref3 = React.createElement(Route, { component: NotFoundPage });
|
| export default function AppRoutes((_temp = _ref, _ref2 = <SubscriberRoutes modules={modules} />, _temp)) {
|   var _temp, _ref2;
|
 @ ./src/components/Login/LoginWall.js 5:0-44 9:32-41
 @ ./src/components/App/App.js
 @ ./src/index.js
 @ multi babel-polyfill ./src
```

### Context

I'm trying to build my app with Webpack.

### Your Environment

```
yarn list --pattern babel
yarn list v1.5.1
├─ @babel/code-frame@7.0.0-beta.40
├─ @babel/generator@7.0.0-beta.40
├─ @babel/helper-function-name@7.0.0-beta.40
├─ @babel/helper-get-function-arity@7.0.0-beta.40
├─ @babel/highlight@7.0.0-beta.40
├─ @babel/template@7.0.0-beta.40
├─ @babel/traverse@7.0.0-beta.40
├─ @babel/types@7.0.0-beta.40
├─ babel-code-frame@6.26.0
├─ babel-core@6.26.0
├─ babel-eslint@8.2.2
├─ babel-generator@6.26.1
├─ babel-helper-bindify-decorators@6.24.1
├─ babel-helper-builder-binary-assignment-operator-visitor@6.24.1
├─ babel-helper-builder-react-jsx@6.26.0
├─ babel-helper-call-delegate@6.24.1
├─ babel-helper-define-map@6.26.0
├─ babel-helper-explode-assignable-expression@6.24.1
├─ babel-helper-explode-class@6.24.1
├─ babel-helper-function-name@6.24.1
├─ babel-helper-get-function-arity@6.24.1
├─ babel-helper-hoist-variables@6.24.1
├─ babel-helper-optimise-call-expression@6.24.1
├─ babel-helper-regex@6.26.0
├─ babel-helper-remap-async-to-generator@6.24.1
├─ babel-helper-replace-supers@6.24.1
├─ babel-helpers@6.24.1
├─ babel-jest@22.4.1
├─ babel-loader@7.1.4
├─ babel-messages@6.23.0
├─ babel-plugin-check-es2015-constants@6.22.0
├─ babel-plugin-istanbul@4.1.5
├─ babel-plugin-jest-hoist@22.4.1
├─ babel-plugin-react-remove-properties@0.2.5
├─ babel-plugin-syntax-async-functions@6.13.0
├─ babel-plugin-syntax-async-generators@6.13.0
├─ babel-plugin-syntax-class-constructor-call@6.18.0
├─ babel-plugin-syntax-class-properties@6.13.0
├─ babel-plugin-syntax-decorators@6.13.0
├─ babel-plugin-syntax-dynamic-import@6.18.0
├─ babel-plugin-syntax-exponentiation-operator@6.13.0
├─ babel-plugin-syntax-export-extensions@6.13.0
├─ babel-plugin-syntax-flow@6.18.0
├─ babel-plugin-syntax-jsx@6.18.0
├─ babel-plugin-syntax-object-rest-spread@6.13.0
├─ babel-plugin-syntax-trailing-function-commas@6.22.0
├─ babel-plugin-transform-async-generator-functions@6.24.1
├─ babel-plugin-transform-async-to-generator@6.24.1
├─ babel-plugin-transform-class-constructor-call@6.24.1
├─ babel-plugin-transform-class-properties@6.24.1
├─ babel-plugin-transform-decorators@6.24.1
├─ babel-plugin-transform-es2015-arrow-functions@6.22.0
├─ babel-plugin-transform-es2015-block-scoped-functions@6.22.0
├─ babel-plugin-transform-es2015-block-scoping@6.26.0
├─ babel-plugin-transform-es2015-classes@6.24.1
├─ babel-plugin-transform-es2015-computed-properties@6.24.1
├─ babel-plugin-transform-es2015-destructuring@6.23.0
├─ babel-plugin-transform-es2015-duplicate-keys@6.24.1
├─ babel-plugin-transform-es2015-for-of@6.23.0
├─ babel-plugin-transform-es2015-function-name@6.24.1
├─ babel-plugin-transform-es2015-literals@6.22.0
├─ babel-plugin-transform-es2015-modules-amd@6.24.1
├─ babel-plugin-transform-es2015-modules-commonjs@6.26.0
├─ babel-plugin-transform-es2015-modules-systemjs@6.24.1
├─ babel-plugin-transform-es2015-modules-umd@6.24.1
├─ babel-plugin-transform-es2015-object-super@6.24.1
├─ babel-plugin-transform-es2015-parameters@6.24.1
├─ babel-plugin-transform-es2015-shorthand-properties@6.24.1
├─ babel-plugin-transform-es2015-spread@6.22.0
├─ babel-plugin-transform-es2015-sticky-regex@6.24.1
├─ babel-plugin-transform-es2015-template-literals@6.22.0
├─ babel-plugin-transform-es2015-typeof-symbol@6.23.0
├─ babel-plugin-transform-es2015-unicode-regex@6.24.1
├─ babel-plugin-transform-exponentiation-operator@6.24.1
├─ babel-plugin-transform-export-extensions@6.22.0
├─ babel-plugin-transform-flow-strip-types@6.22.0
├─ babel-plugin-transform-object-rest-spread@6.26.0
├─ babel-plugin-transform-react-constant-elements@6.23.0
├─ babel-plugin-transform-react-display-name@6.25.0
├─ babel-plugin-transform-react-inline-elements@6.22.0
├─ babel-plugin-transform-react-jsx-self@6.22.0
├─ babel-plugin-transform-react-jsx-source@6.22.0
├─ babel-plugin-transform-react-jsx@6.24.1
├─ babel-plugin-transform-react-remove-prop-types@0.4.13
├─ babel-plugin-transform-regenerator@6.26.0
├─ babel-plugin-transform-strict-mode@6.24.1
├─ babel-polyfill@6.26.0
├─ babel-preset-env@1.6.1
├─ babel-preset-es2015@6.24.1
├─ babel-preset-flow@6.23.0
├─ babel-preset-jest@22.4.1
├─ babel-preset-react@6.24.1
├─ babel-preset-stage-1@6.24.1
├─ babel-preset-stage-2@6.24.1
├─ babel-preset-stage-3@6.24.1
├─ babel-register@6.26.0
├─ babel-runtime@6.26.0
├─ babel-template@6.26.0
├─ babel-traverse@6.26.0
└─ babel-types@6.26.0
```

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0
| Webpack             |  4.1.1
| node             |  9.7.1
| yarn              |  1.5.1
| Operating System | macOS 10.13.3

### LINKED ISSUE #7610: Bug with babel-plugin-transform-react-constant-elements
Using `babel-plugin-transform-react-constant-elements` version `6.23.0`, i'm getting an error which is not transforming well the code and webpack explodes.

Using the following babel config:
```js
"client_prod": {
            "presets": [
                "env",
                "react",
                "stage-0"
            ],
            "plugins": [
                "transform-react-constant-elements",
                "transform-react-inline-elements"
            ]
        }
```

With the following code:
```js
import React from 'react';
import _ from 'underscore';
import PropTypes from 'prop-types';
import Assets from '../../../../../assets.json';
import { translationsHelper } from '../../../../../../helpers';
import { FormattedMessage as Translation } from 'react-intl';

import { Card, Button, css as uicss } from 'panamera-react-ui';
const { grid } = uicss;

import CreditsPackagesList from '../../../../../components/Payment/CreditsPackagesList/CreditsPackagesList';
import css from '../../BuyCredits.scss';

const SelectPackage = ({ wallet, packages, selectedPackage, onChange, onClick }, { config }) => {
    const brand = config.get('theme', 'brand');

    return (
        <div className={ `${grid.row} ${css.buyCredits}` }>
            <div className={ `${grid.col} ${grid.xl8} ${grid.l12} ${grid.m12} ${grid.s12} ${grid.margin}` }>
                <Translation id="paymentWalletGetMoreCreditsTitle">
                    { formattedVal => (
                        <Card className={ css.creditsList }>
                            <h1>{formattedVal}</h1>
                            <div className={ css.tableContainer }>
                                <CreditsPackagesList
                                    packagesList={ packages }
                                    onChange={ onChange }
                                    selectedPackage={ selectedPackage } />
                            </div>
                            <Translation id="payment_wallet_get_more_credits_button">
                                { formattedVal => (
                                    <Button type={ _.isEmpty(selectedPackage) ? 'btnDisabled' : 'btnMain' }
                                            className={ css.continueBtn }
                                            onClick={ onClick }>{formattedVal}</Button>
                                ) }
                            </Translation>
                        </Card>
                    )}
                </Translation>
            </div>
            <div className={ `${grid.col} ${grid.xl4} ${grid.l4} ${grid.m12} ${grid.s12} ${grid.margin} ${css.rightColumn}` }>
                <p className={ css.purchSumHeading }><Translation id="paymentWalletGetMoreCreditsPurchaseDetailTitle" /></p>
                <Card className={ css.widgetCard }>
                    <img src={ `/assets/${Assets[`${brand.toLowerCase()}_credits_small.png`]}` } alt={ brand } />
                    <div className={ css.widgetCardContent }>
                        <span>{ wallet.amount }</span>
                        <p>{ translationsHelper.render('myOlxCreditsSideBarButton', { brand }) }</p>
                    </div>
                </Card>
            </div>
        </div>
    );
};

SelectPackage.contextTypes = {
    config: PropTypes.object
};

SelectPackage.propTypes = {
    wallet: PropTypes.object,
    packages: PropTypes.array,
    selectedPackage: PropTypes.object,
    onChange: PropTypes.func,
    onClick: PropTypes.func
};

SelectPackage.defaultProps = {
    onChange: () => {},
    onClick: () => {}
};

export default SelectPackage;
```

**OUTPUT:**
```js
'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _react = require('react');

var _react2 = _interopRequireDefault(_react);

var _underscore = require('underscore');

var _underscore2 = _interopRequireDefault(_underscore);

var _propTypes = require('prop-types');

var _propTypes2 = _interopRequireDefault(_propTypes);

var _assets = require('../../../../../assets.json');

var _assets2 = _interopRequireDefault(_assets);

var _helpers = require('../../../../../../helpers');

var _reactIntl = require('react-intl');

var _panameraReactUi = require('panamera-react-ui');

var _CreditsPackagesList = require('../../../../../components/Payment/CreditsPackagesList/CreditsPackagesList');

var _CreditsPackagesList2 = _interopRequireDefault(_CreditsPackagesList);

var _BuyCredits = require('../../BuyCredits.scss');

var _BuyCredits2 = _interopRequireDefault(_BuyCredits);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var grid = _panameraReactUi.css.grid;

var _ref4 = _react2.default.createElement(_reactIntl.FormattedMessage, { id: 'paymentWalletGetMoreCreditsPurchaseDetailTitle' });

var SelectPackage = function SelectPackage((_temp = _ref, _ref3 = <_CreditsPackagesList2.default packagesList={packages} onChange={onChange} selectedPackage={selectedPackage} />, _temp), _ref2) {
    var _temp, _ref3;

    var wallet = _ref.wallet,
        packages = _ref.packages,
        selectedPackage = _ref.selectedPackage,
        onChange = _ref.onChange,
        onClick = _ref.onClick;
    var config = _ref2.config;

    var brand = config.get('theme', 'brand');

    return _react2.default.createElement(
        'div',
        { className: grid.row + ' ' + _BuyCredits2.default.buyCredits },
        _react2.default.createElement(
            'div',
            { className: grid.col + ' ' + grid.xl8 + ' ' + grid.l12 + ' ' + grid.m12 + ' ' + grid.s12 + ' ' + grid.margin },
            _react2.default.createElement(
                _reactIntl.FormattedMessage,
                { id: 'paymentWalletGetMoreCreditsTitle' },
                function (formattedVal) {
                    return _react2.default.createElement(
                        _panameraReactUi.Card,
                        { className: _BuyCredits2.default.creditsList },
                        _react2.default.createElement(
                            'h1',
                            null,
                            formattedVal
                        ),
                        _react2.default.createElement(
                            'div',
                            { className: _BuyCredits2.default.tableContainer },
                            _ref3
                        ),
                        _react2.default.createElement(
                            _reactIntl.FormattedMessage,
                            { id: 'payment_wallet_get_more_credits_button' },
                            function (formattedVal) {
                                return _react2.default.createElement(
                                    _panameraReactUi.Button,
                                    { type: _underscore2.default.isEmpty(selectedPackage) ? 'btnDisabled' : 'btnMain',
                                        className: _BuyCredits2.default.continueBtn,
                                        onClick: onClick },
                                    formattedVal
                                );
                            }
                        )
                    );
                }
            )
        ),
        _react2.default.createElement(
            'div',
            { className: grid.col + ' ' + grid.xl4 + ' ' + grid.l4 + ' ' + grid.m12 + ' ' + grid.s12 + ' ' + grid.margin + ' ' + _BuyCredits2.default.rightColumn },
            _react2.default.createElement(
                'p',
                { className: _BuyCredits2.default.purchSumHeading },
                _ref4
            ),
            _react2.default.createElement(
                _panameraReactUi.Card,
                { className: _BuyCredits2.default.widgetCard },
                _react2.default.createElement('img', { src: '/assets/' + _assets2.default[brand.toLowerCase() + '_credits_small.png'], alt: brand }),
                _react2.default.createElement(
                    'div',
                    { className: _BuyCredits2.default.widgetCardContent },
                    _react2.default.createElement(
                        'span',
                        null,
                        wallet.amount
                    ),
                    _react2.default.createElement(
                        'p',
                        null,
                        _helpers.translationsHelper.render('myOlxCreditsSideBarButton', { brand: brand })
                    )
                )
            )
        )
    );
};

SelectPackage.contextTypes = {
    config: _propTypes2.default.object
};

SelectPackage.propTypes = {
    wallet: _propTypes2.default.object,
    packages: _propTypes2.default.array,
    selectedPackage: _propTypes2.default.object,
    onChange: _propTypes2.default.func,
    onClick: _propTypes2.default.func
};

SelectPackage.defaultProps = {
    onChange: function onChange() {},
    onClick: function onClick() {}
};

exports.default = SelectPackage;
```

The problem comes when is trying to transform 
```js
<CreditsPackagesList
                                    packagesList={ packages }
                                    onChange={ onChange }
                                    selectedPackage={ selectedPackage } />
```

If i define a const previous the render, and later i include it in the render it works well...

Like this:
```js
import React from 'react';
import _ from 'underscore';
import PropTypes from 'prop-types';
import Assets from '../../../../../assets.json';
import { translationsHelper } from '../../../../../../helpers';
import { FormattedMessage as Translation } from 'react-intl';

import { Card, Button, css as uicss } from 'panamera-react-ui';
const { grid } = uicss;

import CreditsPackagesList from '../../../../../components/Payment/CreditsPackagesList/CreditsPackagesList';
import css from '../../BuyCredits.scss';

const SelectPackage = ({ wallet, packages, selectedPackage, onChange, onClick }, { config }) => {
    const brand = config.get('theme', 'brand');
    const creditsPackagesList = (
      <CreditsPackagesList
          packagesList={ packages }
          onChange={ onChange }
          selectedPackage={ selectedPackage } />
    );

    return (
        <div className={ `${grid.row} ${css.buyCredits}` }>
            <div className={ `${grid.col} ${grid.xl8} ${grid.l12} ${grid.m12} ${grid.s12} ${grid.margin}` }>
                <Translation id="paymentWalletGetMoreCreditsTitle">
                    { formattedVal => (
                        <Card className={ css.creditsList }>
                            <h1>{formattedVal}</h1>
                            <div className={ css.tableContainer }>
                              { creditsPackagesList }
                            </div>
                            <Translation id="payment_wallet_get_more_credits_button">
                                { formattedVal => (
                                    <Button type={ _.isEmpty(selectedPackage) ? 'btnDisabled' : 'btnMain' }
                                            className={ css.continueBtn }
                                            onClick={ onClick }>{formattedVal}</Button>
                                ) }
                            </Translation>
                        </Card>
                    )}
                </Translation>
            </div>
            <div className={ `${grid.col} ${grid.xl4} ${grid.l4} ${grid.m12} ${grid.s12} ${grid.margin} ${css.rightColumn}` }>
                <p className={ css.purchSumHeading }><Translation id="paymentWalletGetMoreCreditsPurchaseDetailTitle" /></p>
                <Card className={ css.widgetCard }>
                    <img src={ `/assets/${Assets[`${brand.toLowerCase()}_credits_small.png`]}` } alt={ brand } />
                    <div className={ css.widgetCardContent }>
                        <span>{ wallet.amount }</span>
                        <p>{ translationsHelper.render('myOlxCreditsSideBarButton', { brand }) }</p>
                    </div>
                </Card>
            </div>
        </div>
    );
};

SelectPackage.contextTypes = {
    config: PropTypes.object
};

SelectPackage.propTypes = {
    wallet: PropTypes.object,
    packages: PropTypes.array,
    selectedPackage: PropTypes.object,
    onChange: PropTypes.func,
    onClick: PropTypes.func
};

SelectPackage.defaultProps = {
    onChange: () => {},
    onClick: () => {}
};

export default SelectPackage;
```

### LINKED ISSUE #7726: babel-loader Transpilation Issue "Module Parse Failed"
## Bug Report
When attempting to build out production artifacts via webpack and babel a consistent failure in babel-loader presents itself.

The problem never presented when using our dev build configurations and in exploring what could be causing the issue I discovered that the "[transform-react-constant-elements](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-react-constant-elements)" plugin appears to be the "where" for one of my components. Although I still cannot fathom the "why" this is what is breaking my build process.

Removing this plugin from the production config in .babelrc seems to fix the issue for now, but I would ideally like to leave this plugin as part of our production build.

I have already attempted the solution found in [#5325](https://github.com/babel/babel/issues/5325#issuecomment-292064058) and order of my plugins does not seem to affect the resulting error.

Also, to note, this exact setup/configuration below was working ~2 weeks ago without issue. Have not updated versions of any dependencies since. Just the usual refactoring of code during dev process.

### Input Code

The particular component it is failing on in the error message: [SearchHome Gist](https://gist.github.com/r-mc2/563bc148939ca607320d74b334ef0fd4)

#### .babelrc
```js
{
  "env": {
    "development": {
      "presets": [
        "env",
        "react",
        "react-hmre",
        "stage-1"
      ]
    },
    "production": {
      "presets": [
        ["env", {
          "es2015": { "modules": false },
          "targets": {
            "ie": 9,
            "uglify": true
          }
        }],
        "react",
        "stage-1"
      ],
      "plugins": [
        "transform-react-constant-elements",
        "transform-react-remove-prop-types"
      ]
    }
  }
}
```

#### package.json (relevant dependencies)
```js
"devDependencies": {
    "...": "...",
    "babel-cli": "6.24.1",
    "babel-core": "6.25.0",
    "babel-eslint": "7.2.3",
    "babel-jest": "20.0.3",
    "babel-loader": "7.1.1",
    "babel-plugin-transform-react-constant-elements": "6.23.0",
    "babel-plugin-transform-react-remove-prop-types": "0.4.6",
    "babel-polyfill": "6.23.0",
    "babel-preset-env": "1.6.0",
    "babel-preset-react": "6.24.1",
    "babel-preset-react-hmre": "1.1.1",
    "babel-preset-stage-1": "6.24.1",
    "...": "...",
    "extract-text-webpack-plugin": "3.0.1",
    "html-webpack-plugin": "2.29.0",
    "webpack": "3.1.0",
    "webpack-bundle-analyzer": "2.8.2",
    "webpack-dev-middleware": "1.11.0",
    "webpack-hot-middleware": "2.18.2",
    "webpack-md5-hash": "0.0.5",
    "..."
}
```

#### webpack.prod.js (relevant module section)
```js
module: {
  rules: [{
    test: /\.jsx?$/,
    exclude: /node_modules/,
    use: ["babel-loader"]
  },
  {
  	etc: "..."
  }]
}
```

### Expected Behavior
Babel & it's plugins run as usual and produce a transpiled set of code ready for production use.

### Current Behavior
Error during transpilation process:
```bash
ERROR in ./src/components/SearchHome.js
Module parse failed: /<proj_home>/node_modules/babel-loader/lib/index.js!/<proj_home>/src/components/SearchHome.js Unexpected token (122:52)
You may need an appropriate loader to handle this file type.
| );
| 
| var HomePage = exports.HomePage = function HomePage((_temp2 = (_temp = _ref, _ref3 = <_SearchResults2.default resultList={resultList} />, _temp), _ref5 = <_SearchResults2.default resultList={resultList} />, _temp2)) {
|   var _temp, _ref3, _temp2, _ref5;
| 
 @ ./src/components/App.js 19:18-41
 @ ./src/components/Root.js
 @ ./src/index.js
```
(
Not entirely sure what it doesn't like based on the error itself. The line and column it refers to is midway through a line of code that's already been partially transpiled.
```js
_react2.default.createElement(_SearchResults2.default, { resultList: resultList })
//                                     Here-ish?^^
```
)

### Context
Attempting to build out production-ready transpiled "bundle.js" file via Babel & Webpack.

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            | (see above package.json) 
| node             | v9.7.1
| npm              | v5.6.0
| yarn              | v1.5.1
| Operating System | OSX (v10.13.3)

### LINKED ISSUE #9965: [react-constant-elements] Unexpected token. Hoisting elements into imports, breaking source
## Bug Report

I really should make repro's, but I'm sort of overextended even just opening tickets. This one though it happening to me on latest everything:

```
ERROR in ./src/pages/OrbitPage/OrbitHeader.tsx 14:22
Module parse failed: Unexpected token (14:22)
You may need an appropriate loader to handle this file type.
| import { OrbitSpaceSwitch } from '../../views/OrbitSpaceSwitch';
| import { OrbitHeaderInput } from './OrbitHeaderInput';
> import { _ref2 } from (HeaderButtonPassProps, {}, void 0, _jsx(BackButton, {}), _jsx(OrbitHeaderMenu, {}));
| from;
| './OrbitHeaderMenu';
 @ ./src/pages/OrbitPage/OrbitPage.tsx 23:0-44 58:17-28
 @ ./src/OrbitRoot.tsx
 @ ./src/main.tsx
```

from a source file that roughly has:

```ts
import { invertLightness } from '@o/color'
import { Icon, useActiveAppsSorted, useLocationLink } from '@o/kit'
import { isEditing } from '@o/stores'
import { BorderBottom, Button, ButtonProps, Popover, PopoverProps, Row, Space, SurfacePassProps, View } from '@o/ui'
import { FullScreen, gloss, useTheme } from 'gloss'
import React, { forwardRef, memo } from 'react'

import { useStores } from '../../hooks/useStores'
import { useOm } from '../../om/om'
import { OrbitSpaceSwitch } from '../../views/OrbitSpaceSwitch'
import { OrbitHeaderInput } from './OrbitHeaderInput'
import { OrbitHeaderMenu } from './OrbitHeaderMenu'
import { OrbitNav } from './OrbitNav'

// ..

export function View() {
  return (<HeaderButtonPassProps><BackButton />{/* ... */}<OrbitHeaderMenu /></HeaderButtonPassProps>)
}

const HeaderButtonPassProps = styled.div()
const BackButton = styled.div()
```

**Current Behavior**

It's not happening on every element, and in testing it in a lot of cases I can't see what actually triggers it. Some files are fine, others have this error. I've binary searched a file down, but again, it didn't really make sense how.

**Environment**
- Babel version(s): 7.4.4
- Node/npm version: 11
- OS: Mojave
- Monorepo: yes/lerna

using:

```
@babel/preset-env {
          loose: true,
          modules: false,
          targets: {
            chrome: '74',
            esmodules: true,
          }
@babel/preset-typescript
@babel/preset-react
```

as well as

```
@babel/plugin-syntax-dynamic-import
@babel/plugin-proposal-decorators
babel-plugin-transform-react-remove-prop-types
@babel/plugin-transform-react-constant-elements
@babel/plugin-transform-react-inline-elements
```

**Possible Solution**

I'll try and investigate more. The constant-element plugin makes a *huge* difference for performance.

Next try will be binary searching plugins.

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

### LINKED ISSUE #10878: transform-react-constant-elements does not transform all hoisted `_react` references
## Bug Report

**Current Behavior**
`transform-react-constant-elements` can generate unrunnable code if two functional components are defined, and the first component renders the second component.

Note: this only affects `preset-env` + `transform-react-jsx` + `transform-react-constant-elements` configs.

The last line of this simplified output shows the bug:
```
var _react = _interopRequireDefault(require("react"));

function Foo() {
  return _ref;
}

var _ref2 =
/*#__PURE__*/
_react["default"].createElement("div", null);

function Bar() {
  return _ref2;
}

var _ref =
/*#__PURE__*/
React.createElement(Bar, null); // <---- BUG!  This should be _react.createElement
```

**Input Code**
- [A link to my fork with a failing test case](https://github.com/babel/babel/compare/master...GoodForOneFare:bug/react-constant-elements-hoisted-function)
- [REPL link showing broken transform](https://babeljs.io/en/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AoSzAVwDsNgJa4AFIgN2CQHcAKASjgBvcnDhEY1KMzgAeALIoAzjCRQAyjHQBrOAHoAfBQC-VOgyZxFKtZp0DhoseKSTpiYjAB0aIilUAogA2SCBItDC8-AAmwOz4ADRwtNRBQfwm5EA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react%2Cenv&prettier=false&targets=&version=7.7.5&externalPlugins=%40babel%2Fplugin-transform-react-constant-elements%407.7.4)
  * Note that untransformed `React.createElement` call
- [REPL link with functions reordered to work around the bug](https://babeljs.io/en/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AoczAVwDsNgJa4BZFAZxiSgGUZ0A1gAoAlHADe5ONLhEY1KM2ToYAOjREUXAKIAbJCCS0YQ_ABNgAN3wAaOLWq7dIigF9KNejEbMACkUtgJAB3UQkpWSR5RWkAHjZObj5BOAB6AD43SiA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react%2Cenv&prettier=false&targets=&version=7.7.5&externalPlugins=%40babel%2Fplugin-transform-react-constant-elements%407.7.4)

**Expected behavior/code**
When `preset-env` has renamed `React` to `_react`, all references should be updated to `_react`.

**Babel Configuration**
```json
{
  "presets": ["@babel/preset-env"],
  "plugins": ["transform-react-jsx", "transform-react-constant-elements"]
}
```

**Environment**
```
  System:
    OS: macOS 10.15.2
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.12.3 - ~/.dev/yarn/1.12.3/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Monorepos:
    Lerna: 3.19.0
  npmPackages:
    @babel/cli: ^7.7.0 => 7.7.5
    @babel/core: ^7.7.2 => 7.7.5
    @babel/eslint-plugin-development: ^1.0.1 => 1.0.1
    @babel/plugin-proposal-class-properties: ^7.7.0 => 7.7.4
    @babel/plugin-proposal-export-namespace-from: ^7.5.2 => 7.7.4
    @babel/plugin-proposal-nullish-coalescing-operator: ^7.4.4 => 7.7.4
    @babel/plugin-proposal-numeric-separator: ^7.2.0 => 7.7.4
    @babel/plugin-proposal-object-rest-spread: ^7.7.4 => 7.7.4
    @babel/plugin-proposal-optional-chaining: ^7.6.0 => 7.7.5
    @babel/plugin-transform-flow-strip-types: ^7.7.4 => 7.7.4
    @babel/plugin-transform-for-of: ^7.7.4 => 7.7.4
    @babel/plugin-transform-modules-commonjs: ^7.7.0 => 7.7.5
    @babel/plugin-transform-runtime: ^7.6.2 => 7.7.6
    @babel/preset-env: ^7.7.1 => 7.7.6
    @babel/preset-flow: ^7.0.0 => 7.7.4
    @babel/register: ^7.7.0 => 7.7.4
    @babel/runtime: ^7.7.2 => 7.7.6
    babel-eslint: ^11.0.0-beta.2 => 11.0.0-beta.2
    babel-jest: ^24.9.0 => 24.9.0
    babel-plugin-transform-charcodes: ^0.2.0 => 0.2.0
    eslint: ^6.0.1 => 6.7.2
    eslint-config-babel: ^9.0.0 => 9.0.0
    gulp-babel: ^8.0.0 => 8.0.0
    jest: ^24.9.0 => 24.9.0
    lerna: ^3.19.0 => 3.19.0
    rollup-plugin-babel: ^4.0.0 => 4.3.3
```
- Monorepo: Lerna
- How you are using Babel: webpack loader

### LINKED ISSUE #10879: @babel/plugin-transform-react-constant-elements is not create _ref for component in case of using object destructuring syntax
## Bug Report

**Current Behavior**
@babel/plugin-transform-react-constant-elements is not create _ref for component in case of using object destructuring syntax.
As you can see in example - _ref variable was used, but it was not defined. 

**Input Code**
- Babel REPL
https://babeljs.io/repl#?browsers=ie%20%3E%3D%2010%2C%20Chrome%20%3E%3D%2054%2C%20last%202%20versions&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AoctCAOwGd4aUQk6x0k4BeOAb3LhwAsgE8Awrkg0kNGAC44ACjA4wdAJTcAfHBUQ1AOiYtyAXwrV68AEYBXYABsAJgBVW8HouNJNXHf0FLBj5RCXBaGRhTbjhvNg4KQSIYWygaJV8dRQFBOAAeUMkI2VjmJC5eb2iAei0c9QpTciA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react&prettier=false&targets=&version=7.7.5&externalPlugins=%40babel%2Fplugin-transform-react-constant-elements%407.7.4%2C%40babel%2Fplugin-transform-destructuring%407.7.4

**Input:**
```js
import React from 'react';

const namespace = {
  MyComponent: (props) => props.name
};
const buildTest = (name) => {
  const {MyComponent} = namespace;
  return () => (
    <MyComponent name={name} />
  );
}
```
**Output:**
```js
"use strict";

var _react = _interopRequireDefault(require("react"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var namespace = {
  MyComponent: function MyComponent(props) {
    return props.name;
  }
};

var buildTest = function buildTest(name) {
  var MyComponent = namespace.MyComponent;
  return function () {
    return _ref;
  };
};
```
**Expected behavior/code**
_ref variable should be created.

**Expected output:**
```js
"use strict";

var _react = _interopRequireDefault(require("react"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var namespace = {
  MyComponent: function MyComponent(props) {
    return props.name;
  }
};

var buildTest = function buildTest(name) {
  var MyComponent = namespace.MyComponent,
      _ref =
  /*#__PURE__*/
  _react.default.createElement(MyComponent, {
    name: name
  });

  return function () {
    return _ref;
  };
};
```
But it's still possible to achieve expected behavior if don't use destructuring syntax.

Edits by @JLHwung : simplified the REPL setup.

### LINKED ISSUE #11686: Transform React Constant Elements incorrectly orders variable declaration in respect to reference
## Bug Report

**Current behavior**

- [REPL](https://babeljs.io/en/repl#?browsers=&build=&builtIns=false&spec=true&loose=false&code_lz=GYVwdgxgLglg9mABHEUCmAnAFAQwwcwEpEBvAKEUQgQGcpEA3HAGxDQCFEBeRMEZ5gG4KVWvSas0AQW6kAvsJGhIsBIhhgwmLMXKV9osDTjM0AOmZx8WEQYMAeGQGs0ATylcSEtlLkA-Wzsg-04XV3ZPbw5_QKC4xHsAYUQwxM88fDlEAHoA-ODs9jz8-2ypPwAaWMRCETkyEQ0tbEJheqA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact&prettier=false&targets=&version=7.10.2&externalPlugins=%40babel%2Fplugin-transform-react-constant-elements%407.10.1)

`valueA` is defined and set after it is passed into React.createElement, causing it to be undefined in the createElement function.

**Input Code**

```jsx
function outer(arg) {
  const valueB = null;
  const valueA = {};

  function inner() {
      console.log(
          <A keyA={valueA}>
              <B keyB={valueB}>
                  <C keyC={arg} />
              </B>
          </A>,
      )
  }

  inner();
}
```

**Output Code according to REPL**

```js
"use strict";

function outer(arg) {
  var valueB = null,
      _ref = /*#__PURE__*/React.createElement(A, {
    keyA: valueA
  }, /*#__PURE__*/React.createElement(B, {
    keyB: valueB
  }, /*#__PURE__*/React.createElement(C, {
    keyC: arg
  })));

  var valueA = {};

  function inner() {
    console.log(_ref);
  }

  inner();
}
```

**Expected behavior**

The `valueA` variable declaration should occur before it is passed into React.createElement. I.e. `var valueA = {}` should be moved above its use in `createElement(A`.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

Reproducible in the REPL and by copying and pasting the input code into the test fixtures in the plugin's directory within the monorepo. React + Spec + Bug Fixes + Shipped Proposals.

**Environment**

- Babel version(s): v7.10.2

**Additional context**

- If you remove the outer function param, the output is correctly ordered.
- Related to the 'dont-host-before-declaration' test?

### LINKED ISSUE #12237: preset-react and react-constant-elements produce invalid code with dynamic import
## Bug Report

- [ ] I would like to work on a fix!

I would work on a fix but unfortunately I have no experience with the Babel repository.

**Current behavior**

Babel produces invalid code that looks like this:

```js
import React from "react";
import OtherComponent, { var _ref = /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement(LazyComponent, null), /*#__PURE__*/React.createElement(OtherComponent, null)); } from "./components/other-component";
export default function App() {
  return _ref;
}
const LazyComponent = /*#__PURE__*/React.lazy(() => import("./components/lazy-component"));
```

EDIT: Got it reproduced in the REPL aswell now, [here](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wG4AoUSWOAeRgAskoBhXSAOyQ6xz3wB0AejTsIXHgGchERswC0o8OO4wy5ckgAe1eABMkmFAFcANlmMcMwcXACCYMAAoAlHADe5OHCIxjUDjgnL284AB49YAA3AD4Q0PCAGRQALwBPNmUJeCE4hO8w-iZWMWy4XPjwoUjYkJcKAF8NUQ5JeGT0zM5VOABeRGIYAVNUtKdXPpi4KmgYJ0ERUtVpEfTFJZ58F3ryIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.12.3&externalPlugins=%40babel%2Fplugin-transform-react-constant-elements%407.12.1%2C%40babel%2Fplugin-syntax-jsx%407.12.1) is the link.

Here is a GitHub-Repository with a minimal example: https://github.com/leodr/babel-constant-elements-bug

**Input Code**

```js
import React from "react";
import OtherComponent from "./components/other-component";

export default function App() {
  return (
    <div>
      <LazyComponent />
      <OtherComponent />
    </div>
  );
}

const LazyComponent = React.lazy(() => import("./components/lazy-component"));
```

**Expected behavior**

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
module.exports = {
  presets: ["@babel/preset-react"],
  plugins: ["@babel/plugin-transform-react-constant-elements"],
};
```

**Environment**

```
  System:
    OS: Windows 10 10.0.18362
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @babel/cli: ^7.12.1 => 7.12.1
    @babel/core: ^7.12.3 => 7.12.3
    @babel/plugin-transform-react-constant-elements: ^7.12.1 => 7.12.1
    @babel/preset-react: ^7.12.1 => 7.12.1
```

### LINKED ISSUE #12303: React constant elements conflict with ...rest handling
## Bug Report

`Illegal variable reference before declaration` error surfaces when using `...rest` props destructure and React constant elements.

**Current behavior**

- [REPL](https://babeljs.io/repl/#?browsers=safari%2011&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAMTnAFAbziKBnAUygEEAnUuAdzwBpEA6R0gvKAXwEpFMAoRRZlBCkkIQgFkCAWwx9-idFwC8APkQAeACYwAbohz4iZCtSXZchEuSp42AehU05_ANoHLxmwF05HANw8bDw8oJCwCIgAQgCGpOgADhTxeFy8_AA2RNzO-hZG1tRO8gxMLFBybIhKiIlwyQH8gsKiEtKyxYpValq6uYZWJnhm7vmD9o45bnkD3r4BbEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.12.3&externalPlugins=%40babel%2Fplugin-transform-react-constant-elements%407.12.1%2C%40babel%2Fplugin-syntax-jsx%407.12.1)

**Input Code**

```js
function Foo({outsetArrows, ...rest}) {
  return useMemo(
    () => <div outsetArrows={outsetArrows}/>,
    [outsetArrows]
  );
}
```

**Output Code**
```js
function Foo(_ref) {
  var _ref2 = <div outsetArrows={outsetArrows} />; // Illegal variable reference before declaration 

  let {
    outsetArrows
  } = _ref,
      rest = _objectWithoutProperties(_ref, ["outsetArrows"]);

  return useMemo(() => _ref2, [outsetArrows]);
}
```

**Expected behavior**

Should behave the same as if the `props` were destructured inside the function body:
```js
function Bar(props) {
  let {
    outsetArrows,
    ...rest
  } = props;
  return useMemo(
    () => <div outsetArrows={outsetArrows}/>,
    [outsetArrows]
  );
}
```

**Additional context**

The above examples have the same output without use of `...rest`: [REPL](https://babeljs.io/repl/#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAMTnAFAbziKBnAUygEEAnUuAdzwF8BKRTAKEUVKJFKREIFkCAthhatE6BgF4AfIgA8AExgA3RDnxEyFahOy5CJclVoB6KQBoRrANpr9mowF0RdANxMaTJqEiwEiAEIAhqToAA4UoXgMzKwANkSMlqp6GobUIjSIEojhcJFurOxQnNx8gsKiYpIyCsrJ6gZaeDq2qU00phaVNimNjs5uNEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react&prettier=false&targets=&version=7.12.3&externalPlugins=%40babel%2Fplugin-transform-react-constant-elements%407.12.1)

### LINKED ISSUE #12422: @babel/plugin-transform-react-constant-elements causes Uncaught TypeError: Cannot read property 'default' of undefined
## Bug Report

**Current behavior**

When I added @babel/plugin-transform-react-constant-elements to my existing project, all the modules that were exported as `export { default as ModuleName } from 'src/components/ModuleName'` return `Cannot read property 'default' of undefined` when I import them as `import { ModuleName } from 'src/components'`
**Input Code**

source code
```js
var _interopRequireDefault = __webpack_require__(/*! @babel/runtime-corejs3/helpers/interopRequireDefault */ "./node_modules/@babel/runtime-corejs3/helpers/interopRequireDefault.js");

var _Object$defineProperty = __webpack_require__(/*! @babel/runtime-corejs3/core-js-stable/object/define-property */ "./node_modules/@babel/runtime-corejs3/core-js-stable/object/define-property.js");

_Object$defineProperty(exports, "FormattedMessage", {
  enumerable: true,
  get: function get() {
    return _FormattedMessage.default; // <- `problem is here`
  }
});

var _FormattedMessage = _interopRequireDefault(__webpack_require__(/*! ./FormattedMessage/FormattedMessage */ "./src/components/FormattedMessage/FormattedMessage.js"));

```

**Expected behavior**

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
const isServer = process.env.WEBPACK_SIDE === 'server'
const withoutTestIds = process.env.DELETE_TEST_IDS === 'true'
const coreJsVersion = 3

module.exports = {
  presets: [
    '@babel/preset-react',
    [
      '@babel/preset-env',
      isServer ? { targets: { node: 'current' } } : { useBuiltIns: 'entry', corejs: coreJsVersion },
    ],
  ],
  plugins: [
    withoutTestIds && [
      'react-remove-properties',
      { properties: [/^data-test/] },
    ],
    !isServer && [
      '@babel/plugin-transform-runtime',
      { corejs: coreJsVersion },
    ],
    'add-module-exports',
    [
      '@babel/plugin-proposal-decorators',
      { legacy: true },
    ],
    '@babel/plugin-transform-react-display-name',
    [
      'module-resolver',
      {
        root: [
          './src',
        ],
        alias: {
          myredux: './src/redux',
        },
      },
    ],
    ['transform-react-remove-prop-types', {
      ignoreFilenames: ['node_modules'],
    }],
    '@babel/plugin-transform-react-inline-elements',
    !isServer && '@babel/plugin-syntax-dynamic-import',
    '@babel/plugin-proposal-class-properties',
    '@babel/plugin-proposal-json-strings',
    '@babel/plugin-proposal-export-default-from',
    '@babel/plugin-transform-react-constant-elements',
    '@babel/plugin-transform-modules-commonjs',
    '@loadable/babel-plugin',
  ].filter(Boolean),
}

```

**Environment**

```
"dependencies": {
    "@loadable/component": "^5.13.2",
    "@loadable/server": "^5.13.2",
    "@sentry/browser": "^5.7.1",
    "@sentry/integrations": "^5.10.2",
    "@sentry/node": "^5.10.2",
    "accept-language": "^3.0.18",
    "axios": "^0.19.0",
    "basic-auth": "^2.0.0",
    "blueimp-md5": "^2.10.0",
    "bootstrap-sass": "^3.3.7",
    "card-validator": "^4.1.1",
    "centrifuge": "^2.5.0",
    "cheerio": "^0.22.0",
    "classlist-polyfill": "^1.2.0",
    "classnames": "^2.2.5",
    "cloudflare": "^2.7.0",
    "cologne-phonetic": "^0.1.0",
    "compression": "^1.7.1",
    "concat-stream": "^1.6.0",
    "concurrently": "^3.5.1",
    "cookie-parser": "^1.4.3",
    "deep-equal": "^1.0.1",
    "dotenv": "^8.2.0",
    "escape-html": "^1.0.3",
    "exenv": "^1.2.0",
    "express": "^4.16.2",
    "fingerprintjs2": "^2.1.0",
    "history": "^4.10.1",
    "hoist-non-react-statics": "^1.0.3",
    "html-entities": "^1.3.1",
    "html-react-parser": "^0.13.0",
    "http-proxy": "^1.18.1",
    "iban": "^0.0.8",
    "intl": "^1.1.0",
    "intl-locales-supported": "^1.0.0",
    "intl-messageformat": "^1.3.0",
    "is_js": "^0.9.0",
    "libphonenumber-js": "^1.7.31",
    "marked": "^0.3.12",
    "memoizee": "^0.4.14",
    "memory-cache": "^0.2.0",
    "mobile-detect": "^1.4.4",
    "moment": "^2.20.1",
    "node-sass": "^4.13.1",
    "prometheus-node-metrics": "paulcamper/prometheus-node-metrics",
    "qhistory": "^1.0.3",
    "qs": "^6.9.1",
    "ramda": "^0.25.0",
    "rc-tooltip": "^3.7.3",
    "react": "^16.13.1",
    "react-addons-update": "^15.6.2",
    "react-autosuggest": "^9.3.2",
    "react-body-classname": "^1.2.0",
    "react-bootstrap": "^0.32.0",
    "react-checkbox-group": "paulcamper/react-checkbox-group#^4.0.2",
    "react-cookie": "^0.4.2",
    "react-copy-to-clipboard": "^5.0.1",
    "react-day-picker": "^7.0.7",
    "react-dnd": "^2.0.2",
    "react-dnd-html5-backend": "^2.0.2",
    "react-dom": "^16.13.1",
    "react-dropzone": "^3.3.0",
    "react-geocoder": "paulcamper/react-geocoder#^3.0.16",
    "react-gtm-module": "^2.0.4",
    "react-helmet": "^5.2.0",
    "react-images": "^0.5.16",
    "react-infinite-scroller": "^1.0.7",
    "react-intl": "^2.0.0-rc-1",
    "react-lazyload": "^2.3.0",
    "react-map-gl": "^3.3.6",
    "react-motion": "^0.4.2",
    "react-motion-ui-pack": "^0.10.3",
    "react-number-format": "^3.0.3",
    "react-onclickoutside": "^6.7.1",
    "react-phone-input": "paulcamper/react-phone-input#^2.7.0",
    "react-player": "^1.6.4",
    "react-radio-group": "^3.0.2",
    "react-rating": "^0.7.1",
    "react-redux": "^7.2.1",
    "react-router": "^5.1.2",
    "react-router-bootstrap": "^0.25.0",
    "react-router-config": "^5.1.1",
    "react-router-dom": "^5.1.2",
    "react-scroll": "^1.7.6",
    "react-scrollbar": "^0.5.1",
    "react-side-effect": "^1.1.3",
    "react-sizeme": "^2.5.2",
    "react-slick": "^0.16.0",
    "react-slider": "^0.9.0",
    "react-sticky": "^6.0.3",
    "react-toggle-switch": "^3.0.4",
    "redux": "^4.0.5",
    "redux-actions": "^2.6.5",
    "redux-connect": "^10.0.0",
    "redux-form": "^5.3.6",
    "redux-saga": "^1.1.3",
    "redux-struct": "^1.3.1",
    "reselect": "^4.0.0",
    "sanitize-html": "^1.17.0",
    "serialize-javascript": "^3.1.0",
    "serve-favicon": "^2.3.0",
    "sitemap-generator": "^8.4.0",
    "slugify": "^1.2.4",
    "sockjs-client": "1.3.0",
    "store": "^2.0.12",
    "svg-inline-react": "^3.0.0",
    "truncate": "^2.0.0",
    "uuid": "^3.0.1",
    "viewport-mercator-project": "^6.0.0",
    "webpack-cli": "^3.3.7"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/plugin-proposal-class-properties": "^7.12.1",
    "@babel/plugin-proposal-decorators": "^7.12.1",
    "@babel/plugin-proposal-export-default-from": "^7.12.1",
    "@babel/plugin-proposal-export-namespace-from": "^7.12.1",
    "@babel/plugin-proposal-json-strings": "^7.12.1",
    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
    "@babel/plugin-transform-modules-commonjs": "^7.12.1",
    "@babel/plugin-transform-react-constant-elements": "^7.12.1",
    "@babel/plugin-transform-react-display-name": "^7.12.1",
    "@babel/plugin-transform-react-inline-elements": "^7.12.1",
    "@babel/plugin-transform-runtime": "^7.12.1",
    "@babel/preset-env": "^7.12.7",
    "@babel/preset-react": "^7.12.7",
    "@hint/hint-performance-budget": "^2.4.7",
    "@loadable/babel-plugin": "^5.13.2",
    "@loadable/webpack-plugin": "^5.13.0",
    "@storybook/addon-actions": "^5.3.14",
    "@storybook/addon-info": "^5.3.14",
    "@storybook/addon-knobs": "^5.3.14",
    "@storybook/addon-links": "^5.3.14",
    "@storybook/addons": "^5.3.14",
    "@storybook/react": "^5.3.14",
    "@testing-library/jest-dom": "^5.11.3",
    "@testing-library/react": "^10.4.8",
    "autoprefixer": "^9.6.1",
    "babel-eslint": "^10.1.0",
    "babel-loader": "^8.2.2",
    "babel-plugin-add-module-exports": "^1.0.2",
    "babel-plugin-module-resolver": "^4.0.0",
    "babel-plugin-react-remove-properties": "^0.3.0",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
    "bootstrap-loader": "^3.0.4",
    "core-js": "^3.8.0",
    "css-loader": "^3.2.0",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^17.1.1",
    "eslint-plugin-import": "^2.18.0",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.14.2",
    "eslint-plugin-react-hooks": "^2.3.0",
    "file-loader": "^4.2.0",
    "hint": "^6.1.1",
    "image-webpack-loader": "^6.0.0",
    "isomorphic-style-loader": "4.0.0",
    "jest": "^26.4.0",
    "jest-environment-jsdom-sixteen": "^1.0.3",
    "mini-css-extract-plugin": "^0.8.0",
    "morgan": "^1.9.1",
    "nodemon": "^1.19.2",
    "normalize.css": "^8.0.1",
    "optimize-css-assets-webpack-plugin": "^5.0.3",
    "postcss-loader": "^3.0.0",
    "prop-types": "^15.6.0",
    "raw-loader": "^1.0.0",
    "redux-devtools": "^3.4.1",
    "redux-devtools-dock-monitor": "^1.1.3",
    "redux-devtools-extension": "^2.13.8",
    "redux-devtools-log-monitor": "^1.4.0",
    "regenerator-runtime": "^0.13.5",
    "resolve-url-loader": "^3.1.0",
    "sass-loader": "^8.0.0",
    "style-loader": "^1.0.0",
    "text-loader": "^0.0.1",
    "universal-webpack": "^0.6.12",
    "url-loader": "^2.1.0",
    "webpack": "^4.41.6",
    "webpack-bundle-analyzer": "^3.3.2",
    "webpack-dev-server": "^3.8.0",
    "webpack-merge": "^4.2.2",
    "webpack-sentry-plugin": "^2.0.2",
    "workbox-precaching": "^5.1.4",
    "workbox-webpack-plugin": "^5.1.4",
    "workbox-window": "^5.1.4"
  },

```

**Possible Solution**

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #11686, fixes #12422, fixes #12237, fixes #9965, fixes #12303, fixes #10879, fixes #7610, fixes #7565, fixes #7726, fixes #6751.<br/><br/>I think this also fixes #10878 because with this PR the plugin doesn't move JSX elements around, but there isn't an example to confirm it.
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

This PR rewrites the `@babel/plugin-transform-constant-elements` implementation under a new realization: we don't need to actually _hoist_ the elements to prevent them from being unnecessarily evaluated multiple times, we just need to _cache_ them.

This also has the potential effect of improving app startup performance, by only computing JSX elements when they are needed rather than when the app is first loaded.

After this PR, [this code (260 lines)](https://github.com/babel/babel/blob/main/packages/babel-traverse/src/path/lib/hoister.ts) becomes unused in this repository. We could try removing it in Babel 8 if no important community plugins depend on it (it has different bugs).

**UPDATE**: I just realized my idea isn't new: https://github.com/facebook/react/issues/3226#issuecomment-78167666

cc @babel/react

### CODE REVIEW

**Comment by jridgewell** [comment]
Before I forget while reviewing: https://github.com/babel/babel/issues/12422#issuecomment-790998755 made me think of another case:

```js
import { Foo } from "./main.js";

export function bar() {
  return <Foo />;
}
```

This element is not provably constant, because `Foo` is a live binding and can be changed inside `main.js`.

File: packages/babel-plugin-transform-react-constant-elements/src/index.js [hunk 1]
```diff
@@ -83,30 +146,70 @@ export default declare((api, options) => {
     visitor: {
       JSXElement(path) {
         if (HOISTED.has(path.node)) return;
-        HOISTED.add(path.node);
+        HOISTED.set(path.node, path.scope);
 
-        const state = { isImmutable: true };
+        const name = path.get("openingElement.name").node;
```
Comment (jridgewell) [inline packages/babel-plugin-transform-react-constant-elements/src/index.js:151]: Nit:
```suggestion
        const name = path.node.openingElement.name;
```

**Comment by nicolo-ribaudo** [comment]
That's technically true, but:
- this plugin has always operated under the assumption that it's constant, and no one ever complained
- I have never seen a react codebase in my life where assuming that it's constant could cause problems
- it would completely disable the optimization for all the non-builtin elements (since almost always they are imported)

I would prefer to leave it as-is, and possibly change it in the future if needed (with a flag to opt-in or opt-out).

File: packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/member-expression-constant/output.js [hunk 2]
```diff
@@ -1,7 +1,6 @@
+var _this$component;
+
 function render() {
   this.component = "div";
-
-  var _ref = <this.component />;
-
-  return () => _ref;
+  return () => _this$component || (_this$component = <this.component />);
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/member-expression-constant/output.js:5]: This is wrong

File: packages/babel-plugin-transform-react-constant-elements/src/index.js [hunk 3]
```diff
@@ -83,30 +146,70 @@ export default declare((api, options) => {
...
+          const elementName = lastSegment.name;
+          mutablePropsAllowed = allowMutablePropsOnTags.includes(elementName);
         }
 
-        // Traverse all props passed to this element for immutability.
-        path.traverse(immutabilityVisitor, state);
+        // In order to avoid hoisting unnecessarily, we need to know which is
+        // the scope containing the current JSX element. If a parent of the
+        // current element has already been hoisted, we can consider its target
+        // scope as the base scope for the current element.
```
Comment (jridgewell) [inline packages/babel-plugin-transform-react-constant-elements/src/index.js:172]: Can you explain this bit? I can't really understand why we need to track scopes here, or in the analyzer, since it's traversing downwards.

In my head, we need to collect all of the `ReferencedIdentifier`s, then traverse upwards until we find a scope that defines one of them, and inject the lazy binding in that scope.

Comment (nicolo-ribaudo) [reply packages/babel-plugin-transform-react-constant-elements/src/index.js:172]: When you have this code:
```js
function fn() {
  return <div><p/></div>;
}
```

first we traverse the `div`, and it becomes
```js
var _div;

function fn() {
  return _div || (_div = <div><p/></div>);
}
```

and then we don't want it to become
```js
var _div, _p;

function fn() {
  return _div || (_div = <div>{_p || (_p = <p/>)}</div>);
}
```
because it's unnecessary.

However, we might still want to hoist `<p/>` in some cases:
```js
function fn() {
  let cl = "a";
  return () => <div className={cl}><p/></div>;
}
```
will first become
```js
function fn() {
  var _div;
  let cl = "a";
  return () => _div || (_div = <div className={cl}><p/></div>);
}
```
and then it can be still optimized to
```js
var _p;
function fn() {
  var _div;
  let cl = "a";
  return () => _div || (_div = <div className={cl}>{_p || (_p = <p/>)}</div>);
}
```

File: packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/member-expression-this/output.js [hunk 4]
```diff
@@ -1,14 +1,14 @@
...
+    var _this$subComponent;
 
-    this.subComponent = () => _ref;
+    super(...args);
 
-    var _ref2 = <this.subComponent />;
+    this.subComponent = () => _span || (_span = <span>Sub Component</span>);
 
-    this.render = () => _ref2;
+    this.render = () => _this$subComponent || (_this$subComponent = <this.subComponent />);
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-react-constant-elements/test/fixtures/constant-elements/member-expression-this/output.js:11]: I'm not sure I like caching this. For now let's keep the current behavior since no one complained, but this doesn't look safe (I don't know how "react components on `this` are usually used).

File: packages/babel-plugin-transform-react-constant-elements/src/index.js [hunk 5]
```diff
@@ -18,6 +18,19 @@ export default declare((api, options) => {
   // Element -> Target scope
   const HOISTED = new WeakMap();
 
+  function declares(
+    node: t.ThisExpression | t.Identifier | t.JSXIdentifier,
+    scope,
+  ) {
+    // Ideally this should always be a ThisExpression 🤷
+    if (t.isThisExpression(node) || t.isJSXIdentifier(node, { name: "this" })) {
```
Comment (jridgewell) [inline packages/babel-plugin-transform-react-constant-elements/src/index.js:26]: I think we'll also need this for `super`, `new.target`, `arguments`, etc? I think it'd be better to handle an `JSXOpeningElement` that check if we're referencing a binding or using a lowercase name.

File: packages/babel-plugin-transform-react-constant-elements/src/index.js [hunk 6]
```diff
@@ -75,6 +89,68 @@ export default declare((api, options) => {
         stop();
       }
     },
+    "ReferencedIdentifier|ThisExpression"(path, state) {
+      const { node } = path;
+      let { scope } = path;
+      let targetScope;
+
+      let isNestedScope = true;
+      let needsHoisting = true;
```
Comment (jridgewell) [inline packages/babel-plugin-transform-react-constant-elements/src/index.js:98]: I think we can actually reduce this code a bit:

```diff
diff --git a/packages/babel-plugin-transform-react-constant-elements/src/index.js b/packages/babel-plugin-transform-react-constant-elements/src/index.js
index 40d929e992..ccd6340f74 100644
--- a/packages/babel-plugin-transform-react-constant-elements/src/index.js
+++ b/packages/babel-plugin-transform-react-constant-elements/src/index.js
@@ -94,47 +94,11 @@ export default declare((api, options) => {
       let { scope } = path;
       let targetScope;
 
-      let isNestedScope = true;
-      let needsHoisting = true;
-
       while (scope) {
         // We cannot hoist outside of the previous hoisting target
         // scope, so we return early and we don't update it.
         if (scope === state.targetScope) return;
 
-        // When we hit the scope of our JSX element, we must start
-        // checking if they declare the binding of the current
-        // ReferencedIdentifier.
-        // We don't case about bindings declared in nested scopes,
-        // because the whole nested scope is hoisted alongside the
-        // JSX element so it doesn't impose any extra constraint.
-        if (scope === state.jsxScope) {
-          isNestedScope = false;
-        }
-
-        // If we are in an upper scope and hoisting to this scope has
-        // any benefit, we update the possible targetScope to the
-        // current one.
-        if (!isNestedScope && needsHoisting) {
-          targetScope = scope;
-        }
-
-        // When we start walking in upper scopes, avoid hoisting JSX
-        // elements until we hit a scope introduced by a function or
-        // loop.
-        // This is because hoisting from the inside to the outside
-        // of block or if statements doesn't give any performance
-        // benefit, and it just unnecessarily increases the code size.
-        if (scope === state.jsxScope) {
-          needsHoisting = false;
-        }
-        if (
-          !needsHoisting &&
-          (scope.path.isFunctionParent() || scope.path.isLoop())
-        ) {
-          needsHoisting = true;
-        }
-
         // If the current scope declares the ReferencedIdentifier we
         // are checking, we break out of this loop. There are two
         // possible scenarios:
@@ -148,8 +112,7 @@ export default declare((api, options) => {
 
         scope = scope.parent;
       }
-
-      if (targetScope) state.targetScope = targetScope;
+      if (scope) state.targetScope = scope.getFunctionParent();
     },
   };
 
@@ -189,12 +152,11 @@ export default declare((api, options) => {
           current = current.parentPath;
           jsxScope = HOISTED.get(current.node);
         }
-        jsxScope ??= path.scope;
+        jsxScope ??= path.scope.getFunctionParent();
 
         const state = {
           isImmutable: true,
           mutablePropsAllowed,
-          jsxScope,
           targetScope: null,
         };
 
```

File: packages/babel-plugin-transform-react-constant-elements/src/index.js (hunk 5 above)
Comment (jridgewell) [reply packages/babel-plugin-transform-react-constant-elements/src/index.js:26]: Ahh, I see we added `JSXIdentifier` to `ReferencedIdentifier`, so this should be ok.

**Review by jridgewell — APPROVED** [review]
> I would prefer to leave it as-is, and possibly change it in the future if needed (with a flag to opt-in or opt-out).

Going through the examples, it seems we treat member expressions as always constant, eg for `Intl.FormattedMessage`. Given that, I think this is fine.

File: packages/babel-plugin-transform-react-constant-elements/src/index.js (hunk 6 above)
Comment (nicolo-ribaudo) [reply packages/babel-plugin-transform-react-constant-elements/src/index.js:103]: This unnecessarily caches some components:
```js
function Component({ isLoading, text }) {
  if (isLoading) {
    return <p>Loading {text}</p>;
  }
  return <p>Loaded {text}</p>;
}
```
```js
function Component({
  isLoading,
  text
}) {
  var _p;

  if (isLoading) {
    return _p || (_p = <p>Loading {text}</p>);
  }

  return <p>Loaded {text}</p>;
}
```
which is the reason I introduced the `needsHoisting` variable.

Also, I cannot drop `ReferencedIdentifier|ThisExpression` because it needs to handle things like `<p>{() => this}</p>`.

Comment (jridgewell) [reply packages/babel-plugin-transform-react-constant-elements/src/index.js:99]: I edited the diff a few hours after initially comment, are you sure you're using the latest? You can see it running at https://astexplorer.net/#/gist/15ad6fa36177a1ba8f06a94c7dd28f8a/bedfd7d67d72dbb98b33be1e66f98785c3b18aac. This test case (and all the others) are passing for me.

**Comment by nicolo-ribaudo** [comment]
I realized that we don't hoist/cache elements with functions:

```js
function Counter({ inc }) {
  let [value, update] = useState(0);

  return <button onClick={() => update(inc)}>{value}</button>;
}

function Main() {
  return <Counter inc={num => num + 2} />;
}
```

could become

```js
var _Counter;

function Counter({ inc }) {
  let [value, update] = useState(0);

  return <button onClick={() => update(inc)}>{value}</button>;
}

function Main() {
  return _Counter || (_Counter = <Counter inc={num => num + 2} />);
}
```

this PR already contains the logic to track bindings in nested functions, but I'd prefer to actually allow hoisting of components with functions in a separate PR to keep this 1:1 with the previous behavior.

File: packages/babel-plugin-transform-async-to-generator/test/fixtures/regression/7178/output.js [hunk 7]
```diff
@@ -1,16 +1,16 @@
...
 }
 
-var _ref = /*#__PURE__*/React.createElement(Contact, {
-  title: title
-});
-
 function _action() {
   _action = babelHelpers.asyncToGenerator(function* () {
-    return _ref;
+    return _Contact || (_Contact = /*#__PURE__*/React.createElement(Contact, {
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-async-to-generator/test/fixtures/regression/7178/output.js:11]: In Babel 8 we could just use `||=` here, and if someone targets an older browser it will be transformed by another different plugin.

File: packages/babel-plugin-transform-react-constant-elements/src/index.js [hunk 8]
```diff
@@ -83,30 +160,70 @@ export default declare((api, options) => {
...
+        HOISTED.set(path.node, targetScope);
+
+        // Only hoist if it would give us an advantage.
+        if (targetScope === jsxScope) return;
+
+        const id = path.scope.generateUidBasedOnNode(name);
+        targetScope.push({ id: t.identifier(id) });
+
+        let replacement = template.expression.ast`
+          ${t.identifier(id)} || (${t.identifier(id)} = ${path.node})
```
Comment (JLHwung) [inline packages/babel-plugin-transform-react-constant-elements/src/index.js:220]: nit: we can output `${t.identifier(id)} ||= ${path.node}` if the `target` has native logical assignment support, or do it by default in Babel 8.

File: packages/babel-plugin-transform-react-constant-elements/src/index.js (hunk 6 above)
Comment (nicolo-ribaudo) [reply packages/babel-plugin-transform-react-constant-elements/src/index.js:99]: I probably made some mistake while applying your diff.

I'm just commenting out my code instead of deleting it, since it will be needed if/when we do https://github.com/babel/babel/pull/12967#issuecomment-791352695 for cases like
```js
function Component({ isLoading, text }) {
  return () => <p>Loading {text => text}</p>;
}
```
which with the simplified logic would become
```js
function Component({
  isLoading,
  text
}) {
  return () => _p || (_p = <p>Loading {text => {
      var _p;

      return text;
    }}</p>);
}
```

File: packages/babel-plugin-transform-react-constant-elements/src/index.js [hunk 9]
```diff
@@ -83,30 +191,67 @@ export default declare((api, options) => {
...
         // of JSX tags to allow mutable props (such as objects, functions) on. Use sparingly
         // and only on tags you know will never modify their own props.
+        let mutablePropsAllowed = false;
         if (allowMutablePropsOnTags != null) {
           // Get the element's name. If it's a member expression, we use the last part of the path.
           // So the option ["FormattedMessage"] would match "Intl.FormattedMessage".
-          let namePath = path.get("openingElement.name");
-          while (namePath.isJSXMemberExpression()) {
-            namePath = namePath.get("property");
+          let lastSegment = name;
```
Comment (JLHwung) [inline packages/babel-plugin-transform-react-constant-elements/src/index.js:205]: `name` can also be a `JSXNamespacedName`, which is currently not handled.

Can you add a test case like
```jsx
function AComponent () {
  return <BComponent/>

  function BComponent () {
    return <n:CComponent />
  }
}
```
`n:CComponent` should be cached.

**Review by JLHwung — APPROVED** [review]
Looks good to me other than that we may miss the namespaced name, but we didn't support it before this PR anyway.

File: packages/babel-plugin-transform-react-constant-elements/src/index.js [hunk 10]
```diff
@@ -83,30 +191,67 @@ export default declare((api, options) => {
...
+        // Only hoist if it would give us an advantage.
+        if (targetScope === jsxScope) return;
+
+        const id = path.scope.generateUidBasedOnNode(name);
+        targetScope.push({ id: t.identifier(id) });
+
+        let replacement = template.expression.ast`
+          ${t.identifier(id)} || (${t.identifier(id)} = ${path.node})
+        `;
+        if (path.parentPath.isJSXElement()) {
```
Comment (jridgewell) [inline packages/babel-plugin-transform-react-constant-elements/src/index.js:250]:
```suggestion
        if (path.parentPath.isJSXElement() || path.parentPath.isJSXAttribute()) {
```

Test Case:
```js
function C(x) {
  // Bind the div in this scope, so only Main is hoisted.
  return <div x={x} attr=<span /> />;
}
```

File: packages/babel-plugin-transform-react-constant-elements/src/index.js [hunk 11]
```diff
@@ -83,30 +191,67 @@ export default declare((api, options) => {
...
+        const { targetScope } = state;
+        HOISTED.set(path.node, targetScope);
+
+        // In order to avoid hoisting unnecessarily, we need to know which is
+        // the scope containing the current JSX element. If a parent of the
+        // current element has already been hoisted, we can consider its target
+        // scope as the base scope for the current element.
+        let jsxScope;
+        let current = path;
+        while (!jsxScope && current.parentPath.isJSXElement()) {
```
Comment (jridgewell) [inline packages/babel-plugin-transform-react-constant-elements/src/index.js:235]:
```suggestion
        while (!jsxScope && current.parentPath.isJSX()) {
```

Test Case:
```js
function C() {
  return <div attr=<span /> />;
}
```

File: packages/babel-plugin-transform-react-constant-elements/src/index.js (hunk 6 above)
Comment (jridgewell) [reply packages/babel-plugin-transform-react-constant-elements/src/index.js:133]: I think we'll be able to handle that case with the simplified code, but let's wait for the followup PR.

**Review by jridgewell — APPROVED** [review]

**Review by existentialism — APPROVED** [review]
💯
