### PR TITLE
fix: Reset child scopes when `scope.crawl()`

### LINKED ISSUE #3733: scope.crawl() recounts references (T6666)
> Issue originally made by @amasad
### Bug information
- **Babel version:** 6.x
- **Node version:** any
- **npm version:** any
### Options

```
N/A
```
### Input code

``` js
(function() {
  var x = 1;
  x;
  x;
})();
```
### Description

Calling `scope.crawl()` isn't properly resetting the scope and is recounting the references resulting in doubling the references with every count.

Note that I was only able to reproduce it by calling crawl from the parent scope (in this case the `Program` scope) however, I'm not entirely sure this is always the case.

```
babel.transform(code, {
  plugins: [
    function (b) {
      var t = b.types;
      return {
        visitor: {
          // Replace block statements with a new node without changing anything                                                                             
          Scope: function(path) {
            if (path.isProgram()) {
              path.scope.crawl();
              path.scope.crawl();
              return;
            }
             // expected 2, actual 6 (doubles with every crawl call).
            console.log(path.scope.getBinding('x').references);
          },
        }
      };
    }
  ],
}).code;
```

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #3733 
| Patch: Bug Fix?          | √
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | √
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

File: packages/babel-traverse/src/scope/index.ts [hunk 1]
```diff
@@ -227,7 +226,14 @@ function gatherNodeParts(node: t.Node, parts: NodePart[]) {
...
 
-//
+function resetScope(scope: Scope) {
+  scope.references = Object.create(null);
+  scope.bindings = Object.create(null);
+  scope.globals = Object.create(null);
+  scope.uids = Object.create(null);
+  scope.data = Object.create(null);
+}
+
```
Comment (JLHwung) [inline packages/babel-traverse/src/scope/index.ts:236]: This helper seems to be a genuine scope method, I think it could be public as well since the `scope.data` is user defined: They might want to override the `resetScope` method to do custom data cleanup.

Comment (liuxingbaoyu) [reply packages/babel-traverse/src/scope/index.ts:236]: I prefer not to expose it to users, since we've reduced public methods as much as possible in Babel 8, and they couldn't be overridden before.

Comment (liuxingbaoyu) [reply packages/babel-traverse/src/scope/index.ts:236]: I rethought it, it seems we shouldn't reset `data`.

**Review by JLHwung — APPROVED** [review]

**Review by nicolo-ribaudo — APPROVED** [review]
