### PR TITLE
Fix update expression for exported bigints

### LINKED ISSUE #14340: [Bug]: update Expression transform into wrong result in cjs
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

[REPL](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAG2PAZhCcC8cCMA7AbgCgi0IBqcgoA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.17.6&externalPlugins=&assumptions=%7B%7D)
```javascript
export let foo = 1n;

foo++;
```

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

```javascript
exports.foo = void 0;

var _foo;

let foo = 1n;
exports.foo = foo;
_foo = +foo, exports.foo = foo = _foo + 1, _foo;
```

Note: cannot mix bigint with number.

### Environment

default config

### Possible solution

```javascript
++foo
=> exports.foo = ++foo

bar++
=> (ref = bar++, exports.bar = bar, ref)
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by magic-akari**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #14340 
| Patch: Bug Fix?          | 👍
| Major: Breaking Change?  | behavior of `@babel/helper-simple-access` changed
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14341"></a>

### CODE REVIEW

File: packages/babel-helper-simple-access/src/index.ts [hunk 1]
```diff
@@ -20,73 +16,6 @@ export default function simplifyAccess(path: NodePath, bindingNames) {
 }
 
 const simpleAssignmentVisitor = {
-  UpdateExpression: {
```
[the remark this answers is not in the document]
Comment (magic-akari) [reply packages/babel-helper-simple-access/src/index.ts:23]: Yes.
What can I do? Should I bump the version of the package?

[the remark this answers is not in the document]
Comment (nicolo-ribaudo) [reply packages/babel-helper-simple-access/src/index.ts:23]: No, because we keep all the versions synchronized (and it would require a major bump).

It's annoying, but a solution until Babel 8 is to pass a `includeUpdateExpression: boolean = true` option to `simplifyAccess`, and only skip the `UpdateExpression` visitor when that option is set to `false`. (and please add a comment to revisit it in Babel 8!)

File: packages/babel-plugin-transform-modules-commonjs/src/index.ts [hunk 2]
```diff
@@ -81,14 +81,35 @@ export default declare((api, options) => {
...
+        path.isAssignmentExpression({ left: path.node }) ||
+        path.parentPath.isUpdateExpression()
       ) {
         return;
       }
 
       path.replaceWith(getAssertion(localName));
     },
 
+    UpdateExpression(path) {
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-modules-commonjs/src/index.ts:93]: Q: What is this change for?

Comment (magic-akari) [reply packages/babel-plugin-transform-modules-commonjs/src/index.ts:93]: This seems to be a redundant change.
All tests passed without it.

Comment (magic-akari) [reply packages/babel-plugin-transform-modules-commonjs/src/index.ts:93]: I mean the line 85

Comment (magic-akari) [reply packages/babel-plugin-transform-modules-commonjs/src/index.ts:93]: line 93-111 to prevent the following case:

```javascript
module++
```

```javascript
function () {
    throw new Error("The CommonJS '" + "module" + "' variable is not available in ES6 modules." + "Consider setting setting sourceType:script or sourceType:unambiguous in your " + "Babel config for this file.");
}()++;
```

Comment (magic-akari) [reply packages/babel-plugin-transform-modules-commonjs/src/index.ts:92]: instead, we expect the following result
```javascript
module += function () {
    throw new Error("The CommonJS '" + "module" + "' variable is not available in ES6 modules." + "Consider setting setting sourceType:script or sourceType:unambiguous in your " + "Babel config for this file.");
}();
```

Comment (nicolo-ribaudo) [reply packages/babel-plugin-transform-modules-commonjs/src/index.ts:92]: Oh well, both those pieces of code have the same behavior, so whatever we get with less code is ok.

**Review by nicolo-ribaudo — APPROVED** [review]

**Review by JLHwung — APPROVED** [review]

**Review by nicolo-ribaudo — APPROVED** [review]
for the new tests
