### PR TITLE
Merge multiple regex transform plugin

### LINKED ISSUE #8951: SyntaxError: Expected atom at position 2     \p{Script_Ex
## Bug Report

**Current Behavior**

```
> babel . --out-dir dist

SyntaxError: Expected atom at position 2
    \p{Script_Ex
      ^
    at bail (/home/shm/dpp-query-ws/node_modules/regjsparser/parser.js:1093:13)
    at parseTerm (/home/shm/dpp-query-ws/node_modules/regjsparser/parser.js:486:9)
    at parseAlternative (/home/shm/dpp-query-ws/node_modules/regjsparser/parser.js:457:21)
    at parseDisjunction (/home/shm/dpp-query-ws/node_modules/regjsparser/parser.js:437:16)
    at parse (/home/shm/dpp-query-ws/node_modules/regjsparser/parser.js:1108:18)
    at rewritePattern (/home/shm/dpp-query-ws/node_modules/regexpu-core/rewrite-pattern.js:324:15)
    at PluginPass.RegExpLiteral (/home/shm/dpp-query-ws/node_modules/@babel/plugin-transform-unicode-regex/lib/index.js:50:51)
    at newFn (/home/shm/dpp-query-ws/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/home/shm/dpp-query-ws/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/home/shm/dpp-query-ws/node_modules/@babel/traverse/lib/path/context.js:40:17)
```

**Input Code**
- REPL or Repo link if applicable:

```js
var your => (code) => here;
```

**Expected behavior/code**
Successful transpiled code

**Babel Configuration (.babelrc, package.json, cli command)**
package.json
```json5
"devDependencies": {
    "@babel/cli": "^7.1.2",
    "@babel/core": "^7.1.2",
    "@babel/node": "^7.0.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0",
    "@babel/preset-env": "^7.1.0",
    "@babel/preset-flow": "^7.0.0",
    "nodemon": "^1.18.4"
  }
```
babel.config.js
```js
module.exports = {
  "presets": ["@babel/preset-env","@babel/preset-flow"],
  "plugins": [
    "@babel/plugin-proposal-object-rest-spread"
  ]
}
```

**Environment**
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- Node/npm version: Node 8.12.0/npm 6.4.1
- OS: Ubuntu 16.04.4 LTS
- Monorepo
- How you are using Babel: [e.g. `cli`, `register`, `loader`]
  cli
  ```
  "build": "babel . --out-dir dist"
  ```

### LINKED ISSUE #9199: useUnicodeFlag config in babel-preset-env should set with targets config
## Bug Report

**Current Behavior**

`@babel/plugin-proposal-unicode-property-regex` config `useUnicodeFlag` always true.

**Input Code**

```js
/\p{Script_Extensions=Greek}/u;
```

**Expected behavior/code**
/(?:[\u0342\u0345\u0370-\u0373\u0375-\u0377\u037A-\u037D\u037F\u0384\u0386\u0388-\u038A\u038C\u038E-\u03A1\u03A3-\u03E1\u03F0-\u03FF\u1D26-\u1D2A\u1D5D-\u1D61\u1D66-\u1D6A\u1DBF-\u1DC1\u1F00-\u1F15\u1F18-\u1F1D\u1F20-\u1F45\u1F48-\u1F4D\u1F50-\u1F57\u1F59\u1F5B\u1F5D\u1F5F-\u1F7D\u1F80-\u1FB4\u1FB6-\u1FC4\u1FC6-\u1FD3\u1FD6-\u1FDB\u1FDD-\u1FEF\u1FF2-\u1FF4\u1FF6-\u1FFE\u2126\uAB65]|\uD800[\uDD40-\uDD8E\uDDA0]|\uD834[\uDE00-\uDE45])/;

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  presets: ['@babel/preset-env', {
    targets: {
      chrome: 49
   },
  }]
}
```

**Environment**
- Babel version(s): 7.2.2
- Node/npm version: 8.11.3/6.4.1
- OS: OSX 10.13.6
- Monorepo: no
- How you are using Babel: loader

**Possible Solution**

set useUnicodeFlag with targets config, set it false if targets browser is not support unicode flag.

### LINKED ISSUE #9892: Invalid regex polyfill for unicode matches in env preset
## Bug Report

**Current Behavior**
Regex is transformed into invalid form in env preset unless the target version is node 8, electron 1.8 or lower.

**Input Code**
```js
console.log(/[\p{L}\d_]+/u.test('ŁŻŹĆ'));
```
is transpilled to:
```js
"use strict";

console.log(/[0-9L_p\{\}]+/.test('ŁŻŹĆ'));
```
with following settings:

image

This piece of code is not only transpilled incorrectly but also broken (different end result than expected).

**Expected behavior/code**

```js
console.log(/[\p{L}\d_]+/u.test('ŁŻŹĆ'));
```
should be transpilled to:

```js
"use strict";

console.log(/[0-9A-Z_a-z\xAA\xB5\xBA\xC0-\xD6\xD8-\xF6\xF8-\u02C1\u02C6-\u02D1\u02E0-\u02E4\u02EC\u02EE\u0370-\u0374\u0376\u0377\u037A-\u037D\u037F\u0386\u0388-\u038A\u038C\u038E-\u03A1\u03A3-\u03F5\u03F7-\u0481\u048A-\u052F\u0531-\u0556\u0559\u0560-\u0588\u05D0-\u05EA\u05EF-\u05F2\u0620-\u064A\u066E\u066F\u0671-\u06D3\u06D5\u06E5\u06E6\u06EE\u06EF\u06FA-\u06FC\u06FF\u0710\u0712-\u072F\u074D-\u07A5\u07B1\u07CA-\u07EA\u07F4\u07F5\u07FA\u0800-\u0815\u081A\u0824\u0828\u0840-\u0858\u0860-\u086A\u08A0-\u08B4\u08B6-\u08BD\u0904-\u0939\u093D\u0950\u0958-\u0961\u0971-\u0980\u0985-\u098C\u098F\u0990\u0993-\u09A8\u09AA-\u09B0\u09B2\u09B6-\u09B9\u09BD\u09CE\u09DC\u09DD\u09DF-\u09E1\u09F0\u09F1\u09FC\u0A05-\u0A0A\u0A0F\u0A10\u0A13-\u0A28\u0A2A-\u0A30\u0A32\u0A33\u0A35\u0A36\u0A38\u0A39\u0A59-\u0A5C\u0A5E\u0A72-\u0A74\u0A85-\u0A8D\u0A8F-\u0A91\u0A93-\u0AA8\u0AAA-\u0AB0\u0AB2\u0AB3\u0AB5-\u0AB9\u0ABD\u0AD0\u0AE0\u0AE1\u0AF9\u0B05-\u0B0C\u0B0F\u0B10\u0B13-\u0B28\u0B2A-\u0B30\u0B32\u0B33\u0B35-\u0B39\u0B3D\u0B5C\u0B5D\u0B5F-\u0B61\u0B71\u0B83\u0B85-\u0B8A\u0B8E-\u0B90\u0B92-\u0B95\u0B99\u0B9A\u0B9C\u0B9E\u0B9F\u0BA3\u0BA4\u0BA8-\u0BAA\u0BAE-\u0BB9\u0BD0\u0C05-\u0C0C\u0C0E-\u0C10\u0C12-\u0C28\u0C2A-\u0C39\u0C3D\u0C58-\u0C5A\u0C60\u0C61\u0C80\u0C85-\u0C8C\u0C8E-\u0C90\u0C92-\u0CA8\u0CAA-\u0CB3\u0CB5-\u0CB9\u0CBD\u0CDE\u0CE0\u0CE1\u0CF1\u0CF2\u0D05-\u0D0C\u0D0E-\u0D10\u0D12-\u0D3A\u0D3D\u0D4E\u0D54-\u0D56\u0D5F-\u0D61\u0D7A-\u0D7F\u0D85-\u0D96\u0D9A-\u0DB1\u0DB3-\u0DBB\u0DBD\u0DC0-\u0DC6\u0E01-\u0E30\u0E32\u0E33\u0E40-\u0E46\u0E81\u0E82\u0E84\u0E86-\u0E8A\u0E8C-\u0EA3\u0EA5\u0EA7-\u0EB0\u0EB2\u0EB3\u0EBD\u0EC0-\u0EC4\u0EC6\u0EDC-\u0EDF\u0F00\u0F40-\u0F47\u0F49-\u0F6C\u0F88-\u0F8C\u1000-\u102A\u103F\u1050-\u1055\u105A-\u105D\u1061\u1065\u1066\u106E-\u1070\u1075-\u1081\u108E\u10A0-\u10C5\u10C7\u10CD\u10D0-\u10FA\u10FC-\u1248\u124A-\u124D\u1250-\u1256\u1258\u125A-\u125D\u1260-\u1288\u128A-\u128D\u1290-\u12B0\u12B2-\u12B5\u12B8-\u12BE\u12C0\u12C2-\u12C5\u12C8-\u12D6\u12D8-\u1310\u1312-\u1315\u1318-\u135A\u1380-\u138F\u13A0-\u13F5\u13F8-\u13FD\u1401-\u166C\u166F-\u167F\u1681-\u169A\u16A0-\u16EA\u16F1-\u16F8\u1700-\u170C\u170E-\u1711\u1720-\u1731\u1740-\u1751\u1760-\u176C\u176E-\u1770\u1780-\u17B3\u17D7\u17DC\u1820-\u1878\u1880-\u1884\u1887-\u18A8\u18AA\u18B0-\u18F5\u1900-\u191E\u1950-\u196D\u1970-\u1974\u1980-\u19AB\u19B0-\u19C9\u1A00-\u1A16\u1A20-\u1A54\u1AA7\u1B05-\u1B33\u1B45-\u1B4B\u1B83-\u1BA0\u1BAE\u1BAF\u1BBA-\u1BE5\u1C00-\u1C23\u1C4D-\u1C4F\u1C5A-\u1C7D\u1C80-\u1C88\u1C90-\u1CBA\u1CBD-\u1CBF\u1CE9-\u1CEC\u1CEE-\u1CF3\u1CF5\u1CF6\u1CFA\u1D00-\u1DBF\u1E00-\u1F15\u1F18-\u1F1D\u1F20-\u1F45\u1F48-\u1F4D\u1F50-\u1F57\u1F59\u1F5B\u1F5D\u1F5F-\u1F7D\u1F80-\u1FB4\u1FB6-\u1FBC\u1FBE\u1FC2-\u1FC4\u1FC6-\u1FCC\u1FD0-\u1FD3\u1FD6-\u1FDB\u1FE0-\u1FEC\u1FF2-\u1FF4\u1FF6-\u1FFC\u2071\u207F\u2090-\u209C\u2102\u2107\u210A-\u2113\u2115\u2119-\u211D\u2124\u2126\u2128\u212A-\u212D\u212F-\u2139\u213C-\u213F\u2145-\u2149\u214E\u2183\u2184\u2C00-\u2C2E\u2C30-\u2C5E\u2C60-\u2CE4\u2CEB-\u2CEE\u2CF2\u2CF3\u2D00-\u2D25\u2D27\u2D2D\u2D30-\u2D67\u2D6F\u2D80-\u2D96\u2DA0-\u2DA6\u2DA8-\u2DAE\u2DB0-\u2DB6\u2DB8-\u2DBE\u2DC0-\u2DC6\u2DC8-\u2DCE\u2DD0-\u2DD6\u2DD8-\u2DDE\u2E2F\u3005\u3006\u3031-\u3035\u303B\u303C\u3041-\u3096\u309D-\u309F\u30A1-\u30FA\u30FC-\u30FF\u3105-\u312F\u3131-\u318E\u31A0-\u31BA\u31F0-\u31FF\u3400-\u4DB5\u4E00-\u9FEF\uA000-\uA48C\uA4D0-\uA4FD\uA500-\uA60C\uA610-\uA61F\uA62A\uA62B\uA640-\uA66E\uA67F-\uA69D\uA6A0-\uA6E5\uA717-\uA71F\uA722-\uA788\uA78B-\uA7BF\uA7C2-\uA7C6\uA7F7-\uA801\uA803-\uA805\uA807-\uA80A\uA80C-\uA822\uA840-\uA873\uA882-\uA8B3\uA8F2-\uA8F7\uA8FB\uA8FD\uA8FE\uA90A-\uA925\uA930-\uA946\uA960-\uA97C\uA984-\uA9B2\uA9CF\uA9E0-\uA9E4\uA9E6-\uA9EF\uA9FA-\uA9FE\uAA00-\uAA28\uAA40-\uAA42\uAA44-\uAA4B\uAA60-\uAA76\uAA7A\uAA7E-\uAAAF\uAAB1\uAAB5\uAAB6\uAAB9-\uAABD\uAAC0\uAAC2\uAADB-\uAADD\uAAE0-\uAAEA\uAAF2-\uAAF4\uAB01-\uAB06\uAB09-\uAB0E\uAB11-\uAB16\uAB20-\uAB26\uAB28-\uAB2E\uAB30-\uAB5A\uAB5C-\uAB67\uAB70-\uABE2\uAC00-\uD7A3\uD7B0-\uD7C6\uD7CB-\uD7FB\uF900-\uFA6D\uFA70-\uFAD9\uFB00-\uFB06\uFB13-\uFB17\uFB1D\uFB1F-\uFB28\uFB2A-\uFB36\uFB38-\uFB3C\uFB3E\uFB40\uFB41\uFB43\uFB44\uFB46-\uFBB1\uFBD3-\uFD3D\uFD50-\uFD8F\uFD92-\uFDC7\uFDF0-\uFDFB\uFE70-\uFE74\uFE76-\uFEFC\uFF21-\uFF3A\uFF41-\uFF5A\uFF66-\uFFBE\uFFC2-\uFFC7\uFFCA-\uFFCF\uFFD2-\uFFD7\uFFDA-\uFFDC\u{10000}-\u{1000B}\u{1000D}-\u{10026}\u{10028}-\u{1003A}\u{1003C}\u{1003D}\u{1003F}-\u{1004D}\u{10050}-\u{1005D}\u{10080}-\u{100FA}\u{10280}-\u{1029C}\u{102A0}-\u{102D0}\u{10300}-\u{1031F}\u{1032D}-\u{10340}\u{10342}-\u{10349}\u{10350}-\u{10375}\u{10380}-\u{1039D}\u{103A0}-\u{103C3}\u{103C8}-\u{103CF}\u{10400}-\u{1049D}\u{104B0}-\u{104D3}\u{104D8}-\u{104FB}\u{10500}-\u{10527}\u{10530}-\u{10563}\u{10600}-\u{10736}\u{10740}-\u{10755}\u{10760}-\u{10767}\u{10800}-\u{10805}\u{10808}\u{1080A}-\u{10835}\u{10837}\u{10838}\u{1083C}\u{1083F}-\u{10855}\u{10860}-\u{10876}\u{10880}-\u{1089E}\u{108E0}-\u{108F2}\u{108F4}\u{108F5}\u{10900}-\u{10915}\u{10920}-\u{10939}\u{10980}-\u{109B7}\u{109BE}\u{109BF}\u{10A00}\u{10A10}-\u{10A13}\u{10A15}-\u{10A17}\u{10A19}-\u{10A35}\u{10A60}-\u{10A7C}\u{10A80}-\u{10A9C}\u{10AC0}-\u{10AC7}\u{10AC9}-\u{10AE4}\u{10B00}-\u{10B35}\u{10B40}-\u{10B55}\u{10B60}-\u{10B72}\u{10B80}-\u{10B91}\u{10C00}-\u{10C48}\u{10C80}-\u{10CB2}\u{10CC0}-\u{10CF2}\u{10D00}-\u{10D23}\u{10F00}-\u{10F1C}\u{10F27}\u{10F30}-\u{10F45}\u{10FE0}-\u{10FF6}\u{11003}-\u{11037}\u{11083}-\u{110AF}\u{110D0}-\u{110E8}\u{11103}-\u{11126}\u{11144}\u{11150}-\u{11172}\u{11176}\u{11183}-\u{111B2}\u{111C1}-\u{111C4}\u{111DA}\u{111DC}\u{11200}-\u{11211}\u{11213}-\u{1122B}\u{11280}-\u{11286}\u{11288}\u{1128A}-\u{1128D}\u{1128F}-\u{1129D}\u{1129F}-\u{112A8}\u{112B0}-\u{112DE}\u{11305}-\u{1130C}\u{1130F}\u{11310}\u{11313}-\u{11328}\u{1132A}-\u{11330}\u{11332}\u{11333}\u{11335}-\u{11339}\u{1133D}\u{11350}\u{1135D}-\u{11361}\u{11400}-\u{11434}\u{11447}-\u{1144A}\u{1145F}\u{11480}-\u{114AF}\u{114C4}\u{114C5}\u{114C7}\u{11580}-\u{115AE}\u{115D8}-\u{115DB}\u{11600}-\u{1162F}\u{11644}\u{11680}-\u{116AA}\u{116B8}\u{11700}-\u{1171A}\u{11800}-\u{1182B}\u{118A0}-\u{118DF}\u{118FF}\u{119A0}-\u{119A7}\u{119AA}-\u{119D0}\u{119E1}\u{119E3}\u{11A00}\u{11A0B}-\u{11A32}\u{11A3A}\u{11A50}\u{11A5C}-\u{11A89}\u{11A9D}\u{11AC0}-\u{11AF8}\u{11C00}-\u{11C08}\u{11C0A}-\u{11C2E}\u{11C40}\u{11C72}-\u{11C8F}\u{11D00}-\u{11D06}\u{11D08}\u{11D09}\u{11D0B}-\u{11D30}\u{11D46}\u{11D60}-\u{11D65}\u{11D67}\u{11D68}\u{11D6A}-\u{11D89}\u{11D98}\u{11EE0}-\u{11EF2}\u{12000}-\u{12399}\u{12480}-\u{12543}\u{13000}-\u{1342E}\u{14400}-\u{14646}\u{16800}-\u{16A38}\u{16A40}-\u{16A5E}\u{16AD0}-\u{16AED}\u{16B00}-\u{16B2F}\u{16B40}-\u{16B43}\u{16B63}-\u{16B77}\u{16B7D}-\u{16B8F}\u{16E40}-\u{16E7F}\u{16F00}-\u{16F4A}\u{16F50}\u{16F93}-\u{16F9F}\u{16FE0}\u{16FE1}\u{16FE3}\u{17000}-\u{187F7}\u{18800}-\u{18AF2}\u{1B000}-\u{1B11E}\u{1B150}-\u{1B152}\u{1B164}-\u{1B167}\u{1B170}-\u{1B2FB}\u{1BC00}-\u{1BC6A}\u{1BC70}-\u{1BC7C}\u{1BC80}-\u{1BC88}\u{1BC90}-\u{1BC99}\u{1D400}-\u{1D454}\u{1D456}-\u{1D49C}\u{1D49E}\u{1D49F}\u{1D4A2}\u{1D4A5}\u{1D4A6}\u{1D4A9}-\u{1D4AC}\u{1D4AE}-\u{1D4B9}\u{1D4BB}\u{1D4BD}-\u{1D4C3}\u{1D4C5}-\u{1D505}\u{1D507}-\u{1D50A}\u{1D50D}-\u{1D514}\u{1D516}-\u{1D51C}\u{1D51E}-\u{1D539}\u{1D53B}-\u{1D53E}\u{1D540}-\u{1D544}\u{1D546}\u{1D54A}-\u{1D550}\u{1D552}-\u{1D6A5}\u{1D6A8}-\u{1D6C0}\u{1D6C2}-\u{1D6DA}\u{1D6DC}-\u{1D6FA}\u{1D6FC}-\u{1D714}\u{1D716}-\u{1D734}\u{1D736}-\u{1D74E}\u{1D750}-\u{1D76E}\u{1D770}-\u{1D788}\u{1D78A}-\u{1D7A8}\u{1D7AA}-\u{1D7C2}\u{1D7C4}-\u{1D7CB}\u{1E100}-\u{1E12C}\u{1E137}-\u{1E13D}\u{1E14E}\u{1E2C0}-\u{1E2EB}\u{1E800}-\u{1E8C4}\u{1E900}-\u{1E943}\u{1E94B}\u{1EE00}-\u{1EE03}\u{1EE05}-\u{1EE1F}\u{1EE21}\u{1EE22}\u{1EE24}\u{1EE27}\u{1EE29}-\u{1EE32}\u{1EE34}-\u{1EE37}\u{1EE39}\u{1EE3B}\u{1EE42}\u{1EE47}\u{1EE49}\u{1EE4B}\u{1EE4D}-\u{1EE4F}\u{1EE51}\u{1EE52}\u{1EE54}\u{1EE57}\u{1EE59}\u{1EE5B}\u{1EE5D}\u{1EE5F}\u{1EE61}\u{1EE62}\u{1EE64}\u{1EE67}-\u{1EE6A}\u{1EE6C}-\u{1EE72}\u{1EE74}-\u{1EE77}\u{1EE79}-\u{1EE7C}\u{1EE7E}\u{1EE80}-\u{1EE89}\u{1EE8B}-\u{1EE9B}\u{1EEA1}-\u{1EEA3}\u{1EEA5}-\u{1EEA9}\u{1EEAB}-\u{1EEBB}\u{20000}-\u{2A6D6}\u{2A700}-\u{2B734}\u{2B740}-\u{2B81D}\u{2B820}-\u{2CEA1}\u{2CEB0}-\u{2EBE0}\u{2F800}-\u{2FA1D}]+/u.test('ŁŻŹĆ'));
```
unless target supports unicode regex

**Environment**
- Babel version(s): v7.4.0
https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgziA2CmB00QHMAUB6A2gHQA4G8AZAX2wBMB9AXQGp0BXeAF1gidQHJBBQEG9AQT0BAYIAcAlMIDcQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=Node-8.9&version=7.4.3&externalPlugins=

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

### LINKED ISSUE #10367: Named capturing groups cause crashes on the unicode regexp transform
## Bug Report

**Current Behavior**
Adding the `u` flag to a regexp with a named capturing group causes babel to crash if any transform related to unicode regexps is also enabled. This happens even when the named capturing group transform is enabled in preset-env, likely due to plugin execution order.

**Input Code**
- [REPL link](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=true&loose=false&code_lz=PTAECcFMFsHsDcCWA7A5qALgC0QZ1AETyyIAmBoMiG-K8AhgDZmgDGspkAUMS8ABQAdXAEpgPEqVADhYgK4S-_APwAeXAAd6rSAD5Z4kKDnJ20aJGQYU6bHjb05uSPnqgt4Z5XDhY4LiC8UgJqmtp6BgpAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env&prettier=true&targets=Node-8.9&version=7.5.5&externalPlugins=)

```js
void /(?<test>foo)/u
```

**Expected behavior/code**
```js
void _wrapRegExp(/(foo)/, {
  test: 1
})
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    "env"
  ]
}
```

**Environment**
- Babel version(s): 7.4.3
- Node/npm version: 12.6.0
- OS: macOS 10.14
- Monorepo: yes
- How you are using Babel: loader

**Possible Solution**
The named capturing group transform could run before the other transforms; or regexpu should get support for parsing and preserving named capturing groups

**Additional context/Screenshots**
While writing a reproduction to this I also [found an emit bug](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=true&loose=false&code_lz=PQQ2G4ChgCgfgDwBcCmBnJA-EBKYkg&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env&prettier=true&targets=Node-8.9&version=7.5.5&externalPlugins=) when babel helpers are injected and the first statement is a regexp literal. Not related, just a coincidence.

### LINKED ISSUE #10601: Regression in @babel/plugin-transform-named-capturing-groups-regex with unicode regexps
## Bug Report

**Current Behavior**
Likely a regression from https://github.com/babel/babel/pull/10430, but the contents of `u` regexps are getting transformed to being non-`u` without updating a regexp's flags. The problem becomes a more serious bug when the `s` flag is also present, as the transformed `.` no longer matches newlines.

**Input Code**
- [REPL link](https://babeljs.io/repl#?babili=false&code_lz=MYewdgzgLgBATgUxgXhgegDwAoD8GoCGA5gHwA6AJgJQDUJAdAFR5lpkDW-xJJaEArgChQkEABsE9MSCJZE9KAmhYA5BgAMJAB46yYAJ6GMaTSqpV0aGBAAWIfmIowARkihx-CIA&presets=&prettier=true&version=7.6.4&externalPlugins=%40babel%2Fplugin-transform-named-capturing-groups-regex%407.6.3)

```js
const re = /<(?<tag>\d)+>.*?<\/\k<tag>>/su
console.log(re.test('<0>xxx\nyyy</0>')) // should be true
```

- [Link using an older version of the plugin, without the regression](https://babeljs.io/repl#?babili=false&code_lz=MYewdgzgLgBATgUxgXhgegDwAoD8GoCGA5gHwA6AJgJQDUJAdAFR5lpkDW-xJJaEArgChQkEABsE9MSCJZE9KAmhYA5BgAMJAB46yYAJ6GMaTSqpV0aGBAAWIfmIowARkihx-CIA&presets=&prettier=true&version=7.6.4&externalPlugins=%40babel%2Fplugin-transform-named-capturing-groups-regex%407.4.5)

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

Output with `@7.4.5` (ignoring helpers, just the regexp):

```js
/<(\d)+>.*?<\/\1>/su
```

Output with `@7.6.3`:

```js
/<([0-9])+>(?:[\0-\t\x0B\f\x0E-\u2027\u202A-\uD7FF\uE000-\uFFFF]|[\uD800-\uDBFF][\uDC00-\uDFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF])*?<\/\1>/su
```

Note how the regexp, which didn't even have to be transformed _from_ being a unicode regexp (and didn't remove the `u` flag after doing it), specifically skips over both `\x0A` and `\x0D`, the `\n` and `\r` characters, which are supposed to be matched because the regexp has the `s` flag.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "plugins": ["plugin-transform-named-capturing-groups-regex"]
}
```

**Environment**
- Babel version(s): 7.6.4
- Node/npm version: v12.10.0 / yarn 1.19.1
- OS: macOS 10.15
- Monorepo: yes
- How you are using Babel: `babel-jest`

**Possible Solution**
Need some way to tell `regexpu` to not do the unicode downleveling; or if unicode transformation is "inevitable" the `dotAll` flag needs to be respected.

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #8951, closes #10347, fixes #10367, fixes #9892, fixes #9199, fixes #10601 
| Patch: Bug Fix?          | Yes
| Tests Added + Pass?      | Yes
| Any Dependency Changes?  | Yes
| License                  | MIT

This PR is includes refactor on #10430. I will rebase once it gets merged.

In this PR we merge multiple regex transformers into a single meta plugin so that regex transform can be finished in one-pass. The current modular transform plugin is essentially turned into transformer switches. By doing this we provide support for multiple ESNext regex features
such as `/(?<name>\p{Unified_Ideograph}{3}/u`.

We also set `lookbehind: true` to `regexpu-core` so that our regex transformer can always _parse_ the lookbehind assertions. I don't think we require `babel-syntax-regex-lookahead` here as we are _not_ parsing every single regex and `lookbehind: true` is only meaningful when user used it _with_ other transformable features.

Note that although it is a bug fix, I think we may target to a 7.7.0 release as 1) it relies on upstream minor bump. 2) it introduces new package.

Todo: 
- [ ] prevent regexpu from rewritting symbol-kind `-`: https://github.com/mathiasbynens/regexpu-core/pull/31

Edits: I realize that in practice there is no browser that supports property escape but _not_ named capturing groups, as they are supported in same version, we do not rely on https://github.com/mathiasbynens/regexpu-core/pull/30 anymore.

### CODE REVIEW

File: packages/babel-plugin-transform-named-capturing-groups-regex/test/fixtures/wrapper/looks-like-a-group/output.js [hunk 1]
```diff
@@ -1 +1 @@
-/no-groups-\(?<looks-like-a-group>looks\)/;
+/no\x2Dgroups\x2D\(?<looks\x2Dlike\x2Da\x2Dgroup>looks\)/;
```
Comment (JLHwung) [inline packages/babel-plugin-transform-named-capturing-groups-regex/test/fixtures/wrapper/looks-like-a-group/output.js]: consider add simple-ascii character optimize pass to `regexpu-core`.

File: packages/babel-helper-create-regexp-features-plugin/src/util.js [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+export function generateRegexpuOptions(node, features) {
+  let useUnicodeFlag = false,
+    dotAllFlag = false,
+    unicodePropertyEscape = false,
+    namedGroup = false;
+  const { flags, pattern } = node;
+  const flagsIncludesU = flags.includes("u");
+
+  if (flagsIncludesU === true) {
+    if (hasFeature(features, FEATURES.unicodeFlag) === false) {
```
Comment (nicolo-ribaudo) [inline packages/babel-helper-create-regexp-features-plugin/src/util.js]: Nit: Don't you like `!`? :stuck_out_tongue: 
Also all the `=== true`s are unnecessary.

File: packages/babel-helper-create-regexp-features-plugin/src/util.js [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+    hasFeature(features, FEATURES.namedCaptureGroups) &&
+    /\(\?<(?![=!])/.test(pattern)
+  ) {
+    namedGroup = true;
+  }
+  if (
+    namedGroup === false &&
+    unicodePropertyEscape === false &&
+    dotAllFlag === false &&
+    !(flagsIncludesU === true && hasFeature(features, FEATURES.unicodeFlag))
```
Comment (nicolo-ribaudo) [inline packages/babel-helper-create-regexp-features-plugin/src/util.js]: Nit: we could rewrite the last line as `(!flagsIncludesU || useUnicodeFlag)` and avoid the function call.

File: packages/babel-helper-create-regexp-features-plugin/src/index.js [hunk 4]
```diff
@@ -0,0 +1,96 @@
...
+    pre() {
+      const { file } = this;
+      const features = file.get(featuresKey) || 0;
+      let newFeatures = enableFeature(features, FEATURES[feature]);
+
+      const { useUnicodeFlag, runtime = true } = options;
+      if (useUnicodeFlag === false) {
+        newFeatures = enableFeature(newFeatures, FEATURES.unicodeFlag);
+      }
+      if (newFeatures > features) {
```
Comment (nicolo-ribaudo) [inline packages/babel-helper-create-regexp-features-plugin/src/index.js]: Could you add a comment like "If we turn on a new bit, it will increase"? It wasn't obvious to me.

Comment (nicolo-ribaudo) [reply packages/babel-helper-create-regexp-features-plugin/src/index.js]: Or better,
```suggestion
      if (newFeatures !== features) {
```

File: packages/babel-helper-create-regexp-features-plugin/src/util.js (hunk 2 above)
Comment (JLHwung) [reply packages/babel-helper-create-regexp-features-plugin/src/util.js]: Actually I have no preference on `!` or `=== false` until I read the compiled instructions:

This is what happens under the hood when we write `if(a) { // blablabla }`

```asm
0x1fafde0d1bf2    32  4c8b4510       REX.W movq r8,[rbp+0x10]
0x1fafde0d1bf6    36  41f6c001       testb r8,0x1
0x1fafde0d1bfa    3a  0f84cf140000   jz 0x1fafde0d30cf  <+0x150f>
                  -- B4 start --
0x1fafde0d1c00    40  4d3945f8       REX.W cmpq [r13-0x8] (root (false_value)),r8
0x1fafde0d1c04    44  0f8438000000   jz 0x1fafde0d1c42  <+0x82>
                  -- B5 start --
0x1fafde0d1c0a    4a  4d394500       REX.W cmpq [r13+0x0] (root (empty_string)),r8
0x1fafde0d1c0e    4e  0f842e000000   jz 0x1fafde0d1c42  <+0x82>
                  -- B6 start --
0x1fafde0d1c14    54  4d8b48ff       REX.W movq r9,[r8-0x1]
0x1fafde0d1c18    58  41f6410d10     testb [r9+0xd],0x10
0x1fafde0d1c1d    5d  0f851f000000   jnz 0x1fafde0d1c42  <+0x82>
                  -- B7 start --
                  -- B8 start --
0x1fafde0d1c23    63  4d398d80000000 REX.W cmpq [r13+0x80] (root (heap_number_map)),r9
0x1fafde0d1c2a    6a  0f8486140000   jz 0x1fafde0d30b6  <+0x14f6>
                  -- B9 start --
0x1fafde0d1c30    70  4d398d40010000 REX.W cmpq [r13+0x140] (root (bigint_map)),r9
0x1fafde0d1c37    77  0f8466140000   jz 0x1fafde0d30a3  <+0x14e3>
0x1fafde0d1c3d    7d  e913000000     jmp 0x1fafde0d1c55  <+0x95>
```
Basically it compares `a` to these four objects: `false`, `""`, `0` and `0n`. Since JavaScript is weak-typed, even if you know for sure `a` could only be a boolean, the compiler would not simplify `if(a)` to the following codes, which is simplified from `if(a === true)`.

```asm
0x1fafde0d1bf2    32  4c8b4510       REX.W movq r8,[rbp+0x10]
0x1fafde0d1bf6    36  41f6c001       testb r8,0x1
0x1fafde0d1bfa    3a  0f84cf140000   jz 0x1fafde0d30cf  <+0x150f>
                  -- B4 start --
0x1fafde0d1c00    40  4d3945f8       REX.W cmpq [r13-0x8] (root (false_value)),r8
0x1fafde0d1c04    44  0f8438000000   jz 0x1fafde0d1c42  <+0x82>
```

However, these branch instructions would never be our performance bottleneck thanks to complex branch prediction in our modern CPU. I am happy to rewrite into more common code style as long as you find out. 😀

File: packages/babel-helper-create-regexp-features-plugin/src/util.js (hunk 3 above)
Comment (JLHwung) [reply packages/babel-helper-create-regexp-features-plugin/src/util.js]: In practice, the function call will be inlined since it is so small. But your suggested conditions are easier to understand.

File: packages/babel-helper-create-regexp-features-plugin/src/index.js (hunk 4 above)
Comment (JLHwung) [reply packages/babel-helper-create-regexp-features-plugin/src/index.js]: Thanks, I have replaced to `!==`.

File: packages/babel-helper-create-regexp-features-plugin/src/features.js [hunk 5]
```diff
@@ -0,0 +1,35 @@
...
+//      - node_modules
+//        - @babel-plugin-regexp-features
+export const featuresKey = "@babel/plugin-regexp-features/featuresKey";
+export const runtimeKey = "@babel/plugin-regexp-features/runtimeKey";
+
+type unicodeFlag = 1;
+type dotAllFlag = 2;
+type unicodePropertyEscape = 4;
+type namedCaptureGroups = 8;
+type featureType =
```
Comment (existentialism) [inline packages/babel-helper-create-regexp-features-plugin/src/features.js]: Not huge, but if we collapse the `FEATURES` enum, this can be simplified to:

```js
const FEATURES = Object.freeze({
  unicodeFlag: 1,
  dotAllFlag: 2,
  unicodePropertyEscape: 4,
  namedCaptureGroups: 8,
});
  
type FeatureType = $Values<typeof FEATURES>;
```

File: packages/babel-helper-create-regexp-features-plugin/src/index.js [hunk 6]
```diff
@@ -0,0 +1,96 @@
...
+
+import pkg from "../package.json";
+import { types as t } from "@babel/core";
+import { pullFlag } from "@babel/helper-regex";
+
+// Note: Versions are represented as an integer. e.g. 7.1.5 is represented
+//       as 70000100005. This method is easier than using a semver-parsing
+//       package, but it breaks if we release x.y.z where x, y or z are
+//       greater than 99_999.
+const version = pkg.version.split(".").reduce((v, x) => v * 1e5 + +x, 0);
```
Comment (existentialism) [inline packages/babel-helper-create-regexp-features-plugin/src/index.js]: FWIW, I think it's perfectly fine using `semver` to parse (since we use it elsewhere)

File: packages/babel-plugin-proposal-unicode-property-regex/package.json [hunk 7]
```diff
@@ -23,8 +23,7 @@
   "bugs": "https://github.com/babel/babel/issues",
   "dependencies": {
     "@babel/helper-plugin-utils": "^7.0.0",
-    "@babel/helper-regex": "^7.4.4",
-    "regexpu-core": "^4.6.0"
+    "@babel/helper-create-regexp-features-plugin": "^7.6.0"
```
Comment (existentialism) [inline packages/babel-plugin-proposal-unicode-property-regex/package.json]: Nit, should come before `@babel/helper-plugin-utils`

File: packages/babel-plugin-proposal-unicode-property-regex/src/index.js [hunk 8]
```diff
@@ -10,23 +10,9 @@ export default declare((api, options) => {
     throw new Error(".useUnicodeFlag must be a boolean, or undefined");
   }
 
-  return {
+  return createRegExpFeaturePlugin({
```
Comment (existentialism) [inline packages/babel-plugin-proposal-unicode-property-regex/src/index.js]: 💯, clean!

File: packages/babel-helper-create-regexp-features-plugin/src/index.js (hunk 6 above)
Comment (nicolo-ribaudo) [reply packages/babel-helper-create-regexp-features-plugin/src/index.js]: It's my fault 😛

Comment (JLHwung) [reply packages/babel-helper-create-regexp-features-plugin/src/index.js]: I think it is okay to leave it as is because all we need is a version sorter and we are not using `semver` elsewhere.

File: packages/babel-helper-create-regexp-features-plugin/src/features.js (hunk 5 above)
Comment (JLHwung) [reply packages/babel-helper-create-regexp-features-plugin/src/features.js]: Addressed in e8b960c.

**Comment by JLHwung** [comment]
@existentialism @nicolo-ribaudo A new fix 7fbd168  has been pushed since you reviewed. In this fix we apply `dotAllFlag` when `flags` includes `u` and we have to apply `rewritePattern`.

Note that this approach is not ideal. I will propose a `useDotAllFlag` to `regexpu-core` so we can preserve the `s` flag if we are not instructed to transform them. And we can expect subsequent fixes coming in v7.7.x.

File: packages/babel-helper-create-regexp-features-plugin/README.md [hunk 9]
```diff
@@ -0,0 +1,19 @@
+# @babel/helper-create-regexp-features-plugin
+
+> Compile ESNext Regular Expressions to ES5
+
+See our website [@babel/helper-create-regexp-features-plugin](https://babeljs.io/docs/en/next/babel-helper-create-regexp-features-plugin.html) for more information.
```
Comment (peey) [inline packages/babel-helper-create-regexp-features-plugin/README.md]: This link is dead. Is there supposed to be anything here?
