### PR TITLE
fix: Certain comments cause `generator` exceptions

### LINKED ISSUE #14809: [Bug]: parse return type with comments fail with @babel/generator
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Vite

### Input code

```ts
const test = (): {
  // test
  foo: string;
} => {
  return {
    foo: "bar",
  };
};

export default test;
```

### Configuration file name

.babelrc

### Configuration

```json
{
  "parserOpts": {
    "plugins": ["typescript"]
  }
}
```

### Current and expected behavior

Throw error with `@babel/generator@7.18.9`(latest):

```
TypeError: /tmp/reproduce/test.ts: Cannot read properties of undefined (reading 'charCodeAt')
    at Generator._append (/tmp/reproduce/node_modules/.pnpm/@babel+generator@7.18.9/node_modules/@babel/generator/lib/printer.js:210:27)
    at Buffer.withSource (/tmp/reproduce/node_modules/.pnpm/@babel+generator@7.18.9/node_modules/@babel/generator/lib/buffer.js:291:28)
    at Generator.withSource (/tmp/reproduce/node_modules/.pnpm/@babel+generator@7.18.9/node_modules/@babel/generator/lib/printer.js:196:15)
    at Generator._printComment (/tmp/reproduce/node_modules/.pnpm/@babel+generator@7.18.9/node_modules/@babel/generator/lib/printer.js:566:10)
    at Generator._printComments (/tmp/reproduce/node_modules/.pnpm/@babel+generator@7.18.9/node_modules/@babel/generator/lib/printer.js:577:14)
    at Generator._printLeadingComments (/tmp/reproduce/node_modules/.pnpm/@babel+generator@7.18.9/node_modules/@babel/generator/lib/printer.js:473:10)
    at Generator.print (/tmp/reproduce/node_modules/.pnpm/@babel+generator@7.18.9/node_modules/@babel/generator/lib/printer.js:369:10)
    at tsPrintBraced (/tmp/reproduce/node_modules/.pnpm/@babel+generator@7.18.9/node_modules/@babel/generator/lib/generators/typescript.js:386:15)
    at Generator.tsPrintTypeLiteralOrInterfaceBody (/tmp/reproduce/node_modules/.pnpm/@babel+generator@7.18.9/node_modules/@babel/generator/lib/generators/typescript.js:375:3)
    at Generator.TSTypeLiteral (/tmp/reproduce/node_modules/.pnpm/@babel+generator@7.18.9/node_modules/@babel/generator/lib/generators/typescript.js:371:8) {
  code: 'BABEL_GENERATE_ERROR'
}
```

Works with `@babel/generator@7.18.7`:

```
const test = (): {
  // test
  foo: string;
} => {
  return {
    foo: "bar"
  };
};

export default test;
```

### Environment

  System:
    OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
  Binaries:
    Node: 18.4.0 - ~/.nvm/versions/node/v18.4.0/bin/node
    npm: 8.13.2 - ~/.nvm/versions/node/v18.4.0/bin/npm
  npmPackages:
    @babel/cli: ^7.18.9 => 7.18.9 
    @babel/core: ^7.18.9 => 7.18.9 

### Possible solution

_No response_

### Additional context

I found this issue from [`@vitejs/plugin-react`](https://www.npmjs.com/package/@vitejs/plugin-react) and I used npm pnpm overrides / yarn resolutions as workaround:

```json
{
  "pnpm": {
    "overrides": {
      "@babel/generator": "7.18.7"
    }
  }
}
```

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #14809  
| Patch: Bug Fix?          |√
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | √
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14810"></a>

### CODE REVIEW

File: packages/babel-generator/src/printer.ts [hunk 1]
```diff
@@ -799,22 +798,17 @@ class Printer {
...
         );
         val = val.replace(/\n(?!$)/g, `\n${" ".repeat(indentSize)}`);
-
-        maybeNewline = true;
       }
     } else if (!this._noLineTerminator) {
       val = `//${comment.value}\n`;
-      maybeNewline = true;
+    } else {
+      val = `/*${comment.value}*/`;
```
Comment (nicolo-ribaudo) [inline packages/babel-generator/src/printer.ts:805]: This case is for when we had a line comment but we cannot have a line terminator? When can it happen?

Comment (liuxingbaoyu) [reply packages/babel-generator/src/printer.ts:809]: It's in the associated issue. I also added to the test.
You said that and it reminded me that it doesn't contain newlines!😄

Comment (liuxingbaoyu) [reply packages/babel-generator/src/printer.ts:809]: Testing doesn't seem to reflect this.😕

Tested on my local.
```ts
const test = (): {
  /* test*/foo: string;
} => {
  return {
    foo: "bar"
  };
};

export default test;
```

Comment (liuxingbaoyu) [reply packages/babel-generator/src/printer.ts:809]: https://github.com/babel/babel/pull/14758
https://github.com/babel/babel/pull/14762

Oh no, after a long time, I finally found the reason.
Only the first pr was published, and the second was not.

So this test is useless, we need to find another one.

By the way, can you release a new version of `jest-light-runner`?
Filtering of tests can be helpful in debugging generators and parsers.

**Review by JLHwung — APPROVED** [review]
