### PR TITLE
fix typescript for babel-types

### LINKED ISSUE #10065: `decorators` field is not present on `ClassPrivateProperty` in type declarations or documentation, but is in AST
## Bug Report

**Current Behavior**
Neither type declarations nor documentation indicate the presence of a `decorators` field on a `ClassPrivateProperty` node, while it is present in the AST.

**Input Code**
[AST explorer](https://astexplorer.net/#/gist/866ff157d68b2f148c75365361774b80/abf6c150530abdc194b2af45fc19ffd90fbcddb7)

```js
class Foo {
  @Decorator
  #prop = '';
}
```

**Expected behavior/code**
The `decorators` field should be present in both documentation and type declarations.

**Babel Configuration (.babelrc, package.json, cli command)**
Just needs private class fields and decorators enabled, as indicated by link above.

**Environment**
- Babel version(s): v7.4.0
- Node/npm version: Node 12.0.0, npm 6.9.0
- OS: Ubuntu 19.04
- Monorepo: no
- How you are using Babel: CLI

### PR DESCRIPTION
**Pull request by tanhauhau**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #10065, #10075, #8375
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

**Comment by jhpratt** [comment]
LGTM. I'd obviously prefer Babel used TS over Flow, as it's far more popular, but this PR should fix the issues I've found, at least.

**Comment by tanhauhau** [comment]
> Looking at CI, there's one instance where you put object instead of Object for the type declaration.

Oops, because I copied over from `generators/typescript` 🙈

File: packages/babel-types/scripts/generators/flow.js [hunk 1]
```diff
@@ -99,6 +99,14 @@ for (const type in t.NODE_FIELDS) {
         ", "
       )}): ${NODE_PREFIX}${type};`
     );
+  } else {
+    const functionName = toFunctionName(type);
+    lines.push(
+      `declare function _${functionName}(${args.join(
```
Comment (nicolo-ribaudo) [inline packages/babel-types/scripts/generators/flow.js]: Maybe this should be `export declare function ${type}`? They always start with an uppercase letter (thus are valid identifiers), and it would match https://github.com/babel/babel/blob/6467cd1e27ffe2a3a1cfe97bc8c67b407cb1e7c4/packages/babel-types/src/builders/generated/index.js

Comment (tanhauhau) [reply packages/babel-types/scripts/generators/flow.js]: @nicolo-ribaudo what do you think?

**Comment by nicolo-ribaudo** [comment]
CircleCI failure is unrelated.
