### PR TITLE
fix: support named evaluation for using declaration

### LINKED ISSUE #17270: `using` declaration transform does not respect named evaluation
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

[REPL](https://babel.dev/repl#?browsers=chrome%2079&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=K4Zwlgdg5gBAZgewTAvDAxgGwIYhDAbxhABdsSx0YBtAZQE8BbAIwUwDoATMEABwRABTALoAKAJSEAvjCkAodAggg2g9pgRRRiBOwjZGg8UA&forceAllTransforms=false&modules=umd&shippedProposals=false&evaluate=true&fileSize=false&timeTravel=true&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.27.0&externalPlugins=%40babel%2Fplugin-proposal-explicit-resource-management%407.25.9&assumptions=%7B%7D)

```js
using foo = class { static [Symbol.dispose]() {} }
console.log(foo.name)
```

### Configuration file name

_No response_

### Configuration

```json
{
  "plugins": ["@babel/plugin-proposal-explicit-resource-management"]
}
```

### Current and expected behavior

Current: it prints empty string

Expected: it prints `foo`.

### Environment

REPL

### Possible solution

TS emits `__setFunctionName` for the rhs. We can handle this issue in a similar approach.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #17270 
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

Although adding name to class id generally works, in this PR we choose the `setFunctionName` approach because `using ... = class {}` is probably not very popular, I think it is acceptable to trade off output size for spec compliance here.

### CODE REVIEW

File: packages/babel-plugin-proposal-explicit-resource-management/test/fixtures/transform-sync/named-evaluation/output.js [hunk 1]
```diff
@@ -0,0 +1,16 @@
+let log = [];
+let Symbol$dispose = Symbol.dispose || Symbol.for("Symbol.dispose");
+try {
+  var _m;
+  var _usingCtx = babelHelpers.usingCtx();
+  const foo = _usingCtx.u((_m = class {
+    static [Symbol$dispose]() {
+      log.push(`${foo.name} is disposed`);
+    }
+  }, babelHelpers.setFunctionName(_m, "foo")));
```
Comment (liuxingbaoyu) [inline packages/babel-plugin-proposal-explicit-resource-management/test/fixtures/transform-sync/named-evaluation/output.js:10]: `_usingCtx.u(babelHelpers.setFunctionName(class {}, "foo")))`
Is there any difference with this?

**Review by liuxingbaoyu — APPROVED** [review]
