### PR TITLE
fix: Destructuring exceptions `for ( let { } = 0 ; 0 ; ) `

### LINKED ISSUE #15100: [Bug]: (Babel transpilation fail) Empty object destructuring in for-lexical declaration should be allowed
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
for ( let { } = 0 ; 0 ; ) ;
```

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

The input code has no problem, but Babel throws error while transpiling the code.
```
$ node
Welcome to Node.js v18.11.0.
Type ".help" for more information.
> for ( let { } = 0 ; 0 ; ) ;
undefined
```

### Environment

[Reproduction on Babel's own REPL](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=GYewTgBAFBA2CmAXCBvCBfCBeCAGCA3HoRAJSFA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=true&targets=&version=7.20.0&externalPlugins=&assumptions=%7B%7D)

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #15100 
| Patch: Bug Fix?          | √
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | √
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

ref: https://github.com/babel/babel/pull/14841

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15104"></a>

### CODE REVIEW

File: packages/babel-plugin-transform-destructuring/test/fixtures/destructuring/destructuring-empty-in-for/output.js [hunk 1]
```diff
@@ -14,3 +14,11 @@ for (var _x2 in y) {
...
   }
 }
+for (function () {
+  var _ret;
+  var _ = 0;
+  _ret = babelHelpers.objectDestructuringEmpty(_);
+  return _ret;
+}(); 0;) {
+  ;
+}
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-destructuring/test/fixtures/destructuring/destructuring-empty-in-for/output.js:24]: Can we just generate this code?
```js
for (babelHelpers.objectDestructuringEmpty(0); 0; ) {
  ;
}
```

File: packages/babel-plugin-transform-destructuring/src/util.ts [hunk 2]
```diff
@@ -663,9 +659,32 @@ export function convertVariableDeclaration(
...
+    nodesOut.push(node);
+  }
+
+  if (
+    nodesOut.length === 2 &&
+    t.isVariableDeclaration(nodesOut[0]) &&
+    t.isExpressionStatement(nodesOut[1]) &&
+    t.isCallExpression(nodesOut[1].expression) &&
+    nodesOut[0].declarations.length === 1
+  ) {
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-destructuring/src/util.ts:671]:
```suggestion
  if (
    nodesOut.length === 2 &&
    t.isVariableDeclaration(nodesOut[0]) &&
    t.isExpressionStatement(nodesOut[1]) &&
    t.isCallExpression(nodesOut[1].expression) &&
    nodesOut[0].declarations.length === 1
  ) {
    // This can only happen when we generate this code:
    //    var _ref = DESTRUCTURED_VALUE;
    //     babelHelpers.objectDestructuringEmpty(_ref);
    // Since pushing those two statements to the for loop .init will require an IIFE,
    // we can optimize them to
    //     babelHelpers.objectDestructuringEmpty(DESTRUCTURED_VALUE);
```

**Review by nicolo-ribaudo — APPROVED** [review]

**Review by JLHwung — APPROVED** [review]
