### PR TITLE
assertNoDuplicates throw with more context

### LINKED ISSUE #9778: babel-core doesn't list which plugins/presets are duplicated
## Bug Report

**Current Behavior**
babel-core doesn't list which plugins/presets are duplicated:

```
   Duplicate plugin/preset detected.
    If you'd like to use two separate instances of a plugin,
    they need separate names, e.g.

      plugins: [
        ['some-plugin', {}],
        ['some-plugin', {}, 'some unique name'],
      ]

      at assertNoDuplicates (node_modules/@babel/core/lib/config/config-descriptors.js:205:13)
      at createDescriptors (node_modules/@babel/core/lib/config/config-descriptors.js:114:3)
      at createPluginDescriptors (node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
      at alias (node_modules/@babel/core/lib/config/config-descriptors.js:63:49)
      at cachedFunction (node_modules/@babel/core/lib/config/caching.js:33:19)
      at plugins.plugins (node_modules/@babel/core/lib/config/config-descriptors.js:28:77)
      at mergeChainOpts (node_modules/@babel/core/lib/config/config-chain.js:319:26)
      at node_modules/@babel/core/lib/config/config-chain.js:283:7
      at buildRootChain (node_modules/@babel/core/lib/config/config-chain.js:68:29)
      at loadPrivatePartialConfig (node_modules/@babel/core/lib/config/partial.js:85:55)
```

**Expected behavior/code**
A list of duplicate plugins/presets so that you know which ones to remove or rename.

**Babel Configuration (.babelrc, package.json, cli command)**

```json
  "babel": {
    "plugins": [
      "@babel/plugin-proposal-class-properties",
      "@babel/plugin-syntax-dynamic-import",
      "@babel/plugin-transform-runtime",
      "babel-plugin-istanbul",
      "babel-plugin-styled-components",
      "syntax-export-extensions"
    ],
    "presets": [
      ["@babel/preset-env", {
        "debug": true
      }],
      ["@babel/preset-react", { "debug":  true }]
    ]
  },
```

**Environment**
- Babel version(s): 7.4.0
- Node/npm version: Node 10/npm 6
- OS: macOS 10.14.3

### PR DESCRIPTION
**Pull request by hjdivad**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #9778 
| Patch: Bug Fix?          | No
| Major: Breaking Change?  | No
| Minor: New Feature?      | Yes
| Tests Added + Pass?      | Yes
| Documentation PR Link    | N/A
| Any Dependency Changes?  | No
| License                  | MIT

When users see errors like

```
Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]
```

It can be difficult to determine the source of the conflict, especially
in a larger build system.

This commit outputs what is known about the plugins that actually
conflict, which can be helpful for users to determine the root cause of
the conflict.

New example output on conflict:
```
Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]

Duplicates detected are:
[
      "root": "/Users/dhamilto/src/linkedin/ember-cli-pemberly-m3",
      "name": "ember-m3"
    },
    "dirname": "/Users/dhamilto/src/linkedin/ember-cli-pemberly-m3",
    "ownPass": false,
    "file": {
      "request": "/Users/dhamilto/src/linkedin/ember-cli-pemberly-m3/node_modules/ember-compatibilit
y-helpers/comparision-plugin.js",
      "resolved": "/Users/dhamilto/src/linkedin/ember-cli-pemberly-m3/node_modules/ember-compatibili
ty-helpers/comparision-plugin.js"
    }
  },
  {
    "alias": "/Users/dhamilto/src/linkedin/ember-cli-pemberly-m3/node_modules/ember-compatibility-he
y-helpers/comparision-plugin.js",
      "resolved": "/Users/dhamilto/src/linkedin/ember-cli-pemberly-m3/node_modules/ember-compatibili
ty-helpers/comparision-plugin.js"
    }
  }
]
```

Partially addresses #9778

### CODE REVIEW

**Comment by hjdivad** [comment]
Note that this commit only outputs the conflicts that triggered a particular assertion.

It could in principle output all conflicts, but I'd be concerned about the output getting too large.

File: packages/babel-core/test/option-manager.js [hunk 1]
```diff
@@ -27,14 +27,19 @@ describe("option-manager", () => {
...
-      const { calls, plugin } = makePlugin();
+    it("should throw if a plugin is repeated, with information about the repeated plugin", () => {
+      const { calls, plugin } = makePlugin("my-plugin");
 
       expect(() => {
         loadOptions({
-          plugins: [plugin, plugin],
+          plugins: [
+            [plugin, undefined, "my-plugin"],
+            [plugin, undefined, "my-plugin"],
```
Comment (nicolo-ribaudo) [inline packages/babel-core/test/option-manager.js]: What does it throw if you don't specify the `my-plugin` name here?

Comment (hjdivad) [reply packages/babel-core/test/option-manager.js]: @nicolo-ribaudo the example output in the pr is a case where no name is specified.  Because I'm serializing it with `JSON.stringify` you don't see the `name` key in the output at all.

The output for this test is:
```
      Duplicate plugin/preset detected.
      If you'd like to use two separate instances of a plugin,
      they need separate names, e.g.

        plugins: [
          ['some-plugin', {}],
          ['some-plugin', {}, 'some unique name'],
        ]

      Duplicates detected are:
      [
        {
          "name": "my-plugin",
          "alias": "base$0",
          "dirname": "/Users/dhamilto/src/babel/babel/packages/babel-core/test",
          "ownPass": false
        },
        {
          "name": "my-plugin",
          "alias": "base$1",
          "dirname": "/Users/dhamilto/src/babel/babel/packages/babel-core/test",
          "ownPass": false
        }
      ]
```

With the name omitted, the output becomes:

```
      Duplicate plugin/preset detected.
      If you'd like to use two separate instances of a plugin,
      they need separate names, e.g.

        plugins: [
          ['some-plugin', {}],
          ['some-plugin', {}, 'some unique name'],
        ]

      Duplicates detected are:
      [
        {
          "alias": "base$0",
          "dirname": "/Users/dhamilto/src/babel/babel/packages/babel-core/test",
          "ownPass": false
        },
        {
          "alias": "base$1",
          "dirname": "/Users/dhamilto/src/babel/babel/packages/babel-core/test",
          "ownPass": false
        }
      ]
```

**Comment by rwjblue** [comment]
Any thoughts on this one? Not sure what the process itself is to move forward here...

**Comment by rwjblue** [comment]
@nicolo-ribaudo - 👋 I'd love some progress here, we are often times getting bug reports for the current error that require us to manually throw a console.log into `node_modules/@babel/core/lib/config/config-descriptors.js` to see any useful information.
