### PR TITLE
[ts] Insert `export {}` when necessary to imply ESM

### LINKED ISSUE #12568: Typescript plugin doesn't insert `export {}` like tsc does
## Bug Report

- [ ] I would like to work on a fix!

tsc makes sure that ESM files remain in ESM mode (by inserting `export {};`). Should Babel do the same?

**Input Code**

```ts
export type Key = string;
```

https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=KYDwDg9gTgLgBDAnmYcDSxFwLxwM4xQCWAdgOYDcAUEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=typescript&prettier=true&targets=Node-13.1&version=7.12.12&externalPlugins=

**Expected behavior**
```ts
export {};
```

**Current behavior**

```js
// (empty)
```

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

`@babel/preset-typescript`

**Possible Solution**
Insert `export {};` if the input file used ESM Typescript syntax.

### PR DESCRIPTION
**Pull request by wbinnssmith**
This diff is best viewed with whitespace diff disabled: https://github.com/babel/babel/pull/13314/files?w=1

This makes the TypeScript transformer insert an empty `export {}` declaration into files that would otherwise start as modules but become ambiguous after transformation, specifically when there are no imports of exports in the transformed result. See #12568 for context.

Since type imports and exports are removed, this change tracks when imports and exports are left behind as value imports/exports. If there are any left behind, the `export {}` expression does not get added.

| Q                        | A
| ------------------------ | ---
| Fixed Issues?            | Fixes #12568
| Patch: Bug Fix?          | No
| Major: Breaking Change?  | No
| Minor: New Feature?      | Yes
| Tests Added + Pass?      | Adjusted existing, which cover use
| Documentation PR Link    |  None
| Any Dependency Changes?  | None
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/13314"></a>

### CODE REVIEW

File: packages/babel-plugin-transform-typescript/src/index.ts [hunk 1]
```diff
@@ -63,6 +63,8 @@ export default declare((api, opts) => {
     var { allowDeclareFields = false } = opts;
   }
 
+  let hasValueExports = false;
```
Comment (wbinnssmith) [inline packages/babel-plugin-transform-typescript/src/index.ts:66]: I believe this could also be attached to `state` instead of closing over it

Comment (nicolo-ribaudo) [reply packages/babel-plugin-transform-typescript/src/index.ts:66]: We can either use a `WeakMap` from the program node to this variable, or attach it to `state`.

Closing over causes problems, because Babel doesn't reinstantiate the plugin for each file but only when the options change.

Btw, do we need both `hasValueExports`/`hasValueImports`, or can it be a single variable?

Comment (wbinnssmith) [reply packages/babel-plugin-transform-typescript/src/index.ts:66]: > I prefer the WeakMap approach since it's similar to what we use in many other plugins.

Great idea 🙂

> Btw, do we need both hasValueExports/hasValueImports, or can it be a single boolean?

Nope, only one is necessary. I'll combine them.

File: packages/babel-plugin-transform-typescript/src/index.ts [hunk 2]
```diff
@@ -307,24 +328,33 @@ export default declare((api, opts) => {
           )
         ) {
           path.remove();
+          return;
         }
+
+        IMPLICITLY_ESM.add(state.file.ast.program);
```
Comment (JLHwung) [inline packages/babel-plugin-transform-typescript/src/index.ts:334]: nit: Alternatively we can add this to the [`ExportDeclaration`](https://babeljs.io/docs/en/babel-types#exportdeclaration) visitor, it covers `ExportExportAllDeclaration`, `ExportDefaultDeclaration` and `ExportNamedDeclaration`.

File: packages/babel-plugin-transform-typescript/src/index.ts [hunk 3]
```diff
@@ -307,24 +328,33 @@ export default declare((api, opts) => {
...
 
-      ExportSpecifier(path) {
+      ExportSpecifier(path, state) {
         // remove type exports
         if (!path.parent.source && isGlobalType(path, path.node.local.name)) {
           path.remove();
+          return;
         }
+
+        IMPLICITLY_ESM.add(state.file.ast.program);
```
Comment (JLHwung) [inline packages/babel-plugin-transform-typescript/src/index.ts:344]: Q: Why do we need this for `ExportSpecifier`?

**Review by JLHwung — APPROVED** [review]
LGTM with some nits.

For reviewers: please ignore whitespace changes when reviewing.

File: packages/babel-plugin-transform-typescript/src/index.ts (hunk 2 above)
Comment (nicolo-ribaudo) [reply packages/babel-plugin-transform-typescript/src/index.ts:334]: We would have to be careful about ordering, since we only want to add the node to the `WeakSet` if it's not removed.

**Review by nicolo-ribaudo — APPROVED** [review]
https://github.com/babel/babel/pull/13314/files?diff=unified&w=1#r633982388 could probably be removed, but except for that lgtm :+1:

**Comment by nicolo-ribaudo** [comment]
Oh it looks like GH actions are down

File: packages/babel-plugin-transform-typescript/src/index.ts (hunk 3 above)
Comment (wbinnssmith) [reply packages/babel-plugin-transform-typescript/src/index.ts]: Yeah good point — looks like this is already handled above.

**Comment by nicolo-ribaudo** [comment]
Could you address https://github.com/babel/babel/pull/13314#event-4762939255? 🙏

**Comment by wbinnssmith** [comment]
> Could you address [#13314 (comment)](https://github.com/babel/babel/pull/13314#event-4762939255)? 🙏

Ah, missed what you meant here. Just implemented this and checked a few of our test cases agains the typescript playground and they behave the same now.

**Review by nicolo-ribaudo — APPROVED** [review]

File: packages/babel-plugin-transform-typescript/src/index.ts [hunk 4]
```diff
@@ -175,118 +179,140 @@ export default declare((api, opts) => {
...
-            stmt.isTSEnumDeclaration({ declare: true }) ||
-            (stmt.isTSModuleDeclaration({ declare: true }) &&
-              stmt.get("id").isIdentifier())
-          ) {
-            registerGlobalType(path.scope, stmt.node.id.name);
           }
-        }
+        },
+        exit(path) {
+          if (NEEDS_EXPLICIT_ESM.get(path.node)) {
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-typescript/src/index.ts:302]: The tests are failing because here we also need to check if `sourceType` is still `module`: if it has been compiled to CJS we must not inject `export {}`.

**Review by JLHwung — APPROVED** [review]

**Review by lweathermon — APPROVED** [review]

**Comment by nicolo-ribaudo** [comment]
Thanks!
