### PR TITLE
Reinterpret << when parsing TS type arguments

### LINKED ISSUE #11969: [@babel/preset-typescript] Parse error when an explicit type parameter is a generic arrow function
## Bug Report

- [~] I would like to work on a fix!

**Current behavior**
Parse error when an explicit type parameter is a generic arrow function

- [REPL](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=GYHgBCAqB8AUBuBDANgVwKYC4yQJRgF5ox4B7ASwBM4BzXAbjDAHpmxSBrRATwChQAqgBoIMBCgzY8hYmSq0GLNpx78QUOEjRYc-IiQrVYdRkrAAHRACcAzujDorV0laA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ctypescript%2Cenv&prettier=false&targets=&version=7.11.1&externalPlugins=)

**Input Code**

```ts
f<<T>(value: T) => void>(g);
```

**Expected behavior**
The type parameter should be stripped from the code:
```js
f(g);
```
**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "presets": [
    ["@babel/preset-env", { "targets": { "node": "current" } }],
    "@babel/typescript"
  ],
  "plugins": [
    "@babel/plugin-syntax-class-properties"
  ]
}
```

**Environment**

- Babel version(s): v7
- Node/npm version:  Node 13.8.0/npm 6.13.6
- OS:macOS 10.15.5
- Monorepo: yes
- How you are using Babel: cli

**Possible Solution**
Note that these two examples both parse correctly:
```ts
f< <T>(value: T) => void>(g); // Note the space between the two "<"
f<U, <T>(value: T) => void>(g);
```

My guess is that the parser thinks it's encountered a `<<` operator. I think C++ also used to have this problem in its parser 😅.

**Additional context**
[TypeScript playground](https://www.typescriptlang.org/play?ts=3.9.2#code/GYHhBUD4AoDcEMA2BXApgLgATgJSYLySawD2AlgCYwDmOA3EA)

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #11969
| Patch: Bug Fix?          | Y
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

I didn't port the fixe to Flow because Flow does not support `f<<T>(v: T) => void>()`, but it does support `f< <T>(v: T) => void>()`. I will open an issue to Flow later. Before Flow supports it let's focus on the TS.

In this PR we split `tt.bitShift` into `tt.bitShiftL` (`<<`) and `tt.bitShiftR` (`>>`). Then we reinterpret `<<` as `<` when parsing type arguments from ES productions. We don't need to handle `<<` when we are parsing from TS productions because `getTokenFromType` ensures that `<` is always tokenized into `tt.lt` when `state.inType` is `true`.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14145"></a>

### CODE REVIEW

File: packages/babel-parser/src/plugins/typescript/index.js [hunk 1]
```diff
@@ -2818,8 +2829,9 @@ export default (superClass: Class<Parser>): Class<Parser> =>
 
     parseClassSuper(node: N.Class): void {
       super.parseClassSuper(node);
-      if (node.superClass && this.match(tt.lt)) {
-        node.superTypeParameters = this.tsParseTypeArguments();
+      // handle `extends f()<<T>
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/src/plugins/typescript/index.js:2832]: Q: Why `f()<<T>` and not `f<<T>`?

**Review by nicolo-ribaudo — COMMENTED** [review]
It looks like it already works, but can you also add a test for `<<<`? `f<<<T>(x)` is `f << (<T> x)` (with JSX disabled)

And also a test for when `<<` is a real bit shift: `f<<T>((x)=>string)>(x);`

File: packages/babel-parser/src/plugins/typescript/index.js (hunk 1 above)
Comment (JLHwung) [reply packages/babel-parser/src/plugins/typescript/index.js:2832]: Good catch. It can be simplified.

**Review by nicolo-ribaudo — APPROVED** [review]

**Review by sosukesuzuki — APPROVED** [review]
