### PR TITLE
Register `var` decls generated by `import ... =` TS transform

### LINKED ISSUE #15486: [Bug]: Missing registerDeclaration in plugin-transform-typescript
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```
import foo = bar
```

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

plugin-transform-typescript fails to register the declaration at

```
        path.replaceWith(
          t.variableDeclaration("var", [
            t.variableDeclarator(
              path.node.id,
              entityNameToExpr(path.node.moduleReference),
            ),
          ]),
        );
```
in packages/babel-plugin-transform-typescript/src/index.ts.

### Environment

@babel/plugin-transform-typescript: 7.20.13

### Possible solution

Insert
```
path.scope.registerDeclaration(path);
```
after this line:
https://github.com/babel/babel/blob/6e8ce9da64dbb2a9a572bef9ef9450cbd038aba3/packages/babel-plugin-transform-typescript/src/index.ts#L594

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by amoeller**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #15486 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15489"></a>

### CODE REVIEW

File: packages/babel-plugin-transform-typescript/test/fixtures/imports/import=-declaration/plugin.js [hunk 1]
```diff
@@ -0,0 +1,10 @@
+module.exports = function({ types: t }) {
+  return {
+    visitor: {
+      Identifier(path) {
+        if (path.node.name === "foo" && !path.scope.getBinding(path.node.name))
```
Comment (JLHwung) [inline packages/babel-plugin-transform-typescript/test/fixtures/imports/import=-declaration/plugin.js:5]: If we are visiting the `foo` identifier, we can assert that the scope has registered binding:
```js
expect(path.scope.hasBinding(path.node.name)).toBe(true);
```
At the end of the traversal, we can assert that the assertion must have been tested:
```js
{
  visitor: {
    Program: {
      exit() {
        expect.assertions(1)
      }
   }
}
```
So that if the structure of `input.js` is changed, this test will not silently pass because the identifier visitor is not invoked.

**Review by JLHwung — APPROVED** [review]
The transform part looks good to me. Left comments on testing.

**Review by nicolo-ribaudo — APPROVED** [review]
Thank you!

**Comment by nicolo-ribaudo** [comment]
(I'll fix the failing test locally before merging)
