### PR TITLE
Fixes setter paratemer default value

### LINKED ISSUE #7688: Setter default value
Default value in setter argument causes an error:

```js
const obj = {
	set field(num = 1) {this._num = num;},
	get field() {return this._num;}
};
```

Got unhandled error `setter should have exactly one param`, cause setter transpiled as:
```js
set field() {
	var num = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : 1;
	this._num = num;
}
```

And it hasn't any argument.

Perfectly works in chrome without transpiling:

### PR DESCRIPTION
**Pull request by nikolayemrikh**
| Q                        | A
| ------------------------ | ---
| Fixed Issues?            | Fixes #7688
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    |
| Any Dependency Changes?  |
| License                  | MIT

Forces setter's default parameter to use loose transform

### CODE REVIEW

File: packages/babel-plugin-transform-parameters/src/params.js [hunk 1]
```diff
@@ -60,7 +60,8 @@ export default function convertFunctionParams(path, loose) {
   for (let i = 0; i < params.length; i++) {
     const param = params[i];
 
-    if (param.isAssignmentPattern() && loose) {
+    const paramIsAssignmentPattern = param.isAssignmentPattern();
+    if (paramIsAssignmentPattern && loose) {
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-parameters/src/params.js]: Instead of setting `loose` to true for setters, could you update this check to `(loose || node.kind === "set")`?
It would be a little more descriptive and, if we use `loose` for other parts of the transform on the future, they won't be automatically enabled for setters since they might not be needed.

Comment (hzoo) [reply packages/babel-plugin-transform-parameters/src/params.js]: Yep I was thinking that as well!

Comment (nikolayemrikh) [reply packages/babel-plugin-transform-parameters/src/params.js]: In the beginning i did so. But later..
