### PR TITLE
Fix class fields when `super()` is in a default param

### LINKED ISSUE #5074: Class property compilation broken when `super` is called in a parameter default
### Input Code

```js
class A {}
class B extends A {
  foo = 1
  
  constructor (param = super()) {
  }
}
```
[REPL](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=stage-2&code=class%20A%20%7B%7D%0Aclass%20B%20extends%20A%20%7B%0A%20%20foo%20%3D%201%0A%20%20%0A%20%20constructor%20(param%20%3D%20super())%20%7B%0A%20%20%7D%0A%7D)

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "plugins": ["transform-class-properties"]
}
```

### Expected Behavior

The temporary variable holding the `super` result needs to declared when `super` is invoked to avoid the current `_temp is not defined` error.

### Current Behavior

The temporary variable holding the `super` result is declared in the function scope, which is inaccessible in the parameter default expression.

### Possible Solution

Not very elegant, but parameter default expressions containing a `super` call could be wrapped in an arrow function closure (this would depend on #5073 being fixed):

```js
class A {}
class B extends A {
  constructor(param = (() => { var _temp; return _temp = super(), this.foo = 1, _temp })()) {
  }
}
```

### Context

No real-world case. Exploring edge-cases as part of compiling CoffeeScript classes to ES2015.

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #5074
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

Since this fix is at the `@babel/traverse` level, it also fixes any other usage of `insertAfter` in class parameters.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/12729"></a>

### CODE REVIEW

File: packages/babel-traverse/src/path/modification.ts [hunk 1]
```diff
@@ -127,6 +130,18 @@ export function insertAfter(this: NodePath, nodes_: t.Node | t.Node[]) {
     if (this.node) {
       const node = this.node as t.Expression | t.VariableDeclaration;
       let { scope } = this;
+
+      if (scope.path.isPattern()) {
+        this.replaceWith(
+          t.callExpression(
+            t.arrowFunctionExpression([], this.node as t.Expression),
```
Comment (JLHwung) [inline packages/babel-traverse/src/path/modification.ts:137]: nit: use invariant instead if node will never be `t.VariableDeclaration` when `scope.path` is pattern.

Comment (JLHwung) [reply packages/babel-traverse/src/path/modification.ts:137]: Oh I just realize that it is TypeScript! so we can use https://github.com/microsoft/TypeScript/pull/32695 instead.

**Review by kaicataldo — APPROVED** [review]
Like @JLHwung, def prefer type safety and avoiding casting. Otherwise, LGTM!

File: packages/babel-traverse/src/path/modification.ts [hunk 2]
```diff
@@ -127,6 +130,17 @@ export function insertAfter(this: NodePath, nodes_: t.Node | t.Node[]) {
...
       const node = this.node as t.Expression | t.VariableDeclaration;
       let { scope } = this;
+
+      if (scope.path.isPattern()) {
+        t.assertExpression(node);
+
+        this.replaceWith(
+          t.callExpression(t.arrowFunctionExpression([], node), []),
+        );
+        (this.get("callee.body") as NodePath).insertAfter(nodes);
```
Comment (nicolo-ribaudo) [inline packages/babel-traverse/src/path/modification.ts:140]: I replaced the fist typecast with an assertion. I have left this one as a type cast since TS doesn't know that `.get` doesn't return an array here, but we know that it's a single node because it's the body of the arrow expression built at line 138.

**Review by JLHwung — APPROVED** [review]
