### PR TITLE
fix: Transform `using` in `switch` correctly

### LINKED ISSUE #16422: [Bug]: `using` in `switch` is not compiled
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
{
  switch (1) {
    case 1:
      using a = 1;
    case 2:
      using b = 2;
  }
  using c = 4;
}
```

https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=N4KABGDODuCWAuBjAFmAFARgJRlBCiAhpAKZgYBc4-EArpLAHYDmYhYAvOQNzUHFkATFRp0GLMACNOYQbwgBfavSatEMgCy8FQA&debug=false&forceAllTransforms=false&modules=commonjs&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=stage-3%2Ctypescript&prettier=false&targets=&version=7.24.4&externalPlugins=&assumptions=%7B%7D

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

`using` is not transpiled, but it shuold

### Environment

v7.24.4

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #16422 
| Patch: Bug Fix?          | √
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | √
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

File: packages/babel-plugin-proposal-explicit-resource-management/src/index.ts [hunk 1]
```diff
@@ -160,6 +160,58 @@ export default declare(api => {
         }
       }
     },
+    SwitchStatement(path, state) {
+      if (!process.env.BABEL_8_BREAKING && !state.availableHelper("usingCtx")) {
+        return;
+      }
```
Comment (liuxingbaoyu) [inline packages/babel-plugin-proposal-explicit-resource-management/src/index.ts:166]: Maybe we add a warning here?

Comment (nicolo-ribaudo) [reply packages/babel-plugin-proposal-explicit-resource-management/src/index.ts:166]: If would prefer to check if there is a `using` statement in the switch, and if there is throw an error saying "we cannot transpile this, update `@babel/core`".

**Review by JLHwung — APPROVED** [review]

File: packages/babel-plugin-proposal-explicit-resource-management/src/index.ts [hunk 2]
```diff
@@ -160,6 +160,60 @@ export default declare(api => {
...
+            }
+          }
+        }
+      }
+      if (!ctx) return;
+
+      if (!process.env.BABEL_8_BREAKING && !state.availableHelper("usingCtx")) {
+        throw path.buildCodeFrameError(
+          "We cannot transpile this, please update `@babel/core`.",
+        );
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-proposal-explicit-resource-management/src/index.ts:194]: Could you throw this on the first `using` declaration instead of the switch statement?

Saying something "`using` declarations inside `switch` statements are not supported by your current `@babel/core` version, please update to a more recent one"

**Review by nicolo-ribaudo — APPROVED** [review]
Thanks! :)
