### PR TITLE
Resolve programmatic/CLI arguments from cwd, not file being compiled.

### LINKED ISSUE #5434: Babel CLI fails to find presets when compiling files outside the project directory
I'm trying to run `babel` on a JSX file outside the project root (this happens in unit test when using a temporary directory under `/private/tmp`). It seems that babel fails to find presets installed into the same `node_modules` directory as `babel-cli`:

```
michi ~/Documents$ mkdir babel-preset-issue
michi ~/Documents$ cd babel-preset-issue/
michi ~/Documents/babel-preset-issue$ npm install babel-cli babel-preset-es2015
[...]
michi ~/Documents/babel-preset-issue$ echo 'a = 123;' > ../foo.jsx
michi ~/Documents/babel-preset-issue$ node_modules/.bin/babel --presets=es2015 ../foo.jsx
Error: Couldn't find preset "es2015" relative to directory ".."
    at /Users/michi/Documents/babel-preset-issue/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/michi/Documents/babel-preset-issue/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/michi/Documents/babel-preset-issue/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/michi/Documents/babel-preset-issue/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/michi/Documents/babel-preset-issue/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/michi/Documents/babel-preset-issue/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/michi/Documents/babel-preset-issue/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/michi/Documents/babel-preset-issue/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transform (/Users/michi/Documents/babel-preset-issue/node_modules/babel-cli/lib/babel/util.js:50:22)
```

I've tested this with Babel 6.23.0 (babel-core 6.23.1) on OS X 10.11.6.

### PR DESCRIPTION
**Pull request by loganfsmyth**
| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          | 
| Major: Breaking Change?  | Yes
| Minor: New Feature?      | 
| Deprecations?            | 
| Spec Compliancy?         | 
| Tests Added/Pass?        | 
| Fixed Tickets            |   Fixes #5434 
| License                  | MIT
| Doc PR                   | 
| Dependency Changes       | 

This is a change that is breaking, but is _probably_ what people thought was already happening?

In Babel 6, you could have
```
  node_modules/
    babel-preset-example/package.json

  dir/
    node_modules/
      babel-preset-example/package.json
    file.js
```

and do

```
babel --presets example dir/file.js
```
and it would use `example` from the inner directory instead of the current working directory in the base.

While not that weird in this case, it got really confusing for people in cases like this:

```
  file.js
  dir/
    node_modules/
      babel-preset-example/package.json
```

with
```
cd dir
babel --presets example ../file.js
```

which would throw an error because there was no `babel-preset-example` relative to `file.js`.

Similarly, it complicates things like `ignore` and `only`, so we've decided to standardize on the working directory instead.

### CODE REVIEW

File: packages/babel-core/src/transformation/file/options/build-config-chain.js [hunk 1]
```diff
@@ -33,7 +33,7 @@ export default function buildConfigChain(opts: Object = {}) {
   builder.mergeConfig({
     options: opts,
     alias: "base",
-    dirname: filename && path.dirname(filename),
```
Comment (hzoo) [inline packages/babel-core/src/transformation/file/options/build-config-chain.js]: Looks like we default to this already as well https://github.com/loganfsmyth/babel/blob/386f0d2f6d148fea02ce83c1c903d2c9958024fa/packages/babel-core/src/transformation/file/options/build-config-chain.js#L176

Comment (loganfsmyth) [inline packages/babel-core/src/transformation/file/options/build-config-chain.js]: True! I'd probably remove that from there so this declaration is clear up front here.

**Comment by loganfsmyth** [comment]
Related issues I could find:

https://github.com/babel/babel/issues/4280, https://github.com/babel/babel/issues/4010, https://github.com/babel/babel/issues/4869

File: packages/babel-core/src/transformation/file/options/build-config-chain.js (hunk 1 above)
Comment (loganfsmyth) [inline packages/babel-core/src/transformation/file/options/build-config-chain.js]: Removed that default line.
