### PR TITLE
Fixed generateUid creating clashing ids after scope re-crawling

### LINKED ISSUE #11057: @babel/plugin-transform-block-scoping breaks when scope.crawl() is used by another plugin
## Bug Report

Hello, I've found some compatibility issues between `@babel/plugin-transform-block-scoping` and two community plugins (`babel-plugin-transform-react-remove-prop-types`, `babel-plugin-remove-debug`). The common thing between these two plugins is that they are using `scope.crawl()` method. When I comment out that method from `babel-plugin-transform-react-remove-prop-types` the bug seems to disappear. I've read parts of the babel-handbook but didn't find documentation for the crawl method. What does it do?

I've prepared a minimal repository for reproducing this issue with custom plugin where `scope.crawl()` is called.
```json
{
    "plugins": [
        "@babel/plugin-transform-block-scoping",
        "./babel-plugin-tester"
    ]
}
```

Note that `@babel/plugin-transform-block-scoping` is included in preset-env, which is used by create-react-app. In my case this created a bug into production code which was not present in development and test code. In my opinion this is quite dangerous, especially if apps are missing proper integration tests. Developers can't trust their unit tests and development mode functionality.

I'm just getting to know babel's implementation so let's leave this unchecked for now.

- [ ] I would like to work on a fix!

**Current Behavior**

This code block is transformed incorrectly:
```js
// Input
case 'B': {
    const { unicorn } = action;
    const unicorns = state.unicorns.map(_unicorn =>
        _unicorn.id === unicorn.id ? unicorn : _unicorn
    );

    return { ...state, unicorns, someCaseBAttributes: true };
}
```
Note how `var { unicorn: _unicorn } = action;` and `map(_unicorn` have conflicting variable names.
```js
// Output
case 'B': {
    var { unicorn: _unicorn } = action;

    var _unicorns = state.unicorns.map(_unicorn =>
        _unicorn.id === _unicorn.id ? _unicorn : _unicorn
    );

    return { ...state, unicorns: _unicorns, someCaseBAttributes: true };
}
```

When used with webpack this makes terser go crazy:
```js
case 'B':
    var { unicorn: _unicorn } = action,
        _unicorns = state.unicorns.map(
            _unicorn => (_unicorn.id, _unicorn.id, _unicorn)
        );
    return { ...state, unicorns: _unicorns, someCaseBAttributes: !0 };
```

**Input Code**
- REPL or Repo link if applicable:
https://github.com/AriPerkkio/babel-preset-react-app-transpile-bug
```bash
$ yarn # Install deps
$ yarn babel # Runs babel on index.js
$ yarn terser # Runs terser on babel-output.js
$ yarn test # Runs test case against original index.js and dist/terser-output.js
```

**Expected behavior/code**

Variable names should not conflict. When `scope.crawl()` is not called, output is as expected:
```js
case 'B': {
    var { unicorn: _unicorn2 } = action;

    var _unicorns = state.unicorns.map(_unicorn =>
        _unicorn.id === _unicorn2.id ? _unicorn2 : _unicorn
    );

    return { ...state, unicorns: _unicorns, someCaseBAttributes: true };
}
```

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

Any configuration with `@babel/plugin-transform-block-scoping` and other plugin using `scope.crawl()`, such as create-react-app's `babel-preset-react-app`. Here are three examples:
- https://github.com/AriPerkkio/babel-preset-react-app-transpile-bug/blob/master/.babelrc
- https://github.com/AriPerkkio/babel-preset-react-app-transpile-bug/blob/remove-props-plugin/.babelrc
- https://github.com/AriPerkkio/babel-preset-react-app-transpile-bug/blob/another-plugin/.babelrc

**Environment**

```
  System:
    OS: Linux 4.19 Debian GNU/Linux 9 (stretch) 9 (stretch)
  Binaries:
    Node: 13.7.0 - /usr/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.13.6 - /usr/bin/npm
  npmPackages:
    @babel/cli: ^7.8.3 => 7.8.3 
    @babel/core: ^7.8.3 => 7.8.3 
    @babel/plugin-transform-block-scoping: ^7.8.3 => 7.8.3 

```

**Possible Solution**

I'm not familiar with `scope.crawl()` method, but either plugins should not call it, or `@babel/plugin-transform-block-scoping` should not break when it's called.

**Additional context/Screenshots**
Original issues:
- https://github.com/facebook/create-react-app/issues/8322
- https://github.com/AriPerkkio/asus-merlin-simple-vpn-client-setup/issues/1

### PR DESCRIPTION
**Pull request by Andarist**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | fixes #11057
| Patch: Bug Fix?          | x
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    |
| Any Dependency Changes?  |
| License                  | MIT

Bunch of references were not registered back on the program parent after re-crawling because they were not visited by the `collectorVisitor`. I've managed (mostly) to move the code parts responsible for registering those references during the first `crawl` call into the mentioned `collectorVisitor` - this should allow them to be always uniformly, each time.

### CODE REVIEW

File: packages/babel-traverse/src/scope/index.js [hunk 1]
```diff
@@ -761,7 +788,10 @@ export default class Scope {
   }
 
   init() {
-    if (!this.references) this.crawl();
```
Comment (Andarist) [inline packages/babel-traverse/src/scope/index.js:764]: this check was super implicit and confusing (nested scopes don't even gather `references` so this object stays always empty for them, but is initialized in `.crawl`)

File: packages/babel-traverse/src/scope/index.js [hunk 2]
```diff
@@ -773,50 +803,24 @@ export default class Scope {
...
-        const node = path.get(key);
-        if (node.isBlockScoped()) this.registerBinding(node.node.kind, node);
-      }
-    }
-
-    // FunctionExpression - id
-
-    if (path.isFunctionExpression() && path.has("id")) {
-      if (!path.get("id").node[t.NOT_LOCAL_BINDING]) {
+    // TODO: explore removing this as it should be covered by collectorVisitor
```
Comment (Andarist) [inline packages/babel-traverse/src/scope/index.js:806]: attempt to remove this has resulted in 14~ failing tests, most of the updated snapshots seemed OK, but some didn't. It requires more investigation and I'm afraid that I won't have time to do this

Comment (nicolo-ribaudo) [reply packages/babel-traverse/src/scope/index.js:806]: :+1:
