### PR TITLE
fix: Skip computed key when renaming

### LINKED ISSUE #16751: [Bug]: Scope rename affecting parent scope computed property identifier when shadowing
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

See it on ASTExplorer: https://astexplorer.net/#/gist/3a1d53d8dec7b552e6ce309a2d933f7d/487e79162e32ae27cdd60c2b5ef8dd3670e10d95

Given
```js
let x = 1

const foo = {
 get [x]() {
   return x
 },
}
```

And this transformation:
```js
Function(path) {
  const bodyPath = path.get('body');
  // create a declaration that shadows parent variable
  const declaration = t.variableDeclaration('const', [
    t.variableDeclarator(t.identifier('x'), t.nullLiteral())
  ]);
  bodyPath.unshiftContainer('body', declaration);
  const declarationPath = bodyPath.get('body.0');
  // register the new declaration
  bodyPath.scope.registerDeclaration(declarationPath);
  // rename the new "local" declaration 
  bodyPath.scope.rename('x', 'y')
}
```

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

The current output becomes invalid as the resulting identifier is used before being declared

```js
let x = 1;
const foo = {
  get [y]() {
    const y = null;
    return y;
  }
};
```

While I would expect the computed property identifier to still be `x`.
The problem does not affect other types of functions.

### Environment

- Babel: v7.19.0 and 7.23.0 (tested)

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #16751 
| Patch: Bug Fix?          | √
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | √
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

**Review by nicolo-ribaudo — APPROVED** [review]

File: packages/babel-traverse/src/scope/lib/renamer.ts [hunk 1]
```diff
@@ -162,15 +162,27 @@ export default class Renamer {
...
+    // is not part of the current scope and thus should be skipped.
+
+    // const foo = {
+    //   get [x]() {
+    //     return x;
+    //   },
+    // };
+    const skipKeys: Record<string, true> = { discriminant: true };
+    if (t.isMethod(blockToTraverse) && blockToTraverse.computed) {
+      skipKeys.key = true;
```
Comment (JLHwung) [inline packages/babel-traverse/src/scope/lib/renamer.ts:176]: If `blockToTraverse` is a class method, we should also skip its decorators.

**Review by JLHwung — APPROVED** [review]
Pending decorators handling.

**Review by JLHwung — APPROVED** [review]

**Comment by albertogasparin** [comment]
Thanks for the prompt fix @liuxingbaoyu and the smooth merge, team! ❤️
