### PR TITLE
Fix incorrect destructuring in for loop `let` initialization

### LINKED ISSUE #4893: Incorrect destructuring in for loops
### Input Code

```js
const f = range => {
  for (let [ i, n ] = range; i <= n; ++i) {
    console.log(i)
  }
}
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [ "es2015" ]
}
```

### Expected Behavior

```js
var f = function f(range) {
  var _range = _slicedToArray(range, 2);
  for (var i = _range[0], n = _range[1]; i <= n; ++i) {
    console.log(i);
  }
};
```

### Current Behavior

```js
var f = function f(range) {
  for (function () {
    var _range = _slicedToArray(range, 2);

    var i = _range[0],
        n = _range[1];
  }(); i <= n; ++i) {
    console.log(i);
  }
};
```

See in the [REPL](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&code=const%20f%20%3D%20(range)%20%3D%3E%20%7B%0A%20%20for%20(let%20%5B%20i%2C%20n%20%5D%20%3D%20range%3B%20i%20%3C%3D%20n%3B%20%2B%2Bi)%20%7B%0A%20%20%20%20console.log(i)%0A%20%20%7D%0A%7D%0Af(%5B0%2C%2010%5D)).

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  6.18.2
| node             | 6.9.1
| npm              | 4.0.2
| Operating System | Debian

### PR DESCRIPTION
**Pull request by buunguyen**
| Q                        | A
| ------------------------ | ---
| Patch: Bug Fix?          | yes
| Major: Breaking Change?  | no
| Minor: New Feature?      | no 
| Deprecations?            | no 
| Spec Compliancy?         | yes
| Tests Added/Pass?        | yes
| Fixed Tickets            | Fixes #4893
| License                  | MIT
| Doc PR                   | no
| Dependency Changes       | no

__Input__

```js
for (let [ i, n ] = range; ; ) {}
```

__Current (wrong) output__

```js
for (function () {
  var _range = range,
      _range2 = _slicedToArray(_range, 2);

  var i = _range2[0],
      n = _range2[1];
}();;) {}
```

This PR adds special handling in the case of for-init so that all declarations are merged into a single statement, preventing `replaceWithMultiple` from being called and causing the above incorrect transformation.

### CODE REVIEW

File: packages/babel-plugin-transform-es2015-destructuring/src/index.js [hunk 1]
```diff
@@ -491,16 +491,27 @@ export default function ({ types: t }) {
...
-          ) {
-            // Create a single compound let/var rather than many.
-            tail.declarations.push(...node.declarations);
-          } else {
-            nodesOut.push(node);
+
+        // Group all declarations to a single node to avoid
+        // wrong transformation in the `for` initialization.
+        // See https://github.com/babel/babel/issues/4893
+        if (t.isForStatement(parent)) {
```
Comment (jridgewell) [inline packages/babel-plugin-transform-es2015-destructuring/src/index.js]: Couldn't we just always take this path?

Comment (hzoo) [inline packages/babel-plugin-transform-es2015-destructuring/src/index.js]: Yeah it did seem similar to https://github.com/babel/babel/issues/3081 and implementation as well

Comment (buunguyen) [inline packages/babel-plugin-transform-es2015-destructuring/src/index.js]: Good idea. Instead of adding new code, we might do this to achieve the same result in a single code path (basically remove the `kind` check and, not so sure, convert `let`/`const` to `var` to avoid the cases when automatically generated vars will be made `let` or `const`):

```js
const nodesOut = [];
for (const node of nodes) {
  const tail = nodesOut[nodesOut.length - 1];
  if (tail && t.isVariableDeclaration(tail) && t.isVariableDeclaration(node)) {
    // Create a single compound declarations
    tail.declarations.push(...node.declarations);
  } else {
    // Question: should we do this??
    if (node.kind === "let" || node.kind === "const") {
      node[t.BLOCK_SCOPED_SYMBOL] = true;
      node.kind = "var";
    }
    // -- end
    nodesOut.push(node);
  }
}
```

My concern when applying this to all cases is this. Let's say we have this declaration:

```js
const { isExternal, children } = this.props;
```

Currently, after destructuring, the code groups into 2 declarations:

```js
var _props = this.props;
const isExternal = _props.isExternal,
      children = _props.children;
```

With the change in this PR, there will only be 1 declaration:

```js
var _props = this.props,
    isExternal = _props.isExternal,
    children = _props.children;
```

This is beyond my knowledge, but is the above safe? Is it the case that var duplication checking and block scoping etc. will be taken of somehow and it doesn't matter that the destructure plugin merges everything into a single `var`?

I have applied the change and run tests. It seems there's no semantic test failures, so appear to be safe. But as I said, this is beyond my knowledge, I don't know if it could break in some case.

Any feedback is appreciated.

Comment (jridgewell) [inline packages/babel-plugin-transform-es2015-destructuring/src/index.js]: The only problem I can see is with block scoping. In that case, we could just use the binding kind:

```js
const _props = this.props,
    isExternal = _props.isExternal,
    children = _props.children;

Comment (buunguyen) [inline packages/babel-plugin-transform-es2015-destructuring/src/index.js]: Great idea, thanks! New commit: https://github.com/babel/babel/pull/5763/commits/65d47de6cb13e97cf28a9886d5ed66d6555d63da. Some existing tests were updated given the new merge behavior. Please let me know what you think.

**Comment by hzoo** [comment]
Thanks @buunguyen!!
