### PR TITLE
fix: add tokens when tokens: true is passed to parseExpression

### LINKED ISSUE #12936: `parseExpression` missing `tokens`
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

- [REPL](https://babel.dev/repl), [Codesandbox](https://codesandbox.io/s/babel-repl-custom-plugin-7s08o?file=/src/index.js), or GitHub Repo may increase triaging priority!

**Input Code**

```text
require('@babel/parser').parseExpression('[]', {tokens: true}).tokens
undefined
```

**Expected behavior**

Return tokens

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

Should not related

**Environment**

Should not related

**Possible Solution**

N/A

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #12936 
| Patch: Bug Fix?          | Y
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

Assign `tokens` to top level AST node when `tokens: true` is passed to `parser.getExpression()`.

### CODE REVIEW

File: packages/babel-parser/src/types.js [hunk 1]
```diff
@@ -129,16 +130,19 @@ export type BigIntLiteral = NodeBase & {
   value: number,
 };
 
+export type ParserOutput = {
+  comments: $ReadOnlyArray<Comment>,
+  errors: Array<ParsingError>,
+  tokens?: $ReadOnlyArray<Token | Comment>,
```
Comment (JLHwung) [inline packages/babel-parser/src/types.js:136]: When `tokens: false` is passed, `tokens` does not exist in the output.

**Review by nicolo-ribaudo — APPROVED** [review]

**Review by existentialism — APPROVED** [review]
