### PR TITLE
[decorators] Don't transform every AssignmentExpression

### LINKED ISSUE #7027: reduce code generated of plugin-proposal-decorator break compilation...
we need to reopen this;
https://github.com/babel/babel/issues/6965#event-1385806305

this update break the compilation for me with Babel v7.0.0-beta.35
i have got lot of message: Cannot read property 'node' of undefined

### LINKED ISSUE #7030: Incorrect transforms of function custom field assignment in babel 7
When you made multiple assignment to function fields, only first transforms to direct assigment. Others are broken.

### Input Code

First example:
```js
function generateAsyncAction(type) {
    type = type.toUpperCase()
    const request = createAction(type+'_REQUEST',
        undefined, requestMetaCreator
    )
    request.request = request // crazy
    request.success = createAction(type+'_SUCCESS', undefined, metaCreator)
    request.error = createAction(type+'_ERROR', undefined, metaCreator)
    request.cancel = createAction(type+'_CANCEL', undefined, metaCreator)
    request.progress = createAction(type+'_PROGRESS', undefined, metaCreator)
    request.process = createAction(type+'_PROCESS', undefined, metaCreator)

    return request
}
```
Second example:
```js
constructor(timestamp) {
    super()
    this.timestamp = timestamp
    this.moment = moment(timestamp)
}
```

### Babel/Babylon Configuration (.babelrc, package.json, cli command)

```js
{
    "presets": ["@babel/preset-es2015", "@babel/preset-stage-0", "@babel/preset-react"],
    "plugins": [
        "react-hot-loader/babel",
        ["@babel/transform-runtime", { "polyfill": false }]
    ],
    "env": {
        "test": {
            "retainLines": true
        }
    }
}
```
### Current Behavior

First example:
```js
function generateAsyncAction(type) {
  type = type.toUpperCase();
  var request = (0, _reduxActions.createAction)(type + '_REQUEST', undefined, requestMetaCreator); // if (debug) {
  //     const orig_request = request
  //     request = function() {
  //         debugger
  //         return orig_request(...arguments)
  //     }
  // }

  request.request = request; // crazy

  (0, _initializerDefineProperty2.default)(request, "success", type + '_SUCCESS', undefined);
  (0, _initializerDefineProperty2.default)(request, "error", type + '_ERROR', undefined);
  (0, _initializerDefineProperty2.default)(request, "cancel", type + '_CANCEL', undefined);
  (0, _initializerDefineProperty2.default)(request, "progress", type + '_PROGRESS', undefined);
  (0, _initializerDefineProperty2.default)(request, "process", type + '_PROCESS', undefined);
  return request;
}
```
Note that `_initializerDefineProperty2` strings. First string is transformed right and others are wrong. Why? I dunno, lol.

Second example just don't builds with error which listed below. If you removes `this.moment = moment(timestamp)` or change it to `this['moment'] = moment(timestamp)`, all will works. 
```
Module build failed: TypeError: Cannot read property 'node' of undefined
    at PluginPass.AssignmentExpression (/some_dir/node_modules/@babel/plugin-proposal-decorators/lib/index.js:139:261)
    at newFn (/some_dir/node_modules/@babel/traverse/lib/visitors.js:223:21)
    at NodePath._call (/some_dir/node_modules/@babel/traverse/lib/path/context.js:64:19)
    at NodePath.call (/some_dir/node_modules/@babel/traverse/lib/path/context.js:38:17)
    at NodePath.visit (/some_dir/node_modules/@babel/traverse/lib/path/context.js:99:12)
    at TraversalContext.visitQueue (/some_dir/node_modules/@babel/traverse/lib/context.js:139:18)
    at TraversalContext.visitSingle (/some_dir/node_modules/@babel/traverse/lib/context.js:98:19)
    at TraversalContext.visit (/some_dir/node_modules/@babel/traverse/lib/context.js:180:19)
    at Function.traverse.node (/some_dir/node_modules/@babel/traverse/lib/index.js:76:17)
    at NodePath.visit (/some_dir/node_modules/@babel/traverse/lib/path/context.js:106:18)
    at TraversalContext.visitQueue (/some_dir/node_modules/@babel/traverse/lib/context.js:139:18)
    at TraversalContext.visitMultiple (/some_dir/node_modules/@babel/traverse/lib/context.js:93:17)
    at TraversalContext.visit (/some_dir/node_modules/@babel/traverse/lib/context.js:178:19)
    at Function.traverse.node (/some_dir/node_modules/@babel/traverse/lib/index.js:76:17)
    at NodePath.visit (/some_dir/node_modules/@babel/traverse/lib/path/context.js:106:18)
    at TraversalContext.visitQueue (/some_dir/node_modules/@babel/traverse/lib/context.js:139:18)
    at TraversalContext.visitSingle (/some_dir/node_modules/@babel/traverse/lib/context.js:98:19)
    at TraversalContext.visit (/some_dir/node_modules/@babel/traverse/lib/context.js:180:19)
    at Function.traverse.node (/some_dir/node_modules/@babel/traverse/lib/index.js:76:17)
    at NodePath.visit (/some_dir/node_modules/@babel/traverse/lib/path/context.js:106:18)
    at TraversalContext.visitQueue (/some_dir/node_modules/@babel/traverse/lib/context.js:139:18)
    at TraversalContext.visitMultiple (/some_dir/node_modules/@babel/traverse/lib/context.js:93:17)
    at TraversalContext.visit (/some_dir/node_modules/@babel/traverse/lib/context.js:178:19)
```
### Possible Solution

As workaround, you can just don't use dot notation. Next example will works as expected:
```js
    request['request'] = request // crazy
    request['success'] = createAction(type+'_SUCCESS', undefined, metaCreator)
    request['error'] = createAction(type+'_ERROR', undefined, metaCreator)
    request['cancel'] = createAction(type+'_CANCEL', undefined, metaCreator)
    request['progress'] = createAction(type+'_PROGRESS', undefined, metaCreator)
    request['process'] = createAction(type+'_PROCESS', undefined, metaCreator)
```
### Your Environment

```js
    "@babel/core": "7.0.0-beta.35",
    "@babel/plugin-transform-runtime": "7.0.0-beta.35",
    "@babel/polyfill": "7.0.0-beta.35",
    "@babel/preset-es2015": "7.0.0-beta.35",
    "@babel/preset-react": "7.0.0-beta.35",
    "@babel/preset-stage-0": "7.0.0-beta.35",
    "@babel/register": "7.0.0-beta.35",
    "@babel/runtime": "7.0.0-beta.35",
```

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #7030, maybe fixes #7027
| Patch: Bug Fix?          | yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR         | 
| Any Dependency Changes?  |
| License                  | MIT

Somehow I missed this while reviewing https://github.com/babel/babel/pull/7017, sorry. :disappointed:

### CODE REVIEW

**Comment by hzoo** [comment]
No need to apologize @nicolo-ribaudo, we have a handful of people actually helping with this project and reviewing code and thousands of people complaining when stuff doesn't work, especially in a beta which they don't have to use. I'm really appreciate that you are helping out!

We can't do much other than have better infrastructure in testing and other things since we are just going to miss things, it's inevitable.

File: packages/babel-plugin-proposal-decorators/test/fixtures/regression/7030/expected.js [hunk 1]
```diff
@@ -0,0 +1,41 @@
+function _instanceof(left, right) { if (right != null && typeof Symbol !== "undefined" && right[Symbol.hasInstance]) { return right[Symbol.hasInstance](left); } else { return left instanceof right; } }
```
Comment (hzoo) [inline packages/babel-plugin-proposal-decorators/test/fixtures/regression/7030/expected.js]: non-blocker: should we standardize on using helpers or not?

Comment (nicolo-ribaudo) [reply packages/babel-plugin-proposal-decorators/test/fixtures/regression/7030/expected.js]: I usually don't use external helpers so that if I later add an `exec.js` test it works without modifying `options.json`

Comment (hzoo) [reply packages/babel-plugin-proposal-decorators/test/fixtures/regression/7030/expected.js]: Ok I was just thinking in general it makes everything easier to understand if we did, and then we would just need to make sure we test those separately. Or we need to fix that workflow

**Comment by simonjoom** [comment]
yes it's fixed for me with this patch .
Thanks nicolo-ribaudo
