### PR TITLE
transform-spread: create TS types (not Flow) when using TS

### LINKED ISSUE #9530: transform-spread + typescript builds Flow annotation instead of TypeScript
## Bug Report

**Current Behavior**

```
TypeError: Property types[0] of UnionTypeAnnotation expected node to be of a type ["FlowType"] but instead got "TSTypeAnnotation"
    at validate (/work/node_modules/@babel/types/lib/definitions/utils.js:128:13)
    at validator (/work/node_modules/@babel/types/lib/definitions/utils.js:97:7)
    at Object.validate (/work/node_modules/@babel/types/lib/definitions/utils.js:172:7)
    at validate (/work/node_modules/@babel/types/lib/validators/validate.js:17:9)
    at builder (/work/node_modules/@babel/types/lib/builders/builder.js:46:27)
    at UnionTypeAnnotation (/work/node_modules/@babel/types/lib/builders/generated/index.js:733:31)
    at Object.createUnionTypeAnnotation (/work/node_modules/@babel/types/lib/builders/flow/createUnionTypeAnnotation.js:20:47)
    at NodePath.ConditionalExpression (/work/node_modules/@babel/traverse/lib/path/inference/inferers.js:124:14)
    at NodePath._getTypeAnnotation (/work/node_modules/@babel/traverse/lib/path/inference/index.js:63:20)
    at NodePath.getTypeAnnotation (/work/node_modules/@babel/traverse/lib/path/inference/index.js:29:19)
```

**Input Code**

https://github.com/azz/babel-typescript-union-bug

```ts
function bug() {
  const x = 1 ? a() : b();

  return [...x];
}

function a(): number[] {
  return [];
}

function b(): number[] {
  return [];
}
```

**Expected behavior/code**

_Not like this_

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "plugins": ["@babel/plugin-transform-spread"],
  "presets": ["@babel/preset-typescript"]
}
```

**Environment**
- Babel version(s): 7.3.3
- Node/npm version: 6.5.0
- OS: macOS 10.14.2
- Monorepo: no
- How you are using Babel: cli

**Possible Solution**

The builder code for `plugin-transform-spread` is expecting a `UnionTypeAnnotation` instead of a `TSUnionType` in order to determine the type of `x` above, specifically in `scope.toArray`:

https://github.com/babel/babel/blob/5bb1bb080f2cb1ff942c940bdb9595a70e6f4706/packages/babel-traverse/src/scope/index.js#L408-L413

`isGenericType` ends up calling `createUnionTypeAnnotation`:

https://github.com/babel/babel/blob/5bb1bb080f2cb1ff942c940bdb9595a70e6f4706/packages/babel-traverse/src/path/inference/inferers.js#L92-L97

Which creates a `UnionTypeAnnotation`, which works for Flow, but not TypeScript.

### PR DESCRIPTION
**Pull request by Beraliv**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #9530 
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  | No
| License                  | MIT

### CODE REVIEW

File: packages/babel-traverse/src/path/inference/inferers.js [hunk 1]
```diff
@@ -89,7 +89,15 @@ export function LogicalExpression() {
   ]);
 }
 
-export function ConditionalExpression() {
+export function ConditionalExpression(node) {
+  console.log(node);
```
Comment (Beraliv) [inline packages/babel-traverse/src/path/inference/inferers.js:93]: TODO: need to clarify what the node is here

File: packages/babel-traverse/src/path/inference/inferers.js [hunk 2]
```diff
@@ -89,7 +89,15 @@ export function LogicalExpression() {
...
+  if (t.isTSTypeAnnotation(node)) {
```
Comment (Beraliv) [inline packages/babel-traverse/src/path/inference/inferers.js:94]: `isTSTypeAnnotation` is not working here

<details>
<summary>The tree example for <a href="https://github.com/babel/babel/pull/11378/files#diff-15a026b575d179b28985d330d461ff64R1">bug case</a></summary>

```javascript
{
        type: 'ConditionalExpression',
        start: 29,
        end: 42,
        loc: 
         SourceLocation {
           start: Position { line: 2, column: 12 },
           end: Position { line: 2, column: 25 } },
        test: 
         Node {
           type: 'NumericLiteral',
           start: 29,
           end: 30,
           loc: SourceLocation { start: [Object], end: [Object] },
           extra: { rawValue: 1, raw: '1' },
           value: 1,
           leadingComments: undefined,
           innerComments: undefined,
           trailingComments: undefined },
        consequent: 
         Node {
           type: 'CallExpression',
           start: 33,
           end: 36,
           loc: SourceLocation { start: [Object], end: [Object] },
           callee: 
            Node {
              type: 'Identifier',
              start: 33,
              end: 34,
              loc: [Object],
              name: 'a',
              leadingComments: undefined,
              innerComments: undefined,
              trailingComments: undefined },
           arguments: [],
           leadingComments: undefined,
           innerComments: undefined,
           trailingComments: undefined,
           typeParameters: null },
        alternate: 
         Node {
           type: 'CallExpression',
           start: 39,
           end: 42,
           loc: SourceLocation { start: [Object], end: [Object] },
           callee: 
            Node {
              type: 'Identifier',
              start: 39,
              end: 40,
              loc: [Object],
              name: 'b',
              leadingComments: undefined,
              innerComments: undefined,
              trailingComments: undefined },
           arguments: [],
           leadingComments: undefined,
           innerComments: undefined,
           trailingComments: undefined,
           typeParameters: null },
        leadingComments: undefined,
        innerComments: undefined,
        trailingComments: undefined }
```
</details>

File: packages/babel-types/src/builders/typescript/createTSUnionType.js [hunk 3]
```diff
@@ -0,0 +1,16 @@
+import { TSUnionType } from "../generated";
+import removeTypeDuplicates from "../../modifications/typescript/removeTypeDuplicates";
```
Comment (Beraliv) [inline packages/babel-types/src/builders/typescript/createTSUnionType.js:2]: use typescript implementation here: https://github.com/babel/babel/pull/11378/files#diff-31b76153974cd0302007f05a570dfde6R10

File: packages/babel-types/src/modifications/typescript/removeTypeDuplicates.js [hunk 4]
```diff
@@ -0,0 +1,74 @@
...
+
+/**
+ * Dedupe type annotations.
+ */
+export default function removeTypeDuplicates(
+  nodes: Array<Object>,
+): Array<Object> {
+  const generics = {};
+  // FIXME: I don't understand the purpose of bases for Flow (if it has an analogue for TS)
+  // const bases = {};
```
Comment (Beraliv) [inline packages/babel-types/src/modifications/typescript/removeTypeDuplicates.js:15]: didn't understand what it means so left it as is until the clarification

File: packages/babel-types/src/modifications/typescript/removeTypeDuplicates.js [hunk 5]
```diff
@@ -0,0 +1,74 @@
...
+
+    if (isTSUnionType(node)) {
+      if (typeGroups.indexOf(node.types) < 0) {
+        nodes = nodes.concat(node.types);
+        typeGroups.push(node.types);
+      }
+      continue;
+    }
+
+    if (isTSTypeParameter(node)) {
```
Comment (Beraliv) [inline packages/babel-types/src/modifications/typescript/removeTypeDuplicates.js:49]: As I understand `TSTypeParameter` (in comparison to `GenericTypeAnnotation`) doesn't have parameters to merge as it works for Flow
example: https://github.com/babel/babel/blob/master/packages/babel-parser/test/fixtures/typescript/types/conditional-infer/output.json#L23

File: packages/babel-types/src/builders/typescript/createTSUnionType.js [hunk 6]
```diff
@@ -0,0 +1,16 @@
...
+ * Takes an array of `types` and flattens them, removing duplicates and
+ * returns a `UnionTypeAnnotation` node containg them.
+ */
+export default function createTSUnionType(types: Array<Object>): Object {
+  const flattened = removeTypeDuplicates(types);
+
+  if (flattened.length === 1) {
+    return flattened[0];
+  } else {
+    return TSUnionType(flattened);
```
Comment (Beraliv) [inline packages/babel-types/src/builders/typescript/createTSUnionType.js:14]: I'm not sure if here we need to pass array, not elements of the array
But it works this way for Flow:

https://github.com/babel/babel/blob/aeebc0823415ed4770c633cedf570cf774ae89c6/packages/babel-types/src/builders/flow/createUnionTypeAnnotation.js#L9-L19

**Comment by Beraliv** [comment]
🔄 Still working on fixing created test case

● babel-traverse/type reference › input

    TypeError: /Users/beraliv/Documents/Code/babel/packages/babel-traverse/test/fixtures/type-reference/input.ts: Property types[0] of UnionTypeAnnotation expected node to be of a type ["FlowType"] but instead got "TSTypeAnnotation"

      130 |     }
      131 | 
    > 132 |     throw new TypeError(`Property ${key} of ${node.type} expected node to be of a type ${JSON.stringify(types)} but instead got ${JSON.stringify(val && val.type)}`);
          |           ^
      133 |   }
      134 | 
      135 |   validate.oneOfNodeTypes = types;

      at validate (packages/babel-types/lib/definitions/utils.js:132:11)
      at validator (packages/babel-types/lib/definitions/utils.js:103:7)
      at Object.validate (packages/babel-types/lib/definitions/utils.js:229:7)
      at validateField (packages/babel-types/lib/validators/validate.js:24:9)
      at validate (packages/babel-types/lib/validators/validate.js:17:3)
      at builder (packages/babel-types/lib/builders/builder.js:38:27)
      at UnionTypeAnnotation (packages/babel-types/lib/builders/generated/index.js:757:31)
      at Object.createUnionTypeAnnotation (packages/babel-types/lib/builders/flow/createUnionTypeAnnotation.js:20:47)
      at NodePath.ConditionalExpression (packages/babel-traverse/lib/path/inference/inferers.js:123:12)
      at NodePath._getTypeAnnotation (packages/babel-traverse/lib/path/inference/index.js:57:20)

File: packages/babel-traverse/test/fixtures/type-reference/input.ts [hunk 7]
```diff
@@ -0,0 +1,13 @@
+function bug() {
```
Comment (Beraliv) [inline packages/babel-traverse/test/fixtures/type-reference/input.ts:1]: Got an example from https://github.com/azz/babel-typescript-union-bug/blob/master/index.ts

**Comment by Beraliv** [comment]
> 🔄 Still working on fixing created test case

Now I have a different error:

```
TypeError: /Users/beraliv/Documents/Code/babel/packages/babel-traverse/test/fixtures/type-reference/input.ts: Property types[0] of TSUnionType expected 
node to be of a type ["TSType"] but instead got "TSTypeAnnotation"
```

File: packages/babel-types/src/builders/typescript/createTSUnionType.js (hunk 6 above)
Comment (Beraliv) [reply packages/babel-types/src/builders/typescript/createTSUnionType.js:14]: Yeah, only 1 parameter is accepted:

```
TSUnionType: Too many arguments passed. Received 2 but can receive no more than 1
```

File: packages/babel-traverse/src/path/inference/inferers.js (hunk 2 above)
Comment (Beraliv) [reply packages/babel-traverse/src/path/inference/inferers.js]: Now I check `consequent` and `alternate` to be `TSTypeAnnotation`, so it's working fine

**Comment by Beraliv** [comment]
> Now I have a different error:
> 
> ```
> TypeError: /Users/beraliv/Documents/Code/babel/packages/babel-traverse/test/fixtures/type-reference/input.ts: Property types[0] of TSUnionType expected 
> node to be of a type ["TSType"] but instead got "TSTypeAnnotation"
> ```

✅ fixed test case

File: packages/babel-traverse/src/path/inference/inferers.js (hunk 1 above)
Comment (Beraliv) [reply packages/babel-traverse/src/path/inference/inferers.js]: ✅ removed

File: packages/babel-types/src/modifications/typescript/removeTypeDuplicates.js (hunk 4 above)
Comment (Beraliv) [reply packages/babel-types/src/modifications/typescript/removeTypeDuplicates.js]: ✅ replaced with basic TS types

File: packages/babel-types/src/modifications/typescript/removeTypeDuplicates.js (hunk 5 above)
Comment (Beraliv) [reply packages/babel-types/src/modifications/typescript/removeTypeDuplicates.js]: ❌ Removed to clarify how exactly I need to replace `GenericTypeAnnotation`

File: packages/babel-types/src/modifications/typescript/removeTypeDuplicates.js [hunk 8]
```diff
@@ -0,0 +1,89 @@
...
+      continue;
+    }
+
+    // this type matches anything
+    if (isTSAnyKeyword(node.type)) {
+      return [node];
+    }
+
+    // Basic TS types, analogue of FlowBaseAnnotation
+    if (
```
Comment (Beraliv) [inline packages/babel-types/src/modifications/typescript/removeTypeDuplicates.js:47]: I'm not sure if I need to add custom type for `TSBaseKeywords`

File: packages/babel-types/src/modifications/typescript/removeTypeDuplicates.js [hunk 9]
```diff
@@ -0,0 +1,89 @@
...
+
+    if (isTSUnionType(node)) {
+      if (typeGroups.indexOf(node.types) < 0) {
+        nodes = nodes.concat(node.types);
+        typeGroups.push(node.types);
+      }
+      continue;
+    }
+
+    // TODO: add generic types
```
Comment (Beraliv) [inline packages/babel-types/src/modifications/typescript/removeTypeDuplicates.js:73]: ⚠️ I need clarification here

First I tried `TSTypeParameter` https://github.com/babel/babel/pull/11378/commits/e0f3fc2dfd3d7320887e2259757afc03fce81271#diff-31b76153974cd0302007f05a570dfde6R49

Now I'm sure it does NOT cover all cases

File: packages/babel-traverse/src/path/inference/inferers.js [hunk 10]
```diff
@@ -83,17 +83,29 @@ export function BinaryExpression(node) {
...
 
 export function ConditionalExpression() {
-  return t.createUnionTypeAnnotation([
+  const argumentTypes = [
     this.get("consequent").getTypeAnnotation(),
     this.get("alternate").getTypeAnnotation(),
-  ]);
+  ];
+
+  if (argumentTypes.every(t.isTSTypeAnnotation)) {
```
Comment (Beraliv) [inline packages/babel-traverse/src/path/inference/inferers.js:104]: The fix 💊

Changes are also applied for
* `LogicalExpression` - https://github.com/babel/babel/pull/11378/files#diff-6c956a118dc9996dff6b731e42856479R85
* `getTypeAnnotationBindingConstantViolations` - https://github.com/babel/babel/pull/11378/files#diff-1fce3c9f392392fe193c399ad4a97b65R99
* `getConditionalAnnotation` - https://github.com/babel/babel/pull/11378/files#diff-1fce3c9f392392fe193c399ad4a97b65R212

**Comment by Beraliv** [comment]
@JLHwung please have a look at it!

File: packages/babel-traverse/src/path/inference/inferer-reference.js [hunk 11]
```diff
@@ -91,9 +91,15 @@ function getTypeAnnotationBindingConstantViolations(binding, path, name) {
     }
   }
 
-  if (types.length) {
-    return t.createUnionTypeAnnotation(types);
+  if (!types.length) {
+    return;
+  }
+
+  if (types.every(t.isTSTypeAnnotation)) {
```
Comment (JLHwung) [inline packages/babel-traverse/src/path/inference/inferer-reference.js:98]: It suffices to check via `types.some` since the TS type annotation will not be mixed with flow type annotation.

File: packages/babel-types/src/modifications/typescript/removeTypeDuplicates.js (hunk 8 above)
Comment (JLHwung) [reply packages/babel-types/src/modifications/typescript/removeTypeDuplicates.js:47]: Yeah we can definitely add an alias similar to `FlowBaseAnnotation`.

File: packages/babel-traverse/src/path/inference/inferer-reference.js (hunk 11 above)
Comment (Beraliv) [reply packages/babel-traverse/src/path/inference/inferer-reference.js]: Yeah, this is right
Fixed this ✅

File: packages/babel-traverse/test/fixtures/type-reference/input.ts (hunk 7 above)
Comment (Beraliv) [reply packages/babel-traverse/test/fixtures/type-reference/input.ts]: Changed ✅

File: packages/babel-types/src/modifications/typescript/removeTypeDuplicates.js (hunk 8 above)
Comment (Beraliv) [reply packages/babel-types/src/modifications/typescript/removeTypeDuplicates.js:47]: I added `TSBaseType`

**Comment by Beraliv** [comment]
@JLHwung fixed all comments ✅

File: packages/babel-types/src/modifications/typescript/removeTypeDuplicates.js [hunk 12]
```diff
@@ -0,0 +1,65 @@
...
+      continue;
+    }
+
+    // this type matches anything
+    if (isTSAnyKeyword(node.type)) {
+      return [node];
+    }
+
+    // Analogue of FlowBaseAnnotation
+    if (isTSBaseType(node)) {
```
Comment (Beraliv) [inline packages/babel-types/src/modifications/typescript/removeTypeDuplicates.js:36]: use `TSBaseType` here which I added before https://github.com/babel/babel/pull/11378/files#diff-0729be6aceed3c3d27b34e6226aa1509R146

File: packages/babel-types/src/validators/generated/index.js [hunk 13]
```diff
@@ -4611,6 +4611,36 @@ export function isTSType(node: ?Object, opts?: Object): boolean {
 
   return false;
 }
+export function isTSBaseType(node: ?Object, opts?: Object): boolean {
+  if (!node) return false;
+
+  const nodeType = node.type;
+  if (
+    nodeType === "TSBaseType" ||
```
Comment (Beraliv) [inline packages/babel-types/src/validators/generated/index.js:4619]: moved logic from commit https://github.com/babel/babel/pull/11378/commits/aa8c16ab25b1edaf61ab670218816da30c23acc8#diff-31b76153974cd0302007f05a570dfde6R47 here

File: packages/babel-traverse/src/path/inference/inferer-reference.js [hunk 14]
```diff
@@ -91,9 +91,15 @@ function getTypeAnnotationBindingConstantViolations(binding, path, name) {
...
   }
 
-  if (types.length) {
-    return t.createUnionTypeAnnotation(types);
+  if (!types.length) {
+    return;
+  }
+
+  if (t.isTSTypeAnnotation(types[0])) {
+    return t.createTSUnionType(types);
```
Comment (nicolo-ribaudo) [inline packages/babel-traverse/src/path/inference/inferer-reference.js:99]: This is technically a breaking change: it makes the next `@babel/traverse` version incompatible with `@babel/types` <= 7.9.5, because it doesn't contain this function.

We should use `t.createTSUnionType?.(types)` instead.

Comment (Beraliv) [reply packages/babel-traverse/src/path/inference/inferer-reference.js:99]: Oh, this is true, thanks for mentioning that

Comment (Beraliv) [reply packages/babel-traverse/src/path/inference/inferer-reference.js:99]: @nicolo-ribaudo it will change the behaviour as returns `UnionTypeAnnotation` and now it returns `undefined`

I added if-check in https://github.com/babel/babel/pull/11378/commits/5e9c92098d7d79a9e6f0c72d67370d0b2400c9cf

✅

**Comment by nicolo-ribaudo** [comment]
Tests pass locally.
