### PR TITLE
Do not guess relative execution status for exported fns

### LINKED ISSUE #10416: Weird behaviour after recent release
## Bug Report

**Current Behavior**
`Cannot read property 'name' of null` error is coming when babel is parsing.
Since `target.node.id is null`

**Input Code**
- Error code - http://bit.ly/2k7mzXL
- Working code - http://bit.ly/2lZu8QG
- Working code - http://bit.ly/2kzBt9e

This code breaks on repl with only es2015 preset selected
```js

const E_ARR = [];

export default function () {
  const someVar = E_ARR;
  return [...someVar];
}
```

**Expected behavior/code**
This code is working though

```js
export default function () {
  const E_ARR = [];
  const someVar = E_ARR;
  return [...someVar];
}
```
```js
const E_ARR = [];

export default function namedFunction() {
  const someVar = E_ARR;
  return [...someVar];
}

```
**Environment**
- Babel version(s): https://babeljs.io/repl
- Node/npm version: https://babeljs.io/repl
- OS: [e.g. OSX 10.13.4, Windows 10]: OSX
- Monorepo: [e.g. yes/no/Lerna]: N/A
- How you are using Babel: [e.g. `cli`, `register`, `loader`]: https://babeljs.io/repl

**Possible Solution**
We believe it's being caused by the latest release this weekend.

**Additional context/Screenshots**
This same code was working before this weekend's release

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #10416
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

File: packages/babel-traverse/src/path/introspection.js [hunk 1]
```diff
@@ -370,7 +370,12 @@ const executionOrderCheckedNodes = new WeakSet();
 export function _guessExecutionStatusRelativeToDifferentFunctions(
   target: NodePath,
 ): RelativeExecutionStatus {
-  if (!target.isFunctionDeclaration()) return "unknown";
+  if (
+    !target.isFunctionDeclaration() ||
+    target.parentPath.isExportDeclaration()
```
Comment (JLHwung) [inline packages/babel-traverse/src/path/introspection.js]: I am not familiar with this topic, but looking in the code, does it mean that `foo` will pass this check
```js
function foo() {}
export default foo;
```
while `bar` wouldn't?
```js
export function bar() {}
```

Comment (nicolo-ribaudo) [reply packages/babel-traverse/src/path/introspection.js]: Yes, but they are handled the same because of these lines:

https://github.com/babel/babel/blob/373afbf3a604d7aa8a0f5ea64603b49e281acc4d/packages/babel-traverse/src/path/introspection.js#L394-L404

In the `foo` example, `export default foo` references it without calling the function, so it returns `"unknown"`.
In the `bar` example, it returns `"unknown"` because it's directly exported.

Comment (JLHwung) [reply packages/babel-traverse/src/path/introspection.js]: Ah, I see. So we fix the function declaration case without id and also early return when target is an export declaration. Kill two birds with one stone!
