### PR TITLE
Sort module export names

### LINKED ISSUE #13785: [Bug]: the order of exports is incorrect when converting ESM to CJS
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
export let a = 1
export let c = 3
export let b = 2
```

### Configuration file name

_No response_

### Configuration

```js
import * as babel from '@babel/core';
import esm2cjs from '@babel/plugin-transform-modules-commonjs';
output = babel.transformSync(input, { plugins: [esm2cjs] }).code;
```

### Current and expected behavior

Babel generates this code when converting ESM to CommonJS:

```js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.b = exports.c = exports.a = void 0;
let a = 1;
exports.a = a;
let c = 3;
exports.c = c;
let b = 2;
exports.b = b;
```

However, the order of exports is incorrect and does not match what native ESM does. For example, ESM code that uses `Object.keys()` on this file will behave differently when converted to CommonJS. The order should be `['a', 'b', 'c']` but Babel gives an order of `['a', 'c', 'b']` instead. According to [the specification](https://262.ecma-international.org/6.0/#sec-module-namespace-exotic-objects), exports must be sorted:

> **Table 29 — Internal Slots of Module Namespace Exotic Objects**
> | Internal Slot | Type | Description |
> |---|---|---|
> | [[Module]] | [Module Record](https://262.ecma-international.org/6.0/#sec-abstract-module-records) | The [Module Record](https://262.ecma-international.org/6.0/#sec-abstract-module-records) whose exports this namespace exposes. |
> | [[Exports]] | [List](https://262.ecma-international.org/6.0/#sec-list-and-record-specification-type) of String | A [List](https://262.ecma-international.org/6.0/#sec-list-and-record-specification-type) containing the String values of the exported names exposed as own properties of this object. The list is ordered as if an Array of those String values had been sorted using [`Array.prototype.sort`](https://262.ecma-international.org/6.0/#sec-array.prototype.sort) using [SortCompare](https://262.ecma-international.org/6.0/#sec-sortcompare) as _comparefn_. |

### Environment

My `package.json` file:

```json
{
  "dependencies": {
    "@babel/core": "7.15.5",
    "@babel/plugin-transform-modules-commonjs": "7.15.4"
  }
}
```

### Possible solution

I believe Babel should generate `exports.c = exports.b = exports.a = void 0;` instead of `exports.b = exports.c = exports.a = void 0;` here.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #13785 
| Patch: Bug Fix?          | Y
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

In this PR we sort the export initialization statements by the export names. The `initStatements` and `exportsNames` are merged to an array of tuple`<string, Statement>` so we can sort the init statements by their names.

We didn't add new tests as current tests are sufficient to show that the initializations are ordered by names.

Note that under the `noIncompleteNsImportDetection` assumption, the issue can not be fixed _without_ adding new initialization statements, which are exactly removed by definition of the assumption. We can add an extra note about the effects of this assumption.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/13788"></a>

### CODE REVIEW

File: packages/babel-helper-module-transforms/src/index.ts [hunk 1]
```diff
@@ -412,43 +412,92 @@ function buildExportInitializationStatements(
...
+
+  const results = [];
+  if (noIncompleteNsImportDetection) {
+    for (const [, initStatement] of initStatements) {
+      results.push(initStatement);
+    }
+  } else {
+    // We generate init statements (`exports.a = exports.b = ... = void 0`)
+    // for every 100 exported names.
+    const chunkSize = 100;
```
Comment (JLHwung) [inline packages/babel-helper-module-transforms/src/index.ts:462]: The chunk behaviour has existed since https://github.com/babel/babel/commit/95e08b6d2a16d2059284361e8aba8caf7338cfa8#diff-f9b022d801ca0bab9bbb7057b9ac49aac0d8c2ab53f41f97e7e15bdd10f26069R272. I don't know if it is a workaround of browser quirks or it is for aesthetic reasons.

**Review by JLHwung — COMMENTED** [review]
We still need to update `buildNamespaceInitStatements` implementations.

File: packages/babel-helper-module-transforms/src/index.ts (hunk 1 above)
Comment (nicolo-ribaudo) [reply packages/babel-helper-module-transforms/src/index.ts:462]: I think it's to avoid a too deeply nested AST

**Comment by JLHwung** [comment]
Turns out we don't need to update `buildNamespaceInitStatements` because all statically know exports have been initialized in `buildExportInitializationStatements`.

**Review by jridgewell — APPROVED** [review]

**Review by nicolo-ribaudo — APPROVED** [review]

File: packages/babel-helper-module-transforms/src/index.ts (hunk 1 above)
Comment (nicolo-ribaudo) [reply packages/babel-helper-module-transforms/src/index.ts:462]: Ref - https://github.com/babel/babel/issues/14272
