### PR TITLE
Fix compiling duplicate ns imports to lazy CommonJS

### LINKED ISSUE #15939: [Bug]: commonjs lazy transform produces invalid output with multiple ns imports for same module
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
import * as a from "mod";
import * as b from "mod";

later(() => [a, b])
```

### Configuration file name

_No response_

### Configuration

```js
const out = transformSync(input, {
  configFile: false,
  plugins: [[await load(`transform-modules-commonjs`), { lazy: true }]],
});
```

### Current and expected behavior

Current:
```js
"use strict";

function a() {
  const data = _interopRequireWildcard(require("mod"));
  a = function () {
    return data;
  };
  return data;
}
var b = a();
function _getRequireWildcardCache(nodeInterop) { ... }
later(() => [a(), b()]);
```

Expected (note the `b` declaration):
```js
"use strict";

function a() {
  const data = _interopRequireWildcard(require("mod"));
  a = function () {
    return data;
  };
  return data;
}
var b = a;
function _getRequireWildcardCache(nodeInterop) { ... }
later(() => [a(), b()]);
```

### Environment

Current main

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #15939
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

Unblocks https://github.com/babel/babel/pull/15898.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15941"></a>

### CODE REVIEW

**Review by JLHwung — APPROVED** [review]
Nit: can we make `srcNamespace` a const binding and refine its typings?

File: packages/babel-helper-module-transforms/src/index.ts [hunk 1]
```diff
@@ -221,10 +220,15 @@ export function buildNamespaceInitStatements(
...
         NAME: localName,
-        SOURCE: cloneNode(srcNamespace),
+        SOURCE: cloneNode(srcNamespaceId),
       }),
     );
   }
+
+  const srcNamespace = sourceMetadata.lazy
+    ? srcNamespaceId
+    : callExpression(srcNamespaceId, []);
```
Comment (nicolo-ribaudo) [inline packages/babel-helper-module-transforms/src/index.ts:230]:
```suggestion
  const srcNamespace = sourceMetadata.lazy
    ? callExpression(srcNamespaceId, [])
    : srcNamespaceId;
```

**Review by liuxingbaoyu — APPROVED** [review]
