### PR TITLE
scope.rename() missing identifier in VariableDeclarator

### LINKED ISSUE #11591: babel-traverse Scope.rename bad case
## Bug Report

- [x] I would like to work on a fix!
a fix is here #11595

I add a test case here:
https://github.com/yulanggong/babel/commit/0dfff883b67da1d8b405720f23e6fe5d397c58f3

**Input Code**

```js
function test(b) {
  var a = b + 1,
      a = a + 1,
      a = a + 1;

  return a;
}
```

**Plugin Code**

```js
module.exports = function() {
  return {
    visitor: {
      Scope(path) {
        path.scope.rename("a", "_a");
      }
    }
  };
}
```
**Expected Result**

```js
function test(b) {
  var _a = b + 1,
      _a = _a + 1,
      _a = _a + 1;

  return _a;
}
```

**Current Result**

```js
function test(b) {
  var _a = b + 1,
      a = _a + 1,
      _a = _a + 1;

  return _a;
}
```

**Diff**
```diff
- Expected
+ Received

  function test(b) {
    var _a = b + 1,
-       _a = _a + 1,
+       a = _a + 1,
        _a = _a + 1;

    return _a;
  }
```

**Environment**

```
System:
    OS: macOS 10.15.4
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v10.16.3/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v10.16.3/bin/npm
  Monorepos:
    Lerna: 3.19.0
  npmPackages:
    @babel/cli: ^7.8.4 => 7.8.4
    @babel/core: ^7.9.6 => 7.9.6
    @babel/eslint-plugin-development: ^1.0.1 => 1.0.1
    @babel/plugin-proposal-class-properties: ^7.8.3 => 7.8.3
    @babel/plugin-proposal-dynamic-import: ^7.8.3 => 7.8.3
    @babel/plugin-proposal-export-namespace-from: ^7.8.3 => 7.8.3
    @babel/plugin-proposal-object-rest-spread: ^7.9.6 => 7.9.6
    @babel/plugin-transform-flow-strip-types: ^7.9.0 => 7.9.0
    @babel/plugin-transform-for-of: ^7.9.0 => 7.9.0
    @babel/plugin-transform-modules-commonjs: ^7.9.6 => 7.9.6
    @babel/plugin-transform-runtime: ^7.9.6 => 7.9.6
    @babel/preset-env: ^7.9.6 => 7.9.6
    @babel/preset-flow: ^7.9.0 => 7.9.0
    @babel/register: ^7.9.0 => 7.9.0
    @babel/runtime: ^7.9.6 => 7.9.6
    babel-eslint: ^11.0.0-beta.2 => 11.0.0-beta.2
    babel-jest: ^24.9.0 => 24.9.0
    babel-plugin-transform-charcodes: ^0.2.0 => 0.2.0
    eslint: ^6.8.0 => 6.8.0
    gulp-babel: ^8.0.0 => 8.0.0
    jest: ^24.9.0 => 24.9.0
    lerna: ^3.19.0 => 3.19.0
    rollup-plugin-babel: ^4.4.0 => 4.4.0
```

**Possible Solution**

**Additional context**
Add any other context about the problem here. Or a screenshot if applicable

### PR DESCRIPTION
**Pull request by yulanggong**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            |  Fixes #11591 
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  | No
| License                  | MIT

### CODE REVIEW

File: packages/babel-traverse/src/scope/lib/renamer.js [hunk 1]
```diff
@@ -20,7 +20,7 @@ const renameVisitor = {
     }
   },
 
-  "AssignmentExpression|Declaration"(path, state) {
+  "AssignmentExpression|Declaration|VariableDeclarator"(path, state) {
```
Comment (nicolo-ribaudo) [inline packages/babel-traverse/src/scope/lib/renamer.js:23]:
```suggestion
  "AssignmentExpression|Declaration|VariableDeclarator"(path, state) {
    if (path.isVariableDeclaration()) return;
```

Otherwise we check var bindings twice. It shouldn't cause problems, but it's unnecessary.

File: packages/babel-traverse/test/fixtures/rename/parameter-default-11/input.js [hunk 2]
```diff
@@ -0,0 +1,7 @@
+function test(b) {
```
Comment (JLHwung) [inline packages/babel-traverse/test/fixtures/rename/parameter-default-11/input.js:1]: Can you rename the test case by `rename/function-body-declaration`? It seems to me not that related to `parameter-default`.

Comment (yulanggong) [reply packages/babel-traverse/test/fixtures/rename/parameter-default-11/input.js]: done
