### PR TITLE
Parse async arrows with flow type parameters

### LINKED ISSUE #6712: flow + async + generics => SyntaxError
> Issue originally reported by @pavelkucera in babel/babylon#235

### Input Code

```js
// @flow

const test = async <T>(fn: () => T): Promise<T> => {
    return fn();
};
```

### Babylon/Babel Configuration

```js
{
  "presets": ["es2016-node5"],
  "plugins": ["transform-flow-strip-types"]
}
```

### Expected Behavior
The Flow notation is correct as far as I can tell (flow check is performed without any errors) and I expect Babel to properly strip the types

### Current Behavior
Babel reports a syntax error:
```
SyntaxError: src/async-generics.js: Unexpected token, expected ; (3:35)
  1 | // @flow
  2 | 
> 3 | const test = async <T>(fn: () => T): Promise<T> => {
    |                                    ^
  4 |     return fn();
  5 | };
  6 | 
```

And behaves correctly after removing async from the declaration.

### Your Environment

| software         | version
| ---------------- | -------
| Babylon          |  6.14.1
| node             | 6.9.1
| npm              | 3.10.9
| Operating System | macOS

I prepared a sandbox replicating the issue at https://github.com/pavelkucera/babel-flow-async-generics-syntax-error with a travis build showing the error at https://travis-ci.org/pavelkucera/babel-flow-async-generics-syntax-error

You can see that whilst flow performs the check without any issue - https://travis-ci.org/pavelkucera/babel-flow-async-generics-syntax-error#L199
Babel fails - https://travis-ci.org/pavelkucera/babel-flow-async-generics-syntax-error#L207

Is this a bug? If so, please let me know if you need more information about the error, thank you.

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #6712
| Patch: Bug Fix?          | yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR         | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

File: packages/babylon/src/plugins/flow.js [hunk 1]
```diff
@@ -2219,8 +2219,56 @@ export default (superClass: Class<Parser>): Class<Parser> =>
...
       return super.parseSubscripts(base, startPos, startLoc, noCalls);
     }
+
+    parseAsyncArrowWithTypeParameters(
+      startPos: number,
+      startLoc: Position,
+    ): ?N.ArrowFunctionExpression {
+      const node = this.startNodeAt(startPos, startLoc);
+
+      const oldInFunc = this.state.inFunction;
```
Comment (Andarist) [inline packages/babylon/src/plugins/flow.js]: this seems really hacky, looks like the real problem is in the `parseArrow` or `parseFunctionBodyAndFinish`

Comment (nicolo-ribaudo) [reply packages/babylon/src/plugins/flow.js]: Yeah, you are right.

File: packages/babylon/test/fixtures/flow/type-generics/async-arrow-like/actual.js [hunk 2]
```diff
@@ -0,0 +1,5 @@
+async <T>(fn: () => T);
+
+// This looks A LOT like an async arrow function, but it isn't because
+// T + U isn't a valid type parameter.
+(async <T + U>(fn: T): T => fn);
```
Comment (nicolo-ribaudo) [inline packages/babylon/test/fixtures/flow/type-generics/async-arrow-like/actual.js]: Sorry I couldn't resist adding a really confusing test :smile:
