### PR TITLE
Fix scope of catch block

### LINKED ISSUE #5979: CatchClause and Catch's BlockStatement have separate scopes
```js
try { bar(); }
catch (err) { // <----- errPath.scope = CatchClause    (and) scope.uid = 1
  const foo = 1; // <-- fooPath.scope = BlockStatement (and) scope.uid = 2
}
```

For a functionExpression, the variables inside the function have the same scope as the function name.

```js
var f = function foo() { // <-- scope.uid = 42
  const a = 1; // scope.uid = 42
}
```

**Context:**

This causes a bug in babili's mangling - https://github.com/babel/babili/issues/635 - where the logic is to traverse through Scopables in BFS and rename ids. So it mangles for CatchClause and reuses the same name for BlockStatement since these are recognised as 2 different scopes.

I'd like to get a confirmation that this is a bug. I'll find a fix for this and send a PR soon.

### PR DESCRIPTION
**Pull request by boopathi**
| Q                        | A 
| ------------------------ | ---
| Patch: Bug Fix?          | yes
| Major: Breaking Change?  | no
| Minor: New Feature?      | no
| Deprecations?            | no
| Spec Compliancy?         | yes
| Tests Added/Pass?        | 
| Fixed Tickets            | Fix #5979
| License                  | MIT
| Doc PR                   | 
| Dependency Changes       | 

This fixes the issue mentioned in #5979 where a `CatchClause` and it's `BlockStatement` have different `Scope`s - which causes issues in babili's mangling - https://github.com/babel/babili/issues/635

### CODE REVIEW

**Comment by boopathi** [comment]
I hope I'm reading it right - 

http://www.ecma-international.org/ecma-262/6.0/#sec-try-statement-static-semantics-early-errors

> It is a Syntax Error if any element of the BoundNames of CatchParameter also occurs in the VarDeclaredNames of Block.

and in B3.5 - http://www.ecma-international.org/ecma-262/6.0/#sec-variablestatements-in-catch-blocks

> It is a Syntax Error if any element of the BoundNames of CatchParameter also occurs in the VarDeclaredNames of Block, unless that element is only bound by a VariableStatement or the VariableDeclarationList of a for statement, or the ForBinding of a for-in statement.

and 

> NOTE: The Block of a Catch clause may contain var declarations that bind a name that is also bound by the CatchParameter. At runtime, such bindings are instantiated in the VariableDeclarationEnvironment. They do not shadow the same-named bindings introduced by the CatchParameter and hence the Initializer for such var declarations will assign to the corresponding catch parameter rather than the var binding. The relaxation of the normal static semantic rule does not apply to names only bound by for-of statements.

So,

```js
try {}
catch (e) {
  let e;
}
```

is a SyntaxError and the failing test should be fixed. I'll wait for some feedback on this.

**Comment by boopathi** [comment]
Have to add another test case - 

```js
try {} catch (e) { let e; }
```

now throws.

File: packages/babel-types/src/definitions/core.js [hunk 1]
```diff
@@ -154,7 +154,7 @@ defineType("CatchClause", {
       validate: assertNodeType("BlockStatement"),
     },
   },
-  aliases: ["Scopable"],
+  aliases: ["Scopable", "BlockParent"],
```
Comment (boopathi) [inline packages/babel-types/src/definitions/core.js]: I'm not sure about this. Please take a second look at this change.

In `babel-types/src/validators` part of this PR(as shown below), we say flag that the block statement of a CatchClause is not Scopable. And BlockScoped bindings are registered as `scope.getBlockParent().registerBinding`.

So, when registering the `let e` in `catch(e) { let e }`, we have `scope.getBlockParent` where `scope=Catch` and the BlockScope ends up being registered in the wrong scope. So, we include a `BlockParent` alias to the CatchClause.

If you think this should be done in some other way, feel free to suggest. 

The aim is to throw for this code - 

```js
try {} catch (e) { let e }
```

**Comment by boopathi** [comment]
This can be merged if everything is fine. The test is already added.
