### PR TITLE
Fix JSX pragma anywhere in comment

### LINKED ISSUE #13896: [Bug]: JSX pragma can happen anywhere in a comment
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
// Make sure not to use a jsx pragma here (like "@jsx Something"), we need this to be React.createElement!
<blah/>
```

### Configuration file name

_No response_

### Configuration

N/A

### Current and expected behavior

Currently, the above will actually generate this code:

```js
Something"),("blah", null);
``` 

But, even if ignore the syntax error, it seems to me that JSX pragmas should be a bit stricter as to what they match.For example, if we just add the `^` and `$` operators to the current RegExp:
```regex
/\*?\s*@jsx\s+([^\s]+)/
```
becomes:
```regex
/\^*?\s*@jsx\s+([^\s]+)$/
```
Then this would lead to jsx pragmas only being allowed if they are the only content in the comment. This seems to me to be more in the spirit of the intent.

In many ways, the current RegExp is a bit nonsensical just in its construction: `*?\s*` with no ^ is a completely useless pattern, since the entire sequence is optional and there's nothing preceding it. That's why something like "francisco@jsx hi'' is matched.

BTW, I actually ran into this myself, which is why I am filing this. It's annoying that one's first inclination to "escape" the jsx pragma (by doing something like \\@jsx blah) doesn't work either, for the same reason "francisco@jsx hi" is matched.

### Environment

N/A

### Possible solution

Changing

```regex
/\*?\s*@jsx\s+([^\s]+)/
```
to

```regex
/\^*?\s*@jsx\s+([^\s]+)$/
```

And making the equivalent change for JSX fragments.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by The-x-Theorist**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #13896  
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

Regex pattern was changed for only JSX pragma annotation in comments.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14012"></a>

### CODE REVIEW

File: packages/babel-plugin-transform-react-jsx/src/create-plugin.ts [hunk 1]
```diff
@@ -167,29 +170,25 @@ You can set \`throwIfNamespace: false\` to bypass this warning.`,
 
             if (file.ast.comments) {
               for (const comment of file.ast.comments) {
-                const sourceMatches = JSX_SOURCE_ANNOTATION_REGEX.exec(
-                  comment.value,
-                );
+                const value = `/*${comment.value}*/`;
```
Comment (JLHwung) [inline packages/babel-plugin-transform-react-jsx/src/create-plugin.ts:173]: The `comment.value` is either a block comment without the wrapping `/* */` or an inline comment without the leading `//`. I think we don't need to add `/* */` back, instead we can remove `/* */` in the regex.

Comment (The-x-Theorist) [reply packages/babel-plugin-transform-react-jsx/src/create-plugin.ts:173]: I tried removing `/* */` in regex but it isn't working right it works same as old.

Comment (JLHwung) [reply packages/babel-plugin-transform-react-jsx/src/create-plugin.ts:173]: I don't think I can follow. Aren't these propositions logically equivalent to each other?

```
s = " @jsx jsx " implies that /^\*?\s*@jsx\s+([^\s]+)\s*$/.test(s) is true
```

```
s = " @jsx jsx " implies that /^\/\*\*?\s*@jsx\s+([^\s]+)\s*\*\/$/.test(`/*${s}*/`) is true
```

Comment (The-x-Theorist) [reply packages/babel-plugin-transform-react-jsx/src/create-plugin.ts:173]: I think this proposition is equal and the first one will work-out.

Comment (The-x-Theorist) [reply packages/babel-plugin-transform-react-jsx/src/create-plugin.ts:173]: I will make a new commit with the change

File: packages/babel-plugin-transform-react-jsx/src/create-plugin.ts [hunk 2]
```diff
@@ -31,11 +31,13 @@ const DEFAULT = {
   pragmaFrag: "React.Fragment",
 };
 
-const JSX_SOURCE_ANNOTATION_REGEX = /\*?\s*@jsxImportSource\s+([^\s]+)/;
-const JSX_RUNTIME_ANNOTATION_REGEX = /\*?\s*@jsxRuntime\s+([^\s]+)/;
+const JSX_SOURCE_ANNOTATION_REGEX =
+  /^\*?\s*?\*?\*?\s*@jsxImportSource\s+([^\s]+)\s*$/;
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-react-jsx/src/create-plugin.ts:35]: I think we have too many `*`s: we shouldn't accept `* ** @jsxImportSource` (`\s*?\*?` should be deleted from the regexp)

Comment (nicolo-ribaudo) [reply packages/babel-plugin-transform-react-jsx/src/create-plugin.ts:35]: Oh I just saw https://github.com/babel/babel/issues/13896#issuecomment-982985687. I think it can be correctly handled using a regexp like
```js
const SPACE_NO_NEWLINE = /(?:(?![\r\n])\s)/.source;
const JSX_SOURCE_ANNOTATION_REGEX = new RegExp(
  String.raw`${SPACE_NO_NEWLINE}*\*?${SPACE_NO_NEWLINE}*@jsxImportSource\s+([^\s]+)[\s\*]*$`,
  "m"
);
```

Or even just
```js
const JSX_SOURCE_ANNOTATION_REGEX = /\s*\*?\s*@jsxImportSource\s+([^\s]+)[\s\*]*$/m;
```

even if it accepts too much newlines.

Comment (The-x-Theorist) [reply packages/babel-plugin-transform-react-jsx/src/create-plugin.ts:35]: Okay, I will remove the extra spaces.

**Review by nicolo-ribaudo — APPROVED** [review]
Thanks!

**Review by JLHwung — APPROVED** [review]
