### PR TITLE
fix: ts exported vars are shadowed by `declare`

### LINKED ISSUE #14945: [Bug]: TypeScript plugin drops class export
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```ts
declare class Signal<T = any> {
	value: T
}

function Signal(this: Signal, value?: unknown) {
	this.value = value
}

export { Signal };
```

### Configuration file name

_No response_

### Configuration

```json
{
  "presets": ["@babel/preset-typescript"]
}
```

### Current and expected behavior

Actual output:

```js
function Signal(value) {
  this.value = value;
}

export {};
```

Expected output, see this [TypeScript playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEkoGdnwMoEsDmA7KEAPACrwC88UuAngHzwDeAUAJABuBAriAFzzFMAvkyYAzTrjAAXTAHtcGHPggAKKQAtMyPljwEANPA4RuAfj4SA1rlkB3XAEpGrDVoB0x7uSNcQQkSAAHgAOsjBSziy6ykIA3ExAA):

```js
function Signal(value) {
    this.value = value;
}
export { Signal };
```

Basically there is a compilation difference between babel's TypeScript preset and TypeScript itself.

### Environment

OS: macOS 12.5.1
Node: 18.8.0
Yarn: 1.22.17
@babel/core: 7.19.1
@babel/preset-typescript: 7.18.6
Monorepo: no

### Possible solution

_No response_

### Additional context

My assumption is that babel sees the `declare class Signal {}` line and tags it as a type-only thing or something like that.

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #14945 
| Patch: Bug Fix?          |√
| Tests Added + Pass?      | √
| License                  | MIT

For performance I didn't do a full traversal, for ts this is enough.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14946"></a>

### CODE REVIEW

**Review by 3Boysmom — APPROVED** [review]

File: packages/babel-plugin-transform-typescript/test/fixtures/exports/declare-shadowed/input.ts [hunk 1]
```diff
@@ -0,0 +1,9 @@
+declare class Signal<T = any> {
+	value: T
+}
+
+function Signal(this: Signal, value?: unknown) {
+	this.value = value
+}
+
+export { Signal };
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-typescript/test/fixtures/exports/declare-shadowed/input.ts:9]: Can also add a test with the declarations swapped?

```ts
declare class Signal<T = any> {
	value: T
}

function Signal(this: Signal, value?: unknown) {
	this.value = value
}

export { Signal };
```

Comment (liuxingbaoyu) [reply packages/babel-plugin-transform-typescript/test/fixtures/exports/declare-shadowed/input.ts:9]: ts seems to show that it cannot be merged.

**Review by nicolo-ribaudo — APPROVED** [review]

**Comment by nicolo-ribaudo** [comment]
This is good for now, but in the future we should move the fix to inside `path.remove()`

**Review by JLHwung — APPROVED** [review]
