### PR TITLE
Don't loose "this" in helper-call-delegate

### LINKED ISSUE #9385: Typescript loses this in class method when parameter has type signature and default value
## Bug Report

**Current Behavior**
Having code as in example will produce invalid es5 with broken this

**Input Code**

```ts
export class Test {
  invite(options: { privacy: string } = {}) {
    const privacy = options.privacy || "Private"
    console.log(this)
  }
}
```

Babel output will be:
```js
export var Test =
/*#__PURE__*/
function () {
  function Test() {
    _classCallCheck(this, Test);
  }

  _createClass(Test, [{
    key: "invite",
    value: function invite() {
      var options = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {};
      return function () {
        var privacy = options.privacy || "Private";
        console.log(this);
      }();
    }
  }]);

  return Test;
}();
```

**Expected behavior/code**
No additional scope should be created.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "plugins": [
    "@babel/plugin-transform-typescript"
  ],
  "env": {
    "production": {
      "presets": [
        [
          "@babel/preset-env",
          {
            "modules": false
          }
        ]
      ]
    }
  }
}
```

**Environment**
- Babel version(s): 7.2.0
- Node/npm version: Node 10/npm 6
- OS: OSX
- Monorepo: no
- How you are using Babel: `cli`, `loader`]

**Possible Solution**
A possible workaround is to move type from method declaration:

```ts
type Options = { privacy: string }
export class Test {
  invite(options: Options = {}) {
    const privacy = options.privacy || "Private"
    console.log(this)
  }
}
```

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #9385
| Patch: Bug Fix?          | y
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

File: packages/babel-plugin-transform-parameters/test/fixtures/parameters/iife-this-9385/output.js [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+function () {
+  function Test() {
+    _classCallCheck(this, Test);
+  }
+
+  _createClass(Test, [{
+    key: "invite",
+    value: function invite() {
+      var options = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {};
+      return function () {
```
Comment (jridgewell) [inline packages/babel-plugin-transform-parameters/test/fixtures/parameters/iife-this-9385/output.js]: Why is the wrapper generated?

Comment (nicolo-ribaudo) [reply packages/babel-plugin-transform-parameters/test/fixtures/parameters/iife-this-9385/output.js]: Babel deopts because it thinks that the `privacy` key in the object type is a reference. I opened a PR to fix the iife case, but I'll see how we can avoid the deoptimization here.

Comment (nicolo-ribaudo) [reply packages/babel-plugin-transform-parameters/test/fixtures/parameters/iife-this-9385/output.js]: Will be fixed by #9605
