### PR TITLE
Fix derived classes in Chrome <= 36

### LINKED ISSUE #14056: [Bug]: subclassing seems broken in older Chrome
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```js
(function (cb) {
	class Foo extends HTMLElement {
		connectedCallback() {
			this._baz = 'hello';
		}

		baz() {
			return this._baz;
		}
	}

	class Fooz extends Foo {
		connectedCallback() {
			super.connectedCallback();

			this._baz = this._baz + ' world';
		}
	}

	customElements.define('web-test-fooz', Fooz);
	document.body.appendChild(new Fooz());
	var fooz = document.getElementsByTagName('web-test-fooz')[0];

	cb(fooz.baz() === 'hello world');
})(callback);
```

### Configuration file name

_No response_

### Configuration

https://github.com/mrhenry/web-tests/blob/main/webpack-core-web.config.js#L166-L217

```js
use: {
	loader: 'babel-loader',
	options: {
		comments: false,
		presets: [
			[
				'@babel/preset-env',
				{
					corejs: '^3.6.3',
					bugfixes: true,
					targets: {
						browsers: [
							"IE >= 8",
							"Opera >= 12",
							"Safari >= 5.1",
							"Chrome >= 15",
							"Edge >= 12",
							"Firefox >= 4"
						]
					},
					useBuiltIns: 'usage',
					exclude: [
						"web.dom-collections.iterator",
						"web.dom-collections.for-each"
					]
				}
			]
		]
	}
}
```

### Current and expected behavior

Current :

`Uncaught TypeError: Cannot call a class as a function`

In `function _classCallCheck`

Screenshot 2021-12-15 at 14 38 07

Expected subclasses to work.

### Environment

Started occurring after upgrading `@babel/core` from 7.16.0 to 7.16.5

### Possible solution

_No response_

### Additional context

**Test results page :**
https://mrhenry.github.io/web-tests/#53d613d8-773c-43d5-800b-a78aeeab8ef7

Screenshot 2021-12-15 at 14 40 49

Results for chrome <=36 dropped below `1.0` indicating that the test is now failing.
The only change between tests passing and tests failing is this commit : https://github.com/mrhenry/web-tests/commit/16599fd5bd5716d24c63d9dbed57ca63408796c9

(build outputs are included in git)

**Test source code :** 
https://github.com/mrhenry/web-tests/blob/main/specifications/whatwg/html/4.13.4.customElements.define.super/test.pure.js

**Git blame for the affected build output :**

https://github.com/mrhenry/web-tests/blame/main/specifications/whatwg/html/4.13.4.customElements.define.super/test.babel.js

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #14056
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

Unfortunately we don't have the infrastructure to run tests in real old browsers, so you can either trust me and @romainmenke that it works or you can download Chrome <= 36 and try it yourself! :sweat_smile: 

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14072"></a>

### CODE REVIEW

**Comment by romainmenke** [comment]
Fix works in chrome 14-36 (I can't test older versions)

https://mrhenry.github.io/web-tests/#293ee801-4d53-4261-add3-dca6b9f8015f

- 0.1 values indicates it is passing but used to fail, takes a few runs for values to settle back on 1.0
- values that are still 0.0 are just rounded values (0.04 => 0.0)

No test cases dropped in score.

Screenshot 2021-12-21 at 19 27 49

**Review by JLHwung — APPROVED** [review]
Nit: can you also add link to the upstream issue?

https://bugs.chromium.org/p/v8/issues/detail?id=3334

File: packages/babel-helpers/src/helpers.ts [hunk 1]
```diff
@@ -335,16 +335,16 @@ helpers.inherits = helper("7.0.0-beta.0")`
...
-      value: Object.create(superClass && superClass.prototype, {
-        constructor: {
-          value: subClass,
-          writable: true,
-          configurable: true
-        }
-      }),
-      writable: false,
+    // We can't use defineProperty to set the prototype in a single step because it
+    // doesn't work in Chrome <= 36. https://github.com/babel/babel/issues/14056
```
Comment (nicolo-ribaudo) [inline packages/babel-helpers/src/helpers.ts:339]:
```suggestion
    // doesn't work in Chrome <= 36. https://github.com/babel/babel/issues/14056
    // V8 bug: https://bugs.chromium.org/p/v8/issues/detail?id=3334
```

**Review by existentialism — APPROVED** [review]
