### PR TITLE
Fix TypeScript Enum self-references

### LINKED ISSUE #14092: [Bug]: Enum member init expressions should qualify member name references in certain cases
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```TypeScript
var x = 10;
enum Foo {
    a = 10,
    b = a,
    c = b + x,
}
```

### Configuration file name

_No response_

### Configuration

with TypeScript default config

### Current and expected behavior

Babel output([REPL](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=KYDwDg9gTgLgBMAdgVwLZwGIQnA3gKDiLgG0ByAIwEMAvMgXQBp8BffIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cstage-2%2Ctypescript&prettier=false&targets=&version=7.12.12&externalPlugins=&assumptions=%7B%7D)):
```JavaScript 
var x = 10;
var Foo;

(function (Foo) {
  Foo[Foo["a"] = 10] = "a";
  Foo[Foo["b"] = 10] = "b";
  Foo[Foo["c"] = b + x] = "c";
})(Foo || (Foo = {}));
```

TypeScript output([REPL](https://www.typescriptlang.org/play?#code/G4QwTgBAHhC8EEYAMBuAUAUwHYFcC2EAYgPbEQDeaE1EIciSANFTQEb0jM0QDG97AamjMAvkA)) which is expected behavior:
```JavaScript 
var x = 10;
var Foo;
(function (Foo) {
    Foo[Foo["a"] = 10] = "a";
    Foo[Foo["b"] = 10] = "b";
    Foo[Foo["c"] = Foo.b + x] = "c";
})(Foo || (Foo = {}));
```

### Environment

  System:
    OS: macOS 12.1
  Binaries:
    Node: 16.13.1 - /opt/homebrew/Cellar/node@16/16.13.1/bin/node
    Yarn: 1.22.15 - /opt/homebrew/bin/yarn
    npm: 8.1.2 - /opt/homebrew/Cellar/node@16/16.13.1/bin/npm

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by magic-akari**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #14092
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14093"></a>

### CODE REVIEW

**Comment by lightmare** [comment]
The replacement should skip nested identifiers. Otherwise this breaks: 
```js
enum Bar {
  a = 1,
}
enum Foo {
  a = 2,
  b = Bar.a,
}
```

**Comment by magic-akari** [comment]
> The replacement should skip nested identifiers. Otherwise this breaks:
> 
> ```ts
> enum Bar {
>   a = 1,
> }
> enum Foo {
>   a = 2,
>   b = Bar.a,
> }
> ```

It works. I updated the tests.

**Comment by JLHwung** [comment]
I am surprised that the enum reference can be resolved to either an enum member or the whole enum struct. For example TS nightly resolves `b.a` as if it were `A.a` ([playground](https://www.typescriptlang.org/play?ts=4.6.0-dev.20211231#code/KYOwrgtgBAglDeAoKKoEMoF4oAYA0yqARllAIwGpQAepRAdGgQL5A)).

```ts
enum A {
    a = 0,
    b = 1,
    x = b.a,
}
```

**Comment by magic-akari** [comment]
> I am surprised that the enum reference can be resolved to either an enum member or the whole enum struct. For example TS nightly resolves `b.a` to 0 as if it were `A.a` ([playground](https://www.typescriptlang.org/play?ts=4.6.0-dev.20211231#code/KYOwrgtgBAglDeAoKKoEMoF4oAYA0yqARllAIwGpQAepRAdGgQL5A)).
> 
> ```ts
> enum A {
>     a = 0,
>     b = 1,
>     x = b.a,
> }
> ```

This looks very strange and I'm going to report the issue to TypeScript.

File: packages/babel-plugin-transform-typescript/src/enum.ts [hunk 1]
```diff
@@ -124,7 +125,29 @@ export function translateEnumValues(
           value = t.stringLiteral(constValue);
         }
       } else {
-        value = initializer;
+        const IdentifierVisitor: Visitor = {
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-typescript/src/enum.ts:128]: Please move this visitor to the top-level of the file. We do some processing+validation to visitors, and if it's always the same object this work can be cached. You can get the `seen` map by using the "state" parameter:
```js
          Identifier(expr, { seen }) {
            // ...
```

(style nit: we always call non-classes with a name that starts with a lowercase letter. Maybe `enumSelfReferenceVisitor`.

File: packages/babel-plugin-transform-typescript/src/enum.ts [hunk 2]
```diff
@@ -124,7 +125,29 @@ export function translateEnumValues(
...
+          MemberExpression(expr) {
+            expr.skip();
+          },
+        };
+
+        const exprStmt = t.expressionStatement(initializer);
+
+        traverse(t.program([exprStmt]), IdentifierVisitor);
+
+        value = exprStmt.expression;
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-typescript/src/enum.ts:149]: Rather than creating a "fake" program in order to traverse this, you can:
1. Replace `return path.node.members.map(member => {` a few lines above with
    ```js
    return path.members.map(memberPath => {
    ```
    so that you have access to the `NodePath`s rather than to the raw nodes
2. Get the `initializerPath` with `memberPath.get("initializer")`
3. Traverse it with
   ```js
    if (initializerPath.isIdentifier()) {
      enumSelfReferenceVisitor.Identifier(initializerPath, { seen });
    } else {
      initializerPath.traverse(enumSelfReferenceVisitor, { seen });
    }
    ```

File: packages/babel-plugin-transform-typescript/src/enum.ts [hunk 3]
```diff
@@ -124,7 +125,29 @@ export function translateEnumValues(
...
+                  t.cloneNode(path.node.id),
+                  t.cloneNode(expr.node),
+                ),
+              );
+              expr.skip();
+            }
+          },
+          MemberExpression(expr) {
+            expr.skip();
+          },
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-typescript/src/enum.ts:142]: I think that skipping member expressions breaks transpilation of this code:
```js
enum A {
    a = 0,
    b = 1,
    // @ts-ignore
    x = a.toString(),
}
```

You can try visiting `ReferencedIdentifier` instead of `Identifier`, so that it only visits the "correct" identifiers and you don't need to manually skip member expressions.

**Review by nicolo-ribaudo — COMMENTED** [review]
> This seems very weird, and I'm going to report the issue to TypeScript.

I agree, it looks like a TS bug.

File: packages/babel-plugin-transform-typescript/src/enum.ts (hunk 2 above)
Comment (magic-akari) [reply packages/babel-plugin-transform-typescript/src/enum.ts]: Thanks, it helps a lot.

I've run into another problem.
After Visitor is used once, the internal `ReferencedIdentifier` function is not accessible again, which causes me to bring it up in the top scope.

**Review by JLHwung — COMMENTED** [review]
I think we should handle enum reference in scope tracking, because enum initializer can have nested scopes, e.g.

```ts
enum A {
    a = 0,
    b = (() => { let a = 1; return a + 1 })(), // a is shadowed
    c = (() => { return a + 2 })(), // a refers to A.a
}
```

This is exactly what scope tracking handles. We can mark `TSEnumDeclaration` as `Scopeable` in babel-types, so that babel-traverse will setup new scope for it. Then we can register const binding for every enum members in

https://github.com/babel/babel/blob/ddd93b9c61a197711c2e3eae8a8b175783ea6976/packages/babel-traverse/src/scope/index.ts#L225

Now in the TS transform we can retrieve all the referenced Paths from the scope info: `enumDelcarationPath.scope.getOwnBinding("a").referencePaths`, then replace them by member expressions.

As a bonus, the scope tracking should automatically throws on the following invalid cases, which we are now incorrectly passing:

```ts
enum A {
    b = a + 1, // can not reference a before initialization
    a = 0
}
```

**Comment by magic-akari** [comment]
Hi, @JLHwung 
I cannot manage to get `getOwnBinding(name).referencePaths` to work.
Instead, I use `scope.hasOwnBinding` to detect if the name has a binding, and if not, bind it to the Enum name.
It seems to work, but it's not quite the same as the solution you gave.
Could you give me more hints?

**Comment by magic-akari** [comment]
Hi, @JLHwung ,
I tried mark `TSEnumDeclaration ` as `Scopeable`.
It breaks a test case.

```TypeScript
enum A {
  C = 2,
}
namespace A {
  export const B = 1;
}
```

output changes:
```diff
var A;
(function (A) {
    A[A["C"] = 2] = "C";
})(A || (A = {}));

+ let A;

(function (A) {
    A.B = 1;
})(A || (A = {}));
```

`enum` and `namespace`  are mergeable.
Adding a scope to `enum` will cause them not to be merged.
Refactoring `enum` and `namespace ` at the same time is a big work.
- Maybe it would be better to do it after the #11065 be merged.

**Comment by magic-akari** [comment]
Here are some of the interesting things I found while exploring TS Scope.
The enum in the definition can be merged with each other.

```typescript
enum Foo {
    a = 1,
}

enum Foo {
    b = 2,
}
```

```javascript
var Foo;
(function (Foo) {
    Foo[Foo["a"] = 1] = "a";
})(Foo || (Foo = {}));
(function (Foo) {
    Foo[Foo["b"] = 2] = "b";
})(Foo || (Foo = {}));
```

But namespace can also be merged with enum.

```typescript
enum Foo {
    a = 1,
}

namespace Foo {
    export const b = 2;
}
```

```javascript
var Foo;
(function (Foo) {
    Foo[Foo["a"] = 1] = "a";
})(Foo || (Foo = {}));
(function (Foo) {
    Foo.b = 2;
})(Foo || (Foo = {}));
```

In fact namespace can be merged with many things like function and class.

```typescript
class Foo {
    a = 1;
}
namespace Foo {
    export const b = 2;
}

function Bar() {}
namespace Bar {
    export const __esModule = true;
}
```

```javascript
class Foo {
    constructor() {
        this.a = 1;
    }
}
(function (Foo) {
    Foo.b = 2;
})(Foo || (Foo = {}));
function Bar() { }
(function (Bar) {
    Bar.__esModule = true;
})(Bar || (Bar = {}));
```

What if you define both function, enum and namespace with the same name?
You get an error 'Enum declarations can only merge with namespace or other enum declarations.'

**Comment by JLHwung** [comment]
I think the current PR is good enough to go.

To fully support enum reference and the merging behaviour, we can introduce accumulation scope and create `tsEnum` binding info.

An accumulation scope is a scope 1) shared within an array of nodes and 2) incrementally created for nodes spanned in different AST. For example, in an enum declaration

```ts
interface EnumDeclaration {
  id: Identifier,
  members: EnumMember[]
}
```

The enum id should be registered in the upper scope, so the enum scope is only shared within its members. Currently for every Scopeable AST node, we create an isolated scope for the node. To support accumulation scope, let's say we first register a new enum-kind binding for the enum id, with some extra binding info:

```ts
Binding {
  kind: "enum",
  enumMembers: Scope
}
```

now we can extend 

https://github.com/babel/babel/blob/ddd93b9c61a197711c2e3eae8a8b175783ea6976/packages/babel-traverse/src/path/context.ts#L130

when `this` is an EnumMember, we return `parentPath.scope.getOwnBinding(parentPath.id.name).enumMembers` as `path.scope`. Because it is an accumulation scope, we always run `scope.crawl()` instead of `scope.init()` (which is basically run scope.crawl() only once), so every enum member is effectively registered within this scope.

As the accumulation scope is now determined only by the enum id binding, we can handle the mergable enum because `parentPath.scope.getOwnBinding(parentPath.id.name).enumMembers` returns the same scope for every enum defined within the same scope. We can also handle namespace with extra codes.

The storage of accumulation scope can be improved: as long as the scope can be accessed and uniquely determined. For example, it can be placed in parent scope (where enum is defined) as `Map<string, Scope>`.

This approach can potentially handle another issue: https://github.com/babel/babel/issues/14023#issuecomment-993058731, we can create an accumulation scope for all non-simple formal parameters.

**Review by JLHwung — APPROVED** [review]

**Review by nicolo-ribaudo — APPROVED** [review]
Thanks!
