### PR TITLE
Fix handling of `this`&co in computed keys in arrows transform

### LINKED ISSUE #13981: [Bug]: Incorrectly transpile this in object getter/setter/method in arrow function
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
function foo() {
  return () => ({
  [this]: 123,
  get [this + "1"]() {
  }
})}

console.log(foo.call({ x: 123 })())
```

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

Should log
```js
Object { "[object Object]": 123, "[object Object]1": Getter }
```
but get
```js
Object { "[object Object]": 123, undefined1: Getter }
```

### Environment

babel repl

### Possible solution

Transpile computed name in getter/setter/method too

### Additional context

[repl link](https://babeljs.io/repl#?browsers=chrome%2045&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABMOcAUBKRBvAUIxAJwFMoRClNEBeAPkTTwIG0oALGAZwF0AuRAIwAmAMwAafIgDmpRKw6dEAakQAiAau5UmiAL65dGfbggJOcADbEAdBbhS0KONYgBDCxcaIAHv2Ei9DEwMIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.16.4&externalPlugins=&assumptions=%7B%7D)

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #13981
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

I had to extract `environmentVisitor` to a new package to avoid circular deps between `@babel/traverse` and `@babell/helper-replace-supers`.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14005"></a>

### CODE REVIEW

File: packages/babel-helper-environment-visitor/src/index.ts [hunk 1]
```diff
@@ -0,0 +1,45 @@
+import type { NodePath } from "@babel/traverse";
+import { VISITOR_KEYS, staticBlock } from "@babel/types";
+import type * as t from "@babel/types";
+
+// TODO (Babel 8): Don't export this function.
+export function skipAllButComputedKey(
+  path: NodePath<t.Method | t.ClassProperty | t.ClassPrivateProperty>,
```
Comment (JLHwung) [inline packages/babel-helper-environment-visitor/src/index.ts:7]: It seems to me that `skipAllButComputedKey` is not invoked on `ClassPrivateProperty`.

**Review by JLHwung — APPROVED** [review]

**Review by existentialism — APPROVED** [review]
