### PR TITLE
Preserve class id when transforming using declarations with exported class

### LINKED ISSUE #17172: `plugin-proposal-explicit-resource-management` incorrect transform for exported class
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
using x = foo();

export class C {
  static getSelf() { return C; }
}
const K = C;
C = 123;

assert(K.getSelf() === K);
```

[REPL](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=K4Zwlgdg5gBAHjAvDAZgezQCgJQG4BQ-ApnAA5oBOALjAMYA2AhiCDAMIwDe-MMIVjKmFowoRKgGUi9FDi49eMCuOAUI7ArwC--HbTQR-MANJIN-DsgCMAJgDMBZiCLVMxgHRjJ02diSJkYzx8IA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=true&targets=&version=7.26.9&externalPlugins=%40babel%2Fplugin-proposal-explicit-resource-management%407.25.9&assumptions=%7B%7D)

### Configuration file name

_No response_

### Configuration

n/a - just using REPL

### Current and expected behavior

Output after transform with [@babel/plugin-proposal-explicit-resource-management](https://babeljs.io/docs/babel-plugin-proposal-explicit-resource-management):

```js
export { C };
try {
  var _usingCtx = _usingCtx2();
  var x = _usingCtx.u(foo());
  var C = class {
    static getSelf() { return C; }
  };
  var K = C;
  C = 123;
  assert(K.getSelf() === K);
} catch (_) {
  _usingCtx.e = _;
} finally {
  _usingCtx.d();
}
```

In the original source the assertion passes. Post-transform, it fails, because `C` in `getSelf` refers to `var C`, which gets reassigned.

### Environment

n/a - just using REPL

### Possible solution

Probably simplest solution is that if the class name is referenced within class body and class's binding is mutated, the class needs to retain its name (as in source).

```diff
- var C = class { static getSelf() { return C; } };
+ var C = class C { static getSelf() { return C; } };
```

### Additional context

Sorry I'm not offering to fix. I just encountered this problem while working on implementation of this same transform in [Oxc](https://oxc.rs/). I noticed Babel has the same problem, so thought it might be useful to report it here.

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #17172 
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

This PR fixed two issues:

1. The amd/cjs/umd transform will throw when the local exports reference nested var declarations:

   ```js
   export { A }
   {
     var A
   }
   ```
   This pattern is not very popular in real-world codebase but the explicit-resource-management transform will generate such pattern.

2. Preserve class id for inner class binding references, as suggested by @overlookmotel in #17172. Fixing this issue relies on the first fix.

### CODE REVIEW

File: packages/babel-helper-module-transforms/src/normalize-and-load-metadata.ts [hunk 1]
```diff
@@ -495,13 +495,10 @@ function getLocalExportMetadata(
...
-
-      if (kind === undefined) {
-        throw idPath.buildCodeFrameError(
-          `Exporting local "${localName}", which is not declared.`,
-        );
-      }
+      // If localName is not found in the bindingKindLookup generated
+      // from top level declarations, it must be a reference to a var
+      // declaration defined within block statement or switch case
+      const kind = bindingKindLookup.get(localName) ?? "var";
```
Comment (nicolo-ribaudo) [inline packages/babel-helper-module-transforms/src/normalize-and-load-metadata.ts:501]: `export { A }` with no `{ var A }` will throw when parsing, right?

Comment (nicolo-ribaudo) [inline packages/babel-helper-module-transforms/src/normalize-and-load-metadata.ts:501]: Even with `export { A }; { var A }`, the `programPath.scope.get("A")` properly returns the `var` declaration. Could we just query the scope properly, so that we still catch invalid exports?

**Review by nicolo-ribaudo — APPROVED** [review]

**Comment by nicolo-ribaudo** [comment]
Node.js 6 is still unhappy :)

**Review by nicolo-ribaudo — APPROVED** [review]
Thanks for the scope-based update!
