### PR TITLE
Fixes 6965

### LINKED ISSUE #6965: reduce code generated of plugin-proposal-decorators
plugin-proposal-decorators create for each component using decorator same function template:

applyDecoratedDescriptor
and 
initDefineProp

so the code ended is much more bigger, 
i propose to create only this once in global what do you think?
(It s what i did inside babelHelper ...)

same this plugins use the function ensureInitializerWarning who create no useful bit for each component too:
function NAME(descriptor, context){ throw new Error(    'Decorating class property failed. Please ensure that proposal-class-properties is enabled and set to use loose mode.  To use proposal-class-properties in spec mode with decorators, wait for he next major version of decorators in stage 2

will be better to add it in global too ...

### PR DESCRIPTION
**Pull request by perinikhil**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #6965 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR         | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

File: packages/babel-plugin-proposal-decorators/src/index.js [hunk 1]
```diff
@@ -26,75 +26,18 @@ const buildGetObjectInitializer = template(`
...
   function ensureApplyDecoratedDescriptorHelper(path, state) {
     if (!state.applyDecoratedDescriptor) {
       state.applyDecoratedDescriptor = path.scope.generateUidIdentifier(
         "applyDecoratedDescriptor",
       );
-      const helper = buildApplyDecoratedDescriptor({
-        NAME: state.applyDecoratedDescriptor,
-      });
+      const helper = state.addHelper("buildApplyDecoratedDescriptor");
       path.scope.getProgramParent().path.unshiftContainer("body", helper);
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-proposal-decorators/src/index.js]: The problem is that these lines:
```js
const helper = buildApplyDecoratedDescriptor({
  NAME: state.applyDecoratedDescriptor,
});
path.scope.getProgramParent().path.unshiftContainer("body", helper);
```
added the helper function to the file.

On the other hand, `state.addHelper("buildApplyDecoratedDescriptor");` returns the id of the function (not the function itself), and the helper is added automatically.

So you should just remove the `ensure*` functions (which are the equivalent of `state.addHelper`), and replace calls to them (like https://github.com/babel/babel/blob/f5ef928586f592aa2d8bb60120ae58833d17e0db/packages/babel-plugin-proposal-decorators/src/index.js#L273) with `addHelper(" ... ")`.

**Comment by perinikhil** [comment]
Thank you @xtuc and @nicolo-ribaudo for your valuable inputs and patience! Much obliged 😃 
I've also raised a docs PR which could be reviewed as well...
And also, i'd like to pick up another issue, any suggestions?

**Comment by xtuc** [comment]
Feel free to merge @nicolo-ribaudo if it looks good to you.

@perinikhil, either:
- Priority stuff https://github.com/babel/babel/labels/Priority%3A%20High
- Beginner-friendly https://github.com/babel/babel/labels/good%20first%20issue

File: packages/babel-helpers/src/helpers.js [hunk 2]
```diff
@@ -700,3 +700,70 @@ helpers.toPropertyKey = defineHelper(`
...
+`);
+
+/**
+ * Add a helper to take an initial descriptor, apply some decorators to it, and optionally
+ * define the property.
+ */
+helpers.applyDecoratedDescriptor = defineHelper(`
+    export default function _applyDecoratedDescriptor(target, property, decorators, descriptor, context){
+        var desc = {};
+        Object['ke' + 'ys'](descriptor).forEach(function(key){
```
Comment (TrejGun) [inline packages/babel-helpers/src/helpers.js]: what is the problem to use `Object.keys(descriptor)` ?

Comment (nicolo-ribaudo) [reply packages/babel-helpers/src/helpers.js]: It is kept because it was in the original helper, I will check

Comment (xtuc) [reply packages/babel-helpers/src/helpers.js]: Because of transform-runtime, same here https://github.com/babel/babel/pull/7017/files/805c8f7cf2dc6eea9d3dcb85b55acc6a6a3334e5#diff-ba75bd4d116cc90ad8c8002e3010e821R762
