### PR TITLE
fix: Promise.any requires global.AggregateError

### LINKED ISSUE #10910: `core-js` definitions not fully injected with `useBuiltIns: usage`
## Bug Report

**Current Behavior**

When using `useBuiltIns: usage` with `core-js` to add support for `Promise.any()`, I get a `TypeError: getBuiltIn(...) is not a constructor` error. Seems it's due the fact babel is not adding the `esnext.aggregate-error` require in transpiled code. By changing `useBuiltIns` to `entry` and setting by hand both `core-js/modules/esnext.aggregate-error` and `core-js/modules/esnext.promise.any` requires, transpilation works correctly. Seems to be related to https://github.com/babel/babel/issues/10883. More details at https://github.com/zloirock/core-js/issues/737.

**Environment**
  System:
    OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
  Binaries:
    Node: 13.3.0 - /usr/bin/node
    npm: 6.13.1 - /usr/bin/npm
  npmPackages:
    @babel/cli: ^7.7.7 => 7.7.7 
    @babel/preset-env: ^7.7.7 => 7.7.7 
    babel-eslint: ^10.0.3 => 10.0.3 
    babel-jest: ^24.9.0 => 24.9.0 
    eslint: ^6.8.0 => 6.8.0

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #10910 
| Patch: Bug Fix?          | Yes
| Tests Added + Pass?      | Nope
| License                  | MIT

C.f. https://github.com/zloirock/core-js/issues/737#issuecomment-568325801

### CODE REVIEW

File: packages/babel-preset-env/src/polyfills/corejs3/built-in-definitions.js [hunk 1]
```diff
@@ -358,7 +363,7 @@ export const StaticProperties: ObjectMap<ObjectMap<string | string[]>> = {
       "esnext.promise.all-settled",
       ...PromiseDependenciesWithIterators,
     ],
-    any: ["esnext.promise.any", ...PromiseDependenciesWithIterators],
+    any: ["esnext.promise.any", ...PromiseAnyDependencies],
```
Comment (zloirock) [inline packages/babel-preset-env/src/polyfills/corejs3/built-in-definitions.js]: I think that it would be better just add `esnext.aggregate-error` to this line since at this moment it's used only here and I have no ideas where`PromiseAnyDependencies` can be used in the future.

Comment (JLHwung) [reply packages/babel-preset-env/src/polyfills/corejs3/built-in-definitions.js]: Can do. I thought it was some unwritten code convention that almost every entry is written as `[name, ...depedencies]`.
