### PR TITLE
fix: improve static canFollowModifier checks

### LINKED ISSUE #16759: [Bug]: Wrong ASI in class fields when TS plugin is enabled
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
class A {
  static
  foo = 2
}
```

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

When the `typescript` plugin is enabled we parse that class as having a field named `static` and one named `foo`. When it's not enabled, we parse it as a class having a static field named `foo`.

The second behavior is correct, and enabling the TS plugin should not change it.

### Environment

Babel 7.25.0

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #16759 
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

In this PR we also fixed the following case:
```ts
interface Foo {
  get
  foo(): string;
  set
  bar(v);
}
```
Previously Babel parsed it as two property and two method signatures, however, it diverts from the TS4.3+ behaviour.

### CODE REVIEW

File: packages/babel-parser/src/plugins/typescript/index.ts [hunk 1]
```diff
@@ -282,23 +282,32 @@ export default (superClass: ClassWithMixin<typeof Parser, IJSXParserMixin>) =>
...
+        this.isLiteralPropertyName()
       );
     }
 
+    tsNextTokenOnSameLineAndCanFollowModifier() {
+      this.next();
+      if (this.hasPrecedingLineBreak()) {
+        return false;
+      }
+      return this.tsTokenCanFollowModifier();
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/src/plugins/typescript/index.ts:299]: This refactor can be done separately from this PR, but given the deleted comment, we could:
- use `hasFollowingLineBreak` instead of `hasPrecedingLineBreak`
- use `lookaheadCharCode` instead of `tsTokenCanFollowModifier`
- do not use `tsTryParse` to call `tsNextTokenCanFollowModifier`

File: packages/babel-parser/test/fixtures/typescript/class/static-asi/input.ts [hunk 2]
```diff
@@ -0,0 +1,22 @@
+class A {
+    static
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/test/fixtures/typescript/class/static-asi/input.ts:2]: Can you add a test for `static` followed by a modifier and then ASI?
```js
class A {
  static readonly
  foo
}
```
should be a static field called `readonly` and an instance field called `foo`

**Review by nicolo-ribaudo — APPROVED** [review]

**Review by liuxingbaoyu — APPROVED** [review]
