### PR TITLE
Specify runtime exports

### LINKED ISSUE #8462: ESM runtime helper files should have the .mjs extension
#### Config

```js
{
  presets: [
    [
      '@babel/env',
      {
        targets: {
          node: '6.10',
          browsers: '>1%'
        },
        modules: false,
        shippedProposals: true,
        loose: true
      }
    ]
  ],
  plugins: [
    ['@babel/transform-runtime', { useESModules: true }]
  ]
}
```

#### Input code

```js
import React from 'react'

class Demo extends React.Component {}
```

Outputs:

```js
import _inheritsLoose from '@babel/runtime/helpers/esm/inheritsLoose'
import React from 'react'

var Demo = (function(_React$Component) {
  _inheritsLoose(Demo, _React$Component)

  function Demo() {
    return _React$Component.apply(this, arguments) || this
  }

  return Demo
})(React.Component)
```

When run as native ESM in Node.js with `--experimental-modules` enabled:

```
node --experimental-modules lib/demo.mjs
```

`@babel/runtime/helpers/esm/inheritsLoose` resolves to `node_modules/@babel/runtime/helpers/esm/inheritsLoose.js`. Because Node.js can only run native ESM in files with the `.mjs` extension, this results in a runtime error:

```
$ node --experimental-modules lib/demo.mjs
(node:97782) ExperimentalWarning: The ESM module loader is experimental.
/Users/jaydenseric/Sites/demo/node_modules/@babel/runtime/helpers/esm/inheritsLoose.js:1
(function (exports, require, module, __filename, __dirname) { export default function _inheritsLoose(subClass, superClass) {
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Proxy.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at createDynamicModule (internal/modules/esm/translators.js:56:15)
    at setExecutor (internal/modules/esm/create_dynamic_module.js:50:23)
```

### Expected behavior/code

The ESM helper import should resolve a helper file with a `.mjs` extension.

### Environment
- Babel version(s): v7.0.0-rc.1
- Node/npm version: Node.js v10.8.0 / npm v6.3.0
- OS: macOS v10.13.6
- Monorepo: No
- How you are using Babel: CLI

### Possible Solution

Allow Babel helpers to be consumed in native CJS or ESM Node.js environments by publishing sibling `.js` (CJS) and `.mjs` (ESM) files. They should be imported using the same path so the Node.js import resolution algorithm will select the appropriate file for the environment:

```diff
- import _inheritsLoose from '@babel/runtime/helpers/esm/inheritsLoose'
+ import _inheritsLoose from '@babel/runtime/helpers/inheritsLoose'
```

Webpack and other tools have adopted the same resolution algorithm; Webpack actually prefers `.mjs` files for ESM.

### Additional context/Screenshots

I would like to be able to generate an ESM build, that imports ESM helpers, that can run as native ESM in Node.js with `--experimental-modules` enabled.

### LINKED ISSUE #10548: Generated code by preset-env causes error on Node.js v12 and ES Modules
## Bug Report

**Current Behavior**
```bash
$ node --experimental-modules dist/example.mjs
(node:5693) ExperimentalWarning: The ESM module loader is experimental.
internal/modules/esm/default_resolve.js:79
  let url = moduleWrapResolve(specifier, parentURL);
            ^

Error: Cannot find module /path/to/example/node_modules/core-js/modules/es.array.iterator imported from /path/to/example/dist/example.mjs
    at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:79:13)
    at Loader.resolve (internal/modules/esm/loader.js:73:33)
    at Loader.getModuleJob (internal/modules/esm/loader.js:152:40)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:43:40)
    at link (internal/modules/esm/module_job.js:42:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

**Input Code**

`src/example.mjs` (source code)

```javascript
for (const x of [1, 2, 3]) {
  console.log(x);
}
```

`dist/example.mjs` (generated code)

```javascript
import "core-js/modules/es.array.iterator";

for (const x of [1, 2, 3]) {
  console.log(x);
}
```

**Expected behavior/code**
```bash
node --experimental-modules dist/example.mjs
(node:5717) ExperimentalWarning: The ESM module loader is experimental.
1
2
3
```

**Babel Configuration (.babelrc, package.json, cli command)**

```json
[
  "@babel/preset-env",
  {
    "targets": {
      "node": "8.5.0"
    },
    "useBuiltIns": "usage",
    "corejs": 3,
    "modules": false
  }
]
```

**Environment**
- Babel version(s): 7.6.4
- Node/npm version: Node v12.11.1/npm 6.11.3
- OS: Ubuntu 18.04
- Monorepo: no
- How you are using Babel: cli

**Possible Solution**
Could you add `.js` extension when importing polyfill?

```javascript
import "core-js/modules/es.array.iterator.js"; // needs ".js"

for (const x of [1, 2, 3]) {
  console.log(x);
}
```

Now, it will work properly!

```bash
$ node --experimental-modules dist/example.mjs
(node:5705) ExperimentalWarning: The ESM module loader is experimental.
1
2
3
```

**Additional context/Screenshots**
As of Node.js v12, [extension requires on `import` syntax](https://medium.com/@nodejs/announcing-a-new-experimental-modules-1be8d2d6c2ff).

### LINKED ISSUE #12003: Invalid Import Path for core-js Imports When Using type: module
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**
A clear and concise description of the behavior.

- [REPL](babeljs.io/repl), [Codesandbox](https://codesandbox.io/s/babel-repl-custom-plugin-7s08o?file=/src/index.js), or GitHub Repo helps!

When I use `@babel/preset-env` with the `useBuiltIns` option, the `core-js` imports still output without the `.js`. This is usually fine, except when running in a node environment that supports built-in modules, e.g. with `type: module` in the package.json or outputting to a file with the `.mjs` extension.

This happens even if I use `--out-file-extension .mjs`.

`--out-file-extension .cjs` works, if you don't use `modules: false`, but then you're not outputting modules.

**Input Code**

`test.js`
```js
const greeting = new Set(['Hello', 'world!']);
console.log(Array.from(greeting).join(' '));
```

```bash
npx babel test.js -d test/
node test/test.js
```

Output:
```
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '<repo>/node_modules/core-js/modules/esnext.set.add-all' imported from <repo>/test/test.js
Did you mean to import core-js/modules/esnext.set.add-all.js?
    at finalizeResolution (internal/modules/esm/resolve.js:275:11)
    at packageResolve (internal/modules/esm/resolve.js:668:12)
    at moduleResolve (internal/modules/esm/resolve.js:716:14)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:809:11)
    at Loader.resolve (internal/modules/esm/loader.js:85:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:229:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:51:40)
    at link (internal/modules/esm/module_job.js:50:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

**Expected behavior**
A clear and concise description of what you expected to happen (or code).

No errors

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
const presets = [['@babel/preset-env', {
  targets: {node: true},
  modules: false,
  useBuiltIns: 'usage',
  corejs: {version: 3, proposals: true},
}]];

export default {presets};
```

**Environment**

```
System:
  OS: android
Binaries:
  Node: 14.8.0 - /data/data/com.termux/files/usr/bin/node
  npm: 6.14.7 - /data/data/com.termux/files/usr/bin/npm
npmPackages:
  @babel/cli: ^7.10.5 => 7.10.5
  @babel/core: ^7.11.4 => 7.11.4
  @babel/preset-env: ^7.11.0 => 7.11.0
```

**Possible Solution**

One possible solution would be to always output with the extension. This would create longer output, but it would be future-proof and wouldn't require the user to do anything.

The best solution would probably be to guess whether the extension is needed, based on whether the package.json has `type: module`, and have a configuration option like `addExtension` or `addCorejsExtension` to force it one way or the other.

The last option I can think of is to always output `.cjs`, or add a configuration like `changeExtension`. `.mjs` would output to a `.mjs` file AND add the `corejs` path extensions. `.cjs` would output to `.cjs` and wouldn't add the extensions. `.js`, the default, would output to `.js` and possibly guess or use the `addCorejsExtension` option. I notice there is a `--out-file-extension` option for `@babel/cli`: having this keep the `corejs` extensions when you use `.mjs` would be fine, too.

**Additional context**
Add any other context about the problem here. Or a screenshot if applicable

### LINKED ISSUE #12058: Webpack5 ESM strict mode
## Bug Report

Webpack5 `beta.30` has enabled strict mode on the ESM modules imports https://github.com/webpack/webpack/releases/tag/v5.0.0-beta.30

https://github.com/webpack/webpack/issues/11467 has noted people with code problems, however `@babel/runtime` appears to have code that doesn't follow the strict `"type": "module"` requirements, as expected for node / webpack.

`.\node_modules\@babel\runtime\helpers\esm\package.json` has `"type": "module"` being set and libraries that depend on `@babel/runtime` with ESM modules are broken as a result.

I expect the code generator should be outputting with the file extensions to satisfy the requirements of ESM modules

https://nodejs.org/api/esm.html#esm_differences_between_es_modules_and_commonjs

**Current behavior**

@babel/runtime/helpers/esm/*.js contains extensionless imports for dependencies.

**Expected behavior**

@babel/runtime/helpers/esm/*.js to contain fully specified extensions for imports

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

N/A - this is npm published module

**Environment**

```
  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\s\SwiftFox\node_modules\.bin\npm.CMD
  Monorepos:
    Yarn Workspaces: 1.22.5
  npmPackages:
    @babel/core: 7.11.4 => 7.11.4
    babel-loader: 8.1.0 => 8.1.0
    eslint: 7.7.0 => 7.7.0
    webpack: 5.0.0-beta.30 => 5.0.0-beta.30
```

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #10548, fixes #8462, fixes #12003, fixes #12058 
| License                  | MIT

## Solved issues
This PR add helper/esm exports to `@babel/runtime(-corejs[23])?`. Importing esm modular helpers are now broken on Babel 7.7.6 and Node.js 13.2
```js
import "@babel/runtime/helpers/esm/applyDecoratedDescriptor"

// Error: Package exports for /path/to/babel/node_modules/@babel/runtime/package.json
// do not define a './helpers/esm/applyDecoratedDescriptor' subpath,
// imported from /path/to/code/babel/test.mjs

import "@babel/runtime/helpers/esm/applyDecoratedDescriptor.js"

// Error: Package exports for /path/to/babel/babel/node_modules/@babel/runtime/package.json
// do not define a './helpers/esm/applyDecoratedDescriptor.js' subpath,
// imported from /path/to/babel/test.mjs
```

This PR adds such missing exports so both
```js
import "@babel/runtime/helpers/esm/applyDecoratedDescriptor"
// and
import "@babel/runtime/helpers/esm/applyDecoratedDescriptor.js"
```
should work.

## Changes to `@babel/runtime`

Take `@babel/runtime-corejs3` as an example:

[7.11.2](https://unpkg.com/browse/@babel/runtime-corejs3@7.11.2/helpers/esm/arrayWithoutHoles.js)
```js
import _Array$isArray from "../../core-js/array/is-array";
import arrayLikeToArray from "./arrayLikeToArray";
export default function _arrayWithoutHoles(arr) {
  if (_Array$isArray(arr)) return arrayLikeToArray(arr);
}
```

This PR
```
import _Array$isArray from "@babel/runtime-corejs3/core-js/array/is-array";
import arrayLikeToArray from "@babel/runtime-corejs3/helpers/esm/arrayLikeToArray";
export default function _arrayWithoutHoles(arr) {
  if (_Array$isArray(arr)) return arrayLikeToArray(arr);
}
```

The relative imports to core-js helpers are replaced by submodule imports `@babel/runtime-corejs3/core-js`. The relative imports to internal Babel helpers are also replaced by `@babel/runtime-corejs3/helpers/esm/arrayLikeToArray`.

This changes are also applied on non-esm helpers.

[7.11.2](https://unpkg.com/@babel/runtime-corejs3@7.11.2/helpers/arrayWithoutHoles.js)
```js
var _Array$isArray = require("../core-js/array/is-array");
var arrayLikeToArray = require("./arrayLikeToArray");
function _arrayWithoutHoles(arr) {
  if (_Array$isArray(arr)) return arrayLikeToArray(arr);
}
module.exports = _arrayWithoutHoles;
```

This PR
```js
var _Array$isArray = require("@babel/runtime-corejs3/core-js/array/is-array");
var arrayLikeToArray = require("@babel/runtime-corejs3/helpers/arrayLikeToArray");
function _arrayWithoutHoles(arr) {
  if (_Array$isArray(arr)) return arrayLikeToArray(arr);
}
module.exports = _arrayWithoutHoles;
```

Node.js ESM requires relative imports (e.g. `./arrayLikeToArray`) ending with specific extension `.js`. However, adding extension to import path will break people consuming `@babel/runtime` via AMD, because we removed file extension from the module specifier: https://github.com/babel/babel/blob/20fd450ab7855622674f56772879953b49c95f23/packages/babel-helper-module-transforms/src/get-module-name.js#L40. So we generated `define("@babel/runtime/arrayLikeToArray")` for `arrayLikeToArray.js` and thus `require("./arrayLikeToArray.js")` will throw for AMD users.

Since it is a breaking to change the `moduleName` behaviour. This PR does not add extension but adding more `exports` so it can work with both Node.js ESM and AMD.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/10853"></a>

### CODE REVIEW

File: packages/babel-plugin-transform-runtime/scripts/build-dist.js [hunk 1]
```diff
@@ -89,6 +89,21 @@ function writeCoreJS({
 function writeHelpers(runtimeName, { corejs } = {}) {
   writeHelperFiles(runtimeName, { corejs, esm: false });
   writeHelperFiles(runtimeName, { corejs, esm: true });
+  writeHelperExports(runtimeName);
+}
+
+function writeHelperExports(runtimeName) {
```
Comment (JLHwung) [inline packages/babel-plugin-transform-runtime/scripts/build-dist.js]: non-esm helpers should also be exported because `package.exports` prioritize over the cjs relative path loading logic, https://github.com/nodejs/node/blob/8a5c7f6abdfb4a8b09bd1de85c6e9819df66ca48/lib/internal/modules/cjs/loader.js#L526

File: packages/babel-plugin-transform-runtime/scripts/build-dist.js [hunk 2]
```diff
@@ -84,13 +84,44 @@ function writeCoreJS({
...
+  const pkgDirname = getRuntimeRoot(runtimeName);
+  const pkgJsonPath = require.resolve(`${pkgDirname}/package.json`);
+  const pkgJson = require(pkgJsonPath);
+  pkgJson.exports = {
+    "./": "./",
+    "./helpers/": "./helpers/",
+    "./helpers/esm/": "./helpers/esm/",
+    "./regenerator": "./regenerator/index.js",
+    "./regenerator/": "./regenerator/",
```
Comment (JLHwung) [inline packages/babel-plugin-transform-runtime/scripts/build-dist.js]: This exports is meant to support the following usage
```
require("@babel/runtime/regenerator/index")
// or
require("@babel/runtime/regenerator/index.js")
```
`@babel/transform-runtime` will generate `require("@babel/runtime/regenerator")`, we may remove this on 8.x

File: packages/babel-plugin-transform-runtime/scripts/build-dist.js [hunk 3]
```diff
@@ -84,13 +84,44 @@ function writeCoreJS({
...
   writeHelperFiles(runtimeName, { corejs, esm: true });
+  writeHelperExports(runtimeName);
 }
 
+function writeHelperExports(runtimeName) {
+  const pkgDirname = getRuntimeRoot(runtimeName);
+  const pkgJsonPath = require.resolve(`${pkgDirname}/package.json`);
+  const pkgJson = require(pkgJsonPath);
+  pkgJson.exports = {
+    "./": "./",
```
Comment (JLHwung) [inline packages/babel-plugin-transform-runtime/scripts/build-dist.js]: This exports is meant to support
```
const runtimeVersion = require("@babel/runtime/package.json").version;
```

**Comment by nicolo-ribaudo** [comment]
> No need to introduce removeImportsExtension option in 7.8.0

Don't we still need it for the `useBuiltIns` option anyway?

**Comment by JLHwung** [comment]
> Don't we still need it for the useBuiltIns option anyway?

Yes, I can propose upstream PR to core-js and regenerator.

**Comment by incorrupt** [comment]
What's the status on this PR?
Unless I missed something, as of today, it is not possible for Babel to transpile ES6 modules to be consumed natively by Node 13 and 14 when using plugin-transform-runtime.

#10549 was apparently fixing the issue but has been rolled back

File: packages/babel-runtime-corejs2/package.json [hunk 4]
```diff
@@ -18,5 +18,265 @@
...
+    "./helpers/esm/classStaticPrivateMethodGet": "./helpers/esm/classStaticPrivateMethodGet.js",
+    "./helpers/esm/classStaticPrivateMethodSet": "./helpers/esm/classStaticPrivateMethodSet.js",
+    "./helpers/esm/decorate": "./helpers/esm/decorate.js",
+    "./helpers/esm/classPrivateMethodGet": "./helpers/esm/classPrivateMethodGet.js",
+    "./helpers/esm/classPrivateMethodSet": "./helpers/esm/classPrivateMethodSet.js",
+    "./helpers/esm/wrapRegExp": "./helpers/esm/wrapRegExp.js",
+    "./package.json": "./package.json",
+    "./regenerator": "./regenerator/index.js",
+    "./regenerator/": "./regenerator/",
+    "./core-js/": "./core-js/",
```
Comment (JLHwung) [inline packages/babel-runtime-corejs2/package.json:187]: Note that the directory export map is _deep_: All files under `core-js` can be imported via `path/filename.ext`:
```js
import "@babel/runtime-corejs2/core-js/object/assign.js"
```

**Review by evilebottnawi — COMMENTED** [review]
Looks good, maybe it will be good idea to add couple of tests

File: packages/babel-runtime-corejs2/helpers/esm/toArray.js [hunk 5]
```diff
@@ -1,7 +1,7 @@
-import arrayWithHoles from "./arrayWithHoles";
```
Comment (JLHwung) [inline packages/babel-runtime-corejs2/helpers/esm/toArray.js:1]: Interesting, some corejs 2 helper files are tracked in git repository. Yet it is convenient so you can review the actual change of helper imports.

/cc @rwjblue Will ember support self referencing package? In this case `@babel/runtime-corejs2` is referencing itself. The import path extension `.js` is not added so this part should work with amd.

File: test/esm/babel-runtime-corejs3.mjs [hunk 6]
```diff
@@ -0,0 +1,69 @@
+import assert from "assert";
+
+export default {
```
Comment (JLHwung) [inline test/esm/babel-runtime-corejs3.mjs:3]: I wrote the testcases in such a way that hopefully we can use a codemod to convert the testcases to Jest BDD test styles, after Jest supports esm.

File: test/esm/package.json [hunk 7]
```diff
@@ -0,0 +1,11 @@
+{
+  "name": "@babel/test-esm",
```
Comment (JLHwung) [inline test/esm/package.json:2]: This package is not visible to lerna. It is handled by yarn so we can import `@babel/runtime` from the workspace.

File: packages/babel-runtime-corejs2/helpers/esm/iterableToArray.js [hunk 8]
```diff
@@ -1,6 +1,6 @@
-import _Array$from from "../../core-js/array/from";
-import _isIterable from "../../core-js/is-iterable";
-import _Symbol from "../../core-js/symbol";
+import _Array$from from "@babel/runtime-corejs2/core-js/array/from";
+import _isIterable from "@babel/runtime-corejs2/core-js/is-iterable";
+import _Symbol from "@babel/runtime-corejs2/core-js/symbol";
```
Comment (nicolo-ribaudo) [inline packages/babel-runtime-corejs2/helpers/esm/iterableToArray.js:3]: For users using PnP, is it allowed for a package to import itself?

File: packages/babel-runtime-corejs2/helpers/esm/toArray.js (hunk 5 above)
Comment (nicolo-ribaudo) [reply packages/babel-runtime-corejs2/helpers/esm/toArray.js:1]: > Yet it is convenient so you can review the actual change of helper imports.

That's exactly why we don't ignore some of these files :stuck_out_tongue:

**Review by nicolo-ribaudo — APPROVED** [review]
This looks good!

File: packages/babel-runtime-corejs2/helpers/esm/iterableToArray.js (hunk 8 above)
Comment (JLHwung) [reply packages/babel-runtime-corejs2/helpers/esm/iterableToArray.js:3]: Yarn PnP does not support esm yet: https://github.com/yarnpkg/berry/issues/638

@merceyz Does PnP support `require("package/itself")`?

Comment (merceyz) [reply packages/babel-runtime-corejs2/helpers/esm/iterableToArray.js:3]: Yes, that's totally fine

**Review by kaicataldo — APPROVED** [review]
