### PR TITLE
fix: wrap anonymous class expression within statement

### LINKED ISSUE #15112: [Bug]: Babel throws when a decorated class expression contains a static block
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
const dec = () => {};
0, @dec class { static {} }
```

[REPL](https://babel.dev/repl#?browsers=defaults&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=MYewdgzgLgBAJgU2DAvDAFASlQPhgbwF8BuAKAAYAaGAAUWWABsBDCCAmaZqAS2SJiEgA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=stage-2&prettier=false&targets=&version=7.20.1&externalPlugins=&assumptions=%7B%7D)

### Configuration file name

_No response_

### Configuration

```json
{
  "plugins": [["@babel/proposal-decorators", { "version": "2022-03" }]]
}
```

Both the `2022-03` and `2021-12` version are affected. The legacy transform does not throw.

### Current and expected behavior

Current: Babel throws "cannot turn ClassExpression to a statement".

Expected: It should be transformed or if not, provide a better error message.

### Environment

REPL

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #15112 
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

Babel currently throws at decorated anonymous class expression, e.g. `@dec class { static {} }` because we invoked `t.toStatement`. Here we wrap the class expression within an expression statement so that it can be fit in the static block that we used for class decorators.

Before develop this issue I realize that Babel doesn't support the named evaluation for decorated class expression, for example

```js
const dec = (value, context) => {
  context.name; // <-- should be "A", currently "_class"
  return value;
};

let A;
A = @dec class {}
```

TypeScript injects `__setFunctionName` helper call before applying the decorator transform to ensure that `context.name` is always correct (https://github.com/microsoft/TypeScript/pull/50820#discussion_r1009828932). I will address this issue in a separate PR.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15113"></a>

### CODE REVIEW

File: packages/babel-plugin-proposal-decorators/src/transformer-2022-03.ts [hunk 1]
```diff
@@ -937,7 +937,12 @@ function transformClass(
         class extends ${state.addHelper("identity")} {}
       ` as t.ClassExpression;
       staticsClass.body.body = [
-        t.staticBlock([t.toStatement(path.node, false)]),
+        t.staticBlock([
+          t.toStatement(originalClass, true) ||
+            // If toStatement returns false, originalClass must be an anonymous ClassExpression,
+            // because `export default @dec ...` has been handled in the export visitor before.
+            t.expressionStatement(originalClass as t.ClassExpression),
+        ]),
```
Comment (liuxingbaoyu) [inline packages/babel-plugin-proposal-decorators/src/transformer-2022-03.ts:945]: Would it be better to fix in `t.toStatement`?

Also unrelated to this PR, the type definition of `t.toStatement` doesn't seem quite right.

Comment (JLHwung) [reply packages/babel-plugin-proposal-decorators/src/transformer-2022-03.ts:945]: > Would it be better to fix in t.toStatement?

I don't know much context here but it seems that we intentionally fail `toStatement` for anonymous class expression

https://github.com/babel/babel/blob/53185ea275b0a278ac4aafe5841f2a332cabff31/packages/babel-types/test/converters.js#L131-L138

/cc @nicolo-ribaudo if you can shred some light here.

If we decided to overturn this behaviour, we still need the patch here until Babel 8 because the plugin does not depend on `@babel/types`.

Comment (liuxingbaoyu) [reply packages/babel-plugin-proposal-decorators/src/transformer-2022-03.ts:945]: https://github.com/liuxingbaoyu/babel/commit/98ca541fde0c1ec9f2b5e5222e0adf08740cb540

Good find, now I think it's fine.

File: packages/babel-plugin-proposal-object-rest-spread/src/index.ts [hunk 2]
```diff
@@ -531,7 +531,7 @@ export default declare((api, opts: Options) => {
           nodeWithoutSpread.right = t.identifier(refName);
           nodes.push(t.expressionStatement(nodeWithoutSpread));
           nodes.push(
-            t.toStatement(
+            t.expressionStatement(
```
Comment (JLHwung) [inline packages/babel-plugin-proposal-object-rest-spread/src/index.ts:534]: `toStatement` wraps assignment expression within expression statement.

File: packages/babel-plugin-proposal-decorators/src/transformer-2022-03.ts (hunk 1 above)
Comment (nicolo-ribaudo) [reply packages/babel-plugin-proposal-decorators/src/transformer-2022-03.ts:945]: I believe the reason is that `t.toStatement` of a `ClassExpression` should return a `ClassDeclaration`, but converting a class expression without an ID is generally not safe.

**Review by nicolo-ribaudo — APPROVED** [review]
