### PR TITLE
fix: `@babel/node` repl and enable `no-use-before-define` rule

### LINKED ISSUE #15123: [Bug]: @babel/node 7.20.0
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/register or @babel/node

### Input code

```
npm exec babel-node
```

### Configuration file name

_No response_

### Configuration

```
module.exports = {
  'presets': [
    ['@babel/preset-env', {
      'targets': {
        'node': true
      }
    }]
  ],
  'plugins': [
    '@babel/plugin-proposal-class-properties',
    '@babel/plugin-transform-runtime',
    'add-module-exports'
  ]
};
```

### Current and expected behavior

Current:
```
WORKDIR/node_modules/.pnpm/@babel+node@7.20.0_@babel+core@7.19.6/node_modules/@babel/node/lib/_babel-node.js:222
    eval: replEval,
          ^

ReferenceError: Cannot access 'replEval' before initialization
    at replStart (WORKDIR/node_modules/.pnpm/@babel+node@7.20.0_@babel+core@7.19.6/node_modules/@babel/node/lib/_babel-node.js:222:11)
    at Object.<anonymous> (WORKDIR/node_modules/.pnpm/@babel+node@7.20.0_@babel+core@7.19.6/node_modules/@babel/node/lib/_babel-node.js:179:5)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.12.0
```

### Environment

- "@babel/core": "^7.19.6"
- node v18.12
- "@babel/node": "^7.20.0"
- pnpm or yarn, last version

### Possible solution

Replace const replEval by function:

```
function replEval (code, context, filename, callback) {
  let err;
  let result;

  try {
    if (code[0] === "(" && code[code.length - 1] === ")") {
      code = code.slice(1, -1);
    }

    result = _eval(code, filename);
  } catch (e) {
    err = e;
  }

  callback(err, result);
};

function replStart() {
  const replServer = _repl.start({
    prompt: "babel > ",
    input: process.stdin,
    output: process.stdout,
    eval: replEval,
    useGlobal: true,
    preview: true
  });

  const NODE_REPL_HISTORY = process.env.NODE_REPL_HISTORY;
  {
    replServer.setupHistory == null ? void 0 : replServer.setupHistory(NODE_REPL_HISTORY, () => {});
  }
}
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #15123 
| Patch: Bug Fix?          | √
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | No but enabled eslint rule
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15124"></a>

### CODE REVIEW

File: packages/babel-node/src/_babel-node.ts [hunk 1]
```diff
@@ -227,8 +226,13 @@ function requireArgs() {
...
 }
-
-const replEval: REPLEval = function (code, context, filename, callback) {
+function replEval(
+  this: repl.REPLServer,
+  code: string,
+  context: vm.Context,
+  filename: string,
+  callback: (err: Error | null, result: any) => void,
+) {
```
Comment (JLHwung) [inline packages/babel-node/src/_babel-node.ts:235]: For reviewers: this is the real fix, while the others are lint changes.

**Review by JLHwung — APPROVED** [review]

**Review by nicolo-ribaudo — APPROVED** [review]
