### PR TITLE
Fix es6.string.iterator mapping in babel-preset-env

### LINKED ISSUE #8691: babel/preset-env useBuiltIns: "entry" does not include "es6.string.iterator" for ie11
## Bug Report

**Current Behavior**
When using the useBuiltIns: "entry" options while targeting ie11, the "es6.string.iterator" builtin is not included in the generated imports, even though ie11 does not support it.

**Input Code**
- REPL or Repo link if applicable:

```js
const babel = require('@babel/core')
const preset = require('@babel/preset-env')

let {code} = babel.transformSync(`
  import '@babel/polyfill'

  for (let c of 'abcdefg') {
    console.log(c)
  }
`.trim(), {
    presets: [[preset, {
        targets: [
            "ie 11"
        ],
        useBuiltIns: "entry",
        // include: ["es6.string.iterator"], // include this and the result will work on ie11
        modules: false,
        debug: true
    }]]
})

console.log(code)
```

**Expected behavior/code**
`import "core-js/modules/es6.string.iterator";` should appear in the output.

**Environment**
- Babel version(s): v7.0.0
- Node/npm version: Node 8.11.3/npm 5.10
- OS: OSX 10.13.6
- How you are using Babel: loader

**Additional context/Screenshots**
Looking at babel/packages/babel-preset-env/data/built-ins.json, it seems that preset-env assumes a lot of old browsers fully support `String.prototype[@@iterator]()` even though [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/@@iterator#Browser_compatibility) says otherwise. Also, I personally tried running the generated code in ie11 and get the error: 

> Object doesn't support property or method 'Symbol(Symbol.iterator)

But when I include the `include: ["es6.string.iterator"]` option the result runs fine.

### PR DESCRIPTION
**Pull request by existentialism**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #8691 
| Patch: Bug Fix?          | Y
| Major: Breaking Change?  | N
| Minor: New Feature?      | N
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

File: packages/babel-preset-env/data/built-in-features.js [hunk 1]
```diff
@@ -277,7 +277,7 @@ const es = {
   "es6.string.from-code-point": "String static methods / String.fromCodePoint",
   "es6.string.includes": "String.prototype methods / String.prototype.includes",
   "es6.string.italics": "String.prototype HTML methods",
-  "es6.string.iterator": "String properties and methods / Property access on strings",
+  "es6.string.iterator": "String.prototype methods / String.prototype[Symbol.iterator]",
```
Comment (nicolo-ribaudo) [inline packages/babel-preset-env/data/built-in-features.js]: (I hate these human-readable features name)
