### PR TITLE
Parse `using[foo]` as computed member expression

### LINKED ISSUE #15221: [Bug]: Babel throws on computed property access `using[x]`
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
var using = [];
using[0];
```

[REPL](https://babel.dev/repl#?browsers=&build=&builtIns=false&corejs=3.21&spec=false&loose=true&code_lz=G4QwTgBArgzglgOwOYQLwQNoF0DcAoWRJDABlyA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ctypescript&prettier=false&targets=&version=7.20.4&externalPlugins=&assumptions=%7B%7D)

### Configuration file name

_No response_

### Configuration

REPL

### Current and expected behavior

Current: Babel throws "Support for the experimental syntax 'explicitResourceManagement' isn't currently enabled (2:1)"

Expected: Babel parses it successfully.

### Environment

REPL

### Possible solution

_No response_

### Additional context

This is a regression introduced in https://github.com/babel/babel/pull/14968.

The bug is already covered in the test case

https://github.com/babel/babel/blob/e7405b99695b4b499a7a9494e4b5ecb1adc2e445/packages/babel-parser/test/fixtures/experimental/explicit-resource-management/invalid-using-binding-pattern/input.js#L3

but the behaviour is not correct since it is already valid JS.

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #15221 
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

This PR fixes a regression introduced in https://github.com/babel/babel/pull/14968. 

The `using` declaration forbids binding pattern. Previously we tried to recover from `using [`. However, unlike `let [`, `using [foo]` is already a valid expression statement (computed member expression). In this PR we only check if a name token is following `using`.

I suggest reviewing this PR by commits. First we refactor the interface of `parseStatement` and `parseFunction`, then we create a separate branch for the `using` handling. The `hasFollowingIdentifier` method is now split into `hasFollowingBindingAtom` (for `let`) and `hasFollowingBindingIdentifier` (for `using`) so that we can implement the check without extra lookahead.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15225"></a>

### CODE REVIEW

File: packages/babel-parser/src/parser/statement.ts [hunk 1]
```diff
@@ -1139,13 +1223,11 @@ export default abstract class StatementParser extends ExpressionParser {
       kind: kind,
       statementStart: this.state.start,
     });
-    node.body = this.parseStatement(
-      context
-        ? context.indexOf("label") === -1
-          ? context + "label"
-          : context
-        : "label",
```
Comment (JLHwung) [inline packages/babel-parser/src/parser/statement.ts:1147]: The `context` variable is now replaced by an option bag `ParseStatementFlag`. Personally I was constantly confused by the dynamic `context` string, which seems to be an overkill as we are not using that string for error reports.

File: packages/babel-parser/test/fixtures/es2017/async-functions/invalid-generator-inside-loop/output.json [hunk 2]
```diff
@@ -0,0 +1,47 @@
+{
+  "type": "File",
+  "start":0,"end":33,"loc":{"start":{"line":1,"column":0,"index":0},"end":{"line":1,"column":33,"index":33}},
+  "errors": [
+    "SyntaxError: Async functions can only be declared at the top level or inside a block. (1:10)"
```
Comment (JLHwung) [inline packages/babel-parser/test/fixtures/es2017/async-functions/invalid-generator-inside-loop/output.json:5]: Currently Babel reports two errors, the first one is as above and the second one is from the generator *. Here we only report the first error.

File: packages/babel-parser/test/fixtures/es2015/let/let-with-linebreak-and-escaped/input.js [hunk 3]
```diff
@@ -0,0 +1,2 @@
+while (0) let
+\u0061 = 1;
```
Comment (JLHwung) [inline packages/babel-parser/test/fixtures/es2015/let/let-with-linebreak-and-escaped/input.js:2]: Currently Babel parses it as a `WhileStatement` including `let` variable declaration. This is incorrect as it should share the AST structure with
```js
while (0) let
a = 1;
```
which consists of a WhileStatement and an ExpressionStatement.

File: packages/babel-parser/test/fixtures/es2015/statements/label-invalid-let/output.json [hunk 4]
```diff
@@ -2,7 +2,7 @@
   "type": "File",
   "start":0,"end":13,"loc":{"start":{"line":1,"column":0,"index":0},"end":{"line":1,"column":13,"index":13}},
   "errors": [
-    "SyntaxError: Missing semicolon. (1:8)"
+    "SyntaxError: Lexical declaration cannot appear in a single-statement context. (1:5)"
```
Comment (JLHwung) [inline packages/babel-parser/test/fixtures/es2015/statements/label-invalid-let/output.json:5]: The input is
```js
foo: let bar;
```

Now we throw a better error here.

Comment (liuxingbaoyu) [reply packages/babel-parser/test/fixtures/es2015/statements/label-invalid-let/output.json:5]: Yes, this improves the parsed AST result at the same time.

**Review by liuxingbaoyu — APPROVED** [review]
Good work!

File: packages/babel-parser/src/parser/statement.ts [hunk 5]
```diff
@@ -464,14 +463,33 @@ export default abstract class StatementParser extends ExpressionParser {
...
+        if (!allowDeclaration) {
+          this.raise(Errors.UnexpectedLexicalDeclaration, {
+            at: this.state.startLoc,
+          });
+        }
+        if (!this.scope.inModule && this.scope.inTopLevel) {
+          this.raise(Errors.UnexpectedUsingDeclaration, {
+            at: this.state.startLoc,
+          });
+        }
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/src/parser/statement.ts:505]: Will this report a double error when parsing `label: using x = y` as a script?

**Review by nicolo-ribaudo — APPROVED** [review]
Can you also add a test for `using %%x%% = y` with placeholders enabled?

File: packages/babel-parser/test/fixtures/experimental/explicit-resource-management/invalid-using-binding-pattern-declaration/options.json [hunk 6]
```diff
@@ -0,0 +1,3 @@
+{
+  "throws": "Unexpected token (2:16)"
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/test/fixtures/experimental/explicit-resource-management/invalid-using-binding-pattern-declaration/options.json:2]: Could we continue parsing `using [no LineTerminator here] {` with the old logic, to provide the good error message, and only use the new logic for `using [`?

Comment (JLHwung) [reply packages/babel-parser/test/fixtures/experimental/explicit-resource-management/invalid-using-binding-pattern-declaration/options.json:2]: `using { x } = 1` would be a valid lhs assignment under [the extractors proposal](https://github.com/tc39/proposal-extractors). In the future if we implement that proposal, it will throw the missing plugin error. So I removed the recoverable error here.

File: packages/babel-parser/src/parser/statement.ts (hunk 5 above)
Comment (JLHwung) [reply packages/babel-parser/src/parser/statement.ts:505]: Good catch! In this case I lean to the `UnexpectedUsingDeclaration` because it's more specific than the other.

**Review by nicolo-ribaudo — APPROVED** [review]
