### PR TITLE
Use `NodePath#hub` as part of the paths cache key

### LINKED ISSUE #6437: Figure out an approach to NodePath 'hub' object tracking with better cache behavior
I recently realized we've got bug with our invalidation logic for NodePath that can cause some real weirdness. Here it is [on ASTExplorer](http://astexplorer.net/#/gist/232f9956e84a89d90fd02b013071778a/797e7d58601ed6327610784494f19bb18197a9f5) and here:

```
var mem = template("property.access")();

traverse(mem, {noScope: true});

var p2 = path.insertAfter(mem)[0];

console.log(p2.get("expression").hub);
```
will print `undefined` for `hub` even through `p2.hub` is the `Hub` class instance. 

Which is surprising because in https://github.com/babel/babel/blob/d511cfc0e287d3d33292d7f7afa035c37e51b980/packages/babel-traverse/src/path/index.js#L74, the `hub` value is explicitly supposed to pass down.

It fails in this case because on https://github.com/babel/babel/blob/d511cfc0e287d3d33292d7f7afa035c37e51b980/packages/babel-traverse/src/path/index.js#L91 if a value is found in the cache, we never bother bailing out.

The problem is, what do we do. Two options come to mind:
1. Overwrite the `.hub` on the cache result.
2. Only accept items from the cache if the hub is correct.

#### Option 1

Pretty  gross because we could just as easily be introducing another bug by removing a Hub instance that was supposed to be there

#### Option 2
Sounds reasonable, until you realize that we actually _crucially_ rely on this gross caching behavior to instantiate `NodePath` with the correct `Hub` instance in the first place.

In `File` init in https://github.com/babel/babel/blob/d511cfc0e287d3d33292d7f7afa035c37e51b980/packages/babel-core/src/transformation/file/file.js#L42 we create the root `NodePath`, but then we never really do anything with it. Traversal begins on https://github.com/babel/babel/blob/d511cfc0e287d3d33292d7f7afa035c37e51b980/packages/babel-core/src/transformation/index.js#L71, which never explicitly mentions `this.path` at all. That path ends up being used, thus using the root `Hub`, because it is present in the cache. If we explicitly test for the `Hub` in the cache, we'll break this weird cache-based pass-through logic.

#### Solution?

To me, the "feature" we're breaking in option 2 is totally a mistake to rely on since it is essentially relying on sideeffects to the extreme. This means we need a way to do two things:

1. Initialize the NodePath up front, so it can be stored on the `File` class instance
2. Perform a traversal using this NodePath, while ensuring that same traversal logic we have now is preserved.

The exact details on how we do those two things is up in the air, but feels like something we should figure out ASAP.

Incidentally, this same bug is the reason we have to do https://github.com/babel/babel/blob/d511cfc0e287d3d33292d7f7afa035c37e51b980/packages/babel-template/src/index.js#L218 to explicitly clear the cache, otherwise every node we get pack from `babel-template` would trigger this bug, due to the internal traversal, which doesn't have a `hub`, polluting the cache.

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #6437
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

This fixes https://github.com/babel/babel/issues/6437, implementing option 2. I solved the problem of "we call `traverse` with no hub" by adding support for traversing a node visiting also the top-level node itself, so that we can directly traverse the `Program` NodePath that already has the hub.

We might want to, at some point, expose that top-level traversal as an official API, such as `NodePath#traverseSelf`, but I'm intentionally keeping it under the radar now (even if technically the new capability is accessible from the third-party code).

I don't know if this fixes or not #12570, because it looks like that issue has already been fixed on `main`?

cc @robhogan this fixes the underlying issue of https://github.com/facebook/metro/pull/906

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15725"></a>

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
I'm very confused by the "old Babel" e2e failure. That test is using `@babel/core` and `@babel/traverse` 7.0.0, so I do not see how this patch can affect it 🤔

**Review by JLHwung — APPROVED** [review]

**Review by liuxingbaoyu — APPROVED** [review]
Would it be better for us to use `||` instead of `??` in this PR?

File: packages/babel-traverse/src/path/modification.ts [hunk 1]
```diff
@@ -279,7 +279,7 @@ export function updateSiblingKeys(
 ) {
   if (!this.parent) return;
 
-  const paths = pathCache.get(this.parent);
+  const paths = getCachedPaths(this.hub, this.parent) ?? ([] as never[]);
```
Comment (nicolo-ribaudo) [inline packages/babel-traverse/src/path/modification.ts:282]: @liuxingbaoyu We already use `??` in many places -- I'll avoid it here since in this case the compiled output uses a temp variable. Although, I'm not too worried about these small differences in our compiled code, since it's usually not shipped to the browser.
```suggestion
  const paths = getCachedPaths(this.hub, this.parent) || ([] as never[]);
```

**Comment by Tofandel** [comment]
If anyone gets the error
```txt
Cannot read properties of undefined (reading 'addHelper')
    at Scope.toArray (@babel/traverse/lib/scope/index.js:464:36)
    at getSpreadLiteral (@babel/plugin-transform-spread/lib/index.js:21:20)
```
When building after upgrading babel

Make sure to switch from `@babel/plugin-proposal-object-rest-spread` to `@babel/plugin-transform-object-rest-spread`
