### PR TITLE
Redeclaring a variable counts as a modification

### LINKED ISSUE #6217: Variable redeclarations are not recognized as modifications
### Input Code
```js
var a = 1;
var a = 2;
var b = 1, b = 2;
```
### Babel Configuration (.babelrc, package.json, cli command)
Default.

### Expected Behavior
Babel recognizes that `a` and `b` are not constants.

### Current Behavior
Babel reports that `a` and `b` are constants.

### Possible Solution
In babel-traverse, `registerBinding` incorrectly assumes that each variable name of a declaration is a new name and does not exist yet in the bindings.

### Context
The incorrect constantness assumption breaks babel-minify (https://github.com/babel/minify/issues/685).

### Your Environment
All.

### PR DESCRIPTION
**Pull request by RubenVerborgh**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues             |  Fixes #6217.
| Patch: Bug Fix?          |  Yes.
| Major: Breaking Change?  |  No.
| Minor: New Feature?      |  No.
| Tests Added/Pass?        |  Yes.
| Spec Compliancy?         |  Yes.
| License                  | MIT
| Doc PR                   |  No.
| Any Dependency Changes?  |  No.

When a variable is redeclared (as in `var a = 1; var a = 2;`), this PR ensures that the second declaration is no longer regarded as a constant.

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
@jridgewell Woops, didn't find #5745 with issue search. Different keywords I guess.

**Comment by RubenVerborgh** [comment]
Actually, @jridgewell, could you have another look? The unit tests I added fail without my fix, and #5745 already made it to master.

**Comment by RubenVerborgh** [comment]
Indeed, you just concat but don't update.

I personally think the error is where I fixed it (incorrect assumption of a mapping key not existing yet), but I can migrate to the other fix.

**Comment by jridgewell** [comment]
We can revert #5745 with this. Either's fine.

File: packages/babel-traverse/src/scope/index.js [hunk 1]
```diff
@@ -535,13 +535,18 @@ export default class Scope {
...
 
-        this.bindings[name] = new Binding({
-          identifier: id,
-          existing: local,
-          scope: this,
-          path: bindingPath,
-          kind: kind,
-        });
+        // A redeclaration of an existing variable is a modification
+        if (name in this.bindings) {
```
Comment (jridgewell) [inline packages/babel-traverse/src/scope/index.js]: Use `#hasOwnBinding`, please.

**Comment by RubenVerborgh** [comment]
Same with me. Maybe consider reopening #6217 until this is fixed?

File: packages/babel-traverse/src/scope/index.js (hunk 1 above)
Comment (jridgewell) [reply packages/babel-traverse/src/scope/index.js]: Actually, just check `if (existing)`

**Comment by RubenVerborgh** [comment]
@jridgewell What should we do about this failure: /packages/babel-plugin-transform-es2015-parameters/test/fixtures/parameters/rest-member-expression-deoptimisation/expected.js? Is the new version correct or not?

File: packages/babel-traverse/src/scope/index.js (hunk 1 above)
Comment (RubenVerborgh) [reply packages/babel-traverse/src/scope/index.js]: `if(this.hasOwnBinding(name))` works; can't do second because no `existing` is in scope. How do I proceed?

Comment (jridgewell) [reply packages/babel-traverse/src/scope/index.js]: Sorry, it's `local`.

**Comment by jridgewell** [comment]
Just update the test, the new output is fine.

File: packages/babel-traverse/src/scope/index.js (hunk 1 above)
Comment (RubenVerborgh) [reply packages/babel-traverse/src/scope/index.js]: Check, works. Pushed new version.

**Comment by RubenVerborgh** [comment]
Made all the changes, tests pass. Now additionally removing unneeded code from #5745, keeping the tests.
