### PR TITLE
Throw a better error when transforming imported bindings in types

### LINKED ISSUE #13094: @babel/helper-module-transforms rewrites type annotations containing named imports incorrectly
## Bug Report

**Current behavior**

Type annotations containing named imports are incorrectly transformed to `MemberExpressions` and cause a validation error: `Property typeName of TSTypeReference expected node to be of a type ["TSEntityName"] but instead got "MemberExpression"`. See [Babel repl](https://babel.dev/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAbzgMQhOBfOAzKERwDkAdAPTZqEBQV2ArgHYDGMwEDcARgIZQAUFCAC4UaAJSJMVIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.13.14&externalPlugins=%40babel%2Fplugin-syntax-typescript%407.12.13%2C%40babel%2Fplugin-transform-modules-commonjs%407.13.8).

This seems to be due to [this line in `helper-module-transforms`](https://github.com/babel/babel/blob/main/packages/babel-helper-module-transforms/src/rewrite-live-references.ts#L239), which rewrites any `ReferencedIdentifier` to a `MemberExpression`; but type annotations may contain `Identifiers` and be matched by `ReferencedIdentifier`.

**Input Code**

```js
import { Foo } from './foo'

function bar(foo: Foo) { }
```

**Expected behavior**

Type annotations are transformed correctly, or (if this module is not intended to be used with type annotations) flagged with a clear error.

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #13094 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/13739"></a>

### CODE REVIEW

File: packages/babel-helper-module-transforms/src/rewrite-live-references.ts [hunk 1]
```diff
@@ -44,6 +44,24 @@ interface RewriteBindingInitVisitorState {
...
+    switch (path.parent.type) {
+      case "TSTypeAnnotation":
+      case "TSTypeAliasDeclaration":
+      case "TypeAnnotation":
+      case "TypeAlias":
+        return true;
+      case "ExportSpecifier":
+        return path.parentPath.parent.exportKind === "type";
+      default:
+        if (path.parentPath.isStatement() || path.parentPath.isExpression()) {
```
Comment (JLHwung) [inline packages/babel-helper-module-transforms/src/rewrite-live-references.ts:58]: We should not exit the loop when `path.parentPath` is of alias typescript or flow. For example,

```ts
import { A } from "x";

var x = {} as A.b[0]
```

File: packages/babel-helper-module-transforms/src/rewrite-live-references.ts [hunk 2]
```diff
@@ -224,6 +243,13 @@ const rewriteReferencesVisitor: Visitor<RewriteReferencesVisitorState> = {
 
     const importData = imported.get(localName);
     if (importData) {
+      if (isInType(path)) {
+        throw path.buildCodeFrameError(
+          `Cannot transform the imported ${localName} binding since it's used in a type annotation. ` +
```
Comment (hzoo) [inline packages/babel-helper-module-transforms/src/rewrite-live-references.ts:248]: maybe this?
```suggestion
          `Cannot transform the imported binding ${localName} since it's also used as a type annotation. ` +
```

File: packages/babel-helper-module-transforms/src/rewrite-live-references.ts [hunk 3]
```diff
@@ -44,6 +44,25 @@ interface RewriteBindingInitVisitorState {
...
 }
 
+function isInType(path) {
+  do {
+    switch (path.parent.type) {
+      case "TSTypeAnnotation":
+      case "TSTypeAliasDeclaration":
+      case "TSTypeReference":
+      case "TypeAnnotation":
+      case "TypeAlias":
```
Comment (hzoo) [inline packages/babel-helper-module-transforms/src/rewrite-live-references.ts:54]: we don't have an alias to cover all type usage for flow/ts? (or is this it anyway)

**Review by hzoo — APPROVED** [review]

**Review by fedeci — APPROVED** [review]

File: packages/babel-helper-module-transforms/src/rewrite-live-references.ts (hunk 3 above)
Comment (nicolo-ribaudo) [reply packages/babel-helper-module-transforms/src/rewrite-live-references.ts:54]: It's enough to cover the nodes where the AST stops being an expression and starts being a type. The problem with a `TypeScript`/`Flow` catch-all is that both TS and Flow introduce some expression nodes (for example, in enums).

**Review by JLHwung — APPROVED** [review]
