### PR TITLE
Raise recoverable error for await expressions in sync functions

### LINKED ISSUE #12436: Throw better error message when `await` is not used in async functions in errorRecovery mode
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

```js
require('@babel/parser').parse('function foo () {await bar();}', {sourceType: 'module', errorRecovery: true})
Uncaught [SyntaxError: Unexpected token, expected ";" (1:23)
] {
  loc: Position { line: 1, column: 23 },
  pos: 23
}
```

Should throw an error with better message.

**Input Code**

```js
function foo () {await bar();}
```

**Expected behavior**

Mabe like this, when `errorRecovery: false`

```js
require('@babel/parser').parse('function foo () {await bar();}', {sourceType: 'module'})
Uncaught [SyntaxError: 'await' is only allowed within async functions (1:17)
] {
  loc: Position { line: 1, column: 17 },
  pos: 17
}
```

The error message is much better.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**

Through API, without config

**Environment**

```
- Babel version(s): v7.12.7
- Node/npm version: Node 14/npm 6
- OS: Windows 10
- Monorepo: no
- How you are using Babel: api

```

**Possible Solution**

I have no idea

**Additional context**

Issue on Prettier https://github.com/prettier/prettier/issues/9799 and https://github.com/prettier/prettier/issues/9084

### PR DESCRIPTION
**Pull request by sosukesuzuki**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #12436, closes #11090
| Patch: Bug Fix?          | Y
| Tests Added + Pass?      | Yes
| License                  | MIT

This PR addresses only `await` problem, not `yield`.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/12520"></a>

### CODE REVIEW

File: packages/babel-parser/src/parser/expression.js [hunk 1]
```diff
@@ -492,8 +493,18 @@ export default class ExpressionParser extends LValParser {
...
   parseMaybeUnary(refExpressionErrors: ?ExpressionErrors): N.Expression {
-    if (this.isContextual("await") && this.isAwaitAllowed()) {
-      return this.parseAwait();
+    if (this.isContextual("await")) {
+      if (this.isAwaitAllowed()) {
+        return this.parseAwait();
+      } else {
+        if (this.scope.inFunction) {
+          const lookahead = this.lookahead();
+          if (lookahead.type.startsExpr && !this.isAmbiguousAwait(lookahead)) {
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/src/parser/expression.js:502]: We can probably avoid the lookahead by moving this logic to the end of this function: after calling `parseUpdate()`, it it returns an identifier whose name is `await`, we can check if it could be an await expression and the call `parseAwait()`.

`parseAwait()` then needs to be modified to accept the `startLoc` and `startPos` parameters (we can get `.start` and `.loc.start` from `parseUpdate`'s result), and call `startNodeAt` instead of `startNode` in `parseAwait`.

**Comment by nicolo-ribaudo** [comment]
Oh I found #11090 - I completely forgot about it so thanks for opening a new PR!

Something that I notice is missing from this PR is support for TLA: when the plugin is enabled, it we are parsing a `script` and there is a top-level `await` expression, we can report an error.

File: packages/babel-parser/src/parser/expression.js (hunk 1 above)
Comment (sosukesuzuki) [reply packages/babel-parser/src/parser/expression.js]: e16250c

**Comment by sosukesuzuki** [comment]
> Something that I notice is missing from this PR is support for TLA: when the plugin is enabled, it we are parsing a script and there is a top-level await expression, we can report an error.

1affea3

File: packages/babel-parser/src/parser/expression.js [hunk 2]
```diff
@@ -526,7 +532,23 @@ export default class ExpressionParser extends LValParser {
...
+
+    const startsExpr = this.hasPlugin("v8intrinsic")
+      ? this.state.type.startsExpr
+      : this.state.type.startsExpr && !this.match(tt.modulo);
+    if (
+      isAwait &&
+      startsExpr &&
+      !this.isAmbiguousAwait() &&
+      (this.scope.inFunction ||
+        (this.hasPlugin("topLevelAwait") && !this.inModule))
```
Comment (JLHwung) [inline packages/babel-parser/src/parser/expression.js:545]: I think we don't need extra scope / module checks here. When `this.isAmbiguousAwait()` is `false`. It is no more a valid case of `await` being an identifier so we can just reinterpret as a _potential_ await expression.

File: packages/babel-parser/src/parser/expression.js [hunk 3]
```diff
@@ -526,7 +532,23 @@ export default class ExpressionParser extends LValParser {
...
+    ) {
+      this.raise(startPos, Errors.AwaitNotInAsyncContext);
```
Comment (JLHwung) [inline packages/babel-parser/src/parser/expression.js:547]: We throw `AwaitNotInAsyncContext` only when `topLevelAwait` is enabled, otherwise a different error message will be provided.

https://github.com/babel/babel/blob/c8117b6a490607cf6aabbdcb8701457211e60e00/packages/babel-parser/src/parser/expression.js#L2328-L2334

**Comment by sosukesuzuki** [comment]
@JLHwung Thank you for your reviews. I fixed reviewed points!

**Review by existentialism — APPROVED** [review]

File: packages/babel-parser/test/fixtures/experimental/top-level-await/inside-class-property/output.json [hunk 4]
```diff
@@ -0,0 +1,63 @@
+{
+  "type": "File",
+  "start":0,"end":33,"loc":{"start":{"line":1,"column":0},"end":{"line":3,"column":1}},
+  "errors": [
+    "SyntaxError: 'await' is only allowed within async functions (2:6)",
+    "SyntaxError: 'await' is only allowed within async functions (2:6)"
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/test/fixtures/experimental/top-level-await/inside-class-property/output.json:6]: I wonder why this is reported twice :thinking:

Comment (sosukesuzuki) [reply packages/babel-parser/test/fixtures/experimental/top-level-await/inside-class-property/output.json:5]: This is because the error is raised in duplicate with `checkReserved`. 

https://github.com/babel/babel/blob/6e692092fb40950b3fb38eca716a3ad98d3e57f3/packages/babel-parser/src/parser/expression.js#L2349-L2355

I've fixed with workaround by adding a set called `invalidAwaitErrors` to state at 6d3b9c5. Is there better way?

**Review by nicolo-ribaudo — APPROVED** [review]
Thanks!

**Comment by nicolo-ribaudo** [comment]
I tweaked the PR title a bit to make it fit the max commit title length shown by GitHub

File: packages/babel-parser/test/fixtures/es2017/async-functions/await-inside-parameters-of-nested-function/output.json [hunk 5]
```diff
@@ -0,0 +1,77 @@
+{
+  "type": "File",
+  "start":0,"end":55,"loc":{"start":{"line":1,"column":0},"end":{"line":3,"column":1}},
+  "errors": [
+    "SyntaxError: 'await' is only allowed within async functions (2:19)",
+    "SyntaxError: await is not allowed in async function parameters (2:19)"
```
Comment (JLHwung) [inline packages/babel-parser/test/fixtures/es2017/async-functions/await-inside-parameters-of-nested-function/output.json:6]: We are throwing different errors for
```js
async function foo() {
  function bar(x = await 2) {}
}
```
