### PR TITLE
`recordAndTupleSyntaxType` defaults to `"hash"`

### LINKED ISSUE #15756: [Bug]: Error: undefined is not a valid recordAndTuple syntax type
### 💻

- [x] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
const parser = require('@babel/parser');
const traverse = require('@babel/traverse').default;

const ast = parser.parse('const a = #[1]', {
    sourceType: 'module',
    plugins: [
        'recordAndTuple'
    ],
});

traverse(ast, {
    TupleExpression(path) {
        console.log(path.toString());
    }
});
```

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

Current beheviour is crash:

```js
/Users/coderaiser/printer/node_modules/@babel/generator/lib/generators/types.js:136
    throw new Error(`${this.format.recordAndTupleSyntaxType} is not a valid recordAndTuple syntax type`);
    ^

Error: undefined is not a valid recordAndTuple syntax type
    at Generator.TupleExpression (/Users/coderaiser/printer/node_modules/@babel/generator/lib/generators/types.js:136:11)
    at Buffer.exactSource (/Users/coderaiser/printer/node_modules/@babel/generator/lib/buffer.js:239:7)
    at Generator.exactSource (/Users/coderaiser/printer/node_modules/@babel/generator/lib/printer.js:163:15)
    at Generator.print (/Users/coderaiser/printer/node_modules/@babel/generator/lib/printer.js:333:10)
    at Generator.generate (/Users/coderaiser/printer/node_modules/@babel/generator/lib/printer.js:51:10)
    at Generator.generate (/Users/coderaiser/printer/node_modules/@babel/generator/lib/index.js:19:18)
    at generate (/Users/coderaiser/printer/node_modules/@babel/generator/lib/index.js:90:14)
    at NodePath.toString (/Users/coderaiser/printer/node_modules/@babel/traverse/lib/path/index.js:129:35)
    at TupleExpression (/Users/coderaiser/printer/1.js:13:26)
    at NodePath._call (/Users/coderaiser/printer/node_modules/@babel/traverse/lib/path/context.js:46:20)
```

Would be great to receive string representation of `path`.

### Environment

Latest versions.

### Possible solution

Set default to `hash` in `@babel/generator`:

https://github.com/babel/babel/blob/61147b748a4ad9cb5342c501881a225980938a6f/packages/babel-generator/src/index.ts#L74

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by coderaiser**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #15756 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15757"></a>

Not sure how good this fix is, but for `@babel/parser` default syntax is `hash`:

image

So better to set it as default, then crash 🤷‍♂️.

### CODE REVIEW

File: packages/babel-generator/src/index.ts [hunk 1]
```diff
@@ -71,7 +71,7 @@ function normalizeOptions(
       minimal: process.env.BABEL_8_BREAKING ? true : false,
       ...opts.jsescOption,
     },
-    recordAndTupleSyntaxType: opts.recordAndTupleSyntaxType,
+    recordAndTupleSyntaxType: opts.recordAndTupleSyntaxType || "hash",
```
Comment (JLHwung) [inline packages/babel-generator/src/index.ts:74]:
```suggestion
    recordAndTupleSyntaxType: opts.recordAndTupleSyntaxType ?? "hash",
```
boolean option here will not be accepted.

**Review by JLHwung — APPROVED** [review]
