### PR TITLE
fix(class-properties): replace `new.target` in static properties with `undefined`

### LINKED ISSUE #12737: class-property transform leaks new.target in initializer to upper level
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

- [REPL](https://babel.dev/repl#?browsers=IE%206&build=&builtIns=usage&spec=false&loose=false&code_lz=MYGwhgzhAEDC0G8BQ1rAPYDsIBcBOArsDungBQCUiKq0OAFgJYQB0AYuutALxrhTVatXGByNg0AA49omAKYB3FjjB4A5nJw1UAXxp69YEHLw4yZeQrgV2nFpIpA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=stage-3&prettier=false&targets=&version=7.12.12&externalPlugins=)

`(new C).Foo.p` evaluates to `C`.

**Input Code**

```js
class C {
  constructor() {
    this.Foo = class {
      static p = new.target
    }
  }
}
```

**Expected behavior**
`(new C).Foo.p` should evaluate to `undefined`.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
See REPL configs

**Environment**
REPL

**Possible Solution**
When we are converting class properties into `defineProperty` calls that are appended to the `class`, we should replace `new.target` in class field initializers to `undefined` if it is [associated](https://github.com/babel/babel/blob/bab5c62f907b6f90d094531ab22aa0a86d7c35a5/packages/babel-plugin-transform-new-target/src/index.js#L20-L30) to the class scope, otherwise `new.target` is leaked to the upper `new.target` values.

The replacing step can be inserted after `super()` is replaced in initializers:

https://github.com/babel/babel/blob/bab5c62f907b6f90d094531ab22aa0a86d7c35a5/packages/babel-helper-create-class-features-plugin/src/fields.js#L684

More test examples:

```js
class C {
  constructor() {
    this.Foo = class {
      static p1 = class { constructor() { new.target } } // should not replace
      static p2 = new function () { new.target } // should not replace
      static p3 = () => { new.target } // should replace
    }
  }
}
```

### PR DESCRIPTION
**Pull request by colinaaa**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #12737 
| Patch: Bug Fix?          | 👍
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | 👍
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

When we meet a static class property, we traverse to visit all `new.target` with a `MetaProperty` visitor.

Then we find out if or not this `new.target` is associated with a class by:

```ts
const func = path.findParent((path) => {
  if (path.isClass()) return true;
  if (path.isFunction() && !path.isArrowFunctionExpression()) {
    return true;
  }
  return false;
});
```

Now, if `func` is a child of `prop`, we do nothing. If not, that means `new.target` now is leaked to upper `new.target`, we just replace it by `undefined` / `void 0`.

```ts
if (!func.findParent((path) => path === prop)) {
  // if func is not child of prop, which means
  // `new.target` is leaked to the upper `new.target` values.
  // thus we should replace it with `undefined` (`void 0` here)
  path.replaceWith(scope.buildUndefinedNode());
}
```
<a href="https://gitpod.io/#https://github.com/babel/babel/pull/13560"></a>

### CODE REVIEW

File: packages/babel-helper-create-class-features-plugin/src/fields.ts [hunk 1]
```diff
@@ -770,6 +771,26 @@ export function buildFieldsInitNodes(
       needsClassRef = needsClassRef || replaced;
     }
 
+    // if there are `new.target` in static filed
```
Comment (existentialism) [inline packages/babel-helper-create-class-features-plugin/src/fields.ts:774]: Nit:

```suggestion
    // if there are `new.target` in static field
```

File: packages/babel-plugin-transform-new-target/test/fixtures/general/class-properties/options.json [hunk 2]
```diff
@@ -2,6 +2,6 @@
   "plugins": [
     "transform-new-target",
     "transform-arrow-functions",
-    ["proposal-class-properties", { "loose": true }]
+    ["proposal-class-properties", { "loose": false }]
```
Comment (existentialism) [inline packages/babel-plugin-transform-new-target/test/fixtures/general/class-properties/options.json:5]: Should we keep this and create a new test for loose: false behavior?

Comment (colinaaa) [reply packages/babel-plugin-transform-new-target/test/fixtures/general/class-properties/options.json:5]: Sure! I changed loose to make it more readable, and forgot to change it back😭

File: packages/babel-helper-create-class-features-plugin/src/fields.ts [hunk 3]
```diff
@@ -770,6 +771,38 @@ export function buildFieldsInitNodes(
...
+            meta.isIdentifier({ name: "new" }) &&
+            property.isIdentifier({ name: "target" })
+          ) {
+            const func = path.findParent(path => {
+              if (path.isClass()) return true;
+              if (path.isFunction() && !path.isArrowFunctionExpression()) {
+                return true;
+              }
+              return false;
+            });
```
Comment (nicolo-ribaudo) [inline packages/babel-helper-create-class-features-plugin/src/fields.ts:794]: Rather than going back up in the AST to check what `new.target` refers to, we can do it in `thisContextVisitor`:

```ts
const thisContextVisitor = traverse.visitors.merge([
  {
    ThisExpression(path, state) {
      state.needsClassRef = true;
      path.replaceWith(t.cloneNode(state.classRef));
    },
    MetaProperty(path: NodePath<t.MetaProperty>, state) {
      if (
        state.shouldReplaceNewTarget &&
        path.get("meta").isIdentifier({ name: "new" }) &&
        path.get("property").isIdentifier({ name: "target" })
      ) {
        path.replaceWith(scope.buildUndefinedNode());
      }
    }
  },
  environmentVisitor,
]);
```

This is faster because:
- The visitor is cached; we don't need to recreate it on every `buildFieldsInitNodes` call
- It only visits what's needed, thanks to `environmentVisitor`
- We can transform both `this` and `new.target` in the same pass, since they need to be transformed exactly in the same scopes


Also, can you add a test for `new.target` inside a static block? (I think it should be undefined):
```js
class A {
  constructor() {
    class B {
      static { new.target; }
    }
  }
}
```

**Comment by JLHwung** [comment]
We can now enable tests `packages/babel-plugin-proposal-class-static-block/test/fixtures/integration/.new-target/exec.js` , once disabled in #12738. You can rename `.new-target` to `new-target`.

File: packages/babel-helper-create-class-features-plugin/src/fields.ts [hunk 4]
```diff
@@ -665,6 +666,24 @@ const thisContextVisitor = traverse.visitors.merge([
...
+      state.shouldReplaceNewTarget = path.isArrowFunctionExpression();
+    },
+    MetaProperty(path: NodePath<t.MetaProperty>, state) {
+      const meta = path.get("meta");
+      const property = path.get("property");
+      const { scope } = path;
+      // if there are `new.target` in static field
+      // we should replace it with `undefined`
+      if (
+        state.shouldReplaceNewTarget &&
```
Comment (nicolo-ribaudo) [inline packages/babel-helper-create-class-features-plugin/src/fields.ts:680]: I caused confusion using `state.shouldReplaceNewTarget` in my example. After seeing this complete code, `state.shouldReplaceNewTarget` is not needed: `environmentVisitor` (that is merged to this visitor) already skips non-arrow functions, we we don't need to have our custom `Function` visitor.

Comment (colinaaa) [reply packages/babel-helper-create-class-features-plugin/src/fields.ts:680]: Good point!

File: packages/babel-plugin-proposal-class-static-block/test/fixtures/integration/new-target/output.js [hunk 5]
```diff
@@ -0,0 +1,13 @@
+class Base {
+  constructor() {
+    var _class, _temp;
+
+    this.Foo = (_temp = _class = class {}, (() => {
+      // fixme: new.target should be undefined after transformed
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-proposal-class-static-block/test/fixtures/integration/new-target/output.js:6]: Nit: you can delete this comment from `input.js`

**Review by nicolo-ribaudo — APPROVED** [review]
Thanks!

**Review by existentialism — APPROVED** [review]

**Review by JLHwung — APPROVED** [review]
Thanks!
