### PR TITLE
Avoid fancy stack traces size computation

### LINKED ISSUE #14927: [Bug]: rewrite-stack-trace logic break stack trace for Jest
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

Steps for reproducing are described here (https://github.com/facebook/jest/issues/13248); confirmed by `jest` team as upstream (`babel`) issue. More detail on confirming the problem described below.

> In `rewrite-stack-trace.ts`, the Error.stackTraceLimit is being adjusted in a **singleton function**. This runs just once within a process.
> 
> What's happening is as follows:
> 
> 1. Jest starts and sets `Error.stackTraceLimit` to `100`.
> 2. At some point the babel rewrite code runs and sets `Error.stackTraceLimit` to `Error.stackTraceLimit += STACK_TRACE_LIMIT_DELTA;` (`const STACK_TRACE_LIMIT_DELTA = 100;`).
> 3. When errors are reported on first run, they are truncated to `newTrace.slice(0, Error.stackTraceLimit - STACK_TRACE_LIMIT_DELTA),` (see [here](https://github.com/babel/babel/blob/05deb6040523c0af4847c5c8f6d1589a0d8d3e89/packages/babel-core/src/errors/rewrite-stack-trace.ts#L163)).
> 4. When a process is re-used, jest re-initializes the `Error.stackTraceLimit` to `100`.
> 5. Because `rewrite-stack-trace.ts` operates as a singleton, it is not expecting `Error.stackTraceLimit` to have been reset, and then completely truncates subsequent stack traces because now `Error.stackTraceLimit` is `100`, and `STACK_TRACE_LIMIT_DELTA` is `100`, and the processing code `newTrace.slice(0, Error.stackTraceLimit - STACK_TRACE_LIMIT_DELTA)` becomes `newTrace.slice(0, 100 - 100)`.

You can confirm this behavior by changing `setupPrepareStackTrace` method in distributed `@babel/core/lib/errors/rewrite-stack-trace.js`:

```diff
...
function setupPrepareStackTrace() {
+   require('fs').appendFileSync('path_to_log_file.txt', (Error.stackTraceLimit - STACK_TRACE_LIMIT_DELTA).toString() + '\n');
    return prepareStackTrace(err, newTrace.slice(0, Error.stackTraceLimit - STACK_TRACE_LIMIT_DELTA));
...
}
...
```

Sample output when running the [sample repo](https://github.com/smcenlly/jest-stack-trace-issue) provided in the [jest issue](https://github.com/facebook/jest/issues/13248), for `Error.stackTraceLimit - STACK_TRACE_LIMIT_DELTA`:

```
100
100
100
100
0
```

After this point, the error stack is always completely truncated.

### Configuration file name

_No response_

### Configuration

Default Jest Babel Configuration (not applicable to the issue)

### Current and expected behavior

Babel should be tolerant of other tooling setting `Error.stackTraceLimit`.

### Environment

@babel/core@7.19.0

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #14927
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

This will end up with the actual number of frames not exactly matching the user-set Error.stackTraceLimit. However, Error.stackTraceLimit is usually set to generic numbers (10, 100, 1000, Infinity), and it does not matter if it's not _really_ X but a bit less or more.

(How long before we get a bug report "Hey, I use Error.stackTraceLimit=1562 but it's only giving me 1543 frames!"?)

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14930"></a>

### CODE REVIEW

File: packages/babel-core/src/errors/rewrite-stack-trace.ts [hunk 1]
```diff
@@ -131,7 +122,17 @@ function setupPrepareStackTrace() {
...
 
-  Error.stackTraceLimit += STACK_TRACE_LIMIT_DELTA;
+  // We add some extra frames to Error.stackTraceLimit, so that we can
+  // always show some useful frames even after deleting ours.
+  // STACK_TRACE_LIMIT_DELTA should be around the maximum expected number
+  // of internal frames, and not too big because capturing the stack trace
+  // is slow (this is why Error.stackTraceLimit does not default to Infinity!).
+  // Increase it if needed.
+  const MIN_STACK_TRACE_LIMIT = 50;
+  Error.stackTraceLimit = Math.max(
```
Comment (liuxingbaoyu) [inline packages/babel-core/src/errors/rewrite-stack-trace.ts:132]:
```js
  if (
    Error.stackTraceLimit < MIN_STACK_TRACE_LIMIT &&
    Error.stackTraceLimit > 10
  ) {
    Error.stackTraceLimit = MIN_STACK_TRACE_LIMIT;
  }
```
Would this be better?

Comment (nicolo-ribaudo) [reply packages/babel-core/src/errors/rewrite-stack-trace.ts]: I only skipped the 0 case. If `Error.stackTraceLimit` is a low number, we would otherwise often make it 0 by deleting our own frames (and 0 is worse then "a few more than expected", when you still want _something_).

**Review by liuxingbaoyu — APPROVED** [review]

**Review by JLHwung — APPROVED** [review]
