### PR TITLE
fix: throw when `async()` call param is object with assignement

### LINKED ISSUE #13392: [Bug]: `async({ foo33 = 1 })` is parsed without errors
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
async({ foo33 = 1 });
```

### Configuration file name

_No response_

### Configuration

Default parser config

### Current and expected behavior

`foo33 = 1` is parsed as an `ObjectProperty` whose value is an `AssignmentPattern`. It should throw, since objects cannot have property initializers with `=`.

### Environment

Babel 7.14.4

### Possible solution

_No response_

### Additional context

Reported at https://twitter.com/buzyescayadev/status/1398526884955058181

### PR DESCRIPTION
**Pull request by tony-go**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            |  Fixes #13392 
| Patch: Bug Fix?          | 👍
| Major: Breaking Change?  | 🚫 
| Minor: New Feature?      | 🚫
| Tests Added + Pass?      | 👍
| Documentation PR Link    | 🚫
| Any Dependency Changes?  | 🚫
| License                  | MIT

Hi there 👋 ,

After few hours exploring `babel-parser` I open this draft pull request.

Let me know what do you think about the code.

Input code:

```js
async({ foo33 = 1 });
```

**Before**: was parsed without error 🤮 
**After**: throw an error as expected 🎉 

<details><summary>Note: I got an error running all tests</summary>
<p>

But it seems to be there even on `main` branch .

```bash
FAIL  packages/babel-node/test/fixtures.js (72.567 s)
  ● bin/babel-node › node_--inspect
thrown: “Exceeded timeout of 20000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test.”
      206 |     }
      207 |
    > 208 |     it(testName, buildTest(testName, opts), 20000);
          |     ^
      209 |   });
      210 | });
```

</p>
</details>

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/13410"></a>

### CODE REVIEW

File: packages/babel-parser/src/parser/expression.js [hunk 1]
```diff
@@ -931,7 +935,7 @@ export default class ExpressionParser extends LValParser {
       elts.push(
         this.parseExprListItem(
           false,
-          possibleAsyncArrow ? new ExpressionErrors() : undefined,
+          refExpressionErrors || new ExpressionErrors(),
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/src/parser/expression.js:938]: Do we need to always create `new ExpressionErrors()` if `refExpressionErrors` is not defined, or can we do something like this?

```suggestion
          refExpressionErrors || (possibleAsyncArrow ? new ExpressionErrors() : undefined),
```

Or actually, can we just always forward `refExpressionErrors` since we now pass a `new ExpressionErrors()` instance when calling `parseCallExpressionArguments`?

```suggestion
          refExpressionErrors,
```

Comment (JLHwung) [reply packages/babel-parser/src/parser/expression.js:938]: `refExpressionErrors` is provided if and only if `possibleAsyncArrow` is `true`. Guess we can simplify the interface of `parseCallExpressionArguments` and replace the `possibleAsyncArrow` argument.

Comment (tony-go) [reply packages/babel-parser/src/parser/expression.js:938]: Hey Guys 👋 

Thanks a lot for your review.

@JLHwung could you explain a bit more when you said: `replace the possibleAsyncArrow argument"` ?

I can modify it really quick when we'll aligned ^^

Thanks a lot guys ✋

Comment (JLHwung) [reply packages/babel-parser/src/parser/expression.js:938]: That's a good question. If the proposition that `possibleAsyncArrow` is `true` is equivalent to the proposition that `refExpressionErrors !== undefined`, then we can replace `possibleAsyncArrow` by `refExpressionErrors !== undefined` so we can get rid of one parameter, which is more performant.

Claim: I didn't actually test it. It is up to you to discover whether it works. 😄

Comment (tony-go) [reply packages/babel-parser/src/parser/expression.js:936]: I finally deleted `possibleAsyncArrow` and as `parseCallExpressionArguments` is called somewhere without `refExpressionErrors` so I let: `refExpressionErrors || new ExpressionErrors(),`.

File: packages/babel-parser/src/parser/expression.js [hunk 2]
```diff
@@ -931,8 +933,8 @@ export default class ExpressionParser extends LValParser {
       elts.push(
         this.parseExprListItem(
           false,
-          possibleAsyncArrow ? new ExpressionErrors() : undefined,
-          possibleAsyncArrow ? { start: 0 } : undefined,
+          refExpressionErrors || new ExpressionErrors(),
```
Comment (JLHwung) [inline packages/babel-parser/src/parser/expression.js:936]:
```suggestion
          refExpressionErrors,
```
I don't think we should create ExpressionErrors inside `parseCallExpressionArguments`. The ExpressionErrors should be created only when the argument is ambiguous, which means it can either be an Object Pattern in Async Arrow, or an Object Expression in Async Call function.

For example, if we always create `ExpresionErrors`, Babel will consider duplicate proto in call expression arguments are always ambiguous: For example, in this PR Babel does not throw for invalid `async?.({ __proto__: x, __proto__: y })` when the Flow plugin is enabled: [REPL](https://babeljs.io/repl/build/46638/#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=IYZwngdgxg_AdACgN4AID6aAOAnA9gF1wwC4UAPAGnSz0JJTBQF8BKIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2%2Cflow&prettier=false&targets=&version=7.14.4%2Bpr.13410&externalPlugins=).

File: packages/babel-parser/src/parser/expression.js [hunk 3]
```diff
@@ -931,8 +933,8 @@ export default class ExpressionParser extends LValParser {
...
+          { start: 0 },
```
Comment (JLHwung) [inline packages/babel-parser/src/parser/expression.js:937]: Not related to this PR: The `refNeedsArrowPos` argument here seems to be always disabled. We could consider removing this variable.

File: packages/babel-parser/src/parser/expression.js [hunk 4]
```diff
@@ -766,6 +766,7 @@ export default class ExpressionParser extends LValParser {
     optional: boolean,
   ): N.Expression {
     const oldMaybeInArrowParameters = this.state.maybeInArrowParameters;
+    const refExpressionErrors = new ExpressionErrors();
```
Comment (JLHwung) [inline packages/babel-parser/src/parser/expression.js:769]: I think we should create `refExpressionErrors` only when `state.maybeAsyncArrow` is `true`, otherwise `refExpressionErrors !== undefined` is no longer equivalent to `possibleAsyncArrow`.

File: packages/babel-parser/test/fixtures/es2017/async-call/parenthesized-argument-object-double-proto/input.js [hunk 5]
```diff
@@ -0,0 +1 @@
+async({ __proto__: x, __proto__: y })
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/test/fixtures/es2017/async-call/parenthesized-argument-object-double-proto/input.js:1]: Maybe you could also add a test like
```js
async ({ __proto__: x, __proto__: y }) => {}
```
which is valid and shouldn't report an error.

File: packages/babel-parser/src/parser/expression.js (hunk 2 above)
Comment (tony-go) [reply packages/babel-parser/src/parser/expression.js:936]: Thanks 😄 It's probably what @nicolo-ribaudo try to explain me in his first commit but I got it only now 😆 . Sorry for that.

File: packages/babel-parser/src/parser/expression.js (hunk 3 above)
Comment (tony-go) [reply packages/babel-parser/src/parser/expression.js:937]: Do you prefer that we tackle this one in another PR?

File: packages/babel-parser/src/parser/expression.js (hunk 4 above)
Comment (tony-go) [reply packages/babel-parser/src/parser/expression.js]: I push this update in the commit `7ab3018`. Let me know I got you right.

File: packages/babel-parser/src/parser/expression.js (hunk 3 above)
Comment (nicolo-ribaudo) [reply packages/babel-parser/src/parser/expression.js:942]: It can be done in a follow-up PR

Comment (tony-go) [reply packages/babel-parser/src/parser/expression.js:942]: Should I create an issue ?

File: packages/babel-parser/src/parser/expression.js [hunk 6]
```diff
@@ -801,6 +804,10 @@ export default class ExpressionParser extends LValParser {
         node,
       );
     } else {
+      if (refExpressionErrors !== null) {
+        this.checkExpressionErrors(refExpressionErrors, true);
```
Comment (JLHwung) [inline packages/babel-parser/src/parser/expression.js:808]: nit: Can we move this to the `state.maybeAsyncArrow` branch?

If Flow is complaining, you can add an invariant comment to tell flow that `state.maybeAsyncArrow` is equivalent to `refExpressionErrors !== null`:

```js
/*:: invariant(refExpressionErrors !== null) */
```

File: packages/babel-parser/src/parser/expression.js [hunk 7]
```diff
@@ -766,6 +766,9 @@ export default class ExpressionParser extends LValParser {
     optional: boolean,
   ): N.Expression {
     const oldMaybeInArrowParameters = this.state.maybeInArrowParameters;
+    const refExpressionErrors = state.maybeAsyncArrow
+      ? new ExpressionErrors()
```
Comment (JLHwung) [inline packages/babel-parser/src/parser/expression.js:770]: Same here. The idea is that less branching improves performance.

Comment (tony-go) [reply packages/babel-parser/src/parser/expression.js]: Yeah you right. When I step back a bit I found that it's pretty obvious ahaha ^^ Thanks.

**Review by JLHwung — APPROVED** [review]

File: packages/babel-parser/src/parser/expression.js (hunk 3 above)
Comment (nicolo-ribaudo) [reply packages/babel-parser/src/parser/expression.js:940]: If you want to just open a new PR (if you still want to work on it), it's ok to just open a PR without an issue!

Comment (tony-go) [reply packages/babel-parser/src/parser/expression.js:940]: I'll ^^
