### PR TITLE
Fix arrow transformation when `arguments` is defined as variable

### LINKED ISSUE #7673: Top-level arrows that mistakenly use 'arguments' can cause unexpected runtime errors where there are none in an ES6 engine
Reported on Slack yesterday.

### Input Code

```js
var foo = () => {
  console.log(arguments);
};
```

### Expected Behavior

Should be a silent no-op.

### Current Behavior

```js
var _arguments = arguments;
var foo = function() {
  console.log(_arguments);
};
```

throws an exception because there is no global `arguments` binding.

### Possible Solution
Maybe explicitly add extra logic when the arrow is top-level, e.g.
```js
var _arguments = typeof arguments === "undefined" ? undefined : arguments;
var foo = function() {
  console.log(_arguments);
};
```
this wouldn't throw properly if `foo` is actually called through, so possibly expand to

```js
var _arguments = typeof arguments === "undefined" ? undefined : arguments;
var foo = function() {
  console.log(_arguments === undefined ? throw new ReferenceError("...") : _arguments);
};
```
Still not 100% safe since sloppy code might technically have declared a variable named `arguments` that actually has `undefined` as a value? Not super likely though.

### PR DESCRIPTION
**Pull request by snitin315**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            |  Fixes https://github.com/babel/babel/issues/11385, fixes #7673  
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

Fixes https://github.com/babel/babel/issues/11385

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/12344"></a>

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/12344"></a>

### CODE REVIEW

File: packages/babel-traverse/src/path/conversion.js [hunk 1]
```diff
@@ -223,10 +223,14 @@ function hoistFunctionEnvironment(
     );
 
     argumentsPaths.forEach(argumentsChild => {
-      const argsRef = t.identifier(argumentsBinding);
-      argsRef.loc = argumentsChild.node.loc;
-
-      argumentsChild.replaceWith(argsRef);
+      if (
+        !argumentsChild.scope.hasOwnBinding("arguments") &&
+        !argumentsChild.scope.parent.hasOwnBinding("arguments")
```
Comment (snitin315) [inline packages/babel-traverse/src/path/conversion.js:228]: I'm not sure how to check this recursively 😕

Comment (mischnic) [reply packages/babel-traverse/src/path/conversion.js:228]: Maybe `argumentsChild.scope.hasBinding("arguments)`?

https://github.com/babel/babel/blob/5bbad8936b05a2b6739dcade6464dbc361118aa9/packages/babel-traverse/src/scope/index.js#L1036-L1048

Comment (nicolo-ribaudo) [reply packages/babel-traverse/src/path/conversion.js:228]: `.hasBinding()` checks every ancestor scope, while we should stop when we find a `function` scope.
@snitn315 You can write a `while` loop that checks if the current scope has the `arguments` binding, and then moves to `scope.parent` until it finds a function declaration/expression scope.

Another test case:
```js
var arrow = () => {
  var arguments = 2;
  return function () {
    return () => arguments;
  }
};

expect(arrow()(1, 2, 3)()).toEqual([1, 2, 3]);
```

Comment (snitin315) [reply packages/babel-traverse/src/path/conversion.js]: @nicolo-ribaudo , @mischnic  thanks, I have updated the code please review once again.

**Comment by nicolo-ribaudo** [comment]
The CI failure is a bug in a dependency.

**Comment by snitin315** [comment]
So do we have to wait for the patch release of the dep?

**Comment by existentialism** [comment]
> So do we have to wait for the patch release of the dep?

Not to land this PR, no.

File: packages/babel-traverse/src/path/conversion.js [hunk 2]
```diff
@@ -223,10 +223,20 @@ function hoistFunctionEnvironment(
...
-      argsRef.loc = argumentsChild.node.loc;
-
-      argumentsChild.replaceWith(argsRef);
+      let currentScope = argumentsChild.scope;
+      do {
+        if (
+          !currentScope.hasOwnBinding("arguments") &&
+          !(
+            currentScope.path.isFunctionExpression() ||
+            currentScope.path.isFunctionDeclaration()
```
Comment (JLHwung) [inline packages/babel-traverse/src/path/conversion.js:232]:
```suggestion
            currentScope.path.isFunction()
```
A class method is also a function.
```js
var twelve = () => {
  var arguments = 2;
  return class {
    m() { return () => arguments; }
  }
};
```

Comment (snitin315) [reply packages/babel-traverse/src/path/conversion.js]: 👍🏻

**Comment by snitin315** [comment]
The tests are passing locally 😕

**Comment by nicolo-ribaudo** [comment]
Try rebasing on `main`, that should be fixed now :pray:

**Comment by nicolo-ribaudo** [comment]
Since the failures seems realted to this PR, try rebasing on `main`, running `make bootstrap` and then `OVERWRITE=true yarn jest`.

File: packages/babel-traverse/src/path/conversion.js (hunk 2 above)
Comment (JLHwung) [reply packages/babel-traverse/src/path/conversion.js]: Ah the ArrowFunctionExpression should be excluded.
```js
currentScope.path.isFunction() && !currentScope.path.isArrowFunctionExpression()
```

File: packages/babel-plugin-transform-arrow-functions/test/fixtures/arrow-functions/arguments/output.js [hunk 3]
```diff
@@ -81,3 +83,68 @@ function six(obj) {
...
+  return arguments;
+};
+
+seven();
+
+var eight = function () {
+  var arguments = 1;
+  return function () {
+    return _arguments6;
+  };
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-arrow-functions/test/fixtures/arrow-functions/arguments/output.js:98]: This looks wrong to me, since it doesn't return `1`.

Comment (snitin315) [reply packages/babel-plugin-transform-arrow-functions/test/fixtures/arrow-functions/arguments/output.js:98]: The rest looks fine?

File: packages/babel-traverse/src/path/conversion.js [hunk 4]
```diff
@@ -223,10 +223,20 @@ function hoistFunctionEnvironment(
...
-      argsRef.loc = argumentsChild.node.loc;
-
-      argumentsChild.replaceWith(argsRef);
+      let currentScope = argumentsChild.scope;
+      do {
+        if (
+          !currentScope.hasOwnBinding("arguments") &&
+          !(
+            currentScope.path.isFunction() &&
+            !currentScope.path.isArrowFunctionExpression()
```
Comment (nicolo-ribaudo) [inline packages/babel-traverse/src/path/conversion.js:232]: I think these checks should be moved to `getScopeInformation`, where we push to the `argumentsPaths` array.

Also, I find this logic with nested negations a bit hard to read. Maybe (when moving it to `getScopeInformation`) we could rewrite it to use an early return?

```js
let curr = path.scope;
do {
  if (curr.hasOwnBinding("arguments")) return;
  if (curr.path.isFunction() && !currentScope.path.isArrowFunctionExpression()) break;
} while ((curr = curr.parent));
```

File: packages/babel-plugin-transform-arrow-functions/test/fixtures/arrow-functions/arguments/output.js (hunk 3 above)
Comment (nicolo-ribaudo) [reply packages/babel-plugin-transform-arrow-functions/test/fixtures/arrow-functions/arguments/output.js:98]: To fix this, when we find an `arguments` binding in the `do-while` loop, we should probably call `curr.rename("arguments")` so that it changes the binding name.

**Review by nicolo-ribaudo — COMMENTED** [review]
Hey I'm sorry that we forgot about this PR for four months :sweat_smile: 

I left some comments, but if you aren't interested anymore since it's been so long I can make the necessary changes.

**Comment by snitin315** [comment]
I will update the PR 👍

**Comment by snitin315** [comment]
@nicolo-ribaudo I have updated the PR, please take a look.

**Review by nicolo-ribaudo — COMMENTED** [review]
I realized I had this pending comment since your last commit, and I forgot to send the review :sweat_smile:

File: packages/babel-core/test/fixtures/transformation/misc/regression-2364/output.js [hunk 5]
```diff
@@ -1,9 +1,7 @@
 function wrapper(fn) {
   return function () {
-    var _arguments = arguments;
-
     var _loop = function () {
-      var val = fn(..._arguments);
+      var val = fn(...arguments);
```
Comment (nicolo-ribaudo) [inline packages/babel-core/test/fixtures/transformation/misc/regression-2364/output.js:4]: This is a bug; I'll clone this PR locally to understand what's happening.

**Review by nicolo-ribaudo — APPROVED** [review]

**Comment by snitin315** [comment]
Thanks for the update 👍

**Review by JLHwung — APPROVED** [review]
