### PR TITLE
cli: handle multiple input sources in watch mode

### LINKED ISSUE #14269: [Bug]: Babel watch is broken for multiple subdirectories on 7.17.X
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

https://github.com/faow/babel_test

### Configuration file name

_No response_

### Configuration

```json
{
    "ignore": [
        "**/*.d.ts",
        "**/node_modules/**"
    ],
    "presets": [
        "@babel/preset-typescript"
    ]
}
```

### Current and expected behavior

Current Behaviour:

If you add `--watch` to the compiler and have multiple subdirectories, the watcher compiles every edited file to the input and output directory.

It seems like multiple watchers are spawned. For every subdirectory the same file gets compiled again.

## Babel without watch
```bash
 > npx babel "*/src" --out-dir ../webapp --source-maps true --extensions ".ts" --copy-files --include-dotfiles --relative --verbose

subFolder1\src\test1.ts -> subFolder1\webapp\test1.js
subFolder2\src\test2.ts -> subFolder2\webapp\test2.js
Successfully compiled 2 files with Babel (444ms).
```

## Babel with watch initial compilation (working)
```bash
 > npx babel "*/src" --out-dir ../webapp --source-maps true --extensions ".ts" --copy-files --include-dotfiles --relative --watch --verbose

subFolder1\src\test1.ts -> subFolder1\webapp\test1.js
subFolder2\src\test2.ts -> subFolder2\webapp\test2.js
Successfully compiled 2 files with Babel (576ms).
```

## Babel with watch: compilation after editing a file (not working)
```bash
subFolder1\src\test1.ts -> subFolder1\webapp\test1.js
subFolder1\src\test1.ts -> subFolder1\src\test1.js
```
The second compilation should not happen.

## Babel with watch and 3 subfolders: Initial and editing a file
For this case simple add another subfolder to the [github sample project](https://github.com/faow/babel_test).

```babel
> npx babel "*/src" --out-dir ../webapp --source-maps true --extensions ".ts" --copy-files --include-dotfiles --relative --watch --verbose

subFolder1\src\test1.ts -> subFolder1\webapp\test1.js
subFolder2\src\test2.ts -> subFolder2\webapp\test2.js
subFolder3\src\test3.ts -> subFolder3\webapp\test3.js
Successfully compiled 3 files with Babel (420ms).
subFolder3\src\test3.ts -> subFolder3\src\test3.js
subFolder3\src\test3.ts -> subFolder3\src\test3.js
subFolder3\src\test3.ts -> subFolder3\webapp\test3.js
```
The first and second compilation should not happen.

Expected behaviour:
With 
- "@babel/cli": "7.16.8"
- "@babel/core": "7.16.12"

it is working as expected. Just install the mentioned versions to the [github sample project](https://github.com/faow/babel_test).

```bash
> npx babel "*/src" --out-dir ../webapp --source-maps true --extensions ".ts" --copy-files --include-dotfiles --relative --watch --verbose

subFolder1\src\test1.ts -> subFolder1\webapp\test1.js
subFolder2\src\test2.ts -> subFolder2\webapp\test2.js
subFolder3\src\test3.ts -> subFolder3\webapp\test3.js
Successfully compiled 3 files with Babel (423ms).
subFolder2\src\test2.ts -> subFolder2\webapp\test2.js
Successfully compiled 1 file with Babel (109ms).
```

### Environment

**System:**
- OS: Windows 10 10.0.19043

**Binaries:**
- Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
- npm: 8.3.2 - C:\Program Files\nodejs\npm.CMD

**npmPackages:**
- @babel/cli: 7.17.0 => 7.17.0
- @babel/core: 7.17.2 => 7.17.2
- @babel/preset-typescript: 7.16.7 => 7.16.7

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #14269 
| Patch: Bug Fix?          | Y
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

In this PR we fix a regression introduced in #14065. Currently we registered multiple listeners for each `--src` parameter, however, each listeners will be invoked unconditionally even only one of file specified by some `--src` parameter are changed. Therefore `babel-cli` creates multiple compilation and, which is worse, outputs compiled files on unwanted paths.

In this PR we determine the input base from the filename when multiple `--src` parameters are specified. A cache is introduced to avoid repeatedly searching `--src` parameters.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14281"></a>

### CODE REVIEW

File: packages/babel-cli/test/fixtures/babel/dir --out-dir --watch multiple dir/executor.js [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+  console.log(str);
+
+  if (run.next(str).done) {
+    process.exit(0);
+  }
+});
+
+setTimeout(() => {
+  console.error("EXECUTOR TIMEOUT");
+  process.exit(1);
```
Comment (nicolo-ribaudo) [inline packages/babel-cli/test/fixtures/babel/dir --out-dir --watch multiple dir/executor.js:34]: We could replace `exit(1)` with `exit(0)` in all the watch tests and use `.log` instead of `.error`, to see at which point they get stuck.

Comment (JLHwung) [reply packages/babel-cli/test/fixtures/babel/dir --out-dir --watch multiple dir/executor.js]: Good idea! I can't reproduce the timeout error on my local machine, now I have to abuse GitHub CI to see what happens.

File: packages/babel-cli/test/fixtures/babel/dir --out-dir --watch --verbose with external dependencies/executor.js [hunk 2]
```diff
@@ -4,15 +4,16 @@ const assert = require("assert");
...
   let files = [yield, yield].sort();
   assert.match(files[0], /src[\\/]index.js -> lib[\\/]index.js/);
   assert.match(files[1], /src[\\/]main.js -> lib[\\/]main.js/);
   assert.match(yield, /Successfully compiled 2 files with Babel \(\d+ms\)\./);
 
   logFile("lib/index.js");
   logFile("lib/main.js");
-
+  // wait 200ms for watcher setup
+  await new Promise(resolve => setTimeout(resolve, 200));
```
Comment (nicolo-ribaudo) [inline packages/babel-cli/test/fixtures/babel/dir --out-dir --watch --verbose with external dependencies/executor.js:16]: Ohhh thanks for this!

File: packages/babel-cli/src/babel/dir.ts [hunk 3]
```diff
@@ -177,34 +177,70 @@ export default async function ({
...
+      const base = filenames[0];
+      const absoluteBase = path.resolve(base);
+      getBase = filename => {
+        return filename === absoluteBase ? path.dirname(base) : base;
+      };
+    } else {
+      // A map from absolute compiled file path to its base, from which
+      // the output destination will be determined
+      const filenameToBaseMap: Map<string, string> = new Map(
+        filenames.map(filename => {
```
Comment (nicolo-ribaudo) [inline packages/babel-cli/src/babel/dir.ts:193]: I was wondering whether these could be globs or not, but they are already resolved at https://github.com/babel/babel/blob/193728405b6efc46a828e665510a265fc72b344c/packages/babel-cli/src/babel/options.ts#L192-L197

**Review by nicolo-ribaudo — APPROVED** [review]

File: packages/babel-cli/src/babel/dir.ts (hunk 3 above)
Comment (JLHwung) [reply packages/babel-cli/src/babel/dir.ts:193]: Yes they are resolved prior to watch setup, which means if you run `babel */src --watch` and then create a new folder `module3/src`, it will not be added to the watcher.

**Comment by JLHwung** [comment]
Interesting, tests are still failing even if I invoke initial build after the watcher claims ready: https://github.com/babel/babel/actions/runs/1866868095 I have revert this commit and will explore it in another PR.

**Review by existentialism — APPROVED** [review]
