### PR TITLE
fix: validate rhs of `in` when transpiling `#p in C`

### LINKED ISSUE #15013: [Bug]: `in` operator with non-object in private static fields
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
class C { static #x = #x in 0 } ;
```

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

The input program is expected to throw `TypeError` but the transpiled program terminates without any error.
```console
❯ node
Welcome to Node.js v18.10.0.
Type ".help" for more information.
> class C { static #x = #x in 0 } ;
Uncaught TypeError: Cannot use 'in' operator to search for '#x' in 0
    at <static_initializer> (REPL1:1:26)
```

### Environment

[Reproductions on Babel's own REPL](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=MYGwhgzhAEDC0G9oQC5hQS2NAxAD2gF5cCMA7aABmgF9oBuIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=true&targets=&version=7.19.3&externalPlugins=&assumptions=%7B%7D)

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #15013 
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

Per [RS 13.10.1](https://tc39.es/ecma262/#sec-relational-operators-runtime-semantics-evaluation), we should check the RHS `C` of a private-in expression `#p in C` before the brand check. In this PR we emit a `checkInRHS` call for this purpose.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15133"></a>

### CODE REVIEW

File: packages/babel-plugin-proposal-decorators/test/fixtures/2022-03-classes--to-es2015/replacement-static-installed-on-correct-class/output.js [hunk 1]
```diff
@@ -8,8 +8,8 @@ new (_x = /*#__PURE__*/new WeakMap(), _m = /*#__PURE__*/new WeakSet(), (_temp =
       writable: true,
       value: void 0
     }), babelHelpers.defineProperty(this, "x", void 0)), (() => {
-      hasX = o => _x.has(o);
-      hasM = o => _m.has(o);
+      hasX = o => _x.has(babelHelpers.checkInRHS(o));
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-proposal-decorators/test/fixtures/2022-03-classes--to-es2015/replacement-static-installed-on-correct-class/output.js:11]: Could we move the `.has` call to the helper, and just transform `#x in o` to `babelHelpers.privateHas(_x, o)`?

Comment (JLHwung) [reply packages/babel-plugin-proposal-decorators/test/fixtures/2022-03-classes--to-es2015/replacement-static-installed-on-correct-class/output.js:11]: I lean to a new assumption `inRHSIsObject` to skip the check. Otherwise we have to come up with at least three helpers:

- staticPrivateHas for `static #p = #p in C`
- privateHas for `#p = #p in this`
- privateAsPropertiesHas for `#p = #p in this`

And we can implement the `checkInRHS` helper as 
```js
function checkInRHS(v) {
  0 in v
}
```
so that the engine will do the checking job for us.

File: packages/babel-helpers/src/helpers-generated.ts [hunk 2]
```diff
@@ -43,7 +43,7 @@ export default Object.freeze({
   ),
   checkInRHS: helper(
     "7.20.1",
-    'export default function _checkInRHS(value){var type=typeof value;if("object"!==type&&"function"!==type)throw TypeError("right-hand side of \'in\' should be an object, got "+type);return value}',
+    "export default function _checkInRHS(value){return value}",
```
Comment (JLHwung) [inline packages/babel-helpers/src/helpers-generated.ts:46]: This seems to be a minifier bug, I will investigage.

File: packages/babel-plugin-proposal-decorators/test/fixtures/2022-03-classes--to-es2015/replacement-static-installed-on-correct-class/output.js (hunk 1 above)
Comment (nicolo-ribaudo) [reply packages/babel-plugin-proposal-decorators/test/fixtures/2022-03-classes--to-es2015/replacement-static-installed-on-correct-class/output.js:11]: Actually, we can't because `0 in v` is observable when using proxies.

File: packages/babel-plugin-proposal-private-property-in-object/test/fixtures/assumption-privateFieldsAsProperties/rhs-not-object/exec.js [hunk 3]
```diff
@@ -1,27 +1,27 @@
-expect(() => class { static #p = #p in 0 }).toThrowError(`right-hand side of 'in' should be an object, got number`);
-expect(() => class { static #p = #p in "" }).toThrowError(`right-hand side of 'in' should be an object, got string`);
-expect(() => class { static #p = #p in true }).toThrowError(`right-hand side of 'in' should be an object, got boolean`);
-expect(() => class { static #p = #p in void 0 }).toThrowError(`right-hand side of 'in' should be an object, got undefined`);
-expect(() => class { static #p = #p in Symbol.iterator }).toThrowError(`right-hand side of 'in' should be an object, got symbol`);
-expect(() => class { static #p = #p in 0n }).toThrowError(`right-hand side of 'in' should be an object, got bigint`);
+expect(() => class { static #p = #p in 0 }).toThrowError("Cannot use 'in' operator to search for '0'");
```
Comment (JLHwung) [inline packages/babel-plugin-proposal-private-property-in-object/test/fixtures/assumption-privateFieldsAsProperties/rhs-not-object/exec.js:1]: The error message could be confusing since '0' is in the checkInRHS helper. However, in Firefox, this will throw the previous error exactly: "right-hand side of 'in' should be an object, got number".

File: packages/babel-helpers/src/helpers/checkInRHS.js [hunk 4]
```diff
@@ -0,0 +1,9 @@
+/* @minVersion 7.20.1 */
+
+export default function _checkInRHS(value) {
+  var type = typeof value;
+  if (type !== "object" && type !== "function") {
```
Comment (nicolo-ribaudo) [inline packages/babel-helpers/src/helpers/checkInRHS.js:5]:
```suggestion
  if (Object(value) !== value) {
```

This is a bit shorter.

**Review by nicolo-ribaudo — APPROVED** [review]

File: packages/babel-helpers/src/helpers/checkInRHS.js [hunk 5]
```diff
@@ -0,0 +1,9 @@
...
+    throw TypeError("right-hand side of 'in' should be an object, got " + type);
+  }
```
Comment (nicolo-ribaudo) [inline packages/babel-helpers/src/helpers/checkInRHS.js:7]:
```suggestion
  if (Object(value) !== value) {
    throw TypeError("right-hand side of 'in' should be an object, got " + typeof type);
```

This is a bit shorter.

File: packages/babel-helper-create-class-features-plugin/src/fields.ts [hunk 6]
```diff
@@ -206,12 +206,30 @@ function unshadow(
...
+export function buildCheckInRHS(
+  rhs: t.Expression,
+  file: File,
+  inRHSIsObject?: boolean,
+) {
+  let helperRef;
+  try {
+    helperRef = file.addHelper("checkInRHS");
+  } catch (err) {
+    if (err.code !== "BABEL_HELPER_UNKNOWN") {
```
Comment (nicolo-ribaudo) [inline packages/babel-helper-create-class-features-plugin/src/fields.ts:218]: Can we use `availableHelper`?

```js
if (inRHSIsObject || !file.availableHelper?.("checkInRHS")) return rhs;
return t.callExpression(file.addHelper("checkInRHS"), [rhs]);
```

this also avoids injecting the helper when `inRHSIsObject` is false.

**Review by liuxingbaoyu — APPROVED** [review]

**Review by nicolo-ribaudo — APPROVED** [review]
