### PR TITLE
fix: register inserted class declaration

### LINKED ISSUE #10264: How to resolve the warning when use @babel/plugin-transform-typescript to compile typescript
Hi,
When I use `@babel/plugin-transform-typescript` to compile typescript, the warning happens
```
This problem is likely caused by another plugin injecting
"_class" without registering it in the scope tracker. If you are the author
 of that plugin, please use "scope.registerDeclaration(declarationPath)".
The exported identifier "_class" is not declared in Babel's scope tracker
as a JavaScript value binding, and "@babel/plugin-transform-typescript"
never encountered it as a TypeScript type declaration.
It will be treated as a JavaScript value.
```
I cannot find out why.

Here is my `babel.config.js`
```
module.exports = {
    presets: ['@babel/preset-typescript', '@babel/preset-react', '@babel/preset-env', 'mobx'],
    plugins: [
        ['@babel/plugin-transform-typescript', { allowNamespaces: true }],
        // Stage 0
        '@babel/plugin-proposal-function-bind',

        // Stage 1
        '@babel/plugin-proposal-export-default-from',
        '@babel/plugin-proposal-logical-assignment-operators',
        ['@babel/plugin-proposal-optional-chaining', { loose: false }],
        ['@babel/plugin-proposal-pipeline-operator', { proposal: 'minimal' }],
        ['@babel/plugin-proposal-nullish-coalescing-operator', { loose: false }],
        '@babel/plugin-proposal-do-expressions',

        // Stage 2
        ['@babel/plugin-proposal-decorators', { legacy: true }],
        '@babel/plugin-proposal-function-sent',
        '@babel/plugin-proposal-export-namespace-from',
        // '@babel/plugin-proposal-numeric-separator',
        '@babel/plugin-proposal-throw-expressions',
        '@babel/plugin-proposal-object-rest-spread',

        // Stage 3
        '@babel/plugin-syntax-dynamic-import',
        '@babel/plugin-syntax-import-meta',
        ['@babel/plugin-proposal-class-properties', { loose: true }],
        // '@babel/plugin-proposal-json-strings',

        // Other
        '@babel/plugin-transform-runtime',
        '@babel/plugin-transform-modules-commonjs',
        'jsx-control-statements'
    ]
}
```
And part of my `webpack.config.js`
```
module.exports = {
    // ...
    resolve: {
        // Add '.ts' and '.tsx' as resolvable extensions.
        extensions: ['.js', '.ts', '.tsx']
    },

    module: {
        rules: [
            {
                test: /\.[tj]sx?$/,
                loader: 'babel-loader',
            },
        ]
    }
};
```
And the program works OK. When I use `ts-loader` instead, it's OK too.

Can you help me? Thanks.

### PR DESCRIPTION
**Pull request by thiagoarrais**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #10264
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  | No
| License                  | MIT

This fixes the warning generated by `transform-typescript` regarding the class declaration created by `proposal-decorators` by registering the class in scope.

Related: #10172

### CODE REVIEW

File: packages/babel-plugin-proposal-decorators/src/transformer-legacy.js [hunk 1]
```diff
@@ -237,15 +237,18 @@ export default {
 
     const replacement = decoratedClassToExpression(decl);
     if (replacement) {
-      path.replaceWithMultiple([
-        replacement,
+      path.replaceWith(replacement);
+      path.insertAfter(
```
Comment (JLHwung) [inline packages/babel-plugin-proposal-decorators/src/transformer-legacy.js]: The injected `_class` is a VariableDeclaration comes from `decoratedClassToExpression` when `decl.node.id` is empty. I think it suffices to register the VariableDeclaration instead of the ExportDeclaration.
```js
const [VariableDeclaration] = path.replaceWithMultiple(/* replacement */);
if (!decl.node.id) {
  path.scope.registerDeclaration(VariableDeclaration);
}
```

By the way `path.replaceWith` + `path.insertAfter` is more expensive than `path.replaceWithMultiple`.

File: packages/babel-plugin-proposal-decorators/test/fixtures/legacy-decl-to-expression/method-decorators/output.mjs [hunk 2]
```diff
@@ -2,12 +2,12 @@ var _class, _class2;
 
 function _applyDecoratedDescriptor(target, property, decorators, descriptor, context) { var desc = {}; Object.keys(descriptor).forEach(function (key) { desc[key] = descriptor[key]; }); desc.enumerable = !!desc.enumerable; desc.configurable = !!desc.configurable; if ('value' in desc || desc.initializer) { desc.writable = true; } desc = decorators.slice().reverse().reduce(function (desc, decorator) { return decorator(target, property, desc) || desc; }, desc); if (context && desc.initializer !== void 0) { desc.value = desc.initializer ? desc.initializer.call(context) : void 0; desc.initializer = undefined; } if (desc.initializer === void 0) { Object.defineProperty(target, property, desc); desc = null; } return desc; }
 
-let A = (_class2 = class A {
+let A = (_class = class A {
```
Comment (JLHwung) [inline packages/babel-plugin-proposal-decorators/test/fixtures/legacy-decl-to-expression/method-decorators/output.mjs]: I don't think the fixture will need update once we register variable declaration instead of export declaration.

File: packages/babel-plugin-proposal-decorators/src/transformer-legacy.js (hunk 1 above)
Comment (thiagoarrais) [reply packages/babel-plugin-proposal-decorators/src/transformer-legacy.js]: Thanks. Didn't realize `replaceWithMultiple` returned stuff.

File: packages/babel-plugin-proposal-decorators/test/fixtures/legacy-decl-to-expression/method-decorators/output.mjs (hunk 2 above)
Comment (thiagoarrais) [reply packages/babel-plugin-proposal-decorators/test/fixtures/legacy-decl-to-expression/method-decorators/output.mjs]: Unfortunately we do.

File: packages/babel-plugin-proposal-decorators/src/transformer-legacy.js (hunk 1 above)
Comment (thiagoarrais) [reply packages/babel-plugin-proposal-decorators/src/transformer-legacy.js]: Done in 1a770d7

**Comment by keyz** [comment]
Would love to see a release being cut for this (@babel/plugin-proposal-decorators).
