### PR TITLE
 Do not unpack array patterns that update a referenced binding

### LINKED ISSUE #8528: Breaks the swapping of variable values using array destructuring.
## Bug Report

**Current Behavior**
Babel breaks the swapping of two variable values using array destructuring. This only seems to happen if the two values to be swapped are also function arguments.

**Input Code**
Correct Behaviour: [REPL version 7.0.0-beta.39](https://babeljs.io/en/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABDAzgIQKZQO4Y2ACgA8AaRAQzICMBKRAbwChFlhEDzEA-RWxAbUq8AuogC8AqmXLCA3M0QAnLCEVIi3CogBk2xBoA8veQF9GQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.0.0-beta.39&envVersion=7.0.0-beta.39)

Incorrect Behaviour: [REPL version 7.0.0-rc.2](https://babeljs.io/repl/build/master#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABDAzgIQKZQO4Y2ACgA8AaRAQzICMBKRAbwChFlhEDzEA-RWxAbUq8AuogC8AqmXLCA3M0QAnLCEVIi3CogBk2xBoA8veQF8gA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.0.0-rc.2&envVersion=7.0.0-rc.2)

```js
function isBetween(x, a, b) {
  if (a > b) [a, b] = [b, a];
  return x > a && x < b;
}
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  presets: [['@babel/preset-env', {
    targets: {browsers: ['> 1%', 'not ie <= 11', 'not ios < 10']},
    modules: false,
    useBuiltIns: false,
    loose: true
  }]]
};
```

**Environment**
- Babel version: v7.0.0-rc.2
- Node/npm version: Node 8/npm 5

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #8528 
| Patch: Bug Fix?          | yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

> Do not unpack array patterns that update a referenced binding
>
> We used this.scope.traverse to check if the array initializer referenced
> a binding which is present in the array pattern. It doesn't work because,
> in order to check if an identifier is a reference, we need to check its
> parent.
> this.scope.binding can't set the correct `parentPath`, because the only
> path that it knows is the root scope's (e.g. the function path).
> Use `t.traverse` which gives the correct parent.

This regression has been brought to the surface by 29d249e3b700e9bff9d3b6e47f7a8ba9c69612cc because it made the `isReferenced` check stricter, but it is unrelated.

### CODE REVIEW

File: packages/babel-plugin-transform-destructuring/src/index.js [hunk 1]
```diff
@@ -44,13 +44,16 @@ export default declare((api, options) => {
...
-    },
+  // NOTE: This visitor is meant to be used via t.traverseFast
+  const arrayUnpackVisitor = (node, state, parent) => {
+    if (
+      t.isIdentifier(node) &&
+      t.isReferenced(node, parent) &&
+      state.bindings[node.name]
+    ) {
+      state.deopt = true;
+      return true;
```
Comment (loganfsmyth) [inline packages/babel-plugin-transform-destructuring/src/index.js]: I'm not a huge fan of `return true` in traversal-like APIs because it's not clear if the behavior is `.skip()`-like or `.stop()`-like.

My preference would probably be for it to either:
* Explicitly return a STOP constant
* Skip the return value and throw an exception instead, e.g.
```
const STOP = {};
// ...
throw STOP;
```
and do
```
try {
  t.traverseFast(arr, arrayUnpackVisitor, state);
} catch (err) {
  if (err !== STOP) throw err;
}
```

**Comment by JSteunou** [comment]
Any step missing for this PR to be accepted?
