### PR TITLE
fix: `loc.index` of some nodes is wrongly enumerable.

### LINKED ISSUE #14590: [Bug]: parser(ts), ast, TSTypePredicate and TSEnumDeclaration returns additional index property in loc.start
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```ts
export declare const enum Foo {
    foo = 1,
    bar
}
```
```ts
export declare enum Foo {
    foo = 1,
    bar
}
```
```ts
class AssertsFoo {
  isBar(): asserts this is string {
    return;
  }
  isBaz = (): asserts this is string => {
    return;
  }
}
```

### Configuration file name

_No response_

### Configuration

```ts
  require('@babel/parser').parse(text, {
    sourceType: 'unambiguous',
    allowImportExportEverywhere: true,
    allowReturnOutsideFunction: true,
    ranges: true,
    plugins: [
      [ 'estree', { classFeatures: true }, ],
      'decorators-legacy',
      'classStaticBlock',
      'importAssertions',
      'typescript',
    ],
  });
```

### Current and expected behavior

"index" property is added to loc.start of `TSTypePredicate` and `TSEnumDeclaration`

this property is present only on those 2 nodes and it's with us since version 7.17.x

```diff
{
  "end": { "column": 1, "line": 4 },
- "start": { "column": 7, "index": 7, "line": 1 }
+ "start": { "column": 7, "line": 1 }
}
```

### Environment

- Babel: 7.18.2 

### Possible solution

_No response_

### Additional context

https://github.com/typescript-eslint/typescript-eslint/blob/1fb31a4b3e05734f801ade0450fea33494e4d5e6/packages/typescript-estree/tests/ast-alignment/utils.ts#L284-L297

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #14590  
| Patch: Bug Fix?          |√
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | √
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14595"></a>

### CODE REVIEW

File: packages/babel-helper-check-duplicate-nodes/src/index.ts [hunk 1]
```diff
@@ -42,7 +42,7 @@ export default function checkDuplicateNodes(ast) {
         for (const child of subNode) {
           stack.push({ node: child, parent: node });
         }
-      } else {
+      } else if (typeof subNode === "object" && subNode !== null) {
         stack.push({ node: subNode, parent: node });
       }
     }
```
Comment (liuxingbaoyu) [inline packages/babel-helper-check-duplicate-nodes/src/index.ts:48]: Here's a small change for performance.

**Comment by liuxingbaoyu** [comment]
There is a small change for performance in `packages/babel-helper-check-duplicate-nodes/src/index.ts`.

**Review by nicolo-ribaudo — APPROVED** [review]
Thanks for the test update!

**Review by JLHwung — APPROVED** [review]
