### PR TITLE
Prevent ignored files in out dir

### LINKED ISSUE #6226: copy-files flag does not respect ignore block in .babelrc
**Bug:** If in your build script, you have `--copy-files` passed, files that are ignored in .babelrc files will be copied over, instead of being ignored.

### Input Code
```js
babel src --out-dir lib --copy-files
```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    "es2015",
    "stage-1",
    "react"
  ],
  "ignore": [
    "**__mocks__/*.js"
  ]
}
```

### Expected Behavior
Babel should not copy files that are explicitly ignored in `.babelrc` configuration. In this case, babel should not transpile or copy Jest mocks.

### Current Behavior
Babel copies files that are ignored are explicitly `.babelrc`.
```sh
> npm run build 
> babel src --out-dir lib --copy-files
  src/api/__mocks__/index.js -> lib/api/__mocks__/index.js
  src/api/endpoints.js -> lib/api/endpoints.js
```
If you pass an `--ignore` flag (with the same blob) _after_ the `--copy-files` flag, it will behave as expected.
```sh
> npm run build;
> babel src --out-dir lib --copy-files --ignore **__mocks__/*.js
  src/api/endpoints.js -> lib/api/endpoints.js
  (output does not include ignored directories)
```

### Context
This issue comes up when you work with Jest manual mocks inside of your source directory. Jest warns that you have duplicate __mocks__ directories.

| software         | version(s)
| ---------------- | -------
| Babel            |  6.26.0
| node             | 6.9.2
| npm              | 5.4.0
| Operating System | OSX El Capitan

### LINKED ISSUE #10829: '--ignore' conflicts with  '--copy-files'
## Bug Report

**Current Behavior**
cli option '--copy-files' copies all non-compiled files, including ignored files

**Input Code**
- Not behave as what i expect
```json
// package.json
{
  "scripts": {
     "build": "babel src --out-dir dist --copy-files --ignore src/**/*.test.js  --presets=@babel/env"
  }
}
```
run in terminal
```bash
$ npm run build
```

**Expected behavior/code**
'--copy-files' copies all non-compiled files, and skip ignored files

**Environment**

- Babel version(s): [v7.7.4]
- Node/npm version: [ Node v12.13]
- OS: [OSX 10.15.1,]
-  How you are using Babel: [`cli`]

### PR DESCRIPTION
**Pull request by rajasekarm**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #6226
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

--ignore folder should not be present in out dir.

### CODE REVIEW

**Comment by JLHwung** [comment]
C.f. https://github.com/babel/babel/issues/10829#issuecomment-562614238
> but what if i try to copy the ignored files after this issue fixed?

I am afraid people could rely on this behaviour to copy ignored files. Since `--copy-files` is meant to copy files that _will not_ be compiled and the ignored files meets the definition.

I propose to add an `includeIgnoredFiles` cli option so people can configure the behaviour.

**Comment by rajasekarm** [comment]
That can be done, But I assume it should copy only the non supported format files and not the ignored one. Example css is non supported format, can be copied and required for the app to run. Test files are ignored and not copied and not required for the app to run.

**Comment by JLHwung** [comment]
@rajasekarm Given the behaviour has been existed since v7, I would prefer we add this behind a flag. And later we can change the defaults in v8, so that practically it will skip the `ignore` files when `--copy-files` is enabled.

**Comment by rajasekarm** [comment]
Sure, I'll make the change. Thanks for your input @JLHwung.

**Comment by rajasekarm** [comment]
@JLHwung Added the flag, I named it as **includeIgnore**.

File: packages/babel-cli/src/babel/options.js [hunk 1]
```diff
@@ -161,6 +161,11 @@ commander.option(
   "Delete the out directory before compilation.",
 );
 
+commander.option(
+  "--include-ignore",
+  "Include ignored files when compiling and copy to destination",
```
Comment (rajasekarm) [inline packages/babel-cli/src/babel/options.js]: Do we need to rephrase this help text?

File: packages/babel-cli/src/babel/options.js [hunk 2]
```diff
@@ -161,6 +161,11 @@ commander.option(
   "Delete the out directory before compilation.",
 );
 
+commander.option(
+  "--include-ignore",
+  "Copy the ignored files to destination",
```
Comment (existentialism) [inline packages/babel-cli/src/babel/options.js]: To match to `--include-dotfiles`,

```suggestion
  "Include ignored files when compiling and copying non-compilable files.",
```

File: packages/babel-cli/src/babel/options.js [hunk 3]
```diff
@@ -161,6 +161,11 @@ commander.option(
   "Delete the out directory before compilation.",
 );
 
+commander.option(
+  "--include-ignore",
+  "Include ignored files when compiling and copying non-compilable files.",
```
Comment (JLHwung) [inline packages/babel-cli/src/babel/options.js]: 🤔I don't think ignored file will be compiled when `--include-ignore` is true, it is different than `--include-dotfiles`.

Personally I prefer `--include-ignored` than `--include-ignore` because `ignore` is a verb.

Comment (existentialism) [reply packages/babel-cli/src/babel/options.js]: Yeah, we can drop the compiling bit.

Comment (rajasekarm) [reply packages/babel-cli/src/babel/options.js]: @JLHwung , I'll make the the change for the flag. Is the below text ok for you? Just want to confirm before pushing the change.

Include ignored files and copying non-compilable files.

Comment (JLHwung) [reply packages/babel-cli/src/babel/options.js]: I feel like it is

> Include ignored files when copying non-compilable files.

Comment (rajasekarm) [reply packages/babel-cli/src/babel/options.js]: @JLHwung Done ✅
