### PR TITLE
Fix eslint package types

### LINKED ISSUE #17821: [@babel/eslint-parser@8.0.0-rc.2] Broken Types
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/eslint-parser

### Input code

```ts
import * as babelParser from "@babel/eslint-parser";
```

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

The `package.json` file contains mistakes with regards to the types -> it shouldn't.

### Environment

```sh
System:
    OS: Linux 6.18 Nobara Linux 43 (KDE Plasma Desktop Edition)
  Binaries:
    Node: 24.13.1 - /home/rebec/.nvm/versions/node/v24.13.1/bin/node
    npm: 11.10.0 - /home/rebec/dev/eslint-plugin-functional/node_modules/.bin/npm
    pnpm: 10.30.1 - /home/rebec/.nvm/versions/node/v22.15.0/bin/pnpm
  npmPackages:
    @babel/eslint-parser: 8.0.0-rc.2 => 8.0.0-rc.2 
    eslint: 10.0.1 => 10.0.1 
    rollup: 4.58.0 => 4.58.0 
```

### Possible solution

Current `package.json` contains:

```json
"types": "./types.d.ts",
"exports": {
  ".": {
    "default": "./lib/index.js",
    "types": "./types.d.ts"
  },
  "./package.json": "./package.json"
},
```

But it should be:

```json
"types": "./types.d.cts",
"exports": {
  ".": {
    "types": "./types.d.cts",
    "default": "./lib/index.js"
  },
  "./package.json": "./package.json"
}
```

The difference being the filename of the types file (the file that exists ends with `.d.cts`, not `.d.ts`) and that the `default` property needs to be declared last.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #17821 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

File: scripts/publint.ts [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+
+for (const path of paths) {
+  const data = JSON.parse(readFileSync(path, "utf-8"));
+  if (data.private) continue;
+  const result = await publint({
+    pkgDir: dirname(path),
+    pack: "yarn",
+  });
+  for (const message of result.messages) {
+    if (message.type === "error") {
```
Comment (JLHwung) [inline scripts/publint.ts:32]: Can we output error to `stderr` if there is an error message?

**Comment by liuxingbaoyu** [comment]
CI failures are expected. we need to remove the failed CIs or retain the compatible exports.

**Comment by liuxingbaoyu** [comment]
This check is currently checking the local repository. The CI failed because I removed https://github.com/babel/babel/pull/17822/changes#diff-6a9f4fa54adb5d9a89a76a35a55ccbb649bec45ee9a74b91d39d9d1d52415eacL127-L128.

**Comment by nicolo-ribaudo** [comment]
Oh I see, so after merging it should pass?

**Comment by liuxingbaoyu** [comment]
https://github.com/babel/babel/actions/runs/22495530191/job/65168898709?pr=17822
The newly added CI has been passed. :)
The failed CI was for older versions of Node.js. Since we removed the compatibility export (https://github.com/babel/babel/pull/17822/changes#diff-6a9f4fa54adb5d9a89a76a35a55ccbb649bec45ee9a74b91d39d9d1d52415eacL127-L128), we need to remove the CI or restore the compatibility export.

**Comment by nicolo-ribaudo** [comment]
Could you take a look at the CI failures?

**Comment by liuxingbaoyu** [comment]
Do you want to remove these failing CIs (nodejs < v17) or restore compatibility?
I'm hesitant.

**Comment by nicolo-ribaudo** [comment]
I think `@babel/runtime` should preserve old Node.js compat, so that people can use Babel 8 when _targeting_ old Node.js versions.

**Comment by liuxingbaoyu** [comment]
I will revert that change.
Also, the current `engines` of `babel-runtime` are `^20.19.0 || >=22.12.0`, do we need to change it?

**Comment by JLHwung** [comment]
> I will revert that change. Also, the current `engines` of `babel-runtime` are `^20.19.0 || >=22.12.0`, do we need to change it?

The current Babel-runtime 7 sets `engines` to `>= 6.9.0`. It seems that the `engines` setting here is unnecessary. The runtime is supposed to be run on any ES5 environments.

**Comment by nicolo-ribaudo** [comment]
I'll merge this and prepare a PR for that.
