### PR TITLE
fix: Identifiers in the loop are not renamed

### LINKED ISSUE #15308: [Bug]: transform error when use two loops in one function with @babel/plugin-transform-block-scoping@7.20.9
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```
const test = (data) => {
  for (let i = 0; i < data.length; i++) {
    const x = data[i];
    data.find((item) => item === x);
  }
  for (let i = 0; i < data.length; i++) {
    const x = data[i];
    data.find((item) => item === x);
  }
}
```

### Configuration file name

.babelrc

### Configuration

{
  "presets": [
    "@babel/preset-env"
  ]
}

### Current and expected behavior

current output:
```
"use strict";

var test = function test(data) {
  var _loop = function _loop() {
    var x = data[i];
    data.find(function (item) {
      return item === x;
    });
  };
  for (var i = 0; i < data.length; i++) {
    _loop();
  }
  var _loop2 = function _loop2() {
    var x = data[i];
    data.find(function (item) {
      return item === x;
    });
  };
  for (var _i = 0; _i < data.length; _i++) {
    _loop2();
  }
};
```

the second `var x = data[i];` should be `var x = data[_i];`

### Environment

  System:
    OS: macOS 12.6.2
  Binaries:
    Node: 14.19.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.16 - /usr/local/bin/npm
  npmPackages:
    @babel/cli: ^7.17.6 => 7.17.6 
    @babel/core: ^7.20.7 => 7.20.7 
    @babel/node: ^7.16.8 => 7.16.8 
    @babel/plugin-transform-block-scoping: ^7.20.9 => 7.20.9 
    @babel/preset-env: ^7.16.11 => 7.16.11 

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #15308 
| Patch: Bug Fix?          | √
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | √
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

After I tried some wrong methods, I found out that it is so simple. 😅

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15361"></a>

### CODE REVIEW

File: packages/babel-plugin-transform-block-scoping/test/fixtures/regression/rename-with-other-plugins/input.ts [hunk 1]
```diff
@@ -0,0 +1,15 @@
+// `index` will be registered into `scope.globals`
+type SomeLookup = {
+  [index: number]: any[];
+};
```
Comment (liuxingbaoyu) [inline packages/babel-plugin-transform-block-scoping/test/fixtures/regression/rename-with-other-plugins/input.ts:4]: I don't think this test is very good, but I don't know how to make it better.
Because after we change `traverse` it will not be registered in `globals`.

File: packages/babel-plugin-transform-block-scoping/src/index.ts [hunk 2]
```diff
@@ -84,10 +84,22 @@ export default declare((api, opts: Options) => {
...
+              }
+
               if (capturedInClosure) {
                 markNeedsBodyWrap();
                 captured.push(name);
-              } else if (headScope.parent.hasBinding(name)) {
+              } else if (
+                headScope.parent.hasBinding(name) ||
+                blockScope.parent.hasGlobal(name) ||
+                (isProgramScope && varScope.hasGlobal(name))
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-block-scoping/src/index.ts:101]: Since `hasGlobal` checks across all the parent scope, when can it happen that `blockScope.parent.hasGlobal(name)` is false but `isProgramScope && varScope.hasGlobal(name)` is true?

Comment (liuxingbaoyu) [reply packages/babel-plugin-transform-block-scoping/src/index.ts:101]: I'm not sure, I actually copy-pasted it from here. 🤦‍♂️
Because I found the easiest way is to rename this identifier before `wrapLoopBody`.

https://github.com/babel/babel/blob/112169cc94f70fff6b0fc7641e69be8076dbc90a/packages/babel-plugin-transform-block-scoping/src/index.ts#L213-L231

Comment (nicolo-ribaudo) [reply packages/babel-plugin-transform-block-scoping/src/index.ts:101]: Whops :sweat_smile: 
It looks like deleting the `isProgramScope && varScope.hasGlobal(name)` check also from that code still makes all the tests pass.

File: packages/babel-plugin-transform-block-scoping/src/index.ts [hunk 3]
```diff
@@ -216,10 +207,8 @@ function transformBlockScopedVariable(
 
   const blockScope = path.scope;
   let varScope = blockScope.getFunctionParent();
-  let isProgramScope = false;
   if (!varScope) {
     varScope = blockScope.getProgramParent();
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-block-scoping/src/index.ts:211]:
```js
const varScope = blockScope.getFunctionParent() || blockScope.getProgramParent();
```

File: packages/babel-plugin-transform-block-scoping/test/fixtures/regression/rename-with-other-plugins/input.ts (hunk 1 above)
Comment (nicolo-ribaudo) [reply packages/babel-plugin-transform-block-scoping/test/fixtures/regression/rename-with-other-plugins/input.ts]: @liuxingbaoyu Don't forget about this!

**Review by nicolo-ribaudo — APPROVED** [review]

**Review by JLHwung — APPROVED** [review]
