### PR TITLE
fix: allow shebang directive

### LINKED ISSUE #9921: Flow with shebang doesn't work in @babel/parser 7.4.4
## Bug Report

**Current Behavior**
We have some JS scripts with Node.js shebang and Flow which works correctly. However, we are getting a transpilation error starting with `@babel/parser` version `7.4.4`:

```text
💃 babel-playground ./node_modules/.bin/babel src --out-dir lib
{ SyntaxError: /Users/mrtnzlml/Work/mrtnzlml/babel-playground/src/index.js: Unexpected token (5:9)

  3 | // @flow strict-local
  4 | 
> 5 | new Set<() => void>([]);
    |          ^
  6 | 
    at Object.raise (/Users/mrtnzlml/Work/mrtnzlml/babel-playground/node_modules/@babel/parser/lib/index.js:6322:17)
    at Object.unexpected (/Users/mrtnzlml/Work/mrtnzlml/babel-playground/node_modules/@babel/parser/lib/index.js:7638:16)
    at Object.parseParenAndDistinguishExpression (/Users/mrtnzlml/Work/mrtnzlml/babel-playground/node_modules/@babel/parser/lib/index.js:8968:12)
    at Object.parseParenAndDistinguishExpression (/Users/mrtnzlml/Work/mrtnzlml/babel-playground/node_modules/@babel/parser/lib/index.js:2714:18)
    at Object.parseExprAtom (/Users/mrtnzlml/Work/mrtnzlml/babel-playground/node_modules/@babel/parser/lib/index.js:8731:21)
    at Object.parseExprSubscripts (/Users/mrtnzlml/Work/mrtnzlml/babel-playground/node_modules/@babel/parser/lib/index.js:8385:23)
    at Object.parseMaybeUnary (/Users/mrtnzlml/Work/mrtnzlml/babel-playground/node_modules/@babel/parser/lib/index.js:8365:21)
    at Object.parseExprOpBaseRightExpr (/Users/mrtnzlml/Work/mrtnzlml/babel-playground/node_modules/@babel/parser/lib/index.js:8325:34)
    at Object.parseExprOpRightExpr (/Users/mrtnzlml/Work/mrtnzlml/babel-playground/node_modules/@babel/parser/lib/index.js:8318:21)
    at Object.parseExprOp (/Users/mrtnzlml/Work/mrtnzlml/babel-playground/node_modules/@babel/parser/lib/index.js:8297:27)
  pos: 53,
  loc: Position { line: 5, column: 9 },
  code: 'BABEL_PARSE_ERROR' }
```

**Input Code**

[REPL link](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MQQg9ArgzgTmBGBLAdmApsgbgAmQewBM0AoYsMbAAQDMAbPAd2ygBcZEBjFgWno4ENapZGiYBlNCwA8ACgCU2ALwA-bJjyICymQG0AunIDcxIA&debug=true&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=flow%2Cenv&prettier=false&targets=&version=7.4.4&externalPlugins=)

```js
#!/usr/bin/env node

// @flow strict-local

new Set<() => void>([]);
```

**Expected behavior/code**
It should work just like in `@babel/parser` version 7.4.3 with no errors. Please note that this usage of Flow with shebang is valid - Flow works as expected (since shebang _MUST_ be the first line in the file).

**Babel Configuration (.babelrc, package.json, cli command)**

```js
module.exports = function(api) {
  api.assertVersion(7);
  api.cache.never();

  const presets = [];
  const plugins = ['@babel/plugin-transform-flow-strip-types'];

  return { presets, plugins };
};
```

**Environment**
- Babel version(s):

```json
{
  "dependencies": {
    "@babel/cli": "^7.4.4",
    "@babel/core": "^7.4.4",
    "@babel/plugin-transform-flow-strip-types": "^7.4.4"
  },
  "resolutions": {
    "//": "works with 7.4.3",
    "@babel/parser": "7.4.4"
  }
}
```

- Node/npm version: Node v11.14.0
- OS: OSX 10.14.4 (18E226)
- Monorepo: yes - Yarn Workspaces
- How you are using Babel: CLI

### PR DESCRIPTION
**Pull request by tanhauhau**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #9921
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

File: packages/babel-parser/src/plugins/flow.js [hunk 1]
```diff
@@ -96,7 +96,7 @@ export default (superClass: Class<Parser>): Class<Parser> =>
     }
 
     finishToken(type: TokenType, val: any): void {
-      if (!(type === tt.string || type === tt.semi)) {
+      if (![tt.string, tt.semi, tt.interpreterDirective].includes(type)) {
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/src/plugins/flow.js]: Since this code will be run a really high number of times, maybe it's better to avoid the array allocation and the `includes` call?

```suggestion
      if (type !== tt.string && type !==  tt.semi && type !== tt.interpreterDirective) {
```

Comment (loganfsmyth) [inline packages/babel-parser/src/plugins/flow.js]: I'd prefer that we stick with `===` since this function is called very often and making the temporary array and iterating could be slower.

**Comment by mrtnzlml** [comment]
Thank you very much for the fix. Can we expect it to be released in the next patch version?

**Comment by nicolo-ribaudo** [comment]
Yes!
