### PR TITLE
fix: workaround misleading node.js ENOENT error

### LINKED ISSUE #11130: @babel/register write cache fail in node:alpine docker container
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**
In `node:alpine` docker image. The folder `node_modules` create by root. And node server runs by 'node' user. So `node_modules` isn't writeable.

`cache.js` not handle `ENOENT` error. It just throw out and crash node server.

```
/home/node/app/node_modules/@babel/register/lib/cache.js:80
        throw e;
        ^

Error: ENOENT: no such file or directory, mkdir '/home/node/app/node_modules/.cache/@babel/register'
    at Object.mkdirSync (fs.js:856:3)
    at module.exports.sync (/home/node/app/node_modules/make-dir/index.js:97:6)
    at save (/home/node/app/node_modules/@babel/register/lib/cache.js:61:23)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/node/app/node_modules/.cache/@babel/register'
}
```

**Input Code**
- REPL or Repo link if applicable:

```js
var your => (code) => here;
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "your": { "config": "here" }
}
```

**Environment**

```

```
- Babel version(s): v7.8.3
- Node/npm version: Node v13.8.0/npm 6.13.6
- OS: Alpine Linux
- Monorepo: no
- How you are using Babel: `register`

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #11130 
| Patch: Bug Fix?          | Yes
| Tests Added + Pass?      | No test is added
| License                  | MIT

See https://github.com/babel/babel/issues/11130#issuecomment-589402519

### CODE REVIEW

File: packages/babel-register/src/cache.js [hunk 1]
```diff
@@ -43,6 +43,9 @@ export function save() {
     fs.writeFileSync(FILENAME, serialised);
   } catch (e) {
     switch (e.code) {
+      // workaround https://github.com/nodejs/node/issues/31481
+      // todo: remove the ENOENT error check when we drop node.js 13 support
+      case "ENOENT":
```
Comment (JLHwung) [inline packages/babel-register/src/cache.js]: Note that it's okay to place `ENOENT` here because `write(2)` will never throws `ENOENT`. http://man7.org/linux/man-pages/man2/write.2.html

So `ENOENT` must be thrown from `fs.mkdirSync(#, { recursive: true })`.
