### PR TITLE
Raise recoverable error for type members with invalid modifiers

### LINKED ISSUE #12767: babel-parser(ts): Weird AST  for interface property with modifiers when errorRecovery: true
## Bug Report

- [x] I would like to work on a fix!

**Current behavior**

Weird AST is returned with `errorRecovery: true`.

<details>
<div>

```json
{
  "type": "TSInterfaceDeclaration",
  "id": {
    "type": "Identifier",
    "name": "Foo"
  },
  "body": {
    "type": "TSInterfaceBody",
    "body": [
      {
        "type": "TSPropertySignature",
        "key": {
          "type": "Identifier",
          "name": "public"
        },
        "computed": false
      },
      {
        "type": "TSPropertySignature",
        "key": {
          "type": "Identifier",
          "name": "foo"
        },
        "computed": false,
        "typeAnnotation": {
          "type": "TSTypeAnnotation",
          "typeAnnotation": {
            "type": "TSStringKeyword"
          }
        }
      }
    ]
  }
}
```

</div>
</details>

- [REPL](https://babeljs.io/repl#?browsers=safari%2012&build=&builtIns=false&spec=false&loose=false&code_lz=JYOwLgpgTgZghgYwgAgGIHt3IN4ChnIAOArgEYA2wCyMmAXMgM5hSgDmA3LgL65A&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=typescript&prettier=false&targets=&version=7.12.14&externalPlugins=)

**Input Code**

```ts
interface Foo {
  public foo: string;
}
```

**Expected behavior**

Raise syntax error is thrown `'public' modifier cannot appear on a type member.` like [TS](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChkHIAOArgEYA2wCyMmAXMgM5hSgDmA3LgL65A).

And returns the AST like below ([same as typescript-estree](https://astexplorer.net/#/gist/86cc29ab782b4e0fc9bb02acaa636bf6/954d9211b866171ee38ba3aca16ed3b5589f749d)):

<details>
<div>

```json
{
  "type": "TSInterfaceDeclaration",
  "id": {
    "type": "Identifier",
    "name": "Foo"
  },
  "body": {
    "type": "TSInterfaceBody",
    "body": [
      {
        "type": "TSPropertySignature",
        "key": {
          "type": "Identifier",
          "name": "foo"
        },
        "computed": false,
        "typeAnnotation": {
          "type": "TSTypeAnnotation",
          "typeAnnotation": {
            "type": "TSStringKeyword"
          }
        },
        "accessibility": "public"
      }
    ]
  }
}
```

</div>
</details>

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
const code = `interface Foo {
    public foo: string;
  }`;
const result = parse(code, {
  sourceType: "module",
  errorRecovery: true,
  plugins: ["typescript"],
});
```

**Environment**

**Possible Solution**

**Additional context**

from https://github.com/prettier/prettier/pull/10252.
In previous version, `babel/parser` throw syntax error `SyntaxError: Unexpected token, expected ";"`.

### PR DESCRIPTION
**Pull request by sosukesuzuki**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            |  Fixes #12767
| Patch: Bug Fix?          | Y
| Tests Added + Pass?      | Yes
| License                  | MIT

### CODE REVIEW

File: packages/babel-parser/src/plugins/typescript/index.js [hunk 1]
```diff
@@ -573,16 +584,43 @@ export default (superClass: Class<Parser>): Class<Parser> =>
...
+        node,
+        [
+          "readonly",
+          "declare",
+          "abstract",
+          "private",
+          "protected",
+          "public",
+          "static",
+        ],
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/src/plugins/typescript/index.js:605]:
```suggestion
        ["readonly", ...denyModifiers],
```

so that the two lists don't get out of sync.

**Review by nicolo-ribaudo — COMMENTED** [review]
Is there a specific reason for ededec2? I actually preferred the previous version.

**Comment by sosukesuzuki** [comment]
> Is there a specific reason for ededec2? I actually preferred the previous version.

This is because `InvalidModifierOnTypeMember` may be  not the only error we want to raise in `tsParseModifiers`.

File: packages/babel-parser/src/plugins/typescript/index.js [hunk 2]
```diff
@@ -207,6 +210,7 @@ export default (superClass: Class<Parser>): Class<Parser> =>
         accessibility?: N.Accessibility,
       },
       allowedModifiers: TsModifier[],
+      callback?: (startPos: number, modifer: TsModifier) => void,
```
Comment (JLHwung) [inline packages/babel-parser/src/plugins/typescript/index.js:213]: Alternative interface design
```ts
tsParseModifiers(
      modified: {
        [key: TsModifier]: ?true,
        accessibility?: N.Accessibility,
      },
      allowedModifiers: TsModifier[],
      disallowedModifiers: TsModifier[],
      errorTemplate: string
): void
```
So we can raise errors when a disallowed modifier is seen and it can be reused in other situations. Introducing `callback` to parsers can be very nasty.

File: packages/babel-parser/src/plugins/typescript/index.js [hunk 3]
```diff
@@ -226,6 +231,14 @@ export default (superClass: Class<Parser>): Class<Parser> =>
           }
           modified[modifier] = true;
         }
+
+        if (
+          errorTemplate &&
+          disallowedModifiers &&
+          disallowedModifiers.includes(modifier)
+        ) {
+          this.raise(startPos, errorTemplate, modifier);
```
Comment (JLHwung) [inline packages/babel-parser/src/plugins/typescript/index.js:240]: nit: we can assume `errorTemplate` is non null if `disallowedModifiers` is provided. Overall this method not a public interface so we don't have to be defensive.

File: packages/babel-parser/src/plugins/typescript/index.js [hunk 4]
```diff
@@ -207,6 +210,8 @@ export default (superClass: Class<Parser>): Class<Parser> =>
         accessibility?: N.Accessibility,
       },
       allowedModifiers: TsModifier[],
+      disallowedModifiers?: TsModifier[],
+      errorTemplate?: string,
     ): void {
       for (;;) {
         const startPos = this.state.start;
```
Comment (JLHwung) [inline packages/babel-parser/src/plugins/typescript/index.js:217]: We can pass down `allowedModifiers.concat(disallowedModifier)` to `tsParserModifier` so we don't have to duplicate `disallowedModifier` in the `tsParseModifiers` call.

Comment (nicolo-ribaudo) [reply packages/babel-parser/src/plugins/typescript/index.js:217]: Nit: `allowedModifiers.concat(disallowedModifier ?? [])`

**Review by nicolo-ribaudo — APPROVED** [review]

File: packages/babel-parser/src/plugins/typescript/index.js [hunk 5]
```diff
@@ -231,8 +232,12 @@ export default (superClass: Class<Parser>): Class<Parser> =>
           modified[modifier] = true;
         }
 
-        if (callback) {
-          callback(startPos, modifier);
+        if (
+          errorTemplate &&
+          disallowedModifiers &&
+          disallowedModifiers.includes(modifier)
```
Comment (existentialism) [inline packages/babel-parser/src/plugins/typescript/index.js]:
```suggestion
          disallowedModifiers?.includes(modifier)
```

**Review by JLHwung — APPROVED** [review]
