### PR TITLE
Correctly transform spreads of arrays with holes

### LINKED ISSUE #8874: Hole array spread inside of another array isn't work correctly
## Bug Report

**Current Behavior**
If we spread an array with hole (`[1,, 2]` of `new Array(3)`, for example), the code generated from Babel don't convert the holes to `undefined`.

**Input Code**
Using babel, this code
```js
[1, ...[2,, 3]]
```

generates this:

```js
[1].concat([2,, 3]) // returns [1, 4, (empty), 3]
```

**Expected behavior/code**
```js
[1, ...[2,, 3]] // should returns [1, 2, undefined, 3]
```

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  plugins: ["@babel/plugin-transform-spread"]
}
```

**Environment**
- Babel version(s): lasted version from git
- Node/npm version: Node v9, NPM 5.6.0
- OS: macOS High Sierra
- Monorepo: yep
- How you are using Babel: CLI

**Additional context/Screenshots**
I found this bug when I'm doing this PR for fix a similar bug: https://github.com/babel/babel/pull/8872
This PR isn't fix this another bug.

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #8874, closes #9146
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

This is #9146 rebased. I couldn't push to the original PR because the fork has been deleted.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/13439"></a>

### CODE REVIEW

File: packages/babel-plugin-transform-spread/test/fixtures/spread/nested-array-with-hole/exec.js [hunk 1]
```diff
@@ -0,0 +1,2 @@
+let arr = ['a', ...['b',,'c']];
```
Comment (jridgewell) [inline packages/babel-plugin-transform-spread/test/fixtures/spread/nested-array-with-hole/exec.js:1]: What happens if this isn't statically analyzable?

File: packages/babel-plugin-transform-spread/src/index.js [hunk 2]
```diff
@@ -35,14 +39,23 @@ export default declare((api, options) => {
...
 
     for (const prop of props) {
       if (t.isSpreadElement(prop)) {
         _props = push(_props, nodes);
-        nodes.push(getSpreadLiteral(prop, scope));
+        let spreadLiteral = getSpreadLiteral(prop, scope);
+
+        if (t.isArrayExpression(spreadLiteral) && hasHole(spreadLiteral)) {
+          spreadLiteral = t.callExpression(
+            file.addHelper("arrayWithoutHoles"),
```
[the remark this answers is not in the document]
Comment (nicolo-ribaudo) [reply packages/babel-plugin-transform-spread/src/index.js:53]: `arrayLikeToArray` isn't available in every Babel 7 version, I went for the easy route. I'll add a switch to use `arrayLikeToArray` in Babel 8.

File: packages/babel-plugin-transform-spread/test/fixtures/spread/nested-array-with-hole/exec.js (hunk 1 above)
Comment (nicolo-ribaudo) [reply packages/babel-plugin-transform-spread/test/fixtures/spread/nested-array-with-hole/exec.js:1]: It uses `toConsumableArray(spreadArgument)`, which does all the necessary checks to ensure that it's correct. `arrayWithoutHoles` is part of those checks.

Comment (nicolo-ribaudo) [reply packages/babel-plugin-transform-spread/test/fixtures/spread/nested-array-with-hole/exec.js:1]: https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=DYUwLgBAhhC8EG0CMAaCA6TAPAukA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-0%2Cstage-2&prettier=false&targets=&version=7.14.4&externalPlugins=%40babel%2Fplugin-transform-typescript%407.14.4

**Review by jridgewell — APPROVED** [review]

**Review by fedeci — APPROVED** [review]
