### PR TITLE
Fix indentation when generating comments with `concise: true`

### LINKED ISSUE #16077: [Bug]: RangeError: Invalid string length
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/eslint-parser

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

RangeError: Invalid string length
    at Buffer._append (cc.proxy.js:29347:20)
    at Buffer.append (cc.proxy.js:29291:10)
    at Generator._append (cc.proxy.js:33671:15)
    at Generator._printComment (cc.proxy.js:34026:10)
    at Generator._printComments (cc.proxy.js:34073:16)
    at Generator.printInnerComments (cc.proxy.js:33936:10)
    at Generator._maybePrintInnerComments (cc.proxy.js:33924:38)
    at Generator.tokenChar (cc.proxy.js:33593:10)
    at Generator.rightBrace (cc.proxy.js:33550:10)
    at Generator.BlockStatement (cc.proxy.js:29563:8)

### Environment

System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD    
  npmPackages:
    @babel/generator: ^7.22.10 => 7.23.0
    @babel/parser: ^7.22.13 => 7.23.0
    webpack: ^5.88.2 => 5.88.2

### Possible solution

_No response_

### Additional context

I am parsing the input and then simply generating the code.
I observed that when i don't have `concise:true,` option in generator then i'm not seeing the error
```
let babelParserOption = {
        allowImportExportEverywhere: true,
        allowReturnOutsideFunction: true,
        allowAwaitOutsideFunction: true,
        allowUndeclaredExports:true,
        allowSuperOutsideMethod:true,
        attachComment :true,
        createParenthesizedExpressions: true,
        strictMode: false,
        sourceType:"unambiguous"
    }
    var ast = babelParser.parse(code, babelParserOption);    
    let babelgeneratorOptions = {
        compact: (options && options.compact) || false,
        concise:true,
        jsescOption : {
            quotes: 'single'
        }
    }
    //code generation
    let rewrittenCode = babelGenerator(ast, babelgeneratorOptions).code;
```

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #16077 
| Patch: Bug Fix?          | √
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | √
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

**Review by JLHwung — APPROVED** [review]

File: packages/babel-generator/test/fixtures/comments/concise-block-comment-indent/input.js [hunk 1]
```diff
@@ -0,0 +1,3 @@
+"1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111";/**
+            x
+*/
```
Comment (nicolo-ribaudo) [inline packages/babel-generator/test/fixtures/comments/concise-block-comment-indent/input.js:3]: Can you also add a case in which the comment should be indented? Like
```js
{
  "1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111";/**
              x
  */
}
```

**Review by nicolo-ribaudo — APPROVED** [review]
