### PR TITLE
Fix: fallback to typeof when toString is applied to incompatible object

### LINKED ISSUE #12609: _isNativeFunction(HTMLElement) throws an error in Firefox 31.
## Bug Report

- [x] I would like to work on a fix!

**Current behavior**

In Firefox 31.6.0 ESR, `_wrapNativeSuper` fails when called with `HTMLElement` (the error is thrown from `_isNativeFunction`). 

image
"TypeError: Function.prototype.toString called on incompatible object"

A simpler way to reproduce this is to run this in FF DevTools: `Function.toString.call(HTMLElement)`.
image

Repro:
Since FF 31 fails to load both the babel repl and codesandbox, the repro is two steps:
1. I generated the babel output with the babel REPL: [link](https://babel.dev/repl#?browsers=ff%2031&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEAqCmEAuDnXgDyfAdgExgAlYBZAGQFER4BbXJaAbwChppgB7HHeYbPAMJgQIAEZhgAa2gAKAJRMkACwCWEAHQru8AE7Fy0ALzQA5IXgiOJgNwBfZrevMA7lrwdn64AFdkHGlS09Bp48ABmWvAyJtjIALSxSCYANHCIKOly1kA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.12.12&externalPlugins=)
2. I pasted the output into JSBin (which still works with FF 31.6): [link](https://jsbin.com/hutewirebe/1/edit?js,output)

The code just subclasses `HTMLElement` to create a simple web component. Babel wraps `HTMLElement` with `_wrapNativeSuper` which in turn calls `_isNativeFunction`, which fails in FF 31.6.

**Input Code**

```js
class TestTest extends HTMLElement {
  connectedCallback () {this.innerHTML = 'Hello';}
};
window.customElements.define('test-test', TestTest);
```

**Expected behavior**
Expected no error in FF 31.6.

**Babel Configuration (codesandbox)**
Preset-env: `ff 31`

**Environment**

```

```
- Babel version(s): v7.12.12
- Node/npm version: n/a - codesandbox
- OS: n/a - codesandbox
- Monorepo: n/a - codesandbox
- How you are using Babel: n/a - codesandbox

**Possible Solution**
Wrap in a try/catch? Maybe call `fn.toString` directly?
```js
function _isNativeFunction(fn) {
  var s;
  try {s = Function.toString.call(fn)} catch(e){}
  try {s = fn.toString()} catch(e){}
  return s && s.indexOf("[native code]") !== -1;
}
```

**Additional context**
Given that Firefox 31 is six years old now, (2015), is this bug something that babel is willing to accept a fix for? If so, is the try/catch solution acceptable? (Class declarations typically aren't in hot code paths). Otherwise, what fix do you suggest?

Note: my method of running FF 31.6 involves running a docker image in ubuntu and mounting my X11 socket into the docker container. Let me know if you need help reproducing.

Thanks!

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #12609
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

Firefox 31 will throw when `toString` is applied to an HTMLElement. Here we handle the error as suggested in https://github.com/babel/babel/issues/12609#issuecomment-808823218.

### CODE REVIEW

**Review by liuxingbaoyu — APPROVED** [review]

File: packages/babel-helpers/src/helpers.ts [hunk 1]
```diff
@@ -314,7 +314,12 @@ helpers.construct = helper("7.0.0-beta.0")`
 helpers.isNativeFunction = helper("7.0.0-beta.0")`
   export default function _isNativeFunction(fn) {
     // Note: This function returns "true" for core-js functions.
-    return Function.toString.call(fn).indexOf("[native code]") !== -1;
+    try {
+      return Function.toString.call(fn).indexOf("[native code]") !== -1;
+    } catch (e) {
+      // Firefox 31 throws when "toString" is applied to an HTMLElement
+      return typeof fn === "function";
```
Comment (nicolo-ribaudo) [inline packages/babel-helpers/src/helpers.ts:321]: This is safe because on user-defined `Function.toString` never throws, right?

**Review by nicolo-ribaudo — APPROVED** [review]

File: packages/babel-helpers/src/helpers.ts (hunk 1 above)
Comment (JLHwung) [reply packages/babel-helpers/src/helpers.ts:321]: I think so, `Function.toString` will throw a type error if the input is neither object nor function, unless there are more browser quirks we are unaware of.

According to [this SO issue](https://stackoverflow.com/questions/8703208/htmlelement-tostring-only-works-in-chrome), `Function.toString` throws on HTMLElement because at that time they were not inherited from Object.
