### PR TITLE
Setup JSX runtime even if the file doesn't contain JSX

### LINKED ISSUE #12478: pass.get(...) is not a function in @babel/plugin-transform-react-jsx
## Bug Report

Hi there 👋  So from this morning around 08:30GMT we are seeing the following error when we try to compile our code with Rollup. Here is the stack trace that we are seeing.....

image

It looks to be able the same time you published an update to @babel/plugin-transform-react-jsx recently.

Here is the setup of Babel packages we are using.

```
"@babel/cli": "7.2.0",
"@babel/core": "7.2.0",
"@babel/eslint-parser": "^7.11.3",
"@babel/plugin-proposal-class-properties": "^7.2.0",
"@babel/plugin-transform-runtime": "^7.6.0",
"@babel/plugin-transform-spread": "7.2.0",
"@babel/preset-env": "7.2.0",
"@babel/preset-react": "7.0.0",
"babel-core": "7.0.0-bridge.0",
"babel-loader": "8.0.4",
"babel-plugin-add-react-displayname": "0.0.5",
"babel-plugin-file-loader": "1.1.1",
"babel-plugin-inline-import-data-uri": "1.0.1",
"babel-plugin-inline-react-svg": "1.1.0",
"babel-plugin-lodash": "^3.3.4",
"babel-plugin-transform-replace-object-assign": "^2.0.0",
```

Is there anything you suggest we should do instead?

**Environment**

```

```
- Node/npm version: 10.15.3
- OS: Windows
- Monorepo: No
- How you are using Babel: Rollup

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #12478
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

[Please review with whitespaces diff off](https://github.com/babel/babel/pull/12479/files?w=1)

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/12479"></a>

### CODE REVIEW

File: packages/babel-plugin-transform-react-jsx/test/fixtures/regression/issue-12478-automatic/output.js [hunk 1]
```diff
@@ -0,0 +1 @@
+const foo = /*#__PURE__*/undefined.jsx("p", {});
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-react-jsx/test/fixtures/regression/issue-12478-automatic/output.js:1]: This is a different unrelated bug: https://github.com/babel/babel/issues/12467

I'm preparing another PR for it, but it's lower priority since it's not a regression.

**Review by JLHwung — APPROVED** [review]

**Comment by nicolo-ribaudo** [comment]
Btw, we have this test that ensures that even if we are always setting up the runtime, we don't inject it when it's not needed: https://github.com/babel/babel/tree/main/packages/babel-plugin-transform-react-jsx/test/fixtures/nextAutoImport/no-jsx

File: packages/babel-helper-builder-react-jsx-experimental/src/index.js [hunk 2]
```diff
@@ -138,136 +138,134 @@ You can set \`throwIfNamespace: false\` to bypass this warning.`,
 
     Program: {
       enter(path, state) {
-        if (hasJSX(path)) {
```
Comment (hzoo) [inline packages/babel-helper-builder-react-jsx-experimental/src/index.js:141]: I'm assuming the reason why this was done originally was for performance? And that there aren't plugins that convert non-jsx stuff but that I guess isn't the case then

Comment (nicolo-ribaudo) [reply packages/babel-helper-builder-react-jsx-experimental/src/index.js:141]: Yeah probably for performance, but doing a deep traversal to check if there is JSX isn't going to be fast anyway.

Comment (hzoo) [reply packages/babel-helper-builder-react-jsx-experimental/src/index.js:141]: Makes me think this sort of thing shouldn't need to be set every file if it's the same for all of them (for the most part unless you use comments or overrides)?

**Review by hzoo — APPROVED** [review]

File: packages/babel-helper-builder-react-jsx-experimental/src/index.js (hunk 2 above)
Comment (nicolo-ribaudo) [reply packages/babel-helper-builder-react-jsx-experimental/src/index.js:141]: Yeah, usually you just set it once in the config file.

**Review by existentialism — APPROVED** [review]
