### PR TITLE
[ts]Fix syntax error for modifier name class methods with type parameters

### LINKED ISSUE #12353: Class function cannot be named 'declare' and be generic
**I'm submitting a bug report**

**Webpack Version:**
4.41.5

**Babel Core Version**:
7.7.2

**Babel Loader Version**:
8.0.6

**Please tell us about your environment:**
OSX 10.15.5

**Current behavior:**
```
SyntaxError:
Unexpected token (38:9)

  36 |   }
  37 | 
> 38 |   declare<T extends any>(arg: T): T {
     |          ^
  39 |     return arg;
  40 |   }
  41 | 
```

**Expected/desired behavior:**
Class functions can have the name `declare` and be generic without causing a syntax error. Note that it needs to be inside a class to be reproduced.

### PR DESCRIPTION
**Pull request by sosukesuzuki**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #12353
| Patch: Bug Fix?          | Y
| Major: Breaking Change?  | N
| Minor: New Feature?      | N
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/12356"></a>

### CODE REVIEW

File: packages/babel-parser/src/plugins/typescript/index.js [hunk 1]
```diff
@@ -166,7 +166,8 @@ export default (superClass: Class<Parser>): Class<Parser> =>
         !this.match(tt.colon) &&
         !this.match(tt.eq) &&
         !this.match(tt.question) &&
-        !this.match(tt.bang)
+        !this.match(tt.bang) &&
+        !this.match(tt.relational)
```
Comment (JLHwung) [inline packages/babel-parser/src/plugins/typescript/index.js:170]: I think we could align to TS implementation here:

https://github.com/microsoft/TypeScript/blob/4885dec80d184ef1570ac97739679ca66af7181d/src/compiler/parser.ts#L1796

An allowlist instead of denylist is better to reason about and avoid any surprise cases that we did not rule out.

File: packages/babel-parser/test/fixtures/typescript/class/method-modifier-name-with-type-parameters/input.ts [hunk 2]
```diff
@@ -0,0 +1,5 @@
+class C {
+  declare<T>() {}
+  readonly<T>() {}
+  abstract<T>() {}
```
Comment (JLHwung) [inline packages/babel-parser/test/fixtures/typescript/class/method-modifier-name-with-type-parameters/input.ts:4]: Can you also add `private`, `public` and `protected`?

File: packages/babel-parser/src/plugins/typescript/index.js [hunk 3]
```diff
@@ -159,13 +159,12 @@ export default (superClass: Class<Parser>): Class<Parser> =>
...
-        !this.match(tt.parenL) &&
-        !this.match(tt.parenR) &&
-        !this.match(tt.colon) &&
-        !this.match(tt.eq) &&
-        !this.match(tt.question) &&
-        !this.match(tt.bang)
+        this.match(tt.bracketL) ||
+        this.match(tt.braceL) ||
+        this.match(tt.star) ||
+        this.match(tt.ellipsis) ||
```
Comment (sosukesuzuki) [inline packages/babel-parser/src/plugins/typescript/index.js:165]: `babel-parser` cannot parse modifier with ellipsis. I've created issue. I've created new issue (#12371)

File: packages/babel-parser/test/fixtures/typescript/class/modifier-name-parameters/input.ts [hunk 4]
```diff
@@ -0,0 +1,4 @@
+class Foo {
+  constructor(private, public, static) {
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/test/fixtures/typescript/class/modifier-name-parameters/input.ts:2]: This should be an error, because `private`, `public` and `static` are reserved words in strict mode.

Comment (sosukesuzuki) [reply packages/babel-parser/test/fixtures/typescript/class/modifier-name-parameters/input.ts:2]: `babel-parser` doesn't check reserved word for TypeScript? https://github.com/babel/babel/blob/b564368d6efc58038468503ae73d006b0679f0a1/packages/babel-parser/src/plugins/typescript/index.js#L1962-L1972

Comment (nicolo-ribaudo) [reply packages/babel-parser/test/fixtures/typescript/class/modifier-name-parameters/input.ts:2]: Oh right, I didn't remember about that.

**Review by JLHwung — APPROVED** [review]

**Review by nicolo-ribaudo — APPROVED** [review]

**Comment by nicolo-ribaudo** [comment]
Thanks!

**Comment by nicolo-ribaudo** [comment]
(I reworded the commit a bit otherwise it was too long when adding ` (#12356)`)
