### PR TITLE
[ts] allow redeclaring a var/type with the same name as import

### LINKED ISSUE #10015: Can't declare variable with the same name as TypeScript type import
## Bug Report

**Current Behavior**
Babel shows error "Identifier 'xxx' has already been declared" when variable and type uses the same name. 

**Input Code**
- REPL link:
https://babeljs.io/en/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAJQKYEMDGMA0cDecDCEAdjEgB7wC-cAZlBCHAORSoZMDcAUF2sQM7xCJcjABcBYqQoAeHJQB8cALyI2MAHRpWKUsOkwAFPICU3LuUixckkRTiVuQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2%2Ctypescript&prettier=false&targets=&version=7.4.5&externalPlugins=%40babel%2Fplugin-transform-typescript%407.4.5

```js
import React, { Context } from 'react';

const Context: Context<{}> = React.createContext({});

export { Context };
```

**Error message**
```
/repl: Identifier 'Context' has already been declared (3:6)
```

**Expected behavior/code**
Types should be ignored by Babel and name conflict should not happen. This code is acceptable by TypeScript compiler even with `isolatedModules` option.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  presets: ['module:metro-react-native-babel-preset']
}
```

**Environment**
- Babel version(s): v7.4.5
- Node/npm version: v10.15.0
- OS: macOS 10.14.5
- Monorepo: no
- How you are using Babel: React Native metro bundler

**Possible Solution**
It can be inferred from the file that the imported identifier is a type. So it should not count as an identifier.

**Additional context**
Related issue: https://github.com/babel/babel/issues/7943

It's very common in TypeScript to use the same identifier for variable and type without introducing a name conflict. This behaviour should be supported by Babel as well.

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | fixes #10015 
| Patch: Bug Fix?          |√
| Tests Added + Pass?      | √
| License                  | MIT

<del>Doesn't seem to fix the original issue, but fixes https://github.com/babel/babel/issues/10015#issuecomment-1148080994</del>
Also found new similar bugs, this is in the second commit.
Not sure if `flow` is affected, but I guess I can ignore it for now.

This also fixes https://github.com/babel/babel/issues/14795 which has been closed.
[repl](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=JYWwDg9gTgLgBDAnmApnA3nAgnAvnAMyghDgHIA6AemADsYUoCBDAYxTIG4Aob1gG2YBnIdgy4gA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=typescript&prettier=false&targets=&version=7.18.13&externalPlugins=&assumptions=%7B%7D)
[repl2](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=PTAEBcAsEsGdQEQEEGjqAhgO1ASS-AKYBOAZhgMaEBQ0AtgA4D2x4oA3qEqAL6inEmdUAHIAdMGgES5KiIDc1ahQA2GWPG7seQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=typescript&prettier=false&targets=&version=7.18.13&externalPlugins=&assumptions=%7B%7D)

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14900"></a>

### CODE REVIEW

**Comment by liuxingbaoyu** [comment]
https://github.com/liuxingbaoyu/babel/blob/fix-ts-import-type/packages/babel-parser/src/plugins/typescript/index.ts#L3963
Doesn't seem to be expected?

**Comment by liuxingbaoyu** [comment]
https://www.typescriptlang.org/play?noImplicitAny=false&declaration=false&isolatedModules=true&ts=4.8.0-beta#code/JYWwDg9gTgLgBDAnmApnA3gcQDYQEYCG2AvnAGZQQhwDkAAgFYoDOMA9EqszQNwCwAKEGc0OfETgBeOGMLYAdLKL8hAgG4EocAgC4ZuOTyA
https://babeljs.io/repl/build/52855/#?browsers=&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=JYWwDg9gTgLgBDAnmApnA3gcQDYQEYCG2AvnAGZQQhwDkAAgFYoDOMA9EqszQNwBQnNDnxE4AXjjDC2AHRSi_AG4EocAgC5JuaTyA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=typescript&prettier=false&targets=&version=7.18.13%2Bpr.14900&externalPlugins=&assumptions=%7B%7D

Seems to expose another bug?

**Comment by JLHwung** [comment]
It seems to me that `type Global = ...` can shadow `import type { Global } from "./module"`, we may need a new binding type.

**Comment by liuxingbaoyu** [comment]
Yes, it seems that we can fix the original problem altogether by treating import as a new type.

https://www.typescriptlang.org/play?noImplicitAny=false&declaration=false&jsx=0&isolatedModules=true&ts=4.8.0-beta#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDecDCEAdjEgB7wC+cAZlBCHAORSoZMDcAsAFC9rEAzvEIlyMAFwFipCgB4clAHxwAvIjYwAdGlYpSo2TAAUigJTc+PcpFi5pYinEocgA
https://babeljs.io/repl/build/52855/#?browsers=&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAJQKYEMDGMA0cDecDCEAdjEgB7wC-cAZlBCHAORSoZMDcAUF2sQM7xCJcjABcBYqQoAeHJQB8cALyI2MAHRpWKUsOkwAFPICU3LuUixckkRTiUOQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=typescript&prettier=false&targets=&version=7.18.13%2Bpr.14900&externalPlugins=&assumptions=%7B%7D

**Comment by liuxingbaoyu** [comment]
I haven't written complex ts types, it would be great if someone could help add some tests!😃

File: packages/babel-parser/src/plugins/typescript/scope.ts [hunk 1]
```diff
@@ -35,11 +38,50 @@ class TypeScriptScope extends Scope {
 // explanation of how typescript handles scope.
 
 export default class TypeScriptScopeHandler extends ScopeHandler<TypeScriptScope> {
+  importsStack: Set<string>[] = [];
+
   createScope(flags: ScopeFlags): TypeScriptScope {
+    this.importsStack.push(new Set()); // SCOPE_TS_TOP_LEVEL should be kept
```
Comment (JLHwung) [inline packages/babel-parser/src/plugins/typescript/scope.ts:44]: Did you mean `SCOPE_TS_MODULE`?

**Comment by JLHwung** [comment]
> ✘ 4 valid programs parsed without error (in violation of the allowlist file)

That's great! Can you run `node scripts/parser-tests/typescript --update-allowlist`?

File: packages/babel-parser/src/parser/statement.ts [hunk 2]
```diff
@@ -2882,6 +2882,7 @@ export default abstract class StatementParser extends ExpressionParser {
     /* eslint-disable @typescript-eslint/no-unused-vars -- used in TypeScript and Flow parser */
     isInTypeOnlyImport: boolean,
     isMaybeTypeOnly: boolean,
+    bindingType?: BindingTypes,
```
Comment (JLHwung) [inline packages/babel-parser/src/parser/statement.ts:2885]: Can you also update `packages/babel-parser/src/plugins/flow/index.ts`? It does not need any special handling: we just have to pass through all params to the base method.

File: packages/babel-parser/src/plugins/typescript/scope.ts (hunk 1 above)
Comment (liuxingbaoyu) [reply packages/babel-parser/src/plugins/typescript/scope.ts:44]: https://github.com/babel/babel/blob/14ea25fbb337f7c7cc6c29ae5ee480fc76818087/packages/babel-parser/src/plugins/typescript/index.ts#L1861-L1875
There seems to be an extra `SCOPE_OTHER` here.
At first I changed it to `SCOPE_TS_TOP_LEVEL`, but then I found it was not necessary.
Because export detection doesn't happen until all scopes have exited, I must and should always keep the top-level scope.
Perhaps remove the comment or modify it to:
Always keep the top-level scope for export checks.

**Comment by liuxingbaoyu** [comment]
> > ✘ 4 valid programs parsed without error (in violation of the allowlist file)
> 
> That's great! Can you run `node scripts/parser-tests/typescript --update-allowlist`?

OK, I'll do this after the review is complete.

File: packages/babel-parser/src/parser/statement.ts (hunk 2 above)
Comment (liuxingbaoyu) [reply packages/babel-parser/src/parser/statement.ts:2885]: Is there any special reason? I used optional parameters so that I can avoid modifying all plugins.

Comment (JLHwung) [reply packages/babel-parser/src/parser/statement.ts:2885]: So that we can maintain the interface consistence between the derived plugin parser and the base parser. If we started to use `bindingType` in the base parser, we are prone to forget that `flow` plugin also needs update. In the past we see several bugs related to out-of-dated `estree` plugin parser.

Comment (liuxingbaoyu) [reply packages/babel-parser/src/parser/statement.ts:2885]: I think you're right, although we can remove optional tags when we actually use them.
Seems like plugins can exist at the same time? Then I seem to need to disallow `void` here as well.
https://github.com/babel/babel/pull/14900/files#diff-37df9adada2d88868f7240c5668049abc73404f849e024e3dfd68e87a94077beR96

File: packages/babel-parser/src/plugins/typescript/scope.ts [hunk 3]
```diff
@@ -35,11 +38,50 @@ class TypeScriptScope extends Scope {
...
+      this.importsStack.pop();
+    }
+  }
+
+  hasImport(name: string, allowShadow?: boolean) {
+    const len = this.importsStack.length;
+    if (this.importsStack[len - 1].has(name)) {
+      return true;
+    }
+    return !allowShadow && len > 1 && this.importsStack[0].has(name);
```
Comment (JLHwung) [inline packages/babel-parser/src/plugins/typescript/scope.ts:70]: The module declarations can be nested, so it may not suffice to check only the top level imports.

```ts
declare module 'test/sub1' {
  import type { JSONSchema7 } from 'json-schema';
  module 'test/sub2' {
    export { JSONSchema7 }
  }
}
```

Comment (liuxingbaoyu) [reply packages/babel-parser/src/plugins/typescript/scope.ts]: Good catch!

**Review by nicolo-ribaudo — APPROVED** [review]
Thank you!

**Comment by liuxingbaoyu** [comment]
Please don't merge yet, I found that the allowlist comment seems to be missing a bit, I'll take a look later.

**Comment by nicolo-ribaudo** [comment]
Too late :grimacing:

**Comment by liuxingbaoyu** [comment]
Nevermind, I will open a new PR.😃
