### PR TITLE
Fix: improve object rest handling in array pattern

### LINKED ISSUE #17271: Transpiled code from object rest within an array pattern in an assignment throws redeclaration error
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

[REPL](https://babel.dev/repl#?browsers=&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=DYUwLgBATiDOYG4BQSAUBtA3hAdHm8EAvgLoQC8EWpAlEA&forceAllTransforms=false&modules=umd&shippedProposals=false&evaluate=true&fileSize=false&timeTravel=true&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.27.0&externalPlugins=%40babel%2Fplugin-transform-object-rest-spread%407.25.9&assumptions=%7B%7D)

```js
let rest;

([{ ...rest }] = [{}])

for ([{ ...rest }] of [[{}]]);
```

### Configuration file name

_No response_

### Configuration

```json
{
  "plugins": ["@babel/plugin-transform-object-rest-spread"]
}
```

### Current and expected behavior

Current: The generated code throws redeclaration error because `rest` is defined as `let` and then redeclared with `var`
```js
// helper code omitted
let rest;
[_ref] = [{}];
var rest = _extends({}, (_objectDestructuringEmpty(_ref), _ref));
```

Expected: This is valid JS, the transpiled code should not throw. `rest` should be defined and initialized as an empty object.

### Environment

REPL

### Possible solution

_No response_

### Additional context

_No response_

### LINKED ISSUE #17272: Transpiled code from object rest within an array pattern in a for declaration throws "ref is not defined" error
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

[REPL](https://babel.dev/repl#?browsers=&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=GYewTgBAFAxiB2BnALhA2gbwgOl2ApihAL4C6EAvOhmQNzACGANovrQJS1A&forceAllTransforms=false&modules=umd&shippedProposals=false&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.27.0&externalPlugins=%40babel%2Fplugin-transform-object-rest-spread%407.25.9&assumptions=%7B%7D)

```js
for (const [{ ...rest }] = [{}]; false; );
```

### Configuration file name

_No response_

### Configuration

```json
{
  "plugins": ["@babel/plugin-transform-object-rest-spread"]
}
```

### Current and expected behavior

Current: The transpiled code throws "_ref is not defined" error because the `rest` definition is moved out of the for loop.

```js
// helper code omitted

for (const [_ref] = [{}]; false;);
var rest = _extends({}, (_objectDestructuringEmpty(_ref), _ref));
```

Expected: This is valid JS, the transpiled code should not throw and initialize `rest` as an empty object.

### Environment

REPL

### Possible solution

_No response_

### Additional context

This issue may be related to https://github.com/babel/babel/issues/17271, though the error message is different.

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #17271, fixes #17272
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

This PR contains two refactors and the array pattern fix. On https://gist.github.com/nicolo-ribaudo/f8ac7916f89450f2ead77d99855b2098, I plan to implement the object pattern split as we have already done in the `destructuring-private` transform, which is a more ambitious goal. This PR, as a temporary fix, should unblock the discard binding transform PR.

### CODE REVIEW

File: packages/babel-plugin-transform-object-rest-spread/test/fixtures/object-rest/for-x-assignment-shadowed-block-scoped-bindings/exec.js [hunk 1]
```diff
@@ -0,0 +1,7 @@
+let a = 0, result, y;
+
+for ({ [a++]: result, ...y} of [["0", "1"]]) {
```
Comment (JLHwung) [inline packages/babel-plugin-transform-object-rest-spread/test/fixtures/object-rest/for-x-assignment-shadowed-block-scoped-bindings/exec.js:3]: This bug is fixed by the second refactoring commit.

File: packages/babel-plugin-transform-object-rest-spread/test/fixtures/object-rest/for-x-array-pattern/output.js [hunk 2]
```diff
@@ -1,45 +1,65 @@
...
 // ForXStatement
-for (const _ref of []) {
-  const [_ref2] = _ref;
-  const {
-      a
-    } = _ref2,
-    b = babelHelpers.objectWithoutProperties(_ref2, _excluded);
-}
-for (var _ref3 of []) {
-  [_ref4] = _ref3;
```
Comment (liuxingbaoyu) [inline packages/babel-plugin-transform-object-rest-spread/test/fixtures/object-rest/for-x-array-pattern/output.js:13]: It seems we didn't declare `_ref4`? This is also the case in the new output.

**Review by nicolo-ribaudo — APPROVED** [review]
This looks good to me. I wonder whether eventually we should implement transform for object rest, destructuring, and private destructuring all in a single package, similarly to how we do for class features and regexps.

File: packages/babel-plugin-transform-object-rest-spread/test/fixtures/object-rest/for-x-array-pattern/output.js (hunk 2 above)
Comment (JLHwung) [reply packages/babel-plugin-transform-object-rest-spread/test/fixtures/object-rest/for-x-array-pattern/output.js:13]: Fixed in https://github.com/babel/babel/pull/17281/commits/7088af9e61b7c4bf47c39b17df0c558bef78cdc6

**Review by liuxingbaoyu — APPROVED** [review]
> On [gist.github.com/nicolo-ribaudo/f8ac7916f89450f2ead77d99855b2098](https://gist.github.com/nicolo-ribaudo/f8ac7916f89450f2ead77d99855b2098), I plan to implement the object pattern split as we have already done in the destructuring-private transform, which is a more ambitious goal.

It would be nice if we could do it without using iterators. :)

**Comment by JLHwung** [comment]
> It would be nice if we could do it without using iterators. :)

Could you elaborate why you would like to avoid iterators?

**Comment by liuxingbaoyu** [comment]
`Symbol.iterator` is supported in chrome 43, and rest parameters are supported in chrome 47, which means that it will be difficult for users to use it without polyfill.
The benefit is better support for `getter` behavior, which may be rarely used.

**Comment by JLHwung** [comment]
> `Symbol.iterator` is supported in chrome 43, and rest parameters are supported in chrome 47, which means that it will be difficult for users to use it without polyfill. The benefit is better support for `getter` behavior, which may be rarely used.

Thanks. We are on the same page, what I was meant for the "object pattern split" is that we handle the object rest within an object pattern as same as how we currently handle private destructuring. For example, the current private destructuring transforms
```js
var { a, b: { i: x, #p: p }, c } = rhs
```
to
```js
var { a } = rhs,
      _m = rhs.b,
      { i: x } = _m,
      p = _m.#p,
      { c } = rhs;
```
where the object pattern is split into three parts: part before the private access, at the private access and after the private.

Now if we take a look at the current object rest transforms,
```js
var { a, b: { i: x, ...p }, c } = rhs
```
is currently transformed to
```js
const _excluded = ["i"];
var { a, b: { i: x }, c } = rhs,
      p = _objectWithoutProperties(rhs.b, _excluded);
```
where `b` has been accessed twice, and the `c`  is accessed before the `...p` access. Now thinking `...p` as if it were `#p: p`, if we reuse the private-destructuring object pattern split, then it should be transformed to
```js
const _excluded = ["i"];
var { a } = rhs,
      _m = rhs.b,
      { i: x } = _m,
      p = _objectWithoutProperties(_m, _excluded),
      { c } = rhs;
```
where the `b` access is memoised and the `c` access is now placed correctly after `p` is evaluated, and the footprint increase is acceptable.

The private-destructuring assumes the iterable is pure: it does not affect how other nested patterns are evaluated. If this assumption is not held, then we will have to implement the step iterator, which is like you said, will be difficult for users without polyfill. Since we don't implement the step iterator for private-destructuring, I don't plan do so for the object-rest either.

**Comment by liuxingbaoyu** [comment]
Thanks for the detailed explanation! That sounds good.
We can keep the original as `pureGetters` assumption.

> The private-destructuring assumes the iterable is pure: it does not affect how other nested patterns are evaluated. If this assumption is not held, then we will have to implement the step iterator, which, like you said, will be difficult for users without polyfill. Since we don't implement the step iterator for private-destructuring, I don't plan do so for the object-rest either.

Sorry I didn't understand, can you provide an example that is not pure?

**Comment by JLHwung** [comment]
See https://github.com/babel/babel/blob/83c72d0a0404b3ffec279a9d1c54d635ce7edefb/packages/babel-plugin-proposal-destructuring-private/src/util.ts#L439-L463

and https://github.com/babel/babel/blob/main/packages/babel-plugin-proposal-destructuring-private/test/fixtures/ordering/.array-pattern-side-effect-iterable/exec.js

This test has been disabled because we don't support it: A proper support would require the aforementioned step iterator.
