### PR TITLE
Preserve class elements comments in class transform

### LINKED ISSUE #8507: Babel transpiler dislocates comments when fat arrow functions are used!
## Bug Report
Babel transpiler dislocates the jsdocs comments to a separate location in the output file when fat arrow functions are used in a class.

**Current Behavior**
for example, the following function has associated jsdoc comments:
```
/**
     * Promise factory to generate a Bearer Token for write_access to private data.
     * The Unsplash API uses OAuth2 to authenticate and authorize Unsplash users. 
     * Unsplash’s OAuth2 paths live at https://unsplash.com/oauth/.
     * @function generateBearerToken
     * @memberof UnsplashApi
     * @returns {Object} - The user's Access Token JSON data object.
     */
    generateBearerToken = () => {
        let url = this.BEARER_TOKEN_URL +
            '?client_id=' + (this.access_key) +
            '&client_secret=' + (this.secret_key) +
            '&redirect_uri=' + (this.redirect_uri) +
            '&code=' + (this.code) +
            '&grant_type=' + (this.grant_type);
        return this.fetchUrl(url, 'POST');
    };
```
which should produce compiled code like this:
```
/**
     * Promise factory to generate a Bearer Token for write_access to private data.
     * The Unsplash API uses OAuth2 to authenticate and authorize Unsplash users. 
     * Unsplash’s OAuth2 paths live at https://unsplash.com/oauth/.
     * @function generateBearerToken
     * @memberof UnsplashApi
     * @returns {Object} - The user's Access Token JSON data object.
     */
  this.generateBearerToken = function () {
        var url = _this.BEARER_TOKEN_URL + '?client_id=' + _this.access_key + '&client_secret=' + _this.secret_key + '&redirect_uri=' + _this.redirect_uri + '&code=' + _this.code + '&grant_type=' + _this.grant_type;
        return _this.fetchUrl(url, 'POST');
    };
```
Instead it produces the following separately at different locations:
```
this.generateBearerToken = function () {
        var url = _this.BEARER_TOKEN_URL + '?client_id=' + _this.access_key + '&client_secret=' + _this.secret_key + '&redirect_uri=' + _this.redirect_uri + '&code=' + _this.code + '&grant_type=' + _this.grant_type;
        return _this.fetchUrl(url, 'POST');
    };

......................................................
.....................................................
//at the bottom of the page
/**
     * Promise factory to generate a Bearer Token for write_access to private data.
     * The Unsplash API uses OAuth2 to authenticate and authorize Unsplash users. 
     * Unsplash’s OAuth2 paths live at https://unsplash.com/oauth/.
     * @function generateBearerToken
     * @memberof UnsplashApi
     * @returns {Object} - The user's Access Token JSON data object.
     */
```
I observed this behaviour only when regular class methods are changed to fat arrow functions.

**Input Code**
Please clone this repo and see ` fat_arrow_build` and `normal_build` folders:
https://github.com/SandeepVattapparambil/webpack_bug
or see this link:
[babel playground](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=PQKhCgAIUhRBlAbJAxgGwIYGcuQO4CWALgBaQBmGRkGATrQPZ6QEB2rAprRQK6spECDVlighg4cAHIeWDpCxFaBAVIDck0BGiQAAumy4ACgzQBPAObCxkACol5AWwxtIAB1OXhqTDjESDHEgTcytWSABvSUgYyC0oWJ0AYV9cFGFFWh4BBloE2JhdNzoMR0iQAF9IBwILEmp8mMLi2lLyqsIAE1JIRugJRPSRJWyiXIAKGrqiABp8Am6SAEpIvtjSAiwAOlZS-QBeSCkQr1Z1NZiN7an6yEObog1ExKutrp7D95In2Iro2Piz0Ku0c8iwGDMADk9n1CuQ-AIhKxYXo2Jw8kDIABBaocNBuLi8fiCbxjBQQyAgjiwgaxcFQvZ3SDjFb7AB8q2esSGWFMHC2aAYFnGUgAEgQ5gBJGhlDBHOavKmQADURy2UiWPxif0agMSwMZ9PFilyZhRunhxKR5rRXBROIc-MJlsRpIY5LMlJhQNpMSNmzGtE9hxZdw5US5MR5fIFQpFACITmF4yxcJ0uAQAG4cToURhlUjyADitA4HAA1u5TLJmc5WGYVlIVUcMKxc2ECHLxq2LGgOEt1ZrGn8dY4GJ0eH2thwAB4eWhEXCHJPCNRAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=6.26.0&envVersion=)

**Expected behavior/code**
I expected the following output:
```
/**
     * Promise factory to generate a Bearer Token for write_access to private data.
     * The Unsplash API uses OAuth2 to authenticate and authorize Unsplash users. 
     * Unsplash’s OAuth2 paths live at https://unsplash.com/oauth/.
     * @function generateBearerToken
     * @memberof UnsplashApi
     * @returns {Object} - The user's Access Token JSON data object.
     */
  this.generateBearerToken = function () {
        var url = _this.BEARER_TOKEN_URL + '?client_id=' + _this.access_key + '&client_secret=' + _this.secret_key + '&redirect_uri=' + _this.redirect_uri + '&code=' + _this.code + '&grant_type=' + _this.grant_type;
        return _this.fetchUrl(url, 'POST');
    };
```

**Babel Configuration (.babelrc, package.json, cli command)**
available in repo link

**Environment**
- Babel version(s): 6.26.3
- Node/npm version: v9.4.0
- OS:  Windows 10
- Monorepo: yes
- How you are using Babel: loader

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #8507 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

In this PR we try to preserve surrounding member comments in class transforms. Currently the NodePath API `replaceWith` and `replaceWithMultiple` already forward comments from the old node to new node. But in the class transform we are constructing new nodes from the immediate children of member nodes, so we have to explicitly forward such comments.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15406"></a>

### CODE REVIEW

File: packages/babel-helper-create-class-features-plugin/src/fields.ts [hunk 1]
```diff
@@ -994,6 +1042,12 @@ function isNameOrLength({ key, computed }: t.ClassProperty) {
   return false;
 }
 
+function inheritPropComments<T extends t.Node>(node: T, prop: PropPath) {
+  t.inheritLeadingComments(node, prop.node);
+  t.inheritInnerComments(node, prop.node);
```
Comment (JLHwung) [inline packages/babel-helper-create-class-features-plugin/src/fields.ts:1047]: Unlike `t.inheritsComments`, the `inheritPropComments` only inherits leading and inner comments. For every class member except the last one, its trailing comments must be the leading comments of the next sibling. The current approach favours the JSDoc style leading comments, and will lose the trailing comments of the last member. I think it does not worth the extra efforts to recover the last trailing comments. We can fix that in the future.

File: packages/babel-helper-create-class-features-plugin/src/fields.ts [hunk 2]
```diff
@@ -557,14 +557,17 @@ function buildPrivateFieldInitLoose(
   const { id } = privateNamesMap.get(prop.node.key.id.name);
   const value = prop.node.value || prop.scope.buildUndefinedNode();
 
-  return template.statement.ast`
+  return inheritPropComments(
+    template.statement.ast`
     Object.defineProperty(${ref}, ${t.cloneNode(id)}, {
```
Comment (nicolo-ribaudo) [inline packages/babel-helper-create-class-features-plugin/src/fields.ts:562]: Nit: can you indent the template contents one level more, to be visually inside the template tag "call"? In various places in this file.

File: packages/babel-helper-create-class-features-plugin/src/fields.ts (hunk 1 above)
Comment (nicolo-ribaudo) [reply packages/babel-helper-create-class-features-plugin/src/fields.ts:1047]: Could you add the "For every class member [...] the trailing comments of the last member" part as a comment in the code? :)

**Review by nicolo-ribaudo — APPROVED** [review]
:heavy_check_mark:

**Review by existentialism — APPROVED** [review]
