### PR TITLE
Correctly print parens around `in` in `for` heads

### LINKED ISSUE #16628: Missing parenthesis in initializer of for loop
### Describe the bug

Babel is removing some parentheses form this for loop, and the resulting code logs `0` instead of `1`

### Input code

```typescript
let count = 0;
for (var a = 1 || (2 in {}) in { x: 1 }) count++;
console.log(count);
```

### Expected behavior

Same code

### Actual behavior

```js
let count = 0;
for(var a = 1 || 2 in {} in {
    x: 1
})count++;
console.log(count);
```

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #16628
| Patch: Bug Fix?          | y
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

I really wanted to use `using`, but we would need an assumption to avoid the try/catch when we know it's not necessary.

### CODE REVIEW

File: packages/babel-generator/src/printer.ts [hunk 1]
```diff
@@ -119,7 +119,16 @@ class Printer {
   declare _inputMap: TraceMap;
 
   declare format: Format;
-  inForStatementInitCounter: number = 0;
+
+  inForStatementInit: boolean = false;
+  enterForStatementInit(val: boolean) {
+    const old = this.inForStatementInit;
+    if (old === val) return () => {};
```
Comment (liuxingbaoyu) [inline packages/babel-generator/src/printer.ts:126]: Maybe return undefined and then use `exit?.()` on the caller?

Comment (nicolo-ribaudo) [reply packages/babel-generator/src/printer.ts:126]: Isn't it better to use consistent types, rather than having polymorphic functions? It's trivial for an engine to optimise an empty function call.

**Review by JLHwung — APPROVED** [review]

**Review by liuxingbaoyu — APPROVED** [review]

**Comment by kungfooman** [comment]
Interesting PR! I wanted to test it, but link from @babel-bot fails with:

> Could not load Babel build #57311: Error sending request to CircleCI: undefined

**Comment by nicolo-ribaudo** [comment]
CircleCI has been working weirdly in the past few days, thanks for noticing the problem -- I'll see if it something that we need to fix :)

**Comment by liuxingbaoyu** [comment]
It seems that the CircleCI API no longer allows cross-domain.
I will take a look at it.
