### PR TITLE
fix: preserve tokensLength in tryParse

### LINKED ISSUE #13322: [Bug]: Unexpected error thrown
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
require("@babel/parser").parse('<div propA={[ key: value ]} propsB={(a: b)} />', {sourceType: 'module', errorRecovery:true, plugins: ['jsx', 'typescript'], tokens: true})
Uncaught TypeError: Cannot read property 'type' of undefined
    at babel7CompatTokens (<CWD>\node_modules\@babel\parser\lib\index.js:12432:17)
    at Object.parseTopLevel (<CWD>\node_modules\@babel\parser\lib\index.js:12466:44)
    at Object.parse (<CWD>\node_modules\@babel\parser\lib\index.js:14186:10)
    at Object.parse (<CWD>\node_modules\@babel\parser\lib\index.js:7925:18)
    at Object.parse (<CWD>\node_modules\@babel\parser\lib\index.js:14238:38)
```

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

Should throw `SyntaxError`

### Environment

Babel version: 7.14.2

### Possible solution

_No response_

### Additional context

Prettier PR https://github.com/prettier/prettier/pull/10898

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #13322 
| Patch: Bug Fix?          | Y
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

In this PR we preserve `state.tokensLength` (derived from `this.tokens`) on raising errors when `errorRecovery: true`, because the parser will parse remaining tokens. We do not reset the parser state when `tryParse` successfully returns, so when `errorRecovery` is `true`, we should not reset `state.tokensLength`, too.

Technically #13256 does not introduce this regression but it reveals the fact that the parser unexpectedly eats tokens when errors are thrown in recovery mode.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/13326"></a>

### CODE REVIEW

File: packages/babel-parser/test/fixtures/flow/typecasts/fail-without-parens-jsx-tokens-true/input.js [hunk 1]
```diff
@@ -0,0 +1 @@
+<div propA={[key: value]} />
```
Comment (JLHwung) [inline packages/babel-parser/test/fixtures/flow/typecasts/fail-without-parens-jsx-tokens-true/input.js:1]: Currently the `tokens` of [parsed AST](https://astexplorer.net/#/gist/9675cd0445add4e9c24d321fc433be7a/1f4d63fd000b655fedfe1585131fac08b614e4fd) is a length-14 array
```js
[ tt.jsxTagStart, tt.name, undefined, undefined, ... , tt.eof]
```

`babel7Compat` thus throws because the `tokens` unexpectedly includes `undefined`.

**Review by nicolo-ribaudo — APPROVED** [review]

File: packages/babel-parser/src/parser/util.js [hunk 2]
```diff
@@ -216,6 +216,10 @@ export default class UtilParser extends Tokenizer {
       if (this.state.errors.length > oldState.errors.length) {
         const failState = this.state;
         this.state = oldState;
+        // The tokensLength should be preserved on error recovery mode
```
Comment (existentialism) [inline packages/babel-parser/src/parser/util.js:219]:
```suggestion
        // tokensLength should be preserved during error recovery mode
```

File: packages/babel-parser/src/parser/util.js [hunk 3]
```diff
@@ -216,6 +216,10 @@ export default class UtilParser extends Tokenizer {
...
+        // since parser does not halt and instead it will parse the
```
Comment (existentialism) [inline packages/babel-parser/src/parser/util.js:220]:
```suggestion
        // since the parser does not halt and will instead parse the
```

**Review by existentialism — APPROVED** [review]
