### PR TITLE
fix: Should not evaluate vars in child scope

### LINKED ISSUE #8411: path.evaluate wrongly retruns with confidence for "block-scoped" var's
## Bug Report

**Current Behavior**
`path.evaluate` is broken for `var` scopes.

**Input Code**
http://astexplorer.net/#/gist/583ea7d0c0501af69a1b224526f7f864

**Expected behavior/code**
Cannot return with confidence that `doesExist` is true.

**Babel Configuration (.babelrc, package.json, cli command)**

N/A

**Environment**
N/A

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #8411 
| Patch: Bug Fix?          | √
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | √
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

File: packages/babel-traverse/test/evaluation.js [hunk 1]
```diff
@@ -346,6 +346,28 @@ describe("evaluation", function () {
     expect(result.value).toEqual(["foo", "bar"]);
   });
 
+  it("should not evaluate vars in child scope", function () {
+    const path = getPath(`
+      if (typeof Bar != "undefined") {
+        var doesExist = true;
+      }
```
Comment (nicolo-ribaudo) [inline packages/babel-traverse/test/evaluation.js:353]: What happens when evaluating the RefernecedIdentifier in this example?
```js
{
  var doesExist = true;
  doesExist;
}
```

File: packages/babel-traverse/src/path/evaluation.ts [hunk 2]
```diff
@@ -230,14 +230,21 @@ function _evaluate(path: NodePath, state: State): any {
...
-            deopt(binding.path, state);
-            return;
+            if (hasIf) {
+              deopt(binding.path, state);
+              return;
+            }
+            break;
+          }
+          if (scope.path.parentPath?.isIfStatement()) {
+            hasIf = true;
```
Comment (nicolo-ribaudo) [inline packages/babel-traverse/src/path/evaluation.ts:247]: Also while, for, for-of, try-catch. I'd prefer to list "known to be safe" statements (i.e. do-while and block), rather than potentially unsafe ones.

**Review by nicolo-ribaudo — APPROVED** [review]
