### PR TITLE
Fix duplicate declaration error on ambient class declarations

### LINKED ISSUE #13735: [Bug]: Error when I specify "declare class" and "function" with the same name
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@rollup/plugin-babel

### Input code

[REPL](https://babeljs.io/repl#?browsers=defaults&build=&builtIns=false&corejs=3.6&spec=false&loose=true&code_lz=CYUwxgNghgTiAEkoGdnwILwN4F8BQeAZgK4B2YALgJYD2pG8AFAJTY5A&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=typescript&prettier=false&targets=&version=7.15.5&externalPlugins=%40babel%2Fplugin-transform-typescript%407.13.0&assumptions=%7B%7D)
```ts
declare class A {}

function A () {}
```

### Configuration file name

.babelrc

### Configuration

```json
{
  "presets": ["@babel/preset-typescript"]
}
```

### Current and expected behavior

I expect this construction to be compiled correctly because `tsc` [can](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEkoGdnwILwN4F8BQeAZgK4B2YALgJYD2pG8AFAJTY5A) do it. However, currently Babel throws an error:
```
Duplicate declaration "A"
  1 | declare class A {}
  2 |
> 3 | function A () {}
    | 
```

### Environment

- Babel version(s): 7.15.5
- Node: 16
- npm: 7
- OS: Windows 10
- Monorepo: no

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by The-x-Theorist**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #13735  
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

Improve the scope handling for `declare class` by adding a check using `path.node.declare` for "declare class".

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14016"></a>

### CODE REVIEW

File: packages/babel-traverse/src/scope/index.ts [hunk 1]
```diff
@@ -705,6 +705,8 @@ export default class Scope {
       for (const declar of declarations) {
         this.registerBinding(path.node.kind, declar);
       }
+    } else if (path.isClassDeclaration() && path.node.declare) {
+      this.registerBinding("class", path);
     } else if (path.isClassDeclaration()) {
       this.registerBinding("let", path);
```
Comment (JLHwung) [inline packages/babel-traverse/src/scope/index.ts:711]: I think we should skip registering ambient class declaration here.

BTW we don't have a `class` binding type: https://github.com/babel/babel/blob/029cd15bd95b70e1164ac4d05ac2a4c178be5769/packages/babel-traverse/src/scope/binding.ts#L5-L13

Comment (The-x-Theorist) [reply packages/babel-traverse/src/scope/index.ts:711]: Sorry for declaraing an unsual binding type.
Can we just skip the registerDeclaration for declare class using `if(path.node.declare) return` inside binding block statement of registerDeclaration for class declaration?

**Review by JLHwung — APPROVED** [review]

**Review by nicolo-ribaudo — APPROVED** [review]
Thanks!
