### PR TITLE
Fix decorated class computed keys ordering

### LINKED ISSUE #16341: [Bug]: Incorrect computed key evaluation order when a class has only class decorators
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
const dummy = () => {}

const logs = [];

@dummy
class C {
  [(logs.push(1), 1)];
  static [(logs.push(2), 2)];
  [(logs.push(3), 3)];
}

console.log(logs);
```

[REPL](https://babel.dev/repl#?browsers=chrome%2032&build=&builtIns=false&corejs=3.21&spec=false&loose=true&code_lz=MYewdgzgLgBAJgVwLZIJ4wLwwBQEpMB8MA3gL4BQ5oksANiAOYSYwDaAugNyUACiKqKrQCGEZgGES5GG2z0mAOgAOCCAAtsARlwAaGNq7SY0YVACWwWfIjLVGgEy6YjwzNZzGNleuwBmJ_6GFFTgECC0AKYK8h5MuJxAA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.24.0&externalPlugins=%40babel%2Fplugin-proposal-decorators%407.23.3&assumptions=%7B%7D)

### Configuration file name

_No response_

### Configuration

```json
{
  "plugins": [
    ["proposal-decorators", { "version": "2023-11" }]
  ]
}

```

### Current and expected behavior

7.24.0: it prints [2, 1, 3]
main: it prints [1, 3, 2]
expected: it should print [1, 2, 3]

### Environment

REPL

### Possible solution

_No response_

### Additional context

As a workaround, you can add a dummy decorator to any class elements, then the evaluation order will be correct.
For example,

```js
const dummy = () => {}

const logs = [];

@dummy
class C {
  @dummy
  [(logs.push(1), 1)];
  static [(logs.push(2), 2)];
  [(logs.push(3), 3)];
}

console.log(logs);
```

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #16341 
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

In this PR we move the computed keys of static fields to the `computedKeyAssignments` when there are only class decorators. It happens to also fix the failing tests added in #16344 because the assignments are moved to the inner class.

<s>This PR contains commits from #16344, please only review the last commit. I will rebase once that PR is merged.</s>

### CODE REVIEW

File: packages/babel-plugin-proposal-decorators/test/fixtures/2023-11-classes/.replacement-static-private-environment-super-2/exec.js [hunk 1]
```diff
@@ -1,34 +0,0 @@
-{
```
Comment (JLHwung) [inline packages/babel-plugin-proposal-decorators/test/fixtures/2023-11-classes/.replacement-static-private-environment-super-2/exec.js]: This test is moved to the sub test "different private/super access in a non-decorated static method" in `replacement-static-private-environment-super/exec.js`.

**Review by liuxingbaoyu — APPROVED** [review]
This PR reminds me of https://github.com/babel/babel/issues/7690.

**Review by nicolo-ribaudo — APPROVED** [review]
Looks good, but could you add an input/output test? This one would be helpful to see what's going on: https://babeljs.io/repl/build/56517#?browsers=chrome%20120&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=N4KABGDGD2B2DOAXMAbaBzMBeMBtAugNwjhgACkKAhvPACICmkAjABRroCUpF1tjkAEzsM3CJRrwwAYTCgIEJFUQBLSHg4A6AA4BXeAAtWAIgDWzY5yKkINAJ6x1uLXsMnTgy_lYA3TnIBfYgUNDB19IzMAZi9gsACSCAYAD20mRBF0TQAraBVYVk5OTURoACEGVhswM2YAGg8GqLrjMABqMAB6Tpk-eABRFAYAWwZYRH6fKhRdZRU4aohjFjqhFvaunoBBbW0UOwFoACdlY_gAFWhpPsYAM3yVVQWQpchmyAAWVYBWVYA2Yx1TZQPr9ZKIE4ASVgjxU0xUAC8GEd4KROMQAkA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.24.0%2Bpr.16350&externalPlugins=%40babel%2Fplugin-proposal-decorators%407.23.9&assumptions=%7B%7D
```js
  @classDec1(log)
  @classDec2(log)
  class C {
    static [log.push("k1")];
    async [log.push("k2")](v) {};
    [log.push("k3")];
  }
```

**Review by nicolo-ribaudo — APPROVED** [review]
