### PR TITLE
fix: Destructuring exceptions in nested `for` expressions

### LINKED ISSUE #14840: [Bug]: Property init of ForStatement expected node to be of a type
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
for ( let x in Symbol.replace ) for ( var { } = x ; ; ) ;
```
Here is the [REPL](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=usage&corejs=3.21&spec=true&loose=true&code_lz=GYewTgBAFBA2CmAXCAPCBLAdhAygTwFsAjEWCAOgjHgAdYBDAY3ggEoJRIYA3eyAbwgBfCAF5UEANxS2UoA&debug=false&forceAllTransforms=true&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=unambiguous&lineWrap=true&presets=env&prettier=false&targets=&version=7.18.12&externalPlugins=&assumptions=%7B%7D)

### Configuration file name

babel.config.json

### Configuration

```json
{
  "sourceType": "unambiguous",
  "presets": ["@babel/preset-env"],
  "plugins": [
    "@babel/plugin-transform-runtime"
  ]
}
```

### Current and expected behavior

When Babel transpiles this code, it throws the following error:
```shell
Property init of ForStatement expected node to be of a type ["VariableDeclaration","Expression"] but instead got "ExpressionStatement"
```
However, the code can be run by node and transpiled by swc. This is the [repl](https://play.swc.rs/?version=1.2.224&code=H4sIAAAAAAAAA0vLL1LQUMhJLVGoUMjMUwiuzE3Kz1HQUyhKLchJTE5V0FRIA6soSyxSqFaoVbAFqrMGQk0FawCYxr0nOwAAAA%3D%3D&config=H4sIAAAAAAAAA0WMSwrDMAxE76K1t93kDj2EcJXg4B8eB2KM716ZumQlMe%2FNdDphaeuUuUDK%2FNBi5Zs2EhsYtrhcyaim0c4eMgxVLofUqeClzKcEWdRQcNHtbS7ZFHIR4EEcD%2F83hw6F9Llm0Km2rHdWQoonaDxDq%2BzwXvav%2FgXU82csuwAAAA%3D%3D)

### Environment

- babel 
- - ├── @babel/cli@7.18.6
- - ├── @babel/plugin-transform-runtime@7.18.6
- - ├── @babel/preset-env@7.18.6
- Node: [v17.3.0]
- npm version [8.5.2]
- os [ubuntu 20.04]

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #14840  
| Patch: Bug Fix?          |√
| Tests Added + Pass?      | √
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14841"></a>

### CODE REVIEW

File: packages/babel-plugin-transform-destructuring/src/util.ts [hunk 1]
```diff
@@ -620,6 +617,8 @@ export function convertVariableDeclaration(
     }
   }
 
+  const mustVarOrExpr = t.isForStatement(path.parent) && path.key !== "body";
```
Comment (JLHwung) [inline packages/babel-plugin-transform-destructuring/src/util.ts:620]:
```suggestion
  const inForInit = t.isForStatement(path.parent, { init: node })
```

I slightly prefer shorter variable name.

File: packages/babel-plugin-transform-destructuring/src/util.ts [hunk 2]
```diff
@@ -640,7 +639,11 @@ export function convertVariableDeclaration(
     if (!node.loc) {
       node.loc = nodeLoc;
     }
-    nodesOut.push(node);
+    nodesOut.push(
+      node.type === "ExpressionStatement" && mustVarOrExpr
```
Comment (JLHwung) [inline packages/babel-plugin-transform-destructuring/src/util.ts:643]: nit: can you swap `inForInit` before the type check?

File: packages/babel-plugin-transform-destructuring/test/fixtures/destructuring/for-expressions-nest/input.js [hunk 3]
```diff
@@ -0,0 +1 @@
+for ( let x in a ) for ( var { } = x ; ; ) ;
```
Comment (JLHwung) [inline packages/babel-plugin-transform-destructuring/test/fixtures/destructuring/for-expressions-nest/input.js:1]: Can you add a new test case? So that we cover the branch `inForInit === false` but `node` is an `ExpressionStatement`.

```js
for ( let x in a ) for ( ; ; ) var { } = x ;
```

**Review by JLHwung — APPROVED** [review]

File: packages/babel-plugin-transform-destructuring/test/fixtures/destructuring/for-expressions-nest/input.js (hunk 3 above)
Comment (JLHwung) [inline packages/babel-plugin-transform-destructuring/test/fixtures/destructuring/for-expressions-nest/input.js:1]: nit: `for-expression-nest` is a bit too general. Maybe `destructuring-empty-in-for-init`?

Comment (liuxingbaoyu) [reply packages/babel-plugin-transform-destructuring/test/fixtures/destructuring/for-expressions-nest/input.js:1]: Can I put the two tests together? Or can you suggest another test name?

Comment (JLHwung) [reply packages/babel-plugin-transform-destructuring/test/fixtures/destructuring/for-expressions-nest/input.js:1]: The other can be `destructuring-empty-in-for-body`.

File: packages/babel-plugin-transform-destructuring/test/fixtures/destructuring/destructuring-empty-in-for-body/input.js [hunk 4]
```diff
@@ -0,0 +1 @@
+for ( let x in y ) for ( ; ; ) var { } = x ;
```
Comment (JLHwung) [inline packages/babel-plugin-transform-destructuring/test/fixtures/destructuring/destructuring-empty-in-for-body/input.js:1]: We can test even more:
```js
for ( let x in y ) for ( ; { } = x ; {} = x ) var { } = x ;
```
So it will be empty destructuring in every children of ForStatement except `init`.

**Review by JLHwung — APPROVED** [review]

**Review by existentialism — APPROVED** [review]
