### PR TITLE
fix: `Infinity` in enums

### LINKED ISSUE #15768: [Bug]: TypeScript Enums With Global Properties Like `Infinity` or `NaN` Are Transpiled as Members
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```ts
enum StateEnum {
	okay = 0,
	error = -Infinity,
}
```
[REPL v7.22.8](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=MYewdgzgLgBAbjAvDALAJgNwCgsFMwCuAtjAMpQCGUuAooSQN5YCQIA1hQJ5IwAMANCzC4A5jwC0ASTAAzAJZg5UToOYAHEBB7T5i5arAUwPAHIUTq3AA9YyOIIC-QA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=typescript&prettier=false&targets=&version=7.22.8&externalPlugins=&assumptions=%7B%7D) - Buggy
[REPL v7.20.15](https://babel.dev/repl#?browsers=&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=MYewdgzgLgBAbjAvDALAJgNwCgsFMwCuAtjAMpQCGUuAooSQN5YCQIA1hQJ5IwAMANCzC4A5jwC0ASTAAzAJZg5UToOYAHEBB7T5i5arAUwPAHIUTq3AA9YyOIIC-QA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=typescript&prettier=false&targets=&version=7.20.15&externalPlugins=&assumptions=%7B%7D) - Okay

### Configuration file name

_No response_

### Configuration

see REPL

### Current and expected behavior

Input:
```ts
const v = 42;

enum StateEnum {
	okay = 0,
	neg = -Infinity,
	pos = Infinity,
	nan = NaN,
	ext = v,
}
```

Buggy Result (7.22.8):
```js
const v = 42;
var StateEnum = function (StateEnum) {
  StateEnum[StateEnum["okay"] = 0] = "okay";
  StateEnum[StateEnum["neg"] = -StateEnum.Infinity] = "neg";
  StateEnum[StateEnum["pos"] = StateEnum.Infinity] = "pos";
  StateEnum[StateEnum["nan"] = StateEnum.NaN] = "nan";
  StateEnum[StateEnum["ext"] = 42] = "ext";
  return StateEnum;
}(StateEnum || {});
```
Correct old Result (7.20.15):
```js
const v = 42;
var StateEnum;
(function (StateEnum) {
  StateEnum[StateEnum["okay"] = 0] = "okay";
  StateEnum[StateEnum["neg"] = -Infinity] = "neg";
  StateEnum[StateEnum["pos"] = Infinity] = "pos";
  StateEnum[StateEnum["nan"] = NaN] = "nan";
  StateEnum[StateEnum["ext"] = v] = "ext";
})(StateEnum || (StateEnum = {}));
```

In the buggy version not `Infinity` is used, but `StateEnum.infinity` - which is `undefined`

### Environment

- REPL 7.22.8

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #15768 
| Patch: Bug Fix?          | √
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | √
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15774"></a>

### CODE REVIEW

File: packages/babel-plugin-transform-typescript/test/fixtures/regression/15768/output.js [hunk 1]
```diff
@@ -0,0 +1,12 @@
+const v = 42;
+const v2 = Infinity;
+var Infinity = 1; // Known inconsistencies
+var StateEnum = /*#__PURE__*/function (StateEnum) {
+  StateEnum[StateEnum["okay"] = 0] = "okay";
+  StateEnum[StateEnum["neg"] = -Infinity] = "neg";
+  StateEnum[StateEnum["pos"] = Infinity] = "pos";
+  StateEnum[StateEnum["nan"] = NaN] = "nan";
+  StateEnum[StateEnum["ext"] = 42] = "ext";
+  StateEnum[StateEnum["ext2"] = 1] = "ext2";
```
Comment (liuxingbaoyu) [inline packages/babel-plugin-transform-typescript/test/fixtures/regression/15768/output.js:10]: This is inconsistent with TS, if we want to align, it is most convenient to add a feature in `traverse`.

File: packages/babel-plugin-transform-typescript/test/fixtures/regression/15768/input.ts [hunk 2]
```diff
@@ -0,0 +1,11 @@
+const v = 42;
+const v2 = Infinity;
+var Infinity = 1; // Known inconsistencies
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-typescript/test/fixtures/regression/15768/input.ts:3]: Note that in scripts this doesn't actually change the value of `Infinity`. However, there is another case in which it does and TS is not behaving as I would expect: https://github.com/microsoft/TypeScript/issues/54981

**Review by nicolo-ribaudo — APPROVED** [review]
Also related: https://github.com/microsoft/TypeScript/issues/48956
