### PR TITLE
Fix jsx-source to not fail without filename

### LINKED ISSUE #5909: transform-react-jsx-source throws error - strongly expects a fileName being passed
```
TypeError: unknown: Property value expected type of string but got null
  
  at Object.validate (node_modules/babel-types/lib/definitions/index.js:161:13)
  at validate (node_modules/babel-types/lib/index.js:505:9)
  at Object.builder (node_modules/babel-types/lib/index.js:466:7)
  at PluginPass.JSXOpeningElement (node_modules/babel-plugin-transform-react-jsx-source/lib/index.js:35:68)
  at newFn (node_modules/babel-traverse/lib/visitors.js:276:21)
  at NodePath._call (node_modules/babel-traverse/lib/path/context.js:76:18)
  at NodePath.call (node_modules/babel-traverse/lib/path/context.js:48:17)
  at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:105:12)
```

This is the test suite of [babel-preset-edge](https://github.com/sebastian-software/babel-preset-edge) when running the "jest" testrunner.

The babel config is dynamically created based on babel-preset-env, fast-async, react, lodash, ...

It seems to throw in this area (from babel-plugin-transform-react-jsx-source/lib/index.js) at version 6.22.0:

```js
if (!state.fileNameIdentifier) {
  var fileName = state.file.log.filename !== "unknown" ? state.file.log.filename : null;

  var fileNameIdentifier = path.scope.generateUidIdentifier(FILE_NAME_VAR);
  path.hub.file.scope.push({ id: fileNameIdentifier, init: t.stringLiteral(fileName) });
  state.fileNameIdentifier = fileNameIdentifier;
}
```

This here is the thing which throws:

```js
t.stringLiteral(fileName)
```

It seems to expect that the `fileName` is always a valid string. Unfortunately as we can see a few lines above `fileName` could be also `null`. Somehow there should be a workaround for this.

In my case the error is gone when changing the first line from above snippet to:

```js
var fileName = state.file.log.filename !== "unknown" ? state.file.log.filename : "";
```

I am just not sure whether this makes any sense.

### PR DESCRIPTION
**Pull request by danez**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues             | Fixes #5909
| Patch: Bug Fix?          | 👍
| Major: Breaking Change?  | 
| Minor: New Feature?      | 
| Tests Added/Pass?        | 
| Spec Compliancy?         | 
| License                  | MIT
| Doc PR                   | 
| Any Dependency Changes?  | 

This is an easy fix for the jsx-source transform to not throw in case the filename was not provided.

Should I add a test?

### CODE REVIEW

File: packages/babel-plugin-transform-react-jsx-source/src/index.js [hunk 1]
```diff
@@ -50,7 +50,8 @@ export default function({ types: t }) {
       }
 
       if (!state.fileNameIdentifier) {
-        const fileName = state.file.opts.filename;
+        // Default to an empty string in case no filename was supplied in the transform
```
Comment (hzoo) [inline packages/babel-plugin-transform-react-jsx-source/src/index.js]: comment doesn't seem to be necessary?

**Comment by hzoo** [comment]
We should add a test if it's not bad
