### PR TITLE
fix: Pure comments missing parentheses

### LINKED ISSUE #14797: [Bug]: Pure annotations are incorrectly modified to wrong scope
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
(/* @__PURE__ */ f()).g()
```

[REPL Link](https://babel.dev/repl#?browsers=&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=BQegVABAAg-jAKBVASgUThMIIDNgEp8A6AcwKA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=&prettier=false&targets=&version=7.18.9&externalPlugins=&assumptions=%7B%7D)

### Configuration file name

_No response_

### Configuration

None

### Current and expected behavior

Currently babel strips the parentheses of `(/* @__PURE__ */ f())`, causing the whole expression `f().g()` be marked as pure.

```js
/* @__PURE__ */
f().g();

// expect: same as input
```

### Environment

```
System:
  OS: macOS 12.5
Binaries:
  Node: 18.6.0 - /usr/local/bin/node
  Yarn: 1.22.19 - /usr/local/bin/yarn
  npm: 8.15.0 - /usr/local/bin/npm
npmPackages:
  @babel/core: ^7.7.4 => 7.18.9
  @babel/plugin-proposal-class-properties: ^7.7.4 => 7.18.6
  @babel/plugin-proposal-object-rest-spread: ^7.7.4 => 7.18.9
  @babel/plugin-transform-modules-commonjs: ^7.15.0 => 7.18.6
  @babel/preset-env: ^7.7.4 => 7.18.9
  @babel/preset-react: ^7.7.4 => 7.18.6
  @babel/preset-typescript: ^7.7.4 => 7.18.6
  babel-loader: ^8.0.6 => 8.2.5
  webpack: ^5.74.0 => 5.74.0
```

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #14797 
| Patch: Bug Fix?          | √
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | √
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

**Review by nicolo-ribaudo — APPROVED** [review]

File: packages/babel-generator/src/printer.ts [hunk 1]
```diff
@@ -674,13 +664,22 @@ class Printer {
...
+    let shouldPrintParens =
       forceParens ||
       (format.retainFunctionParens &&
         nodeType === "FunctionExpression" &&
         node.extra?.parenthesized) ||
       needsParens(node, parent, this._printStack);
 
+    if (
+      !shouldPrintParens &&
+      parent?.type === "MemberExpression" &&
```
Comment (JLHwung) [inline packages/babel-generator/src/printer.ts:676]: I think we don't have to limit the parent type. If there are leading comments and the node is parenthesized, it suggests that users intend to keep comments within the parentheses. Examples are
```js
(/* @__PURE__ */ f())()
(/* @__PURE__ */ f())?.bar
(/* @__PURE__ */ f())`bar`
```

Comment (liuxingbaoyu) [reply packages/babel-generator/src/printer.ts:676]:
```
    -       var c = /*#__PURE__*/function () {
    +       var c = ( /*#__PURE__*/function () {
```

```
    -       setTimeout( /*#__PURE__*/function () {
    +       setTimeout(( /*#__PURE__*/function () {
```
Unfortunately there are some unexpected situations.

**Review by JLHwung — APPROVED** [review]

**Review by AnimeshRy — APPROVED** [review]
