### PR TITLE
fix: Computed properties should keep original definition order

### LINKED ISSUE #15140: [Bug]: Getter should be shadowed by shorthand property
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Other (Next.js, Gatsby, vue-cli, ...)

### Input code

```js
// Here, both x's before and after the getter are required to trigger the bug.
var x = { x , get x ( ) { return 0; } , x } ;
x.x = 1;
console.log(x.x);
```

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

`x`'s property `x.x` should be writable in the input code but it is not in the transpiled code.

### Current behavior

`x.x` is not writable:
```console
$ node output.js
0
```
### Expected behavior

`x.x` is writable:
```console
$ node input.js
1 // x.x became 1
```

### Environment

[Reproduction on Babel's own REPL](https://babeljs.io/repl#?browsers=since%202015&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=G4QwTgBAHhC8EG9oQDQQOYFMAuyAUEAlIhGDgK5gB2EADANwQC-qyL9AUFAHQzwCMnAMYB7KgGcRAG0zcpI9Hh5RC9IA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.20.1&externalPlugins=&assumptions=%7B%7D)

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by SuperSodaSea**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #15140
| Patch: Bug Fix?          | :+1:
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  | :+1:
| License                  | MIT

`@babel/plugin-transform-computed-properties` use an `_mutatorMap` to hold the accessor computed properties in an object initializer, and use `defineEnumerableProperties` to define them at the end of initialization, which can change the definition order. This PR change it to use new helper function `defineAccessor` to define accessor computed properties in place, keeping the original definition order.

##### :heavy_plus_sign: Added
- babel-plugin-transform-computed-properties/test/fixtures/assumption-setComputedProperties/single-accessor
- babel-plugin-transform-computed-properties/test/fixtures/spec/definition-order
- babel-plugin-transform-computed-properties/test/fixtures/spec/single-accessor

##### :wavy_dash: Output Changed
- babel-plugin-transform-computed-properties/test/fixtures/assumption-setComputedProperties/accessors
- babel-plugin-transform-computed-properties/test/fixtures/assumption-setComputedProperties/symbol
- babel-plugin-transform-computed-properties/test/fixtures/spec/accessors
- babel-plugin-transform-computed-properties/test/fixtures/spec/symbol

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15232"></a>

### CODE REVIEW

File: packages/babel-helpers/src/helpers/defineAccessor.js [hunk 1]
```diff
@@ -0,0 +1,8 @@
+/* @minVersion 7.20.6 */
```
Comment (SuperSodaSea) [inline packages/babel-helpers/src/helpers/defineAccessor.js:1]: Not sure if this is the correct `minVersion`...

File: packages/babel-plugin-transform-computed-properties/test/fixtures/regression/15140/exec.js [hunk 2]
```diff
@@ -0,0 +1,3 @@
+var x = { x, get x() { return 0; }, x };
```
Comment (liuxingbaoyu) [inline packages/babel-plugin-transform-computed-properties/test/fixtures/regression/15140/exec.js:1]: > packages/babel-plugin-transform-computed-properties/test/fixtures/regression/15140/exec.js

This doesn't appear to be a regression.

Comment (JLHwung) [reply packages/babel-plugin-transform-computed-properties/test/fixtures/regression/15140/exec.js:1]: `spec/definition-ordering` looks good to me, also `loose/definition-ordering` if it works.

Comment (SuperSodaSea) [reply packages/babel-plugin-transform-computed-properties/test/fixtures/regression/15140/exec.js:1]: Oops, seems that I misunderstood the meaning of "regression". Then the name of the tests in my previous PR #15183 and #15194 may also be wrong...

Comment (SuperSodaSea) [reply packages/babel-plugin-transform-computed-properties/test/fixtures/regression/15140/exec.js]: Now the test is renamed to `spec/definition-order`. It doesn't apply to `loose` or `assumption-setComputedProperties`.

File: packages/babel-helpers/src/helpers/defineAccessor.js (hunk 1 above)
Comment (nicolo-ribaudo) [reply packages/babel-helpers/src/helpers/defineAccessor.js:1]: We will need to update it when releasing, could you update the Makefile like I did in https://github.com/babel/babel/commit/80c6889342160b783f5eb309055685d95e683317?

File: packages/babel-plugin-transform-computed-properties/test/fixtures/assumption-setComputedProperties/accessors/output.js [hunk 3]
```diff
@@ -1,10 +1,10 @@
-var _foobar, _foobar2, _test, _test2, _obj, _mutatorMap;
-var obj = (_obj = {}, _foobar = foobar, _mutatorMap = {}, _mutatorMap[_foobar] = _mutatorMap[_foobar] || {}, _mutatorMap[_foobar].get = function () {
+var _obj;
+var obj = (_obj = {}, babelHelpers.defineAccessor(_obj, foobar, "get", function () {
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-computed-properties/test/fixtures/assumption-setComputedProperties/accessors/output.js:2]: This is very nitpicky, the PR is very good as it is.

However, `babelHelpers.defineAccessor("get", _obj, foobar, function () {` gzips better, because gzip can deduplicate all the `defineAccessor("get",` parts in the code to refer to the same byte sequence. With `defineAccessor(_obj, foobar, "get"`, the only constant part that gzip can easily deduplicate is only `defineAccessor(`, because the `_obj` variable will likely have a different name for different calls.

File: packages/babel-plugin-transform-computed-properties/test/fixtures/spec/definition-order/exec.js [hunk 4]
```diff
@@ -0,0 +1,16 @@
...
+};
+expect(Object.keys(a)).toStrictEqual(["x", "y"]);
+
+var b = {
+  get ["x"]() { return 0; },
+  ["x"]: 1,
+};
+expect(b.x).toBe(1);
+
+var x = { x, get x() { return 0; }, x };
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-computed-properties/test/fixtures/spec/definition-order/exec.js:13]: Nit, can you use two different variables?
```js
var y = { x, get x() { return 0; }, x };
```

File: packages/babel-helpers/src/helpers/defineAccessor.js (hunk 1 above)
Comment (SuperSodaSea) [reply packages/babel-helpers/src/helpers/defineAccessor.js:1]: Done in 16758f36e8013998b4d80bce0dfc68ed8aa1df6e.

File: packages/babel-plugin-transform-computed-properties/test/fixtures/assumption-setComputedProperties/accessors/output.js (hunk 3 above)
Comment (SuperSodaSea) [reply packages/babel-plugin-transform-computed-properties/test/fixtures/assumption-setComputedProperties/accessors/output.js]: Done in 1fd56a3c4e900159ae31202c5aae8e90c88042c6.

**Review by nicolo-ribaudo — APPROVED** [review]

**Comment by SuperSodaSea** [comment]
Oh, I found a problem: using `@babel/plugin-transform-computed-properties` without `@babel/plugin-transform-spread` will silently remove the spread in object initializer ([REPL](https://babeljs.io/repl/build/53561/#?browsers=&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=IYAgvCDeDaAeC6AuEBGANCAdNgngXyA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=react%2Cstage-2&prettier=false&targets=&version=7.20.6%2Bpr.15232&externalPlugins=%40babel%2Fplugin-transform-computed-properties%407.18.9&assumptions=%7B%7D)). Maybe we need to throw an Error in this situation.

**Comment by nicolo-ribaudo** [comment]
Could you open a separate PR for that? :pray:

**Comment by liuxingbaoyu** [comment]
Just confused: I noticed a new helper was added, do we need to maintain compatibility without helpers? @nicolo-ribaudo

**Comment by nicolo-ribaudo** [comment]
@liuxingbaoyu You are right!

@SuperSodaSea When using the new version of this plugin with older `@babel/core`/`@babel/helpers` versions, the new helper won't be available and we need a fallback.

We could do something like this:
```js
function buildHelperCall(file, type, obj, name, fn) {
  if (file.availableHelper("defineAccessor")) {
    return t.callExpression(file.addHelper("defineAccessor"), [type, obj, name, fn]));
  }

  // Fallback for @babel/helpers <= 7.20.6
  return template.expression.ast`
    Object.defineProperty(${obj}, ${name}, {
      ${type}: ${fn},
      enumerable: true,
      configurable: true
    })
  `;
}
```

We don't currently have a way to test this, other than manually by replacing the `availableHelper` call with just `false`.

**Comment by SuperSodaSea** [comment]
@nicolo-ribaudo

> Could you open a separate PR for that? 🙏

I'll do that after this PR is merged.

> When using the new version of this plugin with older `@babel/core`/`@babel/helpers` versions, the new helper won't be available and we need a fallback.

Or maybe we just don't need a new helper function and always use `Object.defineProperty` directly. What's your opinion?

**Comment by liuxingbaoyu** [comment]
> Or maybe we just don't need a new helper function and always use `Object.defineProperty` directly. What's your opinion?

I'm concerned that this will slightly severely impact the output size.
Although this results in the user having to use a bundler, we already do.

Also I guess we can add helpers directly into the code? While this may result in a global variable, we currently have similar behavior and this should have no side effects.
`path.scope.generateDeclaredUidIdentifier`

File: packages/babel-plugin-transform-computed-properties/src/index.ts [hunk 5]
```diff
@@ -26,6 +27,44 @@ export default declare((api, options: Options) => {
...
+          helperDeclaration,
+        )[0];
+        // TODO: NodePath#unshiftContainer should automatically register new bindings.
+        file.scope.registerDeclaration(helperPath);
+      }
+      helper = t.cloneNode(helper);
+    }
+
+    return t.callExpression(helper, [t.stringLiteral(type), obj, key, fn]);
+  }
```
Comment (SuperSodaSea) [inline packages/babel-plugin-transform-computed-properties/src/index.ts:66]: Now the helper function is directly added to the file scope if it is not available. For example:
```js
var obj = {
  get ["x" + foo]() { return "heh"; }
};
```
The output would be:
```diff
- var obj = babelHelpers.defineAccessor("get", {}, "x" + foo, function () {
+ function _defineAccessor(type, obj, key, fn) {
+   var desc = {
+     configurable: true,
+     enumerable: true
+   };
+   desc[type] = fn;
+   return Object.defineProperty(obj, key, desc);
+ }
+ var obj = _defineAccessor("get", {}, "x" + foo, function () {
    return "heh";
  });
```

**Comment by liuxingbaoyu** [comment]
```
From ddf2251f435c6f3c7e622644ee2965183532f01a Mon Sep 17 00:00:00 2001
From: liuxingbaoyu <30521560+liuxingbaoyu@users.noreply.github.com>
Date: Sat, 3 Dec 2022 04:20:55 +0800
Subject: [PATCH] tmp

---
 .../src/transformation/file/file.ts           |  2 +-
 .../src/index.ts                              | 33 +++++++++----------
 2 files changed, 17 insertions(+), 18 deletions(-)

diff --git a/packages/babel-core/src/transformation/file/file.ts b/packages/babel-core/src/transformation/file/file.ts
index cf687fb0b1..0a7b370f27 100644
--- a/packages/babel-core/src/transformation/file/file.ts
+++ b/packages/babel-core/src/transformation/file/file.ts
@@ -210,7 +210,7 @@ export default class File {
     });
 
     nodes.forEach(node => {
-      // @ts-expect-error Fixeme: document _compact node property
+      // @ts-expect-error Fixme: document _compact node property
       node._compact = true;
     });
 
diff --git a/packages/babel-plugin-transform-computed-properties/src/index.ts b/packages/babel-plugin-transform-computed-properties/src/index.ts
index 0f911ecc9e..8d23d849c9 100644
--- a/packages/babel-plugin-transform-computed-properties/src/index.ts
+++ b/packages/babel-plugin-transform-computed-properties/src/index.ts
@@ -17,6 +17,15 @@ type PropertyInfo = {
   state: PluginPass;
 };
 
+const DefineAccessorHelper = template.expression.ast`
+function (type, obj, key, fn) {
+  var desc = { configurable: true, enumerable: true };
+  desc[type] = fn;
+  return Object.defineProperty(obj, key, desc);
+}`;
+// @ts-expect-error undocumented _compact node property
+DefineAccessorHelper._compact = true;
+
 export default declare((api, options: Options) => {
   api.assertVersion(7);
 
@@ -40,24 +49,14 @@ export default declare((api, options: Options) => {
     } else {
       // Fallback for @babel/helpers <= 7.20.6, manually add helper function
       const file = state.file;
-      helper = file.declarations["defineAccessor"];
+      helper = file.get("fallbackDefineAccessorHelper");
       if (!helper) {
-        helper = file.declarations["defineAccessor"] =
-          file.scope.generateUidIdentifier("defineAccessor");
-
-        const helperDeclaration = template.statement.ast`
-          function ${helper}(type, obj, key, fn) {
-            var desc = { configurable: true, enumerable: true };
-            desc[type] = fn;
-            return Object.defineProperty(obj, key, desc);
-          }      
-        `;
-        const helperPath = file.path.unshiftContainer(
-          "body",
-          helperDeclaration,
-        )[0];
-        // TODO: NodePath#unshiftContainer should automatically register new bindings.
-        file.scope.registerDeclaration(helperPath);
+        const id = file.scope.generateUidIdentifier("defineAccessor");
+        file.scope.push({
+          id,
+          init: DefineAccessorHelper,
+        });
+        file.set("fallbackDefineAccessorHelper", (helper = id));
       }
       helper = t.cloneNode(helper);
     }
-- 
2.38.1.windows.1
```
image
image

It seems better that way.

**Comment by SuperSodaSea** [comment]
Thanks @liuxingbaoyu!

File: packages/babel-plugin-transform-computed-properties/src/index.ts [hunk 6]
```diff
@@ -12,10 +14,18 @@ type PropertyInfo = {
   body: t.Statement[];
   computedProps: t.ObjectMember[];
   initPropExpression: t.ObjectExpression;
-  getMutatorId: () => t.Identifier;
   state: PluginPass;
 };
 
+const DefineAccessorHelper = template.expression.ast`
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-computed-properties/src/index.ts:20]:
```suggestion
// TODO(Babel 8): Remove this.
const DefineAccessorHelper = template.expression.ast`
```

File: packages/babel-plugin-transform-computed-properties/src/index.ts [hunk 7]
```diff
@@ -26,10 +36,33 @@ export default declare((api, options: Options) => {
...
+    type: "get" | "set",
+    obj: t.Expression,
+    key: t.Expression,
+    fn: t.Expression,
+  ) {
+    let helper: t.Identifier;
+    if (state.availableHelper("defineAccessor")) {
+      helper = state.addHelper("defineAccessor");
+    } else {
+      // Fallback for @babel/helpers <= 7.20.6, manually add helper function
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-computed-properties/src/index.ts:50]:
```suggestion
      // Fallback for @babel/helpers <= 7.20.6, manually add helper function
      // TODO(Babel 8): Remove this
```

**Review by nicolo-ribaudo — APPROVED** [review]

**Review by liuxingbaoyu — APPROVED** [review]
