### PR TITLE
typescript: Properly set this.state.inType one token before parsing a type

### LINKED ISSUE #6665: [Presets: React + Typescript] Complex method with generic type fails during transpilation
> Issue originally reported by @babel-bot in babel/babylon#775

Original issue submitted by @pbadenski in https://github.com/babel/babel/issues/6567

Bug.

### Input Code
https://github.com/pbadenski/babel-typescript-sample

```js
const liftA2 = <T, V> (x: X<T, V>): (f: Function) => null;
```

### Babel Configuration

After checking out the code at the link above:
```npm run transpile```

### Current Behavior
```
{ SyntaxError: src/a.ts: Unexpected token (1:17)
> 1 | const liftA2 = <T, V> (x: X<T, V>): (f: Function) => null;
    |                  ^
  2 | 
    at _class.raise (/Users/pbadenski/workspace/babel-typescript-sample/node_modules/babylon/lib/index.js:807:15)
    at _class.unexpected (/Users/pbadenski/workspace/babel-typescript-sample/node_modules/babylon/lib/index.js:2108:16)
    at _class.jsxParseIdentifier (/Users/pbadenski/workspace/babel-typescript-sample/node_modules/babylon/lib/index.js:8031:14)
    at _class.jsxParseNamespacedName (/Users/pbadenski/workspace/babel-typescript-sample/node_modules/babylon/lib/index.js:8042:23)
    at _class.jsxParseAttribute (/Users/pbadenski/workspace/babel-typescript-sample/node_modules/babylon/lib/index.js:8134:24)
    at _class.jsxParseOpeningElementAt (/Users/pbadenski/workspace/babel-typescript-sample/node_modules/babylon/lib/index.js:8146:35)
    at _class.jsxParseElementAt (/Users/pbadenski/workspace/babel-typescript-sample/node_modules/babylon/lib/index.js:8167:33)
    at _class.jsxParseElement (/Users/pbadenski/workspace/babel-typescript-sample/node_modules/babylon/lib/index.js:8228:19)
    at _class.parseExprAtom (/Users/pbadenski/workspace/babel-typescript-sample/node_modules/babylon/lib/index.js:8238:21)
    at _class.parseExprSubscripts (/Users/pbadenski/workspace/babel-typescript-sample/node_modules/babylon/lib/index.js:2864:21) pos: 17, loc: null }
```

### Context
Using https://github.com/gcanti/fp-ts

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  next (7.0.0-beta.3)
| babel-preset-typescript | next (7.0.0-beta.3)
| babel-preset-react | next (7.0.0-beta.3)
| node             | v8.8.1
| npm              | 5.5.1
| Operating System | Mac OS X 10.12.6

### PR DESCRIPTION
**Pull request by andy-ms**
| Q                        | A
| ------------------------ | ---
| Fixed Issues?            | Fixes #6665
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | Yes
| Documentation PR         |
| Any Dependency Changes?  | No
| License                  | MIT

Ensures that we set `this.state.inType` before we parse any type tokens; this ensures that any tokens that are part of a type are never parsed as JSX.
This is an alternative to the fix in #6828; this emulates what flow does, which is to set `this.state.inType` before doing any type parsing. Test cases are taken from #6828.

### CODE REVIEW

File: packages/babylon/src/plugins/typescript.js [hunk 1]
```diff
@@ -802,10 +797,11 @@ export default (superClass: Class<Parser>): Class<Parser> =>
     tsTryParseTypeArgumentsInExpression(): ?N.TsTypeParameterInstantiation {
       return this.tsTryParseAndCatch(() => {
         const res: N.TsTypeParameterInstantiation = this.startNode();
-        this.expectRelational("<");
-        const typeArguments = this.tsParseDelimitedList(
-          "TypeParametersOrArguments",
-          this.tsParseType.bind(this),
+        const typeArguments = this.tsExpectLessThanThenParseInType(() =>
+          this.tsParseDelimitedList(
```
Comment (nicolo-ribaudo) [inline packages/babylon/src/plugins/typescript.js]: I think that this would be more redable, since long names can be hard to read:
```js
const typeArguments = this.tsInType(() => {
  this.expectRelational("<");
  this.tsParseDelimitedList(
```
