### PR TITLE
[ts] Error on invalid type casts in JSX

### LINKED ISSUE #12215: No syntax error is thrown for invalid TSTypeCastExpression at JSX expression wrapped in parentheses
## Bug Report

**Current behavior**

`ReferenceError: test.tsx: unknown node of type "TSTypeCastExpression" with constructor "Node"`

**Input Code**

```tsx
function Foo() {
  return (
    <div prop={[ key: value ]} />
  );
}
```

**Expected behavior**

Throw syntax error `Did not expect a type annotation here.`.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "presets": ["@babel/preset-typescript"]
}
```

**Environment**
```
  System:
    OS: Linux 4.4 Ubuntu 16.04.7 LTS (Xenial Xerus)
  Binaries:
    Node: 10.15.1 - ~/local/lib/node-v10.15.1-linux-x64/bin/node
    Yarn: 1.22.4 - ~/local/lib/node-v10.15.1-linux-x64/bin/yarn
    npm: 6.9.0 - ~/local/lib/node-v10.15.1-linux-x64/bin/npm
  npmPackages:
    @babel/cli: ^7.12.1 => 7.12.1 
    @babel/core: ^7.12.3 => 7.12.3 
    @babel/polyfill: ^7.12.1 => 7.12.1 
    @babel/preset-env: ^7.12.1 => 7.12.1 
    @babel/preset-typescript: ^7.12.1 => 7.12.1 
```

### PR DESCRIPTION
**Pull request by existentialism**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #12215
| Patch: Bug Fix?          | Y
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/12221"></a>

### CODE REVIEW

**Comment by JLHwung** [comment]
The e2e error is not related: https://github.com/browserify/resolve/commit/205b6602ba73935ed4c6b547a4838d855cf5d0fb

File: packages/babel-parser/src/plugins/estree.js [hunk 1]
```diff
@@ -379,16 +379,19 @@ export default (superClass: Class<Parser>): Class<Parser> =>
       return node;
     }
 
-    toReferencedListDeep(
-      exprList: $ReadOnlyArray<?N.Expression>,
-      isParenthesizedExpr?: boolean,
-    ): void {
+    finishCoverCallExpressionArguments(
```
Comment (kaicataldo) [inline packages/babel-parser/src/plugins/estree.js:382]: Trying to understand this method name. For my understanding, would you mind explaining it?

Comment (existentialism) [reply packages/babel-parser/src/plugins/estree.js:382]: It's just mirroring:

https://github.com/babel/babel/blob/4fe8c3acc5934268682d53714e9f42c49f7e8fcb/packages/babel-parser/src/parser/expression.js#L709

Ref: https://tc39.es/ecma262/#prod-CoverCallExpressionAndAsyncArrowHead

Comment (JLHwung) [reply packages/babel-parser/src/plugins/estree.js:382]: The `Cover` prefix means that it is ambiguous: It can be a call expression _or_ an async arrow. In this case it seems to me at the time when `finishCoverCallExpressionArguments` is called, it is indeed a call expression.

However `finishCallExpressionArguments` is a bit confused, since we have called `finishCallExpression` before. Maybe just `toReferencedArguments`? (Naming is hard)

File: packages/babel-parser/src/parser/expression.js [hunk 2]
```diff
@@ -791,6 +791,13 @@ export default class ExpressionParser extends LValParser {
     return node;
   }
 
+  finishCoverCallExpressionArguments(
+    node: N.CallExpression | N.OptionalCallExpression,
+    isParenthesizedExpr?: boolean,
```
Comment (JLHwung) [inline packages/babel-parser/src/parser/expression.js:796]: Is `isParenthesizedExpr` ever used? If not we can simply remove it.

File: packages/babel-parser/src/plugins/estree.js (hunk 1 above)
Comment (existentialism) [reply packages/babel-parser/src/plugins/estree.js:382]: > Naming is hard

Indeed it is, we also have `parseCallExpressionArguments` lol

File: packages/babel-parser/src/parser/expression.js (hunk 2 above)
Comment (existentialism) [reply packages/babel-parser/src/parser/expression.js:796]: It is in the flow plugin... I left it in just to keep all the sites consistent

File: packages/babel-parser/src/parser/expression.js [hunk 3]
```diff
@@ -2057,14 +2064,6 @@ export default class ExpressionParser extends LValParser {
       refExpressionErrors,
       node,
     );
-    if (canBePattern && !this.state.maybeInArrowParameters) {
```
Comment (existentialism) [inline packages/babel-parser/src/parser/expression.js:2060]: This is now moved to the flow plugin (since it doesn't apply to TypeScript)

File: packages/babel-parser/src/plugins/estree.js (hunk 1 above)
Comment (existentialism) [reply packages/babel-parser/src/plugins/estree.js]: I renamed it `toReferencedArguments` as I struggled a bit with it, happy to rename again if someone can cook something up.

Comment (kaicataldo) [reply packages/babel-parser/src/plugins/estree.js]: Thanks for the explanation :+1:

**Review by JLHwung — APPROVED** [review]

**Review by kaicataldo — APPROVED** [review]
