### PR TITLE
fix(parser): throw error with wrong typescript 'export declare'

### LINKED ISSUE #12658: No syntax error is thrown for non-declaration following TypeScript `export declare`
## Bug Report

**Current behavior**

Parsing succeeds without a syntax error.

**Input Code**

```js
export declare foo;
```

**Expected behavior**

A syntax error should be thrown.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "presets": ["@babel/preset-typescript"]
}
```

**Environment**
```
  System:
    OS: Linux 4.4 Ubuntu 16.04.7 LTS (Xenial Xerus)
  Binaries:
    Node: 10.15.1 - ~/local/lib/node-v10.15.1-linux-x64/bin/node
    Yarn: 1.22.4 - ~/local/lib/node-v10.15.1-linux-x64/bin/yarn
    npm: 6.9.0 - ~/local/lib/node-v10.15.1-linux-x64/bin/npm
  npmPackages:
    @babel/cli: ^7.12.10 => 7.12.10 
    @babel/core: ^7.12.10 => 7.12.10 
    @babel/polyfill: ^7.12.1 => 7.12.1 
    @babel/preset-env: ^7.12.11 => 7.12.11 
    @babel/preset-typescript: ^7.12.7 => 7.12.7 
```

### PR DESCRIPTION
**Pull request by fedeci**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #12658  
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

We check if after the first `declare` there is an exportable value.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/12684"></a>

### CODE REVIEW

File: packages/babel-parser/src/plugins/typescript/index.js [hunk 1]
```diff
@@ -2281,6 +2281,13 @@ export default (superClass: Class<Parser>): Class<Parser> =>
       // "export declare" is equivalent to just "export".
       const isDeclare = this.eatContextual("declare");
 
+      if (
+        this.isContextual("declare") ||
+        !this.shouldParseExportDeclaration()
+      ) {
+        super.unexpected(this.state.start, this.state.value);
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/src/plugins/typescript/index.js:2288]: Nit: we always use `this`, unless it's actually needed to use `super`.

```suggestion
        this.unexpected(this.state.start, this.state.value);
```

File: packages/babel-parser/test/fixtures/typescript/export/declare-invalid/options.json [hunk 2]
```diff
@@ -0,0 +1,7 @@
+{
+  "sourceType": "module",
+  "plugins": [
+    "typescript"
+  ],
+  "throws": "foo (1:15)"
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/test/fixtures/typescript/export/declare-invalid/options.json:6]: We can throw a better error here. What about `"export declare" must be followed by an ambient declaration`?

You can add it to the `TSErrors` object, and then use `throw this.raise` rather than `this.unexpected`.

Comment (fedeci) [reply packages/babel-parser/test/fixtures/typescript/export/declare-invalid/options.json:6]: Sure👍🏻

File: packages/babel-parser/src/plugins/typescript/index.js (hunk 1 above)
Comment (fedeci) [reply packages/babel-parser/src/plugins/typescript/index.js:2288]: 🤦🏻‍♂️I missed that

File: packages/babel-parser/src/plugins/typescript/index.js [hunk 3]
```diff
@@ -2281,6 +2283,16 @@ export default (superClass: Class<Parser>): Class<Parser> =>
       // "export declare" is equivalent to just "export".
       const isDeclare = this.eatContextual("declare");
 
+      if (
+        this.isContextual("declare") ||
+        !this.shouldParseExportDeclaration()
```
Comment (JLHwung) [inline packages/babel-parser/src/plugins/typescript/index.js:2288]: nit: We should limit the extra check to `isDeclare === true`. When `isDeclare` is `false`, since no token was eaten, `shouldParseExportDeclaration()` is always `true` because

https://github.com/babel/babel/blob/446c70c6c3367565dafbcb98431442391eddd725/packages/babel-parser/src/parser/statement.js#L1799-L1804

**Review by JLHwung — APPROVED** [review]

File: packages/babel-parser/src/plugins/typescript/index.js [hunk 4]
```diff
@@ -2281,6 +2283,16 @@ export default (superClass: Class<Parser>): Class<Parser> =>
       // "export declare" is equivalent to just "export".
       const isDeclare = this.eatContextual("declare");
 
+      if (
+        isDeclare &&
+        (this.isContextual("declare") || !this.shouldParseExportDeclaration())
+      ) {
+        throw this.raise(
```
Comment (existentialism) [inline packages/babel-parser/src/plugins/typescript/index.js:2290]: Should we not throw here to make it recoverable?

Comment (nicolo-ribaudo) [reply packages/babel-parser/src/plugins/typescript/index.js:2290]: I'm not sure about how we could recover. What should the AST for `export declare foo` be?

**Review by nicolo-ribaudo — APPROVED** [review]
Approving, pending a reply from @existentialism to https://github.com/babel/babel/pull/12684#discussion_r564031856 (if we can easily recover we should do it).

File: packages/babel-parser/src/plugins/typescript/index.js (hunk 4 above)
Comment (existentialism) [reply packages/babel-parser/src/plugins/typescript/index.js:2290]: Yeah, you're right. Let's stick with throwing!
