### PR TITLE
Fix function name computation for literal values

### LINKED ISSUE #7199: undefined is compiled as function name by using template literal as method name.
## BUG REPORT

As metioned on the title I give an example:

```javascript
var methodName = 'test';
var json = {
  [`${methodName}`]: function (){
    
  }
}
```
is compiled to following code:
```javascript
var methodName = 'test';
var json = _defineProperty({}, '' + methodName, function undefined() {}); // function name is undefined

```

Commonly it's ok, but if I use object deconstruction in method, the compiling result will cause undefined overwriting. For example:

### Current Behavior
```javascript
var methodName = 'test';
var json = {
  [`${methodName}`]: function (){
    let o = {};let {a='2'}=o
    console.log( a )
  }
}
```
is compiled to following code:
```javascript
var methodName = 'test';
var json = _defineProperty({}, '' + methodName, function undefined() {
  var o = {};var _o$a = o.a,
      a = _o$a === undefined ? '2' : _o$a; // undefined in this line is referred to current function

  console.log(a);
});

```

In above code, variable "a" will not be assigned to 2, because _o$a is not equal to "undefined", which is referred to current function; I think following Expected Behavior is proper behavior.

### Expected Behavior
```javascript
var methodName = 'test';
var json = _defineProperty({}, '' + methodName, function () { // no undefined name
  var o = {};var _o$a = o.a,
      a = _o$a === undefined ? '2' : _o$a; 

  console.log(a);
});

```

### Babel Configuration (.babelrc, package.json)
```js
{
  "presets": ["env","react"],
  "plugins": ["syntax-dynamic-import"]
}
```

```js
{
  "name": "dynamic-import",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "webpack",
    "start": "webpack-dev-server --open"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "clean-webpack-plugin": "^0.1.17",
    "html-webpack-plugin": "^2.30.1",
    "webpack": "^3.10.0",
    "webpack-dev-server": "^2.9.7"
  },
  "dependencies": {
    "react": "^16.2.0",
    "react-dom": "^16.2.0"
  }
}

```

### Environment
| software         | version(s)
| ---------------- | -------
| Babel            | see above Babel Configuration part ,
| node             | v8.9.1
| npm              | 5.5.1
| Operating System | macOS Sierra v10.12.6

### PR DESCRIPTION
**Pull request by Axnyff**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #7199 
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  | No 
| Minor: New Feature?      | No
| Tests Added + Pass?      | Yes
| Documentation PR         | 
| Any Dependency Changes?  |
| License                  | MIT

I made a first PR [here](https://github.com/babel/babel/pull/7428) but I realized it broke some existing functionalities and I also discovered some other bugs in the way.
Currently,
``    const x = {
        [null]: function(){},
        [/regex/]: function(){},
        [`test`]: function(){}  
};``  

will all create a function with a name of undefined.

My PR correctly creates for null: _null, /regex/: _regex_ and for simple template literals ( which don't have any expressions).
It will not generate a name for more complicated template literals.

### CODE REVIEW

File: packages/babel-helper-function-name/src/index.js [hunk 1]
```diff
@@ -45,6 +45,18 @@ const visitor = {
   },
 };
 
+function getNameFromLiteralId(id) {
+  if (t.isNullLiteral(id)) {
+    return null;
+  } else if (t.isRegExpLiteral(id)) {
+    return `_${id.pattern}_${id.flags}`;
+  } else if (t.isTemplateLiteral(id) && id.expressions.length === 0) {
```
Comment (loganfsmyth) [inline packages/babel-helper-function-name/src/index.js]: It seems like it would be best to concat the quasis all together for this value.

File: packages/babel-helper-function-name/src/index.js [hunk 2]
```diff
@@ -45,6 +45,18 @@ const visitor = {
...
+    return id.quasis[0].value.raw;
+  } else {
+    return id.value;
```
Comment (loganfsmyth) [inline packages/babel-helper-function-name/src/index.js]: Given the name of this function, I think we should make sure that this is converted to a string before returning it.

File: packages/babel-helper-function-name/src/index.js [hunk 3]
```diff
@@ -45,6 +45,18 @@ const visitor = {
   },
 };
 
+function getNameFromLiteralId(id) {
+  if (t.isNullLiteral(id)) {
+    return null;
```
Comment (loganfsmyth) [inline packages/babel-helper-function-name/src/index.js]: Same here, probably want `"null"`.

File: packages/babel-plugin-transform-function-name/test/fixtures/issues/7199/output.js [hunk 4]
```diff
@@ -2,7 +2,7 @@ const x = {
   [null]: function _null() {},
   [/regex/gi]: function _regex_gi() {},
   [`y`]: function y() {},
-  [`${y}`]: function () {},
+  [`${y}`]: function _() {},
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-function-name/test/fixtures/issues/7199/output.js]: Can you use something like `abc ${y} de` in this test?

File: packages/babel-plugin-transform-function-name/test/fixtures/issues/7199/input.js [hunk 5]
```diff
@@ -0,0 +1,8 @@
+const x = {
+  [null]: function () {},
+  [/regex/gi]: function () {},
+  [`y`]: function () {},
+  [`abc${y}def`]: function () {},
```
Comment (danez) [inline packages/babel-plugin-transform-function-name/test/fixtures/issues/7199/input.js]: This could produce duplicate names if there is another template string with for example `abc${other}def`, but not sure if this is critical or will produce problems.

Comment (nicolo-ribaudo) [reply packages/babel-plugin-transform-function-name/test/fixtures/issues/7199/input.js]: Since you can't reference to those functions using their name anyway (the name is only used for debuging), it shouldn't create problems.

File: packages/babel-helper-function-name/src/index.js [hunk 6]
```diff
@@ -45,6 +45,20 @@ const visitor = {
   },
 };
 
+function getNameFromLiteralId(id) {
+  if (t.isNullLiteral(id)) {
+    return "null";
+  } else if (t.isRegExpLiteral(id)) {
```
Comment (jghinestrosa) [inline packages/babel-helper-function-name/src/index.js]: Since you are using the `return` statement, the `else if` statement becomes unnecessary. You could use `if` instead.

Comment (Axnyff) [reply packages/babel-helper-function-name/src/index.js]: That's true, i'll update

**Comment by Axnyff** [comment]
Awesome, thanks everybody for your help!
