### PR TITLE
Handle cases when `??` and `?.` is in binding initializers

### LINKED ISSUE #11166: Deep optional chaining breaks in function argument destructuring
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**

Optional chaining breaks when destructuring deep chains inside the function arguments, due to incorrect hoisting of temporary variables.

[REPL](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=FAMwrgdgxgLglgewgAgBYFMA2mEAoDewyyAhgDRHIBGyAvKQPwB0VzUFAvgJTKHEBO6GGH4oADAG5gHYMAzY8-UgC5eHAAXcpQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env%2Cenv&prettier=true&targets=Node-13&version=7.8.4&externalPlugins=)

**Input Code**

```js
function hello({
  a,
  b = a?.b?.c,
}) {
  return 0;
}
```

**Output Code**
```js
"use strict";

function hello({
  a,
  b = a === null || a === void 0 ? void 0 : (_a$b = a.b) === null || _a$b === void 0 ? void 0 : _a$b.c
}) {
  var _a$b;

  return 0;
}
```

**Expected behavior/code**

The code should assign a value to `b`, and not fail with `_a$b is not defined`.

**Babel Configuration**

```js
// .babelrc
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": { "node": "current" }
      }
    ]
  ]
}

```

**Environment**

- Babel version(s): 7.8.4
- Node/npm version: 13.8.0/6.13.7

**Possible Solution**

Either move the hoisted variable to the module scope, or use a temporary variable for the argument and perform the destructuring inside the function body.

### LINKED ISSUE #12026: Invalid output resulting in ReferenceErrors with plugin-proposal-optional-chaining
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

When a nested optional chaining expression is found inside a parameter position (a parameter default value, or default value inside an object or array destructuring), a `var` declaration is added to the function body. That variable declaration is not in effect when evaluating parameter default values and causes a `ReferenceError` in strict mode when the function is called.

- [REPL](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=OQVwzgpgBGAuBOBLAxrYAoZB7AdnKWARgFZQC8UA3gL6a74BmWW5UAFAA4CG8XAtqyLEAdB3hYOARgD8o8RwBMASnIA-KuihRseLABsIwvVgDmnHvyXpaTLGyVA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2%2Cenv&prettier=false&targets=&version=7.11.5&externalPlugins=)

To repro, you can use the Babel CLI to compile the code below and run it with Node: `babel test.js | node`. Error output:

```
const foo = (param = (_obj$prop = obj.prop1) === null || _obj$prop === void 0 ? void 0 : _obj$prop.prop2) => {
                                ^

ReferenceError: _obj$prop is not defined
    at foo ([stdin]:5:33)
    at [stdin]:11:1
    at Script.runInThisContext (vm.js:132:18)
    at Object.runInThisContext (vm.js:315:38)
    at Object.<anonymous> ([stdin]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1256:30)
    at evalScript (internal/process/execution.js:98:25)
    at internal/main/eval_stdin.js:29:5
    at Socket.<anonymous> (internal/process/execution.js:211:5)
    at Socket.emit (events.js:326:22)
```

**Input Code**

```js
'use strict'
const obj = {}
const foo = (param = obj.prop1?.prop2) => {
  console.log(param)
}
foo()
```

**Output Code**

```js
'use strict';

const obj = {};

const foo = (param = (_obj$prop = obj.prop1) === null || _obj$prop === void 0 ? void 0 : _obj$prop.prop2) => {
  var _obj$prop;

  console.log(param);
};

foo();
```

**Expected behavior**
Should not throw a `ReferenceError`, should log `undefined` to the console.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

See REPL link above, or just add the `plugin-proposal-optional-chaining` (doesn't matter whether loose or not, happens in both modes)
```js
{
  "plugings": [
    "@babel/plugin-proposal-optional-chaining"
  ]
}
```

**Environment**
- Babel version(s): 7.11.5
- Node/npm version: v14.7.0
- OS: macOS
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: CLI for repro

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #11166, fixes #12026, closes #11533 
| Patch: Bug Fix?          | Yes
| Tests Added + Pass?      | Yes
| License                  | MIT

This PR is inspired from #11533 but tries to solve it without interface changes to `scope#maybeGenerateMemoized`. It also addressed https://github.com/babel/babel/pull/11533#discussion_r463183638.

Todo:
- [x] Add tests for loose mode

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/12032"></a>

### CODE REVIEW

File: packages/babel-helper-member-expression-to-functions/src/index.js [hunk 1]
```diff
@@ -362,6 +372,16 @@ const handle = {
 
     // MEMBER?.(ARGS) -> _optionalCall(MEMBER, ARGS)
     if (parentPath.isOptionalCallExpression({ callee: node })) {
+      // Replace `function (a, x = a.b.#c?.()) {}` to `function (a, x = (() => a.b.#c?.())() ){}`
+      // so the temporary variable can be injected in correct scope
+      // This can be further optimized to avoid unecessary IIFE
+      if (scope.path.isPattern()) {
```
Comment (kaicataldo) [inline packages/babel-helper-member-expression-to-functions/src/index.js:378]: Is it worth extracting this into a reusable function since it's the same, for maintenance purposes?

Comment (JLHwung) [reply packages/babel-helper-member-expression-to-functions/src/index.js:378]: I slightly prefer to leave it as-is: Because the same code snippet is used in only two places in this file.

File: packages/babel-helper-member-expression-to-functions/src/index.js [hunk 2]
```diff
@@ -118,6 +118,17 @@ const handle = {
         return true;
       });
 
+      // Replace `function (a, x = a.b?.#c) {}` to `function (a, x = (() => a.b?.#c)() ){}`
+      // so the temporary variable can be injected in correct scope
+      // This can be further optimized to avoid unecessary IIFE
+      if (scope.path.isPattern()) {
```
Comment (jridgewell) [inline packages/babel-helper-member-expression-to-functions/src/index.js:124]: Does this only apply in parameters? I'm not sure when a scope'a path would be the pattern.

File: packages/babel-plugin-proposal-optional-chaining/src/index.js [hunk 3]
```diff
@@ -22,6 +22,30 @@ export default declare((api, options) => {
...
+    while (
+      optionalPath.isOptionalMemberExpression() ||
+      optionalPath.isOptionalCallExpression()
+    ) {
+      const { node } = optionalPath;
+      const childPath = skipTransparentExprWrappers(
+        optionalPath.get("object") ?? optionalPath.get("callee"),
+      );
+      if (node.optional) {
+        return !scope.isStatic(childPath.node);
```
Comment (jridgewell) [inline packages/babel-plugin-proposal-optional-chaining/src/index.js:42]: I think we should only be returning if it's non-static. If it is static, we should continue the loop. Eg, `foo?.bar?.baz().qux` needs it.

**Review by jridgewell — CHANGES_REQUESTED** [review]

File: packages/babel-helper-member-expression-to-functions/src/index.js (hunk 2 above)
Comment (JLHwung) [reply packages/babel-helper-member-expression-to-functions/src/index.js:124]: > Does this only apply in parameters?

Yes, if a Pattern is a `sopce.path`, its parent must be a `Function`: https://github.com/babel/babel/blob/3628c528676a91cd95bb00d56f799be53185e316/packages/babel-types/src/validators/isScope.js#L22

because a `Pattern` is not Scopeable.

However when reviewing what is authored by past me in #10912, I do realize that current `isScope` definition does not cover pattern in catch clause:

```js
try { } catch ({ e = foo?.bar }) {}
```

I will fix that in a separate PR.

File: packages/babel-plugin-proposal-optional-chaining/src/index.js (hunk 3 above)
Comment (JLHwung) [reply packages/babel-plugin-proposal-optional-chaining/src/index.js:43]: Good question. I have added `foo?.bar?.baz().qux` as an example. I overlooked the fact that `NodePath#get` always returns non-nullish.

If `childPath.node` is static, it must be `this`, `super` or `identifier` and we could stop here since `optionalPath.isOptionalChain()` will be no longer `true` in the next loop. The idea here is to find the last chain before `?` an optional chain. So in your example `childPath.node` will be `foo?.bar` for `foo?.bar?.baz().qux`. `foo?.bar` is non-static so the whole chain will then be wrapped in IIFE.

We could further optimize and allow `SimpleMemberExpression` for loose mode.

**Review by nicolo-ribaudo — APPROVED** [review]

**Review by jridgewell — APPROVED** [review]
