### PR TITLE
Define default value for vars shadowing params

### LINKED ISSUE #11256: `Cannot read property 'type' of null` again
## Bug Report

- [x] I would like to work on a fix!

**Current Behavior**
This is a follow up to #11210 . When the assignment expression is wrapped in a block scope that is compiled to IIFE, the error occurs again.

```
TypeError: unknown: Cannot read property 'type' of null
    at convertFunctionParams (/path/to/node_modules/@babel/plugin-transform-parameters/lib/params.js:88:24)
    ...
```

**Input Code**
- REPL or Repo link if applicable:

```js
class A {
  a = b => {
    {
      ({ b } = {});
    }
  };
}
```

```json
// options.json
{
  "plugins": [
    "proposal-class-properties",
    "transform-parameters",
    "transform-destructuring"
  ]
}
```

**Expected behavior/code**
Should not throw error.

**Environment**

```
  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 13.10.1 - /path/to/node_modules/.bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.7 - /path/to/node_modules/.bin/npm
  npmPackages:
    @babel/runtime: ^7.1.5 => 7.8.4
    babel-plugin-macros: ^2.8.0 => 2.8.0
    eslint: ^6.8.0 => 6.8.0
```
- Babel version(s): all latest, @babel/core@7.8.8
- Node/npm version: Node 13/npm 6
- Monorepo: no
- How you are using Babel: cli

**Possible Solution**

Possible cause: In `replaceWithMultiple` the original node is removed, but its bindings are not removed as expected, leaving a node with `removed: true, node: null` in the `constantViolations` and breaks `plugins-transform-parameters`.

The bindings are found from `path.node`:

https://github.com/babel/babel/blob/420f2ee69aad0316c6f49e9dfdc6a02c8f9d4fc8/packages/babel-traverse/src/path/removal.js#L24-L27

But `path.node` is always `null` when it is being removed:

https://github.com/babel/babel/blob/420f2ee69aad0316c6f49e9dfdc6a02c8f9d4fc8/packages/babel-traverse/src/path/replacement.js#L55-L59

I found a tricky way to solve this:
- save the node to be removed before it is set to `null`
- pass it to `remove`
- search bindings: first `this.node = node`, then search, finally `this.node = null`

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes https://github.com/babel/babel/issues/11303, fixes #11256
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

The best way to handle params's horrible shadowing behavior is by... relying on it :grin:

### CODE REVIEW

File: packages/babel-plugin-transform-parameters/src/params.js [hunk 1]
```diff
@@ -1,4 +1,3 @@
-import callDelegate from "@babel/helper-call-delegate";
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-parameters/src/params.js]: This is now unused and can be removed from the repo.

**Comment by nicolo-ribaudo** [comment]
I ended up also pushing a workaround for https://github.com/babel/babel/issues/11256 (a fix would require major changes to how we handle the scope)

File: packages/babel-plugin-transform-parameters/test/fixtures/parameters/var-no-init-for-init-same-as-param/exec.js [hunk 2]
```diff
@@ -1,5 +1,5 @@
 function foo(a = 2) {
   for (var a, i = 0; i < 1; i++);
-  expect(a).toBe(undefined);
+  expect(a).toBe(2);
```
Comment (JLHwung) [inline packages/babel-plugin-transform-parameters/test/fixtures/parameters/var-no-init-for-init-same-as-param/exec.js]: Good catch!

File: packages/babel-plugin-transform-parameters/src/params.js [hunk 3]
```diff
@@ -52,18 +51,22 @@ export default function convertFunctionParams(path, loose) {
...
   };
 
   const body = [];
   const params = path.get("params");
 
-  let firstOptionalIndex = null;
-
-  for (let i = 0; i < params.length; i++) {
-    const param = params[i];
+  let isSimpleParameterList = true;
```
Comment (JLHwung) [inline packages/babel-plugin-transform-parameters/src/params.js]: What about
```js
const isSimpleParameterList = params.every(param => param.isIdentifier());
```
It will return `true` when `params` is empty.

File: packages/babel-plugin-transform-parameters/src/params.js [hunk 4]
```diff
@@ -52,18 +51,22 @@ export default function convertFunctionParams(path, loose) {
   const { node, scope } = path;
 
   const state = {
-    iife: false,
-    scope: scope,
+    stop: false,
+    needsOuterBinding: false,
+    shadowedParams: new Set(),
```
Comment (JLHwung) [inline packages/babel-plugin-transform-parameters/src/params.js]: We can move `shadowedParams` out of `state` if we don't intend it accessed by `visitIdentifier`.

File: packages/babel-plugin-transform-parameters/test/fixtures/regression/11303/exec.js [hunk 5]
```diff
@@ -0,0 +1,6 @@
+function test(date, defValue = 1) {
```
Comment (JLHwung) [inline packages/babel-plugin-transform-parameters/test/fixtures/regression/11303/exec.js]: nit: lol they don't have to be `date` and `defValue`.

File: packages/babel-plugin-transform-parameters/src/params.js [hunk 6]
```diff
@@ -23,27 +22,27 @@ const buildSafeArgumentsAccess = template(`
...
+    (scope.getBinding(name) === state.scope.parent.getBinding(name) &&
+      state.scope.hasOwnBinding(name))
+  ) {
+    state.needsOuterBinding = true;
+    path.stop();
+  }
+};
 
 const iifeVisitor = {
-  ReferencedIdentifier(path, state) {
```
Comment (JLHwung) [inline packages/babel-plugin-transform-parameters/src/params.js]: I guess we can simplify to
```js
const iifeVisitor = {
  "ReferencedIdentifier|BindingIdentifier": visitIdentifier,
}
```
If there is a BindingIdentifier in the function scope, it should not satisfy `scope.getBinding(name) === state.scope.parent.getBinding(name)` so essentially it will be noop.

File: packages/babel-plugin-transform-parameters/src/params.js [hunk 7]
```diff
@@ -178,13 +171,34 @@ export default function convertFunctionParams(path, loose) {
...
 
   return true;
 }
+
+function buildScopeIIFE(shadowedParams, body) {
+  const args = [];
+  const params = [];
+
+  for (const name of shadowedParams) {
+    // We create then twice; the other option is to use t.cloneNode
```
Comment (existentialism) [inline packages/babel-plugin-transform-parameters/src/params.js]:
```suggestion
    // We create them twice; the other option is to use t.cloneNode
```

File: packages/babel-plugin-transform-parameters/src/params.js [hunk 8]
```diff
@@ -23,47 +22,40 @@ const buildSafeArgumentsAccess = template(`
...
+  "ReferencedIdentifier|BindingIdentifier"(path, state) {
     const { scope, node } = path;
+    const { name } = node;
+
     if (
-      node.name === "eval" ||
-      !isSafeBinding(scope, node) ||
-      !isSafeBinding(state.scope, node)
+      name === "eval" ||
+      (scope.getBinding(name) === state.scope.parent.getBinding(name) &&
```
Comment (jridgewell) [inline packages/babel-plugin-transform-parameters/src/params.js]: Isn't this just a `!scope.hasOwnBinding` check?

Comment (JLHwung) [reply packages/babel-plugin-transform-parameters/src/params.js]: Nope, `state.scope` does not equal to `scope`.
