### PR TITLE
fix: "Map maximum size exceeded" in deepClone

### LINKED ISSUE #16967: [Bug]: "Map maximum size exceeded" in deepClone
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

babel.transformFromAstAsync(...) // Called from Angular compiler

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

Current behavior: the deepClone (transformation\util\clone-deep.js) method throws error "Map maximum size exceeded" for very big ASTs, because the standard JS Map can only hold somewhat more than 16.000.000 keys, our AST has more objects than that.

Expected behavior: handling big ASTs without errors.

### Environment

Babel: 7.24.7
Node: v18.20.4
NPM: 10.7.0
Windows 11

### Possible solution

As a quick fix, I implemented a MultiMap class and replaced the standard Map with it in the deepClone implementation, it solved the problem:

```js
class MultiMap {
    #maps = [new Map()];

    has(key) {
        return this.#maps.some(map => map.has(key));
    }

    get(key) {
        for(let map of this.#maps){
            let value = map.get(key);
            if (value)
                return value;
        }
        return undefined;
    }

    set(key, value) {
        if (this.#maps[this.#maps.length-1].size >= 16000000) {
            this.#maps.push(new Map());
        }
        this.#maps[this.#maps.length-1].set(key,value);
    }
}
```

And I replaced "new Map()" in the _default function with "new MultiMap()". After that the deepClone call threw no errors.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #16967 
| Patch: Bug Fix?          | √
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

In Babel 7, only a workaround was applied, and in Babel 8, a complete fix was made.

### CODE REVIEW

File: packages/babel-core/src/transformation/util/clone-deep.ts [hunk 1]
```diff
@@ -29,5 +43,14 @@ function deepClone(value: any, cache: Map<any, any>): any {
...
   if (typeof value !== "object") return value;
-  return deepClone(value, new Map());
+
+  if (process.env.BABEL_8_BREAKING) {
+    return deepClone(value, new Map(), false);
+  } else {
+    try {
+      return deepClone(value, new Map(), true);
+    } catch (_) {
+      return structuredClone(value);
```
Comment (liuxingbaoyu) [inline packages/babel-core/src/transformation/util/clone-deep.ts:53]: This only works in node 17+, but `v8.serialize` doesn't work in browsers and other runtimes.

**Review by JLHwung — APPROVED** [review]

File: packages/babel-core/src/transformation/util/clone-deep.ts [hunk 2]
```diff
@@ -1,25 +1,39 @@
-//https://github.com/babel/babel/pull/14583#discussion_r882828856
-function deepClone(value: any, cache: Map<any, any>): any {
+// https://github.com/babel/babel/pull/14583#discussion_r882828856
+function deepClone(
+  value: any,
+  cache: Map<any, any>,
+  allowCircle: boolean,
```
Comment (nicolo-ribaudo) [inline packages/babel-core/src/transformation/util/clone-deep.ts:5]: The allowCircle is false but the object actually contains a cycle, this function is now going to cause an infinite loop, right? Can we throw in that case instead? We'd only need to keep track of the current "stack", rather than of all nodes in the map.

File: packages/babel-core/src/transformation/util/clone-deep.ts (hunk 1 above)
Comment (nicolo-ribaudo) [reply packages/babel-core/src/transformation/util/clone-deep.ts:53]: Can we use `structuredClone` in Babel 8?

Comment (liuxingbaoyu) [reply packages/babel-core/src/transformation/util/clone-deep.ts:53]: https://github.com/babel/babel/issues/16967#issuecomment-2486557607
Unfortunately it is slow, less than half the performance of current implementations.🤦‍♂️

File: packages/babel-core/src/transformation/util/clone-deep.ts [hunk 3]
```diff
@@ -1,33 +1,66 @@
...
   if (value !== null) {
-    if (cache.has(value)) return cache.get(value);
+    if (allowCircle) {
+      if (cache.has(value)) return cache.get(value);
+    } else {
+      if (circleSet.has(value)) {
+        circleSet.clear();
+        throw new Error("Babel-deepClone: Cycles are not allowed in AST");
+      }
+      circleSet.add(value);
```
Comment (nicolo-ribaudo) [inline packages/babel-core/src/transformation/util/clone-deep.ts:16]: How big is the performance impact of using this set compared to:
- the old behavior with the map
- the behavior with no protection against infinite loops

If it's significantly expensive, we could keep track of the depth we are at in the cloning and only start using the cycle detection logic if it's, for example, >100. It means that we'll be slower in error cases, but faster in the (common) successful case.

Comment (liuxingbaoyu) [reply packages/babel-core/src/transformation/util/clone-deep.ts:16]: current: 263 ops/sec ±1.13% (3.809ms)
circle-check: 255 ops/sec ±0.9% (3.924ms)
no-circle-check: 357 ops/sec ±1.55% (2.799ms)
circle-check-100-depth: 355 ops/sec ±0.7% (2.814ms)

I'll add depth detection. :)

File: packages/babel-core/src/transformation/util/clone-deep.ts [hunk 4]
```diff
@@ -1,33 +1,73 @@
...
+function deepClone(
+  value: any,
+  cache: Map<any, any>,
+  allowCircle: boolean,
+): any {
   if (value !== null) {
-    if (cache.has(value)) return cache.get(value);
+    if (allowCircle) {
+      if (cache.has(value)) return cache.get(value);
+    } else if (++depth > 100) {
```
Comment (nicolo-ribaudo) [inline packages/babel-core/src/transformation/util/clone-deep.ts:12]: I was trying to see what are reasonable depth values: both `@babel/standalone/babel.js` and `@babel/standalone/babel.min.js` are around 200.

Let's increase this to 200 at least, maybe 250 to be safe? It's unlikely that there are files deeper than that.

(Or maybe we could also just completely remove the cycle-detection logic and just throw an error if `depth > 1000` 😬)

Comment (liuxingbaoyu) [reply packages/babel-core/src/transformation/util/clone-deep.ts:12]: Thanks for your investigation!
I'd be inclined to set it to 250, since there are probably a few hundred variables being concatenated(auto-generated code)  :)

**Review by nicolo-ribaudo — APPROVED** [review]
