### PR TITLE
fix(parser): properly handle optional markers in generator class methods

### LINKED ISSUE #17310: Inconsistent behavior when parsing class optional methods (TS)
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```ts
class A {
  * [a?.b]?() {};
}
```

I don't know what this code mean... but ts can parse it without error.

And as I tested Babel can also parse 

```
class A {
  [a?.b]?() {};
}

class A {
  async [a?.b]?() {};
}

class A {
  * [a?.b]?() {};  // <- Not this one.
}

class A {
  async * [a?.b]?() {};
}
```

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

Should all able to parse, I guess.

### Environment

  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 22.14.0 - ~\AppData\Local\fnm_multishells\16504_1747115604064\node.EXE
    Yarn: 4.9.1 - D:\npm\yarn.CMD
    npm: 9.1.2 - ~\AppData\Local\fnm_multishells\16504_1747115604064\npm.CMD
    bun: 1.2.2 - ~\.bun\bin\bun.EXE
  npmPackages:
    @babel/code-frame: 7.27.1 => 7.27.1
    @babel/generator: 7.27.1 => 7.27.1
    @babel/parser: 7.27.2 => 7.27.2
    @babel/types: 7.27.1 => 7.27.1
    eslint: 9.26.0 => 9.26.0
    jest: 30.0.0-alpha.7 => 30.0.0-alpha.7

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by magic-akari**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #17310
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

File: packages/babel-parser/test/fixtures/typescript/class/optional-generator/input.ts [hunk 1]
```diff
@@ -0,0 +1,9 @@
+class A {
+  *[a?.b]?() { };
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/test/fixtures/typescript/class/optional-generator/input.ts:2]: Should we report a recoverable error in cases like this, similarly to how report it for `readonly` and `declare`?

**Review by JLHwung — APPROVED** [review]

File: packages/babel-parser/test/fixtures/typescript/class/optional-generator/input.ts (hunk 1 above)
Comment (magic-akari) [reply packages/babel-parser/test/fixtures/typescript/class/optional-generator/input.ts:2]: Actually, this is valid TypeScript syntax!.

Do you mean `readonly *[a?.b]?() { };` ?

File: packages/babel-parser/test/fixtures/typescript/class/optional-generator-method-with-modifiers/input.ts [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+
+class A {
+  private *[a?.a]?() { }
+  public *[b?.b]?() { }
+  static *[c?.c]?() { }
+  abstract *[d?.d]?() { }
+  readonly *[e?.e]?() { }
+  declare *[f?.f]?() { }
+  protected *[g?.g]?() { }
+}
```
Comment (JLHwung) [inline packages/babel-parser/test/fixtures/typescript/class/optional-generator-method-with-modifiers/input.ts:19]: Thank you. Can you split this test into two? one for the valid cases and the other for invalid ones.

Comment (magic-akari) [reply packages/babel-parser/test/fixtures/typescript/class/optional-generator-method-with-modifiers/input.ts:13]: Done

File: packages/babel-parser/test/fixtures/typescript/class/optional-generator/input.ts (hunk 1 above)
Comment (nicolo-ribaudo) [reply packages/babel-parser/test/fixtures/typescript/class/optional-generator/input.ts:2]: Oh I meant with just `?`, I didn't realize it's actually valid syntax.

**Review by nicolo-ribaudo — APPROVED** [review]
