### PR TITLE
fix: mark `var` declarations in loops as not constant

### LINKED ISSUE #13760: [Bug]: @babel/plugin-transform-react-constant-elements transforms non constant element in for loop
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

```jsx
function Example(){
  const nodes = []
  
  for (let i = 0; i < 10; i++) {
    const n = i
    nodes.push(<div children={n}></div>)
  }
  
  return nodes;
}
```
### Configuration file name

babel.config.js

### Configuration
```js
module.exports = {
  env: {
    production: {
      plugins: [
        '@babel/plugin-transform-react-inline-elements',
        '@babel/plugin-transform-react-constant-elements',
        ['transform-react-remove-prop-types', { removeImport: true }],
      ],
    },
    test: {
      plugins: [['babel-plugin-webpack-alias', { config: './webpack/path-aliases.config.js' }]],
    },
  },
  plugins: [
    [
      '@babel/plugin-transform-typescript',
      {
        allowDeclareFields: true,
        isTSX: true,
      },
    ],
    ['@babel/plugin-proposal-class-properties', { loose: true }],
    '@babel/plugin-proposal-export-default-from',
    '@babel/plugin-proposal-export-namespace-from',
    '@babel/plugin-proposal-nullish-coalescing-operator',
    '@babel/plugin-proposal-object-rest-spread',
    '@babel/plugin-proposal-optional-chaining',
    ['@babel/plugin-proposal-private-methods', { loose: true }],
    ['@babel/plugin-proposal-private-property-in-object', { loose: true }],
    '@babel/plugin-transform-runtime',
    'babel-plugin-generate-i18n-id',
    'react-hot-loader/babel',
  ],
  presets: [['@babel/preset-env', { loose: true }], '@babel/preset-react'],
};
```

### Current and expected behavior

When the code is transformed the element is treated as constant when both `transform-block-scoping` and `transform-react-constant-elements` are used. [incorrect](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAUQB4EMC2AHANgUwAoBKAbwChFEIEBnKRMOAE31sQF5EBtAXUsQDgcAE6JCBBjE6IADAG5E0gDyIAjAqUBqLcUQUqVGmHqMZMAVSataAOmwhaAC0LLmMAG7UnMXMxH4YBykYAC-AHzKAPTuHuHEAqECAgFQICJI1mzy5KFAA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react&prettier=false&targets=&version=7.13.12&externalPlugins=%40babel%2Fplugin-transform-block-scoping%407.15.3%2C%40babel%2Fplugin-transform-react-constant-elements%407.14.5&assumptions=%7B%7D) vs [correct](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAUQB4EMC2AHANgUwAoBKAbwChFEIEBnKRMOAE31sQF5EBtAXUsQDgcAE6JCBBjE6IADAG5E0gDyIAjAqUBqLcUQUqVGmHqMZMAVSataAOmwhaAC0LLmMAG7UnMXMxH4YBykYAC-AHzKAPTuHuHEAqECAgFQICJI1mzy5KFAA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react&prettier=false&targets=&version=7.13.12&externalPlugins=%40babel%2Fplugin-transform-react-constant-elements%407.14.5&assumptions=%7B%7D)

### Environment

```
System:
    OS: macOS 11.4
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
  npmPackages:
    @babel/core: 7.15.0 => 7.15.0
    @babel/plugin-proposal-class-properties: 7.14.5 => 7.14.5
    @babel/plugin-proposal-export-default-from: 7.14.5 => 7.14.5
    @babel/plugin-proposal-export-namespace-from: 7.14.5 => 7.14.5
    @babel/plugin-proposal-nullish-coalescing-operator: 7.14.5 => 7.14.5
    @babel/plugin-proposal-object-rest-spread: 7.14.7 => 7.14.7
    @babel/plugin-proposal-optional-chaining: 7.14.5 => 7.14.5
    @babel/plugin-transform-react-constant-elements: 7.14.5 => 7.14.5
    @babel/plugin-transform-react-inline-elements: 7.14.5 => 7.14.5
    @babel/plugin-transform-runtime: 7.15.0 => 7.15.0
    @babel/preset-env: 7.15.0 => 7.15.0
    @babel/preset-react: 7.14.5 => 7.14.5
    @babel/preset-typescript: 7.15.0 => 7.15.0
    @babel/register: 7.15.3 => 7.15.3
    @babel/runtime: 7.15.4 => 7.15.4
    babel-eslint: 10.1.0 => 10.1.0
    babel-jest: 27.0.6 => 27.0.6
    babel-loader: 8.2.2 => 8.2.2
    babel-plugin-generate-i18n-id: 1.4.12 => 1.4.12
    babel-plugin-istanbul: 6.0.0 => 6.0.0
    babel-plugin-transform-react-remove-prop-types: 0.4.24 => 0.4.24
    babel-plugin-webpack-alias: 2.1.2 => 2.1.2
    eslint: 7.32.0 => 7.32.0
    eslint-plugin-babel: 5.3.1 => 5.3.1
    jest: 27.0.6 => 27.0.6
    webpack: 4.44.2 => 4.44.2
```

### Possible solution

Add an exception for this case here: https://github.com/babel/babel/blob/main/packages/babel-plugin-transform-react-constant-elements/src/index.js#L75

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #13760, closes #13777
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

This is #13777, rebased and fixed. I couldn't push to that PR because it was opened from @stephane-arista's `main` branch.

The first commit is the original one, the second applies the changes suggested in review.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/15027"></a>

### CODE REVIEW

File: packages/babel-plugin-transform-destructuring/test/fixtures/assumption-iterableIsArray/for-in/output.js [hunk 1]
```diff
@@ -5,7 +5,8 @@ for (var _ref in obj) {
 }
 
 for (var _ref2 in obj) {
-  name = _ref2[0];
-  value = _ref2[1];
+  var _ref3 = _ref2;
+  name = _ref3[0];
+  value = _ref3[1];
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-destructuring/test/fixtures/assumption-iterableIsArray/for-in/output.js:10]: Input: 
```js
for ([name, value] in obj) {
```

This output changes because the destructuring transform first transforms it to
```js
for (var _ref2 in obj) {
  [name, value] = _ref2;
```
and then `_ref2` isn't considered constant anymore.

We can avoid this in Babel 8, by injecting `let` instead of `var`.

**Review by liuxingbaoyu — APPROVED** [review]
I like this.
