### PR TITLE
fix: accept duplicated import/variable in different module

### LINKED ISSUE #13510: [Bug]: babel fails on flow definition file, if modules in it have imports with the same name
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
//@flow

declare module 'test' {
  import type { JSONSchema7 } from 'json-schema';
}

declare module 'test/submodule' {
  import type { JSONSchema7 } from 'json-schema';
}
```

[REPL](https://babeljs.io/repl#?browsers=defaults%2C%20ie%2011%2C%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=PTACDMBsHsHcCh4BMCmBjSBDATigBALbRICuk-A5AC4oDOVFeA3vHngJYEAO02VeVAJ5d8TPACkAygHkAcpLQALFAUwB2PAF884bNAJ4KAK1rQAdgFpaSlZgoBueJsSoMOfEVLlDNesFokAEaeZCiMLGycPHwCwqISMvI2qhrauvqGJuZWyXaOzvBAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cflow&prettier=false&targets=&version=7.14.7&externalPlugins=)

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

 There is an error about duplicate declaration:
 
```js
Duplicate declaration "JSONSchema7"
   6 |
   7 | declare module 'test/submodule' {
>  8 |   import type { JSONSchema7 } from 'json-schema';
     |                 ^^^^^^^^^^^
   9 | }
  10 |
  11 |
 ```
 
But, it should be allowed to have same imports in different modules

### Environment

not specific to the environment

### Possible solution

_No response_

### Additional context

Found this when trying traverse an ATS from parsing flow definitions file ([code where it happens](https://github.com/zxbodya/flowts/blob/master/packages/cli/src/detectOptions.ts)).

### PR DESCRIPTION
**Pull request by colinaaa**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #13510 
| Patch: Bug Fix?          | 👍
| Major: Breaking Change?  | Not sure
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

https://github.com/babel/babel/blob/fce35af69101c6b316557e28abf60bdbf77d6a36/packages/babel-traverse/src/scope/index.ts#L201-L212

I make all `ImportDeclaration` `isBlockScoped`, so that it will `getBlockParent` instead of `getProgramParent` (which leads to conflicts).

I'm not sure this is the best way to do so, but since `Declaration` and `BlockScoped` visitor of `collectorVisitor` are doing similar things, it sounds like pretty good to me.

According to the test, this change did not bring any breaking change. However, I not so familiar with babel codebase. So there are possibilities that this PR is breaking something.

Let me know if this approach is not correct / breaking, I will try to find another way out.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/13527"></a>

### CODE REVIEW

File: packages/babel-types/src/validators/isBlockScoped.ts [hunk 1]
```diff
@@ -1,10 +1,20 @@
...
  * Check if the input `node` is block scoped.
  */
 export default function isBlockScoped(node: t.Node): boolean {
-  return isFunctionDeclaration(node) || isClassDeclaration(node) || isLet(node);
+  return (
+    isFunctionDeclaration(node) ||
+    isClassDeclaration(node) ||
+    isLet(node) ||
+    // import declaration can be block scoped when it's in TS/flow module declaration
+    isImportDeclaration(node)
```
Comment (fedeci) [inline packages/babel-types/src/validators/isBlockScoped.ts:18]: Actually it is not block scoped as `ImportDeclaration`s may only appear in the top level or inside a module/namespace (for TS). Adding it here may be a breaking change for someone using the validator.
Furthermore excluding `ImportDeclaration`s from https://github.com/babel/babel/blob/fce35af69101c6b316557e28abf60bdbf77d6a36/packages/babel-traverse/src/scope/index.ts#L201-L212
results in excluding those nodes from the traversal and not running `registerDeclaration` on them.

Comment (colinaaa) [reply packages/babel-types/src/validators/isBlockScoped.ts:18]: I don't think excluding `ImportDeclarations` is well enough, since it will also cause breaking changes.

The main problem here is that **the scope of declared module should be isolated with other modules' scopes and the program's scope**. But unfortunately it's not now.

So maybe we could change the implementation of `getProgramParent` to make it returns not only on `Program`, but also `ModuleDeclaration`. This will make scopes of modules isolated with each other  and the program.

Comment (fedeci) [reply packages/babel-types/src/validators/isBlockScoped.ts:18]: Yep, excluding `ImportDeclaration` is definitely not the right way here.
You will be happy to know that there is already a method called `getBlockParent` that gets the upper block. However I would suggest you to give a look at how the `BlockScoped` visitor is handling block scoped declarations, because we may have to replicate a similar behavior for `ImportDeclaration`.

Comment (JLHwung) [reply packages/babel-types/src/validators/isBlockScoped.ts:18]: > make it returns not only on Program, but also ModuleDeclaration.

I don't think we can mark ModuleDeclaration as program because variables within module declaration can reference bindings defined in program:

```js
type T = number;
declare module 'test' {
  declare var a: T;
}
```

Since ambient declarations are always top level. We can check if `node.parent` is `ModuleDeclaration` and then register declarations there, otherwise we fallback to 

https://github.com/babel/babel/blob/fce35af69101c6b316557e28abf60bdbf77d6a36/packages/babel-traverse/src/scope/index.ts#L209-L210

Comment (colinaaa) [reply packages/babel-types/src/validators/isBlockScoped.ts]: I took a different approach.

Take all `ImportDeclaration` into a separated visitor, and use `getBlockParent` to find parent scope.

I think it is more conducive to maintenance。

**Review by fedeci — APPROVED** [review]

File: packages/babel-traverse/src/scope/index.ts [hunk 2]
```diff
@@ -202,6 +202,9 @@ const collectorVisitor: Visitor<CollectVisitorState> = {
     // delegate block scope handling to the `BlockScoped` method
     if (path.isBlockScoped()) return;
 
+    // import handing to the `ImportDeclaration` method
```
Comment (JLHwung) [inline packages/babel-traverse/src/scope/index.ts:205]:
```suggestion
    // delegate import handing to the `ImportDeclaration` method
```

**Review by JLHwung — APPROVED** [review]

**Review by nicolo-ribaudo — APPROVED** [review]
Thanks!
