### PR TITLE
Fix: Only create `@babel/node` IPC channel when needed

### LINKED ISSUE #13259: [Bug]: babel-node IPC channel causes process to hang when message listener is added
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

@babel/register or @babel/node

### Input code

```js
process.on('message', () => {});
```

... or run the widely-used `exit-hook` library:
```js
const exitHook = require('exit-hook'); // version >= 2.0.0 with PM2 shutdown message hook
exitHook(() => {
  console.log('exit');
});
```

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

The script is expected to exit but hangs instead. When running the same script with `node` instead of `babel-node`, it exits.

### Environment

- Babel version: 7.13.16, (`@babel/node` at 7.13.13)
- Node: 12

### Possible solution

The issue seems to be that when running `babel-node`, an IPC channel is _always_ set up [on this line in `babel-node.js`](https://github.com/babel/babel/blob/main/packages/babel-node/src/babel-node.js#L88).

Node docs state the following regarding the IPC channel:
> It is worth noting that when an IPC channel is established between the parent and child processes, and the child is a Node.js process, the child is launched with the IPC channel unreferenced (using unref()) until the child registers an event handler for the 'disconnect' event or the 'message' event. This allows the child to exit normally without the process being held open by the open IPC channel.

Conversely, if an even handler _is_ added, then the child refuses to exit until disconnected. This causes behavior of the same script to differ when run in `babel-node` compared to regular `node`.

Ideally, the IPC channel would only be set up when needed, which is when the `babel-node` process itself has an IPC channel. Thus, only adding the `"ipc"` argument when `process.send != null` in the current process is true should do the trick.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by quickgiant**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #13259 
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

Fixes an issue where `babel-node` always created an IPC channel for its spawned child, regardless of whether the outer `babel-node` process had an IPC channel itself. This caused compatibility issues with scripts expecting to run without IPC, or expecting to only run with IPC in certain scenarios, for example the `exit-hook` library that [assumes an IPC channel will only be present when running inside PM2](https://github.com/sindresorhus/exit-hook/blob/main/index.js#L36). In those cases, the open IPC channel can cause the script to hang after completion unless `process.disconnect()` is called, which does not occur when running scripts directly through `node` on the command line.

To fix, the IPC channel is only created if the `babel-node` process itself has an IPC channel, in which case messages are expected to be passed through.

In addition, tests for this behavior have been consolidated in `babel-node`'s fixtures, which now have options for handling IPC.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/13295"></a>

### CODE REVIEW

File: packages/babel-node/src/babel-node.js [hunk 1]
```diff
@@ -84,8 +84,12 @@ getV8Flags(async function (err, v8Flags) {
       throw err;
     }
 
+    // passthrough IPC only if babel-node itself has an IPC channel
+    const shouldPassthroughIPC = process.send != null;
```
Comment (JLHwung) [inline packages/babel-node/src/babel-node.js:88]: nit: Per [docs](https://nodejs.org/api/process.html#process_process_send_message_sendhandle_options_callback) we just need to check
```suggestion
    const shouldPassthroughIPC = process.send !== undefined;
```

**Review by JLHwung — APPROVED** [review]
Thanks for changes to fixture runner.

**Review by nicolo-ribaudo — APPROVED** [review]
Thanks!
