### PR TITLE
[babel 8] Enable `allowDeclareFields` option by default w/ Flow

### LINKED ISSUE #10039: Should not remove class fields when using flow
If the flow plugin runs before the class properties one (or if the class properties plugin isn't used), we remove uninitialize class fields:

```js
class Foo { x: string }
```

currently becomes
```js
class Foo {}
```

while it should be
```js
class Foo { x }
```

If someone still wants the old behavior, they can either use flow comments (as [offically recommended](https://github.com/facebook/flow/issues/6811#issuecomment-496808192)), or use the `ignoreUninitialized` option which will soon be added to the class properties plugin (https://github.com/babel/babel/pull/9141).

---

Is there anyone who wants to contribute for the first time to Babel? :slightly_smiling_face: 

> **NOTE** :warning::warning::warning: Since this is a breaking change, we won't merge the PR for a long time (before Babel 8), and it might seem that we are ignoring it.

If you don't know how to clone Babel, follow these steps: (you need to have `make` and `yarn` available on your machine).
1. Write a comment there to know other possible contributors that you are working on this bug.
1. Fork the repo
2. Run `git clone https://github.com/<YOUR_USERNAME>/babel.git && cd babel`
3. Run `yarn && make bootstrap`
4. Wait :hourglass_flowing_sand: 
5. Run `make watch` (or `make build` whenever you change a file)
6. Change the wrong `output.js` files in the `tests/fixture` folder of `@babel/plugin-transform-flow-strip-types` (if there are any)
7. Update the code!
8. `yarn jest [name-of-the-package-to-test]` to run the tests
    - If some test outputs don't match but the new results are correct, you can delete the bad `output.js` files and run the tests again
9. If it is working, run `make test` tu run all the tests
10. Run `git push` and open a PR!

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #10039
| Patch: Bug Fix?          |
| Major: Breaking Change?  | Yes
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

This is a backport of https://github.com/babel/babel/commit/635c7fd6a9279bed2b2a2797748b80f89584d4b6. The original PR is https://github.com/babel/babel/pull/10120, but after many rebases it has been completely rewritten.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/12457"></a>

### CODE REVIEW

File: packages/babel-helper-fixtures/src/index.js [hunk 1]
```diff
@@ -149,6 +149,8 @@ function pushTask(taskName, taskDir, suite, suiteName) {
     },
   };
 
+  delete taskOpts.BABEL_8_BREAKING;
```
Comment (nicolo-ribaudo) [inline packages/babel-helper-fixtures/src/index.js:152]: Without this `@babel/core` throws about the unknown `BABEL_8_BREAKING` option.

**Review by JLHwung — APPROVED** [review]

**Review by hzoo — APPROVED** [review]
