### PR TITLE
Throw a syntax error for a declare function with a body

### LINKED ISSUE #12046: Convert a TypeScript declare function with a body into a function.
## Bug Report

- [x] I would like to work on a fix!

**Current behavior**

Convert a TypeScript declare function with a body into a function.

[Try it out link](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=CYUwxgNghgTiAEAzArgOzAFwJYHtVJxwAoBKeAbwF8AoIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env%2Ctypescript&prettier=false&targets=&version=7.11.6&externalPlugins=)

Output:
```js
"use strict";

function foo() {}
```

**Input Code**

```js
declare function foo() {}

```

**Expected behavior**

It should throw an error like tsc([TypeScript Playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVJxwAoBKeAbwF8BuAKCA)). And it should support `errorRecovery`.

Also babel/parser should return a node of `TSDeclareFunction` instead of `FunctionDeclaration(declare: true)`.

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js`

```js
{
  "presets": ["@babel/preset-typescript"]
}
```

**Environment**

I don't think environment information is needed because this issue is simple, but I will provide it if it is needed for you guys.

**Possible Solution**

**Additional context**

While working in Prettier, I notice that `declare` disappears. ([Prettier Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEATOYA2BDATnAAgDMBXKMGAS2mIggAoBKA4AXxABoQIAHK6AM7JQeXBADuABTwIhKbJnHYAnkK4AjXNjABrODADKPbZSgBzZDFwk4XOAFt1cVOlQAZbOZLYzcAGIQuPbYMFTmyCDYJDAQnCAAFjD2mADq8ZTwAsZgcAayGZQAbhnKEWACaiCmAnC4MJJaZsHIRAo1XABWAgAeAEJauvoG2PZwbqZwLW22IF3dBqZmmHAAiiQQ8FOY7SDGuDW4EerYTpgAtDCVPLimMCmUqDDxyAAcAAxc1xA1KVo8Edc4AdCpMuABHdbwBq8OSRARnKBwZzOOL4CGUfANHzNJCtbYzGr2SiWawExbLNYbSa46ZcGAne6PZ5IABMdK0lEwiwAwhB7DiQECAKxxEg1AAqJzkeJ2hRsAEkoOhYAYwDc+ABBJUGGDKZZbGqsVhAA))
It is possible to fix this issue on Prettier side, but I think this is the parser's responsibility.

### PR DESCRIPTION
**Pull request by sosukesuzuki**
Sorry for creating PR for an issue that hasn't been triaged. If this isn't needed, please close.

| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            |  Fixes #12046
| Patch: Bug Fix?          | Maybe yes
| Major: Breaking Change?  | No
| Minor: New Feature?      | No
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  | Noe
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/12054"></a>

### CODE REVIEW

**Comment by JLHwung** [comment]
May need to check ancestry for `.declare`, or we track `isDeclare` in a context variable passed as arguments of the parse functions.

```ts
declare namespace n {
  function foo() {}
}
```
is also invalid.

**Comment by sosukesuzuki** [comment]
@JLHwung I've fixed it so can you review?

File: packages/babel-parser/src/parser/expression.js [hunk 1]
```diff
@@ -2101,6 +2101,8 @@ export default class ExpressionParser extends LValParser {
     node: N.BodilessFunctionOrMethodBase,
     type: string,
     isMethod?: boolean = false,
+    // eslint-disable-next-line no-unused-vars -- this is used in /plugins/typescript
+    isDeclare?: boolean = false,
```
Comment (kaicataldo) [inline packages/babel-parser/src/parser/expression.js:2105]: Not a big fan of modifying the base parser for this, but it does seem like it might be complicated to overload or wrap a bunch of functions in the plugin. Curious what the rest of the team thinks.

**Comment by nicolo-ribaudo** [comment]
Maybe we can add a Boolean `this.state.isDeclareContext` and only set/check it from the TS parser?

**Comment by sosukesuzuki** [comment]
If `this.state.isDeclareContext` is added, probably it could also be used to fix #11725?

**Comment by nicolo-ribaudo** [comment]
Yes, I _think_ it would help (I haven't checked the code yet).

**Comment by sosukesuzuki** [comment]
I addressed review comments (3471de1) and add test for `declare module` (c242660)

**Review by JLHwung — APPROVED** [review]
Nice work.

**Review by existentialism — APPROVED** [review]
💯

File: packages/babel-parser/src/plugins/typescript/index.js [hunk 2]
```diff
@@ -1764,6 +1774,16 @@ export default (superClass: Class<Parser>): Class<Parser> =>
...
       }
+      if (bodilessType === "TSDeclareFunction" && this.state.isDeclareContext) {
+        this.raise(node.start, TSErrors.DeclareFunctionHasImplementation);
+        if (
+          // $FlowIgnore
+          node.declare
+        ) {
+          this.finishNode(node, bodilessType);
+          return;
+        }
```
Comment (nicolo-ribaudo) [inline packages/babel-parser/src/plugins/typescript/index.js:1785]: Question: Why do we need to special-case this, rather than just parsing the (invalid) function body?

Comment (sosukesuzuki) [reply packages/babel-parser/src/plugins/typescript/index.js:1785]: What does `special-case` mean?

Comment (sosukesuzuki) [reply packages/babel-parser/src/plugins/typescript/index.js:1785]: I don't know if it's the same as what you're pointing out, I noticed a my mistake. I should have used `super.parseFunctionBodyAndFinish`.

Comment (nicolo-ribaudo) [reply packages/babel-parser/src/plugins/typescript/index.js]: I think you can remove this whole `if`, since `parseFunctionBodyAndFinish` would already be done anyway at the end of the function.

Comment (sosukesuzuki) [reply packages/babel-parser/src/plugins/typescript/index.js]: I got it. But I think we need this `if` to use `bodilessType` as the function node type.

Comment (nicolo-ribaudo) [reply packages/babel-parser/src/plugins/typescript/index.js]: Ohhh I missed it :upside_down_face:

**Review by nicolo-ribaudo — APPROVED** [review]
