### PR TITLE
fix: throw error when accessing private method without a getter

### LINKED ISSUE #12673: Get operation on private accessor without getter should throw
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

- [REPL](https://babeljs.io/en/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEDC0G8BQ1oDMD2GAUBKR0ATgKYAuAroQHbSkAWAlhAHQDEARmIQNzQC-KaBDLQOXbGHwIBApFWIB3OHmaYcubkA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.12.12&externalPlugins=%40babel%2Fplugin-proposal-private-methods%407.12.1)

Transpiled code doesn't throw an error in `foo()` and returns `undefined`.

**Input Code**

```js
class C {
  foo() { return this.#bar; }
  set #bar(a) {}
}

new C().foo();
```

**Expected behavior**

`new C().foo();` should throw a `TypeError`. 

- Example from Google Chrome Version 90.0.4393.0 Canary:
  ```
  VM490:2 Uncaught TypeError: '#bar' was defined without a getter
      at C.foo (<anonymous>:2:11)
      at <anonymous>:6:9
  ```
- Related `test262` test: [get-access-of-missing-private-getter.js](https://github.com/tc39/test262/blob/42bf3a9f7aed3790dc1d829f290dee033df41c5b/test/language/statements/class/elements/get-access-of-missing-private-getter.js).

**Babel Configuration:** See the REPL link

**Environment**

- Babel version(s): v7.12.12
- Node/npm version: 10.13
- OS: Using REPL
- Monorepo: Using REPL
- How you are using Babel: Using REPL

**Possible Solution**

`_classPrivateFieldGet` helper should not fallback to returning `descriptor.value` if `descriptor.get` is false-y. If `get` property exists but is `undefined`, it can throw this particular error.

**Additional context**

See `PrivateFieldGet-6.b` from [the spec](https://tc39.es/proposal-private-methods/#sec-privatefieldget):

```
PrivateFieldGet ( P, O )
    1. Assert: P is a Private Name.
    2. If O is not an object, throw a TypeError exception.
    3. If P.[[Kind]] is "field",
        a. Let entry be PrivateFieldFind(P, O).
        b. If entry is empty, throw a TypeError exception.
        c. Return entry.[[PrivateFieldValue]].
    4. Perform ? PrivateBrandCheck(O, P).
    5. If P.[[Kind]] is "method",
        a. Return P.[[Value]].
    6. Else,
        a. Assert: P.[[Kind]] is "accessor".
        b. If P does not have a [[Get]] field, throw a TypeError exception.
        c. Let getter be P.[[Get]].
        d. Return ? Call(getter, O).
```

### PR DESCRIPTION
**Pull request by fedeci**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #12673 
| Patch: Bug Fix?          | Yes
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

When trying to access a private accessor without a getter method now throws a `TypeError` instead of just returning `undefined`.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/12689"></a>

### CODE REVIEW

File: packages/babel-helper-create-class-features-plugin/src/fields.js [hunk 1]
```diff
@@ -224,11 +224,18 @@ const privateNameHandlerSpec = {
...
           this.receiver(member),
           t.cloneNode(id),
         ]);
+      } else if (setId) {
+        if (file.availableHelper("writeOnlyError")) {
+          return t.callExpression(file.addHelper("writeOnlyError"), [
+            t.stringLiteral(name),
+          ]);
+        }
+        return;
```
Comment (fedeci) [inline packages/babel-helper-create-class-features-plugin/src/fields.js:238]: Should this throw an error?

Comment (JLHwung) [reply packages/babel-helper-create-class-features-plugin/src/fields.js:238]: We should fallback to what we did in `getId` when `writeOnlyError` is not available, but we could nudge users to update `@babel/helpers` via warning messages, as it deems a runtime error that most users should avoid to use.

File: packages/babel-helper-create-class-features-plugin/src/fields.js [hunk 2]
```diff
@@ -224,11 +224,20 @@ const privateNameHandlerSpec = {
...
         ]);
+      } else if (setId) {
+        if (file.availableHelper("writeOnlyError")) {
+          return t.callExpression(file.addHelper("writeOnlyError"), [
+            t.stringLiteral(name),
+          ]);
+        }
+        console.warn(
+          `@babel/helpers is outdated, update it to silence this warning.`,
+        );
```
Comment (JLHwung) [inline packages/babel-helper-create-class-features-plugin/src/fields.js:240]: If the `writeOnlyError` helper is not available, we should still transform using
``` t.callExpression(file.addHelper("classPrivateFieldGet"), [
          this.receiver(member),
          t.cloneNode(id),
        ]);
```
otherwise it becomes a breaking change for those update `@babel/deps` but pin `@babel/helper`.

Comment (fedeci) [reply packages/babel-helper-create-class-features-plugin/src/fields.js:240]: Right🤦🏻‍♂️

**Review by jridgewell — APPROVED** [review]

File: packages/babel-helpers/src/helpers.js [hunk 3]
```diff
@@ -875,6 +875,12 @@ helpers.readOnlyError = helper("7.0.0-beta.0")`
   }
 `;
 
+helpers.writeOnlyError = helper("7.12.12")`
```
Comment (nicolo-ribaudo) [inline packages/babel-helpers/src/helpers.js:878]: I just noticed that this should be 7.12.13, because in 7.12.12 the helper isn't available. Do you mind opening a PR? 🙏
