### PR TITLE
fix: Uninitialized var declarator in loop marked as constantViolation

### LINKED ISSUE #17166: uninitialized var declarator in loop marked as constantViolation
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
const parser = require("@babel/parser");
const traverse = require("@babel/traverse").default;

const code = `
var y;
y = 1;
x = 1;
for (;;) {
  var x;
}
`;

const ast = parser.parse(code);

traverse(ast, {
  Program(path) {
    path.scope.dump();
    console.log(path.scope.getBinding("x").constantViolations[0].type);
  },
});
```

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

Current: `var x;` VariableDeclarator is marked as a constantViolation

 - y { constant: false, references: 0, violations: 1, kind: 'var' }
 - x { constant: false, references: 0, violations: 2, kind: 'var' }

Expected: `x` is hoisted like `y`. Since there's no initializer there also shouldn't be an assignment/constantViolation in the loop

 - y { constant: false, references: 0, violations: 1, kind: 'var' }
 - x { constant: false, references: 0, violations: 1, kind: 'var' }

### Environment

  System:
    OS: Linux 6.6 Manjaro Linux
  Binaries:
    Node: 20.10.0 - /run/user/1000/fnm_multishells/1178_1740773138966/bin/node
    Yarn: 4.1.1 - /run/user/1000/fnm_multishells/1178_1740773138966/bin/yarn
    npm: 10.2.3 - /run/user/1000/fnm_multishells/1178_1740773138966/bin/npm
    pnpm: 10.4.0 - /run/user/1000/fnm_multishells/1178_1740773138966/bin/pnpm
  npmPackages:
    @babel/generator: ^7.26.9 => 7.26.9 
    @babel/parser: ^7.26.9 => 7.26.9 
    @babel/template: ^7.26.9 => 7.26.9 
    @babel/traverse: ^7.26.9 => 7.26.9 

### Possible solution

_No response_

### Additional context

Regression from https://github.com/babel/babel/pull/15027 (\@babel/traverse 7.19.4)

This code would probably not be written by a human, but I've seen it occur in the output of other build tools and obfuscators that I want to analyze with the Babel API.

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #17166 
| Patch: Bug Fix?          | √
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | √
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

File: packages/babel-traverse/src/scope/binding.ts [hunk 1]
```diff
@@ -45,7 +45,14 @@ export default class Binding {
     this.kind = kind;
 
     if ((kind === "var" || kind === "hoisted") && isDeclaredInLoop(path)) {
-      this.reassign(path);
+      if (
+        !path.isVariableDeclarator() ||
+        (path.parentPath.parentPath.isForXStatement() &&
+          path.parentPath.parentKey === "left") ||
+        path.node.init
```
Comment (JLHwung) [inline packages/babel-traverse/src/scope/binding.ts:52]: Can we move this check into `isDeclaredInLoop`? Since it already performed the ForXStatement check there.

File: packages/babel-traverse/src/scope/binding.ts [hunk 2]
```diff
@@ -114,19 +114,26 @@ export default class Binding {
...
     ) {
-      return true;
+      if (parentPath.isFunctionParent()) return false;
+      if (
+        parentPath.isWhile() ||
+        parentPath.isForXStatement() ||
+        (parentPath.isForStatement() && key === "body")
+      ) {
+        return true;
+      }
```
Comment (JLHwung) [inline packages/babel-traverse/src/scope/binding.ts:136]: Can it be simplified to
```js
function isInitInLoop(path: NodePath) {
  const isFunctionDeclarationOrHasInit = !path.isVariableDeclarator() || path.node.init;
  for (
    let { parentPath, key } = path;
    parentPath;
    { parentPath, key } = parentPath
  ) {
    if (parentPath.isFunctionParent()) return false;
    if (
      (parentPath.isForXStatement() && key === "left") ||
      (parentPath.isLoop() && key === "body" && isFunctionDeclarationOrHasInit)
    ) {
      return true;
    }
  }
  return false;
}
```
?

File: packages/babel-traverse/test/scope.js [hunk 3]
```diff
@@ -431,6 +431,12 @@ describe("scope", () => {
       expect(isAConstant("while (1) { var a = 1; }")).toBe(false);
       expect(isAConstant("do { var a = 1; } while (1)")).toBe(false);
 
+      expect(isAConstant("for (_ of ns) { var a; }")).toBe(true);
+      expect(isAConstant("for (_ in ns) { var a; }")).toBe(true);
+      expect(isAConstant("for (;;) { var a; }")).toBe(true);
+      expect(isAConstant("while (1) { var a; }")).toBe(true);
+      expect(isAConstant("do { var a; } while (1)")).toBe(true);
+
```
Comment (JLHwung) [inline packages/babel-traverse/test/scope.js:439]: Can we also add test cases for function declarations? For example

```js
expect(isAConstant("for (_ of ns) { function a() {} }")).toBe(false);
```

**Review by JLHwung — APPROVED** [review]
LGTM, thanks.
