### PR TITLE
fix: Duplicate declaration in transformed for...of

### LINKED ISSUE #11920: Repl error – Duplicate declaration – when using the same let-variable in for-of loop
**Current behavior**

Using [REPL](https://babeljs.io/repl#?browsers=firefox%2074&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABMAFATwJQG8BQjlwBOKANgKZSIAeicwimu--5lNAvAwNx7OEUhCSKj3wBfHGKA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env%2Cenv&prettier=false&targets=&version=7.11.1&externalPlugins=) (current/default v7.11.1) with all of checkboxes disabled:

(Explicitly disable `ENV` or enable `es2015` to see the error via the link above)

**Input Code**

```js
function f(y){
  for(let x of y){
    let x = y;
    return x;
  }
}
```

**Expected behavior**

That should successfully compile just as this code does:

```js
function f(z){
  for(let x=0; x<y; x++){
    let x = y;
    return x;
  }
}
```

Which gives

```js
"use strict";

function f(z) {
  for (var x = 0; x < y; x++) {
    var _x = y;
    return _x;
  }
}
```

**Actual behavior**

However, the error is:

```
/repl.js: Duplicate declaration "x"
  1 | function f(y){
  2 |   for(let x of y){
> 3 |     let x = y;
    |         ^
  4 |     return x;
  5 |   }
  6 | }
```

**Additional context**

If the ES6 transpiling (`let` to `var`) is disabled (ENV: `firefox 74`), that code correctly gives:

```js
"use strict";

function f(y) {
  for (let x of y) {
    let x = y;
    return x;
  }
}
```

**Environment**

- Babel version: REPL  v7.11.1
- Browser: Firefox 76 on Windows 7

### LINKED ISSUE #14379: [Bug]: Duplicate declaration in transformed for...of
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
function toLowerCase(){}
low = {toLowerCase}
const v1 = fullStr => {
    const v2 = new Map();
    const v3 = [1,2,3];
    for (let v4 of v3) {
        let {
            v20: v0,
            v4 : v4
        } = {
            [6]: 5,
            get: -12
        };
    }
    return v2;
};
v1(low)
```
Here is the [REPL](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=false&spec=false&loose=true&code_lz=GYVwdgxgLglg9mABFOAZOB3ApgJwMICGAzlgBQCUA3gL4BQANpogLyKUrrb7FZ0QJEoiAG4BGFolD16AZSg4WAPja1EaxPzCCRAJglgsGRAFkCABwoBuVes3bhAZgkBtUQBodbhwF1r6yXAKpPRYQsIALIhwwCIO5Cr-_iFClDaJicI6AAwAXCJZbmnp6hGIeRFF_tQSqcWJzgBs3nkArIV1_gDmoXkAtKI6lerUfsNFOKEgOEiZ1iO0YsGY5EA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=unambiguous&lineWrap=true&presets=env&prettier=false&targets=&version=7.17.8&externalPlugins=&assumptions=%7B%7D)

### Configuration file name

babel.config.json

### Configuration

```json
{
  "sourceType": "unambiguous",
  "presets": ["@babel/preset-env"],
  "plugins": [
    "@babel/plugin-transform-runtime"
  ]
}
```

### Current and expected behavior

The input code can be run by node, but when it is converted by babel, there is an error report
```bash
Duplicate declaration "v4"
```

### Environment

- babel 
- - ├── @babel/cli@7.17.0=6
- - ├── @babel/generator@7.17.3
- - ├── @babel/plugin-transform-runtime@7.17.0
- - ├── @babel/preset-env@7.16.11
- Node: [v17.3.0]
- npm version [8.5.2]
- os [ubuntu 20.04]

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #14379, Fixes #11920 
| Patch: Bug Fix?          |√
| Major: Breaking Change?  |×
| Minor: New Feature?      |×
| Tests Added + Pass?      | √
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14564"></a>

### CODE REVIEW

**Comment by liuxingbaoyu** [comment]
No fix due to missing tests in `no-helper-implementation.ts`.

**Comment by nicolo-ribaudo** [comment]
I would be ok with saying that `no-helper-implementation.ts` doesn't receive any bug fix. That implementation is only used with very old `@babel/core` versions, so users can easily switch to the new/better implementation with a simple upgrade.

**Review by nicolo-ribaudo — APPROVED** [review]
Thanks!

File: packages/babel-plugin-transform-for-of/src/index.ts [hunk 1]
```diff
@@ -167,21 +167,29 @@ export default declare((api, options: Options) => {
...
     const iterationValue = t.memberExpression(
       t.cloneNode(right),
       t.cloneNode(iterationKey),
       true,
     );
 
+    if (
+      t.isBlockStatement(loop.body) &&
+      Object.keys(path.getBindingIdentifiers()).some(id =>
+        path.get("body").scope.hasOwnBinding(id),
```
Comment (JLHwung) [inline packages/babel-plugin-transform-for-of/src/index.ts:180]: Nit: `path.get("body").scope` can be hoisted.

File: packages/babel-plugin-transform-for-of/src/index.ts [hunk 2]
```diff
@@ -234,10 +242,19 @@ export default declare((api, options: Options) => {
...
-        path.ensureBlock();
-
-        (node.body as t.BlockStatement).body.unshift(declar);
+        let blockBody;
+        const body = path.get("body");
+        if (
+          body.isBlockStatement() &&
+          Object.keys(path.getBindingIdentifiers()).some(id =>
+            body.scope.hasOwnBinding(id),
+          )
```
Comment (JLHwung) [inline packages/babel-plugin-transform-for-of/src/index.ts:251]: For further PRs: this check is similar to
https://github.com/babel/babel/blob/cc2de3b7ee85d7bb52ebfae799f1a1c6af2ad8f6/packages/babel-plugin-transform-destructuring/src/util.ts#L12-L15

Maybe we can extract them into a new helper.

**Review by JLHwung — APPROVED** [review]

File: packages/babel-plugin-transform-for-of/src/index.ts (hunk 2 above)
Comment (nicolo-ribaudo) [reply packages/babel-plugin-transform-for-of/src/index.ts:251]: 100% agree, I was thinking the same thing while reviewing.

File: packages/babel-plugin-transform-for-of/src/index.ts [hunk 3]
```diff
@@ -9,6 +9,24 @@ export interface Options {
   loose?: boolean;
 }
 
+function buildLoopBody(path, declar, newBody?) {
```
Comment (JLHwung) [inline packages/babel-plugin-transform-for-of/src/index.ts:12]: Can you add type annotations to the params here? This can save me some time :P, as I am working on enabling `noImplicitAny` compiler option.

Comment (liuxingbaoyu) [reply packages/babel-plugin-transform-for-of/src/index.ts]: of course.

**Review by nicolo-ribaudo — APPROVED** [review]
