### PR TITLE
Do not mutate ast

### LINKED ISSUE #7987: 'transformFromAst' should avoid mutating the AST passed into it
## Bug Report

**Current Behavior**
The description in the documentation for `transformFromAst` in `@babel/core` does not make it obvious that the input AST object is transformed *in-place*. A cursory reading would imply that the input is readonly and only under closer inspection hints that the input might be changed.

**Possible Solution**
Add a simple blurb that says 

> The AST object passed in is transformed in-place. To preserve the original object, make a deep copy before passing it in.

### PR DESCRIPTION
**Pull request by thiagoarrais**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #7987  
| Patch: Bug Fix?          | 👍
| Major: Breaking Change?  | :-1:
| Minor: New Feature?      | :-1:
| Tests Added + Pass?      | :+1:
| Documentation PR Link    | 
| Any Dependency Changes?  | :-1:
| License                  | MIT

This clones the given ast prior to working on it to avoid mutating the AST given to `transformFromAST`.

This is work in progress and intended as input for review. Some questions I have:

- Is this the intended use for `t.cloneNode`?
- `parse.js` was the easiest place to insert the test. I'm not sure where it should go

Please check inline review comments for context.

### CODE REVIEW

File: packages/babel-core/src/transformation/normalize-file.js [hunk 1]
```diff
@@ -69,12 +69,14 @@ export default function normalizeFile(
...
   }
 
+  debugger; // eslint-disable-line no-debugger
   if (ast) {
     if (ast.type === "Program") {
       ast = t.file(ast, [], []);
     } else if (ast.type !== "File") {
       throw new Error("AST root must be a Program or File node");
     }
+    ast = t.cloneNode(ast);
```
Comment (thiagoarrais) [inline packages/babel-core/src/transformation/normalize-file.js]: Is this the intended use for t.cloneNode?

File: packages/babel-core/test/parse.js [hunk 2]
```diff
@@ -28,4 +28,32 @@ describe("parse", function() {
...
+    const node = parse(program, {
+      filename: fixture("input.js"),
+      cwd: fixture(),
+    });
+    expect(node.program.body[0].declarations[0].id.name).toBe("identifier");
+    expect(node).not.toBeNull();
+    transformFromAst(node, program, {
+      filename: fixture("input.js"),
+      cwd: fixture(),
+      plugins: [
```
Comment (thiagoarrais) [inline packages/babel-core/test/parse.js]: this inline plugin forces the AST to change. any ideas on how to write it more succinctly?

File: packages/babel-core/test/parse.js [hunk 3]
```diff
@@ -28,4 +28,32 @@ describe("parse", function() {
     });
     expect(JSON.parse(JSON.stringify(result))).toEqual(output);
   });
+
```
Comment (thiagoarrais) [inline packages/babel-core/test/parse.js]: parse.js was the easiest place to insert this test. I'm not sure where it should go. My first instinct was to add it to `test/transformation.js`, but there weren't any describe'd tests there...

File: packages/babel-core/test/parse.js (hunk 2 above)
Comment (nicolo-ribaudo) [reply packages/babel-core/test/parse.js]: You can replace `function() { return` with `() => (`, but it is not really important

File: packages/babel-core/src/transformation/normalize-file.js (hunk 1 above)
Comment (nicolo-ribaudo) [reply packages/babel-core/src/transformation/normalize-file.js]: The problem is that `cloneNode` only clones properties which represents other nodes. It doesn't copy every property (e.g. position, extras...).

I would use lodash's cloneDeep function.

Comment (thiagoarrais) [reply packages/babel-core/src/transformation/normalize-file.js]: Good idea. Will take a look at that.

File: packages/babel-core/test/parse.js (hunk 2 above)
Comment (thiagoarrais) [reply packages/babel-core/test/parse.js]: Yup. I was wondering if you folks already have some established helper or something for this kind of stuff.

**Comment by thiagoarrais** [comment]
I think this is good to go now. I'm removing the WIP marker.

**Comment by thiagoarrais** [comment]
Closing and reopening to try and trigger a Travis rebuild.

File: packages/babel-core/test/api.js [hunk 4]
```diff
@@ -168,6 +182,30 @@ describe("api", function() {
...
+                path.node.name = "replaced";
+              },
+            },
+          };
+        },
+      ],
+    });
+
+    expect(code).toBe("const replaced = 1;");
+    expect(node.program.body[0].declarations[0].id.name).toBe(
```
Comment (hzoo) [inline packages/babel-core/test/api.js]: Since there was a discussion on deep cloning the test (or a new test) should probably reflect that, like check the the other metadata fields aren't changed?

Comment (thiagoarrais) [reply packages/babel-core/test/api.js]: That would be nice, yes. Any ideas on how to force a metadata change? I'm outputing the AST for this transform and it doesn't seem to change any metadata fields...

Comment (thiagoarrais) [reply packages/babel-core/test/api.js]: I can add something like that if you folks think it would be useful. I am not really in a good position to evaluate that, though. Do people usually sprinkle such metadata fields into their ASTs?

Comment (hzoo) [reply packages/babel-core/test/api.js]: Actually this works fine! thanks!
