### PR TITLE
Fix NodePath.referencesImport for  JSXMemberExpression

### LINKED ISSUE #14375: [Bug]: referencesImport is always false for JSXMemberExpression
### 💻

- [x] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```js
import { parse } from "@babel/parser";
import traverse from "@babel/traverse";

const ast = parse(
  `\
import * as mod from "mod";
mod.name();
<mod.name />;
`,
  {
    sourceType: "module",
    plugins: ["jsx"],
  }
);

traverse.default(ast, {
  MemberExpression(path) {
    if (path.referencesImport("mod", "name")) {
      // referencesImport works with MemberExpression
      console.log("MemberExpression references `name` in `mod`");
    }
  },
  JSXMemberExpression(path) {
    if (path.referencesImport("mod", "name")) {
      // but not with JSXMemberExpression
      // not executed
      console.log("JSXMemberExpression references `name` in `mod`");
    }
  },
});
```

https://codesandbox.io/s/trusting-platform-g4znd2

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

For `MemberExpression`, `referencesImport` infers if a function is imported from given source.
For `JSXMemberExpression` it always returns `false`.

As the structure is similar, I'd expect `referencesImport` to be useful with both of these types.

### Environment

```
  System:
    OS: Linux 5.4 Debian GNU/Linux 10 (buster) 10 (buster)
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.18.1/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  npmPackages:
    @babel/parser: 7.17.8 => 7.17.8
    @babel/traverse: 7.17.3 => 7.17.3
```

### Possible solution

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by swandir**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #14375
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

As [described](https://github.com/babel/babel/issues/14375#issuecomment-1073271503) in the issue, `NodePath.referencesIssue` is only missing a check for `JSXMemberExpression` to support it.

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/14403"></a>

### CODE REVIEW

File: packages/babel-traverse/src/path/introspection.ts [hunk 1]
```diff
@@ -181,7 +181,9 @@ export function referencesImport(
 ): boolean {
   if (!this.isReferencedIdentifier()) {
     if (
-      (this.isMemberExpression() || this.isOptionalMemberExpression()) &&
+      (this.isMemberExpression() ||
+        this.isJSXMemberExpression() ||
+        this.isOptionalMemberExpression()) &&
       (this.node.computed
         ? isStringLiteral(this.node.property, { value: importName })
         : (this.node.property as t.Identifier).name === importName)
```
Comment (swandir) [inline packages/babel-traverse/src/path/introspection.ts:189]: I tried moving `this.isJSXMemberExpression()` outside of the existing `&&` expression, but `this.node` type resolves to `never` for some reason

```ts
(this.isJSXMemberExpression() &&
  (this.node.property as t.JSXIdentifier).name === importName))
        ^
        never
```

Comment (swandir) [reply packages/babel-traverse/src/path/introspection.ts:189]: Doing it like this isn't good, thought. `this.isJSXMemberExpression()` basically disables type checking for the rest of the expression.

Comment (swandir) [reply packages/babel-traverse/src/path/introspection.ts:189]: Ok, so `JSXMemberExpression` is not a part of `Expression` union type in `babel-types/src/ast-types/generated`. Searching for the place to add it.

File: packages/babel-types/src/definitions/jsx.ts [hunk 2]
```diff
@@ -107,6 +107,7 @@ defineType("JSXIdentifier", {
 
 defineType("JSXMemberExpression", {
   visitor: ["object", "property"],
+  aliases: ["Expression"],
```
Comment (swandir) [inline packages/babel-types/src/definitions/jsx.ts:110]: Is it ok to do this change in the same PR?

Comment (swandir) [reply packages/babel-types/src/definitions/jsx.ts:110]: Or perhaps it's better to extend `this` type for `referencesImport` with concrete `JSXMemberExpression` type 🤔

File: packages/babel-traverse/src/path/introspection.ts [hunk 3]
```diff
@@ -175,16 +175,18 @@ export function isStatementOrBlock(this: NodePath): boolean {
  */
 
 export function referencesImport(
-  this: NodePath<t.Expression>,
+  this: NodePath,
```
Comment (swandir) [inline packages/babel-traverse/src/path/introspection.ts:178]: Because `JSXMemberExpression` is not an `Expression`

File: packages/babel-traverse/src/path/introspection.ts [hunk 4]
```diff
@@ -175,16 +175,18 @@ export function isStatementOrBlock(this: NodePath): boolean {
...
-      (this.isMemberExpression() || this.isOptionalMemberExpression()) &&
-      (this.node.computed
-        ? isStringLiteral(this.node.property, { value: importName })
-        : (this.node.property as t.Identifier).name === importName)
+      (this.isJSXMemberExpression() &&
+        (this.node.property as t.JSXIdentifier).name === importName) ||
+      ((this.isMemberExpression() || this.isOptionalMemberExpression()) &&
+        (this.node.computed
+          ? isStringLiteral(this.node.property, { value: importName })
+          : (this.node.property as t.Identifier).name === importName))
```
Comment (swandir) [inline packages/babel-traverse/src/path/introspection.ts:189]: `JSXMemberExpression` is never computed

File: packages/babel-traverse/src/path/introspection.ts (hunk 3 above)
Comment (swandir) [reply packages/babel-traverse/src/path/introspection.ts]: Sure, done
Though I wonder what's the point of narrowing the type of `this` here? all the other methods accept `NodePath` 🤔

Comment (nicolo-ribaudo) [reply packages/babel-traverse/src/path/introspection.ts]: Uhm yes that's a good observation. This method always work, it just return `false` for other node types.

You are right, `NodePath` is good enough here. Sorry!

**Review by nicolo-ribaudo — APPROVED** [review]

File: packages/babel-traverse/src/path/introspection.ts (hunk 3 above)
Comment (swandir) [reply packages/babel-traverse/src/path/introspection.ts:178]: Yeah, I had a thought that making `this` type narrower doesn't make it more convenient for the TypeScript user, since they either would already be in a context where the type matches (e.g in a visitor) and won't notice, or would be forced to preclude the call with a manual check, which is performed inside the method anyway.

> Sure, done

Reverted 😃

Comment (swandir) [reply packages/babel-traverse/src/path/introspection.ts:178]: Although...

```ts
function f(path: NodePath) {
  path.referencesImport("moduleSource", "importName");
}
```

this does not produce a TS error now 🤔

Comment (nicolo-ribaudo) [reply packages/babel-traverse/src/path/introspection.ts:178]: Yeah that's correct, right? It can return `false` for every unsupported node type, but it always knows what to return.
