### PR TITLE
fix: do not remove shadowed for-loop declarators

### LINKED ISSUE #11231: Property left of ForInStatement expected node to be of a type ["VariableDeclaration","LVal"] but instead got null
## Bug Report
As of 7.8.7 I'm getting the error `Property left of ForInStatement expected node to be of a type ["VariableDeclaration","LVal"] but instead got null`

Our CI runs like so automatically on every commit:
```yaml
    - apt install -y nodejs npm
    - npm -g -D install webpack webpack-cli babel-loader @babel/core @babel/preset-env babel-polyfill
    - cd ./webapp/js/
    - webpack --config webpack.dist.js
```
Here's the stack trace coming out of webpack CLI
```
ERROR in ./apps/application/controllers/controllers.addactivity.js
Module build failed (from /usr/local/lib/node_modules/babel-loader/lib/index.js):
TypeError: /Users/henry/Documents/application/application-website/webapp/js/apps/application/controllers/controllers.addactivity.js: Property left of ForInStatement expected node to be of a type ["VariableDeclaration","LVal"] but instead got null
    at Object.validate (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/types/lib/definitions/utils.js:131:11)
    at validateField (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/types/lib/validators/validate.js:24:9)
    at Object.validate (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/types/lib/validators/validate.js:17:3)
    at NodePath._replaceWith (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/replacement.js:172:7)
    at NodePath._remove (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/removal.js:55:10)
    at NodePath.remove (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/removal.js:34:8)
    at hooks (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/lib/removal-hooks.js:11:12)
    at NodePath._callRemovalHooks (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/removal.js:46:9)
    at NodePath.remove (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/removal.js:26:12)
    at convertFunctionParams (/usr/local/lib/node_modules/@babel/preset-env/node_modules/@babel/plugin-transform-parameters/lib/params.js:88:30)
    at PluginPass.Function (/usr/local/lib/node_modules/@babel/preset-env/node_modules/@babel/plugin-transform-parameters/lib/index.js:30:53)
    at newFn (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:179:21)
    at NodePath._call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:90:31)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitMultiple (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:79:17)
    at TraversalContext.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:138:19)
    at Function.traverse.node (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitMultiple (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:79:17)
    at TraversalContext.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:138:19)
    at Function.traverse.node (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:112:16)
 @ multi /usr/local/lib/node_modules/babel-polyfill/ ./application/ironhide.js ./application/utility.js ./apps/application/services/services.js ./apps/application/services/services.appsdevices.js ./apps/application/services/services.branding.js ./apps/application/services/services.ionic.webapp.js ./apps/application/services/services.geo.webapp.js ./apps/application/services/services.minicache.js ./apps/application/services/services.devicesync.webapp.js ./apps/application/services/services.unifyapi.webapp.js ./apps/application/services/services.webappmenu.webapp.js ./apps/application/services/services.localforage.webapp.js ./apps/application/services/services.benefitplanutilities.js ./apps/application/services/services.dateutilities.js ./apps/application/directives/directives.earningsrow.js ./apps/application/directives/directives.helptext.js ./apps/application/directives/directives.helpmodal.js ./apps/application/directives/directives.miniplanbuilder.js ./apps/application/directives/directives.progressbar.js ./apps/application/directives/directives.validation.js ./apps/application/directives/directives.cyberfilters.js ./apps/application/directives/directives.chart.js ./apps/application/directives/directives.surveypage.js ./apps/application/directives/directives.focus.js ./apps/application/directives/directives.selectemployeetags.js ./apps/application/directives/directives.selectcompanyid.js ./apps/application/data/applicationDataSource.js ./apps/application/components/applicationGrid.js ./apps/workstation/components/grid.js ./apps/application/controllers/controllers.js ./apps/application/controllers/controllers.auth.js ./apps/application/controllers/controllers.timeline.js ./apps/application/controllers/controllers.commprefs.js ./apps/application/controllers/controllers.account.js ./apps/application/controllers/controllers.addactivity.js ./apps/application/controllers/controllers.appsdevices.js ./apps/application/controllers/controllers.benefit.js ./apps/application/controllers/controllers.earnings.js ./apps/application/controllers/controllers.challenges.js ./apps/application/controllers/controllers.company.js ./apps/application/controllers/controllers.customer.js ./apps/application/controllers/controllers.rewardsmall.js ./apps/application/controllers/controllers.orgsettings.taxreporting.js ./apps/application/controllers/controllers.newrewardsettings.js ./apps/application/controllers/controllers.reports.individuals.js ./apps/application/controllers/controllers.reports.activities.js ./apps/application/controllers/controllers.reports.rewards.js ./apps/application/controllers/controllers.reports.disbursements.js ./apps/application/controllers/controllers.reports.surveys.js ./apps/application/controllers/controllers.reports.healthcard.js ./apps/application/controllers/controllers.communications.js ./apps/application/controllers/controllers.events.js ./apps/application/controllers/controllers.menu.js ./apps/application/controllers/controllers.surveys.js ./apps/application/controllers/controllers.manage_orgs.js ./apps/application/controllers/controllers.employeeaddress.js ./apps/application/webapp.js webapp[35]

ERROR in ./application/ironhide.js
Module build failed (from /usr/local/lib/node_modules/babel-loader/lib/index.js):
TypeError: /Users/henry/Documents/application/application-website/webapp/js/application/ironhide.js: Property left of ForInStatement expected node to be of a type ["VariableDeclaration","LVal"] but instead got null
    at Object.validate (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/types/lib/definitions/utils.js:131:11)
    at validateField (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/types/lib/validators/validate.js:24:9)
    at Object.validate (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/types/lib/validators/validate.js:17:3)
    at NodePath._replaceWith (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/replacement.js:172:7)
    at NodePath._remove (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/removal.js:55:10)
    at NodePath.remove (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/removal.js:34:8)
    at hooks (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/lib/removal-hooks.js:11:12)
    at NodePath._callRemovalHooks (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/removal.js:46:9)
    at NodePath.remove (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/removal.js:26:12)
    at convertFunctionParams (/usr/local/lib/node_modules/@babel/preset-env/node_modules/@babel/plugin-transform-parameters/lib/params.js:88:30)
    at PluginPass.Function (/usr/local/lib/node_modules/@babel/preset-env/node_modules/@babel/plugin-transform-parameters/lib/index.js:30:53)
    at newFn (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:179:21)
    at NodePath._call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:90:31)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitMultiple (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:79:17)
    at TraversalContext.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:138:19)
    at Function.traverse.node (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/context.js:112:16)
 @ multi /usr/local/lib/node_modules/babel-polyfill/ ./application/ironhide.js ./application/utility.js ./apps/application/services/services.js ./apps/application/services/services.appsdevices.js ./apps/application/services/services.branding.js ./apps/application/services/services.ionic.webapp.js ./apps/application/services/services.geo.webapp.js ./apps/application/services/services.minicache.js ./apps/application/services/services.devicesync.webapp.js ./apps/application/services/services.unifyapi.webapp.js ./apps/application/services/services.webappmenu.webapp.js ./apps/application/services/services.localforage.webapp.js ./apps/application/services/services.benefitplanutilities.js ./apps/application/services/services.dateutilities.js ./apps/application/directives/directives.earningsrow.js ./apps/application/directives/directives.helptext.js ./apps/application/directives/directives.helpmodal.js ./apps/application/directives/directives.miniplanbuilder.js ./apps/application/directives/directives.progressbar.js ./apps/application/directives/directives.validation.js ./apps/application/directives/directives.cyberfilters.js ./apps/application/directives/directives.chart.js ./apps/application/directives/directives.surveypage.js ./apps/application/directives/directives.focus.js ./apps/application/directives/directives.selectemployeetags.js ./apps/application/directives/directives.selectcompanyid.js ./apps/application/data/applicationDataSource.js ./apps/application/components/applicationGrid.js ./apps/workstation/components/grid.js ./apps/application/controllers/controllers.js ./apps/application/controllers/controllers.auth.js ./apps/application/controllers/controllers.timeline.js ./apps/application/controllers/controllers.commprefs.js ./apps/application/controllers/controllers.account.js ./apps/application/controllers/controllers.addactivity.js ./apps/application/controllers/controllers.appsdevices.js ./apps/application/controllers/controllers.benefit.js ./apps/application/controllers/controllers.earnings.js ./apps/application/controllers/controllers.challenges.js ./apps/application/controllers/controllers.company.js ./apps/application/controllers/controllers.customer.js ./apps/application/controllers/controllers.rewardsmall.js ./apps/application/controllers/controllers.orgsettings.taxreporting.js ./apps/application/controllers/controllers.newrewardsettings.js ./apps/application/controllers/controllers.reports.individuals.js ./apps/application/controllers/controllers.reports.activities.js ./apps/application/controllers/controllers.reports.rewards.js ./apps/application/controllers/controllers.reports.disbursements.js ./apps/application/controllers/controllers.reports.surveys.js ./apps/application/controllers/controllers.reports.healthcard.js ./apps/application/controllers/controllers.communications.js ./apps/application/controllers/controllers.events.js ./apps/application/controllers/controllers.menu.js ./apps/application/controllers/controllers.surveys.js ./apps/application/controllers/controllers.manage_orgs.js ./apps/application/controllers/controllers.employeeaddress.js ./apps/application/webapp.js webapp[1]
```

Our config is:
```js
use: {
    loader: 'babel-loader',
    query: {
        /* This makes babel use the node global install directory as the project root during compile so that presets installed globally load correctly  */
        cwd: path.resolve(nodeModulesPath),
        presets: [
            [
                '@babel/preset-env', {
                    targets: {
                        'ie': '11'
                    },
                    //'corejs': 2, // @see https://babeljs.io/docs/en/babel-preset-env#corejs
                    'useBuiltIns': false
                }
            ]
        ] // presets
    } // query
}
```

This has been mentioned here as well:
https://github.com/apexcharts/apexcharts.js/issues/1359

```
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- Node/npm version: [Node v11.15.0/npm 6.14.2]
- OS: [OSX and Ubuntu]
- Monorepo: [no]
- How you are using Babel: [`loader` via Webpack CLI]
```
The problem started on March 5th when our CI webpacks started failing.

### PR DESCRIPTION
**Pull request by JLHwung**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #11231 
| Patch: Bug Fix?          | Y
| Tests Added + Pass?      | Yes
| License                  | MIT

Whitelist var declarator in for loop when we are removing shadowed uninitialized variable declarators.

This PR is a follow-up to #11158 .

### CODE REVIEW

File: packages/babel-plugin-transform-parameters/src/params.js [hunk 1]
```diff
@@ -76,11 +76,14 @@ export default function convertFunctionParams(path, loose) {
           switch (node.type) {
             case "VariableDeclarator":
               if (node.init === null) {
-                redeclarator.remove();
-              } else {
-                state.iife = true;
+                // for (var x in {}); should not be removed
+                const declaration = redeclarator.parentPath;
+                if (!declaration.parentPath.isFor({ left: declaration.node })) {
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-parameters/src/params.js]: In `for (...;...;...)` statements `left` doesn't exist: it's called `init`.
If you meant to only check for-of and for-in (but I don't think so), then you need `ForXStatement`.

:bulb: Idea: an ESLint plugin that prevents us from checking non-existent properties (like in this case).

**Comment by nicolo-ribaudo** [comment]
Can you also add an input/output test?

**Comment by nicolo-ribaudo** [comment]
Release is coming!
