### PR TITLE
fix: Keep type annotations in `syntacticPlaceholders` mode

### LINKED ISSUE #16904: [Bug]: Template parser erases function argument type annotation when using syntactic placeholder
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

```ts
const b = require('@babel/core');
const t = require('@babel/template');

const template = t.smart(`function foo(%%arg%%: string) : void { }`, {
  plugins: ['typescript'],
  syntacticPlaceholders: true,
});

const stmt = template({
  arg: b.types.identifier('bar'),
});

console.log(stmt.params[0]);
```

### Configuration file name

_No response_

### Configuration

_No response_

### Current and expected behavior

The `string` type annotation on the function parameter should still exist in the returned AST, but it does not. The output parameter AST from the code above is just this:

```jsonc
{ type: 'Identifier', name: 'bar' }
```

Doing the same thing using a non-syntactic placeholder returns this more complete parameter instead, which is expected:

```jsonc
{
  type: 'Identifier',
  name: 'bar',
  typeAnnotation: {
    type: 'TSTypeAnnotation',
    typeAnnotation: { type: 'TSStringKeyword', loc: undefined },
    loc: undefined
  }
}
```

### Environment

System:

- OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish) [Windows 11 + WSL2]

Binaries:

- Node: 20.13.0 - ~/.nvm/versions/node/v20.13.0/bin/node
- npm: 10.8.1 - ~/.nvm/versions/node/v20.13.0/bin/npm

npmPackages:
- @babel/core: ^7.25.2 => 7.25.2 
- @babel/generator: ^7.25.6 => 7.25.6 
- @babel/parser: ^7.25.6 => 7.25.6 
- @babel/plugin-syntax-import-attributes: ^7.25.6 => 7.25.6 
- @babel/plugin-syntax-typescript: ^7.25.4 => 7.25.4 
- @babel/template: ^7.25.0 => 7.25.0 
- @babel/traverse: ^7.25.6 => 7.25.6 
- @babel/types: ^7.25.6 => 7.25.6 
- babel-plugin-istanbul: ^7.0.0 => 7.0.0

### Possible solution

_No response_

### Additional context

I have patched my local copy of babel with the fix in https://github.com/babel/babel/pull/16903 to get past another issue (which worked). This behavior is consistent both with and without that patch.

### PR DESCRIPTION
**Pull request by liuxingbaoyu**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #16904 
| Patch: Bug Fix?          | √
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

File: packages/babel-types/src/clone/cloneNode.ts [hunk 1]
```diff
@@ -85,6 +85,34 @@ function cloneNodeInternal<T extends t.Node>(
...
   } else {
+    if (type === "Placeholder") {
+      // @ts-expect-error undocumented
+      if (hasOwn(node, "optional") && typeof node.optional === "boolean") {
+        // @ts-expect-error undocumented
+        newNode.optional = node.optional;
+      }
+
+      if (hasOwn(node, "typeAnnotation")) {
+        newNode.typeAnnotation = deep
```
Comment (nicolo-ribaudo) [inline packages/babel-types/src/clone/cloneNode.ts:96]: Can we declare these various extra properties in the type definitions of Placehodler?

Comment (liuxingbaoyu) [reply packages/babel-types/src/clone/cloneNode.ts:96]:
```
export const PLACEHOLDERS = [
  "Identifier",
  "StringLiteral",
  "Expression",
  "Statement",
  "Declaration",
  "BlockStatement",
  "ClassBody",
  "Pattern",
] as const;
```
I'm afraid there are other properties that should be here, which would result in a large number of properties in the `Placehodler` type definition.
However, I haven't thought of a better way so far.

Comment (nicolo-ribaudo) [reply packages/babel-types/src/clone/cloneNode.ts:96]: Can they, though? For example, a placeholder will never have a `.body` because it's "inside" the node.

The identifier properties are special because they are not really _inside_ the identifier, so they are not hidden by the placeholder.

**Review by nicolo-ribaudo — APPROVED** [review]
Approving assuming that CI will be green

**Review by JLHwung — APPROVED** [review]
