### PR TITLE
Fix recursive async function expressions

### LINKED ISSUE #8783: Recursion within async functions
## Bug Report

**Current Behavior**
When trying to upgrade to Babel 7. Calling async function from within self-invoking function now causes `ReferenceError: poll is not defined`.

**Input Code**
```js
(async function poll() {
  console.log(await Promise.resolve('Hello'))
  setTimeout(poll, 1000);
})();
```
**Transformed Code**
```js
(function () {
  var _poll = _asyncToGenerator(
  /*#__PURE__*/
  regeneratorRuntime.mark(function _callee() {
    return regeneratorRuntime.wrap(function _callee$(_context) {
      while (1) {
        switch (_context.prev = _context.next) {
          case 0:
            _context.t0 = console;
            _context.next = 3;
            return Promise.resolve('Hello');

          case 3:
            _context.t1 = _context.sent;

            _context.t0.log.call(_context.t0, _context.t1);

            setTimeout(poll, 1000);

          case 6:
          case "end":
            return _context.stop();
        }
      }
    }, _callee, this);
  }));

  return function poll() {
    return _poll.apply(this, arguments);
  };
})()();
```

**Error**
```js
Applications.js:64 Uncaught (in promise) ReferenceError: poll is not defined
    at _callee$ (Applications.js:64)
    at tryCatch (runtime.js:62)
    at Generator.invoke [as _invoke] (runtime.js:296)
    at Generator.prototype.(anonymous function) [as next] (webpack:///./node_modules/regenerator-runtime/runtime.js?:114:21)
    at asyncGeneratorStep (Applications.js:19)
    at _next (Applications.js:21)
```

**Expected behavior/code**
Recursively calls async function.

**Babel Configuration (babel.config.js, webpack.config.js)**

```js
module.exports = function (api) {
    api.cache(true)
    const presets = [ '@babel/preset-env', '@babel/preset-react' ];
    const plugins = [ '@babel/plugin-proposal-class-properties' ];
  
    return {
      presets,
      plugins
    };
  }
```

Using @babel/polyfill in webpack.config.js
```js
entry: {
  react: ['@babel/polyfill', './index.js']
},
```

**Environment**
- Babel version(s): v7.0.0
- Node/npm version: v8.9.0
- OS: OSX 10.12.6
- Monorepo: no
- How you are using Babel: loader

**Additional context/Screenshots**
screen shot 2018-09-28 at 12 33 51

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #8783 
| Patch: Bug Fix?          | :+1: 	
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

### CODE REVIEW

File: packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/named-expression/output.js [hunk 1]
```diff
@@ -5,7 +5,9 @@ function () {
     console.log(bar);
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-transform-async-to-generator/test/fixtures/async-to-generator/named-expression/output.js]: We even had a test for this :man_facepalming:
