### PR TITLE
fix: tagged template incorrect receiver

### LINKED ISSUE #13366: [Bug]: Tagged template with strict private field/method tag has incorrect receiver
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

Programmatic API (`babel.transform`, `babel.parse`)

### Input code

While scanning the recent esbuild commits, I noticed https://github.com/evanw/esbuild/commit/f66b586923e2e4569155e758b57bae9d473c7d8f. Essentially, Tagged Template Literals are a special form of function invocation, and we need to preserve the `this` receiver when invoking:

[REPL](https://babeljs.io/repl/#?browsers=Chrome%2075&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=MYGwhgzhAEBiD29oG8BQ1oGIAuYDmAFAJQrobQBOAptgK4UB202AFgJYQDcZAvqmcHgMI2CrWDZ4FYqXLRBw7JSrAqbAG5UK0ALzN2EAHQ58AA1x48VACbMqAWwAO4bFVPc5CiPBBVDkCC1sAmpVDS1dHT1WDiIPaD4-BioAdzhEYk4gA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=true&targets=&version=7.14.1&externalPlugins=)

```js
class Foo {
  #tag() {
    return this;
  }

  constructor() {
    const receiver = this.#tag`tagged template`;
    console.assert(receiver === this);
  }
}
new Foo();
```

### Configuration file name

babel.config.json

### Configuration

```js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "shippedProposals": true,
        "targets": {
          "chrome": "75"
        }
      }
    ]
  ]
}
```

### Current and expected behavior

Currently, the `this.#tag` is transformed into `_classPrivateMethodGet(this, _tag, _tag2)`. The return value from `_classPrivateMethodGet` (which is `_tag2`, the transformed `#tag` method) is then invoked via Tagged Template:

```js
const receiver = _classPrivateMethodGet(this, _tag, _tag2)`tagged template`;
```

In this case, the receiver is `undefined`, which fails the assertion.

```js
console.assert(receiver === this); // Failure, receiver is undefined
```

### Environment

Babel v7.14.1

### Possible solution

When we're transforming a private access in the `tag` of a Tagged Template Literal, we need to bind the value to the correct receiver:

```diff
- const receiver = _classPrivateMethodGet(this, _tag, _tag2)`tagged template`;
+ const receiver = _classPrivateMethodGet(this, _tag, _tag2).bind(this)`tagged template`;
```

Where this is done is a bit confusing. Transforming is done via [`transformPrivateNamesUsage`](https://github.com/babel/babel/blob/b1f57e5fb58f7e890b3be58965e014f6fd4950e0/packages/babel-helper-create-class-features-plugin/src/fields.js#L409-L436), which calls an abstract [`memberExpressionToFunctions`](https://github.com/babel/babel/blob/b1f57e5fb58f7e890b3be58965e014f6fd4950e0/packages/babel-helper-member-expression-to-functions/src/index.ts#L477-L483) transformer. `memberExpressionToFunctions` will call several "handler" functions, which are defined in [privateNameHandlerSpec](https://github.com/babel/babel/blob/b1f57e5fb58f7e890b3be58965e014f6fd4950e0/packages/babel-helper-create-class-features-plugin/src/fields.js#L186-L370).

Currently, the ``` this.#tag`template literal` ``` is invoking the [`get` handler](https://github.com/babel/babel/blob/b1f57e5fb58f7e890b3be58965e014f6fd4950e0/packages/babel-helper-create-class-features-plugin/src/fields.js#L209-L265). This fails to preserve the `this` receiver once transformed. Luckily, there's a similar handler called [`boundGet`](https://github.com/babel/babel/blob/b1f57e5fb58f7e890b3be58965e014f6fd4950e0/packages/babel-helper-create-class-features-plugin/src/fields.js#L267-L274) which will preserve the receiver.

We actually just need to fix the `memberExpressionToFunctions` implementation to detect when the `get` is happening inside a Tagged Template's `tag`. In this case, we need to call `boundGet` instead of `get`. Specifically this line: https://github.com/babel/babel/blob/b1f57e5fb58f7e890b3be58965e014f6fd4950e0/packages/babel-helper-member-expression-to-functions/src/index.ts#L465-L466

We'll also need

### Additional context

This also needs to be applied when transforming a private field, not just a private method:

```js
class Foo {
  #tag() {
    return this;
  }
  
  #tag2 = this.#tag;

  constructor() {
    const receiver = this.#tag`tagged template`;
    console.assert(receiver === this);

    const receiver2 = this.#tag2`tagged template`;
    console.assert(receiver2 === this);
  }
}
new Foo();
```

### PR DESCRIPTION
**Pull request by sag1v**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #13366  
| Patch: Bug Fix?          | 👍
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | 👍
| Documentation PR Link    | 
| Any Dependency Changes?  |
| License                  | MIT

<a href="https://gitpod.io/#https://github.com/babel/babel/pull/13395"></a>

### CODE REVIEW

File: packages/babel-plugin-proposal-class-properties/test/fixtures/private/tagged-template-static/exec.js [hunk 1]
```diff
@@ -0,0 +1,17 @@
+class Foo {
+    static #tag() {
+      return this;
+    }
+    
+    static #tag2 = () => this
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-proposal-class-properties/test/fixtures/private/tagged-template-static/exec.js:6]: Here we are not testing the receiver, since arrow functions always get `this` from the definition context and not depending on how they are called. We should use this instead:
```suggestion
    static #tag2 = function () { return this };
```

File: packages/babel-plugin-proposal-class-properties/test/fixtures/private/tagged-template-static/exec.js [hunk 2]
```diff
@@ -0,0 +1,17 @@
...
+    static getReceiver() {
+        return this.#tag``;
+    }
+      
+    static getReceiver2() {
+        return this.#tag2``;
+    }
+}
+  
+expect(Foo.getReceiver()).toBe(Foo.getReceiver2());
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-proposal-class-properties/test/fixtures/private/tagged-template-static/exec.js:17]: In this test we don't need also the private method, we can just compare the receiver with what we expect:
```suggestion
expect(Foo.getReceiver2()).toBe(Foo);
```

otherwise the test will pass even if both are broken (for example, if both return `undefined`).

File: packages/babel-plugin-proposal-class-properties/test/fixtures/private/tagged-template-static/options.json [hunk 3]
```diff
@@ -0,0 +1,13 @@
...
+        "@babel/preset-env",
+        {
+          "shippedProposals": true,
+          "targets": {
+            "chrome": "75"
+          }
+        }
+      ]
+    ]
+  }
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-proposal-class-properties/test/fixtures/private/tagged-template-static/options.json:13]: Could you try this instead? Ideally we should only compile private fields and methods, but for some reason it's also compiling classes

```suggestion
{
  "plugins": [
    "proposal-class-properties",
    "proposal-private-methods",
  ]
}
```

File: packages/babel-plugin-proposal-private-methods/test/fixtures/private-method/tagged-template/input.js [hunk 4]
```diff
@@ -0,0 +1,6 @@
+class Foo {
+  #tag() {
+    return this;
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-proposal-private-methods/test/fixtures/private-method/tagged-template/input.js:3]:
```suggestion
    this.#tag``;
```

This `input.js` test is needed to check how Babel is compiling tagged template literals, so we have to use a template literal in the code.

File: packages/babel-plugin-proposal-private-methods/test/fixtures/static-accessors/tagged-template/exe.js [hunk 5]
```diff
@@ -0,0 +1,11 @@
+class Foo {
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-proposal-private-methods/test/fixtures/static-accessors/tagged-template/exe.js:1]: I don't think we need tests for accessors, since tagged templates are specifically about the call behavior and not about how the tag is obtained.

**Comment by sag1v** [comment]
@nicolo-ribaudo Thanks for the comments.

General question, Can i create a new commit (fixing review) and push to this PR or do i must keep it with a single commit (using commit --amend with force push)?

File: packages/babel-helper-member-expression-to-functions/src/index.ts [hunk 6]
```diff
@@ -462,8 +462,13 @@ const handle = {
       return;
     }
 
-    // MEMBER   ->   _get(MEMBER)
-    member.replaceWith(this.get(member));
+    if (t.isTaggedTemplateExpression(parent)) {
```
Comment (jridgewell) [inline packages/babel-helper-member-expression-to-functions/src/index.ts:465]: Nit:
```suggestion
    if (parentPath.isTaggedTemplateExpression()) {

File: packages/babel-plugin-proposal-class-properties/test/fixtures/private/tagged-template-static/exec.js (hunk 1 above)
Comment (sag1v) [reply packages/babel-plugin-proposal-class-properties/test/fixtures/private/tagged-template-static/exec.js:6]: Ops miss that one

File: packages/babel-plugin-proposal-class-properties/test/fixtures/private/tagged-template-static/exec.js (hunk 2 above)
Comment (jridgewell) [reply packages/babel-plugin-proposal-class-properties/test/fixtures/private/tagged-template-static/exec.js:17]: Yup. Let's break this into two `expect` calls, each asserting that the return is `Foo`.

File: packages/babel-plugin-proposal-private-methods/test/fixtures/accessors/tagged-template/exec.js [hunk 7]
```diff
@@ -0,0 +1,16 @@
...
+      return this.#tag``
+  }
+
+  publicGetPrivateTagMethod(){
+      return this.#privateTagMethod
+  }
+}
+const instance = new Foo();
+
+expect(instance === instance.publicGetPrivateTagMethod()).toEqual(true)
```
Comment (jridgewell) [inline packages/babel-plugin-proposal-private-methods/test/fixtures/accessors/tagged-template/exec.js:16]: Instead of asserting `true`, let's assert that the method returns `instance`.

**Review by jridgewell — CHANGES_REQUESTED** [review]

**Comment by jridgewell** [comment]
It's fine to add as many commits as needed to this PR.

File: packages/babel-plugin-proposal-class-properties/test/fixtures/private/tagged-template-static/input.js [hunk 8]
```diff
@@ -0,0 +1,15 @@
+class Foo {
+    static #tag() {
+      return this;
+    }
+    
+    static #tag2 = () => this
```
Comment (sag1v) [inline packages/babel-plugin-proposal-class-properties/test/fixtures/private/tagged-template-static/input.js:6]: I will fix this arrow function as well

**Comment by sag1v** [comment]
@nicolo-ribaudo @jridgewell I pushed the new changes per your comments

**Comment by sag1v** [comment]
@nicolo-ribaudo / @jridgewell Are we done here? :)

File: packages/babel-plugin-proposal-class-properties/test/fixtures/private/tagged-template-static/exec.js [hunk 9]
```diff
@@ -0,0 +1,18 @@
+class Foo {
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-proposal-class-properties/test/fixtures/private/tagged-template-static/exec.js:1]: We don't need to test for private methods here, since we already test them in `packages/babel-plugin-proposal-private-methods/test/fixtures/private-static-method/tagged-template/exec.js`. This test can be simplified to
```js
class Foo {
  static #tag = function () { return this };

  static getReceiver() {
    return this.#tag``;
  }
}

expect(Foo.getReceiver()).toBe(Foo);
```

The same applies for `input.js`, and for `packages/babel-plugin-proposal-class-properties/test/fixtures/private/tagged-template/`.

File: packages/babel-plugin-proposal-class-properties/test/fixtures/private/tagged-template/input.js [hunk 10]
```diff
@@ -0,0 +1,8 @@
+class Foo {
+    #tag() {
+      return this;
+    }
+    
+    #tag2 = this.#tag;
+  }
+  new Foo();
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-proposal-class-properties/test/fixtures/private/tagged-template/input.js:8]: Here we are not testing tagged templates, could you rewrite it to something like this?

```js
class Foo {
  #tag;

  test() {
    this.#tag``;
  }
}
```

File: packages/babel-plugin-proposal-private-methods/test/fixtures/accessors/tagged-template/exec.js [hunk 11]
```diff
@@ -0,0 +1,16 @@
+class Foo {
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-proposal-private-methods/test/fixtures/accessors/tagged-template/exec.js:1]: We don't need this test, since
```js
this.#tag``
```
is a private method and not an accessor (and we already test private methods in another field)

File: packages/babel-plugin-proposal-private-methods/test/fixtures/static-accessors/tagged-template/input.js [hunk 12]
```diff
@@ -0,0 +1,9 @@
+class Foo {
+    static #tag() {
+      return this;
+    }
+  
+    static get privateTagMethod() {
+      return this.#tag``;
```
Comment (nicolo-ribaudo) [inline packages/babel-plugin-proposal-private-methods/test/fixtures/static-accessors/tagged-template/input.js:7]: We don't need this test for the same reason as above.

**Review by nicolo-ribaudo — COMMENTED** [review]
I left a few more comments about tests; apart from them it looks good :+1:

File: packages/babel-plugin-proposal-private-methods/test/fixtures/accessors/tagged-template/exec.js [hunk 13]
```diff
@@ -0,0 +1,10 @@
...
+  get #tag() {
+    return () => this;
```
Comment (jridgewell) [inline packages/babel-plugin-proposal-private-methods/test/fixtures/accessors/tagged-template/exec.js:3]: I screwed this up. It should be `return function() { return this };`, since an arrow function will only return the `this` context from the `get #tag`, not the invocation of the returned function.
```suggestion
    return function() { return this; };
```

File: packages/babel-plugin-proposal-private-methods/test/fixtures/accessors/tagged-template/input.js [hunk 14]
```diff
@@ -0,0 +1,7 @@
+class Foo {
+  get #tag() {
+    return () => this;
+  }
```
Comment (jridgewell) [inline packages/babel-plugin-proposal-private-methods/test/fixtures/accessors/tagged-template/input.js:4]: Seems we dropped the tagged template:
```suggestion
  }
  
  constructor() {
    this.#tag``;
  }
```

File: packages/babel-plugin-proposal-private-methods/test/fixtures/static-accessors/tagged-template/input.js [hunk 15]
```diff
@@ -0,0 +1,10 @@
+class Foo {
+  static get #tag() {
+    return () => this;
```
Comment (jridgewell) [inline packages/babel-plugin-proposal-private-methods/test/fixtures/static-accessors/tagged-template/input.js:3]:
```suggestion
    return function() { return this; };
```

**Review by jridgewell — COMMENTED** [review]
Sorry, just a few more comments (that I screwed up). If you can make these changes, run update the tests one last time, this should be good to merge.

**Comment by sag1v** [comment]
@jridgewell Thanks, done.

**Review by jridgewell — APPROVED** [review]

**Review by JLHwung — APPROVED** [review]

**Review by existentialism — APPROVED** [review]
👍
